### ISSUE TITLE
AttributeError: module 'acme.fields' has no attribute 'rfc3339'

### ISSUE THREAD

**Issue by halhwadi** [certbot/certbot#10038]
Im trying to renew SSL certificate and have upgraded the certbot to latest version 2.11.0

when run this command `sudo certbot certificates`  I got this error:

File "/usr/lib/python3/dist-packages/certbot/_internal/account.py", line 57, in Meta
    creation_dt: datetime.datetime = acme_fields.rfc3339("creation_dt")
AttributeError: module 'acme.fields' has no attribute 'rfc3339'

Operation system unbto:
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
 python: 3.0 and 3.9

**Comment by osirisinferi** [comment]
How did you install Certbot and what's the version of the `acme` library on your system?

Because the `acme.fields.rfc3339` method was [added back in version 1.23.0](https://github.com/certbot/certbot/commit/dac0b2c187fd94de9725da623587729ef356b60d#diff-90f4a9727dae2c058855915d2d9560b4b2f45c96f670d89c3206e9f3938e8ecfR75-R77) already and has been there till today.

**Comment by halhwadi** [comment]
Thanks for your response  issue has been resolved when upgrading Certbot and acme libraries
