### ISSUE TITLE
Implement flags to control: security parameters in general, ciphersuites in particular, and autoupdating of those things

### ISSUE THREAD

**Issue by pde** [certbot/certbot#1123]
At the moment, we tweak ciphersuites during `install` but not afterwards.  Arguably the renewal script, when it runs on a daily basis, should check for changes to best practices and auto deploy them.

Users should be able to control several aspects of this:
- Do they get ciphersuites optimised for compatibility, for security, a tradeoff betewen those, or in accordance with a specific project's recommendations (Mozilla/Bulletproof TLS/etc)
- Do they get other security features optimised for compatibility, for security, or a tradeoff?
- Are changes to these things automatically applied after a client update, or only at manual sys admin request?

I believe the default for each of these things should be tradeoff, tradeoff, and automatic.  And those defaults should be documented.

**Comment by pde** [comment]
We do need some level of notification to the user that automation is the default.  I think the right place to do that is in a post-execution note, probably the same one that tells them that autorenewal is active.

**Comment by pde** [comment]
See also #624.

**Comment by rugk** [comment]
See also the thread about this in the LE community: [Does the LE client (automatically) update the TLS config/cipher list if a vulnerability is found?](https://community.letsencrypt.org/t/does-the-le-client-automatically-update-the-tls-config-cipher-list-if-a-vulnerability-is-found/1981)

**Comment by schoen** [comment]
According to my PR #1261 we should have 3 options at launch (`mozilla-secure`, `mozilla-intermediate` [default], and `mozilla-old`) with respect to the ciphersuites, and we should check periodically whether the strings in our code are up-to-date with Mozilla's recommendations. People can also lobby us to add other ciphersuite setting strings if they can make a case that there is a reasonably large population that would use them.

**Comment by jvehent** [comment]
@schoen: Would it help if we provided the mozilla recommendations in JSON format published at a stable location? We're talked about it a few times, and letsencrypt would be a strong enough incentive to act on it :)

**Comment by pde** [comment]
@jvehent If the JSON format mapped to Nginx / Apache configuration options, I think that would be quite useful.  We could then land a unit test to ensure that what we have matches what Mozilla currently publishes.

**Comment by pde** [comment]
When closing this ticket, read #1401.

**Comment by jvehent** [comment]
As a follow-up, v4 of the Mozilla guidelines is now available in JSON format: https://statics.tls.security.mozilla.org/server-side-tls-conf-4.0.json

We won't modify this file. We will bump the version into another file in the future. I intentionally did not provide a "latest" file by fear of people mapping to it and breaking their configuration when we push a new version.

**Comment by osirisinferi** [comment]
@jvehent But how would a fully automated system (like Let's Encrypt is supposed to be) know there's an update? "Manually" check for ...-4.1, 4.2 or 5.0?

I understand your reasoning, but for a fully automated system a "current version" file that *is* updated would be required, don't you think?

**Comment by schoen** [comment]
I'm not sure whether this is the best issue for this, but I think the urgency of having some kind of ciphersuite-setting command (maybe not an automated one but just a manual one) has just increased because, following the creation of the X3 intermediate, it's now going to be the last thing blocking some users from achieving Windows XP client compatibility.

https://community.letsencrypt.org/t/upcoming-intermediate-changes/13106/3

**Comment by My1** [comment]
@jsha recommended Mozilla's old setting but personally I just say "HELL NO!"
(https://community.letsencrypt.org/t/upcoming-intermediate-changes/13106/4)
reasing is this:
I would personally say that generally some high settings should be used as default (TLS1.0+ and AES and if possible PFS) with a flag for XP which enables TLS_RSA_WITH_3DES_EDE_CBC_SHA (also called DES-CBC3-SHA) which is pretty much the only remaining safe cipher for anything on XP except Firefox which as we might know, has it's own TLS security stuff and therefore can run even the highest security settings on XP.

also unless you are going for IE6 support (which you really shouldnt because if they are using IE at least keep it up to date) SSL3 can stay off.

as it seems the 3des cipher above is already in the intermediate so for chrome and IE8 on XP this should be enough.

but for everyone who is on an SNI host (and has therefore lost IE and chrome on XP anyway) an a bit tweaked version of the modern set would be intresting that supports a bit more androids (modern does Android 5+ which is a bit too new...) but 4.1 has AES support so that should work out pretty well.

**Comment by jsha** [comment]
@My1: I appreciate your analysis, but please find a more polite way to express it. In particular, "hell no" is a really rude phrase. Note that you can edit comments in GitHub if you decide to rephrase.

Thanks,
Jacob

**Comment by My1** [comment]
well sorry if I was a bit too straightforward but it hurts when a security-centered company (nonprofit or not doesnt matter) recommends really bad stuff.

SSL3, a dhparam of 1024 this is literally asking to get hacked (while I dunno whether 1024 dh has been cracked in practice, I sure know that SSL3 is down, ya know poodle and stuff)

**Comment by jsha** [comment]
>  it hurts when a security-centered company (nonprofit or not doesnt matter) recommends really bad stuff.

It doesn't matter how bad you think the recommendation was. The rule from the forum is "be kind, even when you disagree," and that applies here as well. It's very important that we maintain a civil community that is welcoming to everyone. As part of that community, it is your responsibility too.

**Comment by My1** [comment]
well I usually try to and I dont wanna use it as an excuse but sometimes my asperger makes me fail certain social stuff.

**Comment by rugk** [comment]
> 1024 dh has been cracked in practice

It is [very likely](https://freedom-to-tinker.com/blog/haldermanheninger/how-is-nsa-breaking-so-much-crypto/). At least for nation-state attackers.

**Comment by My1** [comment]
then this hurts even more.

**Comment by jvehent** [comment]
Administrators should target the intermediate configuration and consider the modern one. Only in very specific instances should they use the old configuration, and when doing so, be aware that their clients are so outdated and broken that https most likely provides no security.

Debating the security of DHE when needing to support Windows XP users is unnecessary.

**Comment by pde** [comment]
Discussing this with @schoen and @sagi, we realised that this setting will need some novel handling machinery to ensure that it stays safely in a renewal config file even if the user renews manually with the `certonly` verb.  There's a draft of that implemented in [the var-preservation-for-1123 branch](https://github.com/certbot/certbot/tree/var-preservation-for-1123).

**Comment by pde** [comment]
Our fix for the first part of this may also close: #3328

**Comment by pde** [comment]
@SwartzCr I don't think this is a low priority ticket. Getting our UI and UX narrative for security enhancements sorted out is a final blocker for calling Certbot 1.0 IMO.

**Comment by pde** [comment]
The reasoning for this is: in the future, we may want Certbot to support fast deployment of config changes to mitigate newly announced TLS vulnerabilities. But we should only do that if users had a clear onboarding experience to opt in to that. So getting our security UI right feels like a blocker for calling Certbot "out of beta".

**Comment by SwartzCr** [comment]
Oh sorry.
This was actually just me misinterpreting the security-low label. When I did the label rename I also tried to remove labels that looked like they weren't being used, with confusing names - security-low was one of those. Glad you removed the mistaken low priority & feel free to recreate a security-low label if you feel that it's needed.

**Comment by pde** [comment]
@SwartzCr the purpose of "security-low" was, "this is a security related bug, but not an urgent thing that might be a vulnerability".

**Comment by bmw** [comment]
With the creation of the more specific issue #4830, I think this issue can be closed. To respond to each of the original points:

> Users should be able to control several aspects of this:
>
> * Do they get ciphersuites optimised for compatibility, for security, a tradeoff betewen those, or in accordance with a specific project's recommendations (Mozilla/Bulletproof TLS/etc)

As suggested in the original post, we went with a tradeoff using [Mozilla's intermediate configuration](https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility_.28default.29).

I think the majority of the Certbot team disagrees that users should be able to control this through the Certbot UI though. Choosing things like ciphersuites is a complicated decision that most users probably shouldn't be making. Additionally as a more minor point, it adds extra complexity to Certbot with little benefit to most users.

Instead, Certbot provides a sane default configuration which users can tweak as the desire outside of Certbot. The way this interacts with automatically the configuration is explained below.

> * Do they get other security features optimised for compatibility, for security, or a tradeoff?

This is the purpose of #4830.

> * Are changes to these things automatically applied after a client update, or only at manual sys admin request?

Since Certbot 0.15.0, the way this works in both the Apache and Nginx plugin is the SSL/TLS configuration is placed in Certbot's configuration directory (`/etc/letsencrypt` by default). When Certbot is updated, Certbot checks whether this file has been modified by the user. If it has, Certbot explains that it cannot safely automatically update your configuration and prints/logs the location of the new file which the user can use as a reference when manually updating their configuration. If it has not been modified by the user, Certbot updates the file. This allows experienced sysadmins to tweak settings to their hearts content while still providing security updates to the majority of Certbot's users.

With that said, I'm closing this issue. If anyone strongly disagrees, please explain why and I'll consider reopening.

**Comment by reillychase** [comment]
It's 2020 and we still need an option to disable TLS 1.0 and 1.1 without having to change a file and manually merge in all future updates. It's a PCI compliance issue now.

**Comment by bmw** [comment]
In 2019 shortly after Mozilla updated their recommendations, we also started disabling TLS 1.0 and 1.1. You have an old version of Certbot. If you need help getting a new one, see https://certbot.eff.org/instructions or https://community.letsencrypt.org/.

**Comment by reillychase** [comment]
Thanks @bmw! If I update my certbot hopefully it will fix this.
