### ISSUE TITLE
Move strings out of raw Python to facilitiate l10n

### ISSUE THREAD

**Issue by pde** [certbot/certbot#115]
Currently the client code has built-in English Python strings.  These should be switched to [gettext](https://docs.python.org/2/library/gettext.html) or equivalent to facilitate internationalisation.

**Comment by ThomasWaldmann** [comment]
gettext usually means _("example"). did you mean that by "move strings out of raw python"?

**Comment by pde** [comment]
Ah, yes. I've actually never translated Python before; that's a nice design.

**Comment by ThomasWaldmann** [comment]
As a general note maybe: for a quickly changing project (with maybe a quick release cycle at some time), translations are sometimes a bit problematic as you need quite some eager translators who keep the stuff updated. If they are slow/busy/unmotivated, you have to release with incomplete translations...

Also, sometimes translations are worse than original texts. I am a native German, but I usually set language to English so that I don't have to read the hard to understand translations.

IF i18n is started at some time, I suggest using transifex and gettext / .po/mo files.

**Comment by pde** [comment]
Agree with all of that -- we use transifex for several other projects at EFF.  Once this bug is done we can push the strings there.

**Comment by ThomasWaldmann** [comment]
Hmm, shall we close this one?

reasons:
a) not a good time for i18n now, see above
b) issue title misleading
c) maybe no i18n at all? admins are usually pretty happy with english (and sometimes even rather unhappy with translations to their native language).

**Comment by jsha** [comment]
Ping on this - should we start working on localization soon?

**Comment by jsha** [comment]
Closing for now. Maybe we'll want to revisit after the CLI UI overhaul.
