### ISSUE TITLE
Standalone could choose challenge based on available ports

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#1164]
As suggested by @pde, the `standalone` authenticator could choose the challenge type based on available ports. For example, if port 80 is bound but port 443 is free, try `dvsni`.

**Comment by IzzySoft** [comment]
I've thought I could work around this using the `--http-01-port` / `--dvsni-port` parameters. But while that fired up the *local* servers on the correct ports, challenges came in on ports 80 resp. 443 regardless of what ports specified – so please make sure this gets fixed along the lines :)

Please consider that it's not always an option to shutdown the "master server" for cert renewal/request – especially with many VHosts being involved, and `letsencrypt-auto` checking for updates on each call, this could mean several minutes runtime/downtime. Also, if run via a cron job: if something fails and Apache doesn't start up anymore (think e.g. of a "broken cert file"), that's real critical – while when a "reload" fails, Apache keeps running (with the old config) and the admin gets mailed. Better chances to fix that this way – then to have a 3 day downtime because the admin was "out of office" ;)

**Comment by bmw** [comment]
Standalone only supports one challenge type so I'm closing this.
