### ISSUE TITLE
Bundle cert and privkey (lighttpd)

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#1201]
https://github.com/letsencrypt/letsencrypt/issues/1190#issue-114027075 - apparently lighttpd requires single file with both private and public key...

**Comment by kuba** [comment]
Reporter was wrong. According to http://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_SSL#Configuration it's a "PEM file for SSL support (Should contain both the private key and the certificate)".

**Comment by kuba** [comment]
I find docs pretty confusing:
```
ssl.pemfile	path to the PEM file for SSL support (Should contain both the private key and the certificate)
ssl.ca-file	path to the CA file for support of chained certificates
```

What goes where?

**Comment by kuba** [comment]
Me thinks `ssl.pemfile == cert.pem + privkey.pem`, `ssl.ca-file == chain.pem`

**Comment by tohn** [comment]
@kuba That's correct :)

**Comment by charno** [comment]
FYI: My workaround is simple: `$ cat /etc/letsencrypt/live/<domain>/privkey.pem /etc/letsencrypt/live/<domain>/cert.pem > /etc/letsencrypt/live/<domain>/combined.pem`, lighttpd.conf is 
`ssl.pemfile = "/etc/letsencrypt/live/<domain>/combined.pem"
ssl.ca-file = "/etc/letsencrypt/live/<domain>/chain.pem"`

**Comment by josch** [comment]
pound and ejabberd also require private key and cert in the same file

**Comment by bwesterb** [comment]
How to fix this?  Add a fourth file managed by `letsencrypt.storage`?

**Comment by kuba** [comment]
Simplest solution is add a fourth file. However, I don't think we should do that, because there are more configurations that we need to support  (we now know of at least #1250, #1276) and managing all those will be a nightmare. My idea was to create a new installer plugin that does that instead. Design decision needs to be taken before any work on those issues is started.

**Comment by nitmir** [comment]
pure-ftpd (like ejabberd as @josch said and like #1250 ) need one single file contening key + cert + chain
Using cat to build it is only prone to forget to do it again at each auto renewal.

**Comment by nitmir** [comment]
As a small hack, I put the code below in a daily cron : 
```
#!/bin/bash
for dir in $(ls -d /etc/letsencrypt/live/*); do
    cat $dir/privkey.pem $dir/fullchain.pem > $dir/fullkeychain.pem
done
```

**Comment by cweiske** [comment]
`courier-imapd-ssl` also requires the public key and the private key in a single file.

**Comment by mjrider** [comment]
haproxy also likes to have a combined file with the contents of fullchain.pem and privkey.pem
@kuba a 'custom' installer plugin which runs a (in the config ) provided script could fix the whole everybody has a different environment problem. And would make installation automation easier to integrate mass hosting configurations where generic apache/nginx configuration mutations are not an option.

**Comment by pde** [comment]
I fear that despite the inelegance of adding four more files in the `live/` directory, perhaps we should do that (and also make sure we add a README file at the same time, saying which ones are appropriate for which software).

Part of the reason is that rather than stub installers that spit out certs and chains in funny formats, what we really want is installer plugins for  `haproxy`, `courier-imapd-ssl`, `pure-ftpd` etc.  And we'll be happier if in general those installers don't need to be re-run with full force at renewal time; there's a lower probability of things going wrong if (say) the `haproxy` daemon can just be reloaded to pick up a new cert file from `/etc/letsencrypt/live/` directory.  But that's only possible if the client handed the `haproxy` plugin a set of files that are sufficient for filling all the necessary lines in the haproxy conf file.

On the other hand, it will suck to have private keys in any of the files in `/etc/letsencrypt/live`.  So maybe this can only work if the formats that have keys in them can go in `/etc/letsencrypt/keys` :(

**Comment by pde** [comment]
A third option: we make all the keyless file formats by default.  For the ones that need keys, there is an *authenticator* ("certonly") flag to request the extra format from storage.py.  Those can have warnings on them saying that they leave keys lying around in `/etc/letsencrypt/live`.  When there's an installer for `haproxy`, using it with `letsencrypt run` can imply the appropriate authenticator setting.

**Comment by pde** [comment]
I like option 3.  @kuba, wdyt?

**Comment by kuba** [comment]
We probably do want `haproxy`, `courier-imapd-ssl`, `pure-ftpd` installers. However, there is no time to implement them now. Having a "swiss-army" installer that spits out various cert/chain/key combinations is the best temporary solution IMHO.

Your third option still seems to require users to manual concat/split files, which is really suboptimal.

**Comment by mjrider** [comment]
fourth option:
having a exec installer which calls a external command in my usecase, it would concat 2 files and place them in /etc/ssl/haproxy/10-domainname.pem and trigger a reload of haproxy, no custom haconfig file changes needed, because haproxy load all the certs in that folder.  
a simple plugin for the installer which just exec's a command and checks if the exit code is 0 shouldn't be that much work

something like: 
exec /path/to/script /path/to/cert.pem /path/to/chain.pem /path/to/privkey.pem

**Comment by NEOatNHNG** [comment]
I would propose that we go for the first option and add more files but modify the code so that it is not so cumbersome to add more formats. This has the advantage that auto-renewal also works for these more exotic formats.

What is the problem with formats containing private keys in `/etc/letsencrypt/live`? We already do that with the `privkey.pem` and it doesn't get worse just because there are multiple files instead of one. If we expect that we will have custom installers for most of the popular software anyway at some time then the additional number of formats is also not a big problem because then the installer would just fill in the right file name.

If we have a swiss-army installer command one would still have to execute that manually on every renewal, right? That doesn't sound like the user friendliest solution to me. On another thought: how do we handle running daemons on certificate renewal anyway? Is there some logic to send a reload to the daemon if it was set up via an installer command?

@mjrider: would haproxy also accept a symlink from `/etc/ssl/haproxy/10-domainname.pem` to `/etc/letsencrypt/live/chainprivkey.pem` assuming `chainprivkey.pem` was a file in the right format?

**Comment by mjrider** [comment]
@NEOatNHNG srry for the delay, the answer is yes

**Comment by martinburger** [comment]
Note: For haproxy, it would be sufficient to have a combined file with the contents of `privkey.pem` and `cert.pem`. It does not require the contents of file `fullchain.pem`.

**Comment by shinji257** [comment]
ZNC actually needs this arrangement.  For that matter I think this may apply to any server coded in python.

With that in mind I found that the private key file for some reason is lacking a new line in it right now so I actually have to do something like this...

cat key.pem <(echo) fullchain.pem > znc.pem

**Comment by Wolf480pl** [comment]
@shinji257 ZNC actually requires privkey, fullchain, and dhparam PEMs all catted together in that order into the znc.pem

**Comment by shinji257** [comment]
@Wolf480pl It is recommended but not required.  The current pem I'm using doesn't include the dh params section although I did generate one on the side when I was working on it at first.

**Comment by kousu** [comment]
@shinji257 , any server? Not true, the core python SSL library uses the split file setup that's easier to handle:
```
                import ssl
                t = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
                t.load_default_certs() # OAuth2 specs that you MUST use TLS, because for simplicity it doesn't do any crypto itself. This is probably a good idea, but it does make testing tricky.
                t.load_cert_chain("localhost.crt","localhost.key")
```

**Comment by shinji257** [comment]
@kousu I'll accept the correction on that.  I've worked with many python based servers that only accepted one file so I made a general educated assumption about it.

**Comment by kousu** [comment]
Well that just proves the bigger point: its so much easier to take one file even when the underlying library can take two that we will never convince everyone to adapt, so letsencrypt must.

**Comment by jmtd** [comment]
I've started working on this.

**Comment by jmtd** [comment]
Ok, I've finally tested what I did in https://github.com/jmtd/letsencrypt/commits/1201-bundle-cert-and-privkey and fixed the test file too. It appears to have worked, at least for how I use certbot (certonly plugin). It is rough around the edges and suggestions for improvement and testing (especially other usage scenarios) would be very welcome

**Comment by jmtd** [comment]
...tests don't actually pass yet though, will keep plugging away

**Comment by jmtd** [comment]
OK the tricky part now is to handle renewals gracefully, where the old bundle didn't have "privkeyandcert". Is there any precedent for this already -- managing a situation where the configuration (dictionary) differs?

I might special-case privkeyandcert so that it doesn't cause a failure if it does not exist, going to see how messy that looks.

**Comment by schoen** [comment]
@jmtd, it's not clear whether we want to continue to track all of the associated archive objects in the renewal configuration file if we add a whole bunch of them (although it does raise a question of how code that uses a certificate lineage should be able to figure out exactly which kinds of objects are being managed by and existing within that lineage). This applies to questions about new private key types too, for example.

**Comment by jmtd** [comment]
@schoen, thanks for the comment. To get this (back) into a working state, I think I'm going to try and make it so that the various consistency checks are permitted to fail for this new archive object if it doesn't exist in a lineage, and see where that leaves us.

**Comment by rimas-kudelis** [comment]
@jtmd: is there any progress with this?

**Comment by jmtd** [comment]
Hi @rimas-kudelis, sorry no, no progress since July. I've gone a bit cold on this, as (IMHO) the certbot code is really hard to work on, and I've "solved" this locally with a shell wrapper, and I might move away from lighttpd anyway... but I haven't completely given up. I'll see if I can pick this back up this week.

**Comment by rimas-kudelis** [comment]
Actually, I'm more interested in a "full" file (#1250).
Anyway, isn't it possible to work around both of these issues with a `renew-hook`? If it is, I wonder if anyone could give me an example of one.

**Comment by bmw** [comment]
@rimas-kudelis, yes it is possible to work around this issue with a `renew-hook`. Such a script might look something like:

```
#!/bin/sh
for domain in $RENEWED_DOMAINS; do
    if [ "$domain" = example.org ]; then
        cat "$RENEWED_LINEAGE/privkey.pem" "$RENEWED_LINEAGE/fullchain.pem" > /desired/path/to/server.pem
        service lighttpd reload
    fi  
done
```

To use this script with Certbot, you'd change your renewal command to something like `certbot renew --quiet --renew-hook /path/to/above/script.sh`. You can include other `if/elif` branches if you want to perform other actions when renewing a different certificate.

**Comment by GigabyteProductions** [comment]
I'm currently using this method to concatenate the files for ejabberd. I think it would help if there was an option to run renew-hook on initial issuance. I'm avoiding an unnecessary --force-renewal by running my hook manually after a certonly call, but it'd suck if I didn't notice a failure in production renewal right away when issuing multiple certificates in different environments like this.

**Comment by moneytoo** [comment]
In my ``cron.daily``:
```
certbot renew --quiet --renew-hook 'systemctl reload nginx postfix dovecot ; chmod 755 /etc/letsencrypt/live && for dir in $(ls -d /etc/letsencrypt/live/*); do cat $dir/privkey.pem $dir/fullchain.pem > $dir/privkeyandcert.pem; done && systemctl restart ejabberd'
```

**Comment by GigabyteProductions** [comment]
I have a renew hook working. I was just adding that there's no option to run the hook on the first run of certbot.

**Comment by jmtd** [comment]
@moneytoo you rotate your LE certs daily?

**Comment by moneytoo** [comment]
@jmtd 
```
certbot renew

This command attempts to renew any previously-obtained certificates that expire in less than 30 days.
...
Since renew only renews certificates that are near expiry it can be run as frequently as you want - since it will usually take no action.
```

**Comment by ethaniel** [comment]
Need this in haproxy!

https://www.digitalocean.com/community/tutorials/how-to-secure-haproxy-with-let-s-encrypt-on-ubuntu-14-04

> Combine fullchain.pem and privkey.pem
> When configuring HAProxy to perform SSL termination, so it will encrypt traffic between itself and the end user, you must combine fullchain.pem and privkey.pem into a single file.

**Comment by Harvie** [comment]
Same problem with courrier... Currently i use this workaround:

`renew_hook = cat /etc/letsencrypt/live/testmail.arachne.cz/privkey.pem /etc/letsencrypt/live/testmail.arachne.cz/fullchain.pem > /etc/letsencrypt/live/testmail.arachne.cz/combined.pem ; systemctl reload-or-try-restart postfix courier`

**Comment by jpgklassen** [comment]
MongoDB requires these two files to be combined too.

**Comment by Harvie** [comment]
This should be very easy to implement. Can't believe, that this issue is open since 2015 :-)

**Comment by kousu** [comment]
On August 26, 2018 8:31:28 PM ADT, Tomas Mudrunka <notifications@github.com> wrote:
>This should be very easy to implement. Can't believe, that this issue
>is open since 2015 :-)

+99

-- 
kousu

**Comment by bmw** [comment]
If someone would like to propose a design and PR for this, please do so! I'd recommend sharing your design first to get feedback before you spend time implementing it.

**Comment by Harvie** [comment]
Related file:
https://github.com/certbot/certbot/blob/master/certbot/crypto_util.py

**Comment by sydneyli** [comment]
Given that the most discussion is on #5087 about this exact issue, I'm closing this one in favor of that one.

**Comment by gstrauss** [comment]
Since lighttpd 1.4.53 (released Jan 2019), lighttpd supports having a separate file for the private key:
```
$SERVER["socket"] == ":443" {
    ssl.engine = "enable"
    ssl.pemfile = "/path/to/site/fullchain.pem"
    ssl.privkey = "/path/to/site/privkey.pem"
}
```
See also comments at end of #94
