### ISSUE TITLE
--install should default to installing whatever certs you got with "letsencrypt certonly"

### ISSUE THREAD

**Issue by pde** [certbot/certbot#1231]
and only demand `--cert-path` and `--key-path` if none of those make sense.

**Comment by kuba** [comment]
I'm not sure if it should do it by default and surprise user. Having `--lineage $domain` that looks up stuff in `/etc/letsencrypt/live/$domain` would be nice.

**Comment by pde** [comment]
If the user just ran "letsencrypt" and the installer errored out, they will be surprised if "letsencrypt install' *doesn't* install the cert they were just given.  I know I was when I first tried it :)

**Comment by bmw** [comment]
We can certainly write some code to be aware of certs that were obtained by the client, but I don't think we should install them without some kind of prompt. I suspect we should do something like:
```
Which names would you like to activate HTTPS for?
-------------------------------------------------------------------------------
1: example.com
2: www.example.com
-------------------------------------------------------------------------------
Select the appropriate numbers separated by commas and/or spaces (Enter 'c' to
cancel):
```

**Comment by nils-ohlmeier** [comment]
When I ran --install with the cert I just had obtained I got a screen which offered me 5 different host names and IPs to use the cert for and all 5 of them were selected. I only had requested a cert for www.mydomain.com, but then ended up selecting www.mydomain.com and mydomain.com as the install targets. When I then select 'secure' instead of 'easy' for the redirects the installer exited with an error that it failed to install the redirect for mydomain.com.
I think would have been helpful to prevent such errors by less experienced users if the domain screen shows all domains and IP addresses the installer found, but selects only the domains for which certs are available (in my case I ran the installer with --cert-path so it should have been very clear to only offer domains from that cert).

**Comment by bmw** [comment]
Thanks for pointing this out @nils-ohlmeier. I created #1482 to track this issue.

**Comment by jpluimers** [comment]
From #3412 :

Currently, `install` won't work without `--cert-path`, `--fullchain-path` or `--key-path` parameters:

```
./certbot-auto install --noninteractive --apache --domains pcm.4delphi.com
```

But `run` (which is the default command) will request and install without any extra parameters:

```
./certbot-auto --noninteractive --apache --domains pcm.4delphi.com
```

And `certonly` will request without any extra parameters:

```
./certbot-auto certonly --noninteractive --apache --domains pcm.4delphi.com
```

So please make `install` as smart as `certonly` or (default) `run` that somehow figure out the correct locations of the certificates.

--jeroen
