### ISSUE TITLE
explicitly disallow messing with config and work dir contents

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#1254]
Exceptions: `/etc/letsencrypt/cli.ini` and renewal config files.

**Comment by SwartzCr** [comment]
I'm pretty sure we're not going to prevent people from moving certs from `/etc/letsencrypt` so I feel like this can safely be closed, @bmw thoughts?

**Comment by bmw** [comment]
I think the purpose of this ticket is to document that you shouldn't modify the config or work directories unless you know what you're doing. There have been dozens of issues about people trying to move things around (e.g. wanting their lineage "www.example.org" to be named "example.org", naively moving things around, and breaking things). I personally think still doing this isn't a bad idea.

**Comment by schoen** [comment]
This is now a README in each `live` directory and will soon be at the top level of `live` itself: https://github.com/certbot/certbot/pull/6377

Maybe we can think of more places to put this because I have a feeling that won't stop people. So I've just opened https://github.com/certbot/certbot/issues/6382 (which might turn out to be a duplicate) for this.
