### ISSUE TITLE
certbot-auto and additional plugins

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#1279]
I would like to see something along the lines of `LE_PIP_PKGS="letsencrypt-nginx git+https://github.com/plesk/letsencrypt-plesk" ./letsencrypt-auto ---configurator plesk`

**Comment by zjs** [comment]
I've taken a look at this ticket, PR #4047, tried to understand the current logic in `letsencrypt-auto.template`, and tried to think about use cases for plugins.

It seems like being able to nuke the `venv` is nice. Starting from a "clean slate" each time makes things easier to test, debug, and reason about. Less persistent state is, I think, preferable.

It also seems like a "one size fits all" solution for plugins may not be tractable, especially if we have a mix of first-party, third-party, and user-specific plugins.

Given this, I propose what I think would be a relatively small change:

Allow people to put scripts in a well-known location relative to the `certbot-auto` script (e.g., `certbot-auto.d/` or `certbot-auto-plugins/`). During phase2, between installing and running, run each script.

To be compatible with `certbot-auto`, plugin authors would simply need to define such a script to install the plugin into the `venv`. This could be anything from a call to `pip` to a command to copy files from elsewhere on the system into the `venv`, whatever is required for the plugin.

For consistency and simplicity, `certbot-auto` can ensure a set of a documented set of environment variables (e.g., `$VENV_BIN`) or even helper functions/aliases (e.g., `pip_install`) are defined when invoking the scripts. In this way, the work required of the plugin author is proportional to how special/unique their plugin's installation process is, without imposing restrictions on that process.

This process means that plugins behave similarly/follow a similar lifecycle to certbot itself when using `certbot-auto`.

This process also means that there is no point of contention when managing plugins; installing/uninstalling plugins is as simple as adding/removing files from a directory.

cc @bmw, @ohemorange

**Comment by ohemorange** [comment]
cc @erikrose

**Comment by bmw** [comment]
More info in #4037.

**Comment by bmw** [comment]
@zjs, thanks for taking a look at this and I'm sorry I didn't respond sooner. I think we have a renewed reason to look into this with all of the DNS plugins. Do we want `certbot-auto` to include all of the DNS plugins by default? I'm happy to create a new issue for this, but the two problems are definitely related and I think it's worth discussing this now as it's much harder to change our decision after we've shipped with certain packages included.

I haven't yet looked at how large these new packages and their dependencies are. Some such as `boto3` for route-53 for AWS are quite large and was roughly 25% of our current venv when I looked a while ago. People run `certbot-auto` on all sorts of devices such as Raspberry Pis, systems with poor internet connections, etc. It might be worthwhile designing a system that allows users to easily specify what plugins they want installed. I think it'll be pretty rare for someone to need multiple DNS plugins on their system. The downside of doing this is it hurts discoverability as we discussed before.

I think the proposal above is pretty good, but there are two potential problems:

1. Users who place the script in something like `/usr/local/bin` might not want to be forced to create a directory at the same location to use other plugins.
2. We'd have to be pretty careful with the permissions on the plugin directories. Since `certbot-auto` uses `sudo` a lot internally and is often run from things like cron/systemd where it may already have root privileges, having sane permissions on these directories and files is very important.

For the purposes of brainstorming, alternatives to scripts could be just a list of python python packages or a pip requirements file. The downside of these approaches is it may not allow hash checking or installation of non-Python dependencies. We could also have users places these things at a predefined location, allow a flag for it to be configurable, or even have the user modify `certbot-auto` itself if it's something simple like a list of packages.

I'm not sure the best approach here but I wanted to reopen this conversation. In the end, it'd be good to get Erik's opinion as he's the author of `certbot-auto` and knows the most about Python packaging but I'm avoiding mentioning him now until we have something we like as I believe he's pretty busy right now.

**Comment by zjs** [comment]
> Do we want certbot-auto to include all of the DNS plugins by default? I'm happy to create a new issue for this, but the two problems are definitely related and I think it's worth discussing this now as it's much harder to change our decision after we've shipped with certain packages included.

Thanks for filing #4767 to track this discussion.

> Users who place the script in something like `/usr/local/bin` might not want to be forced to create a directory at the same location to use other plugins.

We could allow for an optional `--plugins-dir` argument to change where Certbot looks for plugin scripts, with a relative path as the default.

> We'd have to be pretty careful with the permissions on the plugin directories. Since `certbot-auto` uses `sudo` a lot internally and is often run from things like cron/systemd where it may already have root privileges, having sane permissions on these directories and files is very important.

We could follow the convention we established for credentials files and check permissions early, printing warnings as necessary. This should help ensure that users are alerted to the issue when they're first configuring things.

> For the purposes of brainstorming, alternatives to scripts could be just a list of python python packages or a pip requirements file. The downside of these approaches is it may not allow hash checking or installation of non-Python dependencies. We could also have users places these things at a predefined location, allow a flag for it to be configurable, or even have the user modify `certbot-auto` itself if it's something simple like a list of packages.

In addition to the other disadvantages, these also seem to require more design and more work. (Running a directory of scripts is an established pattern and may be as simple as invoking `run-parts` with the right arguments, if it's available on all of the systems we care about.)

**Comment by erikrose** [comment]
setuptools does provide a plugin system called [entry points](https://setuptools.readthedocs.io/en/latest/setuptools.html#dynamic-discovery-of-services-and-plugins) which I've often used to good effect. It's well-supported and considered the normal way of doing Python plugins. It's likely that, whatever custom plugin system we design up front, it will end up expanding over time, making the option of entry points + not obliterating the venv ever more attractive. I hate to keep the venv around, but I also hate to bring a bunch more complexity into the product. Entry points also have the advantage of working on non-Unix OSes.

**Comment by zjs** [comment]
Certbot already uses entry points for discovering and accessing plugins (see, e.g., [disco.py#L194](https://github.com/certbot/certbot/blob/master/certbot/plugins/disco.py#L194)).

I think that pattern works well, and is sufficient for, traditional distribution mechanisms. However, there's a bit lacking when it comes to plugins with `certbot-auto`. 

As you know, `certbot-auto` automatically and continually updates Certbot itself (i.e., `acme`, the core `certbot` package, and "first class" plugins like `certbot-apache` and `certbot-nginx`), but doesn't do anything for other plugins (e.g., "second class" first-party plugins like the DNS authenticators or third-party plugins).

It seems like we need _some_ additional logic to ensure that these other plugins are kept up to date (in a way that ensures their integrity, like `pipstrap` would if they were managed by `certbot-auto`).

It also seems like we want to persist some record of the plugin outside of the `venv`. It seems like preserving the `venv` can be problematic in some cases (#4047) and being able to safely remove the `venv` and start from a "clean slate" seems useful to rule out an entire class of potential issues when debugging failures.

It seems like the idea solution would be one that:

1. Keeps plugins up-to-date.
2. Guarantees integrity of plugins.
3. Allows the `venv` to be deleted.
4. Introduces minimal additional complexity.
5. Does not rely on OS-specific patterns.

If we can't achieve all of these, should we prioritize the list?

**Comment by erikrose** [comment]
Wow, that's a tall order, especially given that pip doesn't yet have a proper dependency resolver. I'd really like to avoid writing *more* of a custom, cross-platform package manager than we already have. :-) So, as a kneejerk reaction heading into the weekend, I'd prioritize 4 pretty highly.

**Comment by extensionsapp** [comment]
```
/etc/certbot-auto -install-plugins cloudflare
usage:
  certbot-auto [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate.
certbot: error: unrecognized arguments: cloudflare
```

How to install cloudflare or is this solution not ready yet?

**Comment by bmw** [comment]
We're still working on how to implement this for `certbot-auto`. In the meantime, if you want to use the Cloudflare plugin, see https://community.letsencrypt.org/t/getting-wildcard-certificates-with-certbot/56285.

**Comment by maximillianh** [comment]
Closing in favor of #6613
