### ISSUE TITLE
Reliance on virtualenv

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#1300]
The client's reliance on `virtualenv` makes it harder for both end users and developers to understand.

**Comment by devnsec-com** [comment]
This was probably because we do not want to pollute system.

But to be honest, I'd prefer to `pip install ...` or `yum/apt-get/etc. install ...` instead of run a script to create a `virtualenv` and install everything into it, and the reason is very simple: it's easy to uninstall/remove when I do not need it anymore.

**Comment by xamnesiax-sx** [comment]
@devnsec-com Pretty sure there was a conversation about this in IRC the other day. Dist based packaging is being looked in to, although it would be nice if there was an external APT / Yum repo set up. You'd have to ask someone like @kuba about that, though.

**Comment by pde** [comment]
Unless we vendorise python-cryptography, we need virtualenv.  But we could in fact vendorise it...

**Comment by pde** [comment]
My instinct has been that virtualenv will go away as we're packaged by distros.  Which means that fixing this is more or less wishlist for our tree.

**Comment by pde** [comment]
For 0.2.0, we want to ensure backportability for the major debian-based distros, and ideally for Fedora/RHEL/CentOS if we can manage it, which means we'll be closing this ticket for a large fraction of our users.
