### ISSUE TITLE
Report configuration help for DV connection errors

### ISSUE THREAD

**Issue by bluecmd** [certbot/certbot#1341]
Hi,

We're running very tight firewalls on our machines and would appreciate if the following error message would state what IPs to allow traffic from:

```
IMPORTANT NOTES:
 - The following 'connection' errors were reported by the server:

   Domains: domain.tld
   Error: The server could not connect to the client for DV

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client.
```

We have no trouble allowing traffic to the paths needed for DV, but I would prefer to not have to guess what IPs Letsencrypt is using.

Thanks for your consideration

**Comment by pde** [comment]
Having the IP addresses from which tests originate be widely variable and unpredictable until the moment of validation is actually a security feature and something we're planning to do more of, because it makes life much harder for attackers who aspire to defeat DV by compromising routers or DNS servers.

*In theory* we could probably tell the client a few seconds before the validation occurs, because the client is about to learn that fact anyway.  But that would require new protocol messages and additional protocol complexity, so I'm initially skeptical the operational payoff is worth that cost.

CC: @rolandshoemaker

**Comment by pde** [comment]
We could also in theory try to mark the validation requests with some other characteristic that is firewall-inspectable.  But I'm not sure whether there are any IP or TCP header fields that could be safely and easily used for that purpose.  We could much more easily use HTTP: headers, but presumably that's too far down the stack for your firewall to work with?

**Comment by rolandshoemaker** [comment]
Yeah I'm with @pde on this. While currently you can probably quite easily nail down where our validation attempts come from by watching logs for a while, we are working on changing this to make attacks against the validation service much harder. Because of this I'd be against providing these addresses to the client far in advance, and agree the additional protocol complexity of telling the client just before validation isn't really worth it.

Also agreed on HTTP headers probably being the safest/easiest place we could implement something, but I'm not really sure *what* that would be that someone doing validations themselves couldn't just copy (not sure how much processing your firewall rules can do...).

**Comment by bluecmd** [comment]
I guess there are a lot of companies that would be in the same situation for their intranets.

What about doing something like attaching some verifiable metadata in DNS? I send you the request from IP X that matches my domain signed with a key. You look up a TXT record in DNS to find my public key and use it to verify my request. Maybe the IP check isn't even needed for that.

I see that https://letsencrypt.org/howitworks/technology/ talks about such a method, but I don't see any authentication plugin for that.

**Comment by rolandshoemaker** [comment]
The method on the technology page is the DNS challenge type as specified in the ACME spec, we currently don't plan to launch with it but hope that it'll be ready for use soon after. (I'm a server not client dev so don't hold me to this but) I think the client has a branch implementing a DNS authenticator but it isn't a focus for launch since server support won't be enabled.

**Comment by bluecmd** [comment]
Ok. Thanks for the information. For us that means that we're able to use Lets Encrypt on ~5% on our domains, which is still already very good - but we would obviously want to arrive at 100%. We'll be awaiting the DNS feature with great anticipation :-)

**Comment by cpu** [comment]
@pde @bmw I think this can be closed.

We've since enshrined the source IP advice in our [integrator/large provider guide](https://letsencrypt.org/docs/integration-guide/), and the DNS challenge is now available:
>Let’s Encrypt will validate from a number of different IP addresses in the future, and will not announce which ones in advance. You should make sure your validation server is available to all IPs.
> Some people who are issuing for non-HTTP services want to avoid exposing port 80 to anyone except Let’s Encrypt’s validation server. If you’re in that category you may want to use the DNS challenge instead.
