### ISSUE TITLE
Suppress insecure platform warnings from python versions that lack SNI client support

### ISSUE THREAD

**Issue by pde** [certbot/certbot#1362]
These confuse people a lot.  They exist for a good reason, but it isn't relevant to the Let's Encrypt client.

**Comment by ArchimedesPi** [comment]
@pde I'd be happy to take this one. How do I replicate the warnings?

**Comment by devnsec-com** [comment]
@ArchimedesPi run `letsencrypt` on a platform that has Python<2.7.9 installed (and `pyOpenSSL` not installed) will reproduce this warning.

**Comment by bmw** [comment]
I think this issue has been resolved since Certbot requires `pyOpenSSL` which is used to avoid these warnings[[1]](https://github.com/certbot/certbot/blob/cf29e89366c7eb57dd48a99a06fe05ceaa9057fa/acme/acme/client.py#L35).

I'm closing this issue but if someone is still hitting this on an up-to-date version of Certbot, please comment or open a new issue.
