### ISSUE TITLE
Node.js auto authentication

### ISSUE THREAD

**Issue by nickdesaulniers** [certbot/certbot#1539]
Hi all, I just got my server up an running with letsencrypt!  Piece of cake!
<img width="1440" alt="screen shot 2015-11-17 at 11 25 43 am" src="https://cloud.githubusercontent.com/assets/1823839/11222431/2f38dee4-8d1f-11e5-9602-2c3efea44abf.png">

I was surprised to see that certs are only valid for 90 days, but it makes sense that clients have to keep proving who they are.  If I understand correctly, nginx and apache can be configured to automatically respond to challenges from letsencrypt via "[authenticators](https://letsencrypt.readthedocs.org/en/latest/contributing.html#authenticators)?"

My question is, is there already a module for this for Node.js (I didn't find one easily, but sometimes people give npm modules weird names), and if not, what's the process like for interacting with let's encrypt to establish/update the cert in use?

I'm not sure that node.js's https module is meant to have the server's certs reloaded on the fly, but idk.

**Comment by pde** [comment]
Hi!  The thing you're describing would be a node.js plugin for the client.  If you'd like to write one, see the docs [here](https://letsencrypt.readthedocs.org/en/latest/contributing.html#plugin-architecture) and [here](https://letsencrypt.readthedocs.org/en/latest/contributing.html#writing-your-own-plugin)

**Comment by pde** [comment]
I haven't thought through what the best experience for Node developers woudl be, but node.js might be a case where it makes more sense for the "UI" to be a JavaScript API, rather than the ncurses/text/command line UI exposed by the Python client.  In that case, you could make a node.js ACME client that exposes such an API.  You could find the beginnings of such a client [here](https://github.com/letsencrypt/boulder/tree/master/test/js).

**Comment by schoen** [comment]
Subsequently, although not at the time that this issue was originally created, people have written a fairly large number of clients and libraries in Node.js which can deal with the process of certificate issuance.

https://letsencrypt.org/docs/client-options/

Most Node.js developers will probably be best-served either by using one of those tools (if they want to manage the certificate issuance directly from their applications) or by using nginx with the `proxy_pass` directive to terminate TLS, and then using `certbot --nginx`. Certbot is far from the only available Let's Encrypt client option these days! :slightly_smiling_face:
