### ISSUE TITLE
letsencrypt-auto should possibly delete ~/.local/share/letsencrypt if venv setup fails

### ISSUE THREAD

**Issue by pde** [certbot/certbot#1559]
1. if something was missing or wrong in your OS'es bootstrap script, but it returned success, it won't be run again, even after a `letsencrypt-auto` update
2. if something is statefully broken in the user's virtual environment, pip will keep trying to set it up each time `letsencrypt-auto is run` but will never remove the broken state (unsure if that type of breakage is really possible)

**Comment by erikrose** [comment]
It's a long shot, but it can happen. Deleting the venv would be a good thing to do if we detect that something's gone wrong.

When I deploy things to a persistent server, I generally start a fresh venv. Otherwise (and this is the case for letsencrypt, too), old, no-longer-needed dependencies never get removed. Because of Python's mutability and dynamicity, it's conceivable that those dependencies could get themselves called and alter the state of the interpreter in unfriendly ways (like my evil library [tracefront](https://pypi.python.org/pypi/tracefront/)). More prosaically, they could register setuptools entrypoints that should no longer be there.

**Comment by pde** [comment]
@erikrose  did this (or an equivalent) wind up being done by the venv management logic of the new leauto?

**Comment by timdream** [comment]
I think we do this already?

https://github.com/certbot/certbot/blob/f544b03911a2c9357fb686e639b27324a12f2d75/letsencrypt-auto-source/letsencrypt-auto#L954

**Comment by pde** [comment]
Yes, I'm pretty sure this ticket is fixed and/or obsolete.
