### ISSUE TITLE
Make ToS inline rather than a PDF link

### ISSUE THREAD

**Issue by Wilm0r** [certbot/certbot#1574]
By using dialog to show the ToS agreement window, it's ~impossible to actually read the ToS using certain terminal emulators.

gnome-terminal allows full-screen UIs to intercept mouse events and dialog does this. As a result I can't right click + open link on the URL, nor can I copy-paste it.

Best way to still read it (other than searching for it or manually copying the URL) is hit agree, then copy-paste it once dialog terminates.

**Comment by TheNavigat** [comment]
This issue looks a bit too convoluted for a volunteer, but here are my 2 cents, for anyone who'd like to work on this.

The message is displayed in https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/cli.py#L153.

```regr``` is defined in https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/client.py#L118, it's returned from ```perform_registration``` function, https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/client.py#L153

And then there's also ```regr``` in https://github.com/letsencrypt/letsencrypt/blob/master/acme/acme/client.py#L103, returned from https://github.com/letsencrypt/letsencrypt/blob/master/acme/acme/client.py#L65.

One parameter sent to the initialization method of ```regr``` is ```response```, https://github.com/letsencrypt/letsencrypt/blob/master/acme/acme/client.py#L97, which is the return value of the ```self.net.post``` method. ```self.net``` is a ```ClientNetwork``` object, initialized here. https://github.com/letsencrypt/letsencrypt/blob/master/acme/acme/client.py#L56. The ClientNetwork class, https://github.com/letsencrypt/letsencrypt/blob/master/acme/acme/client.py#L478, basically sends a request to Let's Encrypt server and one of the returned parameters is basically the ToS URL.

It's a bit too convoluted because the system is a bit too robust. I'm not sure how to carefully remove the URL part and replace it with the content of the ToS page, not sure where to start.

**Comment by kuba** [comment]
https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/cli.py#L146 shows a URL (`regr.terms_of_service`) to the user. If you were to change the output, you would do it here.

How do you plan to turn PDF into text?

**Comment by TheNavigat** [comment]
I initially thought the link is hard-coded, and based on that I should be able to simply replace the URL with static text, but apparently, that's not the case, and consequently, hard-coding the content of the PDF file doesn't sound like a good idea.

I googled a bit for a library that extracts text from PDF files, and that looks good. http://www.unixuser.org/~euske/python/pdfminer/index.html
