### ISSUE TITLE
awkward language during email problems

### ISSUE THREAD

**Issue by jmhodges** [certbot/certbot#1618]
On the dialog screen when there is an issue with a user's email, the text "Enter email address (used for urgent notices and lost key recovery)" is printed as the end of a paragraph with the next line not being a input area but another paragraph of text. It makes the screen a little awkward to read and unclear.

The text looks like this:

![email problem screen](https://cloud.githubusercontent.com/assets/167270/11384810/c43b7480-935e-11e5-965d-774671f81d5f.png)

**Comment by pde** [comment]
I would very much prefer to put the dialog box in between those two paragraphs, I just can't see a way to make dialog do that.

Perhaps we can reorganise so that the text is:

<tt>There seem to be problems with that address.  If you really want to skip entering an email, you can run the client with --register-unsafely-without-email, but make sure you back up your account key from /etc/letsencrypt/accounts</tt>

<tt>Enter your email address (used for urgent notices and lost key recovery):</tt>

<tt>Entry field</tt>

**Comment by bmw** [comment]
I think reorganizing the text is good. Maybe we should also consider including the error message from `boulder` to give the user more information about the problem.

**Comment by sydneyli** [comment]
We don't use ncurses anymore, so I think this is slightly less confusing now. It would still be nice to switch around the suggestion and the "Enter your email" prompt, which should be pretty easy to do in the `get_email` function of `certbot/display/ops.py`

**Comment by bmw** [comment]
This is still a thing.
