### ISSUE TITLE
CLI support for setting XDG_DATA_HOME

### ISSUE THREAD

**Issue by NibeP** [certbot/certbot#1704]
Hello,

I would like to have Command Line support to set the parameter XDG_DATA_HOME

For example: ./letsencrypt-auto --data_home /usr/local/share

**Comment by pde** [comment]
does `XDG_DATA_HOME=/path/to/venv ./letsencrypt-auto` not work for you?

**Comment by Petertjuh360** [comment]
No, unfortunately. I am creating a plugin for DirectAdmin and I need to set the parameter by CLI to make sure Let's Encrypt download and install will go right.

**Comment by schoen** [comment]
I actually don't understand why @pde's solution doesn't work. Environment variables should be inherited by subprocesses, including shell scripts. I'm going to hypothesize that the problem is that the `sudo` invocation resets the environment to a default environment.

`sudo` allows you to set environment variables on the command line, so

`sudo XDG_DATA_HOME=/usr/local/share ./letsencrypt-auto`

should have the desired effect.

If you're still working on this and this workaround doesn't work for you, please re-open this issue! Thanks.
