### ISSUE TITLE
-d and multiple domains

### ISSUE THREAD

**Issue by mnot** [certbot/certbot#1714]
Small thing, but it would make automation _much_ easier (e.g., with tools like Ansible) if -d took multiple, space-separated arguments, rather than requiring multiple instances. E.g.,

> lets encrypt certonly --webroot -w /srv/http/example.com/ -d example.com www.example.com

**Comment by joohoi** [comment]
You should be able to use comma separated values for -d (or --domains)

**Comment by Rob1NN** [comment]
You can add multiple -d arguments to your command for additional domains

**Comment by Maescool** [comment]
example usage that works according to the documentation https://letsencrypt.org/howitworks/
letsencrypt-auto certonly --webroot -w /srv/http/example.com/ -d example.com -d www.example.com

**Comment by mnot** [comment]
@Rob1NN @Maescool yes, I know that, thanks -- this is a request for a different form.

@joohoi comma separated values seems to work, thanks. Ideally it'd be space-separated, as it's visually more distinct, and other kinds of configuration (e.g., Apache ServerAlias) takes space-separated, making it easier to work with.

Again, the focus here is making it easy to integrate LE into automation tools like Ansible, Puppet, etc.

**Comment by schoen** [comment]
(We're reviewing old unresolved issues, hence the new attention to a feature request from nearly three years ago.)

I have an intuition that we didn't want to do this due to tension with some other forms of the CLI invocation, for example the common pattern of alternating `-w` and `-d`, and also the possibility of less helpful error messages when a user provides an unrecognized argument at the end of the command line (if the argument parser wrongly thinks that that argument was meant to be another domain name).

Who is in charge of the overall CLI design? Is there such a person?

By default I'm going to assign this to @bmw. :slightly_smiling_face:

**Comment by bmw** [comment]
I don't think we should do this. This adds complexity to the project and as Seth pointed out results in worse error messages in certain scenarios.
