### ISSUE TITLE
certificates should be installed to /var/lib/letsencrypt, not /etc/letsencrypt

### ISSUE THREAD

**Issue by aburch** [certbot/certbot#1732]
Please consider installing the certificates to /var/lib/letsencrypt/{live,archive,...}.  They are automatically generated and thus don't count as configuration files (IMHO).

Using /var/lib/letsencrypt instead of /etc also allows running the letsencrypt client without write permissions to /etc, for example when mounting /etc read-only or when using systemd with its ProtectSystem=full option.

See also the [File Hierarchy Standard](http://www.pathname.com/fhs/pub/fhs-2.3.html#ETCHOSTSPECIFICSYSTEMCONFIGURATION) which defines /etc as "static", that is "files that do not change without system administrator intervention".

**Comment by ricwein** [comment]
:+1:

**Comment by madduck** [comment]
+1 from me.

**Comment by jpkrohling** [comment]
For Fedora, Red Hat and CentOS, the correct paths should be /etc/pki/tls/private (for keys), /etc/pki/tls/certs (for certificates, including full-chain and chain).

**Comment by madduck** [comment]
also sprach Juraci Paixão Kröhling <notifications@github.com> [2015-12-08 13:48 +0100]:
> For Fedora, Red Hat and CentOS, the correct paths should be
> /etc/pki/tls/private (for keys), /etc/pki/tls/certs (for
> certificates, including full-chain and chain).

Don't these operating systems implement the FHS?

-- 
The sender e-mail address used (reply.github.com@pobox.madduck.net)
is valid and specific to our correspondence. It should not indicate any
affiliation with your organisation.
 
Die verwendete E-mail-Adresse (reply.github.com@pobox.madduck.net)
ist gültig und spezifisch für unsere Korrespondenz. Sie soll in keiner Weise
auf eine Verbindung mit Ihrer Organisation hindeuten.
 
Spamtrap: reply.github.com.bogus@pobox.madduck.net

**Comment by jpkrohling** [comment]
Sure, but whether the cert/keys are configuration files or are persistent data depends on the point of view :) The fact is that those are the places for the certificates and keys. With the files there, selinux takes care of protecting them from being abused from rogue processes.

**Comment by aburch** [comment]
On Tue, 2015-12-08 at 05:58 -0800, martin f. krafft wrote:
> also sprach Juraci Paixão Kröhling [2015-12-08 13:48 +0100]:
> > For Fedora, Red Hat and CentOS, the correct paths should be
> > /etc/pki/tls/private (for keys), /etc/pki/tls/certs (for
> > certificates, including full-chain and chain).
> 
> Don't these operating systems implement the FHS?

/etc is appropriate for manually installed certificates.  Debian also
has a /etc/ssl/private directory.

However the letsencrypt client manages certificates automatically (i.e.
they are not "static" files), so letsencrypt should store them in /var.

Ansgar

**Comment by madduck** [comment]
also sprach Ansgar Burchardt <notifications@github.com> [2015-12-08 15:11 +0100]:
> However the letsencrypt client manages certificates automatically (i.e.
> they are not "static" files), so letsencrypt should store them in /var.

Clearly, this needs to be parametrised so that distros can do as
they want. Let RPM distros conflate /etc as much as they want ;)

-- 
The sender e-mail address used (reply.github.com@pobox.madduck.net)
is valid and specific to our correspondence. It should not indicate any
affiliation with your organisation.
 
Die verwendete E-mail-Adresse (reply.github.com@pobox.madduck.net)
ist gültig und spezifisch für unsere Korrespondenz. Sie soll in keiner Weise
auf eine Verbindung mit Ihrer Organisation hindeuten.
 
Spamtrap: reply.github.com.bogus@pobox.madduck.net

**Comment by tomchiverton** [comment]
This is also a breaking change, because web servers may have configurations (not managed by LE) pointing into the current location.

**Comment by madduck** [comment]
Yup, it's painful to fix things that haven't been done properly from the start :/

**Comment by nitmir** [comment]
Le jeudi 03 mars 2016 à 03:49 -0800, Tom Chiverton a écrit :
> This is also a breaking change, because web servers may have
> configurations (not managed by LE) pointing into the current
> location.

It could be possible to put symlinks
/etc/letsencrypt/{live|archive} -> /var/lib/letsencrypt/{live|archive}
to circumvent that.

**Comment by tomchiverton** [comment]
>It could be possible to put symlinks
>/etc/letsencrypt/{live|archive} -> /var/lib/letsencrypt/{live|archive}

Which LE could (has to?) automate when it sees it's on a machine with the old config. Seems robust to me. 
-- 
Tom
Sent from my phone.

**Comment by pde** [comment]
This is going to be a wontfix wrt the default locations deployed by Certbot.  According to the [Filesystem Hierarchy Standard](http://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s07.html), `/etc/` is used for the following purpose:

> The /etc hierarchy contains configuration files. A "configuration file" is a local file used to control the operation of a program; it must be static and cannot be an executable binary.

Now, you can perhaps argue that certificates are not used to control the operation of programs, but in many important ways they do. Furthermore, existing distributions have made the same choice: Debian puts its native certs in `/etc/ssl/` and Fedora puts them in `/etc/pki`. We'd understand if those OSes customized Certbot to deploy to their historical cert storage locations, but we may alternatively try to polish the `/etc/letsencrypt/live` / `/etc/letsencrypt/archive` arrangement and turn it into a standard, because it has a number of advantages over the way things were done previously.

Despite all of this, if you'd like your certs to go somewhere different, you have a few options:

1. Move all of `/etc/letsencrypt`, which you can do with the `--config-dir` flag
2. Use a `--renew-hook` to deploy certs and keys out of `/etc/letsencrypt/live` to wherever you want them (we recommend copying rather than moving)
3. Certbot 0.10.0 is going to support a lot more customisation of cert and key locations via editing of the renewal configuration file (in `/etc/letsencrypt/renewal/`) for each cert.

**Comment by pde** [comment]
As for the suitability of `/var/lib/`, the FHS [says](http://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s08.html):

> This hierarchy holds state information pertaining to an application or the system. State information is data that programs modify while they run, and that pertains to one specific host. Users must never need to modify files in /var/lib to configure a package's operation, and the specific file hierarchy used to store the data must not be exposed to regular users.

I don't exactly know what "the specific file hierarchy used to store the data must not be exposed to regular users" means, but what we have in `/etc/letsencrypt/live/` may violate that.

**Comment by madduck** [comment]
@pde The point is not so much about certificates being configuration data, but the fact that files under `/etc` are guaranteed to not be overwritten automatically, at least not in ways that do not preserve the sysadmin's choices. As such, I think `/var` is a better location for these auto-generated files. It needs not be `/var/lib`, given your second comment (this was news to me, and I don't think Debian respects this subsentence).

**Comment by pde** [comment]
I do hear what you're saying about sysadmin choices. We're planning to support more sysadmin choice about what's going on in `/etc/letsencrypt/{live,archive}`, but sysadmins will need to edit their renewal conf files to match any changes they make there.

**Comment by pde** [comment]
As a practical matter, I don't think we'll ever change what's deployed in `/etc/letsencrypt/live` because so many systems depend on it. But if one day there's a set of proposals for something that commands consensus as "clearly better", we could declare `/etc/letsencrypt/live` to be deprecated (while still supporting it) and point everyone to something new.

**Comment by pde** [comment]
Another proposal the team was kicking around in this regard was to rename `cert.pem` to `leaf.pem`, because some people accidentally use `cert.pem` when they really should be using `fullchain.pem`.
