### ISSUE TITLE
FAQ: Do I need root (superuser) to use letsencrypt?

### ISSUE THREAD

**Issue by hickford** [certbot/certbot#1741]
My website is hosted on a shared server. I don't have root on it. Can I use letsencrypt? 

I tried installing letsencrypt-auto following https://letsencrypt.readthedocs.org/en/latest/using.html#installation 

    ham@pandora:~/letsencrypt$ ./letsencrypt-auto
    Bootstrapping dependencies for Debian-based OSes...
    [sudo] password for ham:
    ham is not in the sudoers file.  This incident will be reported.

The user guide is confusing:

> Please do not attempt the installation commands as superuser/root

**Comment by spede** [comment]
Try:
https://github.com/kuba/simp_le
Or:
https://github.com/diafygi/letsencrypt-nosudo

The confusing bit means you shouldn't run letsencrypt-auto as superuser, because the program will invoke sudo when it needs to automatically.

**Comment by mikehaertl** [comment]
I also ran into some problems as I started installation as root (`sudo -s`). I think the above notice should also be added here: https://letsencrypt.readthedocs.org/en/latest/using.html#letsencrypt-auto

**Comment by kolAflash** [comment]
In many scenarios it's the most useful to run letsencrypt-auto with "--webroot-path" (on a webroot with proper permissions) or "--manual". If the user is also sure, that everything needed is installed via apt-get, zypper, yum, ... there should be absolutely no reason to require root!

So please, ask only for root if it's needed!

For installing packages, either check first if the needed packages are already installed. E.g.:
rpm -ql | grep PACKAGE_YOU_LOOK_FOR
dpkg -l | grep PACKAGE_YOU_LOOK_FOR
Or provide an option "--dont-install-packages" which just skips this step.

Always using root is a bad idea, because:
- Not everyone has root on a server
- Bad security
Additionally, probably many users don't want software-packages being installed without being asked before.

**Comment by tobiasmcnulty** [comment]
Agreed, it would be nice to be able to automate certificate renewal even if root is not available (e.g., if the cert is going to be uploaded via an API).

**Comment by pde** [comment]
Whether root is required to run Certbot or not depends on how you intend to use it.  In some cases, typically when using the `webroot` and `manual` plugins, Certbot can be run without root if you ensure that `/etc/letsencrypt/`, `/var/log/letsencrypt`, and `/var/lib/letsencrypt` are writeable by the user that wants to run it (you can also change these locations with `--config-dir`, `--log-dir` and `--work-dir`).

The things you *do* need root for are, during installation:
* Running `certbot-auto`, since it installs OS dependencies, and tries to run Certbot as root for the reasons discussed below
* If you're not using `certbot-auto`, you need to install certbot packages. On most OSes, that requires root access.
* Using the standalone plugin, since that needs to bind to port 80 or 443, and those are privileged ports.
* Using the Apache plugin, in order to write apache config files and send graceful reload signals to the Apache process
* Using the Nginx plugin, for the same reasons

**Comment by pde** [comment]
Hmmm, actually, we do have: https://certbot.eff.org/faq/#does-certbot-require-root-privileges
