### ISSUE TITLE
client creates .well-known folder with insufficient permissions

### ISSUE THREAD

**Issue by Kissaki** [certbot/certbot#1761]
I used the `letsencrypt-auto` client with `--webroot --webroot-path`.

When the webroot path does not contain a `.well-known` folder yet, the client creates it as root (current user) with permissions 700. With a webserver running as www-data this will not allow the webserver to serve the challenge files, as it does not have the folder traversal (x) permission.

The subfolder `acme-challenge` is created with www-data:www-data 777, which is fine.

> ./letsencrypt-auto certonly --webroot --webroot-path /path/to -d example.com

**Comment by olovphp** [comment]
I have this same problem but knowing this issue has been open since 2015(!) is very discouraging. I even tried to create the folder manually with the right permissions but no luck.

**Comment by dixonwille** [comment]
I get the same. I thought I was not configuring something correctly... had to set a `watch -t 1 ls -la` to see the permissions were set to root...

**Comment by Shnoulle** [comment]
Maybe best is to have a option for each --webroot-path , --webroot-user.

I use apache-mpm-itk then each of my web server have their own user. To fix the issue i use acl : then all files inside .well-know are readable by my webuser ( `setfacl -m d:u:user:rX www/.well-know`)

**Comment by tmilev** [comment]
This is a very serious bug. 
Please fix it! 
It is preventing me from using certbot -I will buy certificates instead.

Certbot MUST not create challenge files that require root to access. I am running a custom webserver which runs without root privileges (I listen to port 80 without root access with a port redirect trick).

Once again, I want to stress out the fact that certbot is losing users (namely, myself) because of this bug.

**Comment by Kissaki** [comment]
@tmilev just create the folder with adequate permissions yourself and you’re set. This is an inconvenience, not a blocker.

**Comment by tmilev** [comment]
@Kissaki: here is what I get:

`./certbot-auto certonly --config-dir /home/ddtester/ace/calculator/certbot/certificates  --logs-dir /home/ddtester/ace/calculator/certbot/logsdir  --work-dir /home/ddtester/ace/calculator/certbot/workdir --webroot -w /home/ddtester/ace/public_html/ -d calculator-algebra.org -d www.calculator-algebra.org`

the result I get is:

`Requesting root privileges to run certbot...
  /home/ddtester/.local/share/letsencrypt/bin/letsencrypt certonly --config-dir /home/ddtester/ace/calculator/certbot/certificates --logs-dir /home/ddtester/ace/calculator/certbot/logsdir --work-dir /home/ddtester/ace/calculator/certbot/workdir --webroot -w /home/ddtester/ace/public_html/ -d calculator-algebra.org -d www.calculator-algebra.org
/var/tmp/sclzwtpq9: Zeile 8: CERTBOT_AUTO=./certbot-auto: Datei oder Verzeichnis nicht gefunden`

I have no clue why the program is looking for stuff in /var/tmp, but it does.

When run the same command with a "sudo" in the front, my server replies:

> <html><body><b>Error: file appears to exist but I could not open
   it.</b>"

**Comment by stratacast** [comment]
Can someone confirm what the permissions/ownership for the folder and the contents of the .well-known folder are supposed to be? I'm having troubles finding that information

**Comment by mikeshultz** [comment]
Using the setgid sticky bit worked for me.  Should be good enough to automate, anyway.  Though I agree, there should be an argument for a user/group.

Example:

    sudo -u lighttpd mkdir -p /tmp/certbot/public_html/.well-known/
    chmod g+s /tmp/certbot/public_html/.well-known
    certbot certonly --dry-run --webroot -w /tmp/certbot/public_html -d example.com -d www.example.com

**Comment by ppython** [comment]
@Kissaki , @dixonwille :
We figured it out, if you're able to, chown the following directories to your "www-data" or equivalent user. Or start a fresh install as "www-data" or equivalent.
- log directory: /var/log/letsencrypt/
- working directory: /var/lib/letsencrypt/
- config directory: /etc/letsencrypt/

@Shnoulle : I also like the idea of a new "--werbroot-user".

@stratacast : the .well-known folder should be accessible by the acme client, it's all that matter (in our case as "root:root" it didn't work, we switched for the equivalent of "www-data".

**Comment by bmw** [comment]
This issue has been closed due to lack of activity, but if you think it should be reopened, please open a new issue with a link to this one and we'll take a look.

**Comment by wadih** [comment]
@ppython, @Kissaki , @stratacast , @Shnoulle 

Got `--apache` to work on Debian 9 with mpm-itk.

No need for setfacl, sticky bit, changing owners or diluting security anywhere.

I found out that when using `--apache` it doesn't physically create the `.well-known` directory within the web directory anymore but simply creates a world-readable alias to `/var/lib/letsencrypt/http_challenges/` in the target vhost. 

So it should have worked even with mpm-itk out of the box. But it wasn't working so there was something else. 

The reason finally was that `/var/lib/letsencrypt` permissions in my case 700 was thus blocking world path traversability to reach the challenge file which has 755 permission. All other directories up and down were world-traversable. So it is mostly just an oversight by package maintainer and not done on purpose. 

To re-enable traversability to the hard-coded secure path, all I needed was to add o+x to the `/var/lib/letsencrypt` directory and all worked fine. (all other directories up and down had 755 except that one):

Before: 

755 /var/
755 /var/lib/
700 /var/lib/letsencrypt/
755 /var/lib/letsencrypt/http_challenges

So simply doing `chmod o+x /var/lib/letsencrypt` fixed the issue for me. Permissions became: 

After:

755 /var/
755 /var/lib/
**701** /var/lib/letsencrypt/
755 /var/lib/letsencrypt/http_challenges

And traversability was restored so the apache thread could reach the hard-coded challenge file by absolute filename successfully now and all the rest worked. 

Probably this is due to my umask which sets any new files to be 700 by default, but when I installed certbot package maintainer didn't force permission to 755 on `/var/lib/letsencrypt` upon installation although he did on `http_challenges`, so it was most likely just an oversight. I'll try to send them an email to have this fixed in the distribution.

**Comment by szpak** [comment]
Thanks @wadih for your description, it helped me to find a reason of a renewal failure on Fedora 31. However the situation there is a little bit different.

`/var/lib/letsencrypt/` has proper 755 permissions (as configured in RPM), but `/var/lib/letsencrypt/http_challenges/` (created by certbot) has 700. That causes access via httpd (on `sudo certbot renew --dry-run`) to fail with:
> (13)Permission denied: [client x.x.x.x:x] AH00035: access to /.well-known/acme-challenge/xxxx denied (filesystem path '/var/lib/letsencrypt/http_challenges/xxxx') because search permissions are missing on a component of the path

It might be caused by using a default umask for root which is restrictive (0022) - I wasn't find any place in the source code where that directory is created explicitly (only [that](https://github.com/certbot/certbot/blob/9e5bca4bbf3c4fd198382dd9d6e05b54014aca30/certbot-apache/certbot_apache/_internal/http_01.py#L58)).

Sorry for resurrecting that old issue. I might create the new one if you agree it is something worth to follow.

**Comment by bmw** [comment]
The place where the directory is created is https://github.com/certbot/certbot/blob/9e5bca4bbf3c4fd198382dd9d6e05b54014aca30/certbot-apache/certbot_apache/_internal/http_01.py#L171 which on POSIX systems like Linux is essentially a wrapper around [os.makedirs](https://docs.python.org/3/library/os.html#os.makedirs).

While I wouldn't expect the umask of 0022 to cause a problem, a more restrictive umask could. I created an issue to track this at https://github.com/certbot/certbot/issues/7741.

**Comment by szpak** [comment]
> While I wouldn't expect the umask of 0022 to cause a problem, a more restrictive umask could.
Sure, I meant 0077.

Thanks for getting the ball rolling.

**Comment by wadih** [comment]
> Sure, I meant 0077

@szpak @bmw , Yes, my default umask for root was 0077. Interesting to see the differences between Fedora 31 and Debian. 

Also happening in Debian 10 at the moment which is expected.

I just manually just set the permission. I regularly provision new servers, so when it'll be fixed, I will start noticing it on new servers I provision. 

Note that it has to be done after the first certificate has been created, because the directory doesn't exist before that yet. 

    chmod o+x /var/lib/letsencrypt

Thanks all
