### ISSUE TITLE
Missing link to documentation on letsencrypt.org

### ISSUE THREAD

**Issue by mivade** [certbot/certbot#1767]
The main page at https://letsencrypt.org seemingly has no link to the [documentation](https://letsencrypt.readthedocs.org/en/latest/index.html) that I can find. Ideally there would be a link next to "Support" in the navbar or in one of the other dropdown menus.

Apologies if this is not the right place for this.

**Comment by bmw** [comment]
When this was written this was a pretty good place for this ticket. Since then, EFF has taken over the `letsencrypt` client (which has been renamed to Certbot) and Let's Encrypt has a public repository for the website at https://github.com/letsencrypt/website. Due to these developments, I think this issue can be closed.

**Comment by mivade** [comment]
Agreed. There's also a link to the documentation now! :)
