### ISSUE TITLE
ServerName not drawn from apache conf.d

### ISSUE THREAD

**Issue by phasmal** [certbot/certbot#1779]
I start letsencrypt-auto (without args) and get and error:

"No names were found in your configuration files.
You should specify ServerNames in your config...."

however I do have a ServerName entry in a file called apache's conf.d/fqdn, which apache seems to pick up fine.

(This doesn't block continuing, but picking up these values as well would improve the automation of letsencrypt)

**Comment by pde** [comment]
What OS are you on?  Any chance you can [follow the developer instructions](https://letsencrypt.readthedocs.org/en/latest/contributing.html#running-a-local-copy-of-the-client), run letshelp-letsencrypt-apache, and send us the resulting tarball?

**Comment by justdave** [comment]
I'm having this issue on CentOS 6, my config layout is the same.  My vhosts are in files in the conf.d directory and do have ServerName directives that it's not finding.  did a git clone of the repo as the dev instructions say, and I don't see a letshelp-letsencrypt-apache anywhere in the repo, but this ticket is a couple years old, I'm guessing maybe it's changed a little since then...

**Comment by justdave** [comment]
oh, I figured out what was biting mine... I had both the http and https version of the vhost for the same domain name in the same config file, certbot wants each vhost in a separate file.  Splitting the file so http was in one and https in the other made it work.

**Comment by joohoi** [comment]
This is an very old issue and a lot has been changed in certbot-apache since then. I'm very confident that this issue has been solved. certbot-apache also supports multiple vhosts per file now. I'm closing the issue as fixed.
