### ISSUE TITLE
letsencrypt-apache: DocumentRoot not found for DVSNI challenge

### ISSUE THREAD

**Issue by felipecn** [certbot/certbot#1783]
Using letsencrypt with apache plugins fails for me, returning "Failed authorization procedure. vales.ca (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client for DV :: Failed to connect to host for DVSNI challenge".
I tried to debug the issue and the farther I could go is this issue on apache's error.log. It seems that the changes are being reverted before the server could be verified.

$ tail error.log
[Sun Dec 06 01:49:43.457641 2015] [mpm_prefork:notice] [pid 11561] AH00163: Apache/2.4.10 (Debian) PHP/5.6.14-0+deb8u1 OpenSSL/1.0.1k configured -- resuming normal operations
[Sun Dec 06 01:49:43.457716 2015] [core:notice] [pid 11561] AH00094: Command line: '/usr/sbin/apache2'
[Sun Dec 06 01:50:22.514933 2015] [mpm_prefork:notice] [pid 11561] AH00171: Graceful restart requested, doing restart
AH00112: Warning: DocumentRoot [/var/lib/letsencrypt/tls_sni_01_page/] does not exist
[Sun Dec 06 01:50:22.633604 2015] [ssl:warn] [pid 11561] AH01906: 5cfe6fc81b483fd2ffaef9dcc3724dbc.076e271780c94f828a799144b1c5655a.acme.invalid:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Sun Dec 06 01:50:22.633879 2015] [mpm_prefork:notice] [pid 11561] AH00163: Apache/2.4.10 (Debian) PHP/5.6.14-0+deb8u1 OpenSSL/1.0.1k configured -- resuming normal operations
[Sun Dec 06 01:50:22.633892 2015] [core:notice] [pid 11561] AH00094: Command line: '/usr/sbin/apache2'
[Sun Dec 06 01:50:29.455274 2015] [mpm_prefork:notice] [pid 11561] AH00171: Graceful restart requested, doing restart
[Sun Dec 06 01:50:29.777274 2015] [mpm_prefork:notice] [pid 11561] AH00163: Apache/2.4.10 (Debian) PHP/5.6.14-0+deb8u1 OpenSSL/1.0.1k configured -- resuming normal operations
[Sun Dec 06 01:50:29.777304 2015] [core:notice] [pid 11561] AH00094: Command line: '/usr/sbin/apache2'

**Comment by dwilson390** [comment]
I had this issue too until I realised my Apache configuration was causing the issue.  Could you paste your ports.conf?

**Comment by felipecn** [comment]
Sure. I've also tried some options such as disabling listening to 443 so the script would be responsible for setting that.

$ cat /etc/apache2/ports.conf 
# If you just change the port or add more ports here, you will likely also
# have to change the VirtualHost statement in
# /etc/apache2/sites-enabled/000-default.conf

Listen 80
Listen 443
 
#<IfModule ssl_module>
#	Listen 443
#</IfModule>

#<IfModule mod_gnutls.c>
#	Listen 443
#</IfModule>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet

**Comment by RussNelson** [comment]
Same with me. Here's the command line I used. Ubuntu 14.04.

./letsencrypt-auto --apache -d rths.us

**Comment by jordila** [comment]
Same with me.
Using the same exact configuration as @felipecn 
Any ideas ?

**Comment by LeCoyote** [comment]
I'd like to confirm that this is a new issue with the LE apache authentication plugin.
It appeared somewhere between 0.2.0.dev0 and 0.5.0.dev0. Using the former, I had no problem in getting my certs. Using the latter on the exact same VM and web server configuration, the LE client now fails to obtain/renew the same certificate. However, using the webroot plugin in the vhost's DocumentRoot folder works flawlessly.
It looks like somewhere along the procedure, the LE CLI client fails to create the directory that will be served by Apache (perhaps it's dropping its privileges?), hence the DocumentRoot warnings in the logs.

**Comment by LeCoyote** [comment]
After further investigation, it appears that the DocumentRoot error is **not** the culprit here. I have used v0.4.2 successfully with that message still present in the apache error log, but got the certificate nonetheless. However this error:
`(98)Address already in use: make_sock: could not bind to address 0.0.0.0:443`
is present in the two VMs where the problem appears.
Another oddity is that using v0.4.2 was not sufficient to fix the problem on the VMs where it is present. So there must be another factor actually causing the problem, but I have yet to find what it is.

**Comment by LeCoyote** [comment]
For what it's worth, I've finally fixed this issue on my systems. Servers running Apache with -D SSL_DEFAULT_VHOST displayed the problem. In Gentoo, that flag triggers the inclusion of a vhost definition where the "Listen 443" directive is typically located. For some reason, the LE tool could not find it and added ***another*** such directive, hence causing the "could not bind" error.
Hope this helps.

**Comment by Marty** [comment]
I've also just ran into this issue on a fresh installation of Ubuntu 14.04.4 LTS and apache2.

```
[Tue May 10 15:58:48.415780 2016] [mpm_prefork:notice] [pid 28832] AH00171: Graceful restart requested, doing restart
AH00112: Warning: DocumentRoot [/var/lib/letsencrypt/tls_sni_01_page/] does not exist
[Tue May 10 15:58:48.492938 2016] [ssl:warn] [pid 28832] AH01906: RSA server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue May 10 15:58:48.493270 2016] [mpm_prefork:notice] [pid 28832] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.16 OpenSSL/1.0.1f configured -- resuming normal operations
[Tue May 10 15:58:48.493283 2016] [core:notice] [pid 28832] AH00094: Command line: '/usr/sbin/apache2'
```
@LeCoyote Maybe you could provide more insight into your solution, so the devs can fix this issue at the core.

Also I think this should get a high prioritisation, since it is a very common scenario.

**Comment by LeCoyote** [comment]
@Marty In my case the problem was gentoo-specific. The LE client didn't know about gentoo config files, namely /etc/conf.d/apache2, which triggers the inclusion of a specific config file where the "Listen 443" directive appears. The problem has been fixed since.

**Comment by vdecree** [comment]
I am getting the same issue. I've read through the thread, what did you do in order to get it working @LeCoyote

**Comment by LeCoyote** [comment]
@vdecree as I said above, the problem has been fixed. Before that I'd move the "Listen 443" directive around so the letsencrypt CLI client would find it

**Comment by bmw** [comment]
New log of this issue in #3263.

**Comment by stonerl** [comment]
I can confirm @bastian-bramblecloud observations from #3263.

If these lines are missing I get an error:
```
SSLCertificateFile 
SSLCertificateKeyFile 
```

**Comment by gorky** [comment]
Looks like there is an issue when TLS is used rather an SSL?  I am using:
```
GnuTLSCertificateFile
GnuTLSKeyFile
```

**Comment by bmw** [comment]
I think there a lot of unrelated things going on in this issue. The following message should be a warning, not a fatal problem:
```
 AH00112: Warning: DocumentRoot [/var/lib/letsencrypt/tls_sni_01_page/] does not exist
```
This message can be found in your Apache logs even when Certbot is successful. If anyone in this issue is still having a problem, I encourage you to open a new issue with a complete log from Certbot and the Apache configuration file containing the `VirtualHost` you're trying to enable HTTPS on.

For those of you who are curious what's going on here, here is some background: Before Let's Encrypt will issue your certificate, you have to prove control over the domain your requesting a certificate for and Certbot's Apache plugin does this by performing a [TLS SNI challenge](https://tools.ietf.org/html/draft-ietf-acme-acme-01#section-7.3). This challenge mandates the contents of the certificate used, but not the HTTP response or the file served. Because of this, Certbot just sets the `DocumentRoot` to an arbitrary path in Certbot's directories because this value doesn't matter.

**Comment by embray** [comment]
@bmw Thanks for the explanation. I was seeing this as well (and only had warnings about `DocumentRoot`).  Nevertheless my Apache server went belly-up today after new certificates were issued and it's not clear what happened or why, but it's probably an unrelated issue.

**Comment by jsnfwlr** [comment]
@bmw late to the party, but I would like to add for the sake of others encountering this:

I had the same error as described here, everything was fine for a while, then a few certificates reached their renewal point and I saw the error flooding my apache log files every day. Turned out I had disabled about 15 vhosts on the server and pointed their DNS records to another server, and had forgotten to remove their certificates from the one with all the errors. After removing their conf files from /etc/letsencrypt/renewal everything went back to normal.
