### ISSUE TITLE
Carve out installation into a seperate script

### ISSUE THREAD

**Issue by htgoebel** [certbot/certbot#1829]
In some of my communities, letsencrypt get _terrible bad_ critics for behaviour like this:

```
~> ./letsencrypt-auto --help
[sudo] password for xxx:
```

And I must agree on this bad critics. While putting everything in a single script is darn simple for the less skilled user, it is darn irritating for the more sensible once. And the more sensible once will tell all others "letsencrypt is a crap".

So, _please, please_, do the project a favour and carve out the installation part.

Asking the user to run _two_ commands instead of one, will be feasible even for the less skilled.

The new `letencrypt-auto` can simply test whether the venv is installed (and if letsencrypt is installed in this venv) and if not, error out with a _verbose_ message like: "It looks like letencrypt is not yet installed. Please run $(dirname "$0")/letsencrypt-install. If you think, this is an error, ..."

**Comment by pde** [comment]
Conceivably we could make first install require an extra parameter on `letsencrypt-auto`, though I don't think it would be a good idea to remove the auto-updating feature given that many users may be depending on it (we will have a flag to disable it as of 0.2.0, though).  CC: @erikrose

**Comment by dehnhard** [comment]
I also stumbled 2 times upon this "root requirement" while testing this client with webroot and a dedicated system user. One of these issues seems to be fixed in #1875 now, so I'd like to comment on this issue during the bootstrapping / installation phase.

It appears to me the root access here is for installing the required system packages. If you do the bootstrapping with the following steps it stays easy for inexperienced user while giving options to the experienced one:

- Check if required system packages are not installed.
- If thats the case notify the user - "Packages x,y,z need to be installed"
- Ask the user, if the script should install these packages
- If yes: Call the package manager with root permissions (call su / sudo only here)
- If no: Exit script with message "Please install the needed packages with your favorite package manager before executing this script again"

**Comment by htgoebel** [comment]
@dehnhard: This will still not allow to remove the installation-directory after installations, since both are intermixed. But it's a better solution than adding another parameter on the first run.

**Comment by dehnhard** [comment]
In a community discussion I found a statement from a dev, that the preferred way to install letsencrypt for most people is to install it from the distribution repository. That's great and and would solve this issue as the installation will be done in a distribution compliant way.

But it'll be some time, maybe years, until these packages arrive for most of us, as most webservers are running on some stable linux distributions. 

So I'd like to ask the @letsencrypt devs how we new users, who are attracted by the open beta, are expected to treat the letsencrypt client? Especially given the fact that the letsencrypt-auto command is the one documented installation path for this client, which any new user will find first. 

If the answer is to treat it as an unstable beta software, that may even still change parameter format and also shouldn't yet be used automatically, e.g. in a cron job, then I'd repeat my solution from above, as that would allow to -somehow safely- install and use it (with webroot) under a dedicated user without any root permissions.  

Having already written that much I add that for a future time it would be perfect if the webservers itself knows how to talk to an ACME compliant CA. It would be enough to give the webserver config a SSL key, an acme URL and a renewal interval, so that the server can do the signing/renewing magic itself.

**Comment by pde** [comment]
This has been mitigated by #2885, and in general by better packaging and onboarding.
