### ISSUE TITLE
Deliver one-year certificates for HPKP/HSTS/DANE/TLSA compatibility

### ISSUE THREAD

**Issue by HLFH** [certbot/certbot#2083]
Hi,

For [HSTS preloading](https://hstspreload.appspot.com/), we need 18 weeks (126 days) and [at least 180 days to be considered A+ on SSL Labs](https://www.ssllabs.com/).
To be useful, the lifetime of a TLS certificate and the private key should be at least the double of the validity period of HPKP, so [at least 120 days](https://tools.ietf.org/html/rfc7469#section-4.1) (2 x 60 days), so the system admin engineers could have the possibility to overcome a serious problem. 
The comfort zone is one year if we keep in mind the necessary time and required testing for the replacement of the private key.
With DANE/TLSA and DNSSEC enabled, each renewal of the TLS certificate by `letsencrypt` requires that every Let's Encrypt user has the time to regularly modify (= each 90 days) its DNS zone to add the new TLSA DNS resource record. The renewal of domain names are - for the most part - made every year, it would be smarter to be synchronized with that.

It's better to deliver one-year certificates to empower users to use the whole TLS stack and not the bare minimum. If you have some really great research papers to keep the 90 days validity by default, you should at least offer the option to generate one-year certificates, because in the Let's Encrypt CA offering, it seems that we are advised to renew - more manually than automatically in the facts - every 90 days the TLS certificate and the private key, and also avoid additional configuration with HPKP, DANE/TLSA and HSTS. Let's Encrypt should be secure by default.

Thanks in advance,
HLFH

**Comment by FrancisRussell** [comment]
Note, I'm not a Let's Encrypt developer.

The rationale for Let's Encrypts short certificate lifetime is [here](https://letsencrypt.org/2015/11/09/why-90-days.html). The aim is to encourage automation by making it relatively burdensome for a sysadmin to have to update certificates manually. You're suggesting you want security using SSL, HSTS preloading HPKP certificate pinning and DANE, but with a sysadmin who will update all these things manually rather than scripting them. It's precisely this which leads to websites with invalid certificate configurations which users then have to ignore to access.

SSL Labs doesn't require HSTS preloading to get an A+ score. It requires that the server supplies a max-age value of at least six months in the Strict-Transport-Security header. Doing this does not require a certificate lifetime of more than 3 months, neither does adding your site to the HSTS preload list.

RFC7469 suggests a max-age value of 2 months. It says nothing about what the lifetime of a useful certificate should be. You don't need to pin the leaf certificate, it's possible to pin using any certificate in the trust chain including the Let's Encrypt CA's, which is then independent of the lifetime of your certificate. This protects you from a compromise of any CA except Let's Encrypt. Let's say you don't trust Let's Encrypt not to be compromised though. HPKP is based on the *public key* of the certificate used. This is generated by the *client*, and can therefore remain constant for longer than the individual certificate lifetime as long as you re-use the same CSR (which you can do with Let's Encrypt).  

With DANE it's also possible to specify that certificates should only be accepted when issued by a certain CA, which is again independent of certificate lifetime. If you do want to tie TLSA records directly to your leaf certificates, as before, you can ensure they have the same public key. If they don't, it's easily scriptable to manage the DNS updates if you run your own DNS server or are using a cloud DNS solution which provides its own API.

**Comment by aeris** [comment]
> but with a sysadmin who will update all these things manually rather than scripting them

HPKP and DANE (and DNSSec) is **VERY** fragile. Need manual review after change and some time syncing not very simple to guess and automate (HPKP expiration delay for example).

> You don't need to pin the leaf certificate

Goal of HPKP and DANE is mainly to cancel the CA trust problem.
Pinning intermediate or root certificate is not the purpose.

> HPKP is based on the public key of the certificate used

Yep, and by default, Let’s Encrypt renew it ever 90d.
Possible to disable this behaviour, but as always now, we need « directly usable good configuration by default »

And for DANE, I agree, public key can be pinned, but also cert and currently not possible with Let’s Encrypt.

> It's easily scriptable to manage the DNS updates

No, not so simple with DNSSec (and DANE require it), and worse with KSK on a offline shadow master…

**Comment by FrancisRussell** [comment]
The purpose of DANE and HPKP is to reduce the chance of MITM attacks. Reducing the attack surface from the large number of CAs that you know little about to one CA that you've dealt with is a significant improvement. It allows you to avoid MITM attacks from CAs you don't trust. HPKP and DANE wouldn't support pinning intermediate certificates unless it provided a significant trust benefit.

Let's assume however that we don't want to trust any CAs, even Let's Encrypt.

You just stated that HPKP and DNSSec is *very* fragile and requires manual review. If it takes that much effort, it's unclear how this can compare to the one-time effort of adding a single command line option to the script that calls letsencrypt to use a CSR you generated. If things need to be easier, the answer is to add an option that forces the client to reuse the same CSR, not to issue certificates with longer lifetimes.

Yes, DANE supports pinning by a specific certificate. When does this provide a security advantage over pinning by public key? Since you've removed the CA from the trust model, a certificate is compromised only if its private key is compromised, which means you'd have to regenerate based on a new private key in both cases. Pinning by public key rather than by certificate is useful for when you have a site that has a extremely strict certificate rotation policy but are reusing the same keypair. Since you don't, there's no benefit from certificate pinning over public key pinning.

I acknowledge that scripting based on cert-pinning would be difficult, but it appears to have no benefit over public-key pinning as stated above.

**Comment by Skrupellos** [comment]
@HLFH to do DNSSEC (and other) rollovers I have created Sir Tificate https://github.com/Skrupellos/sir (sadly still not well documented, but there are some example config files and the source code of course). This works for me.

**Comment by Tasselhoff** [comment]
I got HSTS preloading for my little Raspberry Pi [https://penfold.fr](url) using Lets Encrypt. The HSTS duration seems decoupled to the certificate TLS Certificate lifetime (I've got A+ and 100% everything in SSLLabs).

**Comment by WebSpider** [comment]
When not publishing the certificate (which has an expiry), but using the public key instead (which has no expiry), this issue should no longer be present. The public key does not have an expiry, and using LE, you can specify which key/csr to use when updating your actual certificate.

Make sure you adapt your TLSA record type to 3 1 1 or 3 1 2 accordingly

**Comment by bmw** [comment]
Changing the length of the certificates offered by the Let's Encrypt CA are out of scope for the Certbot client. Feel free to open an issue at https://github.com/letsencrypt/boulder.
