### ISSUE TITLE
Feature request: parameter to list allowed TLDs

### ISSUE THREAD

**Issue by renne** [certbot/certbot#2152]
Hi,

on automated systems with a lot of domains a single unsupported TLD (like dotbit) causes an error with the need to manage the affected bunch of domains manually.

```
An unexpected error occurred:
The request message was malformed :: Error creating new authz :: Name does not end in a public suffix
```

Please add a parameter to the ACME client which lists the allowed TLDs in a script-comptatible style  to pre-filter allowed TLDs in cron-scripts.

**Comment by patf** [comment]
This is probably out of scope for the client since the CA server is responsible for this check, and getting that information to the client would require changes to ACME.

Let's Encrypt uses the [Public Suffix List](https://publicsuffix.org/list/) to verify domains end with official TLDs. You could parse this list to verify all your domains will be supported (there are libraries that help you with this for pretty much all major languages). This won't cover all cases (i.e. new TLDs that have just been added and are not in sync on the CA server yet), but should be good enough.

**Comment by dineshbhoopathy** [comment]
Strange, I tried to run it for a .la domain that's listed in the public suffix list but it errors 
"Requested domain  is not a FQDN"
thoughts ?

**Comment by patf** [comment]
What's the full domain? Is it an IDN by any chance? Those are currently not supported (ETA for IDN support: Before July 1, 2016).

**Comment by dineshbhoopathy** [comment]
Strange, it's not an IDN. mybrothershouse.la is the domain

**Comment by dineshbhoopathy** [comment]
actually I just updated the package and tried it, I no longer see the error.
