### ISSUE TITLE
ECDSA account keys

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#2209]
Similar to #2163, however there might be no support on the Boulder side at all yet.

**Comment by alex** [comment]
Boulder support was landed in https://github.com/letsencrypt/boulder/pull/1357

**Comment by kuba** [comment]
Oh, thanks once again, @alex!

**Comment by patf** [comment]
Related to this, it looks like it's currently not possible to revoke EC certificates using the certificate key. If I'm reading the stack trace correctly (see link below), this might be due to the request signing code only expecting (or supporting) RSA keys, so I'm guessing a fix for this issue would also solve the revocation issue. LMK if I'm missing something and this is a separate issue.

Further details: https://community.letsencrypt.org/t/cant-revoke-ec-certs-error-but-rsa-cert-revokes-ok/18820

**Comment by ageis** [comment]
Wrote a [related comment](https://github.com/certbot/certbot/issues/3349#issuecomment-325174114)a nd I support this absolutely. Are you having a hackathon soon? I'd probably ease into things better that way, but feel free to point me to low-hanging fruit for now.

**Comment by lnicola** [comment]
Bad bot

**Comment by atombrella** [comment]
I think this depends on finishing this class https://github.com/certbot/josepy/blob/master/src/josepy/jwk.py#L124
