### ISSUE TITLE
Allow selecting which domain name to use as common name

### ISSUE THREAD

**Issue by ids1024** [certbot/certbot#2325]
Using `letsencrypt --nginx` to create a certificate automatically populates a list of domains to create a certificate for, but as far as I can tell there is no way to select which is used for the certificate's common name, which is just taken from the first on the list.

**Comment by bmw** [comment]
Related #1031

**Comment by dak** [comment]
Related: When using a config file to generate certificates with multiple domains, the first domain listed is being used for the directory in `/etc/letsencrypt/live/`, but is not being used for the common name in the cert.

The common name appears to either be the last alphabetically, or the last domain in the domains list in the config.

**Comment by MarioLipinski** [comment]
According to @pde in #1031 reordering domains flags should work. It does not for me. Some random entry is used as CN in the CSR.

**Comment by bmw** [comment]
@MarioLipinski, unfortunately there was a problem in our last release breaking that feature (see #2798), however, our 0.6.0 release coming out later this week will fix the problem.

**Comment by schoen** [comment]
I believe this was indeed subsequently fixed since I've regularly seen people on the forums able to choose the CN that they want. Please reopen if there's some indication that it wasn't fixed in some context. Thanks!

**Comment by vlasbaard** [comment]
While #1031 is fixed for when you specify the domains using -d (it uses the first), this one is not.

If you let --nginx determine the hostnames by itself, it takes the first one, sorted alphabetically by  domain. 

Example, if you have:

aaa.bbb.com
zzz.abc.com

The common name for both will be zzz.abc.com.

With small lists of hostnames this isn't a problem since you can simply list them with -d, but with large ones it is. 

I have 47 on a single nginx, so for me it is a problem since now all 47 (which include ~40 different customers) show the hostname of one of them (that is a competitor of some of the others), that happens to have its domain start with an a.
