### ISSUE TITLE
Criteria for renewing with standalone and webroot conflict

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#2364]
If you have a lineage obtained with standalone and a lineage obtained with webroot, you can only renew at most one of them. The standalone lineage can only be renewed if no web server is listening, while the webroot lineage can only be renewed if a web server is listening!

**Comment by SwartzCr** [comment]
this seems like something people should fix in their renew scripts
For example you could call renew, then shut down your webserver, call it again, and restart your webserver.
I believe that's how we feel about standalone currently

**Comment by pde** [comment]
One problem is that they'll get error output / return codes from each run of the renewer in that case, making it hard to tell if there was some other problem.

**Comment by pde** [comment]
But probably we can live with that, or telling people to use `certonly`, temporarily.

**Comment by SwartzCr** [comment]
Is this resolved by --renew-hook? @bmw

**Comment by bmw** [comment]
I don't think so. The order certs are renewed is not defined, so let's say `certbot renew` needs to renew one cert with standalone and one with webroot. While you're able to use `--renew-hook` start/stop your server after the first issuance with `--renew-hook`, you're unable to do this for the first cert.

Additionally, you could have multiple certs of each type and you have no way of knowing whether standalone or webroot will be used for the next cert to be renewed.

**Comment by SwartzCr** [comment]
But could you use the domain name info to decide if you needed to stop or start your server?
I guess that is very hacky... but possibly a solution

**Comment by bmw** [comment]
To flesh out my explanation above with an example, imagine you have to renew `standalone.example.org` and `webroot.example.org` where each domain uses plugin included in the domain. You could write a renew hook like:
```
if [ "$RENEWED_DOMAINS" = "webroot.example.org" ];
  service lighttpd start
else
  service lighttpd stop
fi
```
Using this script, the sequence of events is:
1. User runs `certbot renew`
2. Domain A is attempted to be renewed
3. Renew hook is run with domain A
4. Domain B is attempted to be renewed
5. Renew hook is run with domain B

You have no way of knowing in advance whether domain A is "webroot.example.org" or "standalone.example.org".

What's the problem with this? Since domain A is attempted to be renewed before your hook is run, you don't have a chance to start or stop your server. Similarly, you can't do this before running Certbot because you don't know which domain will be attempted to renewed first.

Personally, I'm not very worried about this issue until I see a real use case for it. Why can't you use the same plugin for both domains? I believe you'd have the same problem with standalone and the Apache/Nginx plugins as well (unless you've configured Apache/Nginx to not handle unencrypted HTTP traffic and standalone to do the HTTP challenge).

**Comment by bmw** [comment]
This issue has been closed due to lack of activity, but if you think it should be reopened, please open a new issue with a link to this one and we'll take a look.
