### ISSUE TITLE
Fix --csr by separating it from --no-lineages

### ISSUE THREAD

**Issue by pde** [certbot/certbot#2373]
Currently, the `--csr` flag breaks under many circumstances because it implies a whole bunch of variations on how certs are stored.  None of that seems logically necessary.  `--csr` can work perfectly well with storage.py (it should probably imply `--domains <contents of CSR>`, etc) and we can have another flag (perhaps `--no-lineages` or `--dump-cert` or something) that causes the store-certs-in-the-current-directory-without-lineages behaviour.

**Comment by pde** [comment]
This might be a good task for a volunteer who is comparatively strong in following threads through large codebases.

**Comment by schoen** [comment]
I think for 0.4.0 we have a suggestion in one of the PRs to print more
useful error messages when csr is set (to explain that it currently
doesn't work for the renew verb). It's true that we can do better in
terms of making csr actually work in more contexts in the future.

**Comment by bmw** [comment]
The reason for this is `--csr` was designed so you don't have to provide your private key to the client and creating a lineage requires they key.

**Comment by pde** [comment]
@bmw, right, so if you want to supply a CSR and have a normal lineage created in `/etc/letsencrypt` for you, you'll need to supply `--key-path`.  *Conceivably* you could even do that and not have the key file be readable by the Certbot process.

**Comment by jtl999** [comment]
Maybe have some sort of null placeholder instead of the key?

**Comment by bmw** [comment]
There needs to be a design conversation about this before anyone tries to implement it. If anyone is interested, let's chat!

**Comment by St-Ranger** [comment]
I have a suggestion that is related, so, I am posting it here, instead of a separate issue (feel free to split it into a separate issue, if that's more convenient).

1. When I was starting using certbot, I was surprised that it didn't ask me a bunch of questions related to the certificate, which were always asked when I was generating CSRs using openssl, the questions used to generate the "Subject:" line of the CSR (C= .., ST= ..., L= .., O=..., OU=..., CN=..., .

I figured out that it is not offered because Letsencrypt is not issuing [EV](https://en.wikipedia.org/wiki/Extended_Validation_Certificate) certificates, but only [domain-validated](https://en.wikipedia.org/wiki/Domain-validated_certificate).
I don't think it is addressed anywhere in the documentation explicitly. So, I am tagging the documentation issue #4370 here. (I know, that @pconrad-fb is trying to converge on the changes made there and commit them, so, maybe it will be a subsequent iteration step there..)

2. Moreover, since there is an option `--csr` , and it is possible to provide your own CSR (albeit with the restrictions on how that would work), the question that doesn't seem to be addressed at all is: "What would happen if I provide a CSR with the Subject: and all those fields?"
That may be worse being discussed somewhere in the documentation explicitly. 

I was still curious: will it not get validated, or those fields would be dropped (except for CN)?
`localhorst` on IRC told me that those fields will be dropped.

3. And (more academic, but probably still relevant in some real-life use cases) yet another question:
The CSR generated by certbot doesn't contain any requests for the X509v3 extensions (except for SAN), but the CA server issues:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Server Authentication, TLS Web Client Authentication
I understand that the CA server will ignore the requests for a broader key usage (again, it is not documented that it will just drop those requests, but will issue the cert nevertheless). But what would happen if the CSR will have a request for a more restrictive subset? Naively, I'd think that the CA shouldn't object that, but I've been told (by the same helpful <localhorst>), that those requests would be still ignored.
Why is this important? If one wants to have separate certificate for, say, "server" and "client" authentication functionality, it should be possible to have different Extended Key Usage in those, and make them "Critical".

(Just in case, - I find this reference helpful for understanding these functions: https://www.ibm.com/support/knowledgecenter/en/SSKTMJ_8.0.1/com.ibm.help.domino.admin.doc/DOC/H_KEY_USAGE_EXTENSIONS_FOR_INTERNET_CERTIFICATES_1521_OVER.html )

So, it might be worth reflecting all this functionality related to CSRs in the documentation explicitly.
