### ISSUE TITLE
Apache installer has trouble with missing vhost on renewal

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#2491]
I'm not sure whether this is related to the other vhost issues or not.

https://community.letsencrypt.org/t/help-us-test-renewal-with-letsencrypt-renew/10562/7

Can anybody understand what the difficulty was here and how the error message could have been more helpful?

**Comment by pde** [comment]
The prevalence of this problem was somewhat reduced by #1991, but only for people who are installing for the first time.  If they've already installed, they may have these vague wildcard HTTP and TLS vhosts, and the client won't know which one to pick.  We can tell people to manually add their hostnames as `ServerName` and `ServerAlias` entries to the TLS vhost, or we could try to recognise when past versions of the client might have facilitated this situation.  But the latter would be quite tricky to do...

**Comment by joohoi** [comment]
Closing that issue as old and fixed. We do support wildcards in ServerAlias now and a lot has happened in vhost discovery.
