### ISSUE TITLE
letsencrypt-auto should perform version comparison before "upgrading" itself

### ISSUE THREAD

**Issue by pde** [certbot/certbot#2500]
Then we'll be safe from downgrade attacks. And people can run the copy from the `letsencrypt-auto-source` directory before its released.

**Comment by bmw** [comment]
This actually came up in a discussion recently about features that other upgrade systems have and `certbot-auto` doesn't.

If we stick with `certbot-auto`, I think we should definitely consider doing this.

**Comment by erikrose** [comment]
I think it's literally as simple as changing the comparison operator.

**Comment by adferrand** [comment]
Hum. Line 1644 of `certbot-auto`/`letsencrypt-auto` on master:
`elif [ "$LE_AUTO_VERSION" != "$REMOTE_VERSION" ]; then`

For me, current version of `certbot-auto` is already compared to latest version available, and self-upgrade is triggered only if versions differ. At least, on a Ubuntu 14.04 LTS, I see the expected behavior.

Or did I miss something ?

**Comment by bmw** [comment]
The change Peter suggested here is to prevent an attacker from being able to cause certbot-auto to downgrade itself to an older version.

The way this would work is someone would intercept your connection to PyPI. This connection uses HTTPS which thwarts trivial attempts, however, there are a few ways a more sophisticated attacker could accomplish this in theory. If they are able to do this, they could report to `certbot-auto` that an older version of Certbot is the latest one available. When this simple inequality check of `[ "$LE_AUTO_VERSION" != "$REMOTE_VERSION" ]` runs, if `certbot-auto` is not the same version as the version reported by the attacker, `certbot-auto` will happily replace itself with an older version of `certbot-auto` and Certbot. Ideally, `certbot-auto` should only accept upgrades to a newer version.

This is unlikely to happen and the damage caused by downgrading Certbot is likely to be relatively minimal (as all I can think of off the top of my head is causing renewal to fail), however, it's an attack that `certbot-auto` is not protected against.

**Comment by adferrand** [comment]
Yes I understood that after my first response ^^

It makes sense also in particular when you want to test a built `certbot-auto` from the sources, where current version is `0.28.0.dev0` for instance, and will lead to an undesired downgrade. You cannot test directly new logic in `certbot-auto` basically.

But for attackers, well, I am not convinced: if an attacker has the ability to fake your connection to PyPI, it will be able also to advertize a false new version and provide from the fake URL a forged `certbot-auto` script. In this case, downgrade approach is not sufficient.

Anyway, it does not hurt, PR on the way.

**Comment by bmw** [comment]
> It makes sense also in particular when you want to test a built certbot-auto from the sources, where current version is 0.28.0.dev0 for instance, and will lead to an undesired downgrade.

This is a good point. In the past, we've had to carefully ensure `--no-self-upgrade` was provided on the command line to test behavior here.

> But for attackers, well, I am not convinced: if an attacker has the ability to fake your connection to PyPI, it will be able also to advertize a false new version and provide from the fake URL a forged certbot-auto script.

Yes and no. We do [additional signature checking](https://github.com/certbot/certbot/blob/36ebce4a5fa30a0e73bd8656aea54ded2e9d982e/letsencrypt-auto-source/pieces/fetch.py#L111) on the version of `certbot-auto` we downloaded which significantly complicates things for an attacker trying to do this.

With that said, we don't do any checks that the version of `certbot-auto` we downloaded is actually the version we expect so this is another area where we are potentially subject to a downgrade attack. Fixing this is slightly more difficult.

I also wonder what other upgrade mechanisms who claim to have protections around downgrade attacks do about this (if anything). This attack in general came up recently as an example of something upgrade systems written and maintained by others supposedly offer which our custom `certbot-auto` script does not.

> Anyway, it does not hurt, PR on the way.

Great! I don't think this is a super high priority, but it's nice to get it out of the way.

One thing I'll add which I said in our packaging doc is I don't think we can simply change the comparison operator here as I believe the only comparison POSIX shells can do between two strings is testing for equality. See http://pubs.opengroup.org/onlinepubs/9699919799/utilities/test.html. Bash offers more options, but unfortunately we have to work in more shells than just bash.

**Comment by adferrand** [comment]
You can rely on GNU `coreutils`, that provides `sort -V`. Quite reasonable that it is available on a system, otherwise you have waaaay more serious things to handle on your broken system before running certbot.

Yes, not big priority, but it is short, I have time, and it will not interfere with my assignements. By the way, I accepted the collaborator invitation, to not hesitate to assign me the issues we discussed, it will be easier to track them down.

**Comment by bmw** [comment]
> You can rely on GNU coreutils, that provides sort -V. Quite reasonable that it is available on a system, otherwise you have waaaay more serious things to handle on your broken system before running certbot.

I actually don't think we can because `certbot-auto` also has some support for systems other than Linux such as macOS and FreeBSD. `sort` is available, but the `-V` option is not.

I'm open to other options but we do have Python installed at this point in execution. Perhaps we can just use that.

> Yes, not big priority, but it is short, I have time, and it will not interfere with my assignements. By the way, I accepted the collaborator invitation, to not hesitate to assign me the issues we discussed, it will be easier to track them down.

Will do! Feel free to mention me on issues/PRs if you want me to change assignees, add tags, etc.

**Comment by bmw** [comment]
This was fixed in #6448.
