### ISSUE TITLE
Add --key-type flag

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#2625]
The client should support a `--key-type` flag, values `rsa`, `p256`, or `p384`, to make it easy to generate ECDSA certificates.

**Comment by nitmir** [comment]
:+1:

**Comment by ageis** [comment]
Great idea; I love it, but don't forget that we presently default to SHA256 to my knowledge... so why not have an option allowing users to increase that SHA384 or SHA512 too?

Speaking of which, when will [BLAKE2b](https://en.wikipedia.org/wiki/BLAKE_(hash_function)#BLAKE2) go mainstream!

Shouldn't Brainpool be in the curve list too? Or `ed25519`, and `sect###(k|r)1` since the others are @usNISTgov cuves? I still get confused sometimes between the cipher algorithms, key exchange, (ECDHE w/ RSA not bad) and HMACs/hashes/digests, sadly. :sob:

**Comment by jsha** [comment]
FYI, see https://github.com/certbot/certbot/pull/2660; implementation is somewhat stalled out on decisions about storage.

Right now, the listed curves are the only ones valid for issuance under the BRs, but ed25519 will probably come down the pipe soonish.

**Comment by ChadTaljaardt** [comment]
@jsha Has there been any updated regarding this?

**Comment by lnicola** [comment]
I think there's still a lot of interest in ECDSA support.

**Comment by TaaviE** [comment]
Boulder supports [ECDSA](https://github.com/letsencrypt/boulder/pull/1357) for a while now. What's blocking implementing this? PRs are going stale, roadmaps have been changed multiple times already.

**Comment by ali-alsabbah** [comment]
Hello, I’d like to work on this.

**Comment by TaaviE** [comment]
https://github.com/certbot/certbot/pull/7247 There's work being done on this already

**Comment by ali-alsabbah** [comment]
> @ali-alsabbah there's work being done on this already here #7247 .

I see. Do you know of any issues where I can contribute? Should I just browse through the help-wanted label? I did join the Mattermost channel also.

**Comment by TaaviE** [comment]
@ali-alsabbah 
Check out https://github.com/certbot/certbot/issues?q=is%3Aopen+is%3Aissue+label%3Aeasy-fix

**Comment by bmw** [comment]
This was added in https://github.com/certbot/certbot/pull/8444 and will be included in our next release.
