### ISSUE TITLE
Circumstances for deletion of key material

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#269]
Are there circumstances in which we would actually delete private keys?

(If so, we should use a secure deletion tool so that the private key isn't left behind on the hard drive afterward -- though on some filesystems we still can't guarantee that that won't happen.)

**Comment by jdkasten** [comment]
This is an excellent point.  There shouldn't be any code that removes key material except for the authorized key backups removed during revocation.  

I know that in general this is an extremely difficult problem to handle without a hammer.  Do you know of any decent python libraries that attempt to use the drive's secure delete functionality?

**Comment by jdkasten** [comment]
Did a bit of digging... and spoke with @schoen about this.
I didn't find any python libraries that attempt to provide the functionality so that is going to leave us with calling out to run the command.  (This should probably be a new function in le_util.py)

Given the current client and focus, I think it makes the most sense to call out to ```shred```, but the command should be configurable.  (```shred``` isn't perfect and doesn't aim to support too many scenarios)

Anyone know the landscape a bit better and have a better suggestion?

**Comment by ohemorange** [comment]
We don't ever delete private keys. If we ever do, feel free to reopen this issue!
