### ISSUE TITLE
Split cli_tst.py?

### ISSUE THREAD

**Issue by pde** [certbot/certbot#2716]
The incentive to do this is fairly low compared to the crazy amount of work involved, but `cli_tst.py` should probably be split into pieces to test `main`, `cli` and `plugins.selection` separately.

**Comment by pde** [comment]
The big problem is that most tests in that file use some variant of `_call` as their entry point; they will need to change to calling more specific targets, which basically means rewriting a *lot* of tests.

**Comment by pde** [comment]
One small cleanup this would allow: switching things like `from letsencrypt.plugins import disco as plugins_disco` ... `plugins_disco.PluginsRegistry.find_all()` to just `from blah import PluginsRegistery` .. `PluginsRegistry.find_all()`.

**Comment by bmw** [comment]
I think this should definitely be done at some point. I think it will almost be easiest to write the tests from scratch.

If someone takes a crack at this, it'll be much easier to write them as unit tests, testing only a specific function or two at a time, instead of always calling `main.main` and having to mock out a dozen classes/functions.
