### ISSUE TITLE
Disable line wrapping in --text mode

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#2754]
When I run with `--text`, I get these lines as output:

```
Congratulations! You have successfully enabled https://02e645.le-test.hoffman-
andrews.com

You should test your configuration at:
https://www.ssllabs.com/ssltest/analyze.html?d=02e645.le-test.hoffman-
andrews.com
```

These lines are artificially wrapped at 80 characters, even though my terminal is much wider than that. This breaks the links and makes them (a) unclickable and (b) hard to paste into a browser.

I think with `--text`, we shouldn't wrap lines, but leave it to the user's terminal.

**Comment by pde** [comment]
This is a good first ticket for a volunteer.  The line wrapping happens in [https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/display/util.py#L202](FileDisplay) and [https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/display/util.py#L449](NoninteractiveDisplay) and should be easy to remove; it'll mostly be a matter of checking that everything looks sane afterwards.

**Comment by bmw** [comment]
Copied from my comment [here](https://github.com/certbot/certbot/pull/2795#issuecomment-221403893):

So after talking to jsha out of band, we decided that the output above does look pretty bad and we have another solution. Sorry for changing our position on this, but since you've identified all places we use text wrapping in order to write this PR, implemented the new solution should be pretty easy if you're still interested.

The main problem identified in #2754 is we break things like URLs that would normally be clickable in a terminal. `textwrap` has options [break_long_words](https://docs.python.org/2/library/textwrap.html#textwrap.TextWrapper.break_long_words) and [break_on_hyphens](https://docs.python.org/2/library/textwrap.html#textwrap.TextWrapper.break_on_hyphens) which solve this problem. Using the examples, provided [here](https://github.com/certbot/certbot/issues/2754#issue-145527636), output becomes:

```
Congratulations! You have successfully enabled
https://02e645.le-test.hoffman-andrews.com

You should test your configuration at:
https://www.ssllabs.com/ssltest/analyze.html?d=02e645.le-test.hoffman-andrews.com
```
which solves the problem and still allows for text wrap to make the output look a little better.
