### ISSUE TITLE
Duplicate certificate gets created if renewal/*.conf is missing/broken

### ISSUE THREAD

**Issue by ffittschen** [certbot/certbot#2814]
I wanted to renew my certificates, but `./letsencrypt-auto renew` failed, because the `.conf` files in the `/etc/letsencrypt/renewal` directory are not up to date anymore (created using apache + letsencrypt apache plugin, but I switched to nginx)

So I moved the file into a tmp directory and ran `./letsencrypt-auto certonly --rsa-key-size 4096 --webroot -w /var/www/html/mydomain.com/public_html/ -d mydomain.com -d www.mydomain.com -w /var/www/html/subdomain.mydomain.com/public_html/ -d subdomain.mydomain.com --text -v`

Since the docs stated that the `--duplicate` flag defaults to `false`, I thought it would renew my existing certificate (the domains and their order are the same as in the original certificate request). But instead it created a new `mydomain.com-0001` certificate 😔 See the `WARNING` in the log below

This did not happen when I used the `--dry-run` flag!

Is this the correct behaviour? And is there any way to get asked if the CLI really should create a `-0001` certificate?

```
Checking for new version...
Requesting root privileges to run letsencrypt...
   /root/.local/share/letsencrypt/bin/letsencrypt certonly --rsa-key-size 4096 --webroot -w /var/www/html/mydomain.com/public_html/ -d mydomain.com -d www.mydomain.com -w /var/www/html/subdomain.mydomain.com/public_html/ -d subdomain.mydomain.com --text -v
2016-04-11 20:49:30,574:INFO:letsencrypt.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-04-11 20:49:30,771:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-04-11 20:49:31,073:WARNING:letsencrypt.main:Renewal conf file /etc/letsencrypt/renewal/mydomain.com.conf is broken. Skipping.
2016-04-11 20:49:31,089:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-04-11 20:49:31,435:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-04-11 20:49:31,799:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-04-11 20:49:32,147:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
```

**Comment by bmw** [comment]
> I wanted to renew my certificates, but ./letsencrypt-auto renew failed, because the .conf files in the /etc/letsencrypt/renewal directory are not up to date anymore (created using apache + letsencrypt apache plugin, but I switched to nginx)
>
> So I moved the file into a tmp directory and ran ./letsencrypt-auto certonly --rsa-key-size 4096 --webroot -w /var/www/html/mydomain.com/public_html/ -d mydomain.com -d www.mydomain.com -w /var/www/html/subdomain.mydomain.com/public_html/ -d subdomain.mydomain.com --text -v

While usually documented with [renewal](https://letsencrypt.readthedocs.org/en/latest/using.html#renewal), the client actually has support for changing the options used for renewal. If you left the file in `/etc/letsencrypt/renewal` unmodified and ran ran the `./letsencrypt-auto` command above with the exact domains in the certificate you wanted to modify, the renewal conf file would be updated to contain the values you provided on the command line. When you ran `letsencrypt-auto renew` in the future, it would use the webroot plugin, not Apache.

> Since the docs stated that the --duplicate flag defaults to false, I thought it would renew my existing certificate (the domains and their order are the same as in the original certificate request). But instead it created a new mydomain.com-0001 certificate ￼ See the WARNING in the log below

The reason the client appended `-0001` was because it saw that there was a corrupted lineage for `mydomain.com` (the renewal conf file was missing). Rather than overwriting your symlinks/certificates, it opted to create a new directory.

> This did not happen when I used the --dry-run flag!

`--dry-run` doesn't store the resulting certificates so this is to be expected. Perhaps `--dry-run` could tell you where the resulting certificates would have been saved?

> Is this the correct behaviour? And is there any way to get asked if the CLI really should create a -0001 certificate?

This is the current expected behavior of the client. We need better documentation for the files and directories in `/etc/letsencrypt` so users can know what they can/should do in situations like these.

The problem with adding new prompts like this is a number of users have written scripts/automation around `letsencrypt`. Adding new prompts like this would break their configuration, however, there are issues like #2128 which request a way to specify the name on the command line.
