### ISSUE TITLE
I got stucked when I use ./letsencrypt-auto

### ISSUE THREAD

**Issue by Jaggle** [certbot/certbot#2832]
the screen don't show any help message but seems to be checking dependences,and then it stucked at "Installing Python packages..."，and actually I have installed python already

**Comment by bmw** [comment]
The "Installing Python packages..." step may take a few minutes. Unfortunately, `letsencrypt-auto` hides all `pip` output, even in when `--verbose` is provided on the command line (there can be quite a bit of output sometimes). I created #2835 to track that issue.

In the meantime, if you think you gave `letsencrypt-auto` enough time on your system, you can install our Python dependencies manually to see if you get the same behavior.

1. Run `export XDG_DATA_HOME=${XDG_DATA_HOME:-~/.local/share}` to create an environment variable for where to install the Python virtual environment.

2. Run `rm -rf $XDG_DATA_HOME/letsencrypt` to remove any partial installation that may exist.

3. Run `virtualenv --no-site-packages --python $(command -v python2.7 || command -v python27 || command -v python2 || command -v python) $XDG_DATA_HOME/letsencrypt` to create a new virtual environment.

4. Upgrade your virtual environment `curl https://raw.githubusercontent.com/letsencrypt/letsencrypt/v0.5.0/letsencrypt-auto-source/pieces/pipstrap.py | PATH=$XDG_DATA_HOME/letsencrypt/bin:$PATH $XDG_DATA_HOME/letsencrypt/bin/python -`

5. Install `letsencrypt` and it's dependencies. `$XDG_DATA_HOME/letsencrypt/bin/pip install --no-cache-dir --require-hashes -r <(curl https://raw.githubusercontent.com/letsencrypt/letsencrypt/v0.5.0/letsencrypt-auto-source/pieces/letsencrypt-auto-requirements.txt)`

If you're still with me, you will have just accomplished the same thing as `letsencrypt-auto`. If the script hung, please let us know where, otherwise, you can now use `letsencrypt-auto` which will recognize that `letsencrypt` has been installed.

**Comment by ArianeLu** [comment]
Checking for new version...
Creating virtual environment...
Installing Python packages...
Installation succeeded.
Requesting root privileges to run letsencrypt...
   /root/.local/share/letsencrypt/bin/letsencrypt --help
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 7, in <module>
    from letsencrypt.main import main
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/main.py", line 13, in <module>
    from acme import jose
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/acme/jose/__init__.py", line 37, in <module>
    from acme.jose.interfaces import JSONDeSerializable
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/acme/jose/interfaces.py", line 9, in <module>
    from acme.jose import util
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/acme/jose/util.py", line 5, in <module>
    import OpenSSL
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /root/.local/share/letsencrypt/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: undefined symbol: EC_GROUP_new_curve_GF2m

**Comment by eugenedw** [comment]
Seeing the same issue on AWS, Amazon Linux v. 2014.09 with Python 2.7. Running OS upgrade to latest 2016.03 to see if problem is either resolved or better described upon failure.

**Comment by stoxford** [comment]
Using the five steps listed above, installation of cffi in step 5 is taking hours without completing. The last output is:

`Running setup.py install for cffi ... \`

I'm running Ubuntu Server 16.04 LTS on AWS micro. Nginx is my web server.

**Comment by bmw** [comment]
It taking six hours to install our `cffi` dependency certainly isn't normal. Running step 5 on an Ubuntu Server 16.04 LTS on a Digital Ocean droplet with 512MB of RAM takes less than a minute.

While they're a few versions behind, if you're on Ubuntu 16.04, there are OS packages available. Simply run `apt-get install letsencrypt` to install them.

**Comment by stoxford** [comment]
I'm following the DigitalOcean instructions for "[How To Secure Nginx with Let's Encrypt on Ubuntu 16.04](https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04)". It says that by running letsencrypt-auto I should have gotten dialog boxes asking for my email address and asking me to accept the terms of service. Following your five steps above, I never got those. Also, no /etc/letsencrypt/live directory was created. Trying to run letsencrypt-auto after following your five steps above just causes it to hang again.

I'll try out the OS packages.

**Comment by stoxford** [comment]
OK, I just ran letsencrypt-auto for a few hours. I expected the dialog box to look like this:

![le-email](https://cloud.githubusercontent.com/assets/19688025/15742057/b690f2bc-288a-11e6-9296-4b635937ad47.png)

This is what it actually looks like:

![emailinputdialog](https://cloud.githubusercontent.com/assets/19688025/15742067/c097612e-288a-11e6-845f-a127daa674d8.png)

I'm on Windows 7 connecting to AWS using Putty & SSH. I don't know if it's a new bug, a result of a bad build, or just a consequence of using Putty. I think it's probably a bit off topic for this issue, but don't know if it deserves opening a new issue.

**Comment by bmw** [comment]
> It says that by running letsencrypt-auto I should have gotten dialog boxes asking for my email address and asking me to accept the terms of service. Following your five steps above, I never got those. Also, no /etc/letsencrypt/live directory was created.

The 5 steps I posted above just install the project. You have to actually run it to get dialog boxes or the `/etc/letsencrypt` directory.

> Trying to run letsencrypt-auto after following your five steps above just causes it to hang again.

That's because those directions install the version of the project that was available a couple months ago when I wrote that post. `letsencrypt-auto` automatically updates to the newest version, so when it sees an old version is installed, it tries to update it. While I updated the instructions above, you can get around this by running `$XDG_DATA_HOME/letsencrypt/bin/certbot` directly.

> I'm on Windows 7 connecting to AWS using Putty & SSH. I don't know if it's a new bug, a result of a bad build, or just a consequence of using Putty. I think it's probably a bit off topic for this issue, but don't know if it deserves opening a new issue.

This issue is documented at #2025. You can get around it by running the client with `-t` flag which will use a simple text interface.

**Comment by TakehikoShimojima** [comment]
Amazon Linux:

On step 5,
Collecting python2-pythondialog>=3.2.2rc1 (from certbot==0.9.3->-r /dev/fd/63 (line 178))
In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    python2-pythondialog>=3.2.2rc1 from https://pypi.python.org/packages/26/34/b4cf8018dbc51e8a0fae2c51a0dd2c1f34419caa9e3eb83646c73d1beb9d/python2-pythondialog-3.4.0.tar.gz#md5=554d611d435dcc072132586c1cb37ca5 (from certbot==0.9.3->-r /dev/fd/63 (line 178))

Please tell me what's wrong and how to fix it.

**Comment by itbdw** [comment]
Try https://github.com/certbot/certbot/issues/2516

**Comment by magnusbj** [comment]
Hi, I'm running an AWS micro, ubuntu 14.04, 500mb ram. When the docker with the web server was running, installing python packages halted with ./certbot-auto and the above instructions. 

I ran htop on another ssh client, and saw that memory was maxed out on the AWS.

Then I stopped docker with database and webserver, and verified in htop that memory was freed up.

In 1,2,3 ./certbot-auto did it's update, and worked perfect.

Rolled the server back up, and felt I could have saved me some heart burn with stopping docker and checking htop first.

**Comment by sydneyli** [comment]
Hi! If you're still having trouble installing Certbot on your system, I'd suggest checking out the [Let's Encrypt Community Forums](https://community.letsencrypt.org/c/help), where you'll get help faster from a large number of people who are familiar with the project.

**Comment by GiovanH** [comment]
> 5\. $XDG_DATA_HOME/letsencrypt/bin/pip install --no-cache-dir --require-hashes -r <(curl https://raw.githubusercontent.com/letsencrypt/letsencrypt/master/letsencrypt-auto-source/pieces/letsencrypt-auto-requirements.txt)

This doesn't work anymore, because `curl https://raw.githubusercontent.com/letsencrypt/letsencrypt/master/letsencrypt-auto-source/pieces/letsencrypt-auto-requirements.txt` is a 404.
