### ISSUE TITLE
https://letsencrypt.org/getting-started - Documentation shows letsencrypt instead of letsencrypt-auto

### ISSUE THREAD

**Issue by deragon** [certbot/certbot#2834]
On https://letsencrypt.org/getting-started/, the command that is referenced everywhere is `letsencrypt`, which results with the following error:

`-bash: ./letsencrypt: Is a directory`

It should be replaced everywhere with `letsencrypt-auto`.

**Comment by othatbrian** [comment]
Under the first block title ***Installing Client Software***, it states:

> If your operating system includes a packaged copy of the `letsencrypt` client, install it from there and use the letsencrypt command. Otherwise, you can use our `letsencrypt-auto` wrapper script to get a copy quickly:
>
> $ git clone https://github.com/letsencrypt/letsencrypt
> $ cd letsencrypt
> $ ./letsencrypt-auto --help
>
> `letsencrypt-auto` accepts the same flags as `letsencrypt`; it installs all of its own dependencies and updates the client code automatically (but it’s comparatively slow and large in order to achieve that).

Basically, there are two options for clients: `letsencrypt` (a "native client" operating system package, which may or may not be available on your particular platform) and `letsencrypt-auto` (a downloadable, "all inclusive", python-based client). They function identically. The documentation had to choose one or the other command, and they chose to use `letsencrypt`.

You're getting the `-bash: ./letsencrypt: Is a directory` because you didn't `cd letsencrypt` before trying to run the command (and `letsencrypt` is the name of the directly created by cloning the repo).

Why they didn't just call that script `letsenrypt` as well, I'm not sure, but maybe they had reasons.

Hopefully this helps!

**Comment by ye** [comment]
Thanks @othatbrian for the detail explanation. `letsencrypt` or `letsencrypt-auto`, either way, Getting Started guide should fix the documentation (it's why I got tripped up and ended up here). That is, use `letsencrypt-auto` or install `letsencrypt`.

Btw, `letsencrypt` is NOT a native client. It's simply a python package. The entire project is 84.4% Python ATM as seen on the project page.

**Comment by bmw** [comment]
The repo for letsencrypt.org is now public at https://github.com/letsencrypt/website. Additionally, it appears that this issue has been resolved.
