### ISSUE TITLE
Point letsencrypt-auto to the new package on PyPI

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#2839]

**Comment by bmw** [comment]
We have two options here:

1. Release a 0.5.0 version of `certbot` containing shim packages around `letsencrypt`. This is a fair amount of extra work to create temporary shim packages so `letsencrypt-auto` continues to work and pass tests until the 0.6.0 release.
2. Wait to do this until the 0.7.0 release. Have `certbot-auto/letsencrypt-auto` use the `letsencrypt` shim packages during 0.6.0. This means `*-auto` has to download two extra packages (`letsencrypt` and `letsencrypt-apache`) and we'll have to do an `0.7.0` release of the shim packages to allow `*-auto` to update to the new version of itself that points to the `certbot` packages.

I'm in favor of option 2. Either approach involves doing another release of shim packages and we already have the `letsencrypt` shim packages. Additionally, there is still plenty of work to be done for 0.6.0 and there is less of a deadline for 0.7.0

cc @SwartzCr

**Comment by SwartzCr** [comment]
This problem exists because as soon as we make a merge pointing away fro pypi's le-auto all of our tests break since there isn't a cb package in pypi since we haven't done a release

@hlieberman has suggested doing the merge in private, pushing it to pip and then do the release in public.
I think we're all in agreement that there's not much scary with doing this in two seperate releases since the 'extra packages' that people will have to download are just the shim packages - and if we trust them a little it's fine to trust them for everyone (?) but also we'll update cb-auto in the 0.7.0 release to stop pointing at them

I'm in favor of Harlan's rogue plan - as long as people are in the office to do it, or for option 2. But we can decide closer to the release since neither really take much additional coding now

**Comment by pde** [comment]
I'm in favour of the plan that's less work here.  It could be 0.7.0, or even just 0.6.1.  In fact, we could release 0.6.0 and 0.6.1 at basically the same time.

**Comment by SwartzCr** [comment]
that was discussed, the thought was that that'd be the same amount of release work as releasing 0.6.0 and 0.7.0 - but if you're fine with doing two back to back releases I think that'd be fine

**Comment by bmw** [comment]
We decided to do this in a later release.

**Comment by bmw** [comment]
After doing this, we should continue to install the `letsencrypt` package as well to support people reaching into the venv.

**Comment by bmw** [comment]
Fixed in #3026.
