### ISSUE TITLE
Allow webroot to use the TLS SNI challenge

### ISSUE THREAD

**Issue by iangelov** [certbot/certbot#2861]
Hi guys - excellent work, thank you for that.

As usual there's are some minor rough edges - in this case, for me, that's the fact that the webroot plugin doesn't work with the TLS challenge - which is a bit annoying, since I don't have port 80 open and thus I can't properly automate certificate renewal.

Since renewal takes place before the certificate has expired, I think it makes sense to allow the webroot-powered renewal process to work with the TLS challenge - no need to add plugins for that particular type of web server/reverse proxy/load balancer, only a specific path would be used for this as opposed to a whole port (the standalone plugin). Makes it easy to work around limitations that different environments have - in my case, for example, I've haproxy fronting nginx.

**Comment by kuba** [comment]
How would such plugin work? At some point it must create a self-signed cert and what would it do with it? How would you server software pick it up?

**Comment by iangelov** [comment]
I'm only interested in this for renewal purposes, where the whole configuration is already in place.

So, the flow would be something like this:

- obtain a certificate - could even be a manual step if you like
- configure everything (point to 
- automated renew: challenge request -PORT 443/HTTPS-> firewall -HTTPS-> lb (TLS terminated here, SNI read here) -HTTP-> web server -> webroot

**Comment by kuba** [comment]
I understand what the traffic flow is. The part I don't understand is the automation for challenge-response workflow that you're requesting. Webroot solves the challenge by dropping the files into directory served by a HTTP server. Is your software stack capable of picking up a self-signed certificate that letsencrypt plugin would spit out to a disk during the process? What LB software are you using?

Or did you just confuse "webroot" with "manual" (you're requesting non-automatable solution)? FTR https://github.com/letsencrypt/letsencrypt/blob/3961b70debeb228de88751fb4c4cad0058fcd047/certbot/plugins/manual.py#L36.

**Comment by aptalca** [comment]
I'd like to echo iangelov's request. I created a docker container that has nginx with letsencrypt renewal built-in. Most of the users are running this container on NAS systems, where port 80 is reserved for the NAS gui, and some others have their port 80 blocked either on the router or by their ISP. There are many reasons for not being able to use port 80 on a home web server.

The standalone plugin has the tls-sni-01 option that works beautifully for verification through port 443. But the webroot method does not currently have such an option (only port 80).

I am happy to use the standalone plugin to generate the certs the first time. After that, I would like to be able to use the webroot plugin to renew them so that I don't have to take the existing webserver offline during renewals.

Also, the newly added renew parameter in the auto script doesn't have the ability to temporarily take down the other webserver if a renewal is needed. So if you set it to run with renew every night, you have to take the webserver offline every night in case the auto script decides to renew. The other option is to not use the renew parameter, and instead implement a different algorithm that tries and figures out whether the certs need to be renewed, and then force a renewal with the auto script (why reinvent the wheel when the auto script already has that algorithm built-in)

**Comment by chenze** [comment]
Yes if the webroot renewal can be done through port 443 it would be great

In our environment all services are served via HTTPS. I don't really want to open the Port 80 temporarily just to renew the certs

I'm fine with non-HTTPS port 80 for the first time we request the certs. It is just all about renewal

**Comment by precurse** [comment]
In my case, port 80 is blocked entirely (go Canadian ISPs!) and my only option is port 443.  Standalone works great when I'm first getting a cert, but renewing requires me to shutdown my web server so that I can use standalone tls-sni-01 to renew.  Sure, it's a small window the server needs to be shutdown, but it I still see it as an issue if it doesn't restart properly -- plus it's not great running a cronjob every day if I need to shutdown my web server each time.

**Comment by bmw** [comment]
It sounds like most of you used the `standalone` plugin to get your certs the first time, but you want a renewal option. In this case, you can use the `--pre-hook` and `--post-hook` flags to give commands to `certbot` to use during renewal. In short, the flags can be used with `standalone` to stop and then restart your webserver only when actually renewing your certificate (for a few seconds every 2-3 months). An example of this with more details is given in the [documentation](https://certbot.eff.org/docs/using.html#renewal).

While I hope this works for you, like Kuba stated above, I don't see how a webroot solution using port 443 is technically feasible. `webroot` cleverly solves the problem of having webserver specific code by utilizing the fact that most webservers serve files contained in a webroot/public_html directory. Because of this, the `webroot` plugin is able to solve the [HTTP challenge](https://tools.ietf.org/html/draft-ietf-acme-acme-02#section-7.2) by adding the necessary files to your webroot directory. Performing this challenge type over HTTPS is not allowed as stated in the spec.

The challenge type that can be performed over port 443 is the [TLS SNI challenge](https://tools.ietf.org/html/draft-ietf-acme-acme-02#section-7.3). In short, the way this challenge works is by configuring your webserver to respond to an HTTPS request for a randomly generated SNI value with a self-signed certificate containing that random value (and no other random values). The random value is chosen by the Let's Encrypt server and given to the Certbot client to setup.

In order to solve this challenge, the Certbot plugin needs to be able to configure your webserver to serve specific certificates for arbitrary SNI values that are given to the client seconds before performing the challenge. This requires understanding and being able to modify your webserver's configuration, not simply dropping files somewhere in your file system. This is the approach taken by both the Apache and Nginx plugins, but I don't believe it's possible to do this for an arbitrary webserver, each of which has their own configuration language, conventions, executables, etc.

If someone thinks they have a technical suggestion on how to do this within the current confines of the ACME spec, I'd love to hear it or see a PR. In the absence of such a suggestion, I'm going to mark this issue as won't fix. If you think the spec should be changed to accommodate this, please open an issue on https://github.com/ietf-wg-acme/acme.

I hope this all makes sense. While I'd love to see such a feature, I don't think it's technically possible.

**Comment by iangelov** [comment]
Thanks, that's as clear as it could be. I've personally moved on to using https://github.com/xenolf/lego with the DNS challenge - works for me, and as a side effect I don't have an yet another virtualenv hanging around.

**Comment by stylersnico** [comment]
Hi @bmw,

I have the same problem but port 80 is open, I simply redirect everything to HTTPS with that configuration in NGINX:

```nginx
        if ($scheme != "https") {
            rewrite ^ https://$http_host$request_uri? permanent;
        }
```

And webroot simply fails at renewal. 
It's a real problem because Certbot isn't compatible with NGINX and webroot is the only way to get ECDSA certificates.

Any workaround?

I don't want to modify dozens of vhost every time I need to renews certs.

Thanks

**Comment by bmw** [comment]
@stylersnico, are you still having this problem?

I'd double check that your redirect is working as expected. For example, if you have multiple vhosts, it's possible a different vhost is being used than the one you expect.

If that doesn't help, can you create a new issue with the error message you're seeing?

**Comment by stylersnico** [comment]
Hi @bmw,

I have made another PR: https://github.com/certbot/certbot/issues/3361

**Comment by sumpton** [comment]
I am using a Google TCP load balancer and it will not allow an IP to be used on two balancers, so there is nothing on port 80.

Passing a flag for https would be great, because using webroot is fast and simple.

**Comment by bmw** [comment]
As I said above, performing the challenge type that webroot can do over HTTPS is not allowed as stated in the ACME protocol specification that Certbot follows. You can learn more about ACME or suggest changes to it [here](https://github.com/ietf-wg-acme/acme).

**Comment by hydrandt** [comment]
I am in a similar situation - port 80 blocked. I obtained a certificate in the standalone mode:

```
letsencrypt certonly --standalone -d example.com --agree-tos --email e@mail.com --renew-by-default --standalone-supported-challenges tls-sni-01
```

And swallowed the fact that I will have to stop nginx every time when renewing the certs.

However, my colleague tried to renew using the webroot mode, and succeeded! Following works with port 80 blocked and nginx running on 443 with valid letsencrypt certs:

```
letsencrypt certonly -a webroot --webroot-path=/var/www/letsencrypt -d example.com --agree-tos --email e@mail.com --renew-by-default --standalone-supported-challenges tls-sni-01
```

Would somebody be able to explain how is this possible? From what I read here in other issues, I understood that it is an acme protocol limitation to always try 80 and eventually follow a redirect to 443. However, in my case, all traffic to 80 is being dropped by the provider.

**Comment by bmw** [comment]
@hydrandt, that behavior is due to https://community.letsencrypt.org/t/upcoming-change-valid-authz-reuse/16982

Let's Encrypt doesn't actually make you perform the challenge every time you renew.
