### ISSUE TITLE
Zero protection on github - no signed code, no pgp/gpg, no certificates, horrifying dependency forest ...

### ISSUE THREAD

**Issue by gitcnd** [certbot/certbot#2888]
To get a SSL security certificate on my machine, I have to download unsigned and untrusted code from a public web site maintained by an unknown number of arbitrary contributors, and then run this code on my servers.

Upon first-run, I'm greeted like this:-

[sudo] password for gitcnd: 

... this code then reaches out without warning or permission to assorted internet servers and gets even more software from dubious sources (yes, on centos/redhat, RPM has a signature-checking "feature", however, for the last 4 or 5 years since I filed a bug report on that [missing signatures are silently accepted!] those maintainers have chosen not to let RPM have any means to reject an "install request" because that might "break something" - they won't fix the bug, and they won't add that feature either).

and who knows what happens next, because after many dozens of junk dependancies, something died and it all failed.

This suggests to me that nobody in the letsencrypt project takes actual security even slightly seriously.  

<img width="290" alt="screen shot 2015-09-14 at 6 29 10 pm" src="https://cloud.githubusercontent.com/assets/4301826/14764554/4c1b5ffc-09ff-11e6-81d0-ff0b02a8fe21.png">

**Comment by bmw** [comment]
> To get a SSL security certificate on my machine, I have to download unsigned and untrusted code from a public web site maintained by an unknown number of arbitrary contributors, and then run this code on my servers.

All code you have ever run by us has been signed. Perhaps our documentation wasn't very clear on how to check this signature, but regardless, the signature has always existed.

We have always uploaded signatures of our packages to PyPI. `certbot-auto`/`letsencrypt-auto` is also signed and the signatures are verified when downloading any updates. There is a signature generated and checked using `openssl` that `certbot-auto` uses internally. Additionally, there is a PGP signature which can be checked using our instructions [here](https://certbot.eff.org/docs/intro.html#installation).

> Upon first-run, I'm greeted like this:-
>
>[sudo] password for gitcnd:

Unfortunately, in some cases we do ask for your `sudo` password without explaining why/what we plan to do with it. While you can prove the script came from us, it's just bad from a usability perspective to ask for the users `sudo` password with no context. Despite the fact that `certbot-auto`/`letsencrypt-auto` is supposed to be a temporary workaround while OS packages are developed, this should be fixed.

> ... this code then reaches out without warning or permission to assorted internet servers...

While true when you wrote your post, this has been fixed with `certbot-auto`. Your package manager will prompt you before we install any packages. This was also bad for usability.

> gets even more software from dubious sources (yes, on centos/redhat, RPM has a signature-checking "feature", however, for the last 4 or 5 years since I filed a bug report on that [missing signatures are silently accepted!] those maintainers have chosen not to let RPM have any means to reject an "install request" because that might "break something" - they won't fix the bug, and they won't add that feature either).

Do you have another suggestion for how we should obtain Certbot's dependencies? While certainly not perfect, the system's package manager is how this is normally accomplished.

> and who knows what happens next, because after many dozens of junk dependancies, something died and it all failed.

If you provide more information about what happened, I'm happy to try and help you through the problem.

All in all, I think the main issue here is poor documentation and usability design. Perhaps our documentation on how to verify our signatures can be improved. While we knew we weren't going to do anything malicious with `root` permissions, the user did not. I created #3114 to track the issue you pointed out about asking for your `sudo` password without context. Thanks for pointing that out.

If you have any other suggestions on how we can improve in this area, I'd be glad to listen. Again, if you'd like help installing the project, I'm happy to help you with that as well.

**Comment by gitcnd** [comment]
Firstly - shock - I file "bug reports" like this almost daily.  It's rare anyone ever replies, and I can't remember anyone ever replying who *cared*.  I am impressed!

My suggestion is to get rid of as many dependencies as possible.  For example:-

This idiot "owned" 17,000 servers:-
http://incolumitas.com/2016/06/08/typosquatting-package-managers/

and got a ton of press, so every copycat idiot and scrptkiddie worldwide is now going to be busily polluting the ecosystem with lookalike crap and adding malicious mods to dependencies.  Until the world works out that the internet can no longer function without adding trust into the foundations*, the best solution for now is to stop using as much of those crumbling foundations as possible.

* "trust" for foundations means that humans need identification before they get personas, and working authentication is needed for signing code:  When we discover rogue coders, everything they've touched needs to be reviewed.

How skillful are you bmw?  Can you grab the openssl source, find the "seed" call (the part where random numbers are disabled and replaced by a known reproducible stream), throw in a "print" to STDOUT so you know when it gets called, rebuild, and then create some letsencrypt keys.

I am scratching my head here: it looks like someone has left a "test" switch turned on somewhere; private keys are not using any genuine entropy to generate (I run a hardware TRNG).

**Comment by pde** [comment]
The dependency reduction task is being tracked at: #1301 

I made https://github.com/certbot/website/issues/149 to track the task of documenting `certbot-auto`'s security properties to people a little more closely.

Adding to bmw's points, it's also the case that `certbot-auto` checks hashes for everything it downloads with pip.  That _doesn't_ mean there's an audit against malicious code in any of those Python packages, but it does mean that a transient MITM or compromise against `pypi.python.org` can't slip code in that's different to whatever was observed during the Certbot release process.

The deeper problem ("how do we ensure that there's nothing fatally malicious in any of the open source projects that many of our systems depend on") is going to take a much wider effort amongst the open source community to solve.

Closing this bug in favour of the more specific ones, but please open new bugs if there are specific things that are missing and need to be done.
