### ISSUE TITLE
CentOS python-tools conflict

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#2921]
According to a report at https://community.letsencrypt.org/t/python-tools-problem/15336, there may be a conflict on CentOS 6.7 between different `python-tools` versions. (This might ultimately be a forum of Python 2.6 compatibility problem because the client may be causing a dependency on Python 2.7 that's incompatible with the preinstalled Python 2.6...?)

**Comment by centminmod** [comment]
yup can confirm centos 6.7 python-tools (2.6) vs IUS Community repo python27-tools (2.7)

**Comment by schoen** [comment]
Someone has now reported a seemingly-related problem on CentOS 7 as well.

https://community.letsencrypt.org/t/installing-letsencrypt-on-centos-7/15523

**Comment by schoen** [comment]
@centminmod, any thoughts on the circumstances under which this problem arises? We apparently have a very large number of CentOS users and have only recently gotten these problem reports.

**Comment by centminmod** [comment]
Most likely because all the unofficial docs/guides suggest centos 6.x folks to install python27 via alternative means as a side install to official python 2.6 based yum rpms with removale of python-tools so not to conflict with python27-tools. So most of the CentOS 6.x systems have both python (2.6) and python27 (2.7) installed at same time. When you run letsencrypt-auto, currently as outlined above, it checks for and installs python and thus python-tools first without any check if python27 and thus python27-tools already exists. So when letsencrypt-auto tries to reinstall python-tools which was removed, it reinstalls it python-tools but hits an rpm conflict with python27-tools package.

**Comment by centminmod** [comment]
also could be the way you scripted the yum/dnf check it doesn't seem to work as expected as whether or not python is installed or not, it will run yum -y install python first

```
if ! yum -y install python; then echo no; fi
Loaded plugins: fastestmirror, priorities
Loading mirror speeds from cached hostfile
 * base: mirror.n5tech.com
 * epel: linux.mirrors.es.net
 * extras: mirrors.easynews.com
 * rpmforge: mirror.hmc.edu
 * updates: mirror.hostduplex.com
221 packages excluded due to repository priority protections
Package python-2.7.5-34.el7.x86_64 already installed and latest version
Nothing to do
```

**Comment by TheNavigat** [comment]
Per @schoen's request, I investigated a bit using a CentOS 6.7 instance.

This is indeed the problem. Conflicts between python-tools and python27-tools occur if one of them is installed, and the solution proposed here https://github.com/certbot/certbot/issues/2921#issuecomment-217997542 fixes that perfectly.

Thanks a lot, @centminmod

**Comment by centminmod** [comment]
@TheNavigat the 2nd solution at https://github.com/certbot/certbot/issues/2921#issuecomment-218040694 might be better as it has a more accurate check for python/python27 based on os version

**Comment by carlwgeorge** [comment]
I'm one of the IUS maintainers, and this issue was recently brought to my attention.  IUS python27 packages should be 100% [parallel installable](https://ius.io/SafeRepo/#parallel-installable-package) with their stock counterparts.  I was able to confirm that python27-tools has a file conflict with python-tools.  This is a bug, and [has been corrected](https://github.com/iuscommunity-pkg/python27/commit/8d56f51) in the most recent release, [2.7.13-2](https://github.com/iuscommunity-pkg/python27/releases/tag/2.7.13-2).  IUS also offers python27-virtualenv, with the `virtualenv-2.7` command, that would avoid the need to install python-virtualenv and python-tools entirely (see also #2300).

Any future issues that are observed with our packages can be reported on the appropriate repo in the [iuscommunity-pkg organization](https://github.com/iuscommunity-pkg) (such as [python27](https://github.com/iuscommunity-pkg/python27/issues) or [python27-virtualenv](https://github.com/iuscommunity-pkg/python27-virtualenv)).

**Comment by ohemorange** [comment]
Certbot uses Python 3 on CentOS 6 now.
