### ISSUE TITLE
Recovery process

### ISSUE THREAD

**Issue by szepeviktor** [certbot/certbot#2989]
Hello!
I am looking for the documentation on this situation:

1. My server's disk is lost
1. I have a backup of my account data from `/etc/letsencrypt/accounts`

What steps to follow? How is it possible to recover my - already issued - certificate?
Thank you.

**Comment by szepeviktor** [comment]
I suspect Step No1 is reinstall certbot and restore `/etc/letsencrypt/accounts`.

**Comment by schoen** [comment]
Hi @szepeviktor, the account key does *not* allow you to recover your private key, because the certificate authority was, by design, never in possession of your private key. The only copy of the private key would have been on your own server. Therefore, in this situation you will need to issue a new certificate instead.

It should be possible, however, to use your account key to revoke your previously-issued certificate using the `certbot revoke` command.

**Comment by szepeviktor** [comment]
Thank you for clarifying this.

Please consider adding it to docs.
