### ISSUE TITLE
--post-hook validation too strict

### ISSUE THREAD

**Issue by mgedmin** [certbot/certbot#3020]
Here's the command I intend to run from cron.weekly:
```sh
#!/bin/sh

[ -x /opt/letsencrypt/bin/certbot ] || exit 0

/opt/letsencrypt/bin/certbot renew --quiet --post-hook '

if [ -x /usr/sbin/apache2 ]; then
    service apache2 reload
fi

if [ -d /etc/pov/post-cert-renewal.d ]; then
    run-parts /etc/pov/post-cert-renewal.d
fi
'
```

This fails with

```
Unable to find post-hook command 

if in the PATH.
(PATH is /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
```

**Comment by mgedmin** [comment]
Workaround for now:
```sh
# 'true #' on 1st line is a workaround for https://github.com/certbot/certbot/issues/3020
/opt/letsencrypt/bin/certbot renew --quiet --post-hook 'true #

if ...
...
'
```

**Comment by pde** [comment]
I don't think there's going to be any sensible way to validate the correctness of a hook in all of these different cases, and I think that the validation step is necessary [because of PATH-related problems](https://github.com/certbot/certbot/issues/2676#issuecomment-198087749) with hooks and `sudo`.

So one option is that we document the "begin with `true`" hack either in the CLI docs or the error message.  The other (perhaps slightly nicer) option is that we add a `--disable-hook-validation` flag.

**Comment by mgedmin** [comment]
Would it be possible to do the $PATH check only if the script invocation fails?

**Comment by mgedmin** [comment]
Ah, I see from https://github.com/certbot/certbot/issues/2676#issuecomment-198090013 that you want to notify the admin about possible errors even if no certificates were renewed during this run.  That sounds sensible.

In that case I'm in favour for a `--disable-hook-validation` flag.

**Comment by pde** [comment]
@mgedmin want to send a PR for that?

**Comment by mgedmin** [comment]
@pde: #3037.
