### ISSUE TITLE
HelloWorld showing an error when using Chrome on Windows

### ISSUE THREAD

**Issue by buzinas** [certbot/certbot#3043]
Hi,

When opening https://helloworld.letsencrypt.org/ using Chrome on Windows 7 or 10 (there is no error on Firefox nor Chrome for Linux), it's showing the following error:

```
NET::ERR_CERT_AUTHORITY_INVALID
```

And after clicking on "Advanced => Add exception", it looks like this:
![image](https://cloud.githubusercontent.com/assets/7298695/15440525/403ad548-1eac-11e6-89ed-33f7ba47d10e.png)

**Comment by schoen** [comment]
This is because that site deliberately uses the ISRG root certificate instead of the DST X3 root. I don't think this was a very good choice in terms of its potential for confusion, but it doesn't indicate a technical error because the people maintaining the site intend for it to demonstrate the ISRG root. Most browsers currently don't trust the ISRG root so most browsers will not be able to render the site correctly without adding it, unless they have the DST X3-signed Let's Encrypt X1 intermediate cached and are willing to build a path through it on the basis of its key (which is what you're seeing with your particular copy of Firefox, for example).

This does not indicate that sites that use Let's Encrypt certs can expect to have this problem, because those sites are being advised to use the DST X3 root and the associated Let's Encrypt intermediate.
