### ISSUE TITLE
Bug in FQDN detection: installer wrongly interprets _ 

### ISSUE THREAD

**Issue by wkoszek** [certbot/certbot#3057]
## Problem

I'm attempting to get a certificate for a new domain with a following format:

`wkoszek_nc2.x.mycompany.com`

However the client seems to get confused about `_`. Upon removing the `_` from the domain name, it works fine. For example, this works OK:

`wkoszeknc2.x.mycompany.com`

## To reproduce the problem:

Use this command to reproduce:

`# ./certbot-auto certonly --standalone --email wkoszek@mycompany.com -d wkoszek_nc2.x.mycompany.com
`

I'm getting this:

```
Checking for new version...
Requesting root privileges to run certbot...
   /root/.local/share/letsencrypt/bin/letsencrypt certonly --standalone --email wkoszek@mycompany.com -d wkoszek_nc2.x.mycompany.com
Requested domain wkoszek_nc2.x.mycompany.com is not a FQDN
```

**Comment by cowlicks** [comment]
Relevant code: https://github.com/certbot/certbot/blob/master/certbot/le_util.py#L343

The regex was taken from here: http://www.mkyong.com/regular-expressions/domain-name-regular-expression-example/

While fixing this it would also be nice to handle #3056 

Fun things I learned while digging in to this FQDN's *can* have underscores, but hostnames *cannot*. While the label used to identify the host in some network is usually the hostname, it doesn't have to be. http://stackoverflow.com/a/2183140/1609380

**Comment by wkoszek** [comment]
Do we even have to have this check at all? I don't understand why that would be necessary.

If you can reach the domain, it's fine. If not - you would get a different error warning.

Not sure about `_`, since Bonjour has some underscores used for its domain names: https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/NetServices/Articles/domainnames.html

**Comment by cowlicks** [comment]
@wkoszek I'm not sure what we have to check and why. Currently we don't allow unicode.

The only restriction I can find on a fqdn is that each label be between 1 and 63 octets. And that the full domain name be less than 255 octets. Your are allowed to have "any binary label" in that space.

I cannot find extra restrictions looking through the [DANE rfc](https://tools.ietf.org/html/rfc6698), or the [ca policy rfc](https://tools.ietf.org/html/rfc3647). But those are large documents and I'm probably missing something.

However we currently disallow a few things seemingly arbitrarily, like non-ascii unicode. changing this may break downstream code.

For now I can change it to allow underscores.

**Comment by wkoszek** [comment]
@cowlicks It'd be better to understand this check.

@kuba has a mini-client for Let's Encrypt, and it has no FQDN checks: https://github.com/kuba/simp_le

I've looked at the ACME spec by @bmw here: https://github.com/bmw/acme-spec/blob/master/draft-barnes-acme.md and it only has special conditions on wildcard domains. Maybe it'd be better to just check for `*` if `certbot` doesn't support that yet?

If you search for FQDN in the **Issues** of this repo, you'll see there's a lot of problems with this check.

**Comment by cowlicks** [comment]
@wkoszek, as far know the limitations on domain names are:

* no ip addresses (not a domain name issue but relevant)
* no wildcard domains
* no non-ascii unicode domains because of homoglyphs

The current restriction to `-`, `a-z`, `A-Z`, `0-9` was a regex literally copy and pasted from a blogpost. I don't think there is a *reason* for it. I think someone just wanted a regex to verify a FQDN, they googled it, and ended up with the wrong answer.

**Comment by pde** [comment]
I'm not completely sure that we should have merged this.  `_` isn't a valid hostname character, and Let's Encrypt doesn't plan to issue for any names that contain it.  So unless there's another CA that speaks ACME and wants to issue for non-hostname domain names, it's just going to move the error messages from the client to the server.

**Comment by bmw** [comment]
@pde, the question that sprang up in #3061 which resolved this issue is if Certbot plans to work with other potential ACME CAs besides Let's Encrypt. The answer to that question is certainly yes and to make that process as easy possible, we should probably only be making assumptions based on the behavior of Let's Encrypt when it provides a significantly better experience for our users.

The error message now shown is `The request message was malformed :: Error creating new authz :: Invalid character in DNS name`, which is perhaps slightly less user friendly, however, clearly states the problem, simplifies our code, and puts the check for underscores in domain names in exactly one place: the ACME server. If the ACME server is willing to issue for a domain containing an underscore, great, otherwise, it will return an error message which we will show to the user.

I talked to a couple people around the office before merging but if you have strong feelings about this and #3056, feel free to revert.
