### ISSUE TITLE
Improve debug logging of request / response bodies

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#3067]
At debug level `-vv`, we log HTTP request and response bodies. It would be nice to bump up the required log level for this level of detail to `-vvv` so our test runs could be a little quieter.

Also, the printed bodies are escaped and smooshed onto one line. It would be nice to print them literally as they would be seen in HTTP, across multiple lines. This will make it much easier to read the bodies when debugging issues. Right now they are very difficult to use as a diagnostic, and they also clutter up our test logs.

**Comment by TheNavigat** [comment]
For future reference, and if I understand correctly, this is the line the issue addresses. https://github.com/certbot/certbot/blob/master/acme/acme/challenges.py#L258

**Comment by bmw** [comment]
While agree with making request and response bodies more readable, why not just run your tests with `-v` instead of `-vv`?

**Comment by jsha** [comment]
I was guessing that there might be other items besides full HTTP bodies that get logged at `-vv`, which we might not want to skip. If HTTP bodies are the main additional thing that gets logged at `-vv`, I'm fine with that.

Also, the verbosity level code seems a little over-complex. AFAICT, each v adds a level of verbosity, and the verbosity levels are measured in multiples of 10, but there are effectively only two actual levels of verbosity. Any idea what the purpose of the extra complexity is? Also, `tests/integration/_common.sh` provides `-vvvvvvv`, which I think may as well be `-vv`?

**Comment by bmw** [comment]
Our logging code uses the the [logging](https://docs.python.org/2/library/logging.html) module in the Python standard library. This module defines 5 [logging levels](https://docs.python.org/2/library/logging.html#logging-levels) which we also use in our code.

The benefit of using and conforming to the practices in this module is that the logging level set with `-v` also applies to messages logged from other packages. For example, if you run the client with `-vv`, you will see messages from the `requests` package in the log output. If `-vv` isn't included, these messages aren't shown to the user because `requests` only logs messages with the level debug or info (unless errors occur with the request).

This also applies for other packages which my use the `acme` module. By using the standard logging levels, other programs can use `acme` but control the amount of logging information provided in a standardized way.

By default, we set the logging level to warning, meaning that messages logged as warning, error, or critical are shown to the user. HTTP bodies, as well as a lot of other output, is set to debug. We could define our own logging level below debug for HTTP bodies, but given the benefits of using `logging` in the standard way, I'm not sure that we should, especially as the change would be in `acme`.

You're right that the integration tests could just use `-vv`. I suspect the extra Vs were probably added in case we ever did something like change the default logging level.

**Comment by jsha** [comment]
Got it, thanks for the explanation. Mind if I change the integration
tests to use `-v`?

Also, what is the reason for the `* 10` when keeping track of the
logging level?

**Comment by TheNavigat** [comment]
Can I add another question? Why do we multiple things by negative? I tried
reading more through the code but I'm still confused.

**Comment by bmw** [comment]
> Got it, thanks for the explanation. Mind if I change the integration
tests to use `-v`?

I think we still want `-vv` on the client side. If you want to write up a PR to run `-vv` on the client side but `-v` for boulder, I'll merge it.

> Also, what is the reason for the `* 10` when keeping track of the
logging level?

The predefined [logging levels](https://docs.python.org/2/library/logging.html#logging-levels) are given the numeric values 10, 20, 30, 40, 50. By multiplying by 10, one count of `-v` causes you to jump to the next logging level.

> Why do we multiple things by negative?

The way the `count` [action](https://docs.python.org/2/library/argparse.html#action) works in argparse is we start at default value, adding 1 to the result every time the flag is seen. Since we want `-v` to result in a lower numeric logging level, we make the default -3, causing one instance of `-v` to result in a count of -2, which when multiplied by -1 and 10, we get 20 which is the correct logging level (see the logging level link above).

**Comment by jsha** [comment]
This has turned out to not be that important; Won't fix.
