### ISSUE TITLE
Insecure certificates issued due to common name (csr) scrambling

### ISSUE THREAD

**Issue by seanthewebber** [certbot/certbot#3094]
Upon updating from `letsencrypt-auto` to `certbot-auto`, trying to reinstate my certificates resulted in all but one of them being insecure. Upon further inspection:

`sudo ./certbot-auto certonly --standalone -d example.com -d www.example.com -d example2.com -d www.example2.com`

I realized that *all* of my domains have `example.com` (first `-d` parameter) listed as their common name. Thus, causing the certificates to be invalid. Further, deleting the `~/.local/share/letsencrypt/` and `/etc/letsencrypt` directories and running `certbot-auto` with a different domain name first does not correct the issue. I had to completely roll back the VPS in question (thank goodness for DigitalOcean backups) to remedy the issue.

This never seemed to be an issue with the former `letsencrypt-auto`... does it have to do with `--csr` or simply a bug?

**Comment by seanthewebber** [comment]
Also: the VPS is hosting multiple Apache virtual hosts that differ from its FQDN.

**Comment by schoen** [comment]
Sorry, could you explain more about what you mean by "insecure" and "invalid" in this case? How did you check that the certificates aren't the ones you want? Did you get an error when accessing a site in a browser, and, if so, what error?

Since recent client versions, the first name requested is always the one used by the CA in the commonName field (previously it was random), but the other names requested via -d are also used as subjectAltNames, which should also be accepted by clients. There are no modern TLS clients that require a particular name to be provided as CN rather than SAN; having a name presented as a SAN should not prevent a client from accepting the certificate with respect to that name. So, it would help to have more details about what went differently from what you expected (ideally, with examples of the actual certificates that worked and didn't work for you; even if you deleted your local copy, you could find the public copies on crt.sh).

**Comment by seanthewebber** [comment]
@schoen By insecure, I mean Google Chrome throws a fit about the connection not being private:

![google-chrome-your-connection-is-not-private](https://cloud.githubusercontent.com/assets/9794367/15642966/9e54e2d6-2618-11e6-89f6-a58915dc86e8.png)

(Not my screenshot, but the identical error)

The reason I came to that conclusion is the certificate for `example.com` *is* valid (shows a green lock) while all the rest of the domains threw the above error. The common name is the only discrepancy that popped out to me.

What's really strange is the `example.com` common name persists into other commands/sessions where the domain is not mentioned at all. I could spin up another VPS and attempt to recreate the issue, if that would be helpful.

**Comment by schoen** [comment]
We may need to see the actual certificates to figure out what the problem was, and ideally also the exact command you ran to obtain them with certbot and the exact error that Chrome gave about why the connection was insecure. There are many different reasons that Chrome might reject a certificate.

I definitely want to get to the bottom of the problems that you're having, but I don't know any specific reason offhand that it wouldn't have worked, hence the request for more details.

**Comment by jsha** [comment]
Closing for now; Let us know if you can provide more info. Thanks!

**Comment by lostideaslab** [comment]
Hi guys,

I think I have the same issue, 

```
root@lostideaslab:/etc/apache2/sites-available# certbot run --apache -d lostideaslab.com -d www.lostideaslab.com -d lp.lostideaslab.com -d analytics.lostideaslab.com
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator apache, Installer apache
Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Cert not yet due for renewal

You have an existing certificate that has exactly the same domains or certificate name you requested and isn't close to expiry.
(ref: /etc/letsencrypt/renewal/lostideaslab.com.conf)

What would you like to do?
-------------------------------------------------------------------------------
1: Attempt to reinstall this existing certificate
2: Renew & replace the cert (limit ~5 per 7 days)
-------------------------------------------------------------------------------
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 1
Keeping the existing certificate
Created an SSL vhost at /etc/apache2/sites-available/lostideaslab-le-ssl.conf
Deploying Certificate to VirtualHost /etc/apache2/sites-available/lostideaslab-le-ssl.conf
Enabling available site: /etc/apache2/sites-available/lostideaslab-le-ssl.conf
Deploying Certificate to VirtualHost /etc/apache2/sites-available/lostideaslab-le-ssl.conf
Created an SSL vhost at /etc/apache2/sites-available/lostideaslab-le-ssl.conf
Deploying Certificate to VirtualHost /etc/apache2/sites-available/lostideaslab-le-ssl.conf

We were unable to find a vhost with a ServerName or Address of analytics.lostideaslab.com.
Which virtual host would you like to choose?
(note: conf files with multiple vhosts are not yet supported)
...
```

but then:

```
home$ openssl s_client -connect lostideaslab.com:443 -servername lostideaslab.com 2>/dev/null | awk '/Certificate chain/,/---/'
Certificate chain
 0 s:/CN=piratelp.com
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
 1 s:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
---
```

I actually issued another certificate sooner for `piratelp.com` and there everything works perfectly but now for lostideaslab.com it using that domain as the CommonName.

Thanks in advance
