### ISSUE TITLE
Installation halts if Supervisor is already running, Ubuntu 14.04

### ISSUE THREAD

**Issue by sgornick** [certbot/certbot#3099]
Installation stopped during "Setting up supervisor" with the message "Starting supervisor: invoke-rc.d: initscript supervisor, action "start" failed."

```
$ ./certbot-auto 
[...]
Setting up supervisor (3.0b2-1) ...
Starting supervisor: invoke-rc.d: initscript supervisor, action "start" failed.
dpkg: error processing package supervisor (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 supervisor
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

I attempted to re-run certbot-auto and it stopped at the same spot.
I then manually stopped supervisor:

```
$ sudo service supervisor status
 is running

$ sudo service supervisor stop
Stopping supervisor: supervisord.
```

And ran certbot-auto again:

```
$ ./certbot-auto 
[...]
Setting up supervisor (3.0b2-1) ...
Starting supervisor: supervisord.
Creating virtual environment...
Installing Python packages...
Installation succeeded.
```

This is on Ubuntu 14.04.

**Comment by patf** [comment]
I think this is (more or less) unrelated to certbot. certbot has no supervisor dependency, and I can't reproduce this on a clean 14.04 instance with supervisor running. My best guess is that the `apt-get install` command that cerbot runs somehow triggered a pending installation/upgrade of the supervisor package. Maybe the upgrade was launched by `unattended-upgrades`, but used to fail with the same 'action "start" failed' error you got now (that's just one theory, it could be anything). IIRC `apt-get install` will continue installing any unconfigured packages from the last time `apt-get` was executed, so that's my best guess.

(I'm not sure if `apt-get` has some kind of "only do exactly what I tell you to do"-flag, I suppose if something like that exists it would be worth considering for `certbot-auto`.)
