### ISSUE TITLE
Issue with certbot 0.8.0 installed with Homebrew

### ISSUE THREAD

**Issue by cancan101** [certbot/certbot#3132]
I followed the directions and installed `certbot` with brew but am getting:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/certbot/0.8.0/libexec/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.8.0', 'console_scripts', 'certbot')()
  File "/usr/local/Cellar/certbot/0.8.0/libexec/lib/python2.7/site-packages/certbot/main.py", line 707, in main
    config.logs_dir, 0o700, os.geteuid(), "--strict-permissions" in cli_args)
  File "/usr/local/Cellar/certbot/0.8.0/libexec/lib/python2.7/site-packages/certbot/util.py", line 108, in make_or_verify_dir
    os.makedirs(directory, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/var/log/letsencrypt'
```

**Comment by DomT4** [comment]
You need to execute `certbot` with `sudo` to allow it to write to the default locations it wants to. You can also give it custom directories instead, although the process is a bit of a dance (See https://github.com/certbot/certbot/issues/3079).

**Comment by cancan101** [comment]
Perhaps on os x the default output directory should be chosen such that it's user writable? Or St the very least it falls back when run with sudo.

**Comment by DomT4** [comment]
That's a decision for Certbot/EFF themselves to take. I mostly dropped by because I'm a Homebrew maintainer and I crawl the issue tracker here to make sure stuff that should be filed with us isn't dumped on the EFF instead, heh.

I'm sure EFF has considered it but a reasonable middle-ground between the status quo & a full `--nosudo` flag would be to throw a friendlier error with a nudge towards the `--log-dir`, etc options when `certbot` knows it can't write to xyz directory rather than throwing an output that looks to many like a bug.

**Comment by bmw** [comment]
Yes. The project has a long history of requiring `sudo`. `certbot` is in many ways a system tool. It often needs to bind to 80/443, modify web server configuration files, restart your web server, etc. This leads to annoyances like the one found here, but it was the decision made in the design of the project.

I don't think falling back to alternative directories is a good idea. What happens when you forget and accidentally run the the client without `sudo`? Doing this would complicate our code, documentation, and the experience for the user so I think this isn't a path we should go down.

At the same time, the error message you got is pretty awful and #2734 aims to improve it. In the mean time, you can specify alternative directories using the `--config-dir`, `--work-dir`, and `--logs-dir` flags. You can specify this in a [configuration file](https://certbot.eff.org/docs/using.html#configuration-file) which makes this slightly less cumbersome.

As a side note, @DomT4, I had no idea there was a `certbot` brew formula. That's great! I created certbot/website#130 to look into updating our documentation to point OS X users towards that instead of `certbot-auto`. If any of the formulas maintainers have any questions for us, please stop by in #letsencrypt-dev on Freenode.

**Comment by DomT4** [comment]
Aye. My response when asked over at Homebrew on the `sudo` requirement has been [pretty similar](https://github.com/Homebrew/homebrew-core/pull/1110#issuecomment-219049341). You can do a lot to avoid the `sudo` requirement if you're particularly determined, so the flexibility is there in the client; I guess people are just struggling to discover that to some extent.

> As a side note, @DomT4, I had no idea there was a certbot brew formula.

Yeah, I added it back in February because amongst other potential directions _(namely trying to get out of the business of doing our own CI, because it's laughably maintenance intensive)_ we may end up using `certbot` internally, and I wanted to play with it a bit on that front in a local VM.

Despite not announcing it prominently anywhere we're hitting about 3.5k installs of the `certbot` formula per month recently, so there's decent usage around. I've been doing most of the looking after of the formula, so feel free to @ me if you get anything Homebrew specific you think is our problem rather than your's, etc.

We're not actually installing the examples (including `cli.ini`) at the moment, so I might tweak it on our side to make sure those are getting installed.

**Comment by bmw** [comment]
> You can do a lot to avoid the sudo requirement if you're particularly determined, so the flexibility is there in the client; I guess people are just struggling to discover that to some extent.

Yeah it was a bit of a contentious issue when the decision was made, leading to things like https://github.com/diafygi/letsencrypt-nosudo which is the inspiration behind the name for the `--nosudo` flag. I hope things like #2734 and #3079 help though.

And sounds good. I'll probably go ahead and write up the change telling OS X users to use `brew` to install `certbot` on the certbot website as it'll probably be a much better experience for most users. Thanks for taking the time to create the formula.

Lastly, since this issue is a misunderstanding stemming from the bad error messages which are described in #2734, I'm closing this issue. A community contributor said he was going to work on #2734 this weekend so hopefully the issue will be fixed soon. Regardless, thanks for taking the time to report the issue @cancan101.
