### ISSUE TITLE
Pip upgrade suggestion breaks letsencrypt-auto

### ISSUE THREAD

**Issue by seanlinsley** [certbot/certbot#3161]
Pip simply releasing a new version shouldn't break certificate generation.

```
/opt/letsencrypt/letsencrypt-auto stderr: You are using pip version 8.1.1, however version 8.1.2 is available.

You should consider upgrading via the 'pip install --upgrade pip' command.

An unexpected error occurred:

PythonDialogBug
```

**Comment by bmw** [comment]
I don't believe these errors are related. `pip` always shows this output when a new version is available and we've pinned a specific `pip` version in `certbot-auto`.

As for the `PythonDialogBug`, there are a number of issues related to this. The most common cause of this error is your terminal window was too small for `certbot` which is tracked in #2812. If increasing your terminal size doesn't work, you can add `-t` as a workaround to use the text interface instead of `dialog`.

**Comment by seanlinsley** [comment]
The command is being run inside of our Capistrano deploy process, so I don't imagine a full TTY exists when it's being run.

Turns out that `certbot.log` has a message prompting us to switch to `certbot-auto`. If y'all are going to force everyone to switch to the new executable name, it would've been better if that error showed up prominently instead of being hidden in a log file.

**Comment by bmw** [comment]
> The command is being run inside of our Capistrano deploy process, so I don't imagine a full TTY exists when it's being run.

If a TTY isn't available, I recommend adding either `-t/--text` or `-n/--noninteractive` to the command line:

```
  -t, --text            Use the text output instead of the curses UI.
                        (default: False)
  -n, --non-interactive, --noninteractive
                        Run without ever asking for user input. This may
                        require additional command line flags; the client will
                        try to explain which ones are required if it finds one
                        missing (default: False)
```

> Turns out that certbot.log has a message prompting us to switch to certbot-auto. If y'all are going to force everyone to switch to the new executable name, it would've been better if that error showed up prominently instead of being hidden in a log file.

I'm assuming you mean this message: "You are running with an old copy of letsencrypt-auto that does not receive updates, and is less reliable than more recent versions. We recommend upgrading to the latest certbot-auto script, or using native OS packages." This is written both to a log file and to error output, however, if you're using dialog, it's shown in the `dialog` window instead of stderr.

**Comment by seanlinsley** [comment]
> If a TTY isn't available, I recommend adding either `-t/--text` or `-n/--noninteractive` to the command line:

Thanks for the tip :smile:. We'll give that a try.

> however, if you're using dialog, it's shown in the `dialog` window instead of stderr.

Yes that's the message we're getting. I'm not sure what `dialog` is.

**Comment by bmw** [comment]
Sorry. `dialog` is the ncurses software that `certbot` uses as the default UI. I believe the problem is `certbot` is trying to this when a TTY isn't available.

We could potentially try and default to `text` mode if `stdout` isn't a TTY, but this is somewhat magic behavior.

**Comment by seanlinsley** [comment]
`--noninteractive` worked 👍
