### ISSUE TITLE
Allow custom "pip.conf" for certbot-auto

### ISSUE THREAD

**Issue by andrefernandes** [certbot/certbot#3222]
Those doomed to deal with corporate proxies usually setup a local PyPi mirror that goes configured in "/etc/pip.conf".

Problem is certbot-auto creates a virtualenv that seems to ignore it. There is no way to add the file manually to virtualenv because certbot-auto recreates it everytime.

Could certbot-auto accept a parameter (say, "--pipconf") that could point to a pip.conf file that could be copied into the virtualenv it creates?

**Comment by darknesstm** [comment]
this is a big problem in china.... please resolve it as quick as possible. Thank you.

**Comment by systemexitzero** [comment]
For me, at least, the `certbot-auto` does not actually make it to where it calls `pip` internally, it fails (as far as I can tell, I'd love to be wrong) during the [pipstrap.py](https://github.com/certbot/certbot/blob/master/letsencrypt-auto-source/pieces/pipstrap.py) script which runs inside virtualenv just before the requirements files are installed. 
The urls that pipstrap targets are hardcoded to https://pypi.python.org and downloaded manually, verified, and then passed to pip, so even using a global PIP_CONFIG_FILE (of course) would not work for that case.

If you also have an https_proxy you _might_ be able to export https_proxy in addition to exporting PIP_CONFIG_FILE to set your pypi mirror to get around pipstrap, but I do not have an https_proxy I could test this with myself.

Perhaps more frustrating is that pipstrap does not appear to check if the dependencies it aims to guarantee are already satisfied (they are at the system level in my case).

**Comment by bmw** [comment]
cc @erikrose

**Comment by erikrose** [comment]
FWIW, certbot-auto no longer recreates the venv every time, so you do have a working escape route now.

I would gladly accept a PR to https://github.com/erikrose/pipstrap to bail out early if pip >=8 is already around. I think that should make everyone happy.

**Comment by erikrose** [comment]
As it turns out, there is already [such a PR](https://github.com/erikrose/pipstrap/pull/4). :-) Reading it, however, I am [reminded](https://github.com/erikrose/pipstrap/pull/4#issuecomment-193985131) of all the pip/setuptools/wheel bugs we hit in the past when we didn't pin the whole trio. But we haven't seen any with comparatively modern versions, so I'm inclined to merge something like it.

**Comment by systemexitzero** [comment]
Thank you for the response @erikrose, I appreciate your insight on this. If the virtualenv is not recreated, that should be sufficient enough for my purposes. In the more general case though, what complications might arise in allowing pipstrap to be configured to use a pypi mirror (or even a local folder) if pipstrap is still checking hashes before installation anyway?

If that's a better topic for an issue on the pipstrap repo, let me know.

**Comment by erikrose** [comment]
There are no particular security issues I'm concerned with. Rather, I fear the multiplicity of different pip/setuptools/wheel version combinations used to install certbot specifically (which would apply for anything the user has installed if his pip>=8.0). certbot, with its complicated package relationships, conditional dependencies, C extensions, and need to deploy on diverse and ancient systems, has shown itself more vulnerable to subtle differences in installation tools than any other package I have seen. So I have become paranoid, and we have benefitted in a reduced number of installation tickets since we pinned everything down to the hundredths-place version.

**Comment by systemexitzero** [comment]
Sorry if I may have seemed I switching gears; on pinning the versions down strictly, I fully understand your point. My last question was only regarding your thoughts on the ability to point pipstrap at an index other than pypi (such as an internal mirror), but leave the version numbers and hashes pinned as you have balanced them.

**Comment by andrefernandes** [comment]
The need to use a mirror was the point of this thread when I created it :)

Does the current version allows pointing to a mirror at all?

**Comment by erikrose** [comment]
If we merge that PR and you make sure your systems have pip>=8, pipstrap will not run, and so everything should respect your mirror settings.

**Comment by systemexitzero** [comment]
Alright, it's a small enough change that I'd be willing to write up a PR to supercede pipstrap#4. there's a couple issues I see on it, namely that it checks == on the pip version.

**Comment by erikrose** [comment]
I shall endeavor to review it punctually. :-)

**Comment by bmw** [comment]
I believe this was resolved with the change to pipstrap so I'm closing this issue.
