### ISSUE TITLE
Multiple domain certonly renewal with --domain options does not seem to work

### ISSUE THREAD

**Issue by cpg** [certbot/certbot#3235]
I have a handful of domains and I seem to recall (because I see I wrote some script to do this), that I used to be able to use `--domain X` multiple times with certonly and I think it used to work, but now it does not seem to work. Only one of the domains gets renewed.

1) should having multiple `--domain X --domain Y` work and renew multiple at a time? if so, it does not appear to work for me
2) if not, then how can I get certs renewed (just getting the cert) with a handful at a time?

The reason we want to do this is that we use puppet to manage system configurations and the certs are managed (kept, distributed and installed) with puppet, so I would like to automate this.

For bonus points, I would like to renew multiple domains in one place, even if the certs are not in the same machine. Can you recommend a client to do this (if possible doing it in a machine behind a firewall inside a trusted environment that would drop certs as input into the puppet system).

**Comment by bmw** [comment]
>1) should having multiple --domain X --domain Y work and renew multiple at a time? if so, it does not appear to work for me
2) if not, then how can I get certs renewed (just getting the cert) with a handful at a time?

Running `certbot certonly ...` will renew at most one certificate at a time. There can be multiple names in the certificate, however.

As for how to renew multiple certificates, I recommend looking at our [renewal documentation](https://certbot.eff.org/docs/using.html#renewal). In general, I'd encourage you to use `certbot renew` instead of `certbot certonly` unless you have a specific reason that doesn't work for you. If you have to use `certonly`, you'll have to run the client once for each certificate.

**Comment by sydneyli** [comment]
It looks like this question was answered. If not feel free to poke me and I'll reopen this ticket!
