### ISSUE TITLE
certbot http -> https rewrite rules messes up GET params

### ISSUE THREAD

**Issue by jasonmoofang** [certbot/certbot#3243]
Hello,

An issue I encountered today: the rewrite rules added to apache config by certbot-auto to coerce http requests to https doesn't seem to be bulletproof.

In particular, GET params that are url-encoded, eg ?email=testest%2Byhbugfixer%40gmail.com, seem to end up getting encoded twice so that my application receives 'testest%2Byhbugfixer%40gmail.com' for the param value instead of the intended 'testest+yhbugfixer@gmail.com', if I make the initial request in http://

Notably, this does not happen if in place of the rewrite rules added by certbot-auto, I simply create a new virtual host like so:

 &lt;VirtualHost *:80&gt;
        ServerName mydomain.com
        Redirect / https://mydomain.com/
 &lt;/VirtualHost&gt;

**Comment by pde** [comment]
@sagi, thoughts?

**Comment by sagi** [comment]
@jasonmoofang, can you please share with us your configuration files, before and after certbot messes with them ?

**Comment by jasonmoofang** [comment]
hey @sagi ,

Unfortunately I no longer have the "before" configuration files, but I'm pretty sure this is the snippet inserted by certbot to coerce https:

RewriteEngine on
RewriteCond %{SERVER_NAME} =mydomain.com
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,QSA,R=permanent]

This is the contents of the virtual host file for my domain, if relevant:

  &lt;VirtualHost *:443>
      ServerName mydomain.com
      # !!! Be sure to point DocumentRoot to 'public'!
      DocumentRoot /path/to/rails/public
      RailsEnv production
      &lt;Directory /path/to/rails/public>
         Require all granted
         # This relaxes Apache security settings.
         AllowOverride all
         # MultiViews must be turned off.
         Options -MultiViews
      &lt;/Directory>
      SSLEngine on
      SSLCertificateFile /etc/letsencrypt/live/mydomain.com/cert.pem
      SSLCertificateKeyFile /etc/letsencrypt/live/mydomain.com/privkey.pem
      SSLCertificateChainFile /etc/letsencrypt/live/mydomain.com/chain.pem
   &lt;VirtualHost>

**Comment by jt2k** [comment]
I ran into this problem today.  I think the fix is to add the `NE` (noescape) flag to the rewrite rules found [here](https://github.com/certbot/certbot/blob/777356833221669ce578b53dc81a31100e0511aa/certbot-apache/certbot_apache/constants.py#L138-L146), but I'm not sure if that would create any undesired side effects.

**Comment by sagi** [comment]
Back then, during my research on this I bumped on this [thread](http://serverfault.com/questions/331899/apache-mod-rewrite-double-encodes-query-string-on-redirect). 

It seems that `NE` introduces undesired side effects, which were not entirely fixed in Apache 2.4.10 and (although Apache claims otherwise). 

I've been meaning to test it out; but didn't get to it.

Also, I believe that a change in escaping / encoding of the query string may harm current `certbot` users who already got themselves used to its behavior.

**Comment by diablodale** [comment]
Double-encoding a query is a well known issue with a resolution to use NE. There are cases where NE isn't the answer. However, for a blind wildcard redirect to move a client from http -> https it is important to not alter any part of the URL beyond the protocol (i.e. path, port, query, etc.).

Failure example:
`http://foo.bar.com/apple?email=me%40domain.com`
incorrectly redirecting to:
`https://foo.bar.com/apple?email=me%2540domain.com`

There is no reliable manner for the receiving code to know if the received query string is single url encoded or erroneously double url encoded. Therefore, there is no legit legacy workaround coded by current certbot users. Anything written by someone out there...isn't reliable.

Therefore, the resolution is to fix the core issue which is the use of QSA. It should instead be NE. This will result in...

Good example:
`http://foo.bar.com/apple?email=me%40domain.com`
correctly redirecting to:
`https://foo.bar.com/apple?email=me%40domain.com`

**Comment by sagi** [comment]
@diablodale thanks for your insights. I agree with your reasoning.
