### ISSUE TITLE
Performing ./letsencrypt-auto --help should not install anything

### ISSUE THREAD

**Issue by JonTheNiceGuy** [certbot/certbot#3279]
I have git clone'd this repo to a production machine, then performed ./letsencrypt-auto --help to determine what the script was going to do... I was not expecting it to start installing packages!

Clearly, the logic is "This script will need these things to perform actions, so let's do it, then check the arguments", but... it's a little bit nerve racking!

**Comment by bmw** [comment]
`certbot-auto` should be preferred over `letsencrypt-auto`. `letsencrypt-auto` exists only for legacy reasons and `certbot-auto` has the behavior you describe. The behavior for `letsencrypt-auto` was not changed to prevent breaking people who have built integrations around `letsencrpyt-auto`.

If `certbot-auto` has already installed packages, `certbot-auto --help` will give you the help from Certbot itself, otherwise, you'll get help about the `certbot-auto` script.
