### ISSUE TITLE
`letsencrypt renew` doesn't update outdated symlinks in live directory

### ISSUE THREAD

**Issue by alexjurkiewicz** [certbot/certbot#3288]
I had a case reported here:
https://community.letsencrypt.org/t/renew-not-working-for-expired-certificate/17883 (thanks pfg)

`letsencrypt renew` managed to get & write new certificates to `/etc/letsencrypt/archive/` but didn't update the symlinks in `/etc/letsencrypt/live/` (probably I didn't run the command as root -- my error).

Subsequent runs of `letsencrypt renew` told me my certificate was updated but the `live` symlink didn't change from '1' to '2' files so I thought the renewal wasn't working properly.

I think `letsencrypt renew` should try to defend against errors like this by checking the `live` symlinks point to the latest version of the `archive` files, even when it doesn't request a renewal.

**Comment by pde** [comment]
@schoen are you aware of any circumstances whether this might occur?
@alexjurkiewicz can you post a copy of a logfile where this occurred?

**Comment by alexjurkiewicz** [comment]
Sorry, I didn't keep the output!

**Comment by schoen** [comment]
@alexjurkiewicz, you might still have logs in `/var/log/letsencrypt` even without having the output from the individual tiems that you ran the software.

**Comment by fvlasie** [comment]
This same problem is happening to me. I ran letsencrypt successfully but it did not update the symlink.

**Comment by fvlasie** [comment]
/opt/letsencrypt/letsencrypt-auto renew

Run as root

**Comment by schoen** [comment]
To my knowledge, all of the cases of this that we've dealt with on the forum have turned out to be aspects of #6382 (unsupported renaming of contents of `/etc/letsencrypt`). I'm keen to hear about other kinds of problems with symlinks in `live`, but it would probably be most helpful to hear about them on the forum instead of GitHub.

For most cases I think this is superseded by #6382 (we know that there are ways that a user can change `/etc/letsencrypt` contents which Certbot won't detect usefully and which will produce behavior like this).
