### ISSUE TITLE
certbot-auto renew --dry-run is starting apache and failing certificate renewal

### ISSUE THREAD

**Issue by muyiwao221** [certbot/certbot#3299]
When I try to run a dry run of my certificate renewal process, I understand that since apache2 is listening on port 80, I have to stop it. However, when I do stop it, as soon as certbot "installs" the first certificate, apache2 is started automatically. So the first certificate finishes with a success, and then the subsequent certificates fail because apache is listening on port 80. Rather annoying actually as no matter how many times I stop apache2, certbot (for some odd reason) re-enables it after checking the first cert. Any ideas of what is going on? I am running Ubuntu 14.04 trusty, and naturally my webserver is Apache.

Thanks in advance

**Comment by bmw** [comment]
> When I try to run a dry run of my certificate renewal process, I understand that since apache2 is listening on port 80, I have to stop it.

This is only true if you're using the `standalone` plugin. If you're using the `apache` or `webroot` plugin, Apache can (and in `webroot`'s case should) continue to run. You can find more information about the different plugins available [here](https://certbot.eff.org/docs/using.html#plugins).

> However, when I do stop it, as soon as certbot "installs" the first certificate, apache2 is started automatically. 

After installing your certificate, Certbot does a graceful reload of Apache. This is done because if Apache is currently running, it must be reloaded for the new certificate to take effect. We could potentially look into adding logic to skip this step if Apache isn't currently running, but this might be tricky to do reliably across all systems.

In the absence of such a feature, I recommend seeing if you can use the `webroot` or `apache` plugins during renewal which will avoid this problem entirely. This has the added benefit that you don't have to stop/start Apache to renew your certs. You'll simply run Certbot, all your certificates will be renewed, and the certs you've set up to install with Apache will be updated and served by the webserver when Certbot exits.

To change the plugins used to renew your certificate, it's probably easiest to renew once with `certonly` as described in our [renewal documentation](https://certbot.eff.org/docs/using.html#renewal). Alternatively, you can modify the files found in `/etc/letsencrypt/renewal`, however, this is easy to mess up, especially if switching to something like `webroot` which will require more information in order to work.

**Comment by pabsta1** [comment]
Perhaps I am using certbot inappropriately, but I certainly don't want apache to be restarted by certbot for two reasons: 
1) I use nginx; 
2) Certbot is within a broader bash script that also requires to listen to port 80. 

I would recommend adding an option such as --no-apache (or similar). 

Thanks for an otherwise very useful client.
