### ISSUE TITLE
Android 4.x Download through HTTPS not possible

### ISSUE THREAD

**Issue by iliraga** [certbot/certbot#3318]
It seems that downloading a file from a Letsencrypt-Secured Domain (https) is not possible because the downloader-application of android do not recognize the letsencrypt certificate.

I was able to reproduce the bug on three devices running all Android 4.2

**Comment by bmw** [comment]
First, this is the wrong place to report this problem. This repo is for Certbot, EFF's ACME client which obtains from certificates from Let's Encrypt, but has no control over their certificate. The best place would probably be https://community.letsencrypt.org.

Second, this kind of thing has been reported before in #3000 and https://community.letsencrypt.org/t/x3-certificate-not-recognized-on-mobile-browser/14604 and it has always been due to the web server being configured incorrectly. I encourage you use https://www.ssllabs.com/ssltest/ to take a look at the site.

**Comment by SwartzCr** [comment]
Looks like this is probably solved now - gonna close it, feel free to reopen if you're still having issues
