### ISSUE TITLE
"No installers present" message is confusing.

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#3321]
```
No installers seem to be present and working on your system; fix that or try running certbot with the "certonly" command
```

This is one of the most common messages, received when running certbot on an Nginx installation, but it is confusing to a new user. What's an installer? Is it my mistake or certbot's that there are no installers? What does "certonly" do?

Instead how about:

```
Certbot doesn't know how to automatically configure the web server on this system. However, it can still get a certificate for you. Please run "certbot[-auto] certonly" to do so. You'll need to manually configure your web server to use the resulting certificate.
```

**Comment by Mathsoum** [comment]
This won't be a usefull comment but just to let know that I ended up on this page and it helped me.
So it may indeed be a good idea to change the message.

**Comment by bmw** [comment]
We also had #1576 which is the same issue and was supposedly fixed by #3250, however, the only clarification made to installers is to add change it to "installer plugins".

We've had conversations in the past whether we should try to explain to our users what terminology like [installer](https://certbot.eff.org/docs/contributing.html#installer) means in the context of Certbot or hide such jargon entirely. Probably some combination of the two is the best approach.

**Comment by jsha** [comment]
@bmw: What do you think of my proposed verbiage above?

**Comment by jsha** [comment]
Oh, @Mathsoum thanks for mentioned that this was useful to you, that is in fact helpful to know!

**Comment by bmw** [comment]
I think it's good. It doesn't hint at the possibility that you're just missing a plugin in order to get automatic installation, but that might be a lot to fit into one error message.
