### ISSUE TITLE
pyinstaller

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#334]
@jezdez suggested using http://www.pyinstaller.org/ for binary distribution

**Comment by kuba** [comment]
Blocker: https://github.com/pyca/cryptography/issues/2039

**Comment by m1keil** [comment]
I would actually suggest you guys to try the [Omnibus](https://github.com/chef/omnibus) path instead, to create full stack installers. If I understand correctly, your client is pluggable, which is painful when you freezing Python stuff.

Another potential issue there is that your code might need to change in order to adapt to being in frozen state.

**Comment by rmoriz** [comment]
:+1: for Omnibus. Also used by other Python users e.g. https://github.com/DataDog/dd-agent-omnibus

**Comment by bmw** [comment]
We decided not to use pyinstaller, largely for the reasons mentioned above of having optionally installed plugins so I'm closing this issue.
