### ISSUE TITLE
Perfect Score on SSL Labs Test. Possible as of 2016?

### ISSUE THREAD

**Issue by rickhessmann** [certbot/certbot#3365]
Hi guys. I've been trying hard to get a perfect score with Nginx + LetsEncrypt SSL cert on the SSL Labs Server Test. I'm getting A+, no problem. Cert is only incompatible with IE6/XP and Java 6 which is more than fine. Those are built on ancient technology and should not be used anymore.

The main thing is: I simply can't get a 100% score at all. I've followed multiple tutorials claiming to be able to provide me with a perfect score, which doesn't happen.

The most I can get out of the test is:

100% - Certificate 
95% - Protocol Support 
90% - Key Exchange 
90% - Cipher Strength

Is it possible to get perfect score with Nginx using Lets Encrypt certs today?

**Comment by schoen** [comment]
Hi,

This would be more suitable to discuss at the Let's Encrypt Community Forum. There are two existing threads related to the desire for a higher SSL Labs score with Nginx and Apache:

https://community.letsencrypt.org/t/how-to-get-an-a-rating-on-qualys-ssl-labs-with-nginx-without-breaking-loads-of-browsers/4582

https://community.letsencrypt.org/t/howto-a-with-all-100-s-on-ssl-labs-test-using-apache2-4-read-warnings/2436

You could also start a new thread there if neither of these is exactly relevant.

It's not surprising that the default configuration from Nginx or Certbot wouldn't give a 100% score because, as those threads discuss, getting a perfect score requires reducing browser compatibility to exclude browsers that only support older crypto mechanisms.

I don't believe that there is anything about the cert itself that is limiting your score, but you can discuss and clarify the details on the community forum.
