### ISSUE TITLE
[jonathonf's Trusty PPA] Crash in acme/client.py

### ISSUE THREAD

**Issue by mschwerin** [certbot/certbot#3367]
Hi,

I'm running certbot on Ubuntu 14.04 using python 2.7.6 installed from
https://launchpad.net/~jonathonf/+archive/ubuntu/letsencrypt?field.series_filter=trusty
It crashes with the following trace:

root@ssh2:/home/maximilian# letsencrypt renew
Traceback (most recent call last):
  File "/usr/bin/letsencrypt", line 9, in <module>
    load_entry_point('certbot==0.8.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2235, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 19, in <module>
    from certbot import client
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 10, in <module>
    from acme import client as acme_client
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 30, in <module>
    requests.packages.urllib3.contrib.pyopenssl.inject_into_urllib3()
AttributeError: 'module' object has no attribute 'pyopenssl'

The attached patch seems to fix this issue.

[letsencrypt-patch.txt](https://github.com/certbot/certbot/files/398879/letsencrypt-patch.txt)
Cheers Maximilian

**Comment by pde** [comment]
@erikrose do you have an opinion on whether we should apply that patch?
Also CC'ing @hlieberman ...

**Comment by erikrose** [comment]
I suspect (I haven't downloaded and unpacked all the packages to check) that that PPA maintainer has de-vendored urllib3, as is the Debian way. In a typical certbot install, it is vendored inside `requests`. If we apply this patch, we will crash on typical installs, where there is no top-level urllib3 lib: notice it is not in https://github.com/certbot/certbot/blob/master/letsencrypt-auto-source/pieces/letsencrypt-auto-requirements.txt.

The hardline answer is that the PPA maintainer is responsible for applying and maintaining this patch, since he's the one changing the import paths. If we wanted to be nice, at the expense of adding a branch to our code, we could catch an ImportError and try for a top-level urllib3 as a fallback. I lean slightly toward the former, because monkeypatching is scary enough without adding ifs around it. (What if somebody had a non-pinned install and a different version of requests, in which the vendored path was different? We would fall back to a top-level urllib3, which, if installed, could conceivably interact badly with the requests-vendored version if its monkeypatcher got called as well.)

**Comment by pde** [comment]
@jonathonf this is for you, then

**Comment by jonathonf** [comment]
I need to have another look at the PPA; if the Debian and Yakkety packages work as-is there may be something else going on. However, in the meantime I'll add the patch to the PPA package for Trusty and check whether the Xenial build needs it.

**Comment by bmw** [comment]
We landed a similar patch in our code a long time ago so I'm closing this issue.
