### ISSUE TITLE
"archive directory exists" should not be an error

### ISSUE THREAD

**Issue by kornelski** [certbot/certbot#3396]
I've created a certificate using

``` sh
./letsencrypt-auto certonly --webroot -w /www/foobar/ -d foo.com -d bar.com
```

and later I wanted to remove the second domain, so I ran:

``` sh
./letsencrypt-auto certonly --webroot -w /www/foobar/ -d foo.com 
```

and I've got error

> archive directory exists for foo.com 

That is unhelpful. I know I can "fix" it by `rm -rf /etc/letsencrypt`, but I'd prefer that it wasn't an error at all.

IMHO certbot should just overwrite the certificate. If overwriting is considered too risky, then it should ask whether it's OK to overwrite, and/or the message should suggest a flag such as `--force`.

---

I'm running d05f53bd53082832583a5dcfefc2241fd21386e9 on Debian 8.5

**Comment by bmw** [comment]
You should only get this error message if a file in `/etc/letsencrypt/renewal` has been deleted. In general, `/etc/letsencrypt` is very sensitive to changes as a number of assumptions are made in the code about the layout of the directory.

What's going on here is Certbot is picking the lineage name (the name used for the directories in `/etc/letsencrypt/archive` and `/etc/letsencrypt/live` and the file in `/etc/letsencrypt/renewal`) based on the files found in `/etc/letsencrypt/renewal`. It finds an available file name and when it goes to create the `/etc/letsencrypt/archive` directory, the name is already taken which Certbot does not expect.

Instead, we can check the name is available in all three places before deciding on a name. We'd need to be careful here to avoid race conditions. We probably either want to create all three files/directories before choosing the name (and deleting the files/directories if it's determined to be "taken") or implement locks as described in #993. Maybe both to protect against other programs that might not respect our locks.

**Comment by willemdh** [comment]
Also ran into this error. There should be an overwrite switch or something imho.

**Comment by joshribakoff** [comment]
> Instead, we can check the name is available in all three places before deciding on a name. We'd need to be careful here to avoid race conditions.

Or design the system so that you don't need 3 different files to be kept in sync. I'm tasked with renewing dozens of certs from a legacy system. For whatever reason I can't just do a simple certbot renew. It used the nginx module & certbot fails to restart nginx. Manually restarting nginx works fine.  Restarting my webserver several times a day is really concerning so I want to switch to web root.

I'm running a script with a bunch of lines like this:
`certbot -n --webroot -w /var/www/html/example.com/ certonly -d example.com`.

I want to simply run that command 1x a day & forget about it. But certbot is getting in the way of that.

Somehow half the `renewal` files ended up as 0 bytes, which I suspect is an issue within letsencrypt.

About half of them just exit with "archive directory exists". No cert is obtained or renewed. When I run it a second time, it does not error, but instead obtains a new cert & creates a new renewal file with a suffix of `0001`.

Also the renewal file seems to be a "map" of the files, and persists options like the web root. What if I want to rename my web root?

This also seems super kludgy. Why persist the file map in the renewal file instead of just naming the files according to a convention. How do I change a web root if the old web root is persisted in the renewal file? Why would a command fail the first time but succeed upon retry?

**Comment by Tarocco** [comment]
still a problem in 0.19.0

**Comment by Tarocco** [comment]
This creates problems when using webroot method with docker volume mounts:

In docker-compose.yml:

        ...
        volumes:
          - ${NGINX_SSL_CERTIFICATE}:/etc/ssl/certs/server.pem:ro
          - ${NGINX_SSL_CERTIFICATE_KEY}:/etc/ssl/private/server.key:ro
        ...

In my nginx config server directive:

        ...
        ssl_certificate     /etc/ssl/certs/server.pem; # This is the certificate file
        ssl_certificate_key /etc/ssl/private/server.key; # This is the private key file
        ...


In .env:

        NGINX_SSL_CERTIFICATE=./letsencrypt/live/my.site/fullchain.pem
        NGINX_SSL_CERTIFICATE_KEY=./letsencrypt/live/my.site/privkey.pem

If the `./letsencrypt/live/my.site` directory already exists, certbot is unhappy, and if it doesn't, Docker creates _directories_ `./letsencrypt/live/my.site/fullchain.pem` and `./letsencrypt/live/my.site/privkey.pem` (not files). This behavior cannot be changed in either certbot or Docker it seems. Right now all I can think to do is mount `./letsencrypt/live` in Docker, or write scripts to copy the certs to another location like `./ssl`.

**Comment by narcisgarcia** [comment]
I also ran into this error when migrating certificates tree from an old server. certbot should work with this as a normal situation. I know the renewal file is missing, but certificate trees were migrated from another server. I just want to generate new certificates when needed for any one I have already, and overwrite/rotate old ones as a normal renew.

**Comment by grx7** [comment]
I got apache2 with virtual hosts running 3 domains on same VPS. First two were installed without an issue. But when I've added a 3-d site it didn't install it properly, I've removed folders with lets encrypt but seems like already did 5 attempts. Any idea how to override without waiting for a week?

**Comment by maotora** [comment]
(Exactly a week later)

Hi,
Make tested attempts this time.
Goodluck! 🤞🤞

**Comment by schoen** [comment]
Sadly, I think this is basically an instance of the older issue https://github.com/certbot/certbot/issues/775 in the larger sense. If users modify `/etc/letsencrypt`, there are *many* ways that Certbot can fail (including crashes or renewals that go undetected). We'll need a systematic effort to detect all and usefully report all of these conditions.

**Comment by MrMetric** [comment]
This problem resulted in my domains hitting the rate limit because I kept trying things to fix it and it kept not working. Now I can't renew my certificates until next week (assuming I can even get it to work; the error messages are useless).

**Comment by tr0yspradling** [comment]
This shouldn't be closed. This is still an issue when reconfiguring hosts. If a cert exists & you're renewing or verifying with a different method, this should just delete & install the certs. No errors, no issues. Why is this closed?

**Comment by truemoroz** [comment]
> shouldn't be closed. This is still an issue when reconfiguring hosts. If a cert exists & you're renewing or verifying with a different method, this should just delete & install the certs. No errors, no issues. Why is this closed?

I agree. Please, reopen ticket

**Comment by andrewNestorenko** [comment]
running manual mode to verify domains over DNS records, have ~10 domain in the list, put all TXT records and in the end got "archive directory exists for ...."
It is not what I expected to see. I mean it even doesn't look like an error

**Comment by jvpernis** [comment]
I, too, would like to see an `--force` option to have certbot overwrite the existing SSL certificates. 

In my setup, NGINX runs in a separate container from certbot and is my main reverse proxy for all traffic. The NGINX container needs to be running in order to serve the challenge, but I won't start because the SSL certificates for the web applications don't exist yet. 

That is why I though of having a dummy certificate, but then certbot decided to make a new folder with the `-0001` suffix. Super frustrating.

**Comment by ap-wtioit** [comment]
Had this issue when migrating to a new server and restoring /etc/letsencrypt from the backup.

Redacted log:
```
user@host:~$ sudo certbot 
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator nginx, Installer nginx

Which names would you like to activate HTTPS for?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: domain1.tld
2: domain2.tld
3: domain.tld
4: domain4.tld
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate numbers separated by commas and/or spaces, or leave input
blank to select all options shown (Enter 'c' to cancel): 3
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for domain.tld
Waiting for verification...
Cleaning up challenges
archive directory exists for domain.tld
```

No further message. It seemed not even clear that there was an issue from this message for me.

But verifying certificate validities made it clear the cert was not updated:
```
user@host:~$ sudo munin-run certificate_file_expiry 
_etc_letsencrypt_live_domain1_tld_cert_pem.value 86.5711
_etc_letsencrypt_live_domain2_tld_cert_pem.value 86.5712
_etc_letsencrypt_live_domain_tld_cert_pem.value 4.66591
```

To fix i had to:
* configure an invalid certificate for the domain on nginx
* `rm /etc/letsencrypt/archive/domain.tld`
* run certbot again to create the certificate

Good thing we have monitoring of certificate validity. Didn't expect certbot to fail with this.

**Comment by wadewilliams** [comment]
For any of you running into this issue after copying your certs over to a new server for whatever fail over reason, I'll point out that I was able to work around this and get letsencrypt to bypass the error by copying the contents of ` /etc/letsencrypt/renewal/domain.tld.conf` over. 

Agree the issue shouldn't be closed, but a fix could be as easy as regenerating this file if it's empty?

**Comment by vshmoylov** [comment]
Still a problem in 2022.
Force option could save a lot of time for everyone. I use approach with dummy self-signed certificates in docker-compose environment and ran into the same error

**Comment by TonyTromp** [comment]
I constantly run on this issue, especially since we migrate from server to server and run nginx in docker containers. 
It is strange that a new certbot installation can not simply re-use another folder structure and this cripples auto-deployments completely. Such a missed feauture, which could be solved with a simple overwrite or with a --force flag.

**Comment by Chris1234567899** [comment]
I'm trying to get this running on AWS ECS on a multi-container setup and it's a nightmare.
I have a nginx container and a certbot among others. I can't use certbots  standalone, because in ECS task defintions ports cannot be assigned twice, and the nginx container needs obviously port 80 to run.

If I go with webroot, nginx needs to be running to receive the request from certbot. But in order to run, it needs at least a dummy certificate or else it crashes. And now certbot complains that a dummy certificate is already in place? Come on... its been 7(!) years!

**Comment by schoen** [comment]
I'm not sure if this will solve all your problems with the container setup, but you don't have to have nginx listening on port 443 or speaking HTTPS in order to run with --webroot. You can use -a webroot and -i nginx and then Certbot will add the HTTPS configuration where none existed before, for example.

**Comment by error-try-again** [comment]
I encountered this two days ago when searching google for a quickfix. This seems to be a bug related to how both the archive and live directory paths are created, which is not specific to letsencrypt-auto, but certbot more generally. I reproduced this error by generating self-signed certificates within an established directory structure, which lead to a CertStorageError as illustrated below:

```
openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
  -keyout "${certs_path}/privkey.pem" \
  -out "${certs_path}/fullchain.pem" \
  -subj "/CN=${DOMAIN_NAME}"
```

```
host@server:~/project$ ls -la cert
certbot/          certbot_renew.sh  certs/
host@server:~/project$ ls -la certs/
accounts/      archive/       dhparam/       live/          renewal/       renewal-hooks/
host@server:~/project$ ls -la certs/live/
README      mydomain.net/
host@server:~/project$ ls -la certs/live/mydomain.net/
fullchain.pem  privkey.pem
``` 

```
certonly \
--webroot \
--webroot-path=/usr/share/nginx/html \
--register-unsafely-without-email \
--agree-tos \
--no-eff-email \
--force-renew \
--rsa-key-size 4096 \
--domains mydomain.net \
--domains subdomain.mydomain.net \
--staging
```

```
certbot._internal.storage:Creating directory /etc/letsencrypt/archive.
certbot.errors.CertStorageError: live directory exists for mydomain.net
```

Upon examining the letsencrypt codebase, the error occurs when new_lineage is invoked in storage.py, due to changes made in commit #b235dc4 on May 11, 2015. The problem occurs due to checking if the archive or live directory exists and is non-empty, which results in a CertStorageError when the directory contains self-signed certs or temporary certs. The checking itself is fine, but there needs to be a way to override it to handle this edge case. 

Original commit new_lineage #b235dc4, which seems to contain the bug - certbot/letsencrypt/storage.py
```
# storage.py
    ...
    @classmethod
    def new_lineage(cls, lineagename, cert, privkey, chain,
                    renewalparams=None, config=DEFAULTS):
                    renewalparams=None, config=constants.RENEWER_DEFAULTS):
        ...
        lineagename = os.path.basename(config_filename)[:-5]
        archive = os.path.join(archive_dir, lineagename)
        live_dir = os.path.join(live_dir, lineagename)
        
        # The snippet causing the issue
        if os.path.exists(archive):
            raise ValueError("archive directory exists for " + lineagename)
        if os.path.exists(live_dir):
            raise ValueError("live directory exists for " + lineagename)  
        ...
```

Latest related commit #db6de76, to the code snippet & related PR https://github.com/certbot/certbot/pull/7952 - certbot/certbot/_internal/storage.py
```
# storage.py
    ...
        lineagename = lineagename_for_filename(config_filename)
        archive = full_archive_path(None, cli_config, lineagename)
        live_dir = _full_live_path(cli_config, lineagename)
        
        # The snippet causing the issue
        if os.path.exists(archive) and (not os.path.isdir(archive) or os.listdir(archive)):
            config_file.close()
            raise errors.CertStorageError(
                "archive directory exists for " + lineagename)
        if os.path.exists(live_dir) and (not os.path.isdir(live_dir) or os.listdir(live_dir)):
            config_file.close()
            raise errors.CertStorageError(
                "live directory exists for " + lineagename)
        for i in (archive, live_dir):
            if not os.path.exists(i):
                filesystem.makedirs(i)
                logger.debug("Creating directory %s.", i)
        ...
```

To resolve this in [my own project](https://github.com/error-try-again/QRGen-FullStack) I created the following patch, which introduces an --overwrite-cert-dirs option, enabling the overwriting of certificate directories for automation purposes, thus avoiding the error. I've created a forked version of certbot with the fix applied [here](https://github.com/error-try-again/certbot)

It adds: 

- A user-input argument to trigger the overwriting behavior.
- A default configuration setting to ensure the feature is opt-in.
- An updated directory check-and-delete method to facilitate the removal and replacement of existing directories that conflict with lineage names during automated processes.

```
# __init__.py
    ...
    helpful.add(
        "automation", "--overwrite-cert-dirs", dest="overwrite_cert_dirs", action="store_true",
        default=flag_default("overwrite_cert_dirs"),
        help="Overwrite all certificate files (key/cert/chain/renewal) in the specified "
             "certificate directories without asking. Useful for automation via cron. "
             "Implies --non-interactive.")
    ...
```

```
# constant.py             
    ...
    overwrite_cert_dirs=False, 
```

```    
# storage.py
    ...
    @staticmethod
    def check_and_delete_directories(archive, live_dir, lineagename, force_delete):
        if os.path.exists(archive) and (not os.path.isdir(archive) or os.listdir(archive)):
            if force_delete:
                shutil.rmtree(archive)
            else:
                raise errors.CertStorageError(
                    "archive directory exists for " + lineagename)
        if os.path.exists(live_dir) and (not os.path.isdir(live_dir) or os.listdir(live_dir)):
            if force_delete:
                shutil.rmtree(live_dir)
            else:
                raise errors.CertStorageError(
                    "live directory exists for " + lineagename)

    @classmethod
    def new_lineage(cls, lineagename: str, cert: bytes, privkey: bytes, chain: bytes,
                    cli_config: configuration.NamespaceConfig) -> "RenewableCert":
    ...
        lineagename = lineagename_for_filename(config_filename)
        archive = full_archive_path(None, cli_config, lineagename)
        live_dir = _full_live_path(cli_config, lineagename)

        force_delete = cli_config.overwrite_cert_dirs
        cls.check_and_delete_directories(archive, live_dir, lineagename, force_delete)
    ...
```

To use it manually:

```
certonly \
--webroot \
--webroot-path=/usr/share/nginx/html \
--register-unsafely-without-email \
--agree-tos \
--no-eff-email \
--force-renew \
--rsa-key-size 4096 \
--domains mydomain.net \
--domains subdomain.mydomain.net \
--staging \
--overwrite-cert-dirs
```

Here's a bash snippet from my homebrew use case, to dynamically generate docker compose files.

```
# Flag for overwriting self-signed certificates
OVERWRITE_SELF_SIGNED_CERTS_FLAG=""

# Check if there's a need to overwrite self-signed certificates
if [[ $OVERWRITE_SELF_SIGNED_CERTS == "yes" ]]; then
  OVERWRITE_SELF_SIGNED_CERTS_FLAG="--overwrite-cert-dirs"
fi

# Construct the certbot command with the necessary flags and parameters
certbot_command="certonly --webroot \
--webroot-path=${INTERNAL_DIRS[INTERNAL_WEBROOT_DIR]} \
${with_email} \
${TOS} \
${NO_EFF_EMAIL} \
${FORCE_RENEWAL} \
${RSA_KEY_SIZE_FLAG} \
--domains ${DOMAIN_NAME} \
--domains ${SUBDOMAIN}.${DOMAIN_NAME} \
${OVERWRITE_SELF_SIGNED_CERTS_FLAG}"

# Define the certbot service configuration
certbot_service="certbot:
  build:
    context: .
    dockerfile: ./certbot/Dockerfile
  command: ${certbot_command}
  volumes:
    - ${CERTBOT_LETS_ENCRYPT_VOLUME_MAPPING}:rw
    - ${CERTBOT_LETS_ENCRYPT_LOGS_VOLUME_MAPPING}:rw
    - ${CERTBOT_CERTS_DH_VOLUME_MAPPING}:ro
    $shared_volume:rw
  depends_on:
    - frontend"

```

Hope this helps someone else out there still looking for a solution.

**Comment by W1zzardTPU** [comment]
@error-try-again: have you tried submitting PR?

**Comment by W1zzardTPU** [comment]
@error-try-again have you tried submitting a PR?

**Comment by adamkentdev** [comment]
I'm still having issues with this but it's due to me renaming the newly generated cert directory in live (mycert-0001 to mycert) in order to not have to update all my vhost configurations when having to add a new subdomain to the cert. Also when the certificate renewal fails due to this the dry-run option works successfully, but then running without dry-run it fails! Very easy to hit the rate limits when using a cron as a result. An option to overwrite the previous certificate would be extremely helpful!

**Comment by JonBendtsen** [comment]
This issue should be reopened!

I got hit by this after adding an alternative name to my existing certificate. I had 5, I wanted +1 and now it wont get a certificate due to `2026-03-14 16:50:16,876:ERROR:certbot._internal.log:archive directory exists for`:-(

I don't have any email in the command

**Comment by JonBendtsen** [comment]
Deleted everything, and now I get `An unexpected error occurred:\ntoo many certificates (5) already issued for this exact set of identifiers in the last 168h0m0s,`:-(

**Comment by adamkentdev** [comment]
> Deleted everything, and now I get `An unexpected error occurred:\ntoo many certificates (5) already issued for this exact set of identifiers in the last 168h0m0s,`:-(

It's not a fix, but you can get round this issue by changing the domains you are asking for (e.g. add another random sub-domain to the ones your asking for and it will work).
