### ISSUE TITLE
Suggestion:  HPKP key and config management

### ISSUE THREAD

**Issue by DXGLdotinfo** [certbot/certbot#3449]
I would like to see a system where Certbot manages a pool of keys for HPKP deployment, as well as outputting config snippets to be "include"'ed into the main server config.
How I would think it should work:

On first run, the client should first display a warning regarding the risks of "bricking" a site due to poor HSTS deployment.
Upon agreement to the warning, the client should generate 3 RSA and/or EC keys, 1 to be deployed and 2 stand-by keys.
The client should obtain a certificate for the first "deployment" key and output the certificate set plus a configuration snippet for Apache and/or nginx to be "include"'ed into the server configuration, that will output public key pinnings for the deployed key and the two standby keys.
This should be per-domain, of course, like the certificate files.

On re-invocation of certbot, the client should consume one of the stand-by keys, converting it into a deployment key, and generate another stand-by key.  Along with the certificates output, should be a replacement set of HPKP header config files.

Perhaps a good starting point for the HPKP duration would be 90 days.

The number of stand-by keys and the HPKP duration should ideally be configurable, once again with the caveat that YMMV.

**Comment by AliceWonderMiscreations** [comment]
HPKP is severely broken and should not be used IMHO.

HPKP requires at least two fingerprints. One for the live certificate and the other is suppose to be for a backup key. The private key associated with the backup fingerprint MUST NOT be on the same server as active private key but HPKP has no way to enforce it.

If the backup private key is on the same server as the active private key than HPKP is pointless because if the live key is compromised, the backup key likely is compromised too.

In addition for lacking any meaningful way to ensure proper key management, HPKP is also a blind trust on first use system.

This means it only protects the client from an active MITM attack if the client happens to already have a valid fingerprint from the site cached. If the user doesn't already have a valid fingerprint cached, not only will they still be subject to MITM but the attacker can even send their own fingerprint that the browser will blindly trust - preventing the client from being able to connect to the genuine site.

HPKP should not be integrated into LE, it is conceptually flawed. Proper public key pinning should have proper validation of the fingerprint on every use, not blind trust on first use. A mechanism for that exists called DANE and it not only does the key pinning in a better way, but you don't have to pre-generate backup keys so there isn't an issue of how to keep your backup keys safe on a different system until needed.

**Comment by bmw** [comment]
HPKP is deprecated so I'm closing this.

If you think I missed something or would like me to reconsider, please comment or open a new issue.
