### ISSUE TITLE
Revoke old certificate on renewal

### ISSUE THREAD

**Issue by DaKnOb** [certbot/certbot#3465]
Currently `certbot v0.8.1` does not revoke the previous certificate upon renewal with `certbot renew`. I have checked the source code a little bit and also verified this by testing using the actual client. I believe this behavior has not been implemented because it can cause problems with certain automation setups, however, I think it should be implemented and initially be available using a flag, and then, maybe, at some point, be the default. 

Some comments on the proposal above:
* From a security perspective, it makes sense to have the old certificate revoked, since it would not be used any more and there's no reason to have it as valid.
* Most (if not all) browsers do not check for revocation information ([Can you visit this?](https://revoked.grc.com/)) therefore this might not make any difference currently.
* Since most people currently use `certbot renew`, the amount of revoked certificates will increase, placing further load in any CRLs / OCSP Servers that may be used by the CA. Currently the percentage of revoked certificates [is 0.4% for Let's Encrypt](https://plot.ly/~letsencrypt/9/daily-activity/#plot).
* If someone fails to reload their web server after the renewal, they will theoretically serve revoked certificates until they do. 

This is not a high priority issue, it is actually a feature request, and very few people will use this initially, however I am posting this issue so we can track the progress of this.

**Comment by schoen** [comment]
Thanks for the suggestion.

I don't think this is a good default behavior, because the exact difficulties that you mention are likely to be common for a number of users. Other CAs permit overlapping validity of multiple certificates because we don't know for sure the schedule on which users will roll out the new certs, particularly in the case where the certs are served by multiple devices, such as multiple different web servers. Revoking by default upon renewal will force people to deploy the new cert almost instantaneously. In our original renewal design, we contemplated even waiting one week (!!) before trying to roll it out in order to give the user a chance to manually verify that the renewed cert was correct. Although we didn't end up retaining that one-week delay idea, it still seems plausible to me that some users would prefer such a delay because of their particular setups.

While it is definitely good practice to revoke certs that are definitely going to be unused, I just don't think we can make that assumption on the user's behalf in general, because we would end up surprising people and breaking their sites. If you can think of a way to make it optional, I would support having the option available in Certbot somehow for people who know they want it (maybe as a flag --revoke-when-renewing or something).
