### ISSUE TITLE
Clustering?

### ISSUE THREAD

**Issue by TomMettam** [certbot/certbot#3470]
CertBot is apparently not currently usable on sites hosted on multiple servers.

The ACME server does not properly check for all A records on a particular domain.

In my configuration, I have:

www IN A 167.114.139.43
www IN A 167.114.139.44
www IN A 167.114.139.45

Only one of these machines will be able to obtain a certificate (until the TTL expires).

**Comment by schoen** [comment]
Hi @TomMettam ,

There have been some discussions about this on the forum. In this case, the easiest approach may be to use a different client and use the DNS challenge (which demonstrates your control over the domain by adding a DNS record instead of through a connection to a server).

Certbot is eventually going to support the DNS challenge type, and there is some work in progress on that, but in the meantime I agree that Certbot isn't the best choice for some people with this kind of setup. I think this is best tracked at issue #2236 unless you have a specific proposal for a different way that you'd like it to work.
