### ISSUE TITLE
Additional cert for Nginx OCSP when using the default webroot plugin?

### ISSUE THREAD

**Issue by bitinn** [certbot/certbot#3487]
The problem being Nginx OCSP requires the [Root CA certificate to also be in the file](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_stapling_verify) for OCSP stapling to work. As far as I can tell, neither `fullchain.pem` nor `chain.pem` contains the Root CA (for good reasons).

So currently neither 

`ssl_certificate      /etc/letsencrypt/live/[domain]/fullchain.pem;`

nor

`ssl_trusted_certificate /etc/letsencrypt/live/[domain]/chain.pem;`

will allow OCSP to work on Nginx. (`openssl s_client -connect domain:443 -tls1 -tlsextdebug -status` returns no OCSP response.)

Obviously I can prepare such file, but I feel bad creating my own cert file because it should be fully automated (users should just link to such file).

Update: _DST Root CA X3_ alone with `ssl_trusted_certificate` should be enough to make this work. Maybe add a `root-ca.pem` to the live folder?

**Comment by bitinn** [comment]
If I am allowed to argue about *wording*, I think both `fullchain` and `chain` can be misleading here and may confuse new users.

**Comment by bmw** [comment]
Our Nginx plugin that is under development currently automatically enables OCSP stapling by setting `ssl_trusted_certificate` to `chain.pem`. Testing this with `openssl s_client`, it seems to work.

**Comment by ChristophBusold** [comment]
From nginx documentation: "For verification to work, the certificate of the server certificate issuer, the root certificate, and all intermediate certificates should be configured as trusted using the ssl_trusted_certificate directive." (http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_stapling_verify)

Therefore I would like to second the request for certbot to download and install the root certificate into the live folder. Since the OCSP URL is pointing to identrust.com, I am not sure if chain.pem really works.

About the wording, although I generally agree, changing it at this point would surely create a lot more confusion.

**Comment by ArchangeGabriel** [comment]
Hum, I have OCSP working here under nginx, using the fullchain only. The root certificate that must be embedded is Let’s Encrypt one, the OCSP is checking against `http://ocsp.int-x3.letsencrypt.org`. So I don’t see the issue here.

Also, @ChristophBusold you’re quoting `ssl_stapling_verify`, which I belive is for nginx to verify OCSP response it receives (e.g. when proxying to another https server). Quoting stapling:
>If the ssl_certificate file does not contain intermediate certificates, the certificate of the server certificate issuer should be present in the ssl_trusted_certificate file.

My setup (excerpt):
```
    ssl_certificate /etc/letsencrypt/live/<domain>/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/<domain>/privkey.pem;
    ssl_stapling on;
    resolver 127.0.0.1;
```
(I have a local DNS resolver)

**Comment by ChristophBusold** [comment]
That invokes two questions:
1. Does ssl_stapling_verify verify staples from TLS connections with other web servers? If so, why does it need ssl_trusted_certificate? This verification should be part of the existing TLS implementation. I understood it rather to verify staples it receives from OCSP before handing them out to clients, but I agree that the documentation is ambiguous.
2. Does nginx add staples only for the leaf certificate or also for intermediates? In case of the latter, how does it identify which root (LE's own or the cross signed one from DST) the client is using?

**Comment by bitinn** [comment]
I haven't looked back at this, but can someone actually verify **nginx mainline + latest certbot** combo works out-of-the-box with OCSP stapling?

Obviously I have the same setup for `ssl_certificate` and `ssl_certificate_key`, but I do need this extra line in my setup for OCSP stapling to work, it's [this root certificate from Identrust](https://www.identrust.com/certificates/trustid/root-download-x3.html).

`ssl_trusted_certificate /etc/ssl/local/verify-letsencrypt.crt`

I am using a remote resolver, per [the config recommendation from h5bp](https://github.com/h5bp/server-configs-nginx/blob/master/h5bp/directive-only/ssl-stapling.conf). I believe a fair number of users do use this as a base config because of its security and performance considerations.

`resolver 8.8.8.8 8.8.4.4 216.146.35.35 216.146.36.36 valid=60s;`

I am happy to close the ticket IF:

- Without `ssl_trusted_certificate`  but with remote `resolver`, it now works.
- Let Encrypt install now comes with the Identrust cert, so users can just point `ssl_trusted_certificate` to the letsencrypt folder without manually downloading the root certificate.

(Note for testing: you need to initiate a few requests before OCSP kicks in on Nginx.)

**Comment by ArchangeGabriel** [comment]
@ChristophBusold 

1. Hum, this makes sense. But I still don’t understand why this option exist then. So you check upstream OCSP, and then what? Discard if it doesn’t work? But with must-staple, that won’t work. And the client is going to check the answer anyway, so…
2. I have no idea (for both questions)…

@bitinn Why is using an external resolver is better security and performance wise? Anyway, I’ve just tested without `ssl_trusted_certificate` and `8.8.8.8` as `resolver`, and it worked.

And you exactly need one request for OCSP to kick in, that’s because Nginx doesn’t have the answer cached on start.

Now regarding the root certificate, it should not be part of the chain/fullchain. And I’m wondering if the people having issues here have the root certificate in their system trust store… You’re not supposed to have to download it from somewhere, it should be provided by your OS.

**Comment by bitinn** [comment]
While this is off-topic:

1. H5bp is a general template, I am not saying that specific resolver setting is for performance. But it can be as local resolver maybe slow.

2. You often need more than one request to activate OCSP: you need one for each nginx worker thread.

(From my phone)

**Comment by ChristophBusold** [comment]
@ArchangeGabriel I would think that a missing staple is in no case worse than an invalid one. With must-staple you have a problem either way, but it would at least make sense from server side to know that it is invalid (log it/inform admin etc.).

**Comment by schoen** [comment]
@bitinn, do you believe there's still a problem here, or were you satisfied with @ArchangeGabriel's answer?
