### ISSUE TITLE
Incorrect wildcard redirects with Apache

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3495]
The following vhost:

```
<VirtualHost *:80>

    ServerName example.com
    ServerAlias *.example.com
...
```

turns into this after requesting a redirect for `example.com`:

```
<VirtualHost *:80>
    ServerName example.com
    ServerAlias *.example.com
...
RewriteEngine on
RewriteCond %{SERVER_NAME} =*.example.com [OR]
RewriteCond %{SERVER_NAME} =example.com
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,QSA,R=permanent]
</VirtualHost>
```

`RewriteCond %{SERVER_NAME} =*.example.com` doesn't have the desired behavior. Here, `{%SERVER_NAME}` needs to be the exact string `*.example.com` or it doesn't match.

**Comment by alexzorin** [comment]
In the wild: https://community.letsencrypt.org/t/problems-with-ssl-wildcard-automatically-https-forwarding-subdomains/124884

Proposed fix: add `UseCanonicalName on` *inside* the virtual host, if we detect that one of the names is a wildcard.

Since the entire vhost gets reduced to a redirect anyway, I believe there is no real risk of breaking anything.

**Comment by bmw** [comment]
Thanks for updating this Alex.

I'm personally leaning towards constructing a regex when we encounter a wildcard depending on how complex that'd be to do properly.
