### ISSUE TITLE
certbot-auto-cron

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3522]
It'd be nice if we could help people set up cron or systemd timers to automatically run `certbot renew -q`. Ideally, for packaged versions of Certbot, this job should be left up to the package maintainer. For `certbot-auto` users, we could offer to try and set up the cronjob or systemd timer for them.

If we do this, we should probably only do so when installing OS packages (which should only happen once per system) and we should prompt the user to ask permissions (unless they included something like `--noninteractive` on the command line). We should avoid causing `certbot-auto` to be run automatically on systems where Certbot is already installed and there is an existing integration around `certbot-auto`.

Putting this behavior in `certbot-auto` has a couple of downsides:
1. It doesn't help people installing directly through `pip` (which we never tell anyone to do).
2. Some distributions may not create a crontab for us due to ideological reasons or because they don't know they're supposed to. This will leave these users to deal with their own cron/systemd setup.

With that said, I personally prefer putting this behavior in `certbot-auto` rather than the core Certbot client, but I want to make sure we know the limitations here up front.

Related: #880

**Comment by pde** [comment]
Alternative option: offer to do this setup from within the client, after successfully obtaining a cert?

**Comment by bmw** [comment]
Yeah. I mentioned that option above. I personally think it's cleaner to put it in `certbot-auto` as installing a standard crontab for a package is the role of a package manager, but we could theoretically help more people by putting it in the core client. I put in the list above the two groups of people we may miss by putting the functionality into `certbot-auto`.

**Comment by pde** [comment]
My view is that it would be saner to implement this in Python code rather than in `certbot-auto`. Basically, what we would do at the end of `certonly` or `run` is walk through all of the known locations for Certbot cron and systemd configurations, and if all of them are missing, ask an interactive question offering to create one that looks correct for your system.  That would work for:

* All of the `certbot-auto` users
* The OSes that don't / won't have this included in their packaging

This shouldn't interfere with:
* People whose packages provide this now (or in the future, if packing is done well...)
* People who don't want it (they can say no)

**Comment by ynasser** [comment]
Rough plan for this so far (all this code will be in `certbot-auto`, not the core client, as using bash makes more sense for this):

0. Add cron as a dependency to certbot-auto.

1. Ask user if we want to setup a cron job for renewal. If so, proceed to # 2. If not, exit with a message that contains a link to directions on how to setup up cron themselves.

2. Check for existing cron jobs generated by certbot (in `/var/spool/cron`). If we find any, print a message and then quit.

3. If we don't find any, use the `crontab` command to generate a new one that looks something like: `0 */12 * * * root python -c "from time import sleep; from random import randrange; sleep(randrange(3600));" && certbot -q renew # generated by certbot`. The advantage of using the `crontab` command is that there are many different system-specific setups/implementations of `cron`, and using this command functions as the standard interface to all of them.

    i. Special case for Debian (maybe): @hlieberman asked us to put cron jobs for Debian where they're currently setup for packaged certbot (`/etc/cron.d/certbot`), so that may end up happening instead?

@hlieberman how important is it that we special case Debian? And how important is it that we follow the strategy Debian currently uses (install systemd timer too, disable cron job if systemd is detected)? The only consequence @bmw and I can think of of not doing these things is that renewal is checked twice more, which isn't really a bad thing (and also we'd save quite a bit of work if we didn't do these things).

**Comment by zjs** [comment]
> `*/12 * * * root python -c "from time import sleep; from random import randrange; sleep(randrange(3600));" && certbot -q renew # generated by certbot`

I'd suggest using `;` instead of `&&`. With `;`, the renewal will still be run if the call to python exits with a non-zero status (e.g., due to something killing the sleep).

Alternatively, `certbot-auto` could generate a random time when _scheduling_ the cron job. This would simplify the corntab logic, moving the complexity to the initial setup process where it would be easier for some to notice/debug the failure. With this approach, any given system would behave consistently/deterministically, but the load would still be spread out from the server's point of view.

**Comment by ynasser** [comment]
Thanks @zjs, those are great suggestions! I'll definitely incorporate them.

**Comment by ynasser** [comment]
For OpenSuse, we're going to need to add either cron (old) or cronie (newer) as a dependency, and going with the newer version is preferable (https://en.opensuse.org/openSUSE:Cron_replace#Differences_between_old_openSUSE.27s_cron_and_new_openSUSE.27s_cronie), but it'll uninstall the older cron package.

I can see this potentially breaking old scripts users have written around the crontab command (as its behaviour changes slightly), but I'm not sure how much of a problem this is. OpenSuSe's build service doesn't even list cron as a package anymore, only cronie: https://build.opensuse.org/project/show/openSUSE%3AFactory.

Some feedback from someone more knowledgeable about OpenSuSe would be great.

**Comment by computersalat** [comment]
/usr/share/doc/packages/cron/cron_to_cronie.README:
```
package cron 4.2 is only auxiliary package needed for proper renaming package cron to cronie

usefull links :
http://en.opensuse.org/Cron_replace
http://en.opensuse.org/Cron_rename
```
so it is still OK to _require_ ```cron```

**Comment by ynasser** [comment]
Thanks @computersalat!

**Comment by ynasser** [comment]
@bmw I just saw #4520. Since we're phasing out support for certbot-auto for quite a few of the experimental systems, presumably this means I should stop working on getting certbot-auto-cron to support the experimental ones, right?

**Comment by bmw** [comment]
Yes, you definitely don't need to get this working on the "experimental" systems. I didn't realize you had been working on that.

I also think it's fine if we leave out Arch Linux as well. It's technically not experimental, but we push people hard towards the built packages and users have to include `--debug` just like the experimental systems. See [this code](https://github.com/certbot/certbot/blob/v0.16.0/certbot-auto#L619).

**Comment by GreatEmerald** [comment]
I wouldn't want it to depend on cron, because cron is useless if the user only uses systemd timers. Mind you, it's fine to add crontabs, because without cron they will simply not do anything.

**Comment by computersalat** [comment]
> For OpenSuse, we're going to need to add either cron (old) or cronie (newer) as a dependency, and going with the newer version is preferable (https://en.opensuse.org/openSUSE:Cron_replace#Differences_between_old_openSUSE.27s_cron_and_new_openSUSE.27s_cronie), but it'll uninstall the older cron package.
> 
> I can see this potentially breaking old scripts users have written around the crontab command (as its behaviour changes slightly), but I'm not sure how much of a problem this is. OpenSuSe's build service doesn't even list cron as a package anymore, only cronie: https://build.opensuse.org/project/show/openSUSE%3AFactory.
> 
> Some feedback from someone more knowledgeable about OpenSuSe would be great.

Have a look here for openSUSE cron vs cronie:
https://en.opensuse.org/openSUSE:Cron_replace

**Comment by bmw** [comment]
I think we decided not to do this in favor of focusing on a new approach to packaging and distribution that will include automatic renewal configuration.

**Comment by daniejstriata** [comment]
Hi,

Should the output for a successful renewal alone be 0 and if no renewal was made/needed, make the exit code a 1? In doing so I can add a "&& apachectl graceful" which will only restart apache if needed to my activate a new cert.

When I ran `/root/certbot-auto renew -q` followed by `echo $?` when no renewal was done I see it completed successfully which is technically correct.

Is there another method I can use to determine if a new cert was issued and a restart of Apache required to active? Otherwise I can do a graceful each time which should not affect availability as much as having an expired cert. 

My cron:
```
#Certbot
0 0 */3 * * /root/certbot-auto renew -q && /sbin/apachectl graceful
```
