### ISSUE TITLE
Certbot with certonly command still attemps to change Virtual Host configuration

### ISSUE THREAD

**Issue by Eccenux** [certbot/certbot#3530]
So I already have everything setup and want to add just want to add a new domain to the certificate (I have a single cert with all domains). From doc: `certonly Obtain cert, but do not install it (aka "auth")`.

Steps:
1. Setup and install basic cert with: `./certbot-auto`
2. Expand cert: `./certbot-auto certonly --expand --apache -d www.main.pl -d main.pl -d www.different.pl`

Expected:
- Generate new certificate with a new set of domains.
- Update private key and the key chain.
- Update `/etc/letsencrypt/options-ssl-apache.conf` if required.

Actual result - I need to skip (Cancel) setting up domains one-by-one (there is one dialog like the one on the screen per additional domain).
![certbot-vhosts](https://cloud.githubusercontent.com/assets/1045235/18778490/d24bc3ea-8174-11e6-8cff-ae15907b8fd7.png)

**Comment by bmw** [comment]
First of all, I'd like to apologize for that terribly ugly dialog window. It's a known issue (#2025).

Let me explain what's going on here. In order to get your certificate, we need to prove to Let's Encrypt that you control that domain and in doing so we temporarily modify your Apache configuration by creating a new `VirtualHost` (see [this](https://tools.ietf.org/html/draft-ietf-acme-acme-02#section-7.3) if you're curious what changes we have to make). To make this vhost and add potential listen directives, we have to know what IP address and port is used for the domain you've requested. We only ask this question if there are no `ServerName` or `ServerAlias` records matching the domain you've requested.

We may be able to improve this behavior, but that's why Certbot asks you the question. When you hit cancel, it falls back to using all interfaces and port 443.

**Comment by Eccenux** [comment]
Hm... Maybe you could add some Skip all button. The result would be the same like when I click Cancel for each domain.

**Comment by rapmue** [comment]
hm, I have the same issue. but i have all the vhosts configured i try to issue the certificates...

**Comment by joohoi** [comment]
This is fixed, --expanding existing certificate using Apache plugin respects certonly verb.
