### ISSUE TITLE
Certificate generation can be improved (using certbot-auto)

### ISSUE THREAD

**Issue by lordspace** [certbot/certbot#3532]
I have wasted several hours and hopefully my time won't be totally lost by sharing my feedback.

1) I agreed to this and the tool keeps prompting me for every (sub)domain I have on the list.
Why?

certbot-auto certonly --allow-subset-of-names -a manual --rsa-key-size 4096 -v -d domain.com -d www.domain.com

> NOTE: The IP of this machine will be publicly logged as having requested this
> certificate. If you're running certbot in manual mode on a machine that is not
> your server, please ensure you're okay with that.

2) When a certificate doesn't verify prompt the user again and not just fail.

3) If you try to use --nginx this fails miserably so I have used manual mode

4) there has to be an option that would generate a list of files so I don't have to manually create those.

5) There has to be a better process for authenticating subdomains. The files should end in .txt so they can be easily downloaded. 

6) the output of the manual file should also be .crt and key files and not just a bunch of .json files.

**Comment by bmw** [comment]
Thanks for sharing your feedback. I'll start by saying the `manual` plugin certainly needs some UI work. In many places, the plugin is completely hidden from the user because of this.

> 1) I agreed to this and the tool keeps prompting me for every (sub)domain I have on the list.
> Why?

A fix for this has landed in `master` and will be included in the next Certbot release.

> 2) When a certificate doesn't verify prompt the user again and not just fail.

This is a bit tricky. Certbot uses an open protocol called [ACME](https://tools.ietf.org/html/draft-ietf-acme-acme-02) to get your certificates. There is a fair amount of negotiation that happens between the client and server before you get to the step of setting up challenges. If you fail a challenge, most of that work goes out the window and we have to start from scratch. We could potentially initiate another request with the server for you, but in most cases, failure to complete a challenge is the symptom of a larger problem that wouldn't be solved by trying again.

> 3) If you try to use --nginx this fails miserably so I have used manual mode

The Nginx plugin isn't included in [certbot](https://certbot.eff.org/docs/using.html#nginx)-[auto](https://github.com/certbot/certbot#current-features).

> 4) there has to be an option that would generate a list of files so I don't have to manually create those.

Depending on your setup, [webroot](https://certbot.eff.org/docs/using.html#webroot) may be what you want.

I think it depends on your setup whether automatically creating the files or providing you with the contents of the files is easier. We could potentially add an option to dump all the files in a directory for the user, however, because the files must have the names specified by the certificate authority which uses a long base64 string, conveying which file is for which domain is a bit tricky (see [the spec](https://tools.ietf.org/html/draft-ietf-acme-acme-02#section-7.2)). (Technically, the files just need to be accessible at a certain URI, however, in most setups, this is effectively the same thing). I suppose we could dump all the files in a directory with their long, unintelligible names and print a table showing which file is for which domain in the terminal? I'm not convinced this is that useful personally.

> 5) There has to be a better process for authenticating subdomains. The files should end in .txt so they can be easily downloaded.

The process for authenticating subdomains is controlled by the ACME spec which is in the hands of the IETF and outside of the scope of Certbot (which simply follows the spec). Feel free to make suggestions on their [repo](https://github.com/ietf-wg-acme/acme) or [mailing list](https://mailarchive.ietf.org/arch/browse/acme/).

> 6) the output of the manual file should also be .crt and key files and not just a bunch of .json files.

Can you tell me which files you are referring to? Do you mean the files in `/etc/letsencrypt/account`? These files have little to no use for the average user and are generated by Certbot for later runs of the program.

Your certificates and keys are saved in `/etc/letsencrypt/live/<domain>`. If you really want to use the files in `/etc/letsencrypt/account` (which does not contain a certificate so we can't include a `.crt` file), can you describe to me your use case?

**Comment by bmw** [comment]
All of these issues are either resolved or require clarification that hasn't been given since 2016. If anyone has constructive feedback to provide here, please comment or open a new issue.
