### ISSUE TITLE
Ubuntu 16.04 Aptitude package should not be recommended

### ISSUE THREAD

**Issue by cconover** [certbot/certbot#3538]
Over the weekend I had a few of my sites go down due to an expired Let's Encrypt certificate. I determined that the renewal process was failing due to [this documented error](https://community.letsencrypt.org/t/solved-keyerror-server-on-ubuntu-16-04-lts/15696/2). I had the latest `letsencrypt` package installed from the official Ubuntu 16.04 repository, but the latest version available through their repo is `0.4.1`. Once I manually downloaded and ran the Certbot client, I was able to renew my certificates without error.

Until a `1.0` release is made available, and the API is stable, or until Ubuntu's repositories have more frequent updates, Certbot should not be recommending that users install the `letsencrypt` package from Ubuntu, but instead suggest using the Certbot client directly.

**Comment by bmw** [comment]
To be clear, the problem you experienced here is due to the downgrade in the version of `certbot`/`letsencrypt` you were using. This will be a common problem, however, as people upgrade from Ubuntu 14.04 to 16.04. There is no certbot/letsencrypt package on Ubuntu 14.04 so people use `{certbot,letsencrypt}-auto`. When they upgrade to Ubuntu 16.04 and try to use the OS package, the process fails due the error you linked above. The Certbot team including our Debian package maintainer have [asked Ubuntu](https://bugs.launchpad.net/ubuntu/+source/python-letsencrypt/+bug/1610030) to consider upgrading to a newer version, however, they have been unresponsive.

In general, I feel that OS packages (including the out of date `letsencrypt` package in Ubuntu) provide a better experience for the user over the `-auto` scripts. If you're installing certbot/letsencrypt on your server for the first time, I think we should recommend Ubuntu's `letsencrypt` package over `certbot-auto`. However, since more and more `certbot-auto` users on 14.04 will be updating from to 16.04 this is perhaps something we should consider.

Other possibilities include:
* Explaining this complexity to Ubuntu 16.04 users on https://certbot.eff.org
* Resolving #1706 
* Work (harder) with Ubuntu to upgrade the package

I agree this a rough spot in using Certbot right now and we should do something to smooth it out.

**Comment by cconover** [comment]
Perhaps a solution would be to offer an official Certbot repository that could be added to the user's system through a script, similar to the [GitLab omnibus](https://about.gitlab.com/downloads/) package. That would allow Certbot/Let's Encrypt to maintain newer versions of packages, while still keeping the package manager experience.

**Comment by mcarpenterjr** [comment]
Maybe a short term solution is to direct users to the Ubuntu Other docs, that use the certbot-auto script?
[https://certbot.eff.org/#ubuntuother-apache](url)
Might help avoid some confusion.

**Comment by bmw** [comment]
This has been fixed.
