### ISSUE TITLE
apache plugin parses files from /etc/apache2/sites-available

### ISSUE THREAD

**Issue by anarcat** [certbot/certbot#3545]
sample certbot run here:

```
# certbot run --apache

Which names would you like to activate HTTPS for?
-------------------------------------------------------------------------------
1: foobar.example.com        
[...]
```

that domain is not actually enabled in my apache configuration: it is not symlinked to the `sites-enabled` directory:

```
root@marcos:/etc/letsencrypt# grep -R foobar.example.com /etc/apache2
/etc/apache2/sites-available/ikisite-foobar.example.com:        ServerName foobar.example.com:80
```

therefore it should not be detected by the apache plugin.

this is similar to #2949, except that one was treated as a problem parsing files with commas, whereas there is the larger problems of disabled configs here.

**Comment by bmw** [comment]
This was a design decision made when writing the plugin. Currently, in addition to parsing any files included by Apache, we also parse the `vhost_root` as it is defined in [this file](https://github.com/certbot/certbot/blob/master/certbot-apache/certbot_apache/constants.py) for your particular OS. This decision was explained a bit [here](https://github.com/certbot/certbot/issues/2949#issuecomment-218992638), but just because your virtual host isn't enabled doesn't mean that Certbot can't help you set up HTTPS for that name.

**Comment by anarcat** [comment]
i see. well, in my case it means way more domains than I expected to see, and it is really confusing because there's pretty old stuff in there. granted, I should cleanup that directory, but it seems to me that, at least, it should be made clear some directories are disabled.

i am also wondering how the apache plugin will configure LE on those vhosts if they are not configured. will they be temporarily enabled?

maybe i misunderstand how the plugin works.

thanks for the prompt response!

**Comment by bmw** [comment]
> it should be made clear some directories are disabled.

Certbot should understand that the virtual host is disabled and enable it if necessary. More on that below.

> i am also wondering how the apache plugin will configure LE on those vhosts if they are not configured. will they be temporarily enabled?

It depends. If you have a disabled SSL vhost in `sites-available` and you select the domain name found in that vhost, Certbot will enable it and install certificates to the vhost. If you select a disabled HTTP vhost, Certbot will make a copy of the vhost, replace port 80 with port 443, install any certificates, and enable the vhost. The old port 80 vhost will be enabled if you ask for a redirect from HTTP to HTTPS.

**Comment by anarcat** [comment]
On 2016-09-27 20:41:57, Brad Warren wrote:
>> it should be made clear some directories are disabled.
>
> Certbot should understand that the virtual host is disabled and enable it if necessary. More on that below.

I mean in the UI: active vhosts should be marked as a star or something,
and there should be an easy way to enable only active vhosts.

>> i am also wondering how the apache plugin will configure LE on those vhosts if they are not configured. will they be temporarily enabled?
>
> It depends. If you have a disabled SSL vhost in `sites-available` and you select the domain name found in that vhost, Certbot will enable it and install certificates to the vhost. If you select a disabled HTTP vhost, Certbot will make a copy of the vhost, replace port 80 with port 443, install any certificates, and enable the vhost. The old port 80 vhost will be enabled if you ask for a redirect from HTTP to HTTPS.

Does it disable the vhost when it's finished as well? If not, that a
serious issue: some disabled vhosts may be disabled for confidentiality
reasons and it's not immediatly obvious such a leak would occur...

a.

**Comment by bmw** [comment]
> I mean in the UI: active vhosts should be marked as a star or something,
and there should be an easy way to enable only active vhosts.

We could potentially add something like this. One potential problem is this question comes from the core Certbot package rather than the Apache plugin. I bring this up because asking about enabled/disabled vhosts doesn't make much sense for most other webservers as there's usually not a standard place for configuration files you have that you're not currently using. There are over a dozen [Certbot plugins](https://certbot.eff.org/docs/using.html#getting-certificates) and in most cases, having distinctions and prompts like this is unnecessary/invalid. That's an implementation detail we could work around if we wanted this though.

> Does it disable the vhost when it's finished as well? If not, that a
serious issue: some disabled vhosts may be disabled for confidentiality
reasons and it's not immediatly obvious such a leak would occur...

No. In my above description, if I said the vhost is enabled, it stays enabled. I appreciate your confidentiality concerns though. The question you're given while choosing domains is "Which names would you like to activate HTTPS for?". I think this strongly implies that we will configure Apache to respond to this domain (because otherwise we haven't properly enabled HTTPS for the domain) but this could be made more explicit.

**Comment by bmw** [comment]
@joohoi, another reason not to do this is invalid configuration files in `sites-available` completely break the Apache plugin because Augeas errors saying it can't parse the file.
