### ISSUE TITLE
Post to new-authz endpoint requires Expires

### ISSUE THREAD

**Issue by niklas-studer** [certbot/certbot#3556]
According to the ACME documentation the CA must leave the expires field in the new-autz post response empty. If that field is not present in the response certbot fails during the decoding of the response. According to the spec that field should never be there and therefore ignored.

**Comment by cowlicks** [comment]
Can you give a traceback showing certbot failing? Or even better, a test case. In [this unittest](https://github.com/certbot/certbot/blob/master/acme/acme/messages_test.py#L314) we create an `Authorization` object without an "expires" field. And in the [source code of `Authorization`](https://github.com/certbot/certbot/blob/master/acme/acme/messages.py#L365). It looks like we handle this case gracefully. Since that line contains `omitempty=True`.

And for posterity `new-authz`isn't in the [current draft](https://github.com/ietf-wg-acme/acme/blob/master/draft-ietf-acme-acme.md). But it could be [added back](https://github.com/ietf-wg-acme/acme/pull/165).

**Comment by niklas-studer** [comment]
@cowlicks my mistake. The date returned in my test was not a valid field. Not a bug - please close

**Comment by cowlicks** [comment]
@bmw closeable
