### ISSUE TITLE
Bugs with manual mode: webroot-path is ignored; --staging still created ssl in /live/ folder

### ISSUE THREAD

**Issue by lordspace** [certbot/certbot#3597]
letsencrypt 0.9.1

1) --webroot-path or -w options are being ignored.

The plugin still keeps prompting me to paste the verification code in well_known folder ?!?

`certbot-auto certonly -a manual --rsa-key-size 4096 -v --email admin@example.com --staging --verbose --text --agree-tos --webroot-path /var/www/vhosts/example.com/main/htdocs/ -d example.com -d www.example.com`

2)  with --staging option it created the SSL stuff in .../live/ folder however the full chain contained something with Fake CA X1

3) Can you please make it super non-interactive.

--agree-send-ip
--agree-renew

I'd like to be able to automate this without the tool touching my vhosts.

update: it seems --webroot-path appliedto 'certonly' why don't you have it for manual mode as well?

Why make things (more) complicated when they can be simple?

**Comment by bmw** [comment]
> 1) --webroot-path or -w options are being ignored.

Flags that begin with `--webroot` apply to the [webroot plugin](https://certbot.eff.org/docs/using.html#webroot) not the [manual plugin](https://certbot.eff.org/docs/using.html#manual).

> 2) with --staging option it created the SSL stuff in .../live/ folder however the full chain contained something with Fake CA X1

Yes. The `--staging` obtains certificates from Let's Encrypt staging/test environment which does not issue trusted certificates. This is explained in the help output for the flag:

```
  --test-cert, --staging
                        Use the staging server to obtain test (invalid) certs;
                        equivalent to --server https://acme-
                        staging.api.letsencrypt.org/directory (default: False)
```

> 3) Can you please make it super non-interactive.
>
> --agree-send-ip
> --agree-renew

The `manual` plugin will never be completely non-interactive as it's name suggests. It exists for users that we currently can't completely automate the process for in some way. This could be because they can't run Certbot on their server directly, they have load balancers sending traffic to multiple servers, etc. Based on the command you were using and your questions, it sounds like you want the webroot plugin. I linked to our documentation on the webroot plugin above. You can also find out more information about webroot by running `certbot --help webroot`.

If you do want to use the manual plugin, you can learn more about it by running `certbot --help manual` or by visiting the manual link above. There you will find this flag:

```
  --manual-public-ip-logging-ok
                        Automatically allows public IP logging. (default:
                        False)
```

which is the `--agree-send-ip` flag you asked for. Additionally, you probably want to be using the [renew](https://certbot.eff.org/docs/using.html#renewing-certificates) subcommand rather than `certonly`. This command will essential be a noop when your certificates are more than 30 days away from expiration and will renew your certificates otherwise.

If you do want to use the `certonly` subcommand for some reason, you can use the following flag as shown in our help output:
```
  --force-renewal, --renew-by-default
                        If a certificate already exists for the requested
                        domains, renew it now, regardless of whether it is
                        near expiry. (Often --keep-until-expiring is more
                        appropriate). Also implies --expand. (default: False)
```

It seems like the main problem here is you struggled to find the necessary instructions for your use case. Can I ask where you learned about Certbot and what documentation you were using? If there's any way we can smooth out this process for other people in your situation, we'd like to do so.

Let me know if you have any more questions.
