### ISSUE TITLE
Cert Management Improvement Project (C-MIP)

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#3615]
Based on previous discussions (#3587, #2071, #338), we should have an improved overall strategy for managing certs. This looks something like:

Step 1. list-certs command
Step 2. Specify canonical `{archive, live}` directories in conf file
Step 3. --use-lineage-name <lineage-name>
Step 4. --set-lineage-name <lineage-name>
Step 5. --use-lineage-name <wrong name or domain names or whatever>, "did you mean" based on filenames and such if ambiguous

Discussion items:
A. What should we call the canonical selector that I have temporarily termed "lineage-name"?
B. Where does this canonical name live?
Options for this include:
- as a line item in the conf file, whose name does not matter
- as the filename of the conf file, and document this choice.

I am personally for the latter, based on @schoen's observation that the file system then ensures uniqueness.

cc: @pde @bmw @cowlicks @PaulSD @yaegashi

**Comment by schoen** [comment]
I like calling it a lineage name and having it be the name of the file in `/etc/letsencrypt/renewal`, less the `.conf` suffix. (But I think that's the status quo, as nearly as we have one.)

I was hoping `--use-lineage-name` could just be called `--lineage`, although as @pde and I mentioned earlier today, it might be extra-confusing that the existing `-d` can mean both "apply this action to the lineage that has (at least) these domains" and "make this lineage have these domains". So it may be helpful to be sure `--use-lineage-name` and `--set-lineage-name` are very clearly different from one another.

**Comment by ohemorange** [comment]
I would like to amend step 2 to read:

Specify archive directory along with existing `{cert, privkey, chain, fullchain}` files in conf file.

This will remove dependence on lineage name in filepaths while maximizing the flexibility users have for specifying locations of files they plan to serve.

**Comment by ohemorange** [comment]
Update to step 2: Print a helpful error message if we are having trouble with the archive directory.

From @pde:

> 5:43:41 PM - pdeee: […]  think all of these cases can be handled by this algorithm:
> 5:43:49 PM - pdeee: if your live directory doesn't exist, make it
> 5:44:00 PM - pdeee: if your live directory has broken or outdated links, fix them
> 5:44:52 PM - pdeee: (using the relpath function Brad just linked to)
> 5:47:07 PM - pdeee: Probably if the archive directory in the renewal conf file has been edited, and the thing it points to doesn't look like an archive, we should just error out rather than trying to fix things
> 5:47:23 PM - pdeee: But make the error helpful

**Comment by peterthomassen** [comment]
It would be nice if `--set-lineage-name` would allow anything reasonable string (not just domain names).

Reason: In our use case, there's one certificate per virtual host (= FTP account), and domains sometimes come and go. In these cases, I'd like to update the certs on a per-user basis, and use the FTP user name as the lineage name. This would simplify things a lot.

**Comment by ohemorange** [comment]
@peterthomassen that's a reasonable goal. Would "any reasonable string that is a valid filename" be acceptable?

**Comment by peterthomassen** [comment]
@ohemorange Yes, that's what I meant. Of course nothing non-printable etc. :-)

**Comment by jvanasco** [comment]
Just noting my prior suggestion in #2880 to generate a plaintext `.txt` file that lists the domain names and signed/expires data alongside the certs. that would allow for instant inspection and even grep'ing the filesystem.

**Comment by peterthomassen** [comment]
@jvanasco Besides your suggestion being a different issue, I think this would create a redundancy that could lead to inconsistencies quickly. I think a better solution would be to write a command that produces such a list on stdout, so that you can do `certbot list-certs | grep ...` and always get live results from the real certs that are in place.

**Comment by jvanasco** [comment]
It's not a redundancy or different issue if it is an implementation detail for solving this ticket.

How do you envision `list-certs` generating the output -- by analyzing each cert/lineage on every invocation?  Will it list every cert in the archives or just the active ones?  An installation can have hundreds of certificate lineages, each with up to 100 domains, each having multiple issued versions - and they may or may-not be a currently active lineage.

If you're not running this on-demand but storing the certificate data in a file owned by the certbot client, what do users who operate a cluster do? (e.g. one machine runs LE to generate the certs, which are then synced to multiple other machines; any one machine might need to inspect certs).

If you save the "metadata" alongside the certificate in plaintext, the `list-certs` command can use that as the data source (instead of converting/parsing the ssl cert), it becomes much more portable across machines, and backups/archives aren't a nightmare anymore.  Simply including a plaintext document that lists the certificate contents/domains with the generated payload would make a lot of routine tasks easier -- including this `list-certs` command.

**Comment by multiwebinc** [comment]
@jvanasco Analyzing the certificates themselves should be relatively trivial, and using the certificates directly instead of a text file would prevent errors, like missing files, altered files, bad permissions, or even program errors. This is also not likely to be a command you're going to be executing frequently for the efficiency to really be much of a consideration. I would assume in the vast majority of cases it's only going to be executed when manually making changes to the certificates.

I would also actually disagree with your point about portability. I think the most portable thing is to only pass around the certificate file, not a certificate file and an additional text file containing the certificate "metadata" that are also contained in the certificate itself.

Just my $0.02.

**Comment by ohemorange** [comment]
Ok, I'm going to go ahead with `--use-lineage` and `--set-lineage-name`, and with the renewal config filename being the canonical name.

**Comment by ohemorange** [comment]
Actually, better idea, both `--use-lineage` and `--use-lineage-name` will work, because we can do that.

**Comment by ohemorange** [comment]
On second though, "use" is too general. I'm going to try things and see how they work when using them and get back.

**Comment by ohemorange** [comment]
Ok, proposal for the flag previously known as `--use-lineage`:
![untitled presentation](https://cloud.githubusercontent.com/assets/1227205/19825804/1092482a-9d33-11e6-9b83-c5779b18a2dc.png)

**Comment by ohemorange** [comment]
Proposal for the flag formerly known as `--use-lineage`:
![--lineage](https://cloud.githubusercontent.com/assets/1227205/19825948/65c24488-9d35-11e6-8e42-d94dae5984a1.png)
Please note that this does not currently allow any way of renaming existing lineages.

**Comment by ohemorange** [comment]
To go with this, we should have `certbot --rename-lineage OLDNAME NEWNAME`. Which just changes the name of the renewal config file.

**Comment by jpluimers** [comment]
Note that a lot of people noteing native English will have a hard time getting the meaning of lineage. I looked it up and think it comes close to ancestry but have a hard time relating that to the certificates. 

So this needs very intuitive usage scenarios and thorough documentation.

**Comment by peterthomassen** [comment]
@ohemorange Very nice draft! I suppose in the very right box, you mean `lineagename`, not `lineageagename` (the name of the age of the lineage? ::)

Also, I hope that it will be possible to use Option 2 from that very right box (existing lineage, with a new set of domains specified via `-d`) non-interactively. Do you think this will be possible?

**Comment by ohemorange** [comment]
@peterthomassen yes, the automation options should include flags to automatically select from any choice we present, thanks for the reminder!

@jpluimers you're absolutely right about lineage being confusing. that's what we call it internally in the codebase, but it doesn't have to be what we call it externally. any suggestions for a better word? alias? certificate chain? certificate group? (as an aside, it's called lineage because it's an ancestry of certificates that have replaced each other over time.)

**Comment by peterthomassen** [comment]
@ohemorange

1.) Automation: In non-interactive mode, option 1 in the very right box of your chart does not seem reasonable to me (the `-d` options would just be ignored). So, it is not a good idea to provide a flag to enforce option 1 behavior, because something is already wrong when such a command is run; the user should not have specified `-d` in the first place. My favorite behavior would be to just use option 2 without comment, assuming that non-interactive users know what they are doing. Alternatively, one could produce an error by default, and enforce option 2 using `--force-renewal` (this option already exists, meaning something similar.)

Thinking about it more, even in interactive mode, I think option 1 is not very reasonable; it seems like an input error. I think there should be a warning, asking the user for confirmation if (s)he really wants what was specified. In non-interactive mode, we can turn this warning into an error, unless `--force-renewal` is specified.

2.) Terminology: The lineage is really a certificate identifier. Below are a few possibilities that came to my mind (some of them like `alias` were already mentioned in related issues), in descending order of my personal preference. However, I think `lineage` is okay as well; it may be good to have the same term as in the code, for clarity. Suggestions: `label`, `certname`, `name`, `alias`.

(PS: Just making sure -- in that very right box, I assume that the word "update" in option 2 means updating the domain name list for this lineage, not updating (renaming) the lineage name to the first domain or something like that. So, the difference between options 1 and 2 is just the set of domains, right?)

**Comment by ohemorange** [comment]
@peterthomassen Nice suggestions, these match pretty closely with an IRL discussion from yesterday! Some updates from that:

- Have defined semantics for `--lineage lin_name -d domain -d domain2`; this means that you want to modify `lin_name` to include precisely `domain` and `domain2`. In interactive confirm, in non-interactive either error unless there's an affirmative flag or just do it, tbd.
- External name of `lineage` is `certificate name`, with flag `--cert-name`.
- Some copy changes specific to other places that I'll put in the specific PRs.

**Comment by jpluimers** [comment]
@ohemorange for me, `ancestry` is easiest to grasp but I'm not sure why (maybe because I'm partially wordblind).

Is there some kind of docs that explain how lineage/ancestry works for a certificate? How does it become part of such a chain? Where does the chain start? Is there some kind of "marriage" by which ancestry chains get joined? Or "divorce" for them to get split?

I'm trying to relate this to real-life things as I'm very much an associative thinker (heck that's how I remember most stuff), so correct me if those examples are way off.

**Comment by ohemorange** [comment]
@jpluimers this is not currently explained anywhere, but I believe we have an issue somewhere to explain this in the developer guide. We currently try to hide the fact that lineages exist at all from Certbot users, instead using the "renewal" fiction.

A lineage is a series of certificates that have replaced each other, currently either for the same set of domain names or for an increasing set of domain names when using the `--expand` flag. Each lineage has an associated config file under the `renewal` directory, and its name is the name of the config file. We don't ever actually renew certificates (this isn't a thing), we just get a new one and point the symlink under `live` to the new cert.

**Comment by PaulSD** [comment]
Looks like #3785 is missing --force-renewal (or some other mechanism for overriding the confirmation prompts), and is missing --rename-lineage.  Otherwise looks good to me.

**Comment by pde** [comment]
@PaulSD you're right there's an interactivity bug there

(Though note that `-n` / `--non-interactive` is the flag for turning off interactivity; `--force-renewal` does something different, which is to always renew a certificate even if it's not due for expiry, though using `--force-renewal` does indeed get rid of one specific interactive question that Certbot might ask).

**Comment by ohemorange** [comment]
@PaulSD @pde the most recent commit should fix this; `--renew-with-new[maybe soon to be requested]-domains` lets you bypass the only new ask.

**Comment by ohemorange** [comment]
With the major items completed and new issues created for some nice-to-have extra features, I'm marking this issue as completed. Thanks for all the help and input everyone!
