### ISSUE TITLE
Support requesting IDNA2008 Punycode domains

### ISSUE THREAD

**Issue by pde** [certbot/certbot#3619]
As a step toward #3614

**Comment by schoen** [comment]
I'm about 90% sure this can be accomplished by simply deleting the stanza starting at

https://github.com/certbot/certbot/blob/master/certbot/util.py#L449

If we could get punycode allowed on the staging server, I'd be glad to test it out.

**Comment by jsha** [comment]
@schoen @rolandshoemaker You should be able to get a local Boulder instance running that supports Punycode with:

```
docker-compose run --service-ports -e BOULDER_CONFIG_DIR=test/config-next boulder 
```

**Comment by rolandshoemaker** [comment]
Work is underway to enable IDN support in staging, hopefully should be available by the end of the week.

**Comment by jsha** [comment]
However, it's my opinion that we should work on landing the Certbot patch to remove the stanza Seth mentioned, without waiting for the flag to reach staging. We have two teams that work relatively closely together. If there are obstacles for Certbot developers to run the latest version of Boulder, we should hear about them and fix them.

Also, I'd like to have the Certbot patch ready in order to more easily test against staging.

**Comment by schoen** [comment]
I think #3626 should do this, but let's see how it does with the tests.

**Comment by schoen** [comment]
As we discussed, #3614 will be a little more complex. I have some code for it, but it will require changes in more places in order to display the IDNs consistently.
