### ISSUE TITLE
nginx-compatibility-weirdness

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3621]
Running off of the `nginx-compatibility-test` branch, I saw some strange behavior. When testing with all of `nginx.tar.gz` the tests all pass when `-ai` is included on the command line. However, I created a [tarball](https://github.com/certbot/certbot/files/523382/tiny.tar.gz) with the majority of the virtual host files removed and the tests failed due to the problem identified in #3605. What happened?

**Comment by bmw** [comment]
With the addition of #3607, tests pass on the tarball I linked above as well as the full `nginx.tar.gz`. We should still investigate this though to see why tests were passing.

**Comment by schoen** [comment]
After experimenting with different subsets and looking at what the files do and don't have in common, I'm starting to form a hypothesis that this has to do with nginx's behavior when being passed particular combinations of files, rather than with the `nginx-compatibility-test` falsely claiming that something has passed when it hasn't.

The `nginx-compatibility-test` (like `apache-compatibility-test`) attempts to test many vhosts (sites-enabled) in parallel with one another: in particular, all of those included in a single test case will be tested together, followed by all of those in another test case.

It appears that the particular file in @bmw's `tiny.tar.gz` test case, when run through pre-#3607 Certbot, *actually doesn't* make nginx start an HTTPS listener, yet in combination with other files, nginx *does* start a listener which is able to pass the tests. I haven't figured out why this is, but it would suggest that #3605 could be a kind of Heisenbug where you can only trigger the worst form of it if all of your vhosts are affected by it.

In this hypothesis, there may not be any bug in `nginx-compatibility-test` at all, although it would be a great incentive to include a wider variety of test cases somehow, to increase the chance that  interactions between vhosts within a test case don't mask the presence of bugs.

In support of this, the vhost in question is one of a minority of vhosts in the current `nginx.tar.gz` that attempts to do 

```
    listen 443;
    # [...]
    ssl on;
```

*from the outset*. I think that this is highly relevant to what #3607 fixed and I think it's plausible that nginx's overall behavior is affected globally by the presence or absence of `ssl on` directives in vhost files (that is, they affect each other). In support of this, the specific compatibility test that fails in this instance says that nginx isn't serving TLS on port 443.
