### ISSUE TITLE
`certbot-auto --version` still says `letsencrypt 0.9.3` (should say `certbot 0.9.3`?)

### ISSUE THREAD

**Issue by dusek** [certbot/certbot#3637]
Given the systematic renaming of this client from `letsencrypt` to `certbot` some while ago, I was surprised to receive this output:

```
$ certbot-auto --version
letsencrypt 0.9.3
```

I.e. the software still refers to itself as `letsencrypt` instead of `certbot`.

In case it is not desired (which I think so), I am letting you know.

**Comment by bmw** [comment]
I was also surprised by this output reading the issue, however, I've repoed the problem and know the cause. If you're curious, `certbot-auto` still installs the shim package `letsencrypt` for backwards compatibility. It also uses the command `letsencrypt` to call into Certbot for no other reason than we saw no reason to change it. Turns out that `argv[0]` is used to print the version string, so when calling into Certbot through the `letsencrypt` shim, you see `letsencrypt` rather than `certbot`.

This is a one line fix and will be changed in our next release. Thanks for reporting the problem.

**Comment by dashaxiong** [comment]
@bmw I have submitted a pull request to resolve this issue. I have solved it by setting `argparse`'s `prog` attribute to "certbot". This was a one line change, so it seemed to be what you referred to. The other way that occurred to me was to modify `letsencrypt-auto-source.template` to call the `certbot` script instead of `letsencrypt`. However, that seemed a bit more difficult and I probably don't understand the `letsencrypt-auto-source` script well enough to do that at this point.
