### ISSUE TITLE
Logger info messages go to stderr

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3666]
We recently reduced Certbot's logging level to `INFO` and cleaned up the output. As pointed out by @borisovg in #2264, however, we write all of this output to `stderr` which isn't the best place for `INFO` level messages (at least in the way we use them).

I think the best solution here is to stop using `logging` for progress/notification messages to the user. Instead, I think we should raise the default logging level back to `WARNING` and replace many calls to `logger.info()` with `IDisplay.notification()`.

If we implement #3572 as well (which we should), we'd want to use `logger.debug()` there and maybe add a prefix to each message like "Displaying notification: ".

Alternatively, we could split logging output between stdout/stderr, but I think keeping all logging information to one file stream is a little bit nicer.

**Comment by ohemorange** [comment]
Yeah, and this looks even nicer when #3665 is in.

**Comment by dmmortimer** [comment]
We noticed that running Certbox 0.9.x against Entrust's ACME service generates a lot more logs than 0.8.x, which is noisy for the user. So I +1 moving the progress messages, especially the ones about resetting dropped connections, into the log file and off the console.

**Comment by bmw** [comment]
@dmmortimer, which messages about dropped connections are you referring to? If messages like that are being shown to the user without `-v/--verbose` being provided, that's something else we should probably fix.

**Comment by dmmortimer** [comment]
I'm referring to frequent messages like this:
Resetting dropped connection: www.entrust.net

For example:
./letsencrypt-auto -d www.testcertificates.com -t --server https://www.entrust.net/acme/api/v1/directory/...
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Starting new HTTPS connection (1): www.entrust.net
Resetting dropped connection: www.entrust.net
Resetting dropped connection: www.entrust.net
Obtaining a new certificate
Resetting dropped connection: www.entrust.net
Performing the following challenges:
tls-sni-01 challenge for www.testcertificates.com
Enabled Apache socache_shmcb module
Enabled Apache ssl module
Waiting for verification...
Resetting dropped connection: www.entrust.net
Resetting dropped connection: www.entrust.net
Resetting dropped connection: www.entrust.net
Cleaning up challenges
Incomplete authorizations

I guess it's due to the particular way the server is configured and haven't dug into it yet, but the message does not seem to impact success or failure of the operation and is possibly confusing to the end user.

**Comment by bmw** [comment]
These messages come from [urllib3](https://github.com/shazow/urllib3/blob/1.16/urllib3/connectionpool.py#L249). Although they've reduced the logging level to not show these messages as often in their latest releases, this is a good argument for implementing what I proposed above rather than splitting log output between `stdout` and `stderr`. Certbot's dependencies may log information at lower logging levels that we don't want shown to the user.

This will be fixed with this issue.

**Comment by FelixSchwarz** [comment]
> Alternatively, we could split logging output between stdout/stderr, but I think keeping all logging information to one file stream is a little bit nicer.

I prefer having stderr for warnings/errors for simple automation reasons (cron):

1. I like to filter the (stdout) output with grep so I get an email when a certificate was renewed (e.g. to deploy a certificate manually to different hosts until I have this completely automated)
2. I'd like to get an email for all errors (message to stderr -> not filtered -> cron email).

So `--quiet` doesn't solve my use cases above.

**Comment by peterromfeldhk** [comment]
Im running on Amazon AMI, so i have to run with --debug, now i cant just mail errors and get email every time it runs because debug/log messages go to stderr

**Comment by azmeuk** [comment]
Is there any news about this issue?

**Comment by bmw** [comment]
Unfortunately, no. Are you interested in writing a PR?

**Comment by borisovg** [comment]
Problem is still there and is still very annoying.

**Comment by pr0totyp** [comment]
Yes still there! Stop logging to stderr -.-

**Comment by T313C0mun1s7** [comment]
This is frequently used in cron jobs and by logging a success to stderr you are completely breaking the intended behaviour of the e-mail notifications from crontab. Even work around scripts that attempt to be much smarter like cronic are going to interpret this as an error because the info loggin and success messages are being written to stderr rather than stout. I don't even see how there is room for discussion that this is appropriate. Then closing this rather than fixing it? Don't even get me started.

**Comment by adferrand** [comment]
There is no ongoing discussion, and the issue is still opened. I think everyone agrees on the need to change the behavior, and there are even some propositions to drive the implementation.

However, and as for the hundreds of issues opened in the repo, we do not have the time to solve everything with the current capacity in the dev team. Still, this is an opened source project: a really constructive action would be to write and submit a PR. We would be pleased to review it.

**Comment by T313C0mun1s7** [comment]
> There is no ongoing discussion, and the issue is still opened. I think everyone agrees on the need to change the behavior, and there are even some propositions to drive the implementation.
> 
> However, and as for the hundreds of issues opened in the repo, we do not have the time to solve everything with the current capacity in the dev team. Still, this is an opened source project: a really constructive action would be to write and submit a PR. We would be pleased to review it.

Some people are developers and have the skill to create and submit a PR. Others, like myself are on the Ops side and build and maintain the infrastructure you need to do your job. I am in the latter group, and this is software that provides a functionality to that latter group, to the former group can host their projects in a secure manner. Leaving bugs like this, that force the Ops person to ignore logs and warning because of this wrong and broken behavior does not help either side. Neither does suggesting to Ops people to do your job as a dev for you.

Eventually you are going to have one of your projects stop working for you because an SSL cert expired. It will have expired because the person responsible for your server or container was ignoring the logs and didn't know it was broken. You will blame them, but the fault will be yours.

**Comment by bmw** [comment]
@T313C0mun1s7, Certbot is a free and open source project written to a large extent by unpaid volunteers. Telling one of our volunteers to "do their job" and fix this feature for you is not appropriate. Please make sure any further comments on this issue are constructive and on topic.

Finally, while I'm aware there are other reasons to make this change, I think the majority of people who hit this issue can get the behavior they want by setting the `--quiet` command line flag which will cause Certbot to only produce output in the case of an error. Full logging information will still be written to the log files in `/var/log/letsencrypt` like normal.

**Comment by Clement544** [comment]
Still have been hacked

**Comment by massimans** [comment]
hello there,
yes i got "Saving debug log to /var/log/letsencrypt/letsencrypt.log" in stderr 
personally i wouldn't mind getting this kind of log if it wasn't wrongfully put in stderr
cheers

**Comment by mitar** [comment]
Tested with the latest. Still an issue. I would like to log to stdout or stderr only when there are errors.

**Comment by cloudcosmonaut** [comment]
In case you wonder: it's still the case

**Comment by bmw** [comment]
while changing this behavior does make sense, realistically, i don't think we're ever going to (be able to find the time to) do this so i'm going to close this as wontfix
