### ISSUE TITLE
Implement --vhosts (sni|san|both)

### ISSUE THREAD

**Issue by pde** [certbot/certbot#369]
If the client is obtaining certs for multiple names, it is possible to request one cert per name (controlled by SNI) or one cert for all names (using Subject Alternative Name (SAN) fields in the cert).  In theory if the webserver is smart enough, it should be possible to do both at once: if an SNI extension arrives in the handshake, send a small cert; if it doesn't, use the SAN cert.

**Comment by pde** [comment]
(Currently you should get SAN if you run the client once for all names, and SNI if you run it for each name in turn).

**Comment by xied75** [comment]
I wonder if this can be more generic so that even we use "manual" and "certonly" with dns-01, we can still choose to get a single or multiple certs supported directly by the tool.

**Comment by pde** [comment]
Another important option: `--vhosts sni` might work better if it made one cert per Apache VirtualHost or Nginx server block, rather than literally one cert per FQDN, because the latter would require much larger/uglier webserver configs.

**Comment by pde** [comment]
I feel we should either put this ticket (perhaps with a default of "sni", with one cert per vhost/server block) in the 1.0 milestone, or do the work necessary to fix the `--allow-subset-of-names` functionality thoroughly enough that we'd be comfortable really recommending it to people or making it a default (eg, having it kick in only a few days before expiry, and having it remember the "missing" domains if they become re-authable later).

**Comment by schoen** [comment]
This is an idea from over three years ago that we never pursued but that might improve the user experience in a number of contexts but would create tension with rate limits and with the ability to conveniently *remove* names.

I wonder if we could have an issue category for "this would improve Certbot, but it might require a breaking UI change or UI refactor" (@bmw).

If we did have some form of this feature, we would probably have a lot fewer sites breaking due to partially-failed renewals, but also more problems with hitting rate limits (and the overall issuance volume from Certbot users might be somewhere between 1.5 and 10 times as high as it is).

@jsha, is there a form of this feature that you think might be beneficial today?

**Comment by jsha** [comment]
I think the main problem with this is that it would require drastically rewriting people's Nginx and Apache config files to split into multiple vhosts. AFAIK both Nginx and Apache require a 1:1 vhost:certificate relationship (except for certificates that vary by key type).

Assuming the above is correct, I think this is a non-starter for the Nginx and Apache modes. And for manual and similar modes, it's easy to do single-name certificate by simply running single-name commands.

**Comment by pde** [comment]
I don't think that necessarily breaks the idea behind this ticket, which was:

 --vhosts sni  :  make one cert per vhost
 --vhosts san  :  make one cert for all domains
 --vhosts both :  do both of the above, serving the san cert if the client
                  doesn't support SNI (if that's possible)

On Wed, Sep 12, 2018 at 08:49:14PM -0700, Jacob Hoffman-Andrews wrote:
> I think the main problem with this is that it would require drastically rewriting people's Nginx and Apache config files to split into multiple vhosts. AFAIK both Nginx and Apache require a 1:1 vhost:certificate relationship (except for certificates that vary by key type).
> 
> Assuming the above is correct, I think this is a non-starter for the Nginx and Apache modes. And for manual and similar modes, it's easy to do single-name certificate by simply running single-name commands.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/certbot/certbot/issues/369#issuecomment-420874464

-- 
Peter Eckersley                            pde@eff.org
Distinguished Technology Fellow   Tel  +1 415 200 7907
Electronic Frontier Foundation

**Comment by jsha** [comment]
Oh I see what you're saying. I think the default behavior is `--vhosts sni`, which is strongly the behavior we'd like at the moment. We're starting to discourage people from putting a ton of SANs on a single certificate. So I would vote to close this; We don't want to add a configuration option that encourages people in a direction we're trying to deprecate.

**Comment by schoen** [comment]
Currently, Certbot never gets more than one certificate per time that it's run; if I understand properly, `--vhosts sni` was meant to provide a mode in which a single Certbot invocation would obtain one certificate for each subject name specified with `-d`.

In that interpretation, I think that `--vhosts san` is actually the only behavior that we have now, but *not* the one that you'd prefer for the future!

**Comment by makuser** [comment]
> I think the default behavior is `--vhosts sni`, which is strongly the behavior we'd like at the moment.

No, definitely not. (Unfortunately)

> We're starting to discourage people from putting a ton of SANs on a single certificate.

Oh that sounds great, but that's absolutely not what certbot is doing at the time of writing.

```
17:42:56,3 root@MAKserver08: ~ > ll /etc/apache2/sites-enabled/
total 20
drwxr-xr-x 1 root root 180 Jan 19 14:09 ./
drwxr-xr-x 1 root root 310 Jan 19 14:22 ../
lrwxrwxrwx 1 root root  35 Aug 29  2017 000-default.conf -> ../sites-available/000-default.conf
lrwxrwxrwx 1 root root  50 Jan 18  2018 collabora-le-ssl.conf -> /etc/apache2/sites-available/collabora-le-ssl.conf
lrwxrwxrwx 1 root root  37 Jan 19 14:09 homeassistant.conf -> ../sites-available/homeassistant.conf
lrwxrwxrwx 1 root root  33 Aug 29  2017 nextcloud.conf -> ../sites-available/nextcloud.conf
lrwxrwxrwx 1 root root  40 Jan 18  2018 nextcloud-le-ssl.conf -> ../sites-available/nextcloud-le-ssl.conf
17:43:01,4 root@MAKserver08: ~ > 
```
Vhost config:
`collabora-le-ssl.conf` contains `office.somedomain.eu`.
`nextcloud-le-ssl.conf` contains `cloud.somedomain.eu` and the alias `cloud-alias1.somedomain.de`.

Both vhosts share one certificate, because I really did not care about this at that time.
New vhost:
`homeassistant.conf` contains `hass.somedomain.eu`.

Current behavior:
```
17:43:01,4 root@MAKserver08: ~ > certbot
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator apache, Installer apache

Which names would you like to activate HTTPS for?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: cloud.somedomain.eu
2: cloud-alias1.somedomain.de
3: hass.somedomain.eu
4: office.somedomain.eu
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate numbers separated by commas and/or spaces, or leave input
blank to select all options shown (Enter 'c' to cancel): 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
You have an existing certificate that contains a portion of the domains you
requested (ref: /etc/letsencrypt/renewal/cloud-alias1.somedomain.de-0001.conf)

It contains these names: cloud-alias1.somedomain.de, cloud.somedomain.eu, office.somedomain.eu

You requested these names for the new certificate: cloud.somedomain.eu,
cloud-alias1.somedomain.de, hass.somedomain.eu, office.somedomain.eu.

Do you want to expand and replace this existing certificate with the new
certificate?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(E)xpand/(C)ancel: c
User chose to cancel the operation and may reinvoke the client.

IMPORTANT NOTES:
 - To obtain a new certificate that contains these names without
   replacing your existing certificate for cloud-alias1.somedomain.de,
   cloud.somedomain.eu, office.somedomain.eu, you must use the --duplicate
   option.

   For example:

   /usr/bin/certbot --duplicate
17:43:20,5 root@MAKserver08: ~ > 
```

So a year after I set it up for the first two vhosts, I now care that the individual vhosts get individual certificates, which they really don't - OOTB at least. Certbot would still put all of the hostnames on a single certificate, so I canceled the process.

@jsha which future version are you running, that does this out of the box? I'm asking because I'm still running the one that's in the debian unstable repo, and that is currently `certbot 0.28.0-1~bpo9+1`, but I would manually upgrade to the version you are running, just for this feature.

**Comment by jsha** [comment]
@makuser Looks like I was mistaken! Thanks for clearing that up.

**Comment by jsha** [comment]
Coming back to this conversation with fresh eyes I think the naming of the proposed flag is confusing. It's not about how many vhosts to set up, it's about how many certificates to make. And setting up SNI vs SAN is also confusing because they are technologies at different layers. How about a simple boolean flag:

```
--multiple-certificates  Get a separate certificate for each VirtualHost (Apache) or server
                         block (Nginx). Can make smaller certificates when you have many
                         hostnames on one machine. Incompatible with --domains (-d)
```

Also it's worth noting that this idea was internally generated and we seem to have gotten very few support requests for this. Maybe it indicates there's not much need? Or maybe this ticket is hard to find because it doesn't match people's conception of what they're looking for. At any rate, while I'd still kind of like to see this behavior happen, I acknowledge that it adds yet another flag, and it probably makes sense to close it out and reopen only if we see significant demand for it.

**Comment by bmw** [comment]
> At any rate, while I'd still kind of like to see this behavior happen, I acknowledge that it adds yet another flag, and it probably makes sense to close it out and reopen only if we see significant demand for it.

I agree. I'd personally kind of like to make something like `--multiple-certificates` (or maybe even one FQDN per cert) the default some day because I think it'd help mitigate some of our problems with duplicate certificates, but realistically, I can't imagine us getting to implementing this for a long time so I'm closing this for now.

**Comment by R0dri** [comment]
> Also it's worth noting that this idea was internally generated and we seem to have gotten very few support requests for this. Maybe it indicates there's not much need? Or maybe this ticket is hard to find because it doesn't match people's conception of what they're looking for.

Hello, I just learned the difference with SNI & SNA reading this thread. I have been using Certbot for 1-5 websites for a year now and have actually been using both SNI and SAN without knowing so. It wasn't until recent I expanded my workflow to something similar to #3490 that I felt the need to learn what the heck was SNI & SAN.

My personal experience I believe here lied most of my personal caveats which is best explained by the author of #3490

> The real issue here is not necessarily certbot's behaviour, but that the UI defaults to something which is (for many users) clearly not what they would want, and yet it gives no obvious cue that it will do this.
For some users, the intention of "https-enable-my-entire-sever" may be interpreted to mean "get me one https cert for everything", whereas for others, it means "https-enable each of my virtual-hosts [but I would never conflate them, and it is unthinkable that certbot would do that either]"

>Simply changing the interface text from "Which names would you like to activate HTTPS for?" to "Which names do you want to activate HTTPS, with a single combined certificate, for ?" (and maybe footnoting it with a link to an explanation) would make it much less misleading. I would be happy with that.f

**Comment by R0dri** [comment]
Also, 

The --multiple-certificates would be ideal, but maybe something more to it. For now im considering a shell script with that invokes Certbot and fills the `-d` flag with the contents of  a list in txt like:
`domain1.com`
`domain2.com`
`domain3.com`
`...`
 So I can have multiple lists and within the shell script invoke certbot with a different list multiple times.

I don't know how this can work agains the limit of requests but that is my thinking that would enable to allow me adding new servers easily and adding them to the respective certificate SAN.
