### ISSUE TITLE
Allow trailing dot in CN or SAN

### ISSUE THREAD

**Issue by ctubio** [certbot/certbot#3718]
I saw #2241, but instead of support, to me looks like an ignore of the trailing dot?

Because if a trailing dot is defined, certbot ignores it and creates the certificate for the domain without the trailing dot, and the result is:
```
$ curl -vvv https://example.com.
*   Trying x...
* Connected to example.com. (x) port 443 (#0)
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using DHE-RSA-AES256-SHA
* Server certificate:
*        subject: CN=example.com
*        start date: 2016-10-30 02:41:00 GMT
*        expire date: 2017-01-28 02:41:00 GMT
*        subjectAltName does not match example.com.
* Closing connection 0
* SSLv3, TLS alert, Client hello (1):
curl: (51) SSL peer certificate or SSH remote key was not OK
```
This was after run certbot with param `-d example.com.`

Is there any way to generate certificates with a trailing dot  in the CN or SAN with certbot?

Im asking because all my previous providers supported (without removing) the trailing dot and is a bit shocking to see #2241.
Thank you''

**Comment by schoen** [comment]
I don't believe that the Let's Encrypt CA will issue for this subject name at all, so the behavior of Certbot is correct in that respect. If I were going to assign responsibility for dealing with this, I'd suggest changing how curl checks subject name matches (because browsers work OK with a name like https://www.google.com./ even when the subject name in the cert doesn't have a trailing dot).

If you're sure that there's another CA that's willing to issue for this subject (which I'm not at all sure is the case), you could bring it up in https://github.com/letsencrypt/boulder/issues to ask them about server-side support.

**Comment by ctubio** [comment]
Is true that browsers works OK, is only curl failing.

**Comment by schoen** [comment]
I think curl's behavior is mistaken and it shouldn't reject this match.
