### ISSUE TITLE
debian jessie backports upgrade holds back packages

### ISSUE THREAD

**Issue by spieiga** [certbot/certbot#3741]
I guess there is a new upgrade available, but when running `sudo apt-get upgrade` on Debian 8 jessie (with backports repo added to apt), I get
```bash
spieiga@dev:~$ sudo apt-get upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  certbot python-acme python-certbot
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
```

**Comment by pde** [comment]
@spieiga what does `apt` say it's going to do if you run `sudo apt-get dist-upgrade`?

**Comment by spieiga** [comment]
It says
```bash
spieiga@dev:~$ sudo apt-get dist-upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following NEW packages will be installed:
  python-dnspython
The following packages will be upgraded:
  certbot python-acme python-certbot
3 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 321 kB of archives.
After this operation, 610 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
```

**Comment by pde** [comment]
I think this is going to be a wontfix, unfortunately. Certbot 0.9.0 began `Recommends:`ing `python-dnspython` because that helps with the new `--manual --preferred-challenge dns` mode. And `apt-get upgrade` isn't willing to install that as a side-effect.

You can get around this by either doing `apt-get dist-upgrade`, which will install that recommended package; or by doing `apt-get --no-install-recommends upgrade`, which won't.

**Comment by thomaszbz** [comment]
@spieiga It works perfectly fine by pinning the certbot packages and holding back everything else:

https://www.slicewise.net/debian/certbot-aus-backports-installieren/

https://translate.google.com/translate?sl=de&tl=en&js=y&prev=_t&hl=de&ie=UTF-8&u=https%3A%2F%2Fwww.slicewise.net%2Fdebian%2Fcertbot-aus-backports-installieren%2F&edit-text=
