### ISSUE TITLE
Revamp register subcommand

### ISSUE THREAD

**Issue by cowlicks** [certbot/certbot#3816]
The cli subcommand `register` is currently used for account management commands. This causes weird spellings like `certbot register --deactivate`. So `register` should probably be changed to `account`. I did some preliminary work on this [here](https://github.com/cowlicks/letsencrypt/commit/368c49c38e34c560fe9cb470656a02609f4ea066). But missed things like cli flags (`--update-registration`) and documentation.

**Comment by cpu** [comment]
Just wanted to mention that providing the "account" verb in the CLI going forward also has good synergy with the decision to [rename the "registration" in ACME to "account"](https://github.com/ietf-wg-acme/acme/pull/210). When the spec is finalized it will be using "account".

**Comment by pde** [comment]
Go ahead and make a PR!  The old `"auth"` verb is now `"certonly"`, so you can use that as a model.

**Comment by bmw** [comment]
We had a meeting about the Certbot command line awhile ago and decided we should make some changes here. In general, we decided that we should favor add more verbs/subcommands (which can be nicely grouped in our help as shown in #3883) rather than more flags to change behaviors of existing subcommands.

What this means here is that:

* `certbot register --update-registration` should become it's own subcommand. I'm open to suggestions on the name here. To implement this, we can probably change the verb in `certbot.cli.HelpfulArgumentParser.parse_args` if `certbot register --update-registration` is used to preserve compatibility.
* `certbot register --deactivate` as implemented in #3571 should become something like `certbot unregister`.
* `certbot register` should only be used to create a new account with the ACME CA. We can potentially change the name of this subcommand but I personally like it given its new, more specific purpose.

**Comment by dschlessman** [comment]
I'm taking a look at this one at PyCon.

**Comment by bmw** [comment]
Here's a way to run a single problematic test with `pytest`:

```
pytest certbot/tests/main_test.py::MainTest::test_update_registration_unsafely -s
```
`-s` stops `pytest` from capturing terminal output.

On top of that, our tests were capturing terminal output. This breaks the test, but so you can step through it to see what's going on, you can make the following changes:
```
diff --git a/certbot/tests/main_test.py b/certbot/tests/main_test.py
index 22653ca3..c0a5b83f 100644
--- a/certbot/tests/main_test.py
+++ b/certbot/tests/main_test.py
@@ -624,10 +624,10 @@ class MainTest(test_util.ConfigTestCase):  # pylint: disable=too-many-public-met
         args = self.standard_args + args
 
         toy_stdout = stdout if stdout else six.StringIO()
-        with mock.patch('certbot.main.sys.stdout', new=toy_stdout):
-            with mock.patch('certbot.main.sys.stderr') as stderr:
-                ret = main.main(args[:])  # NOTE: parser can alter its args!
-        return ret, toy_stdout, stderr
+        #with mock.patch('certbot.main.sys.stdout', new=toy_stdout):
+        #    with mock.patch('certbot.main.sys.stderr') as stderr:
+        main.main(args[:])  # NOTE: parser can alter its args!
+        return None, toy_stdout, stderr
 
     def test_no_flags(self):
         with mock.patch('certbot.main.run') as mock_run:
```
Use https://stackoverflow.com/questions/12320863/how-do-you-take-a-git-diff-file-and-apply-it-to-a-local-branch-that-is-a-copy-o if you want to apply this diff with git.

To set a breakpoint, use `import ipdb; ipdb.set_trace()`.
