### ISSUE TITLE
Does not detect ServerAlias with wildcard

### ISSUE THREAD

**Issue by arnolem** [certbot/certbot#3821]
Hello,

I have vHost with wildcard on ServerAlias but certbot does not detect this vhost

```
<VirtualHost *:80>
    ServerName my.server.com
    ServerAlias partner.my.*.server.com
...

```
When I execute cerbot on my Ubuntu 16.04 on Apache, I have this:

> Which names would you like to activate HTTPS for?
> [  X  ] my.server.com

**Comment by pde** [comment]
Hi @arnolem! Because Let's Encrypt and ACME don't presently support wildcard certs, there's no way for us to support this in general.  You'll need to specify a list of domains you want with `--domains`.

(Even if we did add support for wildcards in the future, it probably wouldn't help you if the `*` is not at the leftmost portion of the domain name -- certs with multi-level wildcards are rare, and most CAs won't issue them).

**Comment by pde** [comment]
(I think this is a wontfix/cantfix for the time being)
