### ISSUE TITLE
Solaris support for Certbot and certbot-auto

### ISSUE THREAD

**Issue by hflaisher** [certbot/certbot#3841]
I am trying to install certbot on Unix Solaris running Apache 2.4.23.  I am at this page:  https://certbot.eff.org/#pip-apache and have run the initial installation commands listed there:

wget https://dl.eff.org/certbot-auto
chmod a+x certbot-auto

When I attempt to run the 3rd command listed:

$ ./certbot-auto

I get the error in the subject line. 

I would appreciate if someone could point me to a solution.  Thank you.

**Comment by pde** [comment]
Certbot doesn't have Solaris support! So this reply is a guide to building it for yourself, if you'd like to :)

```
./certbot-auto: syntax error at line 23: `BASENAME=$' unexpected
```

That's odd -- it seems your system does not have a POSIX compliant `/bin/sh`:

http://pubs.opengroup.org/onlinepubs/007904875/utilities/xcu_chap02.html#tag_02_02_03
http://pubs.opengroup.org/onlinepubs/009695299/utilities/basename.html

You may be up against [this issue](https://unix.stackexchange.com/questions/164203/will-a-shell-script-execute-in-solaris-if-not-which-is-the-fastest-way-to-make), which honestly makes me think Solaris is going to be insane and hard to support without breaking compatibility with other things.  You could just edit your copy of `certbot-auto` to use a POSIX-y shell, and then always run with `--no-self-upgrade`.

But once you've solved that, you're still going to have the problem that `certbot-auto` doesn't currently have an OS bootstrapper to provide Solaris support, so you'll have to figure out how to get Certbot's dependencies installed yourself. A workaround would be to follow [these instructions](https://certbot.eff.org/docs/contributing.html#running-a-local-copy-of-the-client) to run Certbot without `certbot-auto` (but instead of the `--os-packages-only` step, install OS dependencies, which are goups 1,2,3,4 in [this list](https://github.com/certbot/certbot/issues/1301#issue-114753911) manually).

Or you could even send us a PR that adds a Solaris [bootstrapper](https://github.com/certbot/certbot/tree/master/letsencrypt-auto-source/pieces/bootstrappers) to `certbot-auto`.

Nextly, if you want to run the [Apache plugin](https://certbot.eff.org/docs/using.html#plugins), you'll need to make sure that it knows the correct values for all of these commands and directories on a Solaris system: https://github.com/certbot/certbot/blob/master/certbot-apache/certbot_apache/constants.py.  You could do that by providing lots of flags like `--apache-vhost-root` etc setting values for these, if the defaults are wrong, or again send us a PR adding them to that `constants.py` file.
