### ISSUE TITLE
Allow for a flag disabling some vhosts

### ISSUE THREAD

**Issue by Frankkkkk** [certbot/certbot#3885]
I am a mirror for some distribs and for the ntp pool. That means that I have various "loadbalancing domains" that may sometimes go to my server and sometimes not (pool.ntp.org, mirror.archlinuxarm.org, …).

The problem is that when I have to reselect the websites, I always have to cherry-pick the websites I don't want HTTPs activated on (or else the renewal will fail).

A flag such as `#CERTBOT_DONT_ASK_HTTPS` in the corresponding apache vhost files would be great. It would inform the certbot renewal thingy not to ask me for an HTTPS certificate for this domain.

Thanks,
Cheers

**Comment by pde** [comment]
Hmmm, interesting.  A few possible solutions:

1. You call certbot with `--domains` specifying the domains you actually want
2. You ask for all domains, including some you might not have pointing at you right now, and use the `--allow-subset-of-names` flag so that Certbot doesn't error out if some of the domains fail authentication. If you did this, you might have some trouble with automated renewal; once a name has failed to authenticate at renewal time on one occasion, it will never be re-added by the `certbot renew` command. Performing renewal by running `certbot certonly --allow-subset-of-names` or `certbot --allow-subset of names` interactively is fine though, and would add the name back.
3. Implement the flag you ask for, which could be `--except-domains DOMAINS`.

Note that solutions 2 and 3 both require us to do #3887 too.

**Comment by pde** [comment]
(I mean if we wanted to support clean automatic renewal via `certbot renew` with option 2, we would need to do #3887).

**Comment by Frankkkkk** [comment]
Actually I've just found out that I can simply add an empty virtual host `<VirtualHost *:80></VirtualHost>` in the vhost file to render this file "invalid" and thus not showing it in the list ;-)
But that's a crappy solution. 

I find option 1 a bit limiting. I have ~ 40 FQDNs and the arg would get a bit long. Solution 2 seems good to me though. 

Actually I think that it shouldn't be certbot's concern whether a fqdn wants https or not… well, of course it is, but the fact that a fqdn doesn't want https should be stated on the file showing the fqdn instead; thus the vhost apache/nginx/… file. I suppose that making the parser "crash" on a special keyword may be an easy solution; maybe not the cleanest one. Actually I have no idea how it works, so…

Anyways, thanks

**Comment by bmw** [comment]
While perhaps you might have to write a long command line or [configuration file](https://certbot.eff.org/docs/using.html#configuration-file), I'm not sure adding more options is worth it here, especially when you only have to run this command once and then you can happily run `certbot renew`. I'm closing this issue, but if anyone would like me to reconsider, please comment or open a new issue explaining why.
