### ISSUE TITLE
 The client lacks sufficient authorization :: Incorrect validation certificate for TLS-SNI-01 challenge. Requested 53e284899cd48a822380048681b90521.6ee8cb35eaf00278ae373218f6207c97.acme.invalid from 5.152.178.140:443. Received certificate containing 'sitename.co.za, sitename.co.za'

### ISSUE THREAD

**Issue by neilAzapi** [certbot/certbot#3946]
The client lacks sufficient authorization :: Incorrect validation certificate for TLS-SNI-01 challenge. Requested 53e284899cd48a822380048681b90521.6ee8cb35eaf00278ae373218f6207c97.acme.invalid from 5.152.178.140:443. Received certificate containing 'intranet.scp.co.za, www.intranet.scp.co.za' -  I get this error when i run certbot-auto, i have implemented same functionality on the 4 other servers but with this server there is an conflict with an existing ssl cert from GoDaddy, is there any reason why this will not allow me too generate a cert? I am using webroot to specify path for the command - Thanks in advance

**Comment by schoen** [comment]
Hi @neilAzapi, 

This suggests that you are using the `TLS-SNI-01` challenge, which is *not* a webroot-based authentication method (it is based on changing the server's certificate configuration, not based on creating a file at a specified location, as webroot does).

In this case the problem seems to be that a `TLS-SNI-01` challenge was selected when you didn't expect it to be. Can you tell us what command line you were using? Without knowing what command you ran, I'd say it's possible that you've made a mistake or oversight of some sort in your command line.

**Comment by neilAzapi** [comment]
Greetings,

Thanks for the help, i really appreciate the help.

Below is my command:
certbot-auto --email sysadmin@azapi.co.za --agree-tos --webroot --webroot-path=/path/to/the/domain -d domainName -q --apache certonly -vvv

**Comment by neilAzapi** [comment]
I have sorted the issue 👍  your support was excellent and response deserves a medal 🥇  haha thanks guys

**Comment by walttheboss** [comment]
neil says he sorted the issue.  PLEASE write back to say how!!!

**Comment by goldengit** [comment]
This is an old post but I found a solution that worked - Was getting the same error on an ubuntu 16.04 server - resolved the issue by forwarding ports 80 and 443 in my router settings, to the host ip (this ubuntu server) and re-ran the command worked as expected and added the certificate - hope this helps others!
