### ISSUE TITLE
--deploy-hook

### ISSUE THREAD

**Issue by pde** [certbot/certbot#3947]
`--renew--hook` should probably be supplanted by `--deploy-hook`, which should run when you first make a cert as well as when you renew one.

**Comment by maddes-b** [comment]
Just encountered the problem with current certbot-auto 0.9.3 that renew hooks are not run with certonly command, although this hook is to prepare the retrieved certificate for usage (e.g. converting, here to RSA key format for ESXi).

**Comment by bmw** [comment]
We won't be able to get to it this release.

**Comment by bmw** [comment]
To better explain what we need to do here, we want to:

1. Hide `--renew-hook`. This can be done by setting `help=argparse.SUPPRESS` when the `--renew-hook` command is added in `cli.py`.
2. Add a `--deploy-hook` flag that works the same as `--renew-hook` except it is also called after the cert is obtained for the first time.

How exactly this is done can be left up to the implementator, but the way I'd probably do it is to set `dest='renew_hook'` when adding `--deploy-hook` to `cli.py`. This preserves forward compatibility so when people obtain a cert providing `--deploy-hook` the hook will still be run during renewal with older versions of Certbot. (Downgrading your Certbot version happens from time to time as people switch from `certbot-auto` to OS packages.)

The only other piece I believe you need is a way to differentiate whether `renew_hook` in a config was set by `--deploy-hook` or `--renew-hook` so if you're obtaining a cert for the first time you only run the hook if it was set by `--deploy-hook`. The way I'd do this is by using `certbot.cli.set_by_cli`.

Please let me know if you have any questions!

**Comment by maddes-b** [comment]
Just got a mail that the issue was closed, so I had a quick look and recognized that I missed bmw's post from April, and I have one concern:
Do **not** handle "--renew-hook" and "--deploy-hook" in different ways, no matter how they were stated.
"--renew-hook" was not fully implemented, as the corner case of a new certificate via certonly was missing. The rename to "--deploy-hook" is just cosmetic to make it more clear to the user and the developer.

If you treat them in different ways depending where they were stated, then this will lead to confusion.
For instance if I request a new certificate and use "renew-hook" in it for backwards compatibility, will it be executed with certonly or not?

Please use "--renew-hook" as a synonym to "--deploy-hook" and do **not** handle them differently. Please.

**Comment by ynasser** [comment]
@maddes-b

As you can see in @bmw's PR here: https://github.com/certbot/certbot/pull/4895/files#diff-fee68073ff44ffe30e9303db0210c070R98, `--deploy-hook` is literally a synonym for `--renew-hook`, as the only thing the `deploy_hook` function does is called the `renew_hook` function. So, no need to worry! Thanks for your input :)

**Comment by maddes-b** [comment]
Thanks for clarification :)
