### ISSUE TITLE
Make certonly also work for sites that already are invalid

### ISSUE THREAD

**Issue by binarykitchen** [certbot/certbot#3951]
I have a situation where I run a test site with an expired, invalid certificate (worse, on HSTS).

Hence a command like this fails during verfication:
$ sudo certbot certonly --webroot -w /etc/ssl/something/staging -d staging.something.io

with 
```
Failed authorization procedure. staging.something.io (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Could not connect to staging.something.io
```

I assume a curl-like command is run. If so, needs the `-v` option to ignore existing insecure certificates.

**Comment by binarykitchen** [comment]
And yeah, using v0.9.3 on Ubuntu 16.10 here.

**Comment by pde** [comment]
The HTTP-01 challenge used by Let's Encrypt when you use `--webroot` begins on port 80, so no certs are checked. If you redirect over to 443, I *still* don't think the cert is checked (but see 
https://github.com/letsencrypt/boulder/issues/1492 to confirm that).

My first suggestion would be:
1. Make sure that domain name is pointing at the right server
2. Try the `--nginx` plugin instead of `--webroot`. It works pretty well in Certbot 0.9.x, and doesn't use HTTP01 at all it'll make a new transient server block to pass a TLS-SNI-01 challenge.

**Comment by pde** [comment]
3. If you really want to use `--webroot`, make sure you *aren't* serving the redirect from HTTP to HTTPS for paths below `.well-known/acme-challenge`.

**Comment by binarykitchen** [comment]
ah right, i had a bad redirect from http to https somewhere further up in the nginx config.

regarding `--nginx` ... will it directly modify some nginx configs?

**Comment by pde** [comment]
@binarykitchen yes. If you use it with `certonly` they will be transient modifications; if you use it with `run` (the default), it will also install the cert in your config.
