### ISSUE TITLE
Refactor renewal.py

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3976]
I had to add `# pylint: disable=too-many-branches` to `handle_renewal_request()` today. We should refactor functions like this to make them more manageable, testable, and easier to read.

**Comment by bmw** [comment]
I ended up being able to remove this comment, but I think this is still a worthwhile task.

**Comment by pde** [comment]
One way to do this would be to make a small class that could contain the lists `renew_successes`, `renew_failures`, `renew_skipped` and `parse_failures` and provide methods for adding to and reporting based on them. All the logging and output could be side effects of adding to the lists.

**Comment by pde** [comment]
Have been slightly tempted to do that for a long time.

**Comment by bmw** [comment]
Yeah I remember you talking about that.

An approach like that could work. If this is done, the class should probably be placed in it's own file and have it's own unit tests.

**Comment by bmw** [comment]
Honestly, this file doesn't seem too bad anymore. I think `handle_renewal_request` is a little long and could be stand to be broken up a bit, but the file itself isn't that long and most functions are reasonably short.

**Comment by lmeerwood** [comment]
If you don't mind I could try implement a new class to handle those lists. I'm assuming that the "easy-fix" tag is for beginner contributors like me?

**Comment by adferrand** [comment]
Yes I am still not very satisfied by the code I wrote in `handle_renewal_request` even if I think we agree that is better than before. The two things that bother me are that error handling is way too visible, and the loop that feeds 4 arrays is super weird.

You can give a try, I will gladly review it. Be really careful about respecting the logic, in particular about when it waits, and when and how it errors out, because this is really sensible.

**Comment by lmeerwood** [comment]
Sorry, my circumstances have changed and I no longer have the free time to attempt this.
