### ISSUE TITLE
Add Sphinx Dependencies for Updating Documentation

### ISSUE THREAD

**Issue by nickfong** [certbot/certbot#3980]
Right now there isn't a list of dependencies that are needed to run 
```
make -C docs clean html man
```
to build the documentation.  Adding these dependencies to `contributing.rst` would save developers time when trying to locally verify the formatting of their changes to the documentation.  

I will work on this myself; opening this issue for tracking.

**Comment by bmw** [comment]
If this is about Python dependencies (which was the purpose of the PR opened to solve this issue is about), I think this is solved through our `[docs]` extras. If someone wants to make the existence of these extras more clear, feel free, but as I said on the PR, we automatically install all of this for you if you follow our getting started or docker instructions.

If this is about OS dependencies, this is covered by #6288. For that reason, I'm closing this issue.
