### ISSUE TITLE
Certbot help showing default arguments improperly

### ISSUE THREAD

**Issue by czirkoszoltan** [certbot/certbot#3987]
When issuing:
certbot-auto --help certonly

I get output like:
[...]
  --manual              Provide laborious manual instructions for obtaining a
                        cert (default: <certbot.cli._Default object at
                        0x255e410>)
  --webroot             Obtain certs by placing files in a webroot directory.
                        (default: <certbot.cli._Default object at 0x255e490>)

Version numbers:
certbot-auto --version
letsencrypt 0.9.3
python --version
Python 2.7.3

This works properly with the same certbot, but with python 2.7.12.

**Comment by czirkoszoltan** [comment]
this also applies to 0.10.1:

# /etc/letsencrypt/certbot-auto --version
certbot 0.10.1

# /etc/letsencrypt/certbot-auto --help renew
[...]
  -q, --quiet           Silence all output except errors. Useful for
                        automation via cron. Implies --non-interactive.
                        (default: <certbot.cli._Default object at 0x4523b50>)

**Comment by SwartzCr** [comment]
Thanks for the report @czirkoszoltan 
Can you be a bit more specific about what part of that output is improper?
Also what system are you running these commands on?

**Comment by czirkoszoltan** [comment]
The parts like "<certbot.cli._Default object at 0x4523b50>" are incorrect.
The system is Welcome to Ubuntu 12.04.5 LTS, my current certbot version is certbot 0.12.0, with outputs like the above. Python version is Python 2.7.3 (default, Oct 26 2016, 21:01:49).

**Comment by SwartzCr** [comment]
@bmw any idea why we're spewing these things?

**Comment by bmw** [comment]
This was introduced in 24cc03d1f6e3d3fb5a89aa489b0bd2f71fc80684. Playing with it, whether or not you get this error seems to depend on your Python/argparse version. It doesn't happen with newer versions of Python.

For whoever works on this, the difference in `argparse`'s behavior is whether or not the `type` parameter is called on a `default` string when `--help` is provided.

**Comment by bmw** [comment]
The change `argparse`'s behavior I described above happened in 2.7.4 which came out in April of 2013. Versions of Python 2.7 older than this have this problem. Python 2.6 users are unaffected because since `argparse` isn't in the standard library, we use the `argparse` from PyPI which is a newer version of the module.

It appears that Debian 7.0 Wheezy is the only distro that both has a version of Python with this problem and is still supported by the distro maintainers. We have a lot of users on this platform though so I'll figure out a way to work around this problem.
