### ISSUE TITLE
Track down rsa key size heisenbug

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#4005]
```
FAIL: Test that relevant_values() can reject a default value.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/certbot/certbot/certbot/tests/storage_test.py", line 566, in test_relevant_values_default
    self.assertEqual(self._test_relevant_values_common(values), {})
AssertionError: {'rsa_key_size': 2048} != {}
- {'rsa_key_size': 2048}
+ {}
```

Showed up in py33 test here: https://travis-ci.org/certbot/certbot/jobs/190406373

**Comment by pde** [comment]
I was able to reproduce this with

```
for n in `seq 30` ; do venv/bin/tox -e py27 || break ; done
```

**Comment by pde** [comment]
I believe I was *not* able to reproduce it by running 30 loops of `venv/bin/nosetest --processes=-1 certbot/tests/storage_test.py`. So that's evidence that it may be an interaction between something in `storage_test.py` and something in some other test file. 

But it could also be the case that by loops of length 30 aren't sufficient to be statistically infinite.

**Comment by pde** [comment]
Can also reproduce with
```
for n in `seq 30` ; do venv/bin/nosetests --processes=-1 certbot || break ; done ; echo errored on attempt $n
```

**Comment by bmw** [comment]
I fully believe this could have been a problem with nose is/was no longer maintained. We've since switched to `pytest` and I haven't seen this issue, but if someone does, please let me know!
