### ISSUE TITLE
Certbot-auto and 3rd party plugins

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4037]
As reported by @gboudreau in #4020, because `certbot-auto` recreates the venv every time it upgrades, it removes any 3rd party Certbot plugins that may have been installed here. This is rude.

Easiest and most straight forward fix is to upgrade the existing venv rather than creating a new one.

**Comment by bmw** [comment]
@erikrose, when you get some spare cycles, I'd love your thoughts on how to fix this issue.

**Comment by erikrose** [comment]
The reason to recreate the venv is to remove any packages we used to depend on but no longer do. Python being the dynamic language it is, the mere presence of an old package can occasionally affect the behavior of the program in a hard-to-debug way.

1. One easy quick fix (but with the consequence of a steady drip-drip of weird bug reports as old packages fester) is to stop recreating the venv.
2. The harder, more correct approach is to find a way to separate plugin-installed packages from the ones certbot itself needs. `pip install --target` (to install certbot's packages into a different folder) might be a part of this, but there are corner cases such as packages that both certbot and a third-party plugin need: where do they end up, and what if different versions cohabit in the same interpreter?
3. A third approach would be to come up with some less stateful way of installing third-party plugins, instead of just pip installing them. Then we could still recreate the venv but then, afterward, also automatically install the desired third-party plugs on top.

I think we'd be getting into some Real Crazy Stuff in 2. 3 would entail some nontrivial design work, user behavior changes, and troublesome corner cases if, say, we decided to express third-party plugins in terms of their PyPI package names but a private, unpublished plugin is needed. 1 is probably the way to go. It should be rare that a stale venv actually affects anything, and we can always add a flag (or a manual instruction) to start from a fresh venv as a troubleshooting step.

**Comment by gboudreau** [comment]
@erikrose Care to review #4047, that implements my best guess as to how to implement 1.

**Comment by zjs** [comment]
It seems like this is a duplicate of #1279.

> A third approach would be to come up with some less stateful way of installing third-party plugins, instead of just pip installing them. Then we could still recreate the venv but then, afterward, also automatically install the desired third-party plugs on top.

This sounds sort of like what I described in [my comment there](https://github.com/certbot/certbot/issues/1279#issuecomment-290796148).

**Comment by bmw** [comment]
Yeah this is a dupe. Thanks for pointing that out.
