### ISSUE TITLE
renew calls 'installer.restart()' after every individual renewal

### ISSUE THREAD

**Issue by frozen-sky** [certbot/certbot#4045]
If the `certbot renew` command is executed, certbot scans the available configurations and decide which certificates needs to be renewed. (in `renew_all_lineages()`). 
Once a renewal_candidate if found, `obtain_cert()`, is executed. `obtain_cert()` will execute a `installer.restart()` every time it obtains a new certificate.

If you have a plugin/usage, where restarts are not so graceful or take a long time (for ex. java applications), this can have the undesired effect of unnecessary restarts when multiple certs are renewed in one batch.

The expected behavior is to restart only once after all renewals are processed. 

* tested on 0.9.3
* linux/64-bit/debian jessie

(patch pending, test against 0.11.0.dev.0 pending)

**Comment by bmw** [comment]
The issue with only calling `restart` once is that different installers could be used for each cert.

**Comment by SwartzCr** [comment]
@bmw I think we should decide if we should close this issue or open a new one that handles this if all installers are the same

**Comment by bmw** [comment]
Thinking about this more, I don't think we can change behavior here even if all installers are the same. Imagine someone writes a 3rd party plugin that configures a web server remotely. Despite different certs using the same installer class, you still need to call restart once for each cert to make sure the appropriate remote web server is restarted. Since someone could easily do something like this with Certbot, while it'd be performance benefit to only call `restart` once in many cases, I don't think this is something we can reliably do with the current plugin architecture.

I'd love to see a proposal/PR on how to accomplish this here, but in the meantime, I'm going to move this ticket to the 2.0 milestone so we can consider this limitation when making breaking changes to Certbot in the future.

**Comment by frozen-sky** [comment]
Interesting use-case, however, if someone writes an installer which does something like you describe, it is very likely the plugin also needs to copy/deploy the certificate at some remote location as well, (unless the certbot keystore is on a shared filesystem; this is why I opened ticket #4046 earlier). 
In that case, the author of the plugin can decide to integrate the restart command as part of deploy_certificate() (or renew_deploy_certificate()) method and solve the restart after every deploy within the plugin itself without relying on certbot to call restart() every time.
However the other way around it is not possible. At this point it is not possible to limit the amount of restart() calls executed by the renew handler. Of course it is solvable with post-hook commands, and leaving restart() empty in the plugin, but in my opinion that a bit hacky.
An other option would be to introduce a reload() call, which can be called every time, and a restart() which is called only once per installer type in the renewal case.

**Comment by bmw** [comment]
Good point! In general my concern is that because the installer has a completely different `config` object for each renewal, calling `restart()` only once for each class makes the assumption that the `config` object is irrelevant for the `restart()` call. For most plugins, this is the case, but I'm a bit worried if this is an assumption we should be making.

I'd be okay with adding another method call before 2.0 as long as it doesn't break existing plugins.

**Comment by frozen-sky** [comment]
thinking about it I think `reload()` and `restart()` does not give the correct expatiation. an easy way-out would be to call a `renew_restart()` method (if it exists & is callable) and otherwise fall back on `restart()`. `renew_restart()` will be called after every renewal, and `restart()` only after the whole renewal process, per installer type in this case.
But it feels all a big ugly to me and would be fond of finding a better solution, I also get your point about the `config` object.
