### ISSUE TITLE
renew function does not call installer.deploy_cert()

### ISSUE THREAD

**Issue by frozen-sky** [certbot/certbot#4046]
The `renew` function does not call `installer.deploy_cert()` on every renewal. While this is expected behavior, there are also use-cases where it is desired the installer does handle/process the certificate on renewal. Use-cases are coping certs into a java keystore or push them to some other location/database where they are used. Not all application can work with (sym)linking to the certificates/keystore certbot provides itself.

Of course this kind or processing can also be handled by a wrapper script and/or by using the hooks available in `renew` command. But it would be nicer if this is possible within the plugin infrastructure itself, as it is very likely this code would be very similar to the deploy_cert() code when a new certificate is requested and it is better to keep similar processing in the same place.

We propose to introduce a `renew_deploy_cert()` in the `IInstaller` interface, and call this once a certificate is renewed. Standard the implementation should be empty, to keep the same behavior as in the current situation. But now it's up to the plugin developer to decide if they do or don't want to handle the new certificate in some manner. 

- tested against 0.9.3
- tested on 64-bit/debian jessie

(patch pending, testing against 0.11.0.dev.0 pending)

**Comment by bmw** [comment]
You're right that skipping the call to `deploy_cert()` for renewal won't work in some cases and I agree with you it is better to fix this problem with the plugins rather than writing a workaround.

I wouldn't be opposed to adding a new method like `renew_deploy_cert()` or `redeploy_cert()`, but we could perhaps just get away with just calling `deploy_cert()` on every renewal. This downsides of this are that most plugins would do unnecessary work on renewal and the change in behavior could cause bugs, but it keeps our interface simple and has Certbot make fewer assumptions about what the plugin is doing when it deploys a cert.

With that said, I don't have a strong preference on the approach taken here. If you're planning on sending a patch, I'll let you implement whichever approach you prefer.

**Comment by frozen-sky** [comment]
Thanks for your feedback. I've the patch ready with the renew_deploy_cert() scenario. I will go over it tomorrow once more and will get some second pair of eyes over the code and issue a pull request.

**Comment by Sakorah** [comment]
I have a plugin which handles the authentication and installation of the certificates for a F5 BIG-IP Loadbalancer. This all works fine for the first run, while the renew only renews the certificate but I need to copy the certificate to the loadbalancer, but the renew does not call the installer.

So is there a workaround available? I don't like to handle this with extra scripts via the renew-hook as I have to code the installer in the plugin and in a script which is just not nice.

So whats the status of this?

**Comment by bmw** [comment]
I suggested a potential workaround in [this post](https://github.com/certbot/certbot/pull/4199#issuecomment-295023089).

**Comment by Sakorah** [comment]
ok, thanks!
I also stumbled across https://github.com/certbot/certbot/issues/4045 which is kinda similar as a possible solution.

**Comment by bmw** [comment]
While changing the existing `deploy_cert` method to be called with `certbot renew` wasn't done, there's is now a separate function plugins can implement which will be called at renewal time. See https://github.com/certbot/certbot/blob/v0.26.1/certbot/interfaces.py#L646.
