### ISSUE TITLE
OSError: Command /root/.local/share/letsencrypt/bin/python2.7 - setuptools pkg_resources pip wheel failed with error code 2

### ISSUE THREAD

**Issue by zanjs** [certbot/certbot#4062]
OS : Ubuntu 16.04

```
Reading package lists... Done                     
Reading package lists... Done
Building dependency tree       
Reading state information... Done
augeas-lenses is already the newest version (1.4.0-0ubuntu1).
ca-certificates is already the newest version (20160104ubuntu1).
gcc is already the newest version (4:5.3.1-1ubuntu1).
libaugeas0 is already the newest version (1.4.0-0ubuntu1).
libffi-dev is already the newest version (3.2.1-4).
python is already the newest version (2.7.11-1).
python-dev is already the newest version (2.7.11-1).
libssl-dev is already the newest version (1.0.2g-1ubuntu4.5).
openssl is already the newest version (1.0.2g-1ubuntu4.5).
python-virtualenv is already the newest version (15.0.1+ds-3ubuntu1).
virtualenv is already the newest version (15.0.1+ds-3ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Creating virtual environment...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2363, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 719, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 988, in create_environment
    download=download,
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 918, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 812, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /root/.local/share/letsencrypt/bin/python2.7 - setuptools pkg_resources pip wheel failed with error code 2

```

**Comment by baijianpeng** [comment]
I met exactly the same issue today on Ubuntu 16.04.1 LTS.

Could you please improve this script to fix it?

Thank you.

**Comment by bmw** [comment]
This issue is very similar to #2883. Either install `letsencrypt` through `apt` (which is [what we recommend](https://certbot.eff.org/#ubuntuxenial-other) on Ubuntu 16.04) or take a look at the other thread for issue. Many people seem to have had success by [setting their locale](https://github.com/certbot/certbot/issues/2883#issuecomment-216427925).

**Comment by baijianpeng** [comment]
Well, I finally solved this issue myself, the solution is:

https://github.com/interbrite/letsencrypt-vesta/issues/46#issuecomment-273014451

**Comment by zanjs** [comment]
OK , `sudo apt install letsencrypt`

**Comment by willin** [comment]
0.4.1 does not have nginx plugin included

**Comment by adrianoafonso** [comment]
Same problem here:
Rasperry Pi v3
Server version: Apache/2.4.18 (Ubuntu)
Description:    Ubuntu 16.04.2 LTS

**Comment by samazgor** [comment]
### I solved the issue to my Ubuntu 16.04 x64...

1. `sudo apt-get install letsencrypt`
2. exoprt below
```
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
```

**Comment by antrecu** [comment]
as of today the --no-bootstrap helped on an Ubuntu 16.04 install.

**Comment by hoozecn** [comment]
I believe it's caused by the python version of virtualenv.

`
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 812, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /root/.local/share/letsencrypt/bin/python2.7 - setuptools pkg_resources pip wheel failed with error code 2
`

The letsencrypt takes python2.7 but it invokes virutalenv with python3 to create virtual environment.

Here is my fix:

`
pip2 install virtualenv
certbot --version
`
