### ISSUE TITLE
Add a "rekey" verb

### ISSUE THREAD

**Issue by pde** [certbot/certbot#407]
One of the major commands letsencrypt needs to support is "rekey", which causes the issuance of new certificates with new keys, and probably revocation of the old ones.

A lot of people will want a "reissue" verb but the problem with that is that it really isn't clear if there should be a new key or not.

**Comment by pde** [comment]
This command may be called out as the way to deal with incorrect certs in the Subscriber Agreement.

**Comment by schoen** [comment]
It's possible that this should go into the cert management tool that @jdkasten and I were talking about (a way of doing things to certs other than obtaining and deploying them). Maybe I can open a new issue for the cert management tool.

**Comment by bmw** [comment]
The current behavior of the client is to always use a new key when issuing a certificate. As correctly pointed out by @aetherknight, this is a problem for servers using HPKP. I thought a potential work around was to specify `--key-path` when creating a certificate, but apparently that doesn't work either (see #1490 and #1491).

Whether we create a new verb or just create a flag like `--reuse-key`, automatically finding and reusing the prior key is a nice feature that we should implement on top of #1491.

**Comment by aetherknight** [comment]
I would argue that being able to specify an existing key is really important for supporting HPKP, so that users can set up a backup key that is stored offline.

Browsers will not enforce HPKP unless the header specifies the hash for two or more more unrelated keys. More specifically, browsers will only use and cache the HPKP header if there is at least one hash that matches a certificate in the certificate chain for the site, as well as at least one hash that is not in the certificate chain.

It is possible to use an intermediate CA (or a root CA) instead of the leaf node certificate with HPKP, but then users would have to pick a different intermediate certificate or CA as their backup (or use a backup key as the second pin). This would be easier to use with how letsencrypt currently works, but it removes the flexibility of choosing the most specific certificate in order to minimize the attack surface that HPKP mitigates. Using intermediate certificates as pins is significantly more secure than no HPKP, but if any of the 2+ pinned intermediate certificates is used to create a fraudulent certificate then an HPKP-protected site would be out of luck. It also means deciding in advance which other CA an operator wants to do business with, and that decision cannot be changed if the Let's Encrypt intermediate CA is compromised and the operator is forced to re-issue their certificate with the other CA (after which they have to add the new Let's Encrypt intermediate certificate to the header and then they have to wait the HPKP max-age before they can start using such a certificate again, assuming they still want to use Let's Encrypt).

**Comment by jsha** [comment]
Closing because right now "renew" automatically rekeys. The HPKP questions here (allow issuing with a specific key) are discussed in https://github.com/certbot/certbot/issues/1491.
