### ISSUE TITLE
Renew Hook before DV

### ISSUE THREAD

**Issue by trlthiago** [certbot/certbot#4070]
Hi, I work for a host provider and I'm trying to use certbot. 

I am using the following command:
`certbot certonly --webroot -w /home/{domain}/public -n -q -m {email} -d {domain} --agree-tos --cert-path /etc/letsencrypt/archive/{domain} --key-path /etc/letsencrypt/archive/{domain} --chain-path /etc/letsencrypt/archive/{domain} --fullchain-path /etc/letsencrypt/archive/{domain}`

My problem is that I haven't control over my customers' htaccess content, and many of them have some rules that block access to folders and files starting with dot (e.g .well-known). This is making fail the domain validation.

Some example of rules:

```
<IfModule mod_rewrite.c>
    RewriteRule "(^|/)\." - [F]
</IfModule>
```

`RewriteRule . /index.php [L]`

`RewriteRule ^(.*)$ index.php/$1 [L]`

Even if I remove the htaccess file before call certbot, they can redeploy their websites putting the htaccess back, and making the renewall process fail in the future.

During renewal process I am missing a hook before validation of each domain, not only after as renew-hook does, so I'll be able to deal with htaccess individually.

Is it possible to be implemented?

**Comment by bmw** [comment]
Starting with Certbot 0.10.0, you should be able to use `--pre-hook` for this task. Pre-hooks you provide on the command line will be stored and reused when the certificate is renewed (if you're using `certbot renew`). The only difference here is we don't set an environment variables before calling the pre-hook and it is only called once for the certificate, not once for each domain. Because of this, you have to write something like:
```
certbot certonly ... --pre-hook "move_htaccess.sh {domain}" ...
```
where you pass in the domain(s) affected on the command line.

**Comment by trlthiago** [comment]
Thank you @bmw, I made the update and it worked perfectly 😄

**Comment by bmw** [comment]
Glad I could help.
