### ISSUE TITLE
letsencrypt error: unrecognized arguments: --post-hook

### ISSUE THREAD

**Issue by pkarjala** [certbot/certbot#4121]
Ubuntu 16.04
letsencrypt 0.4.1, installed as per instructions at https://certbot.eff.org/#ubuntuxenial-apache

This is likely related to #3663.

When setting up the auto-renew cron job as per instructions at https://certbot.eff.org/docs/using.html#renewing-certificates, I used the example code for auto-renewing certs, tweaked for our installation:

`letsencrypt renew --agree-tos --email someone@example.com --post-hook "service apache2 restart"`

However, when this runs, I get an error in the logs:

```usage:
  letsencrypt [SUBCOMMAND] [options] [-d domain] [-d domain] ...

The Let's Encrypt agent can obtain and install HTTPS/TLS/SSL certificates.  By
default, it will attempt to use a webserver both for obtaining and installing
the cert. Major SUBCOMMANDS are:

  (default) run        Obtain & install a cert in your current webserver
  certonly             Obtain cert, but do not install it (aka "auth")
  install              Install a previously obtained cert in a server
  renew                Renew previously obtained certs that are near expiry
  revoke               Revoke a previously obtained certificate
  rollback             Rollback server configuration changes made during install
  config_changes       Show changes made to server config during installation
  plugins              Display information about installed plugins
letsencrypt: error: unrecognized arguments: --post-hook service apache2 restart
```

It would be good to update the install instructions so that a user doesn't download the letsencrypt package from the Ubuntu repo, as it does not support all of the listed command flags, which becomes frustrating down the road.  IMHO it should not be the recommended install solution, or a note should be made that it is not kept up-to-date with the upstream package, and alternate install instructions should be included for those that want the latest version.

**Comment by bmw** [comment]
I think this issue basically identifies two potential problems:

1. Our documentation is for the most recent version of Certbot which isn't available on all systems. Like you said, another instance of this problem is #3663. I created #4124 to deal with this problem in the general case.
2. Our Ubuntu packages should not be recommended. See #3538 for more information on this, but at this time we disagree. Currently, the only option is `certbot-auto`, which is a temporary hack that bypasses conventional packaging to get you the latest Certbot. For the average user, we think this is a bad idea, however, if `certbot-auto` better fits your needs feel free to use it. You can find instructions [here](https://certbot.eff.org/#pip-other). We're very close on getting a [newer Certbot package in both Ubuntu 16.04 and 16.10](https://bugs.launchpad.net/ubuntu/+source/python-letsencrypt/+bug/1640978?comments=all) as well as recommending a PPA (see #1706), but neither packages are quite ready yet.

With #3538 and #4124, I think this issue is covered by other issues, but please let me know if I missed something. Thanks for reporting the issue so I could open #4124.

**Comment by pkarjala** [comment]
Both of your points identify the issue, and I agree with your assessment of them!  I would posit that #1706 would be a better solution to the issue overall for item 2, but am glad to see the new Certbot package making its way into Ubuntu 16.04 and 16.10.

We will likely go ahead and move off the `letsencrypt` package and over to `certbot-auto` for our needs in the meantime.  Thanks for your attention to the matter.

**Comment by bmw** [comment]
Glad I could help. We very well end up going the PPA route (or offering both by trying to keep Ubuntu reasonably up to date but offering the absolute latest in the PPA). There are packages in the PPA now, but I want to do a little more testing and review before we tell the public to start using them.

Thanks for the feedback!
