### ISSUE TITLE
certbot cannot find a cert or key directive in files

### ISSUE THREAD

**Issue by guoyunhe** [certbot/certbot#4129]
My Apache vhost config fiie:

```apache
<VirtualHost *:80>
 DocumentRoot "/srv/www/htdocs/nextcloud"
 ServerName cloud.guoyunhe.me

 ErrorLog ${APACHE_LOG_DIR}/error.log
 CustomLog ${APACHE_LOG_DIR}/access.log combined

<Directory /srv/www/htdocs/nextcloud>
 Options +FollowSymlinks
 AllowOverride All

 <IfModule mod_dav.c>
 Dav off
 </IfModule>

 SetEnv HOME /srv/www/htdocs/nextcloud
 SetEnv HTTP_HOME /srv/www/htdocs/nextcloud

</Directory>

</VirtualHost>
```

Then I run `certbot --apache` and get error:

```
Cannot find a cert or key directive in /files/etc/apache2/vhosts.d/cloud.guoyunhe.me-le-ssl.conf/IfModule/Directory
```

openSUSE Tumbleweed 20170124.

Certbot version 0.10.1.

**Comment by bmw** [comment]
Thanks for the bug report and configuration file. I was able to reproduce the problem. We'll try to look into this soon.

**Comment by ynasser** [comment]
Hey @guoyunhe, I tried out your Apache vhost config file on Tumbleweed with Certbot 0.14.1, and I wasn't able to reproduce this. Our apache plugin has undergone significant improvements since you filed this issue so there's a reasonable chance that whatever the problem was, it's been fixed recently. Could you try this again with 0.14.1 and let us know if it's still a problem?

Thanks again for the bug report :)

**Comment by ynasser** [comment]
Hey @guoyunhe, any updates on this?

**Comment by guoyunhe** [comment]
Hi @ynasser . Sorry for late reply! I will test it again on my server. Now I should have version 0.15 from openSUSE repository. I will let you know when I have test results.

**Comment by guoyunhe** [comment]
I tested it again with certbot 0.16. Cannot reproduce this bug anymore. Think it should have been fixed.
