### ISSUE TITLE
Nginx plugin does not see hosts starting with dot or new line

### ISSUE THREAD

**Issue by Yumash** [certbot/certbot#4144]
```
server {
    listen 80;
    server_name .test.ru
	.te-st.ru
	.t-e-s-t.ru;

```

This construction ignores by certbot-auto --nginx

**Comment by bmw** [comment]
I'm not able to reproduce a problem with hosts starting on a new line, however, it's expected behavior that Certbot will not suggest hosts starting with a dot. If you look at the log files in `/var/log/letsencrypt` or run Certbot with `-v` or `--verbose`. you should see lines like:
```
Not suggesting name ".test.ru"
Requested domain .test.ru is not a FQDN because it contains an empty label.
```
A domain starting with a dot isn't a valid domain name so Certbot ignores it because it can't do anything with it. What is the purpose of the dot prefix in your configuration files?

**Comment by Yumash** [comment]
Yes, i checked again and noticed that the behavior with new-line is logical.

As for dot:
http://nginx.org/en/docs/http/server_names.html

> For these reasons, it is better to use exact names where possible. For example, if the most frequently requested names of a server are example.org and www.example.org, it is more efficient to define them explicitly:
> 
> server {
>     listen       80;
>     server_name  example.org  www.example.org  *.example.org;
>     ...
> }
> than to use the simplified form:
> 
> server {
>     listen       80;
>     server_name  .example.org;
>     ...
> }

As for there is no wildcard at Certbot, i suppose that it would be great to offer a cert for a core domain and it's www subdomain, isn't it?

Thank you!

**Comment by bmw** [comment]
I personally didn't know that `.example.org` was shorthand in Nginx for `example.org *.example.org`. Thanks for the link.

Luckily, Certbot understands this though. If you have `.example.org` in your configuration file and provide `--domains example.org,www.example.org,subdomain.example.org` on the command line, Certbot will properly obtain and install your certificate.

We could suggest a certificate for the base of the wildcard and the www subdomain, but I'm not sure we want to do this. If that server block is being used for any other subdomains, users will get certificate errors because their domain isn't contained in the certificate being used by Nginx. Certbot can't possibly know whether or not this is the case and we don't want to suggest actions to the user that will misconfigure their webserver.

Certbot is and should be able to do this if specifically requested though. We could potentially allow users to add their own domains in addition to the domains suggested by Certbot though rather than making them provide these values on the command line.

**Comment by Yumash** [comment]
Seems to be quite logic.
