### ISSUE TITLE
Skip Easy/Secure prompt when already redirecting

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#4175]
Using the Nginx installer on latest Certbot, I get prompted with "Easy / Secure." When I say yes (on a host that is already redirecting), I get this message:

> The appropriate server block is already redirecting traffic. To enable redirect anyway, uncomment the redirect lines in /etc/nginx/sites-enabled/blocktogether.org.

If we can detect the redirect is in place, can we skip the prompt?

**Comment by bmw** [comment]
Not without changing the plugin interface. Currently the relevant methods we have are:
```
    def enhance(domain, enhancement, options=None):
        """Perform a configuration enhancement.

        :param str domain: domain for which to provide enhancement
        :param str enhancement: An enhancement as defined in
            :const:`~certbot.constants.ENHANCEMENTS`
        :param options: Flexible options parameter for enhancement.
            Check documentation of
            :const:`~certbot.constants.ENHANCEMENTS`
            for expected options for each enhancement.

        :raises .PluginError: If Enhancement is not supported, or if
            an error occurs during the enhancement.

        """

    def supported_enhancements():
        """Returns a `collections.Iterable` of supported enhancements.

        :returns: supported enhancements which should be a subset of
            :const:`~certbot.constants.ENHANCEMENTS`
        :rtype: :class:`collections.Iterable` of :class:`str`

        """
```
We could make `supported_enhancements` take a domain and return what enhancements the plugin can enable for that domain. Alternatively, we can make another method that performs this task.

This also gets a bit tricky when running the client for multiple domains because you currently have to apply the same enhancements to all domains for that run. Perhaps we should remove this restriction, although that will significantly increase the number of prompts and/or the complexity here.

**Comment by jsha** [comment]
Okay. I'm happy to close this as Won't Fix since it's a fairly minor UX issue.

**Comment by bmw** [comment]
I think that's the right call at least until we're comfortable making breaking changes. How about I reopen this but move it to the 2.0 milestone so it's something we can consider when redesigning our interfaces?

**Comment by jsha** [comment]
Sounds good.
