### ISSUE TITLE
which domains do you want to select should indicate which are from LetsEncrypt

### ISSUE THREAD

**Issue by jsoref** [certbot/certbot#4213]
I'm slowly migrating domains on systems, often there's a private domain (www.example.org) and a public domain (www.example.com). I might replace the private domain w/ letsencrypt for testing purposes, and then once it works run certbot again to deploy it for the other domain. But the domains are fairly similar, it'd be helpful if the letsencrypt domains were badged as such to make it easier to identify the ones I haven't upgraded yet.

**Comment by SwartzCr** [comment]
I'm going to put this in the wishlist milestone and we'll bring it into a sooner one once we find someone who's willing to make the change

**Comment by SwartzCr** [comment]
@bmw can you provide a description of where this should be inserted into the code and what it should look like?

**Comment by bmw** [comment]
The way this works in the code is the Certbot core asks the selected [installer](https://certbot.eff.org/docs/contributing.html#installer) plugin which domains are available in the user's configuration files. The installer plugin returns a list, which Certbot displays to the user to pick from.

Making this change would require modifying the plugin API to allow installer plugins to tell the Certbot core whether a domain already supports HTTPS and/or a certificate from an ACME CA. Since changes to our plugin API used by our [third party plugins](https://certbot.eff.org/docs/using.html#third-party-plugins) must be done carefully, I'm removing the label "Good Volunteer Task" from this issue.

**Comment by jsoref** [comment]
I doubt this was fixed.

**Comment by bmw** [comment]
While I agree this change has value, I honestly doubt we'll ever have the resources to prioritize it so I'm going to close it as won't fix. Thanks for the suggestion though!
