### ISSUE TITLE
Chrome doesn't accept certificate for the main domain

### ISSUE THREAD

**Issue by grigorgeous** [certbot/certbot#4240]
I have the following issue: Chrome browser (both desktop and mobile) shows me "Not Secure" label for my main domain "https://astrakhan.ru/" while it works OK for "https://www.astrakhan.ru/". Firefox and IE work just fine. What causes the problem? Chrome shows me only "net::ERR_UNEXPECTED" error but this doesn't seem to be any helpful.

**Comment by strugee** [comment]
@grigorgeous I don't know for sure, but my guess is that Chrome is penalizing you for a non-optimal TLS configuration. I'd guess it's because your server doesn't have robust forward secrecy support, or perhaps because it doesn't prefer server-negotiated cipher suites.

https://www.ssllabs.com/ssltest/analyze.html?d=astrakhan.ru will help you.

**Comment by grigorgeous** [comment]
It was a Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=695193

**Comment by SwartzCr** [comment]
great - I'm going to close this issue - feel free to reopen it if you find that it's a problem with Certbot!
