### ISSUE TITLE
Get static typing (using mypy?)

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#4244]

**Comment by ohemorange** [comment]
http://blog.zulip.org/2016/10/13/static-types-in-python-oh-mypy/

**Comment by ynasser** [comment]
Since we need to support Python 2.6, we can only use the comment-style type annotations mentioned in the blog post above (i.e. the ones from the `typing` module). The type-hints-in-function-definitions syntax (such as `def my_function(numbers: List[int]) -> str:` is only available in Python 3.4+.

As for where to start annotating, the blog post above suggests that changes can be gradual and suggests starting with the "core library" first (see here for details: http://blog.zulip.org/2016/10/13/static-types-in-python-oh-mypy/#fullyannotatingalargecodebase). For certbot, this would probably mean starting with:
- `certbot/main.py`
- `certbot/configuration.py` (because `config`, which is an instance of `NamespaceConfig`, is passed around everywhere) 

Also, the blog post suggests standardizing how you're running mypy and sharing that information, as that will allow multiple people to work on this more smoothly!

**Comment by dokazaki** [comment]
I'll start working on this.

**Comment by toolness** [comment]
Oh, apparently some foundation was actually laid out for this in #4386, but when I run `tox -e mypy` on my system, I get tons of errors. Hmmmm.

**Comment by bmw** [comment]
Glad you're interested in working on this! We're excited about getting mypy type annotations added to Certbot.

None of the core Certbot team has done much experimentation with mypy yet, however, dokazaki tried to work on this at another Python sprint and hit some issues. Basically, the problem is our continued support of Python 2.6. Certbot currently is supporting this old version of Python due to old Red Hat Enterprise Linux systems. Issue #2208 aims to remove our Python 2.6 support while still supporting old Red Hat systems, but there's some nontrivial engineering work to be done to make that happen.

mypy does not support Python 2.6. At the bare minimum, the `typing` module cannot be used. No one has done much additional probing to determine what other problems there are with using mypy on Python 2.6 (if there are any). If you'd still like to work on this knowing this hurdle, you have at least a few options:

1. Don't use `typing` at all. My understanding is this makes it next to impossible to provide meaningful type annotations.
2. When importing `typing`, put a `try` and `except` around each import.
3. Ignore problems with Python 2.6 and work on this in a separate branch. If you take this approach, tests on Travis will fail and we probably won't be able to merge the work into `master` for a few weeks, but it'll allow you to ignore the hurdles that should be going away soon.

Alternatively, maybe you have an even better idea!

**Comment by dokazaki** [comment]
Actually, I've been experimenting on the side on my current fork and believe I have the correct solution. It's on the typehint-acme branch on my fork. Since mypy must be executed under Python 3, and since we're using the comment style annotations, then the solution is to add the following to the top of modules being type-hinted:

MYPY = False
if MYPY:
    from typing import List, Any, <etc....>  # pylint: disable=unused-import
    from functools import partial  

When mypy executes, it will override the MYPY = False and execute the import statements guarded by it. However this will not impact the code builds even under Python 2.6. Just need to remember to add the pylint override on the protected imports so it doesn't flag these imports as errors.

Also in the case where the type-hinted code has a pylint override, the type-hint comment comes first.  You can look at my fork for examples.

**Comment by toolness** [comment]
Yep, that works!  You can actually even do `if False:` (this was actually recommended by guido in one of the GitHub mypy issues).

That said, I also have another strategy with regards to all the `type: ignore`s: rather than attempting to run mypy across the entire codebase, it might be more effective to run it only on certain files at first, so that you can incrementally bring strong typing to the whole project. This actually means you can *remove* the `type: ignore`s rather than continually add more, and it also means that you can run mypy on your whitelist of files during CI.

This is actually what I started doing yesterday, until I realized that mypy was already added in #4386. Let me know if you think we should use this strategy instead, or if you'd rather keep using your current one.

**Comment by bmw** [comment]
If mypy is added to CI, I think it makes the most sense to only run it on a subset of our files. I'd rather not slow down contributors by making them add `type: ignore` to work around mypy's limitations.

If it's not added to CI, I think you can take whatever approach you think is easier.

**Comment by dokazaki** [comment]
mypy is already in the tox config, so it runs on files that are type-hinted and skips those that aren't.
I would suggest using MYPY = False to make it clear what the imports are being guarded against. In the  mypy docs (in Common Issues) Jukka explains its usage (for a slightly different issue) as: "...define a constant named MYPY that has the value False at runtime. Mypy considers it to be True when type checking."

**Comment by toolness** [comment]
Oh cool, I didn't realize that `MYPY = True` was the documented/recommended way to do things. And you're right, it is more readable than `if False`. I'll use that, then!

How does the tox config determine whether a file is type-hinted or not? From my reading, and from looking at the code for #4386, it seems as though it's just looking at *all* files, and the only type annotations seem to be a handful of `dict`s (the key/value typings of which aren't defined) and the rest are `type: ignore`s...

**Comment by dokazaki** [comment]
The tox config for mypy is pretty much brute-force like the config for lint and just command-line executes mypy on the same directories that are linted. So it type checks all the python packages and files it finds under those directories.
After setting up the rule, there were only a handful of files that failed type hint checking as-is, so I added the type: ignore... and minimal type-hints just to tide them over until someone determined and applied the correct type-hints.

**Comment by StefanoChiodino** [comment]
@ohemorange that instagram package only works with python 3 hints. Is support for python 2 being dropped?

**Comment by ohemorange** [comment]
Yes stalebot, we're finally scheduling to get this finished!
