### ISSUE TITLE
Add an option to unsubscribe from renewal notices for one certificate and add a re-subscribe option

### ISSUE THREAD

**Issue by multiwebinc** [certbot/certbot#4270]
I was previously getting some expiration notice emails, like:

> Hello,
> 
> Your certificate (or certificates) for the names listed below will expire in 19 days (on 29 Feb 16 22:12 +0000). Please make sure to renew your certificate before then, or visitors to your website will encounter errors.
> 
> example.com
> www.example.com
> 
> For any questions or support, please visit https://community.letsencrypt.org/. Unfortunately, we can't provide support by email.
> 
> If you are receiving this email in error, unsubscribe at http://mandrillapp.com/track/unsub.php?u=30850198&id=5a003f028561442[...]. (HTTP link, we know. We're working on it!)
> 
> Regards,
> The Let's Encrypt Team

I had issued multiple certs for the same domain and I wanted to let this particular certificate expire, so I clicked on the unsubscribe link. However I didn't realize that it would unsubscribe that email for all certificates I issued using that email address.

I suggest:

1) Add an additional link in the email to unsubscribe from notifications ONLY for that certificate (e.g. when you want to let it just expire and don't want to be notified every few days).
2) Allow users to re-subscribe if the link was accidentally clicked on.

**Comment by cpu** [comment]
Hi there @multiwebinc :wave:,

> I had issued multiple certs for the same domain and I wanted to let this particular certificate expire, so I clicked on the unsubscribe link. However I didn't realize that it would unsubscribe that email for all certificates I issued using that email address.

Oops! I'm sorry to hear that. I know even with the warning message it can be easy to do accidentally. 

Your two suggestions are both good ones but the expiration emails are generated by [Boulder](), the server-side CA for Let's Encrypt that Certbot and other ACME clients talk to. I'm going to mark this issue closed because of that.

I'd like to save you a bit of running around so I'll also provide more context here. Boulder uses [Mandrill](http://mandrill.com/) to send the actual expiration emails to users (running our own email service for the volume we need to send is way too hard for a team of our size). Unfortunately this means that improving the service with additional features like per-certificate unsubscribe and a better subscription management interface is significant work since it isn't present out-of-box (we would need to write quite a bit of additional code on top of their API). It's not impossible but it's a big job and we have a lot of service-impacting work to get through first.

> Allow users to re-subscribe if the link was accidentally clicked on.

Totally agree that this is needed & we have issue https://github.com/letsencrypt/boulder/issues/1396 filed on Boulder for this one already.

> Add an additional link in the email to unsubscribe from notifications ONLY for that certificate (e.g. when you want to let it just expire and don't want to be notified every few days).

We have  https://github.com/letsencrypt/boulder/issues/2475 filed on the Boulder repo for this feature request.

In the short-term one work-around I can suggest for resubscribing is to use Certbot to update your account's email address to a new one that hasn't been unsubscribed. If you use Gmail it might be as easy as adding `+letsencrypt@gmail.com` to the email you already unsubscribed.

Thanks for filing the issue!
