### ISSUE TITLE
Feature request: Allow to use certbot with fake / dummy certificates in order to test installer plugin

### ISSUE THREAD

**Issue by e00E** [certbot/certbot#4298]
I am developing an installer plugin for certbot which I would like to test by running it with certbot. However I do not have a domain or public web server so I cannot get a real certificate nor do I want to as I am just trying to test this plugin and actual certificate authentication is unnecessary overhead for this task.
It would be helpful if certbot had a kind of developer mode that acts like it had real certificates for whatever domain which could then be used to invoke the installer plugin.

Apologies if this mode does exist already. I did not find such a thing in the documentation.

**Comment by cpu** [comment]
Hi @e00E,

One idea for acheiving this is to run Boulder (the server-side component of Let's Encrypt that Certbot talks to) locally. Take a look at [the Quickstart guide](https://github.com/letsencrypt/boulder#quickstart) as a starting point. The `FAKE_DNS` setting mentioned will let Boulder run in such a way that it will generate test certificates for any domain.

You can tell Certbot to talk to your local Boulder instance instead of the real thing by using `--server http://localhost:4000/directory`.

Hope that helps! If you run into any trouble please feel free to [open an issue on Boulder](https://github.com/letsencrypt/boulder/issues/new) and we can help troubleshoot there.

**Comment by bmw** [comment]
There's currently no feature like this, however, there aren't any checks on the validity of the cert and key. You can use a self-signed cert, a cert for a different domain, etc. For example, if you install the `ssl-cert` package on Debian systems, you could use `/etc/ssl/certs/ssl-cert-snakeoil.pem` and `/etc/ssl/private/ssl-cert-snakeoil.key`.

Because of this, I'm not sure how beneficial this feature would be and I'm closing this issue for now. If you disagree and think this would really help your development process, please explain why these suggestions don't work for you and I'll consider reopening.

**Comment by m-emelchenkov** [comment]
I 'd like to re-open this feature request. I use Vagrant + Ansible for web development and have two versions: dev (local VM) and production (VPS). dev version has custom domain name and does not have incoming open ports, and also custom domain name for local dev differs from real name, but underlying VMs directory structure, including certs paths, is identical to a production environment.

It's important to debug the whole process on local VM before publishing it on production but it's hard to make it without ability to generate 'dummy' certs.

I use the next code:
```
- name: Obtain certificate
  shell: certbot -n certonly --webroot -w /var/www/{{ domain }}/public -d {{ domain }} -d www.{{ domain }}
```

I'd like to have option "--dummy" which will tell certbot to generate dummy certs for any domains, but these certs will be self-signed, so no any incoming connection and domain name verification will be required.

**Comment by pde** [comment]
We would consider a patch from the community that effectively shims out the remote calls to the ACME server and instead creates a locally-produced test cert, for testing installer plugins, renew/deployment hooks, etc. @m-emelchenkov @e00E would either of you be interested in writing that patch?

**Comment by m-emelchenkov** [comment]
@pde Unfortunately, not. SSL automation is a small part of my R&D activities so I just tested it manually for two servers and wrote Ansible recipes which already works for me. I think, it is a high demand feature for those companies who converting existing SSL infrastructure to LetsEncrypt (like me but who have large volumes of servers), and, probably, they will be ready to implement it. I wish you will find developers for this feature, because, I believe, it will be a huge improvement to an overall usability. Anyway, even without this feature it is a nice product, thank you!

**Comment by e00E** [comment]
@pde No, at least not at the moment.

**Comment by codeclown** [comment]
This would be very helpful for automated testing. Correct me if I'm wrong, but `--dry-run` still requires a domain pointing to the webserver in order to achieve certs. So you can only test failing attempts with it, unless your automated testing enables domains for test servers.

Running Boulder manually would be an option. Currently it seems a bit heavy to run it, because it doesn't have a single docker image encompassing all the components. Ideally in test environment one could `docker run boulder` and use that instance for certbot server.

I would like to see two new options for certbot: `--fake-success` and `--fake-failure`. Accompanying environment variables would be also nice (so environment can decide per test, not in code).

**Comment by cpu** [comment]
> Running Boulder manually would be an option. Currently it seems a bit heavy to run it, because it doesn't have a single docker image encompassing all the components. Ideally in test environment one could docker run boulder and use that instance for certbot server.

I think you'll find [Pebble](https://github.com/letsencrypt/pebble) works well for this. At the time I wrote my earlier comment recommending Boulder there was no ACME v2 or Pebble :-)

**Comment by codeclown** [comment]
@cpu Ah, indeed! So I'll use local Pebble for success testing and staging environment for failure testing. Should work.

It might be worth it to add a note about Pebble to the [Staging Environment](https://letsencrypt.org/docs/staging-environment/) page, because that's where people probably land when searching for LetsEncrypt testability.

**Comment by cpu** [comment]
> It might be worth it to add a note about Pebble to the Staging Environment page, because that's where people probably land when searching for LetsEncrypt testability.

@codeclown Thanks for the idea! :+1: https://github.com/letsencrypt/website/pull/859
