### ISSUE TITLE
Security concern: required use of folder name beginning with 0x2e: ".well-known"

### ISSUE THREAD

**Issue by drhsqlite** [certbot/certbot#4342]
## My operating system is (include version):
Ubuntu 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt-get install

## I ran this command and it produced this output:
letsencrypt certonly -webroot ....

## Certbot's behavior differed from what I expected because:
Certbot was unable to verify the domain because it creates new witness files under the ".well-known" directory in the web server file hierarchy.  But my webserver disallows URIs that start with a "." for security reasons.  I had to hack and recompile the webserver so that it makes a special-case exception for ".well-known".

It seems ironic to have to weaken the security of the webserver in order to obtain a cert, does it not?

I consider URLs that have leading "." elements in their path to be a security risk because it allows serving files that are not normally seen by an ordinary "ls" command on the server.  In other words, it allows the serving of "hidden" files.  By prohibiting hidden files, an operator error that leaves (for example) a ".git" folder somewhere in the web server hierarchy will not lead to an accidental security breach.

For similar reasons, the webserver I use also refuses to deliver files with other special characters.  It only delivers files whose names are composed entirely of [a-zA-Z0-9_,-./] and that do not begin with "-" or ".".

I'm not familiar with the ACME protocol, and so this might not be an easy thing to do, but I think it would be a great enhancement to allow certbot to create its witness files using only alphanumeric characters.  A name of 20 randomly chosen alphanumerics will not collide (with any realistic probability) with any preexisting files or folders on the webserver.  Why not use random name instead of ".well-known"?  Is that possible with the ACME protocol?  Could this at least be made a run-time option for certbot?

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

In case anyone is interested, the webserver mentioned above can be seen at https://www.sqlite.org/docsrc/file/misc/althttpd.c

**Comment by schoen** [comment]
Hi @drhsqlite,

The use of the string `.well-known` for this purpose is an Internet standard from RFC 5785, which was based on the goal of having one single prefix for URLs that have special meanings or convey meta-information on behalf of the web site operator.

https://tools.ietf.org/html/rfc5785

The uniqueness of that prefix provides benefits like allowing sysadmins to prevent unprivileged users from creating URLs that others will interpret specially. As the introduction says, it would have been best if some mechanism for this had been available in the past to prevent the proliferation of ad-hoc solutions.

Because of that standard, the draft ACME RFC has always explicitly required this particular prefix.

https://datatracker.ietf.org/doc/draft-ietf-acme-acme/

A random name isn't permitted by the protocol. (Although it wouldn't necessarily be too terrible for security, one concern is that someone who isn't the site administrator but is allowed to create arbitrarily-named files at the top level—which could conceivably happen on some kinds of wikis, pastebins, image boards, etc.—could then get a certificate for the site.)

**Comment by drhsqlite** [comment]
Thanks for the detailed explanation and the pointer to RFC 5785 (which I had never heard of before).  I have added appropriate comments to the /.well-known/ hack in the web server source code.  :-)
