### ISSUE TITLE
"certbot plugins" should not throw Permission denied

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#4350]
Steps to reproduce:

1. As non-root, run "certbot plugins"

Expected result:

Get a list of plugins.

Actual result:

```
The following error was encountered:
[Errno 13] Permission denied: '/var/log/letsencrypt/letsencrypt.log'
If running as non-root, set --config-dir, --work-dir, and --logs-dir to writeable paths.
```

**Comment by SwartzCr** [comment]
This sounds a lot like what we did with `certbot help` to allow it to run without venv-ing itself.
@ynasser Do you want to think about adding this to things people can work on at the sprint?

**Comment by SwartzCr** [comment]
Still no progress on this, but it seems like an easy fix, @bmw wanna put it in a milestone?

**Comment by SwartzCr** [comment]
similarly `certbot --version` should get the same treatment as per #4491

**Comment by bmw** [comment]
`certbot --version` should work without root.

**Comment by r5d** [comment]
@SwartzCr,

If I'm correctly understanding the issue, it looks like, the `plugins_cmd` must be called before the call to `make_or_verify_needed_dirs(config)` in `certbot.main.main` function. Where would be good place to do this?

**Comment by bmw** [comment]
@SwartzCr asked me to respond to this.

@r5d, the problematic functions are `certbot.main.make_or_verify_needed_dirs` (as you correctly pointed out) and `certbot.log.post_arg_parse_setup`.

As for how to accomplish this, it might be simplest to just do something like:
```
try:
    log.post_arg_parse_setup(config)
    make_or_verify_needed_dirs(config)
except errors.Error:
    if config.func != plugins_cmd:
        raise
```
While this feels a little hacky, the "plugins" subcommand is the exception here so moving this code into the other individual subcommands seems like a recipe for bugs when new subcommands are added in the future. Additionally, I think we should always try to run this code because when it's not run successfully, logs are written to a temporary file instead of the normal log directory. We should try to run it for the times when we do have the necessary permissions.

I'm open to other ideas if you have them though.

**Comment by r5d** [comment]
@bmw, I've submitted a PR. It uses your idea.

**Comment by bmw** [comment]
Fixed in #5103.

**Comment by SwartzCr** [comment]
Awesome job @r5d ! Any interest in working on another issue? Maybe #4879?

**Comment by jsha** [comment]
Nice, thanks for fixing this bug!

**Comment by r5d** [comment]
@SwartzCr, I'll look into #4879.
