### ISSUE TITLE
why generating certification required domain with SSL connection using port 443?

### ISSUE THREAD

**Issue by kim0z** [certbot/certbot#4359]
executing command:   
letsencrypt-auto certonly --standalone -d myDomain

expected:  
To have PEM file

Actual:  
Failed to connect to xx.xx.xx.xxx:443 for TLS-SNI-01 challenge  

My question is why the domain must have this TLS challenge while all what I am asking for is to generate certification to be able to convert my server from HTTP to HTTPS?  

I thought it's obvious that how want to generate certification maybe have no TLS  #server, I will be happy to have an explain  

Thank you

**Comment by SwartzCr** [comment]
Hi @kim0z good question!
So the standalone plugin attempts to spin up a webserver to communicate with the Let's Encrypt Certificate Authority. If you would like to validate your domain another way you might rather choose the webroot validation - which will have you place a file on your already running http webserver, or the dns validation which will verify you via a TXT record in your DNS entry.
You can find out more about those options here: https://certbot.eff.org/docs/using.html#getting-certificates-and-choosing-plugins
Let me know if that helps! Otherwise I'm happy to answer more specific questions

**Comment by kim0z** [comment]
Thank you I will take a look

**Comment by SwartzCr** [comment]
cool - I'm going to close this issue, feel free to open a new one if you run into trouble with a different challenge
