### ISSUE TITLE
bash completion

### ISSUE THREAD

**Issue by Hainish** [certbot/certbot#441]
A nice-to-have: bash completion for the LE CLI

**Comment by pde** [comment]
I believe bash-completion is a Debian project.  We can send them a patch [here](https://bash-completion.alioth.debian.org/), but I suspect once we launch that they might quickly write their own.

**Comment by zjs** [comment]
Given the complexity of `certbot`'s options, their dynamic nature (e.g., due to dependence on the installed set of plugins), and the frequency with which they change, it may be easiest to package the completion logic with `certbot`, possibly by leveraging a [library that integrates with `argparse`](https://argcomplete.readthedocs.io/en/latest/).
