### ISSUE TITLE
Certbot JWSObject structure is different from the acme spec (specifically re: header/protected/nonce))

### ISSUE THREAD

**Issue by laran** [certbot/certbot#4417]
If I'm not mistaken, here's the line where certbot generates the signature that is used on the server to verify integrity of a JWSObject:
https://github.com/certbot/certbot/blob/8011fb2879659008528e8b6ba5c04ac3de1e63a0/acme/acme/jose/jws.py#L233

Certbot seems to deviate from the ACME spec in terms of the structure of the requests. In the spec the nonce is in the header and there is just the protected, payload and signature fields. The requests from certbot however have only the nonce in the protected field and have the header attributes separately, not Base64Url encoded, as just plain JSON.

I'm working with the JOSE implementation from nimbusds.

Here's the line where the signing input is created:
https://bitbucket.org/connect2id/nimbus-jose-jwt/src/a730749c3831e429617d0cb4203303b36edfc6f2/src/main/java/com/nimbusds/jose/JWSObject.java?at=master&fileviewer=file-view-default#JWSObject.java-204

Here's where that method is called:
https://bitbucket.org/connect2id/nimbus-jose-jwt/src/a730749c3831e429617d0cb4203303b36edfc6f2/src/main/java/com/nimbusds/jose/JWSObject.java?at=master&fileviewer=file-view-default#JWSObject.java-165

This line of code is invoked just a few lines above that call:
https://bitbucket.org/connect2id/nimbus-jose-jwt/src/a730749c3831e429617d0cb4203303b36edfc6f2/src/main/java/com/nimbusds/jose/JWSObject.java?at=master&fileviewer=file-view-default#JWSObject.java-151

The JWSHeader.parse() method that's called validates that the header contains an "alg" attribute:
https://bitbucket.org/connect2id/nimbus-jose-jwt/src/a730749c3831e429617d0cb4203303b36edfc6f2/src/main/java/com/nimbusds/jose/JWSHeader.java?at=master&fileviewer=file-view-default#JWSHeader.java-631

Putting the pieces together:
- certbot generates a signature based on a protected field with only a nonce (no alg or other information)
- nimbus-jose-jwt checks the signature based on the header, which must contain the alg.
- based on the ACME spec (https://tools.ietf.org/html/draft-ietf-acme-acme-04#section-5.2), the protected field should contain all of the information that certbot puts in the header AND the nonce 

The net result is that verification doesn't work properly without some contortions on the server side.

I hope this all makes sense. Are there plans to bring certbot in line with the acme spec?

**Comment by laran** [comment]
I see that this was called out in a recent version of the acme-divergences document:
https://github.com/letsencrypt/boulder/commit/db3a6d650774228515b6b0d869b442f9409661c7#diff-3d6d8baf462b78681424da8ce68634d9

**Comment by pde** [comment]
@jsha do you want to decide how urgent this is, and assign it to 0.15.0, 1.0 or Wishlist accordingly?

**Comment by jsha** [comment]
Yep, we should fix this. In short, JWS offers an unprotected header ("header") and a protected header ("protected"). Boulder originally allowed JWK to be in the unprotected header, because tampering with the JWK would just result in a failure to validate. However, we later decided it was silly to allow anything in the unprotected header. I think it's worth moving jwk to the protected header, and should make @laran's implementation easier.

**Comment by laran** [comment]
I really appreciate your attention to this. Things like this make a big difference, making it much easier to interoperate. Thank you.

**Comment by mslone** [comment]
I appreciate this fix as it's bringing certbot in line with the ACME spec, but it's worth noting: because of this change release 0.15.0 broke compatibility with our ACME server (our server had been set up handling the jwk and alg fields in the unprotected header). Easy fix, but updated certbot clients were incompatible with our server in the meantime.

**Comment by cpu** [comment]
@mslone Are there any details available publicly about your ACME server? Can you name the organization you're affiliated with? The circle of folks implementing ACME on the server-side is quite small and I'm always interested in building relationships within that circle so that we can better coordinate. If you'd prefer to share in private my email is my github username followed by `@letsencrypt.org`. Thanks!

**Comment by mslone** [comment]
@cpu I'm one of the developers at Entrust Datacard. We have an ACME service that’s tested for interoperability with Certbot (and available to all customers who have an SSL account with us).

**Comment by cpu** [comment]
@mslone Aha! Thanks. Is your intention to only support the Certbot ACME client? Have you started to plan for adopting a finalized ACME RFC (In Boulder we're calling this ["ACME v2"](https://letsencrypt.org/2017/06/14/acme-v2-api.html))?  (Maybe this is a better conversation for email?)
