### ISSUE TITLE
Stupidly deleted import folders and now certbot can't find configuration.

### ISSUE THREAD

**Issue by brendanw36** [certbot/certbot#4454]
## My operating system is (include version):
Raspbian 8

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
./certbot-auto

Error while running apache2ctl configtest.
Action 'configtest' failed.
The Apache error log may have more information.

apache2: Syntax error on line 219 of /etc/apache2/apache2.conf: Syntax error on line 32 of /etc/apache2/sites-enabled/000-default-le-ssl.conf: Could not open configuration file /etc/letsencrypt/options-ssl-apache.conf: No such file or directory

## Certbot's behavior differed from what I expected because:
What I was I was hoping to have happen is for it to ask me my domain name, but it just gave errors. was switching domains and instead of running certbot-auto delete I deleted folders for certbot.  I'm very new to this and I haven't even been operating a web server for more the two weeks.  What is the solution to this?  Fresh install of certbot?  How would I go about that?

**Comment by SwartzCr** [comment]
So it sounds like you deleted your /etc/letsencrypt directory, or some files in it. Apache2ctl is checking the validity of your apache config files, which are pointing at this file `/etc/letsencrypt/options-ssl-apache.conf` which no longer exists. Apache2ctl is understandably throwing an error, because if you tried to run apache it would throw an error.
One solution is to delete these apache files - you likely can't use their configurations (especially the one in `/sites-enabled/`) if you don't have the relevant certs for it. And if you're no longer administering the domain names in them then you don't need them anyway.
If you do this certbot should regenerate the 000-default-le-ssl.conf file when it fetches you a new certificate.
Altrenately you could try to manually edit these files and remove all instances of file paths that include `/etc/letsencrypt` - if you're feeling up to it.
If you re-installed certbot, unfortunately it wouldn't fix your problem.
For one thing the `certbot-auto` script essentially reinstalls itself on every run anyway, but even if it didn't these apache config file errors would persist and cause the newly installed certbot to fail again when it runs apache2ctl.
Hope that was helpful! Let me know if it fixes your problem!

**Comment by brendanw36** [comment]
Thanks!  This worked for me.  I saw that directory a while ago and was leaning toward deleting the whole thing.  Thanks for the info.
