### ISSUE TITLE
Failed authorization procedure. login.kristshell.net (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization

### ISSUE THREAD

**Issue by solbu** [certbot/certbot#4477]
We successfully enabled certificates using certbot in early february.
The last few days I noticed that the cronjob attempting to renew is failing.

cat /etc/cron.daily/certbot-auto-renew 
#!/bin/sh
exec /usr/bin/certbot renew --no-self-upgrade --quiet

Attached is the latest letsencrypt.log

[letsencrypt.txt](https://github.com/certbot/certbot/files/904169/letsencrypt.txt)

**Comment by solbu** [comment]
Oh, and we run Debian 8, and installed certbot via apt using the Debian backports repo.

**Comment by SwartzCr** [comment]
hmm, have you stopped hosting any of the domains listed on your cert? The error that it's giving is that it's not able to reach one of them.
Also if you could share your renewal conf file that'd help, it might be that the way it's trying to renew them is wrong - so I'd like to get a sense of the original command you used to generate the cert.

**Comment by solbu** [comment]
> have you stopped hosting any of the domains listed on your cert? 
> The error that it's giving is that it's not able to reach one of them.

No, that still puzzle me. When I attempted manual renewal, I check using 3 different servers, in 3 different counties, each using a differend dns server. The dns name worked. The page hosated there was live and well.

After several hours I finally got it working, by adding the webroot path to the certbot command "certbot renew --no-self-upgrade -a webroot --webroot-path=/var/www/html/"
I did not have to do that for the other 3 domain certs we use. Thet where renewd without problems.

Thanks to the magic of etckeeper (which maintain /etc in a local git repo) I was able to find the relevant renewal conf at the time of the failure:

> # renew_before_expiry = 30 days
> version = 0.9.3
> cert = /etc/letsencrypt/live/www.kristshell.net/cert.pem
> privkey = /etc/letsencrypt/live/www.kristshell.net/privkey.pem
> chain = /etc/letsencrypt/live/www.kristshell.net/chain.pem
> fullchain = /etc/letsencrypt/live/www.kristshell.net/fullchain.pem
>
> # Options used in the renewal process
> [renewalparams]
> authenticator = apache
> installer = apache
> account = <redacted>
 
After I added the webroot option, the authenticator option changed from apache to webroot, and these lines where added to the config:

> webroot_path = /var/www/html,
> [[webroot_map]]
> login.kristshell.net = /var/www/html
> webmail.kristshell.net = /var/www/html
> www.kristshell.net = /var/www/html
> cubemail.kristshell.net = /var/www/html
> ordbok.kristshell.net = /var/www/html
> squirrelmail.kristshell.net = /var/www/html
> sid.kristshell.net = /var/www/html
> erikandre.kristshell.net = /var/www/html

**Comment by SwartzCr** [comment]
Oh! That makes sense - you may have first registered them with apache, and now are no longer running apache so it can't find them in an apache config.
Sounds like you got it worked out though, so I'm going to close this ticket - Sorry for the issue!

**Comment by solbu** [comment]
How does that make sense? We still run apache, we ran apache when the update broke. The 3 other domains that we use certbot on works with the short config that doesn't work with the kristshell.net domain.

We do not run any other webserver than apache, so how does it make sense? I don't understand

**Comment by SwartzCr** [comment]
Oh sorry - I misunderstood you then. I had thought that you had switched away from apache & it was still trying to renew via apache. Let me re-open this.

**Comment by bmw** [comment]
We've seen this happen a few times over the last few months and can confirm that using `webroot` for authentication is a valid workaround. Sorry for the trouble though.

Do you by chance have multiple virtual hosts in a single file, especially the HTTP/HTTPS ones for the domains that Certbot is obtaining certificates for? While doing this is completely valid in Apache, Certbot doesn't properly support it right now. Unfortunately, previous versions of Certbot would often try to parse multiple vhosts in the same file, only sometimes doing so correctly. We've fixed this and Certbot currently ignores vhosts that it's not expected it can parse, but this change has caused the problems you're seeing for other users. We expect Certbot will have real support for this in the next release at the beginning of next month though and I can confirm that using `webroot` will fix the problem.

**Comment by solbu** [comment]
No, but we do use the vhost_alias module. We have a directory /var/hosts/ where we create symlink for hosts that we host for our users, to where the user put their website content. That way we don't have to create a config file for each domain. (We have done this for at least 10 years)

The config file (/etc/apache2/mods-available/vhost_alias.conf) is attached.
Note that since we started using certbot we have created a config file for each and every host/alias that we secure with TLS.
[vhost_alias.txt](https://github.com/certbot/certbot/files/923008/vhost_alias.txt)

**Comment by bmw** [comment]
Interesting. Looking through your log, the only domain that's failing authorization is `login.kristshell.net`. All other domains are succeeding.

What's going on when Certbot tries to authorize your domain using the Apache plugin is it creates a temporary virtual host that responds to a TLS request to your server for the host `<specific hash>.acme.invalid` with a specific self signed certificate. When it tries to do the challenge for `login.kristshell.net`, something goes wrong. In particular, the Let's Encrypt server gets back a certificate containing the domains `cubemail.kristshell.net, erikandre.kristshell.net, login.kristshell.net, ordbok.kristshell.net, sid.kristshell.net, squirrelmail.kristshell.net, webmail.kristshell.net, www.kristshell.net` rather than the self signed certificate. Presumably this is the certificate you're trying to renew.

When Certbot creates this temporary vhost, it tries to find the existing vhost that matches the domain it's trying to solve the challenge for and creates the temporary vhost using the same address and port values in the existing vhost. For `login.kristshell.net` it uses the address and port `*:443` while for all other domains it uses `91.205.184.98:443`. Is this correct? It chooses the vhost based on `ServerName`/`ServerAlias` directives, preferring the most specific match both in terms of the name/alias and server/port. Looking at your existing vhosts, is this `*:443` the correct choice? By creating the vhost this way (whose full contents are in your log), do you know why it conflicted with your existing vhost serving the domains I listed above?

Hopefully this information and questions helps to start to try and track down the problem.

As for having to create a config file for every host/alias that you secure, I'm unaware of another solution to the problem with Apache, however, I'm certainly open to suggestions.

**Comment by SwartzCr** [comment]
Hey @solbu are you still having issues?

**Comment by solbu** [comment]
We solved it by creating a config file (etc/apache2/conf-available/certbot.conf), where we added the following content:

> AliasMatch ^/.well-known/acme-challenge/(.*)$ /var/www/html/.well-known/acme-challenge/$1
> Alias /.well-known/acme-challenge/ /var/www/html/.well-known/acme-challenge/
> <Directory "/var/www/html/.well-known/acme-challenge/">
>     Options None
>     AllowOverride None
>     ForceType text/plain
>     RedirectMatch 404 "^(?!/\.well-known/acme-challenge/[\w-]{43}$)"
> </Directory>
>

**Comment by SwartzCr** [comment]
Okay - glad you got it fixed, sorry for the issue!
I'm going to close this issue, but feel free to open new ones if you run into any more problem!
