### ISSUE TITLE
certbot-auto stores configuration in /~/ directory when launched as systemd service

### ISSUE THREAD

**Issue by Talkless** [certbot/certbot#4489]
## My operating system is (include version):

Debian 8 amd64

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
```
# wget -q -O certbot-auto https://dl.eff.org/certbot-auto
# chmod a+x certbot-auto 
# mv certbot-auto /usr/local/bin/certbot
```

## I ran this command and it produced this output:

I create initial certificates like this:
```
certbot certonly --non-interactive --agree-tos --no-self-upgrade --email info@domain.com --apache -d my.domain.com
```
Certbot creates `/root/.local/share/letsencryt`file tree:
```
# tree -a /root/.local/ | head
/root/.local/
└── share
    └── letsencrypt
        ├── bin
        │   ├── activate
        │   ├── activate.csh
        │   ├── activate.fish
        │   ├── activate_this.py
        │   ├── certbot
        │   ├── easy_install
```

BUT, 

After declaring systemd unit file `/etc/systemd/system/certbot.service` (to be usde by `certbot.timer`) like this:
```
[Unit]
Description=Certbot

[Service]
Type=oneshot
ExecStart=/usr/local/bin/certbot --no-self-upgrade -q renew
PrivateTmp=true
```
And execute `systemctl start certbot.service` (or by setting up `certbot.timer`),  Certbot creates different configuration file tree in system root, in `~` directory:
```
# tree -a /~/ | head                                                                                                                                     
/~/
└── .local
    └── share
        └── letsencrypt
            ├── bin
            │   ├── activate
            │   ├── activate.csh
            │   ├── activate.fish
            │   ├── activate_this.py
            │   ├── certbot

```

## Certbot's behavior differed from what I expected because:

Certbot duplicates `.local/share/letsencrypt` in different path when executed as systemd service, compared to execution interactively in terminal. Seems like "~/" is not resolved when running as systemd service.

## Here is a Certbot log showing the issue (if available):
There is no relevant log entries.

**Comment by zjs** [comment]
What is the output of `systemctl --system show-environment` on your system?

**Comment by SwartzCr** [comment]
@bmw or @schoen would one of you like to take this on (and/or milestone it?)

**Comment by Talkless** [comment]
@zjs :
```
# systemctl --system show-environment
LANG=en_US.UTF-8
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**Comment by bmw** [comment]
I'll put it in the 0.14.0 milestone for now so we can determine the scope of the problem.

@Talkless, what's the output of `certbot --no-self-upgrade --version`?

**Comment by Talkless** [comment]
`0.13.0`

**Comment by bmw** [comment]
Reproduced this. This is due to the `HOME` environment variable not being defined so `~` isn't expanded. I'll write a PR that causes `HOME` to be set to `/root` if it's not defined.

To work around the problem in the meantime, you can use the Certbot packages in `jessie-backports` which should be preferred over `certbot-auto`. They usually offer a better experience and avoid problems like this. They even ship with a cronjob/systemd timer so this is already set up for you. You can find instructions for using these packages at https://certbot.eff.org/#debianjessie-other. If you need/want to continue to use `certbot-auto`, you can work around the problem by defining `HOME`, `XDG_DATA_HOME`, and/or `VENV_PATH` to control where Certbot is installed. You can do this by adding a line like:
```
Environment="HOME=/root"
```
under the `[Service]` section of your unit file.

**Comment by Talkless** [comment]
Yes, I am using certbot from jessie-backports. I just wanted to test this alternative setup :-) .
