### ISSUE TITLE
Rewrite argument parsing

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4493]
We currently use the largely unmaintained `configargparse` and a number of hacks like magic default values and reaching into the internals of `configargparse`/`argparse` to get the behavior we want. We should rewrite our argument parsing to use another library like `click` or `fire`.

cc @erikrose, @ohemorange

**Comment by erikrose** [comment]
I've had excellent experiences with click. See https://github.com/mozilla/dxr/blob/master/dxr/cli/__init__.py for the top-level entrypoint in DXR's click-based CLI. click is particularly good at subcommands.

**Comment by ohemorange** [comment]
I don't know anything about `click`, but my friend wrote `fire` so we could probably get good support. I'm all for cleaner code everywhere!

**Comment by erikrose** [comment]
Then we should probably make a pro/con list and see what pops out!

**Comment by anarcat** [comment]
i don't know if [click](http://click.pocoo.org/) will cover the use cases currently covered by configargparse. first, it doesn't support config files out of the box - that might be done by a third party module like [click_config_file](https://github.com/phha/click_config_file). that config file support doesn't support writing config files the way certbot currently does either.

then click is way more than a commandline parser - it's a whole TUI (text user interface) driver. it hijacks the main control flow of your program and makes testing ... different, for example. it supports progress bars and ANSI art and whatnot. it is *very* opiniated about how things should be and you might find it difficult to work with if you deviate from canon.

[fire](https://github.com/google/python-fire) is much simpler, but also has the limitation of not working with config files.

another option people often favor is [docopt](http://docopt.org/) which also doesn't support config files (let alone writing them) but there is some [sample code to parse config files](https://github.com/docopt/docopt/blob/master/examples/config_file_example.py) that is surprisingly clean.

there aren't that many options here - rewriting the commandline parser is a huge deal in certbot. argparse, while it's weird and complicated, is one of the best things we have right now. i wonder if the best approach might not be to fix the issues in configargparse instead of rewriting half of certbot. ;) and there's been some [action](https://github.com/bw2/ConfigArgParse/issues/133) on the issue of finding a new maintainer on that side, so I wouldn't give up on it already...

**Comment by bmw** [comment]
Thanks for the thoughts @anarcat! For what it's worth, we don't use configargparse for writing configuration files and instead use configobj.

**Comment by ronhanson** [comment]
If you are having issues with Configargparse, or new feature requests, feel free to fill bug reports and do PR. I will try my best to move the project forward and fix the existing bugs.

**Comment by anarcat** [comment]
@ronhanson there are many issues in certbot that are ultimately upstream issues in configargparse. for example, https://github.com/bw2/ConfigArgParse/issues/104 and https://github.com/certbot/certbot/issues/6049 are two issues here specific to the project...

**Comment by bmw** [comment]
If we ever get to this, it'll honestly probably be years from now, but I personally still think this should be done. Our current CLI parsing is very complex, relies on a bunch of hacky custom code, and has caused a number of issues for us (see some of the issues referencing this one for a few examples).

**Comment by ohemorange** [comment]
When we do this, we should keep in mind that `verbose` is a `count` argument, and therefore can be given with no arguments, or with a number in the `cli.ini` file. Then, we can deprecate the unlisted `verbose-level` argument.

**Comment by wgreenberg** [comment]
looking into this a bit, at first it seemed like `click` would be a great choice, but as mentioned earlier in this thread it's _very_ opinionated. for example, it requires strict separation of arguments between commands and subcommands, e.g. `certbot -d foo.com certonly` means `-d` belongs to the `certbot` command, and thus you wouldn't be able to do `certbot certonly -d foo.com`. there's workarounds for this (see https://github.com/pallets/click/issues/108), but nonetheless it'd be an annoying hack we'd have to pepper in everywhere.

`fire` looks like a convenient way to get a CLI up and running on a smaller project, but it doesn't look like it supports a lot of our use cases. for example, it doesn't seem to support multiple flags of the same type (`-d foo.com -d bar.org`), and it seems you can only set help text through docstrings.

i'll keep looking into the `click` hack and see if i can make it more palatable.

**Comment by bmw** [comment]
Ooo interesting. Thanks for doing that research! I'm very curious if any of these libraries help with our "default detection" stuff we've got going on.

Also, I think the Python CLI landscape has shifted a bit since this issue was initially created. Most of these are false leads, but I found https://python.libhunt.com/categories/181-command-line-application-development which lists all the libraries I think I've ever heard anyone talk about. In addition to `docopt` which was mentioned above, I've also heard good things about `typer` which is based on `click`.

**Comment by bmw** [comment]
Also also, I haven't looked into how hacky the workaround for click is, but in case you hadn't seen it already, I wanted to share that our support for arguments either on `certbot` or the subcommand is a hack on `argparse` too. See https://github.com/certbot/certbot/blob/8037321ad772ff1031cb1b599d81922c28e5b984/certbot/certbot/_internal/cli/helpful.py#L300-L322

**Comment by wgreenberg** [comment]
updating this: although i ended up getting click to be flexible enough to handle certbot's (shall we say) _freeform_ handling of CLI args, unfortunately `argparse` is built into some of our plugin interfaces, and so any migration away from it would almost certainly be a backwards compatibility-breaking change. since this feature would necessitate a major version change, i'll punt on it for now and instead focus on patching the existing argparse system to fix #9598
