### ISSUE TITLE
How come sphinx thinks asterisks are links?

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4498]
I made #4497 to fix [this](https://travis-ci.org/certbot/website/builds/221423692#L1275) but I don't understand why sphinx was interpreting things that way. I'm more worried about just getting the website repo fixed for now, but we should look into this.

**Comment by schoen** [comment]
(Renamed for rhyme)

**Comment by erikrose** [comment]
Because * and ** are what reStructuredText uses for italics and boldness. The usual is to do something like this, which also has the advantage of formatting the code in monospace:

```
"""Context manager for running code that must be cleaned up on failure.
The context manager allows you to register functions that will be called
when an exception (excluding SystemExit) or signal is encountered. Usage::

    handler = ErrorHandler(cleanup1_func, *cleanup1_args, **cleanup1_kwargs)
    handler.register(cleanup2_func, *cleanup2_args, **cleanup2_kwargs)

with handler::

    do_something()

Or for one cleanup function::

    with ErrorHandler(func, args, kwargs):
        do_something()

If an...
"""
```

Note the double colons, which render the following indented paragraph in monospace. If you want inline monospace, that's done by surrounding text with double backticks.

**Comment by bmw** [comment]
Makes sense! Closing now that the mystery is solved.
