### ISSUE TITLE
Finalize Python 3 support

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4507]
We should be Python 3 compatible now! Before the next release though, we should:

- [ ] Spend some time playing with it to see if we can find a corner case where it breaks. If so, it should be added to our integration tests.
- [x] Make `tools/venv3.sh` install Certbot and it's official plugins (fixed in #4532)
- [ ] Modify the relevant `setup.py` files listing support for Python 3.
- [ ] Update system requirements in `docs/install.rst` to mention support for Python 3 versions.

**Comment by ahaw021** [comment]
Hi @bmw 

Awesome

how do we help out with testing?

Andrei

**Comment by yan12125** [comment]
@ahaw021 A good way is packaging certbot for Python 3 and using it. Apparently you're already doing that :) https://github.com/ahaw021/CERTBOT-WINDOWS-BUILD

Here I'd like to advertise my packages, too. For Arch Linux users, python-certbot-git, python-certbot-apache-git and python-certbot-nginx-git on AUR can be used for testing. Note that I patch setup.py in python-certbot-apache-git so that it accepts python-augeas 1.x.

**Comment by cclauss** [comment]
TODO: Add `'Programming Language :: Python :: 3'` to setup.py.

**Comment by yan12125** [comment]
I have a question: I guess https://certbot.eff.org/docs/install.html#system-requirements should be updated, too? Currently it reads:

> Certbot currently requires Python 2.6 or 2.7

**Comment by bmw** [comment]
Nice catch! I added updating `docs/install.rst` to my original post.
