### ISSUE TITLE
Check when we check python dependencies

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#4529]
Make sure that if a python dep we need isn't available, that we crash immediately rather than later in execution

**Comment by bmw** [comment]
So my current plan here is to implement #4521 which will tell the user to handle non-Python dependencies themselves and then run `certbot-auto --no-bootstrap` which will create the virtual environment and `pip install` OS dependencies in the same way we do for all other systems in `certbot-auto`. With this in mind, I'm not sure this is a concern because:

1. We're not changing anything that should affect the current behavior of installing/checking Python dependencies.
2. For there to be a problem, we need both `pip` to silently fail when the requested packages cannot be not installed and `setuptools` to not error out about the problem.

With this in mind, I personally don't think there's an issue here so I'm closing this, but feel free to reopen/comment with more info if you disagree.

cc @joohoi
