### ISSUE TITLE
Can we get a certificate with our Node.js server?

### ISSUE THREAD

**Issue by exebook** [certbot/certbot#4541]
## My operating system is (include version):
AWS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
```
git clone
certbot-auto certonly
```
We need update certificate automatically from cron, but we cannot stop our production server (Node.js + Express.js), can we configure "webroot" thing with express routing?

**Comment by SwartzCr** [comment]
You have a number of options for challenges. If your node express server can serve directories to the public internet then it should be easy to set up webroot. Here's more information on the webroot challenge: https://certbot.eff.org/docs/using.html#webroot
Otherwise, if you're using a DNS provider with a simple API you can use the new DNS challenge, as documented here: https://certbot.eff.org/docs/using.html?highlight=dns#manual

**Comment by SwartzCr** [comment]
I'm going to close this issue, but feel free to re-open if neither of those work for you!

**Comment by schoen** [comment]
I would also suggest asking questions like this on the Community Forum at https://community.letsencrypt.org/, because it's better-positioned to give advice about how to accomplish something (when there's no associated bug in Certbot requiring changes to Certbot's code).
