### ISSUE TITLE
Use environment markers for conditional dependencies?

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4553]
This problem will go away (for now) by solving #2208, but the way we've currently been handling conditional dependencies is by dynamically setting `install_requires` in `setup.py`. This causes our wheels to be built incorrectly, however, which while it doesn't negatively affect OS or `certbot-auto` packaging, it might be nice to get this right.

If we do this we should get a new enough version of `setuptools` available in `pipstrap` and verify with our Debian, EPEL, and Ubuntu maintainers that this won't cause issues for them.

**Comment by erikrose** [comment]
It looks like pipstrap's setuptools (29.0.1 as of this writing) is new enough to understand env markers, though we may have to specify them in setup.cfg rather than setup.py. (There's a lot of confusing noise in the [setuptools changelog](https://github.com/pypa/setuptools/blob/master/CHANGES.rst) about this, so it merits testing.)

**Comment by bmw** [comment]
We don't have conditional dependencies anymore!
