### ISSUE TITLE
Cannot expand domains list for certificate

### ISSUE THREAD

**Issue by alexzaitsev** [certbot/certbot#4615]
## My operating system is (include version):
Linux 4.4.0-75-generic #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
./certbot-auto certonly --standalone --email myemail --expand -d softcraft.co,www.softcraft.co,hampi.softcraft.co,beta.softcraft.co,blog.softcraft.co 

Firstly, I had this output:
```
Killed
Error: couldn't get currently installed version for /home/second/.local/share/letsencrypt/bin/letsencrypt: 
Killed
```
Then I did `cd $HOME/.local/share && rm -fr letsencrypt`  
After that the same command produces next output:
```
Bootstrapping dependencies for Debian-based OSes... (you can skip this with --no-bootstrap)
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Hit:2 http://mirrors.digitalocean.com/ubuntu xenial InRelease
Get:3 http://mirrors.digitalocean.com/ubuntu xenial-updates InRelease [102 kB]
Get:4 http://mirrors.digitalocean.com/ubuntu xenial-backports InRelease [102 kB]  
Hit:5 https://deb.nodesource.com/node_6.x xenial InRelease   
Get:6 http://mirrors.digitalocean.com/ubuntu xenial-updates/main amd64 Packages [527 kB]
Killedg package lists... 62%                                                                        
apt-get update hit problems but continuing anyway...
Killed
No LSB modules are available.
No LSB modules are available.
No libaugeas0 version is available that's new enough to run the
Certbot apache plugin...
Killedg package lists... 86%
```

## Certbot's behavior differed from what I expected because:
I would like to add new subdomain (blog.softcraft.co) to my sertificate and instead nothing happened.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

**Comment by SwartzCr** [comment]
It looks like previously you installed the letsencrypt package that is packaged for ubuntu. I'd suggest apt-get removing it. Additionally there's a new version packaged for xenial in a PPA. You can find instructions on how to install it here: https://certbot.eff.org/#ubuntuxenial-apache
So I'd apt-get remove letsencrypt
Then add this PPA, install it, and run certbot from that new package.
All of your certs will be unaffected by the reinstallation and all of your renewal configuration files will stick around (since that all lives in /etc/letsencrypt which isn't managed by apt)
Let me know if this works for you!
