### ISSUE TITLE
NGINX option need a plug-and-play solution for Weak-DH bug

### ISSUE THREAD

**Issue by ppKrauss** [certbot/certbot#4753]
See all details at [this letsencrypt.org discussion](https://community.letsencrypt.org/t/certbot-on-nginx-not-working-no-plug-and-play-solution/33895/6).

PROBLEM: the default ([see ubuntuxenial-nginx recommendation](https://certbot.eff.org/#ubuntuxenial-nginx)) of the most popular Linux is not working, because generates a  [Weak-DH "bug"](https://weakdh.org/).

WORKAROUND: a terminal sequence of commands... not is a real solution.

SOLUTION: the `certbot --nginx`  command must detect the problem (eg. by checking `/etc/nginx/ssl/` folder existence)  and run internally the "workaround instructions".

**Comment by ohemorange** [comment]
Planning to work on this for 0.16.0. Thanks for finding this!

**Comment by ohemorange** [comment]
Related: github.com/certbot/certbot/issues/374

**Comment by ohemorange** [comment]
Summarizing my understanding based on previous discussions:

- We're getting a bad grade because Nginx is willing to do 1024-bit DHE with 2048-bit RSA keys
- There's no problem using shared params with 2048-bit keys
- We should pre-generate and ship shared params, then set `ssl_dhparam` to a file containing the results of a precomputed param generation, which is done by executing `openssl dhparam -out dhparams.pem 2048`

**Comment by ohemorange** [comment]
Updates from meeting:

- Watch out for Java maybe not able to connect (logjam)
- See RFC: https://tools.ietf.org/html/rfc7919

**Comment by ohemorange** [comment]
See https://wiki.mozilla.org/Security/Server_Side_TLS#ffdhe3072

**Comment by ohemorange** [comment]
Some notes:

- `ssl_dhparam` takes a file as a parameter
- The location of this file is either distribution-dependent or flag-dependent, and either way we can't know it until runtime.
- The directive, and the therefore the location of the file, should ideally go into `options-ssl-nginx.conf`.
- Ergo, the contents of `options-ssl-nginx.conf` are only knowable at runtime.
- We therefore cannot, pre-distribution, compute the hash of `options-ssl-nginx.conf`.
- We cannot distribute the hash of the file we would have written in a previous version, because we can only compute that at runtime

So either:
- We need a new mechanism for pushing updates to `options-ssl-nginx.conf`, or
- The `ssl_dhparam` doesn't go into `options-ssl-nginx.conf`

**Comment by ohemorange** [comment]
I will think about this more. In the meantime, @bmw, any strong opinions?

**Comment by bmw** [comment]
I think the points from the meeting are important. If this change will break compatibility with Java clients that we previously configured Nginx to work with, we should think carefully about what we should do here. Also, I think unless we have a very good reason to do so, we should use one of the predefined groups rather than creating our own.

> The location of this file is either distribution-dependent or flag-dependent, and either way we can't know it until runtime.

Can you elaborate a little more on this? If `ssl_dhparam` takes a file path, why can't we define this path ahead of time and put it in `/etc/letsencrypt` or something?

**Comment by ohemorange** [comment]
> Also, I think unless we have a very good reason to do so, we should use one of the predefined groups rather than creating our own.

Yup, this is what https://github.com/certbot/certbot/issues/4753#issuecomment-315477556 means.

> If `ssl_dhparam` takes a file path, why can't we define this path ahead of time and put it in /etc/letsencrypt or something?

Because we don't know beforehand (that is, before we ship Certbot) the absolute path of where the file will be. `/etc/letsencrypt` might be a different directory.

**Comment by ohemorange** [comment]
On the Java problem:

- https://github.com/mozilla/server-side-tls/issues/107

**Comment by bmw** [comment]
> Because we don't know beforehand (that is, before we ship Certbot) the absolute path of where the file will be. /etc/letsencrypt might be a different directory.

Ah OK. We probably want the file referenced by `ssl_dhparam` to be in our config directory so we can update it later as necessary. We can put the `ssl_dhparam` directive itself either directly in the user's config or have a file whose hash we don't worry about in Certbot's config directory containing that value. Another potential option to look into is to use indirection and store the path to the file in variable.

There's also [this](https://wiki.mozilla.org/Security/Server_Side_TLS#DHE_and_Java) if you haven't seen it. Looking at the current list of ciphersuites, we do prioritize ECDHE so I believe the only problem is Java 6. This is *probably* fine, but we should do some more research to make sure.

It might be good to get @schoen to weigh in on this as he [thought a lot about this kind of thing](https://certbot.eff.org/docs/ciphers.html) a while ago.

**Comment by schoen** [comment]
The Mozilla wiki page you linked to reflects my current understanding, which is probably partly derived from that page and partly from talking with DKG. It seems like we have to make a policy choice about Java 6 compatibility (including the possibility of enabling non-PFS RSA ciphersuites that are compatible with Java 6... which might not be quite as awful if I can move forward with the idea of erasing old private keys after renewals).

**Comment by ohemorange** [comment]
https://plumbr.eu/blog/java/java-version-and-vendor-data-analyzed-2017-edition
4.82% of Java is Java 6 as of May 3. "Number of Java 6 deployments keeps shrinking 2x each year for the fifth year in a row" Looks like these numbers are specifically for client-side JVMs.

**Comment by ohemorange** [comment]
Doesn't look like they ever added support for 3072.

The RFC recommends 3072, but doesn't disrecommend 2048. So we could use 2048 and at least allow Java clients that are getting the SE updates.

**Comment by ohemorange** [comment]
So far it's not looking good for "can we conscionably automatically cause people's Nginx servers to stop accepting Java clients".

**Comment by ohemorange** [comment]
Update: since we already follow "intermediate" compatibility, we can probably also just go ahead and do this.

Additionally, we should probably stick the directive inline, but place the dhparams file under the same hash-based version control as the ssl options file.

**Comment by ageis** [comment]
I typically generate 4096-bit ssl_dhparam (no matter how long that takes) as part of some Ansible automation on most servers I maintain.
