### ISSUE TITLE
certbot-auto and DNS plugins

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4767]
The purpose of this issue is to open a conversation about packaging Zach's DNS plugins in `certbot-auto`.

While not a perfect recreation, I tried to get an estimate of the increased download and installation size of adding the Python 2.6 compatible DNS plugins to `certbot-auto`. The way I did this isn't perfect, but the estimates should be pretty close. I wanted to keep this post somewhat brief, but I'm happy to provide how I got these estimates if people are curious. These numbers do not include the size of OS dependencies.

### Download size
Base: 6932 KB
Cloudflare additional: 1120 KB (16.2% increase)
Digital Ocean additional: 28 KB (0.4% increase)
Google additional: 592 KB (8.5% increase)
Route53 additional: 4412 KB additional (63.6% increase)

### Installation size
Base: 37256 KB
Cloudflare additional: 5508 KB (14.8% increase)
Digital Ocean additional: 368 KB (1.0% increase)
Google additional: 4228 KB (11.3% increase)
Route53 additional: 34376 KB (92.3% increase)

### My thoughts

Boto3 (as required by route53) is absolutely massive. Given its size and the wide variety machines `certbot-auto` is run on, I'd prefer not to include it by default. With that said, I expect it'll be one of our most popular DNS plugins and people need a way to install it.

We had a long term design meeting for Certbot earlier this week and solving the problem of how to install additional plugins not included by default in our different installation methods was brought up. Unfortunately, us investing time to solve this was fairly contentious and an executive decision was made that we'd only solve this problem in the next year if we finished everything else on our plate.

With this in mind, I'm leaning towards just including everything. For the vast majority of `certbot-auto` users, the increased size doesn't matter so weighing the cost and benefits of doing this, I think it's worth it.

I'm curious what other people think though.

EDIT: By the way, at our last weekly meeting some people thought `certbot-auto` no longer deletes its virtual environment when it upgrades allowing users to work around the issues discussed in #4037. Unfortunately, this [not the case](https://github.com/certbot/certbot/blob/ee70799c62e9bf52b7077da29d9031f38f32beac/letsencrypt-auto-source/letsencrypt-auto#L677).

**Comment by zjs** [comment]
To throw out some random unbaked/off-the-cuff ideas/thoughts:
- Given that there are widely different use cases for `certbot-auto`, maybe a one-size-fits all approach isn't the best. Perhaps users could somehow customize the `certbot-auto` they download. (E.g., through a download-time selection process, like [jQuery](https://jqueryui.com/download/) has.)
- Instead of guessing about which plugins are worth packing in `certbot-auto`, perhaps we could make data-driven decisions. We could package each so that it can be downloaded and used (somehow) and keep track of downloads or active lineages or some similar metric and add plugins to `certbot-auto` based on some objective criteria.
- What do we do about the DNS plugins we currently can't ship by default (e.g., because they don't support Python 2.6)? There are three such plugins in the tree now, PRs out for three more, and another 10 or so that would be easy to implement. (The specifics of that might be best discussed in #1279, but I mention it here in part because having a good installation process may influence our decision on what to include by default.)
- What happens to people who using `certbot-auto` on a machine with very limited disk space when we double (or more) the disk space required? (It seems like `certbot-auto` could fill someone's drive, which would be... bad.)
- Could there be a `certbot-auto` with the set of plugins that it includes today and `certbot-auto-extras` (or whatever) with stricter requirements (e.g., Python 2.7+, lots of disk space) that includes _everything_ (these plugins, the Lexicon plugins, the in-progress GoDaddy [#4748] and RFC 2136 [#4701] plugins, additional installer plugins [#4671, #4672, #4673], etc.)?

**Comment by erikrose** [comment]
What's our telemetry like? If we don't do it already, I think we need to prioritize recording some stats when we issue a cert: installation method (certbot-auto, packaged, other) and plugin used, for starters. Decisions based around these things keep coming up, and it would be great to stop having to guess!

Following my reluctance to guess, I'd tend toward the idea of just shipping a giant pile of stuff, just in order to avoid complexity that turns out not to have a payoff. Then we can collect stats and complaints and adjust course. (This does make me a little sick, since 37MB is a crazy amount of storage for a couple of network protocols.)

**Comment by zjs** [comment]
> If we don't do it already, I think we need to prioritize recording some stats when we issue a cert: installation method (certbot-auto, packaged, other) and plugin used, for starters

I think all of this is collected as of #4354.

**Comment by bmw** [comment]
We can tell whether you're using `*-auto` or not, but we can't currently explicitly differentiate between the other options, however, between the additionally collected OS and version number, we can usually get a pretty good idea.

Here's a snippet of our help output explaining more about the values we collect:
```
  --user-agent USER_AGENT
                        Set a custom user agent string for the client. User
                        agent strings allow the CA to collect high level
                        statistics about success rates by OS, plugin and use
                        case, and to know when to deprecate support for past
                        Python versions and flags. If you wish to hide this
                        information from the Let's Encrypt server, set this to
                        "". (default: CertbotACMEClient/0.14.1 (certbot;
                        Ubuntu 16.04.2 LTS) Authenticator/XXX Installer/YYY
                        (SUBCOMMAND; flags: FLAGS) Py/2.7.12). The flags
                        encoded in the user agent are: --duplicate, --force-
                        renew, --allow-subset-of-names, -n, and whether any
                        hooks are set.
```
If there's anything in particular you guys are curious about, let me know and I'll pull some stats.

If we can allow these plugins to be optionally installed without a massive increase in complexity and I get the OK next week for those of us at EFF to invest some time developing a solution, I think we should do it.

**Comment by bmw** [comment]
By the way, I just got the go ahead that we can spend some time implementing something here. Making every user download `boto3` sounded painful.

**Comment by AnalogJ** [comment]
The way that I handle this in `lexicon` is by making the provider specific dependencies optional using the `extras_require` keyword in [setup.py](https://github.com/AnalogJ/lexicon/blob/master/setup.py#L87). 

If you want to use the `route53` provider you need to run:
`pip install dns-lexicon dns-lexicon[route53]`

It does make the install command more complicated, but doesn't include all the unnecessary packages if they aren't required.

**Comment by erikrose** [comment]
Thanks for bringing it up, @AnalogJ. Extras would be the perfect thing, if only we recommended (or even supported) installing via pip. Unfortunately, we have so many non-Python dependencies and so great a need for security that our situation is much more constrained. Hash-checking alone means we'd need to include exhaustive or layered-on requirements files for each plugin (or combination thereof?) in certbot-auto. That actually sounds pretty tempting, but then I think about packaged versions of certbot and realize they'd need a separate solution. At any rate, it's going to require some design thought.

**Comment by bmw** [comment]
The `cloudflare-packaging`, `zjs-digitalocean-packaging`, and `zjs-google-cloud-dns-packaging` branches on this repo may prove useful when we go to solve this.

**Comment by jvanasco** [comment]
Have you considered a `certbot-auto` command to register and track desired plugins?

i.e. one might do `certbot-auto --install-plugins lexicon`, which would do the following:

* track the plugins as managed (e.g. lexicon) in the config directory (e.g. /etc/letsencrypt)
* install the plugins via pip
* on certbot upgrades, install the tracked/managed plugins in /etc/letsencrypt

it would only work for pypi plugins, but that would allow you to trash the directory, reinstall plugins, and only ship the core requirements by default.

**Comment by erikrose** [comment]
Sure, that's a fine UI. Unfortunately, I don't think it solves any of the technical issues surrounding pinning.

**Comment by pde** [comment]
@erikrose I'm pondering an implementation of this. I can either conditionally add sections to the requirements file for each DNS plugin, if the user has installed that plugin or try doing it with extras (which is somewhat cleaner). Would anything explode if I added extras sections to the pinned requirements list?

**Comment by pde** [comment]
Maybe another way of putting that is, is it possible to specify requirements with `-r requirements.txt` and then optionally supply extras to that command?

**Comment by bmw** [comment]
@pde, I'd encourage you not to spend too much time on an implementation here that doesn't work for third party plugins unless we're planning on taking on and maintaining most of the of DNS plugins from the community ourselves. A solution here that would work for 3rd party plugins would work for our DNS plugins as well.

(As a briefly touched on, I also have some concerns/thoughts with our approach to packaging in general and I think our solution outside of distro packaging can be improved if it's going to be something we want to support in the long term. This could just mean largely rewriting `certbot-auto`, but while a patch to do this to the current version of `certbot-auto` could be useful now, it might not be in 3 months.)

**Comment by pde** [comment]
@bmw my plan wrt to third party plugins was to let them make 3-5 line PRs to be supported by `certbot-auto`. Overall not sure it's worth it, but wanted to see how simple/crazy it looked in practice.

**Comment by bmw** [comment]
Not sure exactly what UI you had in mind, but I think we need to be a little careful about `certbot-auto` containing code to install 3rd party plugins that we don't maintain and run as `root`.

**Comment by pde** [comment]
Malicious 3pp code is going to be run as root regardless of how it's installed, i fear? Probably via registration code even if the plugin isn't used.

At least with this install method 3pp authors would have to publish hashes over their packages :/

**Comment by pde** [comment]
We could also prompt for user confirmation  on the 3pp install step.

**Comment by noci2012** [comment]
How about separately installable packages? (ie. not the tree including tests, only the modules needed with dependencies mentioned.).   Not all distro's are pip friendly. Gentoo's pip install tells to use pip install --user  with this: "ERROR: (Gentoo) Please run pip with the --user option to avoid breaking python-exec"

**Comment by maximillianh** [comment]
Closing this in favor of #5884 and #6613
