### ISSUE TITLE
Interpret replace=True as "replace if possible, otherwise append"

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#4832]
https://community.letsencrypt.org/t/permissions-required-to-etc-letsencrypt-live-for-script/35645/6

In Nginx, say someone's done something like this:

```
server {
  server_name perfectly-good-name.com;
  listen 443 ssl;
  # ssl_certificate /etc/letsencrypt/live/example.org/fullchain.pem;
  # ssl_certificate_key /etc/letsencrypt/live/example.org/privkey.pem;
}
```

They know where the certs will live, so they've put in links to them, but Nginx needs real files there, so they comment them out.

But now the installer's going to fail, because we make the assumption that if someone has a server block with ssl enabled, we shouldn't add any ssl directives because we should try to leave things as much the same as possible.

I propose changing this assumption from an empirical perspective. People run into this all the time, so therefore it's the workflow that people expect should work. Therefore we should support it.

I'd love to hear any reasons why we didn't do this previously, or if we treat this differently in Apache.

**Comment by ohemorange** [comment]
@bmw @joona?

**Comment by HumanJHawkins** [comment]
My two cents as a user, on varying degrees of improvement that could be made:

1) Least Work: Just improve the error message... "Unable to install" sounds like something went wrong, which triggers the need to find out what happened and evaluate if other things may have broken. It would help if the message said something like:
`Certificate created and stored at <path to certs>. Modification of existing SSL server blocks not supported. Manual configuration will be required. 
NOTE: Most users just need to add the following to their ssl-enabled server block(s):
ssl_certificate /etc/letsencrypt/live/example.org/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/example.org/privkey.pem;`

2) Most Work: Allow the script to run regardless of validity of existing ssl_certificate configuration. If existing ssl_certificate configuration becomes valid because of cert creation, do nothing. Otherwise, update the config to be valid, using the new certificate. (Possibly with "Do you want to overwrite" type messages for cert files if some already exist.)

3. Middle ground: One could imagine a scope-reduced version of (2) above... Just handle the easiest most common cases... I.e. only those with a single server block using the cert. Any case more complex than that could fall back on a useful error message... Something like "Site configuration too complex for script to safely handle. Certificates are created, but manual configuration will be required."

Thanks.

**Comment by bmw** [comment]
> I propose changing this assumption from an empirical perspective. People run into this all the time, so therefore it's the workflow that people expect should work. Therefore we should support it.
>
> I'd love to hear any reasons why we didn't do this previously, or if we treat this differently in Apache.

I had to do some digging and testing here as the relevant code even predates my involvement in the project. I agree that we should do this when trying to add the cert and key directives to a virtual host.

To provide the best justification I could come up with for why things are this way, in both Apache and Nginx a virtual host like this is probably technically misconfigured. You're telling your webserver to use HTTPS but not providing a cert or key unless you've added one to your top level config which isn't done by default or a normal practice as far as I know.

This is especially true in Apache where Apache will fail to start if you tell it to use SSL/TLS without a cert and key. Nginx behaves differently and will start, but will refuse connections to the server and write messages to `error.log`. Part of the reason we do this in Nginx may be that the Nginx plugin was written to strongly mimic the way the Apache plugin worked at the time where this makes a little more sense.

With all that said, Nginx still runs in this case and the configuration is valid in either server if there are certs and keys in the top level config. I see no problem fixing this and made #4837 to track the issue in Apache.

In Nginx, this could be done as simply as catching the error thrown if `replace=True` and the directive doesn't exist and calling again with `replace=False`. We could make an additional function in `parser.py` to do this if we wanted. Alternatively, we could just make `replace=True` have this behavior by default, but I'd carefully audit the code to make sure this is what we want to happen in every case.

**Comment by ohemorange** [comment]
This case is the one and only time it's called with `replace=True`.
