### ISSUE TITLE
certbot is testing for /etc/system/systemd in cron file even if there is no systemd

### ISSUE THREAD

**Issue by georgthegreat** [certbot/certbot#4834]
## My operating system is (include version):
```
I am running ubuntu xenial with upstart.
```

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
```
apt-get install certbot
```

## I ran this command and it produced this output:
```
$ cat /etc/cron.d/certbot
...
0 */12 * * * root test -x /usr/bin/certbot -a \! -d /run/systemd/system && perl -e 'sleep int(rand(3600))' && certbot -q renew
```

## Certbot's behavior differed from what I expected because:
I'd like certs to be cron-renewable

**Comment by ynasser** [comment]
Hi @georgthegreat, thanks for reaching out.

Certbot's Debian package tries to be compatible with both cron and systemd timers, which is why it's written like this. If you don't have systemd installed, this cron job will run just fine. 

If you really want, you can just change it to something like this: 
`0 */12 * * * root perl -e 'sleep int(rand(3600))' && certbot -q renew`

Note: make sure to test this, as I haven't.

If you modify the cron job further, please make sure to the time it runs remains randomized somehow so as to not overwhelm the LE servers.

**Comment by ynasser** [comment]
Closing as this behaviour is intentional.
