### ISSUE TITLE
Failed authorization Procedure

### ISSUE THREAD

**Issue by walttheboss** [certbot/certbot#4835]
## Ubuntu Server 16.04.2 with Kubuntu Desktop

!!!  I am currently running this domain on a 14.04 Ubuntu/Apache2 server at the same WAN address.  Is that the reason for the conflict?  The new server is failing and the old/current server is fine. 

## Certbot's behavior differed from what I expected because:  I expected new certificates and it failed
[letsencrypt.log.txt](https://github.com/certbot/certbot/files/1074045/letsencrypt.log.txt)

## Here is the relevant Apache virtualhost for the domain I am configuring:

<VirtualHost *:443>
    ServerAdmin it@msg-kmg.com 
    ServerName msgkmg.com
    ServerAlias www.msgkmg.com
    DocumentRoot /var/www/msgkmg
<Directory />
                Options FollowSymLinks Indexes
                IndexOptions +ShowForbidden
                AllowOverride All
        </Directory>
        
ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined
        
#    ErrorLog /srv/www/mydomain.net/logs/error.log
#    CustomLog /srv/www/mydomain.net/logs/access.log combined

   SSLEngine on
    SSLOptions +StrictRequire
SSLCertificateFile /etc/ssl/certs/ssl-cert-snakeoil.pem
SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key
</VirtualHost>

Below is the Terminal output
[certbot_terminal_output.txt](https://github.com/certbot/certbot/files/1074074/certbot_terminal_output.txt)

**Comment by SwartzCr** [comment]
Is the vhost block that you wrote into the comment the entire config file for those domains? I'd like to see the full unedited vhost to be able to help debug this problem

**Comment by walttheboss** [comment]
Thanks Swartz,  Attached are a few files.  They are titled to be clear.
The last one is my entire apache2 folder from the new install.

NOTE:  I am currently running all of my domains on a 14.04 server here in the office(ddclient and dynamic IP).  The new server(16.04) is here on a different lan address.  No ddclient running and no router redirects.  If (I am a rookie) the test process goes out and then returns to msgkmg.com the return signal on port 443 will go to the old box.  I have attached the 14.04 apache2 config files as well. 

[apache2-conf.txt](https://github.com/certbot/certbot/files/1076463/apache2-conf.txt)
[ports-conf.txt](https://github.com/certbot/certbot/files/1076464/ports-conf.txt)
[sites-available-default.conf.txt](https://github.com/certbot/certbot/files/1076465/sites-available-default.conf.txt)
[sites-available-ssl-default.conf.txt](https://github.com/certbot/certbot/files/1076466/sites-available-ssl-default.conf.txt)

OLD SERVER:  Currently running fine on certbot/letsencrypt
[apache2-14.04.zip](https://github.com/certbot/certbot/files/1076475/apache2-14.04.zip)

THANKS!

**Comment by SwartzCr** [comment]
So one thing to note is that you need to be serving the domain from the server that you're running the challenge from.
When Certbot initiates the challenge, the Let's Encrypt server does a DNS query for that domain and then tries to validate it at the IP address that it gets back.
So if you have the domain hosted on one server, and then are trying to run the challenge from another it won't work, since it'll make the challenge request to the server that is currently hosting the domain.
To get it to work, you'll need to either request a cert from the server currently hosting the domain, or move the DNS to the new server

**Comment by SwartzCr** [comment]
Yes, you won't be able to do the challenge from the server until it is serving the domains that you want the certificates for. On the plus side you would be able to migrate the certificates from one server to the other if you don't want to have to worry about potential downtime.
I'm going to close this issue since it seems like your questions have been answered, but feel free to open another issue if you run into problems later when you try it on your new server
