### ISSUE TITLE
SEC_ERROR_UNKNOWN_ISSUER (weird/odd issue)

### ISSUE THREAD

**Issue by FexileTV** [certbot/certbot#4849]
## My operating system is (include version):
Ubuntu 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
The Instructions that were provided, I've installed it the same way for other domains too and always worked fine.

## I ran this command and it produced this output:
do you know how I can fix this? SEC_ERROR_UNKNOWN_ISSUER
https://galaxycheats.com/
https://www.galaxycheats.com/ works fine for some reason
sudo certbot --apache -d galaxycheats.com -d www.galaxycheats.com

## Certbot's behavior differed from what I expected because:
www.galaxycheats.com works fine, without www. it gives the Unknown issuer warning

do you know how I can fix this? SEC_ERROR_UNKNOWN_ISSUER
https://galaxycheats.com/
https://www.galaxycheats.com/ works fine for some reason

command I'm using:
sudo certbot --apache -d galaxycheats.com -d www.galaxycheats.com

I used the EXACT same command for Nexusblocks.com (sudo certbot --apache -d nexusblocks.com -d www.nexusblocks.com)
and there it worked fine both www and without it....? so why is it not working on my new domain?

**Comment by FexileTV** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=galaxycheats.com&latest

Issuer 	GalaxyCheats.com   Self-signed ?

Why is it Self-Signing?? I want Lets Encrypt to verify it.

**Comment by FexileTV** [comment]
How do I force it to get issued by Lets Encrypt?
Issuer 	Let's Encrypt Authority X3  Like this is what I want and most likely will resolve the problem I'm having

**Comment by SwartzCr** [comment]
So it seems like you have a valid Let's Encrypt Certificate. It's getting served when you navigate to www.galaxycheats.com
Unfortunately that certificate is issued for galaxycheats.com and not www.galaxycheats.com, so the browser is complaining that it has the wrong URL listed, thus `NET::ERR_CERT_COMMON_NAME_INVALID`
The certificate that gets served when you go to galaxycheats.com is a self signed cert, not the let's encrypt certificate. I'd suggest doing two things:
using the --cert-name command to expand the domains listed in the certificate that you got to include www.galaxycheats.com. Once you do this it should just automatically start working, since it'll store the new certificate in the same location that it was previously stored (where your webserver is serving it)
Also I'd look to see where in your conf file you're specifying how to serve GalaxyCheats.com and see if it's pointing to some other certificate.
I'd be happy to help with this debugging, but you'd have to let me know what webserver you're using so that I can help suggest where these files might be.
Let me know if this helps!

**Comment by FexileTV** [comment]
I'm seeing this Issue: SEC_ERROR_UNKNOWN_ISSUER
On GalaxyCheats.com, While www.galaxycheats.com works fine.
I'm using Apache2 on Linux Ubuntu 16.04

I did the EXACT same setup for NexusBlocks.com and there both www. and non-www work fine without any problems. 
I used this command:
sudo certbot --apache -d nexusblocks.com -d www.nexusblocks.com (both work fine as expected)

sudo certbot --apache -d galaxycheats.com -d www.galaxycheats.com (only the www. works, and without www. it gives a self signed cert error, I do want to use Lets Encrypt to sign my cert, how do I force/fix this problem?)

I've tried a reinstall, and tried to force-renew the cert but those didn't help.

**Comment by SwartzCr** [comment]
Can you share the apache config file that mentions galaxycheats.com, I'm willing to bet it's pointing at a different certificate than the one you just issued.
It might be best to consolidate the apache vhosts if you have one for www.galaxycheats.com and a different one for galaxycheats.com
If you can share them with me I'd be happy to help you debug this

**Comment by FexileTV** [comment]
Here is my apache config file for galaxycheats: https://pastebin.com/raw/e6YAgUQb

**Comment by SwartzCr** [comment]
@FexileTV I'd be happy to debug this more with you today, would it be possible for you to join our IRC channel? It's #letsencrypt on irc.freenode.net

**Comment by SwartzCr** [comment]
if not - it might help if you could share all of your virtualhosts with me. I'm guessing that you have multiple config files that specify galaxycheats.com

**Comment by FexileTV** [comment]
My name is _Fx on the IRC Channel, I can't type/write in the general channel though?
== Cannot send to channel

**Comment by FexileTV** [comment]
I'm _Fx on IRC

**Comment by FexileTV** [comment]
Here's all my config files:
https://pastebin.com/raw/B2WcmCuh

You can test/see that NexusBlocks works perfectly fine, Both www. and non-www. I set this one up first and then I setup GalaxyCheats, With the EXACT same steps as I did on NexusBlocks, and somehow it won't doesn't work...

**Comment by SwartzCr** [comment]
I tried to find you on IRC but it seems that you had logged off already, feel free to ping me next time - my name there is also swartzcr
Just to triple check, those are the only apache configs in your sites-enabled directory?

**Comment by FexileTV** [comment]
There's some more but they are not relevant/using LetsEncrypt

**Comment by FexileTV** [comment]
Issue was resolved (with help) by disabling default-ssl.conf
