### ISSUE TITLE
OSError: [Errno 95] Not supported

### ISSUE THREAD

**Issue by gimmemoore** [certbot/certbot#4850]
## My operating system is (include version):
Docker for Azure on swarm manager

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Certbot is installed in an image nginx:alpine

## I ran this command and it produced this output:
2017-06-19 17:51:40,050:DEBUG:root:Sending GET request to https://acme-staging.api.letsencrypt.org/acme/issuer-cert. args: (), kwargs: {'headers': {'Accept': 'application/pkix-cert'}}

## Certbot's behavior differed from what I expected because:
The following occurs if the drive is not empty using a cloudstor:azure plugin for the drive.

2017-06-19 17:51:40,160:DEBUG:certbot.storage:Creating directory /etc/letsencrypt/archive.
2017-06-19 17:51:40,180:DEBUG:certbot.storage:Creating directory /etc/letsencrypt/live.
2017-06-19 17:51:40,216:DEBUG:certbot.storage:Archive directory /etc/letsencrypt/archive/app.concludely.io and live directory /etc/letsencrypt/live/test.app.io created.
2017-06-19 17:51:40,226:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.7.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 693, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 512, in obtain_cert
    _, action = _auth_from_domains(le_client, config, domains, lineage)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 93, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains)
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 293, in obtain_and_enroll_certificate
    configuration.RenewerConfiguration(self.config.namespace))
  File "/usr/lib/python2.7/site-packages/certbot/storage.py", line 801, in new_lineage
    target[kind])
OSError: [Errno 95] Not supported

**Comment by SwartzCr** [comment]
hmm
well 0.7.0 is a really old version of certbot - do you think there's a way to get a newer version of certbot? I'm not sure if that'd fix the problem, but it might be good regardless.
You're experiencing this error even when there is disk space, but not if the drive is empty?
Have you previously gotten certbot to work on this platform?

**Comment by gimmemoore** [comment]
I'm getting this error on a brand new docker volume that is configured with the cloudstor:azure (docker for azure plugin for volumes) and I also get the error when there is data in that drive from previous attemps to save certificates.

I'll rebuild the docker image to use the latest certbot from APK registry and give it a shot tomorrow.

**Comment by SwartzCr** [comment]
Okay great, let me know how it goes!

**Comment by trajano** [comment]
I think the file system it is trying to use in my case CIFS on windows gives issues

**Comment by SwartzCr** [comment]
@trajano Are you running certbot on windows?
also tagging @bmw to take over this ticket

**Comment by trajano** [comment]
@SwartzCr yes and no.  I was looking for this ticket earlier so I can post the solution.  The issue is that certbot requires the use of symlinks which are not available in Windows and CIFS shares by default do not support symlinks

I say yes and no because I am running Docker inside a Linux VM guest hosted on a Windows box whose drives are shared via SMB using the https://github.com/ContainX/docker-volume-netshare.

The key option is *mfsymlinks* as noted in my docker-compose.yml volume configuration below.

```
  letsencrypt:
    name: 'noriko/s/letsencrypt'
    driver: cifs
    driver_opts:
      cifsopts: vers=3.02,file_mode=0666,dir_mode=0777,mfsymlinks
```

**Comment by bmw** [comment]
Thanks for providing the solution @trajano.

Unfortunately, Certbot's directory structure relies heavily on symlinks so fixing this in Certbot won't be a quick and easy fix, but I'm glad to see there is a workaround for Docker users.

**Comment by weboide** [comment]
This issue comes up when using Azure Container Groups (with a linux docker image) with a mounted volume for /etc/letsencrypt using the azureFileVolume object.
Looking at the docs (https://docs.microsoft.com/en-us/azure/templates/microsoft.containerinstance/2018-10-01/containergroups#AzureFileVolume and https://docs.microsoft.com/en-us/azure/templates/microsoft.containerinstance/2018-10-01/containergroups#volumemount-object) I'm not seeing any way to define cifsopts...

I feel like my only other option is mounting that folder manually, but that defeats the whole purpose of easily mounting volumes through Azure's API.

**Comment by cwiederspan** [comment]
@weboide - Did you have any luck coming up with a work around on Azure Container Groups? I've run into the same exact problem.

**Comment by weboide** [comment]
No I could not find a way to change mount options on a ARM template cifs mount and you can't remount on azure container due to permissions restrictions.
The workaround I had to come up with to keep going with my project is basically:
- see if there's a tarball of letsencrypt config in storage
- untar it to /etc/letsencrypt
- run certbot-auto
- tar /etc/letsencrypt and put it back in storage.

**Comment by hermanho** [comment]
I tried with pv and pvc configuration and it works with azureFile

Template:
https://gist.github.com/hermanho/736f8074672a644fddddaeab438e7c68

Original ref:
https://www.danielemaggio.eu/containers/azure-files-shares-with-symlinks-support-on-aks/

**Comment by cwiederspan** [comment]
@hermanho - Thanks, that's definitely helpful. Unfortunately, my use case is to have this working in Azure Container Instance, not AKS, so I think I'm still stuck. That said, you did give me an idea to try this in App Service for Containers using the Kubernetes deployment option, so I might tinker with that, too.

**Comment by dsschneidermann** [comment]
> if there's a tarball of letsencrypt config in storage
> * untar it to /etc/letsencrypt
> * run certbot-auto
> * tar /etc/letsencrypt and put it back in storage.

@weboide -Will you share your script and/or Dockerfile? Would be helpful to work around this issue

**Comment by weboide** [comment]
@dsschneidermann And here you go: https://gist.github.com/weboide/4e6e7fda740affd34c4011f794a4317c
Make sure you define each environment variable, they should be self-explanatory.
Use $CERTBOT_EXTRA_ARGS to do pass --dry-run or --test-cert to certbot for your testing.
