### ISSUE TITLE
Installation instructions certbot-dns-route53

### ISSUE THREAD

**Issue by rtfmoz** [certbot/certbot#4875]
The main page for this plugin just says step 4 "Install this package" but does not specify how. 

git clone? can we have the universal command for downloading this plugin please as git clone is not working.

**Comment by SwartzCr** [comment]
So you can either follow the developer instructions, or in some rare cases it's packaged for the OS. What OS are you using?

**Comment by rtfmoz** [comment]
Ubuntu. I figured it out in the end but their no download on that dns-route53 page. You have to download the entire certbot from the main page. Once certbot is setup then start configuring plugins. However this is NOT documented anywhere and the plugins page is woefully out of date. I have rudimentary github skills. So better documentation is needed. I'm happy to help

**Comment by SwartzCr** [comment]
Yeah, we actually have an issue for that: https://github.com/certbot/certbot/issues/4828
I'd happily review any documentation you want to write

**Comment by franklinyu** [comment]
The documentation of [DNS Plugins](https://certbot.eff.org/docs/using.html#dns-plugins) says

> These plugins are still in the process of being packaged by many distributions and cannot currently be installed with `certbot-auto`. If, however, you are comfortable installing the certificates yourself, you can run these plugins with [Docker](https://certbot.eff.org/docs/install.html#docker-user).

It seems to imply that the docker image has all these plugins installed, which is not the case. I tried the docker image but still got

> The requested dns-route53 plugin does not appear to be installed

**Comment by ConnixConsulting** [comment]
Hi.
I was following the instructions on this article, but the command _pip install certbot_dns_route53==0.22.2 return error.
Any tip?

https://medium.com/prog-code/lets-encrypt-wildcard-certificate-configuration-with-aws-route-53-9c15adb936a7

**Comment by ciarancourtney** [comment]
The following worked for me on Ubuntu 18.04 which comes with Python 3.6

    # install system pip if not already (usually not installed)
    sudo apt install python3-pip

    pip3 install certbot-dns-route53

**Comment by juanjoku** [comment]
Hello!

I also have problems with dns-route53 plugin:

I installed certbot (v0.28.1 - Linux Ubuntu 16.04), no problem: it works perfectly with http-challenges.
Then I installed the dns-route53 plugin, without any error in the process.

```
$ sudo apt-get update && sudo apt-get -y upgrade
$ sudo apt-get install python-pip
$ pip install certbot_dns_route53==0.26.1 (my version)
```

BUT when I try to use it ... 

```
$ sudo certbot certonly --dns-route53 -d mydomain.com

Saving debug log to /var/log/letsencrypt/letsencrypt.log
Could not choose appropriate plugin: The requested dns-route53 plugin does not appear to be installed
The requested dns-route53 plugin does not appear to be installed
```

:-(


Log details:

```
$ sudo cat /var/log/letsencrypt/letsencrypt.log

2018-10-17 14:00:01,359:DEBUG:certbot.main:certbot version: 0.26.1
2018-10-17 14:00:01,359:DEBUG:certbot.main:Arguments: ['--dns-route53', '-d', 'mydomain']
2018-10-17 14:00:01,360:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2018-10-17 14:00:01,370:DEBUG:certbot.log:Root logging level set at 20
2018-10-17 14:00:01,370:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2018-10-17 14:00:01,372:DEBUG:certbot.plugins.selection:Requested authenticator dns-route53 and installer None
2018-10-17 14:00:01,372:DEBUG:certbot.plugins.selection:No candidate plugin
2018-10-17 14:00:01,372:DEBUG:certbot.plugins.selection:Selected authenticator None and installer None
2018-10-17 14:00:01,372:INFO:certbot.main:Could not choose appropriate plugin: The requested dns-route53 plugin does not appear to be installed
2018-10-17 14:00:01,373:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.26.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1364, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1233, in certonly
    installer, auth = plug_sel.choose_configurator_plugins(config, plugins, "certonly")
  File "/usr/lib/python3/dist-packages/certbot/plugins/selection.py", line 237, in choose_configurator_plugins
    diagnose_configurator_problem("authenticator", req_auth, plugins)
  File "/usr/lib/python3/dist-packages/certbot/plugins/selection.py", line 341, in diagnose_configurator_problem
    raise errors.PluginSelectionError(msg)
certbot.errors.PluginSelectionError: The requested dns-route53 plugin does not appear to be installed  
```

**Comment by ciarancourtney** [comment]
`pip` is probably your Python2 system pip, you want `pip3` or `pip3.6`

**Comment by juanjoku** [comment]
Oops! Thanks, Ciaran.

PS: Yes, I was using pip/python2; I don't understand why pip3/python3 is required now.
(I've never worked with Python)
I suppose it will be a "new" requirement from some version of certbot.

**Comment by franklinyu** [comment]
I managed this without `pip`.

I’m using Ubuntu Bionic Beaver (18.04). I installed [`certbot`](https://packages.ubuntu.com/bionic/certbot) and [`python3-certbot-dns-route53`](https://packages.ubuntu.com/bionic/python3-certbot-dns-route53). After that, I configured my credential in `~/.aws/credentials` as

```ini
[default]
aws_access_key_id=ASDFGHJKL
aws_secret_access_key=my+secret/key+base64/encoded
```

(This is not required if running in EC2.) Then I managed to generate a wildcard certificate with

```bash
sudo certbot certonly --dns-route53 -d '*.example.com,example.com' --server https://acme-v02.api.letsencrypt.org/directory
```

(The `--server` option is required in this case. I guess latest Certbot defaults to ACME-v02.)

**Comment by amlife180** [comment]
@franklinyu  took me a full day to finally find your post. 

It worked.  I wonder of renewing will be as easy.  Can someone confirm? 

Thanks

**Comment by franklinyu** [comment]
@amlife180 Renew worked. Just make sure that the credential is still available during renew.

Also note that renewal is essentially applying for a new certificate, so the DNS record on Route53 will be changed again. This takes about a minute in my machine. Be patient.

**Comment by amlife180** [comment]
@@franklinyu  thanks so much!  your help is highly appreciated.

**Comment by FranklinYu** [comment]
I checked yesterday and the unattended renewal happened. So yes, wildcard certificate Route53 should be fully supported. Note that server (NGINX in my case) needs to reload to pick up the new certificate, of course.

**Comment by harshayburadkar** [comment]
@FranklinYu I am in the same boat and would like to set up auto-renew if possible. How did you set up your autorenewal or better yet unattended auto renewal? I read in the documentation that certbot-auto does not support plugins (for e.g. certbot-dns-route53) yet. So then the only option is using the certbot command instead of certbot-auto.  I am not sure how to set up auto-renewal with certbot.

**Comment by FranklinYu** [comment]
@harshayburadkar No, I didn't use `certbot-auto`. I installed and run `certbot` manually.

**Comment by Zyles** [comment]
```
# sudo certbot certonly --dns-route53 -d '*.example.com,example.com' --server https://acme-v02.api.letsencrypt.org/directory
An unexpected error occurred:
pkg_resources.VersionConflict: (acme 0.39.0 (/usr/lib/python3/dist-packages), Requirement.parse('acme>=0.40.0'))
Please see the logfile '/tmp/tmp4sjmivuu/log' for more details.
```

**Comment by FranklinYu** [comment]
@Zyles How did you install certbot and the plugin?

**Comment by Zyles** [comment]
> @Zyles How did you install certbot and the plugin?

Can't remember. I tried 5 different install methods and gave up because non worked.

Ubuntu 19.10.

**Comment by johnrix** [comment]
Having similar problems on Ubuntu 18.04 today:

```
# add-apt-repository ppa:certbot/certbot
# apt install certbot python3-certbot-dns-route53
# certbot-auto certonly --dns-route53 --dns-route53-propagation-seconds 30 -d example.com
```

Produces:

```
An unexpected error occurred:
pkg_resources.VersionConflict: (certbot 0.31.0 (/usr/lib/python3/dist-packages), Requirement.parse('certbot>=0.39.0'))
Please see the logfile '/tmp/tmpec2y9tsy' for more details.
```

Also currently having no joy with certbot-auto installation or trying directly via pip3.

**Comment by johnrix** [comment]
Ah... had some residual python modules installed from previous installation efforts that were conflicting with that last procedure. To clean this up, I first uninstalled the APT package, uninstalled the packages installed via pip3 and then restored the APT packages (may only need to remove the pip3 packages, but not certain!):

# apt remove python3-certbot-dns-route53
# apt autoremove
# pip3 uninstall certbot-dns-route53
# apt install python3-certbot-dns-route53

Happy days!

**Comment by FranklinYu** [comment]
> I tried 5 different install methods and gave up because non worked.

That’s the problem. Install methods conflict with each other. Even if the 3rd method works, you won’t know, because it was hidden by 1st or 2nd. (Look at the case right below you.) For example, if you do `sudo pip`, a corrupted installation is pretty much doomed. Sorry but I can’t offer any help in this case.

**Comment by rotorboy** [comment]
Just tried the install and run and ran into same issues mentioned above. Is there a SINGULAR AUTHORITATIVE install for certbot + route53 on Ubuntu 16.04 that will work?

Oddly enough, I used the very same commands on a "fresh install" about a month ago:

sudo add-apt-repository -y ppa:certbot/certbot

# update added repositories with all additions
sudo apt-get update
sudo apt-get --with-new-pkgs upgrade

# install certbot, python3-pip, and route53 plugin
sudo apt-get -y install certbot
sudo apt install python3-pip
sudo pip3 install certbot-dns-route53

And everything worked fine. Now, I'm getting conflicts mentioned above:

/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.25.7) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
An unexpected error occurred:
pkg_resources.VersionConflict: (acme 0.31.0 (/usr/lib/python3/dist-packages), Requirement.parse('acme>=0.40.0'))

error logfile contents: 

  File "/usr/local/bin/certbot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/certbot/main.py", line 14, in main
    return internal_main.main(cli_args)
  File "/usr/local/lib/python3.5/dist-packages/certbot/_internal/main.py", line 1320, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/local/lib/python3.5/dist-packages/certbot/_internal/plugins/disco.py", line 208, in find_all
    plugin_ep = PluginEntryPoint(entry_point)
  File "/usr/local/lib/python3.5/dist-packages/certbot/_internal/plugins/disco.py", line 50, in __init__
    self.plugin_cls = entry_point.load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2442, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2465, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (acme 0.31.0 (/usr/lib/python3/dist-packages), Requirement.parse('acme>=0.40.0'))

I tried everything; removing all packages and starting again, removing route53 pip package...nothing seems to remove conflict, so clearly something above is conflicting...

**Comment by johnrix** [comment]
Just a thought... you could try starting with a minimal Ubuntu 16.04 docker container and install just the APT packages for certbot and python3-certbot-dns-route53 to see if any improvement. That would at least give you some indication if it is actually feasible to get it working on 16.04.

**Comment by rotorboy** [comment]
Hey John;

I "solved" the issue by: 

first uninstalling certbot via apt-get remove, the using pip3 to "uninstall" certbot, certbot-dns-route53, and acme.  Even though they were removed from "pip3", a pip3 listing should "older versions of ALL THREE still remaining.

I then reinstalled "cerbot" via apt-get, and that ran properly.

As a post mortem: It seems that the certbot version in ubuntu 16.04 repository is version 0.31, as opposed to 1.0.0 which seems to be the most current. It also would be helpful to have a SINGULAR and authoritative installer that installs the latest versions of acme, cerbot, and any dns plugins that certbot knows about. having to install plugins via pip seems to throw things off. 

It should also be noted that while I hacked to get it to work, I have no idea what combination to use to get the latest versions of acme, cerbot, and required dns-plugin that won't conflict with itself. Even if I DID come up with one, the evolutionary nature of this project means what works today may not work tomorrow...

**Comment by FranklinYu** [comment]
> It seems that the certbot version in ubuntu 16.04 repository is version 0.31, as opposed to 1.0.0 which seems to be the most current.

@rotorboy Maybe you are new to Ubuntu (or even to Linux?) but Ubuntu packages are known to be lagged a bit behind the latest version. [v0.31](https://github.com/certbot/certbot/releases/tag/v0.31.0) was released this February so it shouldn’t be too bad; is there anything, functionality or bug fix, in v1.0.0 that concerns you?

**Comment by rotorboy** [comment]
Franklin; 

As I've been using Linux since pretty much the day Linus released it, and Ubuntu since 2005 while doing web application development, I'm pretty well aware of the "lag" in packaging, often finding myself running apt-get --with-new-packages to force the upgrade to the latest in another repository, and careful reading of my post would reveal that "lag", while annoying, isn't my primary question/concern.

The issue, as you had mentioned, is that there are MULTIPLE installers for "certbot" and its various dependencies and plugins; each provides required pieces, but often providing other pieces that conflict with previous installers that ran prior. There doesn't seem to be a current, singular "complete and authoritative" installer source that will install the "latest and greatest" acme, certbort, and necessary plugins (and their dependencies like python3 etc) in one installer. 

As for concerns between 0.31 and 1.0.0, I have looked at GitHub for all the diffs between 0.31 and 1.0.0, but the commit notes are pretty light so without going through all the code changes, its hard to know with certainty if any of the changes are significant to me. That being said, I believe its usually better to be on the latest code than older code.

**Comment by johnrix** [comment]
FWIW, I have certbot v0.31.0 on Ubuntu 18.04 at present also. According to dpkg:

```
ii  certbot                             0.31.0-1+ubuntu18.04.1+certbot+1   all          automatically configure HTTPS using Let's Encrypt
ii  python3-certbot-dns-route53         0.23.0-2+ubuntu18.04.1+certbot+1   all          Route53 DNS plugin for Certbot

**Comment by FranklinYu** [comment]
> The issue, as you had mentioned, is that there are MULTIPLE installers for "certbot" and its various dependencies and plugins

Not surprising. There is no single best way to install Certbot that satisfy everyone and every use case. For me I prefer the stability for distribution unless I want a certain function or a bug fix there. If there is a Pull Request removing the current instruction of installing Certbot through package manager, I would vote against it.

> As I've been using Linux since pretty much the day Linus released it, and Ubuntu since 2005 while doing web application development, I'm pretty well aware of the "lag" in packaging

Then I assume that there is some other reason for you to stay with Ubuntu, because (as you have mentioned) “it’s usually better to be on the latest code than older code” which works better with rolling-release distributions (such as Arch Linux) rather than Ubuntu.

---

Now that I have false assumption about your usage about Ubuntu and Linux, do you develop with Python and are familiar with Python virtual environments?

**Comment by rotorboy** [comment]
> Not surprising. There is no single best way to install Certbot that satisfy everyone and every use case. For me I prefer the stability for distribution unless I want a certain function or a bug fix there. If there is a Pull Request removing the current instruction of installing Certbot through package manager, I would vote against it.

Concur, stability via package "safety and convenience" is optimal, and as I said, I don't have any requirements that require the latest feature set, but having latest bug fixes is typically a good thing. 

To be clear, up until last night's install on an Ubuntu AWS instance, the package-based certbot install + pip3 + route53 plugin process worked just fine. Due to my lack of familiarization with the package internals such as dependencies, paths etc. and no singular authoritative and complete doc to address some of the cracks, I was left with guessing and backing out pieces of the install until I got some combo to work. To wit; I'm still not clear on what the best install order precedence for each of the pieces are for Ubuntu 16.04, perhaps even making the problem of my own doing by using --with-new-packages after addng the certbot repository, then doing the pip3 + route53 install afterward.

> Then I assume that there is some other reason for you to stay with Ubuntu, because (as you have mentioned) “it’s usually better to be on the latest code than older code” which works better with rolling-release distributions (such as Arch Linux) rather than Ubuntu.

When the company I work for started up two years ago, we went with Ubuntu for EC2 image as I felt it was the best option of available choices (kernel stability, security, package manager, my experience with it etc). As such, we have stayed with Ubuntu as it is a known, trusted environment, and a good soldier. As mentioned, the appeal of "latest code" was more from a "user perspective", where all things being equal, having the latest version usually means having the most stable version (i.e. bug fixes), but in this case, 0.31 works just fine for my simple needs; ie issue a wildcard cert. So long as that works as quickly, reliably, and flawlessly as possible, I don't care what version I use. To be sure I wasn't even AWARE there WAS a certbot 1.0.0. until I had to start debugging my installation. 

As a "end user", it would be great to simply have a single apt-get install to do that installs acme, certbot, and the selected dns-updater plugin, if one is needed.
 
> Now that I have false assumption about your usage about Ubuntu and Linux, do you develop with Python and are familiar with Python virtual environments?

Unfortunately, I have only a miniscule amount of experience working with Python itself (out of necessity to debug some code). AWS CLI tools, and packages like certbot seem to be gravitating to  Python and by extension, pip/pip3. Other than knowing they exists, I have no detailed knowledge of differences between Python 2.7 and 3.x, or any details on pip/pip3 version differences, and none with Python virtual environments, so my ability to do "conflict resolution" between packages that use any of these is limited.

**Comment by Zyles** [comment]
It is ridiculous the install steps are 10 steps and hours of debugging because they are outdated and install old crap that conflicts with the new packages.

Make an installer that installs EVERYTHING and WORKS.

**Comment by rotorboy** [comment]
Zyles;

While I wouldn't characterize the issue as ridiculous, nor did I spend "hours" debugging (but did spend hours researching the "right way to install all pieces"), I would concur that the lack of a singular, trusted, comprehensive install package for the popular install systems of un*x for the likely "majority use case" is disappointing, given most usage cases involve issuing one or more certs for a set of subdomains or wildcard for a "production server" and then renewing.

My guess is there are licensing and/or other non-technical issues or decisions that preclude certbot / EFF from bundling everything in one installer. The "language lovefest" developers are having with python has the python installer/environment playing a critical role in this, and for those of us not steep in its mythology, adds a degree of complexity to deal with when the install goes awry, which is what happened to me the other night.

**Comment by FranklinYu** [comment]
> most usage cases involve issuing one or more certs for a set of subdomains or wildcard for a "production server" and then renewing.

I agree, however I would argue that most users don’t want (or don’t care about) latest release. If you only use the APT packages, then you got the automatic renewal automatically. Your requirement of *latest release* adds complexity to installation and configuration.

For example, this satisfy my need (and probably a great lot of others):

1. Install Certbot and the plugin through APT. My DNS provider is Cloudflare (I switched from Route53 to Cloudflare for fun), so for me it’s `certbot` and `python3-certbot-dns-cloudflare`. <sup>1</sup>
2. Configure Cloudflare credentials according to https://certbot.eff.org/docs/using.html#dns-plugins
3. Run `certbot` to get a wildcard certificate, as I mentioned above. https://github.com/certbot/certbot/issues/4875#issuecomment-430869042

The package name in the first step isn’t documented, but I claim that this step works for most users.

I’m not trying to argue against you. When the documentation was written, it didn’t consider much about wildcard certificates. Actually I believe more users are still using non-wildcard certificates rather than wildcard ones, so in this sense “most users“ is a false claim for us. That said, I would still love to improve the documentation to cover wildcard certificate users like me. Two possible improvement:

1. Update the “Certbot Instruction” in the website so that it covers wildcard certificates: https://certbot.eff.org/instructions
2. Add package name to documentation, either at https://github.com/certbot/certbot/blob/6d527bcc426111912fb9faf37ee8467cb75fb55b/certbot/docs/install.rst#operating-system-packages or at https://github.com/certbot/certbot/blob/6d527bcc426111912fb9faf37ee8467cb75fb55b/certbot/docs/using.rst#id4

For the first improvement, I have not yet find out how to do that. I’ll create an issue at https://github.com/certbot/website and link it here. Again, ranting isn’t going to help; this is open source software, so do it your own if you really care about it.

<sub>Footnotes:</sub>  
<sub>1. If you are still using Xenial then you should use the Python 2 version `python-certbot-dns-cloudflare`. The complexity here is obviously not Certbot’s fault. Since we are talking about “most users”, I claim that more users are using Bionic than Xenial, as of now.</sub>

**Comment by rotorboy** [comment]
> I agree, however, I would argue that most users don’t want (or don’t care about) the latest release. If you only use the APT packages, then you got the automatic renewal automatically. Your requirement of _latest release_ adds complexity to installation and configuration.
> 

You continue to misread or otherwise misinterpret what I write, so I'll try again: I don't REQUIRE the latest release, as the current release does all that I need (issue wildcard certs via route53). That said, it would be NICE to HAVE the latest release, especially going from a "point" release to a "major" release, assuming the latest release fixes any issues found in previous releases. 

While APT does provide for "automatic" updates, that requires that the latest packages be made available to APT through "default repositories", which is not always the case. Case in point: Apache 2.4.41 does not come as part of "base" Xenial repository; the repository must be added. If Apache is already installed, the new repository must be added, and --with-new-packages must be used.  Same applies to Certbot: currently, the "certbot repository" only has 0.31, NOT 1.0.0

> I’m not trying to argue against you. When the documentation was written, it didn’t consider much about wildcard certificates. Actually I believe more users are still using non-wildcard certificates rather than wildcard ones, so in this sense “most users“ is a false claim for us. That said, I would still love to improve the documentation to cover wildcard certificate users like me. Two possible improvements:
> 

Well, for someone not trying to argue against me, you seem to be making points to counter my main thesis; It would be nice to have an installer that installs the latest and greatest Certbot with the desired plugins. 

Obviously Letsencrypt can likely run some queries and find out just how many wild-card vs non-wildcard certs have been issued, but I don't think those numbers are germane to our discussion; making Certbot and desired plugins easier to install and configure as desired.

> 1. Update the “Certbot Instruction” in the website so that it covers wildcard certificates: https://certbot.eff.org/instructions
> 2. Add package name to documentation, either at https://github.com/certbot/certbot/blob/6d527bcc426111912fb9faf37ee8467cb75fb55b/certbot/docs/install.rst#operating-system-packages or at https://github.com/certbot/certbot/blob/6d527bcc426111912fb9faf37ee8467cb75fb55b/certbot/docs/using.rst#id4
> 
> For the first improvement, I have not yet find out how to do that. I’ll create an issue at https://github.com/certbot/website and link it here. Again, ranting isn’t going to help; this is open-source software, so do it your own if you really care about it.

These are good steps forward, and I certainly appreciate what the tools that are available today do for me to make cost-free certs. As for "ranting", I think you read something into my posts I did not write; The OP wasn't intended to be a "rant" or "denunciation" of Letsencrypt and/or Certbot, or the tools and installers currently available. With a bit of careful installing, they work as needed. As for "doing my own", while I could probably get up to speed on the source to make changes, unfortunately, I don't have the time to figure all the pieces out to make that so, especially not compared to those who are already working on it full time and familiar with all of it.

**Comment by FranklinYu** [comment]
For users who are already using Docker, my comment above https://github.com/certbot/certbot/issues/4875#issuecomment-377867240 is outdated. Now plugins are available in Docker according to [documentation](https://certbot.eff.org/docs/install.html#running-with-docker):

> There are also Docker images for each of Certbot’s DNS plugins available at https://hub.docker.com/u/certbot which automate doing domain validation over DNS for popular providers. To use one, just replace `certbot/certbot` in the command above with the name of the image you want to use. For example, to use Certbot’s plugin for Amazon Route 53, you’d use `certbot/dns-route53`. You may also need to add flags to Certbot and/or mount additional directories to provide access to your DNS API credentials as specified in the [DNS plugin documentation](https://certbot.eff.org/docs/using.html#dns-plugins). If you would like to obtain a wildcard certificate from Let’s Encrypt’s ACMEv2 server, you’ll need to include `--server https://acme-v02.api.letsencrypt.org/directory` on the command line as well.

Drawback is that unattended renew probably won’t work, because this Docker command is one-shot. Manual renew should work.

**Comment by FranklinYu** [comment]
> While APT does provide for "automatic" updates, that requires that the latest packages be made available to APT through "default repositories", which is not always the case.

@rotorboy I was talking about “automatic renewal (of certificates)”, not “automatic update”. This doesn’t require anything; you follow the steps and you get it.

**Comment by dor-cyolo** [comment]
> The following worked for me on Ubuntu 18.04 which comes with Python 3.6
> 
> ```
> # install system pip if not already (usually not installed)
> sudo apt install python3-pip
> 
> pip3 install certbot-dns-route53
> ```



Eventually, after everything I saw in so many groups and talks, this is what has worked for me - 

```
          sudo add-apt-repository ppa:certbot/certbot
          sudo apt-get install python3-certbot-apache
          sudo apt install python3-certbot-dns-route53
```

Otherwise, you encounter in many many conflicts between apt and pip packages.

**Comment by rotorboy** [comment]
I was able to get it to work with just two steps:

sudo add-apt-repository ppa:certbot/certbot
sudo apt install python3-certbot-dns-route53
Didnt need:
sudo apt-get install python3-certbot-apache

**Comment by namedgraph** [comment]
How about Amazon Linux? It doesn't use the `apt` package manager, but `yum` instead.

**Comment by santosh** [comment]
On Amazon Linux 2. The package is `python-certbot-dns-route53`.

Please note that at the time of writing this, Amazon Linux deals with Python 2 only. So the command would be 
```
sudo yum install python-certbot-dns-route53
```

/cc @namedgraph

**Comment by obonyojimmy** [comment]
@namedgraph you can also enable epel repos and install it like 

```
sudo amazon-linux-extras install epel -y
yum-config-manager --enable epel*
yum -y install python3
pip install -U --upgrade --ignore-installed certbot
pip install -U --upgrade --ignore-installed certbot-dns-route53
```
works in elastic-beanstalk configs !

**Comment by zaiddabaeen** [comment]
Note if you're installing using `snap`, then those are the steps as taken from certbot.eff.org:

```
sudo snap install --classic certbot
sudo ln -s /snap/bin/certbot /usr/bin/certbot
sudo snap set certbot trust-plugin-with-root=ok
sudo snap install certbot-dns-route53
```
