### ISSUE TITLE
Produce python patch to make python-acme 0.4.1 compatible with 'adding-random-entries-to-the-directory'

### ISSUE THREAD

**Issue by evilaliv3** [certbot/certbot#4877]
The addition  as by is making incompatible python-acme 0.4.1 with any ubuntu/debian distribution that is still offering it as official package.

https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417

this include making impossible to use python-acme on ubuntu-trusty, ubuntu-xenial, debian-jessie, debian-stretch that are the long term support platforms fro Ubuntu and Debian.

This ticket is to propose to produce a patch to make python-acme compatible with 'adding-random-entries-to-the-directory' addition to lets'encrypt spec.

**Comment by evilaliv3** [comment]
On GlobaLeaks we just applied this patch that is allowing to put working the minimal implementation of let'encrypt we made: https://github.com/globaleaks/GlobaLeaks/blob/5e986768aef8f2b5280c5dcd435b5a413d6a58bd/backend/globaleaks/utils/letsencrypt.py

**Comment by bmw** [comment]
I believe we fixed this in our repo with #2963 in May of last year. This fix was included in our 0.6.0 release in the same month. The only distribution that I'm aware of that is still affected by this is Ubuntu 16.04 Xenial. On Xenial, we do not recommend people install the stale `letsencrypt` packages and instead should [use our PPA](https://certbot.eff.org/#ubuntuxenial-other). With that said, we're currently actively [working with Ubuntu maintainers](https://bugs.launchpad.net/ubuntu/+source/python-letsencrypt/+bug/1640978) to provide a newer version in Xenial and have #3708 in our repo to track this issue.

Since we have #3708 to track updating Xenial and it is the only distribution I'm aware of that is affected, I believe this issue can be closed. If I missed something, please comment and I'll reopen.
