### ISSUE TITLE
I have deleted certbot-auto and certbot files and now i can't recreate certificates

### ISSUE THREAD

**Issue by alain12345** [certbot/certbot#4890]
## My operating system is (include version):
Debian 7.10 (Wheezy)
Apache/2.2.22 

I installed Certbot with certbot-auto to genrate one certificate for two domains which are on the same serveur. But i got an inexpected redirection from my-domain1.fr to my-domain2.fr ??!! :/
So, after a lot of time i decided to delete certbot files... in order to restart from the beginning...

## I ran this command and it produced this output:
I ran:  ./certbot-auto

and got: Error while running apache2ctl configtest.
Action 'configtest' failed.
The apache error log may have more information.

syntax error on line 46 of /etc.apache2/sites-enabled/domain-name.backup:
SSLCertificationFile: file '/etc/letsencrypt/live/domain-name.fr/cert.pem' does not exist or is empty

## Certbot's behavior differed from what I expected because:
I probably shouldn't have to delete cerbot-auto files

Thank you for your time guys.
I think it's obvious but i'm a noob with shell and certificates, this was my first attempt.

**Comment by SwartzCr** [comment]
No worries - I think I understand what is going wrong!
So when you run certbot it makes a directory at `/etc/letsencrypt/` which stores all of your certificate files.
You deleted that directory but your apache config file still has a refernce to it. So when certbot first tries to do anything it checks that your apache config file is valid, it then notices that it's making reference to a directory that doesn't exist and decides that it doesn't want to do anything until you have a valid apache config.
I'd delete the lines referencing your ssl certs from your apache config file and run the whole process again, especially since it sounds like you deleted your previously generated certificates.
Those config files should live at `/etc/apache2/sites-available` and will likely by symbolically linked into `/etc/apache2/sites-enabled`.
In the future if you're having weird redirect issues it's likely due to something in one of your apache configuration files rather than with your lets encrypt certificates.
Let me know if that helps!

**Comment by SwartzCr** [comment]
@alain12345 any luck?

**Comment by alain12345** [comment]
Hi @SwartzCr !
First I thank you for your post. 
I have succeed in resolving my problem few days after my post. 

You are right, it was exactly the problem I met: 
My  apache config file still had a reference to some deleted directories.
So I have rebuilded my folders tree and then updated my apache config.
Now it's fine my ssl certificate works fine on my two domains !

Thx again for your time !
