### ISSUE TITLE
certbot can't renew with DNS challenges

### ISSUE THREAD

**Issue by chrylis** [certbot/certbot#4925]
I'm using certbot 0.16.0 on Arch (upgraded from 0.12.0 because of this problem, which is still there).

I administer a TLD with a number of hostnames, many of which aren't live at any given time and which can't trivially be given distinct challenge texts (they're staging containers for a blue-green CD pipeline that's public-facing). In order to generate certificates, I need to use DNS challenges. However, the `renew` command hard-forces noninteractive mode (`cli.py:561`), with _absolutely no way_ to override it. Since DNS challenges _require_ interactive mode (and I'm manually updating the TXT records anyway), there's simply no way to renew the certificates.

I commented out line 561 with no obvious deleterious effects; the interactive challenge protocol went through normally, and I got a renewed certificate.

This is a nasty gotcha with no clear rationale and no clear workaround. My proposed resolution is to simply drop the restrictions on the `renew` subcommand.

**Comment by SwartzCr** [comment]
Hmm this does seem true.
On recommendation would be to use a DNS plug-in if possible so that you don't need to manually manage the DNS challenge. If this isn't possible, my best bad advice would be to make a renewal `--pre-hook` that blocks on user input, do allow you to update your DNS. This might not work if you're doing the challenges for multiple renewals at once. So I'm curious if @bmw has a better proposed solution (we might be able to do a bug fix which allows for a flag to cut out `cli.py:561` on `--force-interactive`)

We may also want to rework the docs section on this to stop recommending -n since it's no longer necessary: https://certbot.eff.org/docs/using.html#renewing-certificates

**Comment by bmw** [comment]
The reason the `renew` subcommand is strictly non-interactive is largely historical. We also expect/want people to automate certificate renewal wherever possible though. Due to the otherwise largely automated nature of Certbot and Let's Encrypt and the short 3 month certificate lifetimes, making renewal automated makes using Certbot much less error prone and easy to use.

With that said, we can potentially look into allowing interactivity with `renew` (through something like the `--force-interactive` flag as Noah suggested), but I have a few options for you that might resolve this for you:

1. Ideally, you can use [manual hooks](https://certbot.eff.org/docs/using.html#hooks) to automate renewal for you. This allows you to execute arbitrary commands to set up and clean up the challenge. Certbot sets environment variables with all the information needed to perform the challenge.
2. If the above option doesn't work, you can use `certbot certonly` (or `certbot run` if you're also using an [installer](https://certbot.eff.org/docs/using.html#getting-certificates-and-choosing-plugins) like our Apache or Nginx plugins). How exactly you should use this depends on your configuration and workflow. You can use the `--cert-name` flag to specify which certificate to renew. The name you'd use here is the name of the directory in `/etc/letsencrypt/live` containing the certificate. Any questions that Certbot asks you can be answered on the command line. For example, if your certificate is not close to expiration, Certbot will ask you if you want to exit or renew the cert anyway. You can choose between these options with the `--keep` or `--force-renewal` flags respectively.

@SwartzCr, I don't think this requires a bug fix release as this has always been the behavior of `certbot renew`. We can consider allowing interactivity in the future though if my suggestions above don't solve the problem.

> We may also want to rework the docs section on this to stop recommending -n since it's no longer necessary: https://certbot.eff.org/docs/using.html#renewing-certificates

I don't think we recommend `-n` for `renew`. We do if you're renewing your cert with `certonly` though.

**Comment by SwartzCr** [comment]
I didn't suggest a bug fix release, just merely a bug fix pr :)

**Comment by pos42** [comment]
What is the status of this? I have the very same problem

**Comment by bmw** [comment]
@pos42, do neither of the suggestions I provided [here](https://github.com/certbot/certbot/issues/4925#issuecomment-315250785) work for you?

**Comment by pos42** [comment]
@bmw 

I have tried hooks to restart a service. That works well. But  If I should write my own code to make an interactive process to be non interactive, I will probably which to another software than certbot... I thought easy non interactive automation was an important development driver when the certs are 3 months only.

This works with success, but is interactive which I do not want...
certbot --manual certonly --dry-run --agree-tos --preferred-challenges=dns -d <FQDN1> -d <FQDN2> -d <FQDN3> 

If I skip "-manual" I have to use apache or nginx plugins, or the dns challenge does not work.

I am relatively new to certbot and have probably missed something obvious. But as far as I can see it is not possible to do non interactive renewal with a dns challenge...


But If it is possible... , please enlighten me

**Comment by bmw** [comment]
Automatic renewals is a very important part to using Certbot and Let's Encrypt as I said above in the response to the request to make `certbot renew` a manual process. Unfortunately, the complexity here comes from there not being a standard protocol for updating DNS. Every DNS provider has their own protocol, so Certbot has to write code for each provider in order to automate this type of challenge. We've done some of this work and will continue to do more in the future, but the process certainly isn't trivial.

We have code to automate DNS challenges for Cloudflare, CloudXNS, DigitalOcean, DNSimple, DNS Made Easy, Google Cloud DNS, LuaDNS, NSOne, Amazon Route53, or and providers supporting [RFC 2136](https://tools.ietf.org/html/rfc2136). Unfortunately, Arch Linux is the only Linux distro to have packaged these parts of Certbot, but we're actively working on changing that.

If you must use the DNS challenge but you're not using Arch Linux and are opposed to writing your own script to automate it, I think another ACME client is a better choice for you at this time. Different clients have prioritized different things and if another client makes it easier to secure your server, you should use it! While we want to make Certbot better to support more people, you should probably use what works best for you right now. If you're looking around for another client to automate DNS challenges, I'd recommend [acme.sh](https://github.com/Neilpang/acme.sh).

**Comment by jult** [comment]
I managed to renew automatically just fine, with some tweaking.
https://gist.github.com/jult/e4dd064e3988aa111ea2194b05bc69f5

**Comment by minfrin** [comment]
I've just hit this bug.

Am I right in understanding that there is no procedure to manually renew a DNS challenge certificate?

Obviously there is a mechanism to manually create a DNS challenge certificate, the lack of the ability to renew seems to me that this feature is half finished?

Am I missing something, all my googling finds bug reports but no concrete resolutions.

**Comment by pos42** [comment]
For me I see no other option than running the following to renew...
`certbot --manual certonly  --agree-tos --preferred-challenges=dns -d DOM1 -d DOM2 -d DOM3 -d DOM4`

and while answering questions to the above, add DNS challenges in the zone file.

A feature that could to this automatic and also a hook script to update the zonefiles would be great.

/Peo

**Comment by bmw** [comment]
@pos42, I think using `--cert-name` as described at https://github.com/certbot/certbot/issues/4925#issuecomment-315250785 allows you to stop specifying domains if you want.

If you're asking for the ability to register a hook with Certbot to perform the DNS challenge, that exists. It's `--manual-auth-hook` which I described in the same post as `--cert-name`.

If you want us to write the hook for you, I hope my explanation at https://github.com/certbot/certbot/issues/4925#issuecomment-338843009 makes sense for why this is hard. With that said, we do have plugins for 14 DNS APIs ourselves and others have written 3rd party plugins for the same purpose. Who is your DNS provider?

**Comment by pos42** [comment]
After my certbot --manual command above I simply with a script copy the certs, chmod them and restart the service.

I would love to do all of it automatic...

I am my own DNS provider. So the std usable stuff is to use "nsupdate" command with a key or over SSH to alter the dns zone verification. As nsupdate is standard in bind I am surprised it is not supported. Of course it requires a key setup to be used between nsupdate client and bind, but that is a very simple prerequisite if you own the dns.

I simply just want to be able to renew on any host and not to be dependant on Apache or nginx.

Any suggestions very much appreciated. 

/Peo

**Comment by bmw** [comment]
Ah! We have a [certbot-dns-rfc2136](https://certbot-dns-rfc2136.readthedocs.io/en/latest/) plugin which uses the same protocol as `nsupdate` to automate DNS challenges. You can enter your OS and webserver in the dropdown menus at https://certbot.eff.org/ to learn the best way to install it on your system.

**Comment by pos42** [comment]
That seems to be what I was looking for... I will look into that a s a p. I assume it will solve the manual edit of the DNS data. Will it run totally non-interactive?

**Comment by bmw** [comment]
Yep! You'll have to install it, set up credentials using the links in my previous post, and run `certbot certonly --force-renewal ...` with it once so it's used to obtain a certificate but after that, all DNS changes should happen completely non-interactively. You can (and should) test it after doing this by running `certbot renew --dry-run`.

**Comment by bmw** [comment]
I believe this issue has been resolved so I'm closing it. If you think I missed something, please add a comment or open a new issue.
