### ISSUE TITLE
UBUNTU apt not upgraded certbot

### ISSUE THREAD

**Issue by ppKrauss** [certbot/certbot#4964]
## My operating system is: UBUNTU 16 LTS (xenial)
`certbot --version` = 0.14.2

## I installed Certbot with:
Standard apt install instructions.

## I ran this command and it produced this output:
... after `apt update` and general upgrade... used `sudo apt-get install python-certbot-nginx`

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-certbot-nginx is already the newest version (0.14.2-1+certbot+16.041).
The following packages were automatically installed and are no longer required:
  libssl1.0.2 linux-headers-4.4.0-78 linux-headers-4.4.0-78-generic linux-headers-4.4.0-79 linux-headers-4.4.0-79-generic
  linux-headers-4.4.0-81 linux-headers-4.4.0-81-generic linux-image-4.4.0-78-generic linux-image-4.4.0-79-generic
  linux-image-4.4.0-81-generic php7.0-cli php7.0-fpm php7.0-json php7.0-opcache php7.0-readline zlib1g-dev
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```

## Certbot's behavior differed from what I expected because:
Need version 0.16! not 0.14.

## Here is a Certbot log showing the issue (if available):
stay `certbot --version` = 0.14.2

**Comment by ppKrauss** [comment]
After `apt purge` and repeating https://certbot.eff.org/#ubuntuxenial-nginx   same result

**Comment by ppKrauss** [comment]
PS: now nothing is working!!! Befor I was using with sucess, need only new version... The purge/reinstall **DESTROY ALL**, how to back my service!

```
certbot --nginx

Saving debug log to /var/log/letsencrypt/letsencrypt.log
Error while running nginx -c /etc/nginx/nginx.conf -t.

nginx: [emerg] open() "/etc/letsencrypt/options-ssl-nginx.conf" failed (2: No such file or directory) in /etc/nginx/snippets/ssl-oficial.news.conf:11
nginx: configuration file /etc/nginx/nginx.conf test failed

The nginx plugin is not working; there may be problems with your existing configuration.
The error was: MisconfigurationError('Error while running nginx -c /etc/nginx/nginx.conf -t.\n\nnginx: [emerg] open() "/etc/letsencrypt/options-ssl-nginx.conf" failed (2: No such file or directory) in /etc/nginx/snippets/ssl-oficial.news.conf:11\nnginx: configuration file /etc/nginx/nginx.conf test failed\n',)
```

**Comment by SwartzCr** [comment]
Hi @ppKrauss - I think I understand what happened
First off, the version of certbot that is packaged by Ubuntu is 0.14.2, I'd recommend keeping an eye on the Ubuntu PPA for version to see when it changes: https://launchpad.net/~certbot/+archive/ubuntu/certbot
At some point Certbot will become officially packaged in Ubuntu and might be version 0.16.0 or higher, maybe @bmw knows when that's likely to happen.
As far as certbot not working, I think when you purged certbot you removed the folders in the /etc/letsencrypt directory which stored the certificates referenced in your `/etc/nginx/snippets/ssl-MYSITE.conf`. Since it was pointing at a certificate which you had deleted, it was causing a nginx MisconfigurationError and preventing nginx from starting.
I'd suggest that you get new certificates for that domain, and in the future try not to delete your certificate files.

**Comment by bmw** [comment]
> At some point Certbot will become officially packaged in Ubuntu and might be version 0.16.0 or higher, maybe @bmw knows when that's likely to happen.

Updates to the Certbot packages in Ubuntu should happen in the next couple weeks, however, the currently proposed update will only be to version 0.14.1.

**Comment by SwartzCr** [comment]
Certbot should now be version 0.17.0 in Ubuntu, is this fixed for you @ppKrauss ?

**Comment by ppKrauss** [comment]
I used, just  now, `apt install python-certbot-nginx` and... Yes, `certbot --version`  0.17.0! Thanks @SwartzCr

**Comment by SwartzCr** [comment]
Great! I will close this issue, feel welcome to open new ones if you have more issues
