### ISSUE TITLE
Expiration notice after renewing with allow-subset-of-names

### ISSUE THREAD

**Issue by edwinm** [certbot/certbot#5006]
## My operating system is (include version):
Ubuntu 16.04.2 LTS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot 0.14.2

## I ran this command:
sudo certbot renew --allow-subset-of-names

## Certbot's behavior differed from what I expected because:
I ran the command above a week ago and I'm still receiving (two) "Let's Encrypt certificate expiration notice ..." e-mails.

Both `sudo certbot certificates` and the information in the browser show the certificates are renewed.

**Comment by SwartzCr** [comment]
The reason why this is happening is that when you renew a certificate you are actually issuing an entirely new one. If it has different domain names listed than the original certificate (like in your case) then the Let's Encrypt CA doesn't know that they're actually certificates that Certbot views as the same. 
This is why you got an expiration notice, because the initial certificates are expiring, and Let's Encrypt doesn't see newer versions of them (instead you have these new different certificates).
I don't think we can fix this in Certbot so I'm going to close this issue, but if you want more insight on this I'd suggest you post on community.letsencrypt.org
