### ISSUE TITLE
Can't install on Strato.com - SunOS 5.10 

### ISSUE THREAD

**Issue by sorinmustaca** [certbot/certbot#5023]
Hi,
I have an account at Strato.com (Germany).
I have an ssh account on their system, but it is different than all those documented.

## My operating system is (include version):
SunOS gaffer 5.10 Generic_150401-49 i86pc i386 i86pc Solaris

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

wget

## I ran this command and it produced this output:
 ./certbot-auto --apache
./certbot-auto: syntax error at line 32: `BASENAME=$' unexpected

## Certbot's behavior differed from what I expected because:

It doesn't work

**Comment by SwartzCr** [comment]
That's strange, that argument is meant to know whether to call the script `certbot-auto` or `letsencrypt-auto`, but it seems to not be sure how to get that. This is probably because we don't support SunOS, and it handles variables differently than the OS's that we do support. While you could probably get past this error by setting the basename to something arbitrary, certbot-auto will almost definitely not work on your machine.
Your best bet would be to try to run it from inside a docker container, or something else that will let you use an OS that certbot supports

**Comment by drscream** [comment]
The point is `$()` is not available in a regular `sh` only in `bash` and similar shells. An option would be to run it with `bash certbot-auto` to be sure it's executed by `bash`

**Comment by sorinmustaca** [comment]
I tried that too:

bash-4.2$ ./certbot-auto
./certbot-auto: syntax error at line 32: `BASENAME=$' unexpected
bash-4.2$

The script is created to be run under /bin/sh.
I changed that in the script and this is the next step:

$ ./certbot-auto
"sudo" is not available, will use "su" for installation steps...
Sorry, I don't know how to bootstrap Certbot on your operating system!

You will need to install OS dependencies, configure virtualenv, and run 
pip install manually.
Please see 
https://letsencrypt.readthedocs.org/en/latest/contributing.html#prerequisites
for more info.


Well, I guess that's it... :)
I don't have time right now to figure out what is needed.
And I don't have anyway access on that machine to any of the tools 
mentioned, nor do I have sudo or su.

**Comment by SwartzCr** [comment]
Unfortunately even if you got sudo working, it still wouldn't know how to install your missing dependencies. I'm going to close this ticket, since we don't have plans to support SunOS - hopefully you'll find a way to get a certificate
