### ISSUE TITLE
Explain authentication requirements

### ISSUE THREAD

**Issue by OlafvdSpek** [certbot/certbot#5032]
It's unclear what certbot certonly authentication choices do and require. I think webroot is recommended and standalone is problematic as an existing web server is likely to be running.
But neither the docs nor the certbot output indicate this properly.
This is a request to improve both.

https://github.com/certbot/certbot/issues/4986

@SwartzCr

**Comment by SwartzCr** [comment]
@pconrad-fb this seems like exactly the kind of thing I'd like to see for documentation of challenges
@schoen how would you feel about writing something like this for all challenges?

**Comment by schoen** [comment]
I've forgotten the status of our various plans around this topic, but right now we have both

https://certbot.eff.org/docs/using.html#getting-certificates-and-choosing-plugins

and

https://certbot.eff.org/docs/challenges.html

(the latter of which is possibly not linked from anywhere).

What should we do with these, and what more should they cover?

**Comment by OlafvdSpek** [comment]
So I've read https://certbot.eff.org/docs/using.html#getting-certificates-and-choosing-plugins before.
The right side of the plugins table is cut off and requires horizontal scrolling to view, IMO this is bad usability.
And indeed, only today I noticed the last column mentions what ports each plugin uses.

The Webroot section below does not mention port 80 being used.. It also doesn't mention Webroot is recommended over Standalone.

The Standalone section does not mention (potential) problems with automatic renewal due to the ports being used by the real web server.

**Comment by pconrad-fb** [comment]
I think these whole sections need to be rethought. Fortunately, they have all the info (at least I think so). I'll take a look at them.

**Comment by pconrad-fb** [comment]
The reason the table needs to scroll is that the <div> tag it sits in is limited to, I think, 768 pixels. This seems like an old-school measurement in today's high-res display environment. Maybe either the table can be similarly restricted, or the "document" <div> can be increased to 1200?

**Comment by pconrad-fb** [comment]
I've spent a little time today looking at using.rst and challenges.rst with an eye toward eliminating overlap and redundancy. The first thing that occurs to me is that using.rst is, well... monolithic. It's the entire user guide.

I think we should break it up (for now, keeping the user experience mostly the same) to get better chunk sizes, so to speak. Then we can make the chunks a bit more discrete. Actually, challenges.rst is not a bad example, and if it were a sub-document of the user guide, it could be made to fit quite nicely.

Once we break this into chunks, we can decide what experience is important. Right now, everything is a bit structural—talking about plug-ins, for example—and it could be moved in the direction of being more goal/task oriented. I think if there's a way to take some common scenarios and make them into tutorials, it might help novices who have easy (but hard) problems to solve. We could do a little content reuse if we had to, or we could just say "Step one, look at this subpage, step two, look at this one" to create a guide to using Apache with the TLS-SNI challenge for authentication. 

I'm still looking at the structure, but I think we should have sections about Authentication and Certificate Installation (we talk about them, but they'd be hard to find for someone who doesn't know the docs).

Any feedback on all this? It's potentially major, because it will mean a proliferation of .rst files that will then need to be plugged into the doc structure. What do you think?

**Comment by SwartzCr** [comment]
I'm fine with splitting things up
I'd also be fine with making tutorials, that then link to other parts of the documentation (this should be easy). I often want to link to things in github issues, so having topics separated from tutorials is likely good for me.
I'm generally fine with proliferating .rst files, especially if it makes navigating the documentation easier

**Comment by pconrad-fb** [comment]
Okay. Let me see what I can do here. Worst case scenario, you can reject my PR. :P

**Comment by adferrand** [comment]
The documentation has been improved greatly since this issue was created, with detailed explanation to choose the correct plugin. I think it is not relevant anymore. If not, do not hesitate to reopen an issue with updated info about its context.
