### ISSUE TITLE
failed to renew certificates, but dry-run success

### ISSUE THREAD

**Issue by CordlessWool** [certbot/certbot#5040]
## My operating system is (include version):
debian:8.9 but I am running the docker container

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
docker container

## I ran this command and it produced this output:
docker run -t --rm \
 -v "/etc/letsencrypt:/etc/letsencrypt" \
 -v "/tmp:/var/www" \
 -v "/var/lib/letsencrypt:/var/lib/letsencrypt" \
 certbot/certbot:latest renew --webroot --webroot-path /var/www --rsa-key-size 4096

Attempting to renew cert (sub.domain.tld) from /etc/letsencrypt/renewal/kanban.dropanote.de.conf produced an unexpected error: Failed authorization procedure. sub.domain.tld (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://sub.domain.tld/.well-known/acme-challenge/zOq3BHOb7KqO6WALfFalHWoGmeUTe2ld5UY1-N5f3M0: Timeout. Skipping.d

## Certbot's behavior differed from what I expected because:
If I run it with --dry-run it says everything is ok. On a other server it also works. The different between the two server is that one have a fix IP. On the server it fails there is a cname entry to a dyndns url

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
location /.well-known/acme-challenge {
       root /tmp;
    }

**Comment by creepersbane** [comment]
The domain name seems to be pointing to an invalid IP address. Make sure your domain is pointing to the correct address.

The current IP registered with the domain is 62.157.58.48

**Comment by CordlessWool** [comment]
But why dry-run is working and it does not work with normal request? The service behind the domain is not running right now, only nginx is running. I also try to get the certs with standalone service and it works without this domain and one other. All other other domains get a new one. It is the same connection for all sub domains. CName points to an dyndns address.

**Comment by SwartzCr** [comment]
Yeah, it might be a timeout issue, maybe @jsha knows what one can do about this?

**Comment by cpu** [comment]
@SwartzCr Jsha is on vacation for a few more days.

> But why dry-run is working and it does not work with normal request?

Is it possible you had tried issuance with the staging server within the past 30 days when the server was configured correctly? If so then I suspect you created a valid authorization in the staging environment that's being re-used now when you try to issue again because it hasn't expired or been deactivated. Likely no such cached authorization exists in the production server and so the current misconfiguration prevented issuance there.

**Comment by CordlessWool** [comment]
ok I am not sure what you mean with staging server. Which staging server and how could I had connect to it? 

I tring it again some minutes before. First I run --dry-run and in second without. Now it works. The only change to the last run was that I start the service behind the url again. But the nginx server is just running before so that should not make a different? There was also an second url was not renewal the last time, but also now and I did not change anything at it.

**Comment by SwartzCr** [comment]
Okay - I think this is resolved so I am going to close the issue.
@CordlessWool let us know if you're still having issues and we can work to fix them.
Let's Encrypt provides access to two different servers, one which generates valid certificates, and another called the 'staging server' which can be used to test certificate generation, but the certificates that it provides are not valid in web browsers. People use the staging certificate for testing to avoid being rate limited by the normal server.
It seems that you created an authorization for the staging certificate which was being reused instead of generating a new one for the main server. It seems that that authorization has been overwritten now, since your renewals are working. I wouldn't worry about this anymore since this is a somewhat rare issue.

**Comment by rvanzon** [comment]
Sorry to comment on this closed issue, but I have the same problem:

This works:
```sudo certbot certonly -w ../root/DOMAINNAME -d DOMAINNAME --webroot --dry-run```

Also staging works
```sudo certbot certonly -w ../root/DOMAINNAME -d DOMAINNAME--webroot  --break-my-certs --test-cert```

Any ideas?

**Comment by SwartzCr** [comment]
If you try a different authorization method or change the domains that you're querying for it should generate you a new authorization and then succeed. Currently there's no way to manually remove authz's #4945
So you'll have to wait for that one to expire or do something to create a new one for the proper server.

**Comment by rvanzon** [comment]
I tried all ways without luck :( On production I use "certbot --nginx" and it always works. But on MacOS (my development environment) I face this problem some times.

Because this is on my development-machine I decided to use the staging certificate. The advantage of this is also that it doesn't expire in 20 years.

FYI: I generated a staging-certificate and added the fullchain.pem to the login-keychain (using MacOS KeyChain Access). Then set it to "Always trust".
