### ISSUE TITLE
Renew not generating privkey cert

### ISSUE THREAD

**Issue by REPTILEHAUS** [certbot/certbot#5041]
## My operating system is (include version):
debian jessie

## I ran this command and it produced this output:
sudo certbot certonly --webroot --dry-run -w /var/www -d example.com -d www.example.com

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Starting new HTTPS connection (1): acme-staging.api.letsencrypt.org
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for example.com
http-01 challenge for www.example.com
Using the webroot path /var/www for all unmatched domains.
Waiting for verification...
Cleaning up challenges
Generating key (2048 bits): /etc/letsencrypt/keys/0004_key-certbot.pem
Creating CSR: /etc/letsencrypt/csr/0004_csr-certbot.pem

IMPORTANT NOTES:
 - The dry run was successful.
```

## Certbot's behavior differed from what I expected because:
generating privkey cert

**Comment by SwartzCr** [comment]
It's important to know that --dry-run is a way to test that renewal works, and is not an actual renewal. For example it doesn't actually save these certificates, and gets them from our staging server, which is not trusted by browsers.
You may want to remove the --dry-run flag from your command, so that you do an actual renewal (now that it seems like it's successful)
You can learn more about renewal here: https://certbot.eff.org/docs/using.html#renewing-certificates
