### ISSUE TITLE
If nginx site file refers to cert that certbot hasn't created, certbot won't create it

### ISSUE THREAD

**Issue by JeffAbrahamson** [certbot/certbot#5047]
## My operating system is (include version):

ubuntu 16.04
Linux nantes-1 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

apt-get install

## I ran this command (with my real domain name) and it produced this output:

    ╭╴ (master=)╶╮
    ╰ [T] jeff@nantes-1:p27 $ certbot --version
    certbot 0.17.0
    ╭╴ (master=)╶╮
    ╰ [T] jeff@nantes-1:p27 $ 

    ╭╴ (master=)╶╮
    ╰ [T] jeff@nantes-1:p27 $ sudo certbot --nginx -d example.com -d www.example.com
    Saving debug log to /var/log/letsencrypt/letsencrypt.log
    2017/08/24 19:39:41 [emerg] 1313#1313: BIO_new_file("/etc/letsencrypt/live/example.com/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/example.com/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
    Error while running nginx -c /etc/nginx/nginx.conf -t.

    nginx: [emerg] BIO_new_file("/etc/letsencrypt/live/example.com/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/example.com/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
    nginx: configuration file /etc/nginx/nginx.conf test failed

    The nginx plugin is not working; there may be problems with your existing configuration.
    The error was: MisconfigurationError('Error while running nginx -c /etc/nginx/nginx.conf -t.\n\nnginx: [emerg] BIO_new_file("/etc/letsencrypt/live/example.com/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen(\'/etc/letsencrypt/live/example.com/fullchain.pem\',\'r\') error:2006D080:BIO routines:BIO_new_file:no such file)\nnginx: configuration file /etc/nginx/nginx.conf test failed\n',)
    ╭╴ (master=)╶╮
    ╰ 1,[T] jeff@nantes-1:p27 $ 

Note that the nginx site file already had a reference to the not-yet-existing certs.

## Certbot's behavior differed from what I expected because:

I expected certbot to see that the certs didn't exist but that the paths were precisely the paths that certbot would have tried to create.  And so I expected certbot to create the certs.

This comes up when re-installing a host, since I'd like the git-controlled site files to be the same as what lives in production.  In other words, I've copied the certbot-modified site files to git.

**Comment by SwartzCr** [comment]
Hi!
I think the problem is a little different . It's not that certbot is seeing a cert location and aborting so as not to overwrite it (though it might do that) it's failing when it checks the validity of your nginx config file. The -t flag checks the validity of the file references https://nginx.org/en/docs/switches.html
Since it's also checking that files referenced in that config file exist, it's aborting because the referenced cert doesn't exist.
As far as shipping the same configs to all of your servers, why can you not just leave the cert path blank, and let certbot fill it in?

**Comment by JeffAbrahamson** [comment]
That mechanism (that certbot is starting by first validating that the nginx files parse) sounds quite believable.

The issue is that I want to have my nginx config in git.  But that means that if I change my nginx config and git update, I've either dropped out the certs or I need certbot to add them back each time.  As long as the certs exist in the file system, this isn't a problem.  It is a problem, though, when I use my script to bring up a new host.

I don't bring up new hosts too often -- in my case this is a personal site.  But in my professional life I'd use something like puppet, and then I'd be faced with puppet wanting to change an nginx config file because it's not the same as the one installed.

**Comment by SwartzCr** [comment]
Ah, so you're saying that if the machine changes the nginx config then Puppet will complain and try to change it back?
That's upsetting, since starting it with a reference to a non-existent cert will definitely prevent certbot from working.
I don't think there's a direct way around this, except to use a script the first time that certbot runs to edit that file, and then let certbot run. Do you think you could write a wrapper script that would allow certbot to operate without puppet having an issue?

**Comment by JeffAbrahamson** [comment]
I played with this a bit, but then realised that there are some quite good efforts under way to sort this directly in tools such as puppet ([example](https://github.com/voxpupuli/puppet-letsencrypt)).  And in the manual case, it's easy enough to get around by a quick `grep -v` to drop the cerbot lines when doing the first certbot invocation.

So I think this can be closed.  The more important cases seem to be handling themselves, and the less important cases are easy enough to work around.
