### ISSUE TITLE
Automatically fall back to certonly

### ISSUE THREAD

**Issue by OlafvdSpek** [certbot/certbot#5051]
```
# certbot
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Certbot doesn't know how to automatically configure the web server on this system. However, it can still get a certificate for you. Please run "certbot certonly" to do so. You'll need to manually configure your web server to use the resulting certificate.
```

IMO it'd be simpler if certbot automatically falls back to certonly. The user can always cancel if certonly isn't what they wanted.

**Comment by SwartzCr** [comment]
Hi @OlafvdSpek!
What system are you running certbot on? And what webserver do you have installed? Are there more webserver errors in the logs?
There are a few reasons why we wouldn't default to certonly. In this case it's because certonly would invoke --standalone, which would spin up a web server on your computer. This would try to bind to port 443. But we've already detected that you have a webserver running, which would prevent certbot from binding to 443. Which means that it'd likely fail. Alternately we could use the webroot authenticator, but again we'd need to know that your webserver is configured to serve files in that way, in which case I think we'd want to know that you've opted into that.

**Comment by OlafvdSpek** [comment]
Nginx @ Debian 9 again. ;) 

>  In this case it's because certonly would invoke --standalone

Wouldn't it first pop the question to allow the choice between webroot and standalone?

**Comment by SwartzCr** [comment]
Ah I see, so when it fails at doing a verification via apache, it should fall back to a prompt for standalone vs webroot with a warning saying that it will not install the certificate?
That almost makes sense to me, except that this might cause people who would prefer it to use the apache installer to have to manually install their certificates. Prompting the user allows them to make the choice between fixing their apache or running it again in a different mode.
But I'm curious how @ohemorange and @bmw feel about this feature request.

**Comment by bmw** [comment]
We've had people run with `certbot certonly` and think they've done everything they needed to do so I'm not sure we want to automatically fall back to this behavior. In fact, we've often regretted adding automated behavior like this such as making the `run` subcommand the default (which is the behavior you're seeing by just running `certbot` without a subcommand) or automatically selecting a plugin when it's the only one available.

I'd be happy to make improvements to this error message if there's something with its wording you think we can improve, but I don't think we should introduce the possibility of a successful `certbot run` command not installing your cert.

**Comment by adferrand** [comment]
Fallback will not be implemented, but the original error message is still here. However, this issue has not been updated for a long time. So I assume it is not relevant anymore. If not, do not hesitate to reopen an issue with updated info about its context.
