### ISSUE TITLE
Error Creating Certificate for Cloudfront Distribution that points to S3 Bucket (static site)

### ISSUE THREAD

**Issue by vladejs** [certbot/certbot#5078]
## My operating system is (include version):
Debian (Deepin)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
pip, certbot-auto

## I ran this command and it produced this output:
```
AWS_ACCESS_KEY_ID="AccessKey"  \
AWS_SECRET_ACCESS_KEY="SecretAKey" \
certbot --agree-tos -a certbot-s3front:auth \
--certbot-s3front:auth-s3-bucket staticbokito \
-i certbot-s3front:installer \
--certbot-s3front:installer-cf-distribution-id E4BQ4258M4M6 \
-d staticbokito.s3-website.us-east-2.amazonaws.com
```

**Output**
`Error creating new authz :: Policy forbids issuing for name`

## Certbot's behavior differed from what I expected because:
It didn't generated the certificate

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
[letsencrypt.txt](https://github.com/certbot/certbot/files/1282145/letsencrypt.txt)

**Comment by SwartzCr** [comment]
Unfortunately we cannot issue certificates for amazonaws.com domains due to Let's Encrypt policy, see: https://community.letsencrypt.org/t/policy-forbids-issuing-for-name-on-amazon-ec2-domain/12692/2?u=swartzcr
This is not a certbot problem, but something hard coded into the server software for Let's Encrypt :(
I'm going to close this issue, since it's not fixable on our end, but if you have more questions about this policy I'd recommend that you post on community.letsencrypt.org and ping @cpu there.
