### ISSUE TITLE
Suggesting to add clues about enforce at renew message

### ISSUE THREAD

**Issue by ppKrauss** [certbot/certbot#5099]
At `certbot renew` when "Cert not yet due for renewal" (but --dry-run is fine), add the messagem 
> it is not recommended but you can renew with `--force-renewal`

See typical problem at https://community.letsencrypt.org/t/impossible-renew/41909

User take decision, and need a clue for your options.

**Comment by SwartzCr** [comment]
I think that we should just better explain what `--dry-run` does. I've worked a little bit on documentation for this.
@bmw, what do you think about adding this to the output of `renew`? If you like it maybe @ynasser can do it as part of #5045

**Comment by ppKrauss** [comment]
Hi @SwartzCr, the message must solve the problem that the command not solved.

1. The command `certbot renew` is not "let's try to renew", I used  because I need to renew. So, when the command `certbot renew`  stops to do what it must to do, I need a clue... The software must show a message in respect to user expectative... Must  say something as *"you can renew but not need it. If you really need, please add the option `--force-renewal`"*<br/> without this message it will be a software interface bug.

2. The certbot-ecosystem sends to me an e-mail, and the e-mail (see dump below) say to renew (!). So, it is a big contradiction.


-----

Email:
```
Let's Encrypt Expiry Bot <expiry@letsencrypt.org> Unsubscribe
8:17 AM (3 hours ago)

to me 
Hello,

Your certificate (or certificates) for the names listed below will expire in
9 days (on 20 Sep 17 10:59 +0000). Please **make sure to renew**
your certificate before then, or visitors to your website will encounter errors.

```

**Comment by SwartzCr** [comment]
I think in your situation the email from Let's Encrypt references a certificate that you are no longer maintaining, which is why your getting an expiration notice.
If certbot doesn't think your certificate is due for renewal then it is not.
You can force renewal, but first I would check the expiration date on the certificates that you're serving.

**Comment by ppKrauss** [comment]
Hi @SwartzCr , not make sense (or was deleted by force-renew) because I have only one certificate as listed by `certbot certificates`,


```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
-------------------------------------------------------------------------------
Found the following certs:
  Certificate Name: oficial.news
    Domains: oficial.news, api.ok.org.br, baixar.oficial.news, baixar.ok.org.br,...., www.ok.org.br
    Expiry Date: 2017-12-09 15:28:00+00:00 (VALID: 87 days)
    Certificate Path: /etc/letsencrypt/live/oficial.news/fullchain.pem
    Private Key Path: /etc/letsencrypt/live/oficial.news/privkey.pem
```

**Comment by SwartzCr** [comment]
It looks like you might have all of your domains under one certificate now - as long as all of your websites are working I think you're okay

**Comment by ppKrauss** [comment]
Hi @SwartzCr , thanks for all (!). <br/>Yes, certbot is working fine... All the discussion is only about the message... Again: consistency and the need for clues (in respect to user when certbot is frustrating the command expectative)  &nbsp; :-)

**Comment by bmw** [comment]
I don't feel one way or another too strongly, but my preference is to not include output like this. The only reason I can think of where a user should be using `--force-renew` is if they want to change a property of their cert (such as the key size) and don't want to answer the following interactive prompt:
```
What would you like to do?
-------------------------------------------------------------------------------
1: Keep the existing certificate for now
2: Renew & replace the cert (limit ~5 per 7 days)
-------------------------------------------------------------------------------
Select the appropriate number [1-2] then [enter] (press 'c' to cancel):
```
Including `--force-renewal` in standard renewal output suggests this flag to many more people than that.

My personal preference on how to fix this problem is to make the expiration notice sent by Let's Encrypt as clear as possible so users don't think there's a problem with their cert's renewal when there isn't one.

**Comment by SwartzCr** [comment]
@jsha would you be willing to assist with this? We've found that a lot of people are confused by the emails from Let's Encrypt

**Comment by SwartzCr** [comment]
Closing this in favor of the boulder issue
