### ISSUE TITLE
e-mail error, needs LetsEncrypt-server correction of expiration alerts

### ISSUE THREAD

**Issue by ppKrauss** [certbot/certbot#5120]
The command `certbot certificates` (v0.17.0) shows only one certificate, it says
```
...   Found the following certs:
  Certificate Name: oficial.news
    Domains: oficial.news,api.ok.org.br, baixar.oficial.news, baixar.ok.org.br,.....
    Expiry Date: 2017-12-09 15:28:00+00:00 (VALID: 81 days)
    Certificate Path: /etc/letsencrypt/live/oficial.news/fullchain.pem
    Private Key Path: /etc/letsencrypt/live/oficial.news/privkey.pem
```
Say "VALID: 81 days". The e-mail at the same day says other thing (0 days), so is an ERROR and need correction.

--------

Subject *"Let's Encrypt certificate expiration notice for domain "baixar.ok.org.br" (and 20 more)"*

Body:
```
Hello,

Your certificate (or certificates) for the names listed below will expire in
0 days (on 19 Sep 17 19:17 +0000). Please make sure to renew
your certificate before then, or visitors to your website will encounter errors.

baixar.ok.org.br
datasets.ok.org.br
...
```

**Comment by cpu** [comment]
Hi @ppKrauss 

This is a pretty common source of confusion that's surprising at first but makes sense after some explanation about what the Let's Encrypt considers a renewal to be:

Your Certbot issued certificate covers the domains:
> oficial.news,api.ok.org.br, baixar.oficial.news, baixar.ok.org.br,.....

The expiration warning was for a certificate that covers the domains:
> baixar.ok.org.br, datasets.ok.org.br

The Let's Encrypt [documentation for expiration warning emails](https://letsencrypt.org/docs/expiration-emails/) explains why you received this warning message:
> We consider a certificate to be renewed if there is a newer certificate with the exact same set of names, regardless of which account created it. If you’ve issued a new certificate that adds or removes a name relative to your old certificate, you will get expiration email about your old certificate.

This warning was for a different certificate. Your new certificate is for a different set of names and so it isn't a renewal of the old certificate. 

If you aren't using the old certificate you can safely ignore the email.

I hope that makes sense. I'm going to close this issue since it isn't a bug that can be fixed by the Certbot team (the expiration emails come from [Boulder](https://github.com/letsencrypt/boulder), the Let's Encrypt server-side CA).

**Comment by ppKrauss** [comment]
> If you aren't using the old certificate you can safely ignore the email.

Hum... This is not a solution, so **the system have a bug**. I want to report it as a bug.

**Comment by cpu** [comment]
Hi again @ppKrauss,

>  so the system have a bug.

I tried to explain above. The system does not have a bug. If you add or remove names from a certificate you create a second distinct certificate. Unless you renew both the old and new certificates one will generate expiration warnings.

>  I want to report it as a bug.

Certbot isn't the right place to report this bug. [Boulder, the Let's Encrypt server-side CA](https://github.com/letsencrypt/boulder) is what generates the expiration emails. You can report this bug there and we can discuss more if you still believe there is a bug.

**Comment by ppKrauss** [comment]
Hi @cpu, thanks all explanations and discussion.
 
Sorry, it's a "contract context": user contract with `certbot` covers this e-mail message mechanism, so it's actual part of the contract. The certbot user has no choice to change the webservice-supplier, so this webservices are components of the "certbot system".
  
My request for you or the certbot team: can you submit a BUG ALERT to the [Boulder  Let's Encrypt server-side CA](https://github.com/letsencrypt/boulder)?

**Comment by cpu** [comment]
@ppKrauss I opened https://github.com/letsencrypt/boulder/issues/3105 - let's continue to discuss there.

**Comment by ppKrauss** [comment]
Hi @cpu, closing again ;-)  thanks a lot!
