### ISSUE TITLE
Allow removing all contacts in our acme module

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5129]
Related to #3162, our ACME module does not allow the user to remove all contact information from a registration. If the contact field is set to an empty tuple, it is omitted from the request to the ACME server. This is because [omitempty is set to True for the field](https://github.com/certbot/certbot/blob/f6be07da74c664b57ac8c053585f919c79f9af44/acme/acme/messages.py#L250) and an empty tuple is considered empty and omitted.

It's not immediately clear to me what the fix for this is. I think setting `omitempty` to `False` would cause subtle bugs. The behavior we really want is if the caller sets the value to an empty object, it should be included in the request, otherwise, it should excluded.

**Comment by trinopoty** [comment]
I had a got at it and got `Error: urn:ietf:params:acme:error:malformed :: The request message was malformed :: Unable to update account :: empty contact`. Probably the staging server does not support removing contact?

**Comment by trinopoty** [comment]
I believe I have it figured out. However, I added a new option/flag `--remove-email`. Is that acceptable?

**Comment by trinopoty** [comment]
Opened a PR #5899 for this.

**Comment by cpu** [comment]
:wave: :robot:

I believe this is still an issue. Implementing this will unblock a Boulder integration test: https://github.com/letsencrypt/boulder/issues/3114

**Comment by aeturnum** [comment]
I've done some work on this and have something that might work, but there's a series of needed modifications that I'm unsure of how to verify.

First, in order to send an empty set of contacts to the server, we need to change [the contact field of Registration message in acme](https://github.com/certbot/certbot/blob/master/acme/acme/messages.py#L318) to be included when empty. However, this complicates the saving and loading of registration information on disk in a way I don't understand.

The function for saving an account's information to disk will currently [*always* save an empty body](https://github.com/certbot/certbot/blob/master/certbot/certbot/_internal/account.py#L377-L384). This needs to change because `josepy` will expect the contact field in the body when de-serializing it from disk. This can be minimally supported by changing the body arguments to `body={'contact':()}`, however I don't understand why the current function is the way it is. Why not simply use josepy to serialize the body (like we do when loading the objects from disk?). Are there other locations where we hard-code this information? 

I'm also uncertain about how to verify that the server has accepted our update message and removed the users' contact information.

**Comment by alexzorin** [comment]
>First, in order to send an empty set of contacts to the server, we need to change the contact field of Registration message in acme to be included when empty

Thinking out loud:

For the `contact` field, would it be possible to subclass [`jose.Field`](https://josepy.readthedocs.io/en/stable/api/json_util/?highlight=Field#josepy.json_util.Field)? Override its `_empty` method to only treat `None` as an empty value,

That way, an empty list would still be sent in the JWS during `certbot update_account --register-unsafely-without-email`.

Hopefully that would avoid any modifications to the storage layer at all.

**Comment by aeturnum** [comment]
Oh what a clever solution @alexzorin! That should allow transmission of an empty tuple with the `contact` field still being omitted when empty. 

I'm still uncertain about verifying that the server properly handles that message, but maybe that's a problem for the pull request.

**Comment by bmw** [comment]
This was fixed in https://github.com/certbot/certbot/pull/8212.
