### ISSUE TITLE
TTPError: 404 Client Error: Not Found for url: https://www.piwheels.hostedpi.com/simple/zope-component/

### ISSUE THREAD

**Issue by tomofu74** [certbot/certbot#5138]
## My operating system is (include version):
Rasberrypi3 raspbian 

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
letsencrypt-auto

## I ran this command and it produced this output:
letsencrypt-auto

File "/opt/eff.org/certbot/venv/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

**Comment by nachoparker** [comment]
same here

**Comment by LaLaGuy** [comment]
Same problem.

The problem is that the given url is wrong :
https://www.piwheels.hostedpi.com/simple/zope-component/

It should be :
https://www.piwheels.hostedpi.com/simple/zope.component/

Don't know how to correct it myself.
Waiting for an update.
[log.txt](https://github.com/certbot/certbot/files/1341580/log.txt)

**Comment by bmw** [comment]
Are you still seeing this problem? Is everyone that can reproduce running Raspbian?

@erikrose, any thoughts?

**Comment by LaLaGuy** [comment]
The problem is still here.
Personally, I followed those instructions : https://certbot.eff.org/#pip-nginx.
After your comment, I tried again from the start but got the same result.
Like I said on my last post, it tries to access a wrong url.
The problem is the same for other software (Apache for example).

**Comment by sadreck** [comment]
Can confirm as well, running Raspbian (stretch) and am getting the same error:

`HTTPError: 404 Client Error: Not Found for url: https://www.piwheels.hostedpi.com/simple/zope-component/ `

Command line is:

`sudo ./certbot-auto certonly --standalone -d mydomain`

**Comment by nachoparker** [comment]
Exactly the same here. I create Raspbian based images in an automated way for [NextCloudPi](https://ownyourbits.com/2017/02/13/nextcloud-ready-raspberry-pi-image/) and I can reproduce 100% of the times.

**Comment by erikrose** [comment]
@bmw This is [an upstream bug in piwheels itself](https://github.com/bennuttall/piwheels/issues/20) and should go away when it gets fixed.

**Comment by ShashankJain123** [comment]
I managed to solve this by giving the auto script an additional repository to look for files; in this case **zope.component** rather than **zope-component**

To do this modify /etc/pip.conf and add the below line item
extra-index-url=https://www.piwheels.hostedpi.com/simple/zope.components

Worked like charm and certificate has been generated.

PS: I am not a programmer or a coder and don't know anything about pip or python. This may be a temporary solution and worked for me; so should for you.

**Comment by tball78** [comment]
@ShashankJain123 Thanks.  Workaround worked like a charm.  I appreciate you sharing this since this has been a recent frustration while attempting to get Let's Encrypt cert created.

**Comment by nachoparker** [comment]
It works, thank you so much!!

**Comment by fanconic** [comment]
Unfortunately, if I try the workaround by entering "/etc/pip.conf" I'm denied the access.
What am I doing wrong, or how could I access it?

**Comment by ShashankJain123** [comment]
@fanconic I worked on that with WinSCP.  Helps perform all root actions. Try that

**Comment by fanconic** [comment]
@ShashankJain123
I’ve tried now with WinSCP, however I‘m still getting a permission error (error 3: permission denied)

Any answer to that?
Or maybe a link to another forum, as I wasn‘t able to find any solution so far.

Thank you already in advanced

**Comment by erikrose** [comment]
There are about a zillion different places pip looks for configuration. If you can't work out the permission problems for one, try creating another: https://pip.pypa.io/en/stable/user_guide/#configuration. Cheers!

**Comment by fanconic** [comment]
@erikrose Thank you, I shall try!

**Comment by wpmjones** [comment]
I'm on Raspbian and tried to set up certbot using `./certbot-auto certonly --standalone --standalone-supported-challenges http-01 --email your@email.address -d hass-example.duckdns.org` and got the same error with the incorrect url.  I used the solution that @ShashankJain123 proposed and it worked fine.

**Comment by nachoparker** [comment]
The issue has been fixed

https://github.com/bennuttall/piwheels/issues/20#issuecomment-340108171

No workarounds are required now

**Comment by tomofu74** [comment]
Thanks!

**Comment by Halloran** [comment]
In my case, adding lines to: 
/etc/pip.conf
as recommended above did not work. What did work was commenting all lines out of the file. I believe that removing the file altogether would have worked as well.

**Comment by maxverstappen** [comment]
"What did work was commenting all lines out of the file"
Worked also for me
