### ISSUE TITLE
Hitting rate limits on (free) usa.cc subdomains

### ISSUE THREAD

**Issue by patrakov** [certbot/certbot#5148]
## My operating system is (include version):
Linux (Ubuntu 16.04)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
 OS package manager

## I ran this command and it produced this output:
letsencrypt --apache -d redacted-domain.usa.cc
...
An unexpected error occurred:
There were too many requests of a given type :: Error creating new cert :: too many certificates already issued for: usa.cc

## Certbot's behavior differed from what I expected because:
I expected a certificate to be issued.

usa.cc is used by many (too many?) people because of free subdomains - maybe it needs a rate limit exception?

https://crt.sh/?q=%25.usa.cc

**Comment by bmw** [comment]
I would encourage your DNS provider to request to be added to the public suffix list. You can read more about this [here](https://github.com/certbot/certbot/issues/1607#issuecomment-159168888).

If for some reason that does not resolve your issue, I encourage you to open a ticket with [Let's Encrypt's boulder server](https://github.com/letsencrypt/boulder) which determines and enforces these rate limits rather than EFF's Certbot client.

I hope this helps!
