### ISSUE TITLE
require-hashes mode

### ISSUE THREAD

**Issue by torsinclair** [certbot/certbot#5163]
## My operating system is (include version):
Ubuntu 10.4

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
wget https://dl.eff.org/certbot-auto

## I ran this command and it produced this output:
sudo ./path/to/certbot-auto --apache certonly

In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    setuptools from https://pypi.python.org/packages/32/28/16fffbead19dc705f9546134ca81090d6c266aff6173fb092bb6d8dfd76a/setuptools-36.5.0-py2.py3-none-any.whl#md5=14b28ae24ea931a752f70acaafcb1b9f (from zope.component==4.2.2->-r /tmp/tmp.6pTxkO1B9B/letsencrypt-auto-requirements.txt (line 165))

## Certbot's behavior differed from what I expected because:
didn't install

**Comment by bmw** [comment]
@erikrose, looks like `zope.component`'s `setup.py` depends on `setuptools`. Do you have a suggestion how to work around this problem?

**Comment by erikrose** [comment]
@bmw I'm confused as to how this is just coming up now. It doesn't look like zope.component is a new requirement for us. Any clue?

Our options are…
* Get setuptools removed as an upstream dependency. (I don't see what good having it there could do, since setup.py itself will crash if setuptools isn't around. Maybe it has an application for the wheel.)
* Pick a version of setuptools, and pin it.

**Comment by bmw** [comment]
I have no idea. We haven't changed the version `zope.component` pinned in certbot-auto since March 2016. The hash didn't change either so it's not like they reuploaded the package with different requirements. Perhaps there's indeterminism and/or differences in how `pip` parses requirements in different versions/systems?

I don't like it, but I think our only option for the time being is:

> Pick a version of setuptools, and pin it.

The version of `zope.component` we have pinned is the last version that supported Python 2.6.

**Comment by erikrose** [comment]
Say, @hannosch, do you have any idea why zope.component includes setuptools in `install_requires`? It seems unnecessary, given that setup.py would crash in its absence before it ever got to `install_requires` anyway.

**Comment by erikrose** [comment]
The only use of setuptools in zope.component outside setup.py is in bootstrap.py, which is an optional script you can run if you're using buildout.

**Comment by hannosch** [comment]
@erikrose zope.component and Zope projects in general tend to use setuptools style namespace packages. So the `__init__` in `src/zope` contains something like `__import__('pkg_resources').declare_namespace(__name__)`.

There are also some other Zope projects using `pkg_resources` features to get version information about installed packages.

I forgot when namespace packages got added to Python Core, but they aren't in Python 2.7, and that's still supported.

Otherwise you'd be correct, declaring setuptools as a `setup_requires` dependency is useless, as that's a setuptools feature in the first place. But for the namespace package support, it's an actual runtime (install_requires) dependency.

**Comment by erikrose** [comment]
Ah, I forgot pkg_resources was part of setuptools. Thanks for the deep and informative reply! I hope all's going well in your new adventure. :-)
