### ISSUE TITLE
Incorrect validation certificate for tls-sni-01 challenge

### ISSUE THREAD

**Issue by MiningPickaxe** [certbot/certbot#5189]
## My operating system is (include version):
Debian Jessie

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
wget https://dl.eff.org/certbot-auto && chmod a+x certbot-auto
./certbot-auto

## I ran this command and it produced this output:
`certbot-auto certonly --standalone --rsa-key-size 4096 -d thisismysub.domain.de`

## Certbot's behavior differed from what I expected because:
Incorrect validation certificate for tls-sni-01 challenge. Requested xxxxxxxxxxxxxx.xxxxxxxxxxxxxx.acme.invalid from myip:443. Received 2 certificate(s), first certificate had names "anotherdomain.com, www.anotherdomain.com" 

Certificates could not be created.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
https://privatebin.net/?d275648123115258#RO5Jh5A1NieojXImF74GoBZYhtZdwtDCkC0QbfJodGQ= 
All Domains were censored, ANOTHERDOMAIN is always the same domain, CENSORED DOMAIN is the domain the certificate is for (including subdomain)

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
NGINX: 
```
server {
        listen 80;
        server_name CENSORED DOMAIN;
        return 301 https://$server_name$request_uri;
}


server {
        listen 443 ssl http2;
        server_name CENSORED DOMAIN;

#Following will be turned on as soon as certificate is created, otherwise nginx wont start
#        ssl on;
#        ssl_certificate         /etc/letsencrypt/live/CENSORED DOMAIN/fullchain.pem;
#        ssl_certificate_key     /etc/letsencrypt/live/CENSORED DOMAIN/privkey.pem;

        location / {
                proxy_pass http://localhost:7257;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_connect_timeout 150;
                proxy_send_timeout 100;
                proxy_read_timeout 100;
                proxy_buffers 4 32k;
                client_max_body_size 8m;
                client_body_buffer_size 128k;
        }
}
```

## Other notes
Nginx was stopped during the whole process, no other processes were using port 443, confirmed with netstat. No A/AAAA record was not used, a CNAME is in the DNS record. Would prefer to not change it to A/AAAA if possible.

**Comment by bmw** [comment]
Do you recognize the domain you called "anotherdomain.com"?

I've got a few things for you to try, but I recommend you add `--dry-run` to the command line while doing so to avoid [rate limits](https://letsencrypt.org/docs/rate-limits/) from Let's Encrypt.

If you run the same command and add `--debug-challenges` (and `--dry-run`) to the command line, Certbot will stop with `Challenges loaded. Press continue to submit to CA.`. After seeing this but before contining, what's the output if you run `openssl s_client -connect <your domain>:443` on another machine? If you get a certificate back, something other than Certbot is serving certificates.

You can also potentially work around the problem by using the HTTP challenge. You can do this by including `--preferred-challenges http` on the command line.

**Comment by MiningPickaxe** [comment]
`Do you recognize the domain you called "anotherdomain.com"?`
Yes I do. It was the domain of the Server cluster. 

`I've got a few things for you to try, but I recommend you add --dry-run to the command line while doing so to avoid rate limits from Let's Encrypt.`
So I tried that, apperantly not rate limits.

`openssl s_client -connect <your domain>:443`
that gave some information... Apperantly it was Plesk causing the mess... There was a RapidSSL certificate for the "anotherdomain". And cerbot-auto or let's encrypt (wich one I don't know) somehow found a certificate for the subdomain hostname.anotherdomain.com wich should not even be present since anotherdomain.com is not a wildcard certificate and hostname.anotherdomain.com was not even registered in the DNS settings, it was a non-existent subdomain. Now that I registered that subdomain, everything seems to be behaving again, I can create certificates with certbot. I have no Idea why that happened... If you have any ideas, I would be interested to learn what caused that to happen

**Comment by bmw** [comment]
> If you have any ideas, I would be interested to learn what caused that to happen.

I can tell you more about what's going on behind the scenes and you might be able to figure out what happened with more knowledge of your setup. To verify that you control your domain, Let's Encrypt is attempting to establish a TLS connection with the IP address for the domain you requested a certificate for. It is requesting to create that connection for a randomly generated, invalid domain name ending in `.acme.invalid`. (This works through a process call [TLS SNI](https://en.wikipedia.org/wiki/Server_Name_Indication) if you're familiar or curious.)

Certbot creates a self-signed certificate for this randomly generated domain, listens on port 443, and handles any requests for it. If Certbot gets a request for a domain it doesn't recognize, it drops the connection.

I think something else on your server was picking up this request and handling it. This could have been the default TLS configuration for your server that handles any requests for domains it doesn't recognize. It's extremely unlikely that Certbot itself was using this certificate as all certs and keys it is using are generated and stored in memory rather than using certs on the file system that Certbot could have accidentally found.

I hope this helps! Please let me know if you have any more problems or questions.

**Comment by urbenlegend** [comment]
@bmw So I am running into this same issue right now. I have 2 Wordpress sites hosted via the same HTTP server. I can correctly renew for one of the Wordpress sites but the other one fails with this message

`
-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/domain2.net.conf
-------------------------------------------------------------------------------
Cert not due for renewal, but simulating renewal for dry run
Plugins selected: Authenticator apache, Installer apache
Renewing an existing certificate
Performing the following challenges:
tls-sni-01 challenge for urbanmythic.net
Waiting for verification...
Cleaning up challenges
Attempting to renew cert (domain2.net) from /etc/letsencrypt/renewal/domain2.net.conf produced an unexpected error: Failed authorization procedure. domain2.net (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect validation certificate for tls-sni-01 challenge. Requested xxxxxxxxxxxxxxxxxxxxxxxxxxx.acme.invalid from <ip_address>:443. Received 2 certificate(s), first certificate had names "domain1.me, cloud.domain1.me, office.domain1.me". Skipping.
`

You mentioned that the default TLS configuration for the server may be causing issues. Indeed, if my server gets a domain name it doesn't recognize it will automatically go to domain1.me, simply due to the order of the Apache conf files.

How do I either fix my apache conf or fix my certbot conf so that it can properly validate the second domain?

**Comment by joohoi** [comment]
Please note that TLS-SNI challenge is now in sunset phase because of the following: https://community.letsencrypt.org/t/important-what-you-need-to-know-about-tls-sni-validation-issues/50811

Everyone should start moving their configuration towards HTTP or DNS validation.

**Comment by urbenlegend** [comment]
I tried HTTP challenge and I got a failure as well for the second domain.

```
 - The following errors were reported by the server:

   Domain: domain2.net
   Type:   unauthorized
   Detail: Invalid response from
   http://domain2.net/.well-known/acme-challenge/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:
   "<!DOCTYPE html><!-- Nikkon.ORG -->
   <html lang="en-US">
   <head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device"
```

Nikkon.org seems to be the name of the wordpress theme that domain2.net is using.

**Comment by sydneyli** [comment]
Hi all! These sorts of queries are better asked (and more quickly answered) on the [Let's Encrypt Community Forums](https://community.letsencrypt.org/c/help), where there's a larger audience of people who are also familiar with the project.
