### ISSUE TITLE
0.19.0 version of certbot-auto stops detecting new domains....

### ISSUE THREAD

**Issue by felisucoibi** [certbot/certbot#5233]
## My operating system is (include version):
Ubuntu 16.04.3

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
It self upgraded to 0.19.0

## I ran this command and it produced this output:
./certbout-auto

No new domains detected in list, only the old previously detected ones.

## Certbot's behavior differed from what I expected because:
It does not detect new config files in apache2/sites-avaliable only the previos ones detected.

**Comment by SwartzCr** [comment]
@joohoi wanna look into this? This might be due to some of your recent changes

**Comment by joohoi** [comment]
Yes, indeed this is the behavior since version 0.19. Because of various errors while trying to parse inactive vhost files in some configurations (see #3545 #3791). Certbot now only sees the same vhosts that Apache does.

To make Certbot version >= 0.19 detect your vhosts, you can enable them prior to running Certbot by issuing: 
`a2ensite nameofsitetoenable`

or by symlinking the vhost file to `/etc/apache2/sites-enabled` by:
`ln -s /etc/apache2/sites-available/yoursitetoenable.conf /etc/apache2/sites-enabled/yoursitetoenable.conf`

That said, Certbot as an option for letting user to define the directory to check vhost files from. You can make Certbot behave like before the change by adding parameter `--apache-vhost-root=/etc/apache2/sites-available` to command line.

I will close this issue as resolved as this is the intended behavior.

**Comment by felisucoibi** [comment]
Sorry but is a very bad decision, i read the bugs, and you remove something useful by default jsut because somebody has a crap configuration on its server:
https://github.com/certbot/certbot/issues/3545 and https://github.com/certbot/certbot/issues/3545
But you remove something is kind of the normal behavour that is check for sites avaliable and enable them.....

Now if i create a new config, and i enable it with a2ensite after that i can't use the certbot because apache gives a error of ssl because the certificate is still not created, and after that obviously certbot cant check for the host because apache is faulted....

The certbot should generate the config and make the chabges before the a2ensite....

Anyway is on your own... i'll try to fix it somehow with my installation script...

**Comment by joohoi** [comment]
> That said, Certbot has an option for letting user to define the directory to check vhost files from. You can make Certbot behave like before the change by adding parameter --apache-vhost-root=/etc/apache2/sites-available to command line.

Doesn't this fix it for you? Let me know if this is not working somehow and I'll reopen the issue in order to fix the bug.

> Sorry but is a very bad decision, i read the bugs, and you remove something useful by default jsut because somebody has a crap configuration on its server

To a certain extent, I agree with you. However with the design decisions we've taken allows us to support both options by not confusing people and causing possible conflicts as default. After all, this is all about just changing default behavior.

**Comment by felisucoibi** [comment]
The idea of certbot i thought was to make kind of one click solution, the default behavour should be the default setting, and by default webs r in sites-avaliable, if somebody has crap there and dont want default config should use extra settings, not the oposite, and you are breaking compatibility for just a crap config of somebody... Nonsense.

**Comment by felisucoibi** [comment]
And it creates derivate problems in my tests like apache stops workin because the cert is not created before a2add, anyway for me is fixed just wait bugs to come.
