### ISSUE TITLE
Ubuntu PPA includes 'rogue' packages beyond python-certbot

### ISSUE THREAD

**Issue by alanfranz** [certbot/certbot#5234]
## My operating system is (include version):
Ubuntu 16.04 x86_64

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Ubuntu PPA as per certbot instructions official recommendation on https://certbot.eff.org/all-instructions/#ubuntu-16-04-xenial-nginx
```
deb http://ppa.launchpad.net/certbot/certbot/ubuntu xenial main
```

## I ran this command and it produced this output:
```apt-get -y upgrade```

[...cut...]
```
Get:38 http://ppa.launchpad.net/certbot/certbot/ubuntu xenial/main amd64 python-asn1crypto all 0.22.0-2+ubuntu16.04.1+certbot+1 [70.2 kB]
Get:39 http://ppa.launchpad.net/certbot/certbot/ubuntu xenial/main amd64 python-certifi all 2017.4.17-2+ubuntu16.04.1+certbot+1 [177 kB]
Get:40 http://ppa.launchpad.net/certbot/certbot/ubuntu xenial/main amd64 python-cffi-backend amd64 1.10.0-0.1+ubuntu16.04.1+certbot+1 [71.5 kB]
Get:41 http://ppa.launchpad.net/certbot/certbot/ubuntu xenial/main amd64 python-chardet all 3.0.4-1+ubuntu16.04.1+certbot+2 [80.6 kB]
Get:42 http://ppa.launchpad.net/certbot/certbot/ubuntu xenial/main amd64 python-idna all 2.5-1+ubuntu16.04.1+certbot+1 [31.5 kB]
Get:43 http://ppa.launchpad.net/certbot/certbot/ubuntu xenial/main amd64 python-six all 1.11.0-1+ubuntu16.04.1+certbot+1 [11.9 kB]
Get:44 http://ppa.launchpad.net/certbot/certbot/ubuntu xenial/main amd64 python-cryptography amd64 1.9-1+ubuntu16.04.1+certbot+2 [212 kB]
Get:45 http://ppa.launchpad.net/certbot/certbot/ubuntu xenial/main amd64 python-openssl all 17.3.0-1~0+ubuntu16.04.1+certbot+1 [47.5 kB]
Get:46 http://ppa.launchpad.net/certbot/certbot/ubuntu xenial/main amd64 python-requests all 2.18.1-1+ubuntu16.04.1+certbot+1 [76.5 kB]
Get:47 http://ppa.launchpad.net/certbot/certbot/ubuntu xenial/main amd64 python-urllib3 all 1.21.1-1+ubuntu16.04.1+certbot+1 [97.2 kB]
Get:48 http://ppa.launchpad.net/certbot/certbot/ubuntu xenial/main amd64 python3-certifi all 2017.4.17-2+ubuntu16.04.1+certbot+1 [177 kB]
Get:49 http://ppa.launchpad.net/certbot/certbot/ubuntu xenial/main amd64 python3-chardet all 3.0.4-1+ubuntu16.04.1+certbot+2 [81.0 kB]
Get:50 http://ppa.launchpad.net/certbot/certbot/ubuntu xenial/main amd64 python3-idna all 2.5-1+ubuntu16.04.1+certbot+1 [31.6 kB]
Get:51 http://ppa.launchpad.net/certbot/certbot/ubuntu xenial/main amd64 python3-six all 1.11.0-1+ubuntu16.04.1+certbot+1 [12.0 kB]
Get:52 http://ppa.launchpad.net/certbot/certbot/ubuntu xenial/main amd64 python3-requests all 2.18.1-1+ubuntu16.04.1+certbot+1 [76.1 kB]
Get:53 http://ppa.launchpad.net/certbot/certbot/ubuntu xenial/main amd64 python3-urllib3 all 1.21.1-1+ubuntu16.04.1+certbot+1 [97.3 kB]
```

example for python-chardet:

```
python-chardet:
  Installed: 2.3.0-2
  Candidate: 3.0.4-1+ubuntu16.04.1+certbot+2
  Version table:
     3.0.4-1+ubuntu16.04.1+certbot+2 500
        500 http://ppa.launchpad.net/certbot/certbot/ubuntu xenial/main amd64 Packages
        500 http://ppa.launchpad.net/certbot/certbot/ubuntu xenial/main i386 Packages
 *** 2.3.0-2 500
        500 mirror://mirrors.ubuntu.com/mirrors.txt xenial/main amd64 Packages
        500 mirror://mirrors.ubuntu.com/mirrors.txt xenial/main i386 Packages
        500 http://ubuntu.mirrors.ovh.net/ftp.ubuntu.com/ubuntu xenial/main amd64 Packages
        500 http://ubuntu.mirrors.ovh.net/ftp.ubuntu.com/ubuntu xenial/main i386 Packages
        500 http://fr.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
        500 http://fr.archive.ubuntu.com/ubuntu xenial/main i386 Packages
        100 /var/lib/dpkg/status
```

## Certbot's behavior differed from what I expected because:

Since long (I've seen this be October, 23th, as per @oerdnj upload, but it seems that the issues existed before that), the Ubuntu PPA is providing, beyond python-certbot-* packages, a lot of python3 packages that **override default packages provided by the 16.04 distribution in main** with **radically different versions** (not just bugfix point releases). e.g. python-openssl was upgraded from 0.15 to 17.3 

I wouldn't expect such a behaviour from certbot ppa; overriding system dependencies with custom versions could impact system stability and isn't generally advised. If updated python deps are required for certbot, either a) a forked package name version is advised, or b) the certbot package could provide a prebuilt virtualenv with separate dependencies.

**Comment by SwartzCr** [comment]
I think @pde and @oerdnj would be the best people to comment on this

**Comment by jwm** [comment]
A side effect of these newer packages: a `dist-upgrade` can break other OS-installed packages.

For example, the version of `awscli` in Ubuntu 17.04 (`1.11.44-1`) breaks when the Ubuntu `python3-urllib3` package (`1.15.1-2`) is upgraded to Certbot's (`1.21.1-1+ubuntu17.04.1+certbot+1`).

```
ubuntu@ip-172-31-14-165:~$ sudo apt-get dist-upgrade 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  linux-headers-4.10.0-32 linux-headers-4.10.0-32-generic linux-image-4.10.0-32-generic
Use 'sudo apt autoremove' to remove them.
The following packages will be upgraded:
  python3-cryptography python3-requests python3-urllib3
3 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/385 kB of archives.
After this operation, 92.2 kB of additional disk space will be used.
[...]
ubuntu@ip-172-31-14-165:~$ aws s3 sync s3://foo .
fatal error: 'AWSHTTPSConnection' object has no attribute 'ssl_context'
```

**Comment by oerdnj** [comment]
The problem is that Ubuntu 14.04 LTS doesn't have the required libraries. Instead of backporting random versions to Ubuntu 14.04 LTS, I am creating an uniform environment for all supported Ubuntu versions.

I am sorry that aws is broken, but I simply don't have a time to handle each Ubuntu version differently.

You simply cannot expect nothing will broke when you want to use recent version of something on an old system.

**Comment by jwm** [comment]
Hi @oerdnj, thanks for your response. Like I mentioned, I'm using Ubuntu 17.04, which is still a fairly modern release.

@alanfranz's suggestion to ship a virtualenv, or in a different path that `certbot` can add to `sys.path`, might be useful. You could treat all Ubuntu versions the same (thus minimizing your time investment for supporting multiple releases) while also avoiding collateral damage in other Python code on the same system.

**Comment by alanfranz** [comment]
@oerdnj  I find your answer really problematic. Beside the fact that we're using 16.04 (latest LTS) and 17.04 (second-latest Ubuntu ever, just 7 months old);

# First and foremost: 

```... when yoy want to use a recent version of something...```

It's not that **I want** to use a recent version. It's **you** (certbot/eff) that are instructing me of using that install method. Go to certbot.eff.org, pick Ubuntu 16.04 and nginx, and you get this url:

```
https://certbot.eff.org/all-instructions/#ubuntu-16-04-xenial-nginx
```

# Second:

```
I am sorry that aws is broken, but I simply don't have a time to handle each Ubuntu version differently.
```
I understand that. But breaking userspace is not a good solution. Drop Ubuntu and Nginx from the supported systems if their software is too old to install the client, and tell people to use the developer docs to install from source.

# Third:

if you look at other certbot docs I stumbled upon today:

```
https://certbot.eff.org/docs/install.html#operating-system-packages
```
you can read this:
```
Please do not use python setup.py install, python pip install ., or easy_install .. Please do not attempt the installation commands as superuser/root and/or without virtual environment, e.g. sudo python setup.py install, sudo pip install, sudo ./venv/bin/.... These modes of operation might corrupt your operating system and are not supported by the Certbot team!```

What you're doing is effectively that, but with a PPA and deb packages.

# Proposal for solutions

If you'd like an alternative approach: what I do with my Python software, WITHOUT using a PPA (because I couldn't build there, I then host packages on bintray) is using fpm and docker (example: https://github.com/alanfranz/docker-rpm-builder/tree/v1dev/packaging )

I suppose there're ways to build and ship a virtualenv even in PPA, but I can't help with that. **In the meantime I suggest the Ubuntu docs are removed or that a Big Fat Warning is added**.

**Comment by SwartzCr** [comment]
@alanfranz I think you bring up a lot of good points - it really shouldn't be the case that the packaged certbot install breaks other packages on your Ubuntu version, especially if the versions of packages you have are above what certbot requires.
@oerdnj It seems like the versions of dependencies you're shipping correspond mostly to whatever is in Ubuntu trunk. While this makes things simple, it does seems like it has high potential for causing issues for users who aren't on the latest Ubuntu release. I understand that it's significant work to ship multiple sets of libraries, so I think my recommendation would be to ship a set of libraries that correspond with our minimum requirements for certbot. That way old versions of Ubuntu would get newer packages when they need it, but newer versions could safely ignore your packages.

As for people who are experiencing breakage, I would recommend uninstalling the PPA version of certbot and re-installing it using the certbot-auto script so that all packages are kept in a virtual environment

**Comment by andrewbanchich** [comment]
Strange this about this is with [my possibly-related issue](https://github.com/certbot/certbot/issues/6397) I have two servers that are both running Ubuntu 16.04.5, ran `sudo apt update && sudo apt upgrade` on both, both have the certbot PPA, etc. and they are both configured to use Route53 for a DNS challenge.

However, one of them works without any issues, but the other server displays the error I posted when doing a dry run.

**Comment by linsomniac** [comment]
I also am seeing problems on Ubuntu 16.04, probably related to the upgrading of all sorts of packages built from trunk, via the PPA:

    Found credentials in environment variables.
    Plugins selected: Authenticator dns-route53, Installer None
    An unexpected error occurred:
    AttributeError: 'AWSHTTPSConnection' object has no attribute 'ssl_context'

Since this has been open for a year, and #6397 was closed as a duplicate, and I have to use Route53 in my setup (LetsEncrypt cert is going on a backup box, primary is using AWS cert, can't do HTTP verification), I'm wondering if this is going to get attention.

**Comment by kr4ut** [comment]
First of all @oerdnj does an awesome job here :1st_place_medal:  The problem is that upstream development is quite active and by nature backporting really hurts with such a bunch of dependencies. So either you want always the newest upstream version with it's dependencies provided or you spend serious efforts on backporting for each new version :sweat_smile: 

For xenial we now pushed now a lean backport attempt without touching the existing Python packages and only introducing missing Python packages. This shouldn't break any other Python based packages and provides so far just Certbot without integration and plugin packages:

https://launchpad.net/~kraut.hosting/+archive/ubuntu/certbot/+packages

**Comment by linsomniac** [comment]
Thanks for the kraut.hosting packaging, that looks like a more reasonable set of packages to include.

I appreciate your comments about @oerdnj and your viewpoint on the packages.  I'm afraid that I'm not familiar with the certbot community and @oerdnj so I'm unfamiliar with the history here.  And I definitely understand and appreciate the effort that goes into maintaining packages and open source projects.

However, I do have some concerns about the certbot PPA and packaging that I'd like to open up discussion on.  I've reached out to the EFF to be involved in this as it relates to changes that may need to be made to the certbot instructions pages, particularly the Ubuntu Xenial page.

Potential changes to the Ubuntu Xenial and possibly other Ubuntu versions pages:

- Some sort of a warning that the "ppa:certbot/certbot" PPA includes backports of many Python packages from trunk and may have unexpected interactions with other Python packages on the system.
- *or* Change to using the kraut.hosting PPA?  It's unclear to me if that is a drop in replacement for the certbot PPA.

I'll admit that I have some pretty big concerns with the certbot PPA as it stands.  I have not deeply investigated the PPA, these comments are based on the previous discussions in this ticket, so I admit I may have some misunderstandings.  But here are my concerns:

- Overriding the distro packages should be avoided.  Users are running an LTS release like Xenial because they want a platform that has certain stability profiles and attention security issues.  Overriding double-digits of distro packages from trunk dramatically changes that profile.
- The distro packages include updates and fixes to bugs and security issues.  Taking a snapshot of trunk and building them into this PPA means that fixes to the distro, and even to trunk, are not picked up.  This can lead to security issues.
- This PPA includes packages of a security-sensitive nature (python crypto libraries, pyopenssl, ASN1).
- This PPA overrides some heavily used Python libraries (boto, requests, urllib, setuptools, zope libraries)
- The nature of this package is that it is likely to be deployed on Internet facing computer running web applications.  Due to the above, this method of packaging could introduce security problems in applications running on these web servers.
- This PPA is under the certbot name, so it invokes the reputation of certbot and the EFF and problems with it can negatively impact them.

That said, here are my thoughts on the repo itself:

- I understand very well the conflict of LTS releases versus the latest versions of libraries, and how hard it can be to reconcile those.  If this repo just wants to pull in the latest of everything, it probably should be doing so in a virtualenv or similar so it doesn't impact the other applications on the server.  dh-virtualenv might help there.
- I understand it may be desirable to have a "one size fits all" solution to the different distro versions, as it makes things simpler, but there are significant problems to that, beyond the conflict that causes the Route53 DNS method not to work.
- I'm willing to help resolve these issues. 

Thoughts?

**Comment by alanfranz** [comment]
I'll chime in again. One year is an astonishingly long time to handle an issue like the one I reported.

First and foremost, nothing here is a personal attack to @oerdnj . I think he's involved in many initiatives, and possibly he's a volunteer (let's encrypt has some industry backing, but I suspect not everybody gets paid) but the job being done on the PACKAGING PART (the PPA) is far from awesome; on the contrary, it's problematic, because it's the recommended way to install certbot on some distros. No problem if it were a random PPA on launchpad.

So: if the job can't be done properly, just strip that install method from the docs and let the user deal with it. Certbot is published as a snap on edge channel as well, so ubuntu users can use that.

```
Overriding the distro packages should be avoided. Users are running an LTS release like Xenial because they want a platform that has certain stability profiles and attention security issues. Overriding double-digits of distro packages from trunk dramatically changes that profile.
```

I think @linsomniac has a great point here. I had not thought about security issues, but that's surely a concern. If @oerdnj doesn't have enough time to build new deps for new certbot versions, for sure won't follow every potential security issue in the deps he packages.

If it can't be fixed, drop this PPA now, before it's too late; recommend every user of it of reinstalling "original" deps; if a vulnerability is accidentally introduced and exploited, the whole Let's Encrypt initiative credibility will suffer, greatly.

**Comment by bmw** [comment]
A couple of you have expressed interest in helping to resolve this issue. Any help would be greatly appreciated as we would certainly like to continue to offer the PPA if it's able to get updated. While Ubuntu releases like Bionic have fairly recent packages, those in other releases like Xenial [do not](https://bugs.launchpad.net/ubuntu/+source/python-letsencrypt/+bug/1745126) do not and while [certbot-auto](https://certbot.eff.org/docs/install.html#certbot-auto) is an OK workaround, distro packages should be preferred in general for a number of reasons.

@oerdnj and @NCommander, if people here propose packages for the PPA, are you able to review them? While I don't think I'm familiar enough with Ubuntu packaging to help review the actual .debs, I can potentially help with testing. The [test script](https://wiki.ubuntu.com/StableReleaseUpdates/Certbot/TestScript) I wrote when it was looking like we'd get an SRU could be useful.

If it helps, because we are packaged on a variety of systems, we regularly test with both newer and older versions of our dependencies ourselves. The list of the oldest dependencies we are known to work with can be found [here](https://github.com/certbot/certbot/blob/master/tools/oldest_constraints.txt). We also work with the newest version of all of our dependencies. If anyone has any questions about this aspect of things, don't hesitate to ask!

cc @hlieberman

**Comment by kr4ut** [comment]
I hope we don't get too much confusion in here and keep discussion streamlined and constructive.
Still i like to restate broader picture of the software distribution of Certbot on major server distros:

1. The certbot/certbot PPA does indeed overwrite Ubuntu distro pkgs but this is kind of PPA culture.
2. On RedHat/CentOS we have certbot packages in EPEL which forbids touching distro pkgs.
3. Debian has certbot in backports. For Ubuntu we're missing both backports and SRU got stuck.
4. Ubuntu has a parallel initiative with a Snap from Robie https://github.com/basak/certbot-snap-build

@bmw Thanks for involving in here again :+1: Just one question in that regard to upstream:
5. What about LTS/ESR releases of Certbot itself that would help backporting and QA in distribution?

**Comment by bmw** [comment]
@kr4ut, I'm happy to answer that question but I don't think that discussion belongs here. I've responded at https://github.com/certbot/certbot/issues/5884#issuecomment-433197649.

**Comment by bmatthewshea** [comment]
Fixed this error that came up today on 16.04 per OP.

Removed certbot ppa package for route53:

```
sudo apt purge python3-certbot-dns-route53
sudo apt autoremove
sudo apt -H install pip3
sudo -H pip3 install certbot_dns_route53
```
`certbot certonly --agree-tos --dns-route53` ...

install/renew/cron works fine again.

**Comment by kr4ut** [comment]
@bmw FYI we looked into the "dependencies-by-distro-backport" to trusty, but honestly that's a lot of nasty work. For the few of our clients who insisted on staying the whole LTS cycle with trusty despite upgrade offers we're actually using the certbot/certbot PPA. But are praying those last systems may rest in peace soon :sweat_smile:

For backporting the additional plugins to xenial we actually don't have a use case for them ourselves. Especially due to need for distributed credentials of the DNS providers at the TLS endpoints and the security implications of that. But if someone would seriously help out with the testing we might be able to continue here with some delay :construction_worker_man:

**Comment by bmw** [comment]
> @bmw FYI we looked into the "dependencies-by-distro-backport" to trusty, but honestly that's a lot of nasty work. For the few of our clients who insisted on staying the whole LTS cycle with trusty despite upgrade offers we're actually using the certbot/certbot PPA. But are praying those last systems may rest in peace soon 😅

Yeah. We only have a few more months until Trusty's EOL and backporting Certbot and most of its plugins to 16.04+ should be much easier. We're currently working on backporting the version of Certbot in Bionic to Xenial and there are no dependency problems.

> For backporting the additional plugins to xenial we actually don't have a use case for them ourselves. Especially due to need for distributed credentials of the DNS providers at the TLS endpoints and the security implications of that. But if someone would seriously help out with the testing we might be able to continue here with some delay 👷

Our DNS plugins are in state of flux at the moment (see https://github.com/certbot/certbot/issues/6504) so I'm personally not too worried about this. Until we have a clear path forward, I'd prefer to get our DNS plugins as widely packaged as possible, but this is likely to be less of an issue in the long term.

**Comment by oerdnj** [comment]
@kr4ut I would appreciate a write up on what was needed for the minimal 16.04 backport and what packages needs to be backported. I could then try to cleanup the “official” repository since Ubuntu 14.04 EOLs next month, I think we should just stop caring about it.

**Comment by kr4ut** [comment]
@oerdnj Sorry for the late response i didn't see the Github notification, but yes it would be nice if we do some coop mode here. While i agree on not putting any bloody efforts into trusty question is if we're aiming for a seperate LTS PPA here. Saying this because i expect that the backporting will be always serious downstream work without LTS releases by upstream and then people will complain we don't offer the newest certbot release.

For the write up i guess we need to look first in the latest work by @basak on https://bugs.launchpad.net/ubuntu/xenial/+source/python-letsencrypt/+bug/1640978/comments/132 But guess for the rest debdiff on the packages in the repo should give you all the glues:

https://launchpad.net/~kraut.hosting/+archive/ubuntu/certbot/+packages

Basically i worked through earlier backporting commits from hlieberman and basak on the relevant packages on Debian's Gitlab that got reverted later again. If can help you more let me know again :smiley:

**Comment by bmw** [comment]
For the josepy, acme, certbot, certbot-apache, and certbot-nginx packages, we maintain compatibility with the versions of our dependencies found in Xenial. We also regularly test against the latest versions of each of our dependencies for all Certbot components. You shouldn't have to backport any dependencies to offer these packages on Xenial or newer.

For the DNS plugins, they depend on DNS provider's official libraries or [Lexicon](https://github.com/AnalogJ/lexicon) which often aren't available in Xenial. We'd have to talk about this, but perhaps if the PPA offered the oldest version of the dependencies found in any version of Ubuntu, we could maintain compatibility with that old version like we do for our other plugins.

**Comment by devec0** [comment]
There are still quite a lot of python packages which are present in the Certbot PPA which could cause undesirable interactions with other packages and code deployed by users by short-circuiting Ubuntu's release policy, especially on LTS, and that has been discussed in depth here already.

Given that Certbot and the certbot-maintained packages (certbot, acme, josepy, etc) required for basic certbot functionality are tested against dependency versions for Xenial and newer (@bmw, please feel free to fact check me here) - the goal here should be to remove any non-certbot python library packages from the PPA. I think this is fairly easy.

The remaining gap here is the plugins (per #6053) and those require some python packages (#6927, i.e. lexicon) which are either not in Ubuntu or require newer versions to fix functionality issues.

It might make sense to have two PPAs in light of this, one "core" PPA for Certbot and another for the plugins, where the core certbot PPA could contain only packages which do not require dependent python libraries which are no present in the base version of Ubuntu, and the plugins PPA would not have this same restriction. That way, for example, Xenial and Bionic users wanting the full DNS plugin suite could grab the extra PPA and get the updated lexicon package.

Thoughts on this approach obviously welcome.

**Comment by bmw** [comment]
With a couple of exceptions, it's currently just our DNS plugins that may require new versions of dependencies. We've made sure `josepy`, `acme`, `certbot`, `certbot-apache`, and `certbot-nginx` work with the packages available in Xenial.

The exceptions to this are:

1. We recently added `distro` as a dependency of Certbot which is not packaged in Xenial. See https://github.com/certbot/certbot/pull/7337#issuecomment-525523875.
2. Our docs (which aren't even packaged in the PPA right now anyway) require newer versions of Sphinx than those found in Xenial.

A separate PPA seems like it may be a good solution in the long run, but since in the long run we're currently planning on replacing a lot of our packaging options possibly including the PPA with snaps, I think it may be overkill.

@devec0, what do you think about the PPA only including our components that either have all dependencies available or has a dependency that is unpackaged such as `distro` mentioned above? If a dependency is packaged but too old, the PPA would not provide a newer version overwriting the one provided by Ubuntu. To provide any dependencies that are unpackaged, we'd take them from the oldest non-EOL'd version of Ubuntu where they are available to help ensure a stable upgrade path. In the case of an SRU to these dependencies, we should try to keep them up-to-date and repackage them so PPA users on older systems get the same update.

Any Certbot components we can't do this for would remain unpackaged for now. This may never come up, but if we went this route, how hard would it be to only offer some Certbot components for newer versions of Ubuntu?

**Comment by alanfranz** [comment]
Dear package maintainers,
it's more than two years since my original report, and the problem still happens, even for Ubuntu 18.04:

```
Get:1 http://it.archive.ubuntu.com/ubuntu bionic/main amd64 python3-openssl all 17.5.0-1ubuntu1 [41,5 kB]
Get:2 http://ppa.launchpad.net/certbot/certbot/ubuntu bionic/main amd64 python3-josepy all 1.1.0-2+ubuntu18.04.1+certbot+1 [27,8 kB]
Get:3 http://ppa.launchpad.net/certbot/certbot/ubuntu bionic/main amd64 python3-requests-toolbelt all 0.8.0-1+ubuntu18.04.1+certbot+1 [38,3 kB]
Get:4 http://it.archive.ubuntu.com/ubuntu bionic/main amd64 python3-pbr all 3.1.1-3ubuntu3 [53,8 kB]
Get:5 http://ppa.launchpad.net/certbot/certbot/ubuntu bionic/main amd64 python3-acme all 0.31.0-2+ubuntu18.04.3+certbot+2 [50,7 kB]
Get:6 http://it.archive.ubuntu.com/ubuntu bionic/universe amd64 python3-mock all 2.0.0-3 [47,5 kB]
Get:7 http://ppa.launchpad.net/certbot/certbot/ubuntu bionic/main amd64 python3-configobj all 5.0.6-2+ubuntu18.04.1+certbot+1 [35,5 kB]
Get:8 http://ppa.launchpad.net/certbot/certbot/ubuntu bionic/main amd64 python3-future all 0.15.2-4+ubuntu18.04.1+certbot+3 [333 kB]
Get:9 http://it.archive.ubuntu.com/ubuntu bionic/main amd64 python3-tz all 2018.3-2 [25,1 kB]
Get:10 http://it.archive.ubuntu.com/ubuntu bionic/main amd64 python3-rfc3339 all 1.0-4 [6.356 B]
Get:11 http://it.archive.ubuntu.com/ubuntu bionic/main amd64 python3-pyasn1 all 0.4.2-3 [46,8 kB]
Get:12 http://it.archive.ubuntu.com/ubuntu bionic/universe amd64 python3-ndg-httpsclient all 0.4.4-1 [23,5 kB]
Get:13 http://it.archive.ubuntu.com/ubuntu bionic/universe amd64 python3-configargparse all 0.11.0-1 [22,4 kB]
Get:14 http://it.archive.ubuntu.com/ubuntu bionic/universe amd64 python3-zope.event all 4.2.0-1 [7.402 B]
Get:15 http://it.archive.ubuntu.com/ubuntu bionic/main amd64 python3-icu amd64 1.9.8-0ubuntu1 [173 kB]
Get:16 http://ppa.launchpad.net/certbot/certbot/ubuntu bionic/main amd64 python3-parsedatetime all 2.4-3+ubuntu18.04.1+certbot+3 [32,4 kB]
Get:17 http://ppa.launchpad.net/certbot/certbot/ubuntu bionic/main amd64 python3-zope.hookable amd64 4.0.4-4+ubuntu18.04.1+certbot+1 [9.532 B]
Get:18 http://ppa.launchpad.net/certbot/certbot/ubuntu bionic/main amd64 python3-zope.interface amd64 4.3.2-1+ubuntu18.04.1+certbot+1 [89,6 kB]
Get:19 http://ppa.launchpad.net/certbot/certbot/ubuntu bionic/main amd64 python3-zope.component all 4.3.0-1+ubuntu18.04.1+certbot+3 [43,1 kB]
Get:20 http://ppa.launchpad.net/certbot/certbot/ubuntu bionic/main amd64 python3-certbot all 0.31.0-1+ubuntu18.04.1+certbot+1 [208 kB]
Get:21 http://ppa.launchpad.net/certbot/certbot/ubuntu bionic/main amd64 certbot all 0.31.0-1+ubuntu18.04.1+certbot+1 [11,0 kB]
```

Various packages shadow original distribution packages, even though those seem cherrypicked bugfixes rather than full-version updates.

I understand that packaging is hard. But still, in the certbot install page (https://certbot.eff.org/lets-encrypt/ubuntubionic-apache), nobody is explaining to the user what is happening and what are the risks of such PPA. Just be honest, and state that some spurious packages can enter their system with such PPA (as with just any PPA, in fact).

**Comment by bmw** [comment]
Thanks for the nudge @alanfranz.

We could just add text to https://certbot.eff.org describing this issue, but I worry that many Certbot users wouldn't know what to do with that information. We have users ranging from advanced sysadmins to beginners largely copying and pasting commands. I think trying to describe this issue both succinctly and sufficiently without assuming any background knowledge is pretty hard. Even if we did that and all users understood, what are they supposed to do? My suspicion is that for almost all of them, the answer is nothing. They will still use our PPA and things will still mostly work. Because of all this, I personally don't like this approach.

The good news is that I think this issue will be solved indirectly relatively soon. We have been working on Certbot packaged as a [snap](https://snapcraft.io/) for a while now and are planning to transition our PPA users to that. This completely avoids any dependency problems because all of Certbot's dependencies will be inside the snap isolated from the rest of the system. We're planning on starting the beta period for that in the next month or two and if that goes well, will no longer be recommending the PPA. This will take a little longer than updating the documentation, but I personally think it is a much better way for us to solve this long standing issue.

**Comment by ak5** [comment]
I used the snap and the `certbot-dns-route53` from pip3 and it works FYI for anyone else coming here from google. The ppa just stopped working for me

**Comment by devec0** [comment]
I really thought I had commented here, apologies for that. I've got a plan to address the above, but am just exceptionally time-poor at the moment. I've been mapping out the various packages and their dependencies, vs what actually needs to be backported, with a view to updating the packages to their latest versions and removing packages which are covered by the extensive work done by the certbot development team to make sure certbot and dependencies work with older versions of libraries (such as those shipped with LTS releases of Ubuntu). It's frankly a big job, and without a concerted chunk of time, which I'm hoping to come across shortly, it's not going to be done in the short term. If folks have problems with individual plugins, please file issues and tag me, and I'll attempt to help. I too am looking forward to the snap becoming the default mechanism for installing Certbot, as snaps definitely address many of the issues with backporting newer code to older releases.

**Comment by bmw** [comment]
We're deprecating the PPA with the plan to make use of [Certbot's SRU exception](https://wiki.ubuntu.com/StableReleaseUpdates/Certbot) so I'm closing this issue.
