### ISSUE TITLE
Pre-hook is being called a bit later than what I'd have expected

### ISSUE THREAD

**Issue by adiov** [certbot/certbot#5235]
## Background
I have all egress traffic blocked on my server. All scripts initiating outgoing connection must call the firewall API to request a shot-lived exception. This is done with a script `enable-outgoing-traffic.sh`. This seems to be a good case for post and pre hooks.

## Info
- certbot 0.19.0
- Installed with APT
- Running command `cerbot renew`
- Output:

```
Attempting to renew cert xxx) from /etc/letsencrypt/renewal/xxx.conf produced an unexpected error: HTTPSConnectionPool(host='acme-staging.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd7dc90ae10>: Failed to establish a new connection: [Errno -2] Name or service not known',)). Skipping.
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/xxx/fullchain.pem (failure)
```

## What happened
In `renew_cert()`, pre-hook is called from inside `_get_and_save_cert()`, which is happening after `_init_le_client()`, which seems to be contacting the LE API to determine the account. Since no egress connections are allowed, Certbot fails.

## What I expected
I expected the pre-hook to be called right after Certbot determined that the cert is due for renewal, before contacting the LE API.

## Possible fix
At least in my case, moving `hooks.pre_hook(config)` call to the [`if should_get_cert`](https://github.com/certbot/certbot/blob/3087b436f3be0adbbb2800263288cd5aae452828/certbot/main.py#L696) block or even to [`renew_cert()`](https://github.com/certbot/certbot/blob/3087b436f3be0adbbb2800263288cd5aae452828/certbot/main.py#L740) works to fix the issue for me.

## PR?
I've been considering making a PR with my changes, but I don't quite understand the big picture consequences of moving the pre-hook call to before the LE client initialisation. It might be that this is the intentional and, indeed, expected behaviour. Ideas?

**Comment by SwartzCr** [comment]
Hmm, this is interesting.
The complexity with this is that we want to be able to handle many different pre- and post- hooks. We do some batching of them to ensure that hooks like `service apache restart` aren't called too many times.
Where you might be generating different authz - I think we may only confirm your Let's Encrypt account once. This would make it hard to determine which pre-hook to run in the case where you had multiple.
I think ultimately @bmw is the one who could comment on whether we'd take a PR for this kind of thing. I think we're probably unlikely to make a new flag for hooks of this sort, but there may be an easy way for you to wrap certbot in something that handles your firewall. Then again maybe this isn't the first time that we've gotten someone asking about this, so I'll leave it to @bmw to comment - though he's out for the week, so the soonest answer would be on Monday.

**Comment by bmw** [comment]
We could potentially make this change and it's probably fine, however, since users have the ability to stick whatever they want in a hook, I'm a bit worried that changing the time it is run could break things for some people.

To propose a few safer alternatives here:

1. You can check the output of `certbot certificates` and if it contains "EXPIRED", "# day" (where # is a number between 1 - 30), or "# hours", a certificate is due to be renewed. You can do this now without us making any changes to Certbot.
2. We could add output to `certbot certificates` that included a specific string when a certificate is due for renewal and you can `grep` for this string.
3. We could add a subcommand that simply checks if any cert is due to be renewed and reports it to stdout and/or through an exit code. You could run this subcommand and if renewal needs to happen, you could modify your firewall before running Certbot.

Please let me know what you think and how well the alternatives I proposed would work for your use case.

**Comment by adiov** [comment]
Thanks for the reply @bmw. All of the proposed alternatives would address the issue I'm having. However, this is done at the expense of the usability model of certbot. Right now, certbot is automatically setup as Systemd timer running with the `tls-sni` with virtually no manual configuration overhead. The proposed solutions break and force the use of external tools to monitor the operation of certbot.

In my opinion, addressing this at the hook level is much more robust. This is right now what I have in my cerbot build. If executing the hook a little earlier would break things for other users, I don't think specific changes for me would be necessary as I'm okay with patching my own copy.

What about moving the account check till after certbot determines the cert is due for renewal?

**Comment by bmw** [comment]
I agree making the change to our hooks is better for use cases like yours, however, it's hard to know if it would break things for other users since hooks can be arbitrary scripts and we never collect data on their contents. With that said, it's hard for me to come up with a real use case where this matters.

I'd accept a well written PR for this. The function `_get_and_save_cert` in `certbot/main.py` is currently where `pre_hook` is called. It's important that all code after the call to `pre_hook` remains in a `try` block with a `finally` block to call `post_hook`.

The account is initialized in `_init_le_client` in the same file. Multiple functions call both of these methods so a bit of refactoring should be done to do this cleanly.

**Comment by jo-so** [comment]
I'm requesting the same change. I'm using the `pre_hook` to remount the filesystem read-write. Currently, `_init_le_client` fails to create the symlinks, because the `pre_hook` gets started after this in `_get_and_save_cert`. I've fixed it the same way as @adiov did, by placing a call of `hooks.pre_hook(config)` before `_init_le_client`.

Currently, the call of `hooks.pre_hook(config)` in `_get_and_save_cert` is not guarded by a try-finally block with `post_hook`. Hence, all callers of `_get_and_save_cert` have to do it. The call in `renew_cert` isn't guarded, too. The try-finally-block must be somewhere upward in the call chain. Therefore, I would move the call of `hooks.pre_hook(config)` before `_init_le_client` or better inside of `_init_le_client`.

`_get_and_save_cert` is used a second time in `certonly` where a call of `_init_le_client` precedes the call of `_get_and_save_cert`. Both of them are not separated by a try-finally-block which requires the call of `post_hook` is somewhere upward the call chain.

**Comment by jo-so** [comment]
```
--- main.py     2019-02-21 08:26:10.156993939 +0100
+++ /usr/lib/python3/dist-packages/certbot/main.py      2019-02-21 08:25:29.899704043 +0100
@@ -107,7 +107,6 @@
     :raises errors.Error: if certificate could not be obtained
 
     """
-    hooks.pre_hook(config)
     try:
         if lineage is not None:
             # Renewal, where we already know the specific lineage we're
@@ -599,6 +598,7 @@
     :rtype: client.Client
 
     """
+    hooks.pre_hook(config)
     if authenticator is not None:
         # if authenticator was given, then we will need account...
         acc, acme = _determine_account(config)
```

BTW: The symlink creation happens (rw access of the filesystem) in `_determine_account`.

**Comment by jo-so** [comment]
The proposed changes above aren't applied to *certbot/_internal/main.py*. I guess the changes made didn't solve this issue.

**Comment by derekatkins** [comment]
I just ran into this myself, but I admit it's with an older version.  Specifically, I ran into https://community.letsencrypt.org/t/httpsconnectionpool-host-acme-v02-api-letsencrypt-org-port-443-read-timed-out/95354/2 which pointed me to https://community.letsencrypt.org/t/cannot-get-new-certificate-readtimeout-error/94586/9 and I verified that changing the MTU to 1380 would allow it to work.  So I thought, gee, let me set up a pre-hook to set the MTU and then I'll set it back in the post-hook.  Bzzt.  That doesn't work because it tries to reach out to the server before calling the pre-hook.

This server is still running version 0.39.  I cannot reproduce this error on another server on the same network running version 1.3.0 (I don't have the MTU issue on that second server).  So it's POSSIBLE the MTU issue is local to the failing server, but I don't have a good way to test that (short of upgrading my server, which I'll try to do).

I'll try to update the server and see if this behavior continues, in which case this bug would be important to me.
