### ISSUE TITLE
Option to remove HTML output from urn:acme:error:unauthorized

### ISSUE THREAD

**Issue by KimBrodowski** [certbot/certbot#5239]
Hello,

I'm running certbot 0.10.2 on Debian Stretch. When attempting to obtain a certificate for a domain I do not have control over or that is improperly configured I receive the following error for HTTP-01 or DNS-01 respectively:

https://gist.github.com/KimBrodowski/4875fee0b8e2803f29b1c88a73b4277f

(I've moved this to gist as GitHub's markdown parser appears to have issues with that content)

I'd appreciate an option to turn off the HTML part of the output, since it is quite messy on a terminal. To my understanding the error message originates from the ACME server, so filtering that in certbot is probably not the best idea. A better alternative might be to have an option that prevents all ACME responses from being sent to the terminal (off by default).

Otherwise I also see issues when parsing the output because you're effectively parsing untrusted data.

Kim-Alexander Brodowski

**Comment by SwartzCr** [comment]
An interesting point, this is also the cause of some other utf-8 errors we've encountered.
I'm curious if @bmw would be in support of stripping the html response out of the error message.

**Comment by bmw** [comment]
I don't think stripping the HTML out of the error message is a good idea because as you said, the message contents here come from the ACME server and is not standardized. If we wrote code that tried to remove strip this out, it might not work with another ACME CA or if Let's Encrypt changed their message format in the future.

We could ask Let's Encrypt to stop including this in the error message, but I don't think that's a good idea either as I think this can help people identify which virtual host is responding for the domain. Something like `--no-acme-errors` feels a little awkward but we could potentially go down that route.

@KimBrodowski, what if we just stopped including this content in the output when `--quiet` is included on the command line? Would this work for your use case?

**Comment by KimBrodowski** [comment]
@bmw Yes, but only if I get an indication as to what went wrong from the exit code. I haven't checked whether this is the case already. I'll spin up my test server.

For automated setups it can be very helpful to know where the error originates and differentiating between miscellaneous certbot errors and ACME validation errors is quite use imo.

**Comment by bmw** [comment]
Rather than assigning meanings to arbitrary exit codes (other than a non-zero status indicating an error), how about we just print a less verbose version of this message without the HTML to stderr? The current behavior of Certbot when `--quiet` is provided is to continue printing messages to stderr for important warnings and/or errors, so the only change we'd need to make here is to reduce the verbosity here when this flag is provided.

**Comment by KimBrodowski** [comment]
This is exactly what I originally asked for ;)

**Comment by bmw** [comment]
Great! I didn't want to add a new flag specifically for this, but changing this behavior in quiet mode by not including the field from the ACME server that includes this HTML seems like a good solution to me.

**Comment by francisrod01** [comment]
The same problem here.
I can generate with `quay.io` but not with `certbot`.
