### ISSUE TITLE
Please could you correctly recognise ClearOS

### ISSUE THREAD

**Issue by nikkilocke** [certbot/certbot#5242]
## My operating system is (include version):
ClearOS 6.9 (based on CentOS)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
certbot-auto -apache -d domain.com

## Certbot's behavior differed from what I expected because:
It was looking for apache2ctl, instead of apachectl, and other stuff caused by it not recognising ClearOS as a CentOS derivative

## Workround
After much time searching through the python source, I created an /etc/os-release file containing

    ID=CentOS
    VERSION_ID=6.9

certbot-auto now recognised the O/S as CentOS, and works.

**Comment by joohoi** [comment]
Thanks for the heads up. The best place to fix this issue would be adding /etc/os-release file to ClearOS linux with `LIKE=rhel centos` variable. This would allow other software besides Certbot to correctly fingerprint the configuration style of the OS.

**Comment by nikkilocke** [comment]
Clearos is almost exactly like centos - I would have thought the presence of the redhat release file was a clue?Regards Nikki On 15 Nov 2017 9:24 pm, Joona Hoikkala <notifications@github.com> wrote:Thanks for the heads up. The best place to fix this issue would be adding /etc/os-release file to ClearOS linux with LIKE=rhel centos variable. This would allow other software besides Certbot to correctly fingerprint the configuration style of the OS.

**Comment by joohoi** [comment]
The file `/etc/os-release` is a standardized (by systemd) way of indicating distribution id and "likeness" to other distributions, out of which one the distribution might be a fork of. There's a lot, and by that, I mean a LOT of different "minor" linux distributions out there, forked from a close relative. It would be really cumbersome for software to do unique fingerprinting methods for all of them. The only long term solution is to use a common way of doing so. And I believe it's a sensible thing to let the distribution itself state likelihood towards other distributions instead of multiple software packages trying to hardcode unique fingerprints per distribution. 

This is also why redhat release file (and similar files for other flavors of Linux) are skipped in favor of `/etc/os-release`.

Certbot is also being packaged for different distributions, and some of the packages might get pulled to forks of these. Which, in most cases will mean having dated fingerprint data for especially the newly forked distribution. `/etc/os-release` variable `ID_LIKE` solves this too.

The Linux distribution landscape, and the issue we're facing looks like this: https://upload.wikimedia.org/wikipedia/commons/1/1b/Linux_Distribution_Timeline.svg
