### ISSUE TITLE
Update tests/letstest/targets.yaml to more relevant AMIs

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5275]
This is something I'd like to sooner rather than later as many of these tests are now irrelevant as they are testing old, sometimes EOL'd distros, and not testing more modern and popular ones. The lack of more modern tests has caused us to ship bugs.

@joohoi or especially @SwartzCr, this would be something useful for you to take off my plate.

**Comment by hugovk** [comment]
https://github.com/certbot/certbot/blob/master/tests/letstest/targets.yaml

Current list:

* ubuntu15.10
* ubuntu15.04LTS
* ubuntu14.04LTS
* ubuntu14.04LTS_32bit
* ~ubuntu12.04LTS~
* debian8.1
* debian7.8.aws.1
* debian7.8.aws.1_32bit
* amazonlinux-2015.09.1
* amazonlinux-2015.03.1
* RHEL7
* ~fedora23~
* centos7
* centos6

Crossed-out ones are EOL.

https://en.wikipedia.org/wiki/Ubuntu_version_history#Table_of_versions
https://en.wikipedia.org/wiki/Debian_version_history#Release_table
https://en.wikipedia.org/wiki/Red_Hat_Enterprise_Linux#Product_life_cycle
https://en.wikipedia.org/wiki/Fedora_(operating_system)#Releases

Testing on LTS, where available, would be sensible.

Here are the non-EOL from the handy [Support Life Cycles for Enterprise Linux Distributions](https://linuxlifecycle.com/) not already listed:

* RHEL6
* RHEL5
* Ubuntu 16.04 LTS
* Debian 9
* SUSE 12
* SUSE 11

Perhaps add these, ditch the EOL and remove Ubuntu 15.10 (because 16.04 LTS is added)?

I didn't find support dates for Amazon Linux, but 2017.09.1 is the latest, released on 2017-11-22. Perhaps one of amazonlinux-2015.09.1 and amazonlinux-2015.03.1 could be replaced with this.

**Comment by bmw** [comment]
Awesome. Thanks @hugovk.

Despite it being used in our tests, I'm not very familiar with AWS. If you are, what is the easiest way to get the AMI values for the distros you mentioned above so we can update our configuration file?

**Comment by hugovk** [comment]
Unfortunately I'm not very familiar with AWS either. However, some good news is https://docs.docker.com/machine/drivers/aws/#default-amis says ami-26d5af4c is now Ubuntu 16.04 LTS not 15.10. See PR https://github.com/certbot/certbot/pull/5306.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/finding-an-ami.html documents how to find Linux AMIs, and requires access to an EC2 console or AWS CLI, which I don't have.

**Comment by bmw** [comment]
I think this issue has been superseded by new issues/PRs.
