### ISSUE TITLE
Can certbot store individual certificates for each domain?

### ISSUE THREAD

**Issue by eddiejibson** [certbot/certbot#5310]
Hi,

Can certbot store individual certificates for each domain? So it generates a .pem and .key for each domain separate instead of just adding it to a large chain? If so, how would one go about doing so?

I didn't see it in the documentation.

Thanks.

**Comment by ArchangeGabriel** [comment]
Yes, and that’s the default behaviour.

The behaviour you describe is implying you explicitly asked for one certificate containing multiple domains using the `-d` switch. To revert to separate certificate, you will have to ask for new certificate following [this procedure](https://certbot.eff.org/docs/using.html#changing-a-certificate-s-domains).

When you will be done, nothing will be required on renews to make it work, each certificate will be renewed separately.

**Comment by SwartzCr** [comment]
That's essentially right.
You should likely revert your certificate that has all of your domains in it, then run certbot again specifying only one domain at a time.
So instead of running `certbot -d domain1 -d domain2 -d domain3`
run it as:
```
certbot -d domain1
certbot -d domain2
certbot -d domain3
```
Does that make sense?
Let me know once you get it working and I'll happily close this ticket, or let me know if you need any more help and I can provide more detailed instruction.

**Comment by klangborste** [comment]
The question seems for some a bit basic, but i was also very confused, because if you use google and duckduckgo you will got only some how to add to a already existing certificate and it seems that are nearly all results ^^
I was happy find this github issue.

**Comment by bmw** [comment]
I believe this question has been answered so I'm closing this issue.

**Comment by mkormendy** [comment]
How about just having a flag that does that for us?
