### ISSUE TITLE
Allow non-interactive revocation without deleting certificates

### ISSUE THREAD

**Issue by danjjeff** [certbot/certbot#5323]
## My operating system is (include version):
Xubuntu 17.10

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
git + certbot-auto

## I ran this command and it produced this output:
certbot-auto revoke -n --cert-path /path --key-path /path --reason cessationofoperation

## Certbot's behavior differed from what I expected because:
There is no option to operate non-interactively AND not delete the certificates. I was able to achieve this prior to https://github.com/certbot/issues/4914 and just got around to updating my scripting to discover this appears to no longer be possible.

This is a request for a flag to NOT delete certs when revoking non-interactively. The reason I need this is so the certificates can still be used to check OCSP and verify that they were successfully revoked, all via non-interactive automation.

**Comment by SwartzCr** [comment]
Hmm yeah this seems like an issue. I'd be happy to possibly add a --no-delete flag or something of the sort to allow this. I'm curious what @bmw thinks of this use case.
I'm happy to add this to my todo list for when I get around to #4258
Alternately if you wanted to submit a PR, we'd happily review it, though I might wait to hear what @bmw thinks about implementation methods.

**Comment by ohemorange** [comment]
We definitely want to keep the default behavior as "cert that is revoked does not get renewed on `certbot renew`". Whether we do the simple thing and add a flag here, or rework `certbot revoke` to stick a flag in the renewal conf file, or any other option, we should keep that behavior.

**Comment by bmw** [comment]
Good point about avoiding renewal.

While we could potentially flag the cert so it's not renewed with `certbot renew` in the future if we had a good reason to, for now I personally I think we should take the approach we've used a lot for yes or no questions like this. We add two flags named something like `--delete-after-revoke` and `--no-delete-after-revoke`. This allows people to automate their way past this question with either answer in both interactive and non-interactive mode. The help for these flags should go under the revoke subcommand.

Unless anyone has any objections, @danjjeff, if you're interested in taking a crack at this, let us know. Alternatively, @SwartzCr, if you think you can get to it by the next release, can you assign this to yourself, otherwise, can you assign it to me?

**Comment by danjjeff** [comment]
I'll see if I can over the holidays when I will hopefully have a few space cycles.

**Comment by danjjeff** [comment]
Thanks!
