### ISSUE TITLE
Document that --webroot also tries tls-sni-01, which is nice.

### ISSUE THREAD

**Issue by JulienPalard** [certbot/certbot#5324]
## My operating system is (include version):

Debian GNU/Linux 9.3 (stretch)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

Used `apt install certbot`

## I ran this command and it produced this output:

```
# certbot certonly -n --agree-tos -d redacted.example.com -m admin@redacted.example.com --webroot --webroot-path /var/www/html/ --rsa-key-size 4096
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for redacted.example.com
Using the webroot path /var/www/html for all unmatched domains.
Waiting for verification...
Cleaning up challenges
Generating key (4096 bits): /etc/letsencrypt/keys/0007_key-certbot.pem
Creating CSR: /etc/letsencrypt/csr/0007_csr-certbot.pem

[...IMPORTANT NOTES...]
```

## Certbot's behavior differed from what I expected because:

I explicitly asked for the webroot plugin to be used, stdout told me webroot was used BUT in the background, tls-sni-01 was in fact used.

## Here is a Certbot log showing the issue (if available):

```
[...]
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/.../...",
      "token": "..."
    },
    {
      "type": "dns-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/.../...",
      "token": "..."
    },
    {
      "type": "tls-sni-01",
      "status": "valid",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/.../...",
      "token": "...",
      "keyAuthorization": "...-...",
      "validationRecord": [
        {
          "hostname": "redacted.example.com",
          "port": "443",
          "addressesResolved": [
            "..."
          ],
          "addressUsed": "...",
          "addressesTried": []
        }
      ]
    }
  ],

[...]
```

**Comment by SwartzCr** [comment]
So I think what's happening here is that the log is very verbose and confusing.
As I understand it, that section of the log refers to the challenge auth given to your client from the Let's Encrypt server.
What it's saying is that that auth is valid for any challenge type, but you are planning to use the http-01 challenge (as it is pending).
@cpu can correct me if I'm wrong, or provide more context if he thinks it's necessary.

**Comment by JulienPalard** [comment]
As I understand it, it's a "progression status" received by my client, telling that tls-sni-01 is valid and the others are still pending. But as I understand it, pending tests won't even be executed as one is valid, so http-01 won't be executed (and as my logs and strace is telling me, no HTTP requests are done on my port 80).

**Comment by cpu** [comment]
@JulienPalard @SwartzCr - I can't say with 100% certainty because too much has been redacted (authz IDs, challenge IDs, the domain name, authz expiry date). It would be helpful if you could provide that information next time :-)

I believe what's happened here is [valid authorization reuse](https://community.letsencrypt.org/t/upcoming-change-valid-authz-reuse/16982). I suspect that within the past 30 days @JulienPalard's ACME client validated `redacted.example.com` via an HTTP-01 challenge, resulting in the authorization shared above. Yesterday when @JulienPalard re-ran his ACME client configured for a TLS-SNI-01 challenge the CA realized his account already had a valid authorization for the requested domain name and so it returned that authorization instead of making a new pending authorization & performing challenges. I suspect if you ran a `tcpdump`/`tshark` on the server you wouldn't see an HTTP-01 or a TLS-SNI-01 challenge request arrive since the cached authorization is being used without requiring a new challenge be performed. (This is a [frequent source of confusion](https://letsencrypt.org/docs/faq/#i-successfully-renewed-a-certificate-but-validation-didnt-happen-this-time---how-is-that-possible))

> What it's saying is that that auth is valid for any challenge type, but you are planning to use the http-01 challenge (as it is pending).
> @cpu can correct me if I'm wrong, or provide more context if he thinks it's necessary.

That's not quite what the output is saying. The three challenges there basically reflect that: HTTP-01, TLS-SNI-01, and DNS-01 were three choices for validating the domain but TLS-SNI-01 was the one that was used to complete the overall authorization. For Let's Encrypt only **one** challenge per authorization is ever valid. It's harder to see when the authorization itself is truncated and only the challenges array is present.

Hope that helps!

**Comment by JulienPalard** [comment]
I think you're right, I tried using strace on nginx and didn't see anything, not a single accept, so it looks like a reuse. Which make sense as I previously used the nginx module which uses tls-sni-01.

So it's more like a "Document that auth reuse is a thing, which is nice."?

**Comment by adferrand** [comment]
With the incoming removal of tls-sni-01, this issue is not relevant anymore, and I am closing it.
