### ISSUE TITLE
Docker, change from entrypoint to cmd

### ISSUE THREAD

**Issue by StianOvrevage** [certbot/certbot#5327]
Currently the Docker image of certbot (certbot/certbot) is using `ENTRYPOINT [ "certbot" ]`.

The advantage is that you can then run a certbot command like this:

`docker run -it --rm --name certbot certbot/certbot certonly --args`

However, it also means that you cannot run a shell inside the container like this:

`docker run -it --rm --name certbot certbot/certbot sh`

Which makes using certbot very difficult as you have to invoke the docker container again and again, especially when having to update DNS entries for every try. It is also difficult to get the certificates out from the container, as the only way is to mount volumes to the host. 1) This is very flaky on Windows. 2) There is also some redirection in the Dockerfile (`VOLUME /etc/letsencrypt /var/lib/letsencrypt`) which means that the output from the container logs are wrong.

So, please consider something like this:

```
- ENTRYPOINT [ "certbot" ]
+ CMD [ "/bin/sh", "-c" ]
```

That way you can run it non-interactively (like now):

`docker run -it --rm --name certbot certbot/certbot "certbot certonly --args"` (Even works on Windows!).

And "interactively" via a shell:

`docker run -it --rm --name certbot certbot/certbot sh`

Not sure about the `VOLUME` statement. I think the paths could be cleaned up to avoid confusion.

**Comment by bmw** [comment]
I don't think we should make this change. Suddenly changing this will break things for existing users when they pull in a new version of the Docker image. I also think the goal of the Docker image is to run Certbot so let's continue to do that by default. I don't think most people need to make internal changes to their container and most changes come externally from mounting different paths, exposing different ports, etc. You can change the entrypoint yourself by adding `--entrypoint=sh` on the command line.

I'd also encourage you to look into automating solving DNS challenges as having to do it every 2-3 months is obviously a bit of a pain. We have some [DNS plugins](https://pypi.python.org/pypi?%3Aaction=search&term=certbot&submit=search) that may be able to help with this if you're using a popular provider, but otherwise, it might be useful to look into [writing a script yourself](https://certbot.eff.org/docs/using.html#hooks) to automate this if possible.

As for the volumes, [we recommend](https://certbot.eff.org/docs/install.html#running-with-docker) that people mount the volumes on their host. I'm sorry to hear this doesn't work well on Windows. We specify volumes for these directories in our Dockerfile so files such as your private key or certificates aren't lost by default when you shut down the container.

If there is a sane way for us to determine the path of the volume on the host, we could potentially land a change to correct Certbot output, however, then output is incorrect when inside the container (unless you've mounted the volumes to the same path on your host). I think this is a general problem with paths inside of a Docker container or other virtualization and I've never seen a good solution here.

I'm closing this issue since there is the `--entrypoint` workaround available to you that doesn't affect existing users, but if there are other problems that you think I'm missing, please let me know.

**Comment by StianOvrevage** [comment]
Thanks for your very detailed reply.

I was not aware of the --entrypoint flag to Docker. Embarrassing 😿 

Due to some complex infrastructure that is not yet automated I needed the raw key and certificate-blocks to copy-paste into a Kubernetes configmap. So not really a huge gain from volume mounting. That is why a interactive run where I could cat the resulting files and place the keys where needed is the best we could achieve today. Hopefully able to automate it further in less than 90 days ;)
