### ISSUE TITLE
Alternative way to signal successful renew?

### ISSUE THREAD

**Issue by hgl** [certbot/certbot#5333]
I'm using the official Certbot docker image to auto renew certificates, everything works flawless until I try to reload my load-balancer once the certificates are successfully renewed.

I can't use post-hook, because the Certbot and the load-balancer are in different containers, so there is not way for the Certbot to reload the load-balancer (well, unless you let Certbot have access to the docker daemon, but let's not do that).

I wonder if it's possible to let the renew command return a status 0 if it's successful, and something else if it didn't renew? Or maybe return different string to stdout based on different renew results?

**Comment by thecjharries** [comment]
Have you tried [deploy hooks](https://github.com/certbot/certbot/blob/v0.20.0/docs/using.rst#renewing-certificates) (not explicitly linked, you gotta scroll a bit, sorry)? Anything executable in `/etc/letsencrypt/renewal-hooks/deploy` will be run after a successful renewal. Similarly, the `--deploy-hook` flag can specify a deploy hook on the CLI.

Based on your description, it seems like it'd be pretty easy to just pass the `renew` output to a script in the Certbot container that can parse the output and send off the proper external communication. [A volume](https://docs.docker.com/engine/admin/volumes/volumes/) would make short work of that. Are you using [Compose](https://docs.docker.com/compose/) to link everything together?

I'm not actually affiliated with the project; I just had a similar issue myself.

**Comment by hgl** [comment]
Thanks for the tip @thecjharries.

I just realized that by post-hook, I meant deploy hook in my first post.

But I'm not quite sure how it can help. Do you mean I make the deploy hook output some signal string and then pipe the whole renew output (which contains the deploy hook output) to another container?

The renew command outputs a lot of text to stdout, parsing out a signal string doesn't seem to be ideal. If renew can accept a flag like `-q` to suppress all output but the output of hooks, that will make sending signal strings more reliable.

A volume seems like another choice, but in that case, another container needs to watch the file change in order to be notified if I'm not wrong. It seems quite complicated.

What did you settle on eventually?

**Comment by thecjharries** [comment]
I'm going to break this into a few different pieces:

### Parsing Output

I just ran a quick test via `--dry-run`. It looks like `all renewals succeeded` should be present in [the success output](https://github.com/certbot/certbot/blob/v0.20.0/certbot/renewal.py#L343). Something like this will fail when the renewal doesn't succeed and completely hide output:

```bash
$ (certbot renew | grep "all renewals succeeded") >/dev/null 2>&1; echo $?
1
$ (certbot renew --dry-run | grep "all renewals succeeded") >/dev/null 2>&1; echo $?
0
```
The tailing `echo` is just there to explicitly display the status.

### Masking Output

You can't easily hide some of `STDOUT` and show the rest. It looks like [hooks are piped directly to `STDOUT`](https://github.com/certbot/certbot/blob/v0.20.0/certbot/hooks.py#L233), so `--quiet` is going to mute hooks as well. But, since hooks can be full scripts, you can pipe their output to another file.

There might be a way to mask things with a `pre_hook` and restore them with a `post_hook`. I've tried a couple of different things with no luck. I ran out of easy ideas there.

### Brittle Solution

Assuming `certbot` is `renew`ing on a schedule, you could also schedule a load-balancer restart (or at least parse a shared file to possibly trigger a restart) a little bit after the `renew` command. I'd recommend not doing that, though, because you have to assume way too much about your environment working as intended all the time.

### Communicating Between Containers

No matter what, you're going to have to pass information between containers somehow.

* You can [share a file](https://superuser.com/questions/181517/how-to-execute-a-command-whenever-a-file-changes) over a volume.
* You could log to a system channel on the host and trigger actions there (e.g. `systemd` with a tool like [`journald-triggerd`](https://jjacky.com/journal-triggerd/)).
* You can connect a port and [listen for commands](https://unix.stackexchange.com/a/139315)
* You can [`POST` a message via Python 2](https://docs.python.org/2/library/cgihttpserver.html) or [Python 3](https://docs.python.org/3/library/http.server.html?highlight=http%20server#http.server.CGIHTTPRequestHandler) (at least one box has to have Python because of Certbot)
* You can [CURL a request](https://gist.github.com/joyrexus/85bf6b02979d8a7b0308) from Certbot to the load balancer and use the load balancer's server to execute a script (e.g. [Nginx](https://stackoverflow.com/questions/22891148/nginx-how-to-run-a-shell-script-on-every-request))

With Compose, you should be able to directly connect a pair of ports at launch. If one machine is just sending, say, `1`, to the other, there's not a whole lot to worry about.

At this point, I think a really good question is how did you hope to trigger a load balancer restart? Assuming you could get `certbot` to do whatever you wanted, how were you planning to handle it?

**Comment by hgl** [comment]
Whoa, thanks for the detailed research.

Let me answer your final question first.

If `certbot renew` can return a status 0 if it's successful, status 1 if too early to renew, and everything else for errors, then reloading a load balancer should be as simple as this

```
docker run -v "[mount /etc and stuff]" certbot/certbot renew
case $? in
0) docker kill -s HUP nginx;;
1) exit 0;;
*) exit 1;;
esac
```
Assuming the load balancer is nginx, and `/etc/letsencrypt` is shared between it and certbot.

Parsing `all renewals succeeded` seems flaky because there is no guarantee the text won't change between versions.

The other solutions you mentioned are quite interesting, I'll give them a shot if checking status is a dead end.

Thanks.

**Comment by thecjharries** [comment]
That makes sense! Okay, so you're running renew in a temporary container? I was looking at it as permanent container. I agree with your analysis about the output; you'd have to update it every version.

Running ephemerally negates a majority of my suggestions. Do `nginx` and `certbot` live on the same host? Can you execute logic on the host?

Since you're running this from (I think?) a script on the host, you can maintain state there.

```bash
#!/bin/bash

# Create a temp working directory
WORKING_DIR=$(mktemp -d)

# Snag a copy of the old fullchain
cp cat /etc/letsencrypt/live/example.com/fullchain.pem "$WORKING_DIR/fullchain.pem"

# Create a temp file to hold the error pipe
SAVED_STDERR=$(mktemp -p "$WORKING_DIR")

# I'm not sure if SAVED_STDERR needs to be mounted or not; I need to actually run this to grok it
docker run -v "[mount /etc and stuff]" (certbot/certbot renew --quiet) 2> $SAVED_STDERR

if [[ -s $SAVED_STDERR ]]; then
    # certbot wrote to STDERR, dunno why
else
    if diff -q /etc/letsencrypt/live/example.com/fullchain.pem "$WORKING_DIR/fullchain.pem"; then
        # No difference; file wasn't changed
    else
        # No STDERR and fullchain is different
        docker kill -s HUP nginx
    fi
fi

# Clean up
rm -rf "$WORKING_DIR"
exit 0
```

**Comment by thecjharries** [comment]
By the way, I think this is at least a feature request if not a full-fledged issue. All of these workarounds are necessary because [hooks are thrown in the generic `PIPE`](https://github.com/certbot/certbot/blob/v0.20.0/certbot/hooks.py#L240). Being able to 1) specify hook output pipes, 2) split hook and app pipes, or 3) specify a hook log (which is a different way of saying 1) would be very useful. Hook output is [totally dropped](https://github.com/certbot/certbot/blob/v0.20.0/certbot/hooks.py#L229); it's [thrown in the general log](https://github.com/certbot/certbot/blob/v0.20.0/certbot/hooks.py#L245) but is not exposed in a meaningful way.

**Comment by bmw** [comment]
Yes, thank you @thecjharries for the detailed research indeed.

I think you already can specify hook output pipes, at least when you're using the command line. For example, `--deploy-hook 'echo foo > /path/to/file'` sends the `echo` output to `/path/to/file`. If you're using `renewal-hooks` directories, you have to do this redirection inside of the script. While we could change this by adding flags to Certbot that specifies where different output should be redirected for each script, I personally think leaving this to be done in scripts is the simpler and more straightforward. Let me know if you disagree though.

Unfortunately, I don't think we're going to be changing `certbot renew`'s exit status to designate whether or not a cert was renewed. Since a non-zero exit status usually designates failure and we've had this behavior for a while with over a million people regularly running `certbot renew`, I don't want to suddenly change this.

We could potentially add a new subcommand or a flag to `certbot renew` that does this, however, we decided early on we weren't going to try and convey information through exit status like this (other than simple success and failure) as we felt a numeric value wasn't the cleanest way to communicate information. This lead to the creation of hooks which I understand doesn't work as well for your use case, so while I might be open to changing this optionally, I don't think we should change the default behavior of Certbot renew.

Another potential approach that requires some work on our end is to have the `certbot certificates` (or another subcommand) clearly designate when a certificate is going to be attempted to be renewed. You'd still have to run `certbot renew` separately and see if it succeeds before deploying your certificates, but you'll be able to check if renewal is going to be attempted.

Let me know what you think!

**Comment by hgl** [comment]
@bmw piping to files isn't easily consumable on the other end, because you have to watch file changes.

How about a flag to `certbot renew` that simply output text like `renewed`, `unchanged` without other decoration text? That shouldn't introduce compatibility issues and can be consumed by scripts easily. Currently the output from hooks is buried inside a long piece of text, making the parsing unreliable.

And another somewhat related question: do you think the nginx plugin can be adapted to this multi-container situation?

**Comment by bmw** [comment]
> How about a flag to certbot renew that simply output text like renewed, unchanged without other decoration text?

While slightly different, what if we ensured certain strings are output in both of these cases in normal output, documented this, and set up tests to prevent regressions? Sure, `grep` or whatever tool you use has to parse a little more data and the strings have to be specific enough to avoid false positives, but this should get the functionality you want without introducing more flags to Certbot.

> And another somewhat related question: do you think the nginx plugin can be adapted to this multi-container situation?

Probably not. The nginx plugin needs to be able to run the `nginx` command line tool to have nginx reload the config after making changes. It also uses this to get the version of nginx being used. Getting this to work across containers seems hard.

Perhaps in the future we could adapt the nginx plugin to work without this, but it would require the user to restart nginx themselves (sometimes during Certbot execution if you're having the nginx plugin perform the domain validation challenge) and Certbot would be unable to know if nginx was able to reload using the config Certbot modified. Currently, if nginx fails to reload after Certbot makes a change, it automatically rolls back your config and this behavior would be lost as well if Certbot can't run the `nginx` command.

**Comment by hgl** [comment]
> documented this, and set up tests to prevent regressions

That sounds good enough for me.

> Probably not.

Makes sense.

I think another solution is to simply install certbot in the same container as nginx lives.

**Comment by bmw** [comment]
> I think another solution is to simply install certbot in the same container as nginx lives.

Yes that'll definitely work.

**Comment by hgl** [comment]
Actually, using pipe as suggested by @bmw is enough to get this to work:

1. Mount a dir to host. E.g., `docker:/foo` -> `host:/tmp/foo`
2. `docker run certbot renew --post-hook 'touch /foo/renewed'`
3. When the command returns, check if `/tmp/foo` exists on the host

**Comment by bachya** [comment]
Sorry to bring up a stale issue, but in case any future reader is interested in how one might implement @hgl's "check if `/tmp/foo/renewed` exists in the host" idea, I would recommend checking out [`incron`](http://inotify.aiken.cz/?section=incron&page=doc&lang=en) (a cron-like system for responding to file events).
