### ISSUE TITLE
certbot-auto removes ~/.local/share/letsencrypt without asking

### ISSUE THREAD

**Issue by f03el** [certbot/certbot#5335]
## My operating system is:
Linux Mint 18.3

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
```
$ certbot-auto certonly --manual -c ~/.config/letsencrypt/XXXXXX.ini
Requesting to rerun /home/somebody/.local/bin/certbot-auto with root privileges...
[sudo] password for somebody:
Upgrading certbot-auto 0.19.0 to 0.20.0...
Replacing certbot-auto...
Creating virtual environment...
Installing Python packages...
Installation succeeded.
Failed to find executable /home/somebody/.local/share/letsencrypt/post-XXXXXX.sh in PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Unable to find post-hook command /home/somebody/.local/share/letsencrypt/post-XXXXXX.sh in the PATH.
(PATH is /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
```

## Certbot's behavior differed from what I expected because:
I had put my auth, cleanup and post hooks (six scripts in total) in `~/.local/share/letsencrypt` but certbot removed that folder without asking and created a link to `/opt/eff.org/certbot/venv`. Certbot should at least _ask_ before running `rm -rf` on _anything_ in a user's home folder.

https://github.com/certbot/certbot/blob/d039106b687f7300a41e11088412f16dd6f023d5/certbot-auto#L1306-L1309

**Comment by SwartzCr** [comment]
Eek, sorry about that.
I'd say that it should be added to a bugfix release - but I'm not sure that we'd be able to get it out before all possibly affected people run into this.
@bmw thoughts?

**Comment by bmw** [comment]
`{certbot,letsencrypt}-auto`  has had this behavior since February 2016 with our [0.4.0 release](https://github.com/certbot/certbot/blob/v0.4.0/letsencrypt-auto-source/letsencrypt-auto#L426) so I don't think this requires we rush out a bug fix release.

@f03el, did you choose to place your hook scripts in that directory because that's where the rest of Certbot's code was located or was it for another reason?

**Comment by f03el** [comment]
I was lucky to find sufficiently new versions of my scripts in a backup, but I still think it would be a good idea to let Certbot ask before wiping that folder.

@bmw I put them there because that was what made most sense to me. Usually I keep scripts in `~/.local/bin`, but it felt more logical to put Certbot hooks in the `letsencrypt` folder, just like I put Git hooks in each repository's `hooks` folder.

**Comment by bmw** [comment]
So you placed it there because Certbot's installation was there? While I understand that, here's what's going on on our end.

Until Certbot 0.18.0, certbot-auto installed Certbot inside the user's home directory. This was done by creating a Python virtual environment and installing Certbot inside of it. When certbot-auto upgrades, it deletes and recreates this virtual environment. While it's kind of nice to start with a clean environment each time a new version of Certbot is installed, we tried just upgrading the installation if it exists for other reasons and found this approach often didn't work. See #4047.

I think this problem was largely mitigated with Certbot 0.18.0. For new certbot-auto users, we never touch your home directory and instead put everything in `/opt`. However, when updating a certbot-auto user from a version that did put everything in your home directory and deleted it upon upgrading, we create a symlink to the new installation as some users have been running Certbot from the virtual environment directly.

Unfortunately, I don't think we want to interactively prompt the hundreds of thousands of certbot-auto about this when they upgrade, especially when most are running Certbot from something like cron once they've initially obtained their certs.

Due to the installation in `/opt`, I think this problem will fade away on its own over time, but if we wanted to do more, I think we could document this behavior and/or try to leave the top level directory of the virtual environment untouched and just delete the specific files and directories it creates. This seems error prone, I'm not sure it will always work, and obviously won't work if the user modifies the subdirectories here, but it's something we could consider.

Sorry again for the trouble here and let me know what you think!

**Comment by f03el** [comment]
Thanks for at least taking the issue seriously, even if I see your point as well. Would it be a possibility to ask the user only if the script is run interactively? I see that there have been some earlier discussions regarding checking for a TTY (like #3906), but I'm not sure whether you would like to make such checks in this shell script.

**Comment by schoen** [comment]
Could we maybe address this by creating some README files that tell users that the directory is likely to be deleted automatically?

**Comment by bmw** [comment]
Yeah that's not a bad idea. I think we're also helped by the fact the installation is now in `/opt/eff.org/certbot/venv` and we never delete anything outside of the `venv` directory.

While I understand this behavior is frustrating, it hasn't affected many users (or any since we switched to `/opt` as far as I know) so I'm moving this to wishlist.
