### ISSUE TITLE
HTTP01 support for Apache

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#5410]
Part of #5409.

**Comment by bmw** [comment]
Due to [how the sections are merged](https://httpd.apache.org/docs/2.4/sections.html#merging) in Apache, I don't see how we can always handle concerns 1 and 2 without a really deep understanding of the user's Apache config. (Being on the inside of Apache and seeing the merged config sure would be useful.)

My plan here is to do something similar to what is done in [acme.sh](https://github.com/Neilpang/acme.sh/blob/9a419bd63fadaae41e42ddea9d81a4cae9e195a9/acme.sh#L2502), however, if the request for the challenge file would normally be redirected or proxied somewhere else, this will still happen as those directives take precedence. We in theory could try and temporarily disable them for a domain, but this would halt normal operation of their server.

Similarly (although much less likely), the user's config could set permissions on directories that override ours somewhere deep in their configuration and I don't know how to reliably detect it. With that said, the approach from `acme.sh` will work for most users and I think we should go forward with it, but I do not think it is error proof.

**Comment by bmw** [comment]
My work so far is on the `apache-http` branch. This has a working implementation of HTTP-01 (with the concerns I mentioned in my previous post), works on Apache 2.2 and 2.4, and has full test coverage.

The things left to do so far are:

- [ ] See if there's not another viable approach to address some of my concerns from my previous post.
- [ ] Ensure I've handled the concerns in #5409 the best we reasonably can.
- [ ] Add a listen statement if one doesn't already exist for `config.http_01_port`.
- [ ] Verify the overall sanity of this PR.

I've squashed all of my commits so if someone builds of it, they can do the same and we can merge rather than squashing the final PR and have two clean commits preserving authorship.

@joohoi, if you see anything you don't like in the PR, you're welcome to change it and I can review it first thing tomorrow morning.
