### ISSUE TITLE
Speed up or eliminate set_by_cli

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#5412]
In https://github.com/certbot/certbot/pull/5372#issuecomment-356781859, I noticed that set_by_cli can be very slow. It takes about one second per flag to evaluate. With a lot of flags, that really adds up.

**Comment by bmw** [comment]
The way this should work is the first time `set_by_cli` is run in a given instance of Certbot or a test, it is very slow. This is because it is creating a new argument parser class, having all the different pieces of Certbot add the arguments they take to it (including Certbot's plugins), and reparsing all command line arguments. After that initial run though, subsequent runs should be very fast because these reparsed arguments are saved in something like a static variable of the function [here](https://github.com/certbot/certbot/blob/0a4f926b160cf118c81974e91df7f196bc7a379d/certbot/cli.py#L205). Did you see different behavior?

**Comment by jsha** [comment]
Yeah, I saw each run taking about a second.

**Comment by bmw** [comment]
How were you running it?

**Comment by bmw** [comment]
I've seen Certbot print output about set_by_cli with a long pauses in between, but I'm not sure this is necessarily due to set_by_cli. It certainly could be, but this function often isn't called in a tight loop so I think it's entirely possible it's other parts of Certbot that are too slow or Certbot just isn't being very clear about what it's doing.

Erica's planning on cleaning up the UI soon and while we could leave this open to profile this area of Certbot, it doesn't seem like the highest priority to me personally. If we're going to try and improve performance, I think it makes more sense to look at the big picture which is being tracked by issues like https://github.com/certbot/certbot/issues/6027.

For that reason, I'm closing this issue, but if you disagree, feel free to reopen it explaining why!

**Comment by jsha** [comment]
Hi! set_by_cli actually is called in a tight loop in storage.py when writing out the renewal config:

```
        for option, value in six.iteritems(all_values)
        if _relevant(option) and cli.option_was_set(option, value))
```

(option_was_set calls set_by_cli)

I still regularly see this add several seconds to an issuance, and think it's worth fixing.

**Comment by bmw** [comment]
That's fair! I agree speeding up this section of Certbot is valuable. I put this in wishlist because in the grand scheme of Certbot priorities, it doesn't seem as critical as some of the other problems we have, but with that said, this nerdsniped me a bit while I was waiting on tests for the release to run and I think I figured this out.

PR incoming...

**Comment by bmw** [comment]
The change isn't in `set_by_cli` but it makes that section of code have no visible delay on my system and dramatically speeds up Certbot, so I personally think #6917 can close this issue.

**Comment by jsha** [comment]
Based on your measured results I'm fine closing this. Thanks for working on it!
