### ISSUE TITLE
HTTP01 fails with default CentOS 7 config due to PrivateTmp

### ISSUE THREAD

**Issue by ryanjaeb** [certbot/certbot#5427]
## My operating system is:

I'm using CentOS 7.3, but this is likely applicable to RHEL 7 too.

## I installed Certbot with:

I installed Certbot HEAD (2cb9d9e2aa332e4fd53aab32ad1d3946438a0dd3) using [these instructions](https://community.letsencrypt.org/t/help-test-certbot-apache-and-nginx-fixes-for-tls-sni-01-outage/50207).

## I ran this command:

```
venv/bin/certbot --apache --preferred-challenges http -d sub.example.com
```
and it produced this output:

```
Performing the following challenges:
http-01 challenge for sub.example.com
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. sub.example.com (http-01): urn:acme:error:unauthorized
```

My server is giving back a 403 forbidden error.

## Certbot's behavior differed from what I expected because:

The `httpd` service on CentOS 7 and, I assume, RHEL 7 use [SystemD's PrivateTmp support](https://access.redhat.com/blogs/766093/posts/1976243) by default.  When the `httpd` process reads `/tmp`, it's actually reading from a private folder similar to `/tmp/systemd-private-*`.   As far as the `httpd` process is concerned, the `/tmp/*` directory temporarily used to alias `/.well-known/acme-challenge` doesn't exist, so an error is returned rather than what's expected.

## Workaround

It's possible to use a [SystemD drop-in](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/sect-Managing_Services_with_systemd-Unit_Files#brid-Managing_Services_with_systemd-Extending_Unit_Config) to override the `PrivateTmp` feature of the `httpd` service.  However, this is **not recommended** by the author of the [RHEL blog article](https://access.redhat.com/blogs/766093/posts/1976243) linked above.  The author recommends the use of `/run` or `/var/lib` instead.

```
sudo mkdir /etc/systemd/system/httpd.service.d

sudo tee /etc/systemd/system/httpd.service.d/no-privatetmp.conf > /dev/null << 'EOF'
[Service]
PrivateTmp=false
EOF

sudo systemctl daemon-reload
sudo systemctl restart httpd
```

## Other Notes

It's possible to get to the real tmp directory for httpd via the `/proc` directory, but I don't know if it's useful:

```
systemctl status httpd | grep "Main PID"
```

```
 Main PID: 30762 (httpd)
```

```
echo "testing for httpd tmp" > /proc/30762/root/tmp/test.txt
cat /tmp/systemd-private-19a42c88bf784b63af9846e509c36212-httpd.service-VCqHvj/tmp/test.txt
```

```
testing for httpd tmp
```

I think these types of issues are being tracked in #5409.

**Comment by bmw** [comment]
Thank you so much for the detailed issue here @ryanjaeb. I think this problem is pretty widespread as it at least also affects the newest Ubuntu (and I suspect Debian) releases. I knew nothing about this feature so you saved me quite the headache trying to figure it out.

We've moved the directory to Certbot's working directory which avoids this problem.

**Comment by christianlx** [comment]
Hi, 

I updated this post because I use an apache Web Server on Centos 7.x and I still encouter this issue
This server already host 6 https websites configured with let's encrypt. Since January, I cannot create anymorenew certificate for a new web site whereas renewals on old websites are working.

I've always have this message : 

Domain: www.hxxxxxxxxxxxxxxn.com
   Type:   unauthorized
   Detail: Invalid response from
   http://www.hxxxxxxxxxxxxxxxxxxn.com/.well-known/acme-challenge/ugFCIXCxjcnvFpPpv_cjvYBDRdCA-f8IVeEQU90VycY:
   "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
   <html><head>
   <title>403 Forbidden</title>
   </head><body>
   <h1>Forbidden</h1>
   <p"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.

Of course I've already checked a lot of things : the DNS record is good, my website is working fine on http and if I create manually the directory .well-known/acme-challenge with a single file inside, the URL is working

My certbot version is 0.21.1 with apache 2.4.6. Are you aware of an issue like this with this version.

Thanks.

Christian.

**Comment by bmw** [comment]
@christianlx, no I'm not aware of an issue here. Sorry to hear you're having trouble. I'd recommend you open a thread at https://community.letsencrypt.org/ as there's a larger community there to help look into the problem.

**Comment by christianlx** [comment]
OK thanks, I've created a thread here : https://community.letsencrypt.org/t/create-certificate-error-403-since-january/53489/10

But I'm still stucked for the moment with this 403 error whereas I don't have this issue on a similar configuration with Debian. For the moment I still have doubt on a centos specific bug on this.

**Comment by christianlx** [comment]
Bug confirmed. The 0.21.1 package put an incorrect permission on the httpd_challenges directory : 

namei -l /var/lib/letsencrypt/http_challenges/
f: /var/lib/letsencrypt/http_challenges/
dr-xr-xr-x root root /
drwxr-xr-x root root var
drwxr-xr-x root root lib
drwxr-x— root root letsencrypt
drwxrwxr-x root apache http_challenges

a chown root:apache /var/lib/letsencrypt/ command correct the issue.

**Comment by bmw** [comment]
Thanks for the update. I created #5602 to track that issue.
