### ISSUE TITLE
Certbot, how to specify static directory?

### ISSUE THREAD

**Issue by ckcollab** [certbot/certbot#5430]
Hey there! Thanks for certbot and providing so many wonderful things for free, it is appreciated!

I am having a simple problem: I don't understand how to specify the "webroot" static file path on my server. For example, my django static folder points to `https://mydomain.com/static/`, so any webroot authentication files end up at `https://mydomain.com/static/.well-known/acme-challenge/yaddayadda`

How do I specify the `"/static/"` path on my domain to look for `"/.well-known"`? I know this is probably obvious somewhere, but I've read quite a bit and still can't find it. I know someone like me will search for "certbot specify static folder" some day so this may help someone in the future, even if it is obvious :)

**Comment by jsha** [comment]
@ckcollab This is a great question, and it will depend on the details of your server setup, rather than the Certbot implementation. Can I ask you to re-post it at https://community.letsencrypt.org/? The forum is much better suited to a back-and-forth conversation, and more people follow it so it will be easier to get you the help you need. Thanks!
