### ISSUE TITLE
 No valid IP addresses found for… DNS A Record Exists and WORKS!

### ISSUE THREAD

**Issue by own3mall** [certbot/certbot#5433]
https://community.letsencrypt.org/t/no-valid-ip-addresses-found-for-dns-a-record-exists-and-works/50528

## My operating system is (include version):

CentOS 6

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

Downloaded from website manually

## I ran this command and it produced this output:

`/root/Downloads/certbot-auto certonly --webroot --agree-tos --email {EMAILHERE} -d php72.webehostin.com -w {PATH_HERE}`

```
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: php72.webehostin.com
   Type:   unknownHost
   Detail: No valid IP addresses found for php72.webehostin.com
```

## Certbot's behavior differed from what I expected because:

DNS resolves for me on EVERY machine... problem with Let's Encrypt DNS?

**Comment by SwartzCr** [comment]
@cpu any ideas?

**Comment by cpu** [comment]
@own3mall You have issues with your authoritative DNS servers. [unboundtest confirms as much](https://unboundtest.com/m/A/php72.webehostin.com/UXYYRQN6):

> Error running query: dns: failed to unpack truncated message

This isn't a problem the Certbot team can solve so I'm going to close this issue. I recommend you change DNS providers and see if the problem persists, or otherwise try to return to the community forum to solicit help debugging your authoritative DNS server's problems.

**Comment by own3mall** [comment]
Or your DNS system is busted.  Works just fine for everyone else on the planet.

**Comment by own3mall** [comment]
https://github.com/skynetservices/skydns/issues/45
https://github.com/mehrdadrad/mylg/issues/42

Looks like your software should be processing the "truncated message" regardless.  The rest of DNS appears to work this way... there is nothing WRONG with this setup.  Nothing out there says it's wrong officially anyways...

Sigh.

**Comment by cpu** [comment]
> If you noticed in the thread, a query against open DNS returned a successful response.

This does not discount an issue with your authoritative DNS servers. We make unboundtest.com available specifically because it emulates the same recursive resolver settings Let's Encrypt uses in production (0x20 case randomization, fully validating DNSSEC, etc).

> Also, if you ping it on any Windows or Linux system, you'll see DNS resolves,

Again, this does not discount an issue with your authoritative DNS servers. Performing a ping to do an A lookup with your local recursive resolver is not equivalent to the DNS lookups being done by Let's Encrypt.

**Comment by own3mall** [comment]
Why are you performing such a large lookup and why?  You should only be using an A record lookup.  

Also:

> Error running query: dns: failed to unpack truncated message

How am I supposed to troubleshoot an error your system generates when the output message doesn't tell me ANYTHING as to what is possibly wrong?

**Comment by cpu** [comment]
> How am I supposed to troubleshoot an error your system generates when the output message doesn't tell me ANYTHING as to what is possibly wrong?

This is an error from Unbound, not our own software. The configuration to set up your own instance of Unbound to troubleshoot is there. I also recommended that you move to the community forum if you need help understanding the problems.

I'm going to lock this issue now. As previously mentioned this isn't anything the Certbot team can help with, the problem exists in an entirely separate layer of technology than the ACME client you're using.
