### ISSUE TITLE
renew always renews certifcate despite "renew-by-default = False" in cli.ini

### ISSUE THREAD

**Issue by mogoh** [certbot/certbot#5451]
## My operating system is (include version):
debian jessie

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS Package manager

$ certbot --version
certbot 0.10.2

## The Problem
In my `/etc/letsencrypt/cli.ini`, I had this line which I expected to set the default explicit.
```
renew-by-default = False
```
I expected certbot to renew certificates only when they are close to expire.

## Instead
Instead, certbot renew always renews a the certificates.

**Comment by SwartzCr** [comment]
Interesting
The way that renew is expected to work is that it'll check all certs to see if they are in the renewal window and then renew them if they're within 30 days of exipiring. It will list all certs as it checks if they're up for renewal.
My guess is that this is an occurrence of #4407 
This was fixed in #4995, but the version that is packaged for jessie is old enough to still have this issue.
The solution should be to just remove that line from your cli.ini file, though it's possible that it is now in the renewal.conf files for your various certificates and will need to be removed from them as well.
Once you do that renewals should work as normally expected.
Sorry about this issue, but it was a problem that we inherited from our parsing library :(

**Comment by SwartzCr** [comment]
Let me know once you get things working again - or if you need help taking those steps

**Comment by mogoh** [comment]
> The solution should be to just remove that line from your cli.ini file, though it's possible that it is now in the renewal.conf files for your various certificates and will need to be removed from them as well.

Removing the line helped. It looks exactly like #4407. So I suggest we mark this bug as duplicated and if it turns out, that this is not the case, we reopen it.

Thank you for your help.
