### ISSUE TITLE
The 'certbot==0.19.0' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by sharoonamjid** [certbot/certbot#5454]
On Ubuntu 16.04, I have LEMP stack setup and also installed Python 3.5.2 for the use of LetsEncrypt.

When I run this command `sudo certbot --nginx` I get this error:
The 'certbot==0.19.0' distribution was not found and is required by the application

Can someone help me please to fix this problem?

**Comment by SwartzCr** [comment]
Can you please answer the questions that are listed in the new issue template?
Namely, how did you install certbot initially, what version do you have, and so on.
I'm happy to help you with figuring out what commands to run to get relevant information, but `dpkg -l | grep certbot` is a good first step

**Comment by schoen** [comment]
I'm closing this because we haven't heard back; if you or anyone else has this problem nowadays, please submit a new issue and we'll be happy to take a look!

A good reminder is to be sure to follow the current recommended installation instructions at

https://certbot.eff.org/

There can definitely still be problems, but often version and dependency problems arise when using alternative installation methods that aren't the ones that we suggest.
