### ISSUE TITLE
wildcard support

### ISSUE THREAD

**Issue by sneerin** [certbot/certbot#5470]
wildcard support is coming, so that would be incredibly awesome to get this desirable feature.

**Comment by SwartzCr** [comment]
Hi @sneerin - we are planning to get ready for the acme v2 spec that will allow wildcard support. If you want to follow our progress you can watch the issues labelled 'acme' in the 0.22.0 milestone: **https://github.com/certbot/certbot/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.22.0**
Since we're already tracking this I'm going to close this issue as a duplicate
