### ISSUE TITLE
Break lockstep between our packages

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5490]
As part of getting distros to package more of our plugins, we've agreed to stop releasing all of our packages in lockstep. This means that instead of requiring that all of our packages have the same version number, people are able to mix and match versions. The benefit of this is distros (and us) don't have to repackage everything anytime we change a single package.

To do this, we need to:

1. Modify each `setup.py` to depend on the oldest version of its Certbot dependencies that is needed to work. Some digging needs to be done to figure out what this version is.
2. Set up tests in Travis to ensure the minimum versions required stays accurate. This can be a mix and match between the test-everything branch depending on what makes the most sense.

**Comment by ohemorange** [comment]
My current thought is that rather than digging, we should set everything to the current version. It's faster and I don't currently see any drawbacks.

**Comment by erikrose** [comment]
I agree with @ohemorange. Add to it the complication that pip doesn't yet have a proper dependency resolver, so, if we required >=1.1 in one of our packages and >=1.2 in another, it's a toss-up which one gets obeyed.

**Comment by erikrose** [comment]
Just sat down and sketched out an approach with Erica. Basically amounts to…

* a tox config with pinned shallow versions of the minimum allowed dep versions
* installing the certbot packages with `--no-deps`
* declaring deps like `>=1.1.4,<=2.0` in the setup.py files

Then we'd have a second tox env that tests the latest versions of everything together, because that's a common real-world setup. We should probably just let pip do its thing for that rather than trying to keep up with a pinning; we will *want* to know when somebody does a release of a dep that makes things go bad.

**Comment by bmw** [comment]
Did you guys think about how to handle cases where different Certbot plugins require different minimum versions? We don't have that problem yet, but if the Apache plugin requires Certbot 1.0 and the Nginx plugin requires Certbot 1.1, do we just keep reordering our tests as this changes to test the plugins with the minimum required version first?

**Comment by erikrose** [comment]
No, but, on a brief minute of thought, it seems like that should be handled in the test suites of the individual plugins: Apache should test with certbot 1.0 and nginx with 1.1. Or were you thinking of still coupling the packages together under the auspices of one gigantic test suite? I'd suggest making a list of pros and cons, if so; there is probably value in decoupling "all the way".

**Comment by bmw** [comment]
The way that the unit tests currently work is for each Python version we have a tox environment that iterates over our packages installing and testing them. This looks something like:

1. Install acme.
2. Test acme.
3. Install Certbot.
4. Test Certbot.
5. Install certbot-apache.
6. Test certbot-apache.
7. Install certbot-nginx ...

This uses a single Python virtual environment for all tests. I think if we continue using a single environment like this, we have to install with minimum required version first, otherwise, something like the following happens:

1. certbot-nginx is installed and tested with Certbot 1.1
2. certbot-apache is installed with Certbot 1.0 and setuptools complains that Certbot 1.1 is needed for certbot-nginx.

I'm certainly open to doing this differently. Hopefully we don't need a separate toxenv for each plugin and for each Python version we want to test it against though. That's a lot of toxenvs/Travis' jobs.

**Comment by erikrose** [comment]
I don't have a super-strong opinion about it. If you want to optimize for fast Travis runs, maintaining the test setup becomes an error- and work-prone human task. Going the other way inverts both of those.

**Comment by bmw** [comment]
Going the other way meaning to build that toxenv matrix of X packages times Y Python versions?

Not to get too off topic, but related to this I've been considering trying to break this repo into separate repos for each piece which would make testing like this more natural in my opinion. Do you have any opinions on this?

**Comment by erikrose** [comment]
I'm +1 on multiple repos (one per plugin, right?) iff we decouple the tests. It's what most of the tools assume, so it cuts down on the exceptional config we have to write/maintain/teach. As for Travis efficiency, we should be able to use their caching to avoid having to reinstall heavy deps like acme or certbot itself all the time. As a first cut, I'd suggest a {Python versions} * {oldest-supported deps, newest deps} Travis matrix. The "tox config with pinned shallow versions of the minimum allowed dep versions" I suggested above shouldn't be a problem: being shallow, it won't require looking at any information outside the current plugin's repo.

**Comment by bmw** [comment]
The shallow dep list is a great idea. I have a couple minor concerns:

1. What happens when the oldest version of dep we need to support for Python 2.7 distro packaging doesn't work on a newer Python like 3.6?
2. What happens when a new version of a dependency drops support for a Python version we're still supporting?
3. Do we want to maintain a deep list of dependencies of the plugin that aren't maintained by us for increased stability for devs and real testing of old package versions? For example, if a package didn't pin back the next major versions of its dependencies, an old version of the package may break.

But I'm not planning on splitting everything immediately right now. To get a basic version of these tests up and running, I'm planning on sticking with our current test structure and have the tests for the oldest dependency versions ordered so the plugins that allow an older acme/certbot versions are tested before the ones that require a newer version. With the good idea of not looking backward to see what versions are supported, the only difference will be the last packaged version and plugins that require changes from master. If you have a problem with this approach please let me know.

Continuing on my separate repo tangent if you don't mind, the biggest concern I have is trying to make things sane for devs that are adding changes to acme/certbot to be immediately used in a plugin. For example, we often add functionality for the Apache/Nginx that we expect to be more generally useful to `certbot/plugins/common.py`. Will devs be able to (easily) check out a branch of acme/certbot to use for plugin development or do they have to wait for the changes like this to land in master before working on the plugin? How do we keep the version of acme/certbot used for plugin development up to date with master? Hopefully they don't have to recreate the virtual environment each time they want to pull in the most recent changes. I've personally never worked on a project structured in this way so if you have ideas here I'd love to hear them.

**Comment by erikrose** [comment]
1. Good question. [Platform-specific deps can be expressed with setuptools](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-platform-specific-dependencies), which is nice. If this corner case happens, we may have to expand the matrix to {Python 2 versions} * {oldest-supported Python 2 deps, newest deps} + {Python 3 versions} * {oldest-supported Python 3 deps, newest deps}. Do you see this scenario coming? I'd try other things first, like nudging the distro to package a newer version of the dep.
2. A dep shouldn't drop support for a Python version without itself having a major version bump, so our pinnings should take care of us. Otherwise, we'll have to retroactively pin the upper end of our range more tightly.
3. Instead, I would add a recommendation to "pin back" major versions in our documentation for plugin developers. It's extra work, and it's unlikely that whatever combination of packages we pin would be representative of what end-users would see anyway. Letting devs see breakage when pip-installing their stuff would incent them to fix it.

> If you have a problem with this approach please let me know.

I don't really have a grip on what you're proposing. Can you break it down step by step, as in "First, we install an old version of certbot, then we…"?

> Will devs be able to (easily) check out a branch of acme/certbot to use for plugin development

Sure, why not? You check out what you want, then you do `pip install -e .` in the checkout dirs.

> How do we keep the version of acme/certbot used for plugin development up to date with master?

Is there really so much branch-dependent plugin dev going on before a release that we have to keep merging master back in? We release about weekly, after all.

We're not depending on the plugins to act as tests for our mainline features, are we? If we split the repos, part of the process should be making sure there are tests for each API in the package that provides the API.

**Comment by bmw** [comment]
Thanks for all your thoughts. I'll respond to all comments soon, but for now I'll only respond to this comment as it's the most pressing as we need to break lockstep between our packages for the next release which requires we change our testing a bit.

> I don't really have a grip on what you're proposing. Can you break it down step by step, as in "First, we install an old version of certbot, then we…"?

So my goal here is to delay major testing refactoring until we're not under a tight [deadline for ACMEv2](https://letsencrypt.org/2017/12/07/looking-forward-to-2018.html#new-features). (You should be happy to know I'm pushing my managers to give us time for code health, refactoring, testing, stability work like this and #4947 after this release though.)

With this in mind, I'm using our current testing setup which has some tests that test against the oldest versions of our dependencies we support and another that test against the newest. I'm not going to make any changes for the ones that test against the newest versions, but for the oldest versions, I'm planning to do something like:

1. Install latest acme.
2. Test acme.
3. Install certbot and oldest version of acme it supports.
4. Test certbot.
5. Install plugin X and oldest version of acme/certbot it supports.
6. Test plugin X.
7. Install plugin Y and oldest version of acme/certbot it supports.
...

This is currently what the tests do except they previously didn't have to worry about installing older versions of acme/certbot. Plugins will be installed and tested sorted in the order from oldest to newest versions of the dependencies they require. This sorting will be pretty minor since the oldest version we're going to support for all plugins is either the last release or the latest version in master.

**Comment by bmw** [comment]
For each package:

1. Install package and oldest versions of its dependencies.
2. Test package.
3. Uninstall all packages from venv.

This would be a fairly minor change for our oldest tests and would resolve the problems with conflicting oldest versions.

**Comment by bmw** [comment]
@erikrose, a more minor detail here, do you have any thoughts on the best way for the oldest tests to sometimes install ACME/Certbot from PyPI and other times install the version from the git repo? (I suppose we could always use the git repo by using the release tag if that makes it easier.)

**Comment by erikrose** [comment]
Your 7-point example for testing against old deps seem sane. The only thing to watch out for is that, if you install an old acme with its old deps, then uninstall acme and install a new acme, some of the old deps will remain instead of getting updated to the latest, since they technically fulfill the requirements. I'm not sure if you were planning on wiping the venv between tests, but it's a good idea. Likewise, for step 3 just above, recreating the venv is probably faster and certainly less error-prone than trying to uninstall all the packages.

> any thoughts on the best way for the oldest tests to sometimes install ACME/Certbot from PyPI and other times install the version from the git repo?

Sure, git URLs are perfectly cromulent lines in a requirements file (though hash-checking might get grumpy about them, but hash-checking isn't so vital for tests, perhaps).
