### ISSUE TITLE
python-certbot-nginx std install not restarting nginx after cron successful renewal?

### ISSUE THREAD

**Issue by nodje** [certbot/certbot#5496]
## My operating system is (include version):
Debian 9 Stretch

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt-get install python-certbot-nginx (without backport)
So I'm running v0.10.2 (and was wondering why it was so outdated until I cam to realise I didn't use the backport version)

Which leads me to the question: Is there any use to bother adding the dedicated PPA on Debian/Ubuntu? Or is using backport just fine?

## Certbot's behavior differed from what I expected because:
I use the `webroot` style for authentication.

I added my own cron command for renewal and while investigating why I got an expired certificate alert on my website, I came to understand the existence of the `/etc/cron.d/certbot` 

In effect I just had to restart nginx for it to pickup the renewed cert.

A log analysis showed that it wasn't MY cron that did the last renewal, and thus explained why the`--renew-hook "systemctl restart nginx"` I bothered to add to it didn't kick.

So I'm wondering why this nginx restart hook doesn't exist with the provided `/etc/cron.d/certbot` ?
How is Nginx supposed to restart? Didn't I see the hook somewhere maybe?

I've now seen in the doc the `/etc/letsencrypt/renewal-hooks` structure, but it just doesn't exist with this version by default.

Is it just that this version is too old and didn't include the restart hook for the `webroot` auth method? I'd be surprised it wasn't part of the feature with a provided cron for cert renewal.

Also, it's nice to have an automatic log management (very nice indeed, and it is documented on the website) but it's not easy to understand when you're looking at the command line: I couldn't see any logrotate policy or any indication in the documentation as for where this rotation policy is implemented and configured. It'd be nice to have clues in the system (again maybe it's done differently in newer version?)

Thanks!

**Comment by SwartzCr** [comment]
Sorry about the confusion. Let me see if I can answer some of your questions:
On debian it is worth it to use the backports version, as that will ensure you have the newest packaged version. Since you're on debian and not ubuntu you should not use the ubuntu ppa. Ubuntu users should use the ppa since they don't have a debian backport option.
As for the lack of restarting it's possible that the built in renewal job restarted nginx as root but your hook is being run as your user. It's also possible that you also have a systemd timer that is being used instead of the cron job - I'm not sure what the status for version 0.10.2 is but maybe @hlieberman can answer that.
As far as documentation about this and the log rotation, we've written it up but it's not on the website yet, you can view it in plaintext here: https://github.com/certbot/certbot/pull/5460/files
