### ISSUE TITLE
Can no longer renew certificates with no warning or useful explanation

### ISSUE THREAD

**Issue by tufelkinder** [certbot/certbot#5511]
## My operating system is (include version):

Ubuntu 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

I installed certbot from the instructions on the certbot page, and then updated it using pip to version 0.21.

## I ran this command and it produced this output:

certbot 
Output: I have exceeded the renewal rate limit

certbot --staging
Output: Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA.

## Certbot's behavior differed from what I expected because:

It should have renewed my certs OR reported an issue. Instead, it simply said it was unable to connect to the server and now reports that I've exceeded the rate limit. How can I exceed the rate limit if it was unable to connect?

This is incredibly frustrating and disappointing. Even when the rate limit expires, I still do not expect to be able to renew since the staging command also produces errors.

**Comment by SwartzCr** [comment]
Hi - are you saying that you've installed Certbot via the ppa and then again via pip?
This implies that you have two versions of certbot running.
To know why you've exceeded your rate limit it would help to know what commands you've run recently or if you've tried to process any renewals. Can you share some recent error logs?
Additionally it's possible that the staging server is refusing your connection because you're specifying a TLS-SNI-01 authentication which is no longer supported: https://community.letsencrypt.org/t/2018-01-11-update-regarding-acme-tls-sni-and-shared-hosting-infrastructure/50188
If you could also include some information about what certificates you have and what methods you used to generate them that would be helpful as well.

**Comment by schoen** [comment]
This problem and its solution are most recently described at

https://community.letsencrypt.org/t/how-to-stop-using-tls-sni-01-with-certbot/83210

I hope that's helpful to anyone finding this issue here.
