### ISSUE TITLE
Version 1.0.0

### ISSUE THREAD

**Issue by evanp** [certbot/certbot#5516]
## My operating system is (include version):

Ubuntu 17.10

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

Docker

## I ran this command and it produced this output:

docker run -v /etc/letsencrypt:/etc/letsencrypt -v /var/log/letsencrypt:/var/log/letsencrypt -it certbot/certbot --version

certbot 0.21.1

## Certbot's behavior differed from what I expected because:

Let's Encrypt supports 61 million domains (
https://letsencrypt.org/2017/12/07/looking-forward-to-2018.html
). I don't know what percentage of those use certbot to get their certs, but my wild-ass guess would be >50%.

Software that is used in production by tens of millions of sites should not be marked as "pre-production" software with version 0.x. It's not 100% clear that certbot follows the Semantic Versioning standard, but here's the suggestion from semver.org on when to release 1.0.0 (https://semver.org/#how-do-i-know-when-to-release-100):

> How do I know when to release 1.0.0?

> If your software is being used in production, it should probably already be 1.0.0. If you have a stable > API on which users have come to depend, you should be 1.0.0. If you’re worrying a lot about 
> backwards compatibility, you should probably already be 1.0.0.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

No output to the logs, AFAICT

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

N/A

**Comment by SwartzCr** [comment]
Hi @evanp - thanks for writing.
I understand your desire for us to release version 1.0 but there are a few reasons we haven't.
First off we are waiting until we feel like we're in line with the ACME spec. Since the ACME spec will be changing soon we shouldn't release 1.0 until after we're confident that we support ACME v2.
Additionally we have a lot of features that we feel are necessary for our 1.0 release, you can look over them in the 1.0 milestone: https://github.com/certbot/certbot/milestone/8
I'm going to close this, since we're already tracking 1.0.0, but @bmw can respond if he feels differently about our timeline and versioning

**Comment by evanp** [comment]
Hi, @SwartzCr . I'm not asking you to release 1.0.0; I'm asking you to recognize that you've already released it. You're in production with tens of millions of users. It's a good idea to recognize this reality and mark your version as 1.0.0, and start using semantic versioning for future releases.

It seems like you've set 1.0.0 as the Never Never Land future version. If it were me, I'd mark what's available now as 1.0, start looking at compatible changes for the 1.x version line, and move incompatible changes to 2.x. That's what people have come to expect from semver.

Good luck, and thanks for making a great product that has changed the Web!

**Comment by bmw** [comment]
@evanp, I largely agree with you. A number of us have had this conversation internally.

Since our first non-development release of 0.1.0, we've largely treated Certbot like it was 1.0+. We have had stable APIs and spent a lot of time avoiding making breaking changes. Our initial hesitation about calling it 1.0 was that we weren't sure if the software was production ready. Certbot 1.0 was launched the same day as you could obtain trusted certificates from Let's Encrypt so before that it hadn't seen much real world usage. Over the 2+ years since that release, we've been installed and run regularly on millions of web servers and feel much more confident about Certbot's abilities here.

Honestly, the only reason we haven't declared Certbot 1.0 is it's a PR opportunity for us to make noise about Certbot and bring attention to features people have missed since the initial release. We plan to make use of that soon, but thanks for the nudge here and you can feel confident that Certbot's not going to suddenly change it's behavior on you.
