### ISSUE TITLE
Error when attempting to run certbot

### ISSUE THREAD

**Issue by birdvidorg** [certbot/certbot#5527]
## My operating system is (include version): Ubuntu 16.04

I received the following error when attempting to set up letsencrypt via certbot: 
An error occurred and we failed to restore your config and restart your server.  Please submit a bug report to https://github.com/letsencrypt/letsencrypt

**Comment by schoen** [comment]
Hi @birdvidorg, did you also happen to try to get any help on the Let's Encrypt Community Forum?

Do you have the logs available from `/var/log/letsencrypt` so that we can understand more about the circumstances of this error?

How did you install Certbot, and do you know what version of Certbot you're using?

**Comment by birdvidorg** [comment]
No, I got my answer here: https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/
