### ISSUE TITLE
Error first setup letsencrypt using Digital Ocean

### ISSUE THREAD

**Issue by KhairulAzmi21** [certbot/certbot#5535]
## My operating system is (include version):
Ubuntu WordPress 4.9.1 on 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-16-04

## I ran this command and it produced this output:
sudo certbot --authenticator standalone --installer apache --pre-hook "systemctl stop apache2" --post-hook "systemctl start apache2"
<img width="782" alt="screen shot 2018-02-05 at 11 02 39 pm" src="https://user-images.githubusercontent.com/12378983/35811155-b66eee98-0ac8-11e8-850a-4f92f1373767.png">

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

<img width="874" alt="screen shot 2018-02-05 at 11 03 15 pm" src="https://user-images.githubusercontent.com/12378983/35811189-cfdae602-0ac8-11e8-9287-4ebbc7b2f8a1.png">

**Comment by schoen** [comment]
Hi @KhairulAzmi21 

Could you please ask about this on the forum? 

https://community.letsencrypt.org/

Thanks! There are a lot more people there who should be prepared to help.

This error is strange and makes me wonder if you tried to rename things or reorganize things within `/etc/letsencrypt` somehow. But it would be better to continue that conversation over on the forum rather than in this issue tracker. (If we determine that Certbot gets into this confused state on its own, we can certainly re-open this issue here.)
