### ISSUE TITLE
Certbot 0.21.1 installed & cert created; cannot access domain on HTTPS

### ISSUE THREAD

**Issue by eicksl** [certbot/certbot#5541]
## My operating system is (include version):
Ubuntu 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS package manager

## I ran this command and it produced this output:
See below.

## Certbot's behavior differed from what I expected because:
`mod_ssl` and the `default-ssl` vhost are enabled. No errors were displayed while creating the cert, yet when I try to access the domain via HTTPS it times out. Checking on https://www.ssllabs.com/ssltest I get:

"Unable to connect to server - failed to connect to the server, it usually happens due to firewall restrictions"

Ports 80 and 443 are open for incoming and outgoing connections.

Apache2's `access.log` also does not contain any connection attempts for HTTPS.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
No log seems to be available for the correct date.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
```<IfModule mod_ssl.c>
<VirtualHost *:443>
 ServerName aevasun.com
 DocumentRoot /var/www/Portfolio-Webpage
 ErrorLog ${APACHE_LOG_DIR}/error.log
 CustomLog ${APACHE_LOG_DIR}/access.log combined
Include /etc/letsencrypt/options-ssl-apache.conf
Include /etc/letsencrypt/options-ssl-apache.conf
Include /etc/letsencrypt/options-ssl-apache.conf
SSLCertificateFile /etc/letsencrypt/live/aevasun.com/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/aevasun.com/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
<IfModule mod_ssl.c>
<VirtualHost *>
 ServerName aevasun.com
 DocumentRoot /var/www/Portfolio-Webpage
 ErrorLog ${APACHE_LOG_DIR}/error.log
 CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
</IfModule>```

**Comment by trinopoty** [comment]
Your virtualhost block is malformed.
The first `</IfModule>` does not have a corresponding `<IfModule>`.
The 2nd `<VirtualHost *>` is incorrect; it should be `<VirtualHost *:80>`

**Comment by eicksl** [comment]
Thank you for the reply. Sorry for not catching that. This file was automatically generated when running certbot. Actually, the first `<IfModule>` does exist (I clumsily left out the first line when I copied the code). The code inside the second `IfModule>` seems to have been automatically copied from my previous configuration file and I have edited it as you suggested. The entire file now looks as such:
```
<IfModule mod_ssl.c>
 <VirtualHost *:443>
  ServerName aevasun.com
  DocumentRoot /var/www/Portfolio-Webpage
  ErrorLog ${APACHE_LOG_DIR}/error.log
  CustomLog ${APACHE_LOG_DIR}/access.log combined
  Include /etc/letsencrypt/options-ssl-apache.conf
  SSLCertificateFile /etc/letsencrypt/live/aevasun.com/fullchain.pem
  SSLCertificateKeyFile /etc/letsencrypt/live/aevasun.com/privkey.pem
 </VirtualHost>
</IfModule>
<IfModule mod_ssl.c>
 <VirtualHost *:80>
  ServerName aevasun.com
  DocumentRoot /var/www/Portfolio-Webpage
  ErrorLog ${APACHE_LOG_DIR}/error.log
  CustomLog ${APACHE_LOG_DIR}/access.log combined
 </VirtualHost>
</IfModule>
```

One curious thing is that both `<IfModule>` statements take `mod_ssl.c` as a condition which seems weird. Perhaps the second one should be changed? And if so, to which module?

By the way, it's still not working in case that's not clear. I also disabled the original configuration file and restarted apache, but no success.

**Comment by trinopoty** [comment]
The `<VirtualHost *:80>` should not be inside a `<IfModule mod_ssl.c>`. Move the 2nd VirtualHost block outside of all `IfModule` blocks.
If it still does not work, there's another problem. The problem is difficult to deduce without looking at the full configuration but I can think of a few things.

- Use `apachectl configtest` to check the configuration
- If apache does not start (check with `ps` to be certain) and the ports are set to listening in netstat, another http server exists on your system.

Also, I think the there should be a `<Directory>` block somewhere for `/var/www/Portfolio-Webpage`; check if that exists. A missing `<Directory>` block sometimes causes 403 errors.

**Comment by trinopoty** [comment]
Looking at the message you posted, "Unable to connect to server - failed to connect to the server, it usually happens due to firewall restrictions". If an external server is unable to connect to your server, there can be one of few problems.

- The apache server is not running.
- As mentioned, the firewall is blocking incoming connections. Could be a network firewall that sits before your server.
- Without more information, maybe a NAT device between your server and the internet? In which case, ports 80 and 443 need to be forwarded to your system.

**Comment by eicksl** [comment]
Thank you again for the reply. The issue is now resolved. Bit of a mental lapse on my part. I'm using an Amazon Lightsail instance and forgot that I also needed to open port 443 via the Lightsail console. Opening ports with `ufw` alone is insufficient.

I also had a bit of trouble getting it to work with my WSGI app as per [this issue](https://github.com/certbot/certbot/issues/1820). I commented out the `WSGIDaemonProcess` statement in the SSL module and now it seems to be working fine.
