### ISSUE TITLE
certbot-auto no longer  working on ClearOS 6

### ISSUE THREAD

**Issue by emil-totev** [certbot/certbot#5544]
## My operating system is (include version):
ClearOS 6 (Based on CentOS / RHEL 6)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
I installed certbot-auto almost an year ago

## I ran this command and it produced this output:
#./certbot-auto renew
Bootstrapping dependencies for RedHat-based OSes that will use Python3... (you can skip this with --no-bootstrap)
yum is /usr/bin/yum
No supported Python package available to install. Aborting bootstrap!
## Certbot's behavior differed from what I expected because:

I have last renewed the certificate on 28.11.2017 and it worked OK.

## More comments
It seems the problem is that either certbot-auto is not detecting correctly the distribution/release, or it has stopped working with python 26.

**Comment by schoen** [comment]
@bmw, do you know what's going on here?

**Comment by bmw** [comment]
Hi @emil-totev, sorry for the trouble.

Unfortunately, I'm not familiar with ClearOS, but I'll tell you what certbot-auto is doing on RHEL 6 based systems and maybe you can tell me what's going wrong. In our last major release, we deprecated support for Python 2.6. Now when you run certbot-auto on RHEL 6 based systems, it tries to install Python 3.4 from [EPEL 6](https://fedoraproject.org/wiki/EPEL), letting `yum` prompt you to agree/disagree with this.

The way this works is it first checks if EPEL needs to be enabled. It does this by running:
```
yum list *virtualenv
```
If this command exits with a zero status, we assume EPEL is already enabled. If it does not, we either error out asking you to enable EPEL or try and do it ourselves letting `yum` prompt for your permission.

I suspect our detection of EPEL is off on ClearOS because `yum` as run by certbot-auto is not finding the Python 3 packages available in that repo. The packages it's looking for is python34, python34-devel, and python34-tools.

I'd like to get more information from you so we can try and work around this problem automatically in the future, but as a workaround you could try making sure the EPEL 6 packages are available to `yum` and try running `certbot-auto` again.

**Comment by emil-totev** [comment]
ClearOS  actually have their own "EPEL" in repository clearos-epel.
```
# yum list *virtualenv
Loaded plugins: clearcenter-marketplace, fastestmirror
ClearCenter Marketplace: fetching repositories...
.....................
Installed Packages
python-virtualenv.noarch               1.10.1-1.el6                @clearos-epel
```
So probably you should parse the output in order to get the correct repository name.
In my case it was disabled, but running
```
yum install python34 --enablerepo=clearos-epel
```
installed it, and then certbot-auto was able to finish its job.

Thank you very much for your assistance! Let me know if I can be of more help.

**Comment by keith-mojo** [comment]
It should be noted that the EPEL repo must be Enabled for this to work.
I had to edit /etc/yum.repos.d/epel.conf and set enabled=1 before certbot-auto could install the necessary packages.

May I suggest that certbot-auto be modified to run "yum --enablerepo=epel".

**Comment by bmw** [comment]
> May I suggest that certbot-auto be modified to run "yum --enablerepo=epel".

I suspect the repo not being enabled caused the initial problem in this issue. We currently don't provide any flags like this to `yum`. My only concern with this is if the name of the repo varies on different systems. Apparently it's clearos-epel on ClearOS for example.
