### ISSUE TITLE
Should install/enhance take --domains?

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5551]
Proposed for the install subcommand by Peter at https://github.com/certbot/certbot/pull/5536#issuecomment-363185524. The enhance subcommand works in a similar way by making use of an existing cert so Joona is considering this behavior for that command as well.

Do we want to do this? Should the behavior be identical?

**Comment by pde** [comment]
My default argument would be that all of Certbot's verbs should allow things to be specified in the same ways. Since `certonly` and `run` do this, it will be less confusing if all the verbs do. Though I could also see the case for erroring out if there are multiple plausible (valid, matching) lineages, and asking the user to provide a disambiguating `--cert-name` in that case.

**Comment by ohemorange** [comment]
If this takes any level of annoying work or refactoring, I don't think it's worth it because:
a) our subcommands already don't match each other on the specifiers they take
b) it makes sense for certonly/run to take domains because you need domains to request a cert, but if an operation is actually being done on a cert then it should take the cert, and not try to figure out which cert you actually meant based on domains. this is especially true if we're using the domains to find a cert, then updating the list of domains with the list of domains in the cert
