### ISSUE TITLE
Better support for running in primarily read-only embedded environments

### ISSUE THREAD

**Issue by stevebovy** [certbot/certbot#5556]
## My operating system is (include version):

Linux RT-AC66U_B1 2.6.36.4brcmarm #1 SMP PREEMPT Wed Jan 31 17:32:52 CST 2018 armv7l GNU/Linux

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

With Imbedded OS;  the majority OF the  OS  file System is Read Only; any installation
program must be configured to install in alternate locations where things can be saved in a permanent 
location;  basically there are two locations  /jffs  OR   a usb  thumb/hardrive or mmc flash card 

the usb mounts are in /mnt   and the flash is in /mmc 
 
Can we add new options to control where all the os files and dependencies are installed?

I  will try running it as-is but It is likely to fail or worse-> disappear after a reboot

**Comment by schoen** [comment]
Hi @stevebovy,

This is a great idea, but I don't think it's something that we'll be able to address quickly because it may touch a great many different areas of Certbot and not many people have been asking for this.

I hate to send people away to other ACME client projects because I don't want to make it sound like we don't care about particular use cases, but have you looked at some of the other ACME clients to see if one of them might already meet your needs?

https://community.letsencrypt.org/t/list-of-client-implementations/2103

You can see that there are quite a few different client options, not just Certbot. Notably Certbot has tried to provide a very convenient experience for new users, including the installer functionality that helps to install the new certificate in a web server, and the renewer that helps to autorenew certificates when they're near expiry. However, some of the other clients are much lighter weight in terms of their functionality, size on disk, memory consumption, and dependencies, and also create fewer temporary and configuration files than Certbot does. So you might find that one of the other clients would be more suitable for your embedded application, including just because many of them have significantly fewer dependencies than Certbot. Many of them are rather reliable and easy-to-use.

Since other clients don't typically have installers to edit server configurations, you'd still need to figure out how to handle that part yourself if you used a different client.

**Comment by stevebovy** [comment]
Thanks for the reply :)

 

Yes : I have been trying  to find a shell script client that does not have a boat-load of pre-reqs.     It is an interesting challenge trying to hack your way  thru

Undocumented router firmware which could be based on multiple different sources
