### ISSUE TITLE
Can i test my renew-hooks via certbot?

### ISSUE THREAD

**Issue by victor-lund** [certbot/certbot#5568]
certbot 0.10.2
Debian Jessie

I've created the directories:

/etc/letsencrypt/renewal-hooks/pre/ 
/etc/letsencrypt/renewal-hooks/post/ 
/etc/letsencrypt/renewal-hooks/deploy/

and put som scripts in them. Nothing fancy, just echoing some timestamps to a log file, and restarting nginx.

So I thought I'd test if the scripts ran properly by executing:

`sudo certbot renew --noninteractive --force-renewal`

But the log file appears to be empty. Are the renew-hook scripts not suppose to be fired when i run the command above? Is there a way I can test my scripts without waiting until the certificates needs to be renewed?

Many Thanks!

**Comment by schoen** [comment]
Hi @victor-lund,

I think this is a problem with your Certbot version. According to our changelog, Certbot's support for renewal hook directories was only added in version 0.19.0. So this functionality isn't yet present in your version of Certbot.

There are various ways that you can get a newer version of Certbot if you'd like, but you'll probably have to go outside of your OS package repositories in order to do so.

I was going to suggest that you could emulate this behavior by making a single script that calls `run-parts` on the appropriate directory and then calling that script as a hook, but even `--deploy-hook` was only added in 0.17 (the corresponding hook would have been called `--renew-hook` in 0.10.2).

By the way, `certbot renew` is always noninteractive, so you don't have to specify `--noninteractive` to make it so.

**Comment by victor-lund** [comment]
@schoen 

I tried the same on a system with the following specs

certbot 0.21.1
Debian Buster

I still couldn't get the scripts to execute when running:
`
sudo certbot renew --logs-dir /home/user/certs/logs --work-dir /home/usercerts/work --config-dir /home/user/certs/conf --force-renewal`

These are my scripts:

cat /etc/letsencrypt/renewal-hooks/pre/testscript
```
#!/bin/sh 
DATE=`date '+%Y-%m-%d %H:%M:%S'`
echo $DATE "Pre hook ran." >> /var/log/le-renew.log
```

cat /etc/letsencrypt/renewal-hooks/deploy/testscript
```
#!/bin/sh 
DATE=`date '+%Y-%m-%d %H:%M:%S'`
echo $DATE "Deploy hook ran." >> /var/log/le-renew.log

/bin/systemctl reload nginx >> /var/log/le-renew.log
```
Can someone see what i'm missing here?

**Comment by victor-lund** [comment]
@schoen Can you re-open this issue, please?
