### ISSUE TITLE
I'm trying to config certbot for nginx with command sudo certbot --nginx, and now my site not available. What's wrong?

### ISSUE THREAD

**Issue by artemzakholodilo** [certbot/certbot#5572]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Ubuntu trusty trust

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt-get

## I ran this command and it produced this output:
sudo certbot --nginx

## Certbot's behavior differed from what I expected because:

Congratulations! You have successfully enabled https://numi.ru.darovec.com.ua
and https://my.numi.ru.darovec.com.ua

You should test your configuration at:
https://www.ssllabs.com/ssltest/analyze.html?d=numi.ru.darovec.com.ua
https://www.ssllabs.com/ssltest/analyze.html?d=my.numi.ru.darovec.com.ua

**Comment by artemzakholodilo** [comment]
I see that kerberos already installed on my server and listen port 88

**Comment by bmw** [comment]
What's the problem here? `sudo certbot --nginx` was able to obtain a certificate and install it for use with your Nginx webserver. Looking at ssllabs though, it looks like your server isn't reachable.

I'd like to encourage you to ask for help at https://community.letsencrypt.org/ as they'll be able to better help you debug any problems you're having. If a problem with Certbot gets identified, feel free to open an issue here. If I missed something and you'd like me to reconsider, please comment and I'll consider reopening.
