### ISSUE TITLE
Authz for wildcard vs base domain

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5613]
In a number of places, we store authorizations as a mapping from domains to its authorization. This is a problem because when requesting a single certificate for *.example.org and example.org, boulder returns an order with two authorizations for example.org. The authorization for the wildcard includes `wildcard: true` in the authz, but this doesn't seem to be in the ACME spec.

I'm sure we can find a way around it, but @jsha, is there anything I'm missing in the spec that we can rely on to map authzs back to their domains for an arbitrary ACMEv2-style server?

**Comment by jsha** [comment]
Each authz has an identifier in it. In the `*.example.com, example.com` case, you'll have two authzs with the same identifier. You could represent these with a multimap, or a map to a list.

**Comment by bmw** [comment]
Sure, but as an example of the problem we're having, if you use `--allow-subset-of-names` with a request for *.example.org and example.org and you fail one of the challenges, there's no way for us to tell which domain you failed the authorization for so we can remove it from the request.

This also affects our ability to map the failed authorization back to its domain in error messages about what went wrong. I don't see a reliable way around these problems, but I wanted to double check I'm not missing anything. This seems like a side effect of requesting all authorizations at once rather than an authorization per identifier.

**Comment by jsha** [comment]
> This seems like a side effect of requesting all authorizations at once rather than an authorization per identifier.

To be pedantic, it's not an issue of requesting all authorizations at once, but of having multiple authorizations with the same identifier. For instance, say we were using the new-authz flow but established the policy "If you want to issue for `*.example.com` and `example.com` you need to get two authzs with the same name, and pass a wildcard flag to one of them," we would have the same issue.

> if you use --allow-subset-of-names with a request for *.example.org and example.org and you fail one of the challenges, there's no way for us to tell which domain you failed the authorization for so we can remove it from the request.

The typical case should be: If the validation for `*.example.com` fails, almost certainly the validation for `example.com` will have failed also, because it's validating the same thing. IMO the logic should be: For any failed authorization, look at its identifier and remove that identifier, plus any `*` variants of it, from the next request. I realize this winds up encoding some logic that might be specific to Let's Encrypt, but I think it's worthwhile to make this thing "just work".

**Comment by bmw** [comment]
> To be pedantic, it's not an issue of requesting all authorizations at once, but of having multiple authorizations with the same identifier. For instance, say we were using the new-authz flow but established the policy "If you want to issue for *.example.com and example.com you need to get two authzs with the same name, and pass a wildcard flag to one of them," we would have the same issue.

That's true.

> The typical case should be: If the validation for *.example.com fails, almost certainly the validation for example.com will have failed also, because it's validating the same thing. IMO the logic should be: For any failed authorization, look at its identifier and remove that identifier, plus any * variants of it, from the next request. I realize this winds up encoding some logic that might be specific to Let's Encrypt, but I think it's worthwhile to make this thing "just work".

That's a good idea. For now I'm planning on just not supporting `--allow-subset-of-names` with wildcards (which isn't a breaking change because we've never supported wildcards). Failed validation error messages will just show the base domain for now.
