### ISSUE TITLE
Cannot run ./certbot-auto on CentOS 6.0, python 2.6.5

### ISSUE THREAD

**Issue by arthibald** [certbot/certbot#5642]
## My operating system is (include version):
CentOS 6.0

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
./certbot-auto --no-bootstrap --no-self-upgrade
_Creating virtual environment...
Cannot find any Pythons; please install one!_

python --version
_Python 2.6.5_

## Certbot's behavior differed from what I expected because:
It says that python 2.6 is supported

If I go into the script and force the PYVER to 26, it still breaks:
_virtualenv: command not found_

**Comment by sydneyli** [comment]
`certbot` very recently dropped [Python 2.6 support](https://github.com/certbot/certbot/issues/5489) . It looks like we have to update the documentation [here](https://github.com/certbot/certbot/issues/5642)!

**Comment by bmw** [comment]
`certbot-auto` on CentOS 6 has deprecated support for using Python 2.6 and it will stop working entirely in the next release.

What's going on here is that normally `certbot-auto` will walk you through installing Python 3 from EPEL6, but you've included `--no-bootstrap` on the command line so it's skipping that step and failing to find Python 3 later. This error message is misleading as the real problem is it's expecting Python 3 to be available and I'm sorry about that, but again, support is going away in the next release so this case is going away. In the next release you'd see:
```
You have an ancient version of Python entombed in your operating system...
This isn't going to work; you'll need at least version 2.7
```
If you want to work around this problem for now, try setting the environment variable `LE_PYTHON` to the name or path of your Python 2.6 executable. This will continue to work as long as you keep `--no-self-upgrade` on the command line, although doing so will exclude you from any new features and security fixes to Certbot.

**Comment by arthibald** [comment]
Ah, thanks guys. I was a bit worried about the dual install of python affecting the OS.
I tested it without the flags and with a reboot and it seems like the script took care of all that for me.

Magic!

**Comment by boomsya** [comment]
the same problem. Centos 6. Certbot-auto 1.3.0.
![111](https://user-images.githubusercontent.com/8008462/77760196-a236b900-703e-11ea-97f9-c70a86a007be.jpg)
