### ISSUE TITLE
Error: Private file is not supported while importing it into Certificate Manager on AWS

### ISSUE THREAD

**Issue by akaulgud** [certbot/certbot#5656]
I am using Ubuntu 16.4. I received SSL certificate files. When I tried importing certificate in ACM i.e. certificate manager in AWS, I got following error

"Private file is not supported"

I checked certbot is using RSA2048, Version 3

Does anybody know what could be the issue?

**Comment by schoen** [comment]
Hi @akaulgud ,

I saw that you've also posted about this at

https://community.letsencrypt.org/t/error-private-file-is-not-supported/54701

That's a more appropriate place because there is a larger audience of people who might know how to deal with ACM. People looking at this issue tracker here probably won't be able to help with that.

I hope that people on the Community Forum thread are able to help resolve your issue!
