### ISSUE TITLE
packaging dependencies not the same between certbot and plugins

### ISSUE THREAD

**Issue by prometheanfire** [certbot/certbot#5693]
I'm packaging certbot for Gentoo and noticed an anomaly between the different setup.py updates.

Compare

https://github.com/certbot/certbot/blob/cc344bfd1e080ad8ae253e0b1073a5ba7879583d/certbot-apache/setup.py#L12

and

https://github.com/certbot/certbot/blob/cc344bfd1e080ad8ae253e0b1073a5ba7879583d/setup.py#L39

I'm not sure setup.py for certbot should have `acme>0.21.1`, but should probably be `acme>=0.21.1` as is defined by the plugins.

**Comment by bmw** [comment]
`pip` might do some silly things here due to https://github.com/pypa/pip/issues/988 (although it also prefers the newest version of each package which should always work), but these version specifiers are actually correct, if written a little strangely.

Looking at our currently released versions, `certbot-apache` works with `acme` and `certbot` 0.21.1 and 0.22.0, but `certbot` 0.22.0 requires `acme` 0.22.0. `certbot-apache` only transitively requires `acme` 0.22.0 when used with `certbot` 0.22.0.

**Comment by prometheanfire** [comment]
ok, that's what I thought it was saying, just looked like a typo (wanted to make sure that's actually what you wanted).

**Comment by bmw** [comment]
I appreciate you flagging the potential bug. Sorry for any confusion!
