### ISSUE TITLE
README / Docs should have guidelines for renew cronjob

### ISSUE THREAD

**Issue by jashsayani** [certbot/certbot#5700]
I just installed `certbot` on a Debian box running my Wordpress blog. I have not yet moved to https because I want to ensure that my cert will be auto-renewed seamlessly without downtime. I looked over the docs and see that I can use `certbot renew` to renew my certificates and have a cronjob to take care of it.

I don't know what the interval should be. Since the certificate is *not renewed* if its still valid, my job could run hours before expiration and not be renewed and then run 24 hours later, causing a downtime of say 20 hours (if it last ran 4 hours before expiration and I run it every 24 hours).

How often should the cronjob be run? Running it every hour seems redundant given 6 month validity. Also, since `certbot` knows the expiration timestamp, can a deamon (say `certbotd`) run in the background and take care of renewal upon expiration without setting up a cronjob?

**Comment by schoen** [comment]
Hi @jashsayani ,

Our documentation says

> If you’re sure that this command executes successfully without human intervention, you can add the command to crontab (since certificates are only renewed when they’re determined to be near expiry, the command can run on a regular basis, like every week or every day). In that case, you are likely to want to use the -q or --quiet quiet flag to silence all output except errors.

https://certbot.eff.org/docs/using.html?highlight=crontab

Elsewhere we've suggested running twice per day. Some ways of installing Certbot take care of this for you automatically.

The default behavior of `certbot renew` is to renew certificates that are expiring in less than 30 days. So, the scenario you were concerned with won't occur. Your certificates will ordinarily be renewed long before they are due to expire. (Certificates are allowed to have overlapping validity, so the previous certificate and new certificate will both continue to be valid for a period of about 30 days.)

> can a deamon (say certbotd) run in the background and take care of renewal upon expiration without setting up a cronjob?

That would be fine, but we've never implemented anything like this. Since most systems have `cron` and/or `systemd` for periodic task scheduling, creating our own daemon feels like extra work and memory use for no obvious benefit. (It might appear to be a benefit that it could perform the renewal at *the exact right moment*, but we think `cron` is probably actually quite appropriate for this because the renewal attempt can fail for random and often transitory reasons, in which case it should be re-attempted periodically.)

**Comment by xunxky** [comment]
would it really kill you to specifically state what is the default behavior in the otherwise utterly verbose manual? :roll_eyes: 
why? because your recommendation twice a day is much too often!

By the way the default renewal behaviour is 30 days and can be (only?!) changed  in the specific renewal.conf  with renew_before_expiry = 30 days
https://certbot.eff.org/docs/api/constants.html#certbot.constants.RENEWER_DEFAULTS

**Comment by KeiroD** [comment]
>That would be fine, but we've never implemented anything like this. Since most systems have cron and/or systemd for periodic task scheduling, creating our own daemon feels like extra work and memory use for no obvious benefit. (It might appear to be a benefit that it could perform the renewal at the exact right moment, but we think cron is probably actually quite appropriate for this because the renewal attempt can fail for random and often transitory reasons, in which case it should be re-attempted periodically.)

That's not an excuse for not providing examples. You provide plenty of examples for how to run `certbot` but none for `cron` or `systemd`.

**Comment by julianlam** [comment]
I don't feel it is up to the Certbot developers to teach you how to use cron. In fact, running `crontab -e` on Ubuntu systems shows instructions in the file itself, and you can always use the `man` command to look up the manual on cron.
