### ISSUE TITLE
revoke v02

### ISSUE THREAD

**Issue by ecc256** [certbot/certbot#5813]
## My operating system is (include version):
CentOS 7

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
yum

## I ran this command and it produced this output:
certbot revoke --delete-after-revoke \
> --server https://acme-staging-v02.api.letsencrypt.org/directory \
> --cert-path /etc/letsencrypt/live/www.mydomain.com/fullchain.pem
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Starting new HTTPS connection (1): acme-staging-v02.api.letsencrypt.org
An unexpected error occurred:
**The request message was malformed :: No Content-Type header on POST. Content-Type must be "application/jose+json"**
Please see the logfiles in /var/log/letsencrypt for more details.

## Certbot's behavior differed from what I expected because:
It works fine with 
--server https://acme-staging.api.letsencrypt.org/directory

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
Nothing interesting  there

**Comment by bmw** [comment]
This is fixed in Certbot 0.22.2 which came out a week and a half ago. This package is [currently in testing for EPEL 7](https://koji.fedoraproject.org/koji/buildinfo?buildID=1060531).

If you need to revoke your cert now and don't want to install from testing, you can use [certbot-auto](https://certbot.eff.org/docs/install.html#certbot-auto) or [Docker](https://certbot.eff.org/docs/install.html#running-with-docker).

**Comment by ecc256** [comment]
Thanks for quick response! 👍
