### ISSUE TITLE
Creating certificate for IPv6 is broken

### ISSUE THREAD

**Issue by mgrep** [certbot/certbot#5816]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
OpenSuse Tumbleweed 20180331

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot 0.22.2

## I ran this command and it produced this output:
On terminal we see the following

 sudo certbot --duplicate certonly -d maikel.greppie.nl,2001:1c00:e07:9100:46d:80a4:38b9:a8 --test-cert --standalone
Saving debug log to /var/log/certbot/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
An unexpected error occurred:
The request message was malformed :: Error creating new order :: DNS name does not have enough labels

In log we see the following
2018-04-02 16:25:56,268:DEBUG:acme.client:Storing nonce: tBiw6Wm_S3DAih2KA2aksgN-AHY-6lccmb6FQe3RqLw
2018-04-02 16:25:56,268:DEBUG:acme.client:JWS payload:
{
  "status": "pending", 
  "identifiers": [
    {
      "type": "dns", 
      "value": "maikel.greppie.nl"
    }, 
    {
      "type": "dns", 
      "value": "**2001**"
    }
  ], 
  "resource": "new-order"
}

{
  "type": "urn:ietf:params:acme:error:malformed",
  "detail": "Error creating new order :: DNS name does not have enough labels",
  "status": 400
}

## Certbot's behavior differed from what I expected because:
I would expect that IPv6 is supported but it can clearly not handle IPv6 addresses it only read it till the first ':' and strips everything after that.

**Comment by schoen** [comment]
Hi @mgrep ,

Let's Encrypt by policy never issues any certificates for IP addresses (whether IPv4 or IPv6), only for domain names. This has always been true since Let's Encrypt started operations. See for example

https://community.letsencrypt.org/t/certificate-for-public-ip-without-domain-name/6082

and some other forum threads on the same topic.

In this case Certbot actually *did* pass your request through to the certificate authority, which rejected it—the error message

```
{
"type": "urn:ietf:params:acme:error:malformed",
"detail": "Error creating new order :: DNS name does not have enough labels",
"status": 400
}
```

came from the Let's Encrypt CA, not from Certbot. We had a discussion at some point, I think, about whether Certbot should warn users about this case, and I think we decided not to because each CA can decide on its policy for itself. I'll file an issue suggesting that the CA error message should perhaps be more explicit in this case and say something like "We don't issue certificates for IP addresses".

**Comment by schoen** [comment]
I filed an issue about improving this error message at

https://github.com/letsencrypt/boulder/issues/3610

**Comment by mgrep** [comment]
Thanks for clearing it up.
So for now I can only have a secure IPv4 website and there is no way to secure my site on IPv6 at least with let's encrypt ?
Do you think it will change in the future as IPv6 will become more dominant ?

**Comment by mgrep** [comment]
I understand now what happens and it does seem to work with domain name only.
I tested this by disabling IPv4 on my website so it only listened to IPv6 and the site was still reachable by domain name.

**Comment by alexzorin** [comment]
This because it does seem like a Certbot bug after all. The JWS payload that was sent to the ACME server was for the identifier `2001`. It should have sent the full IPv6 address. 

What seems to be happening is that Certbot is happy to generate a CSR with `DNS:2001:1c00:e07:9100:46d:80a4:38b9:a8`, but upon parsing it in [`acme/crypto_util._pyopenssl_cert_or_req_san`](https://github.com/certbot/certbot/blob/master/acme/acme/crypto_util.py#L199-L239), it is only reading the first segment due to the way colons in the SAN extension are treated.

At that point, Boulder can't improve its error message because the identifier is not distinguishable as an IP address.

I've opened #7566 which should hopefully prevent this in the first place.

**Comment by alexzorin** [comment]
Certbot now errors out early when an IP address identifier is provided, so I'm closing this.
