### ISSUE TITLE
Unable to install on Ubuntu 16 -- Unable to locate package python-certbot-nginx

### ISSUE THREAD

**Issue by GildedHonour** [certbot/certbot#5835]
According to the instructions for Ubuntu 16:

  https://certbot.eff.org/lets-encrypt/ubuntutyakkety-nginx

I'm doing this:
```
    sudo apt-get update
    sudo apt-get install software-properties-common
    sudo add-apt-repository ppa:certbot/certbot
    sudo apt-get update
    sudo apt-get install python-certbot-nginx

```
And get this:

```
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    E: Unable to locate package python-certbot-nginx

```

**Comment by numberwhun** [comment]
I did the following to reproduce and confirm this issue:
- installed ubuntu 16.10
- ran through the above stated steps (they are the same as in the docs)
- received the same error output

I then used tab complete for the apt-get command on the command line, to get a list of available python-certbot packages, and was shown that the issue is that there are apache packages, but no nginx packages, as described in the docs.  The resolution to this would be to have nginx packages created to meet this demand.

<img width="649" alt="screen shot 2018-04-08 at 12 19 36 am" src="https://user-images.githubusercontent.com/214416/38463230-c121b606-3ac3-11e8-92b9-de9ad8f13c4a.png">

**Comment by joohoi** [comment]
If you are using Ubuntu 16.10 in general, you are strongly encouraged to upgrade, as the version does not receive updates anymore.

**Comment by numberwhun** [comment]
I did confirm that the python-certbot-nginx package is available in Ubuntu 17.10.  Have you thought about updating your system?

**Comment by nick-xie** [comment]
For those using 16.04, try running `sudo apt-get update` before trying to install python-certbot-nginx

**Comment by RESHNAM** [comment]
Thanks nick-xie

**Comment by yordadev** [comment]
Confirmation Ubuntu 16.04 -- running `sudo apt-get update` worked ..
Ran it earlier in a script but still didn't work until placed RIGHT before `-python-certbot-nginx`.

Why is this?

**Comment by datashaman** [comment]
FYI: The package _python-certbot-nginx_ on Ubuntu 18.10 does not contain the _certbot_ binary. Yes, I've followed the instructions from the certbot site for upgrading. 

$ dpkg -L python-certbot-nginx
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/python-certbot-nginx
/usr/share/doc/python-certbot-nginx/changelog.Debian.gz
/usr/share/doc/python-certbot-nginx/copyright

**Comment by silva96** [comment]
> sudo apt-get update

this works

**Comment by silva96** [comment]
> Confirmation Ubuntu 16.04 -- running `sudo apt-get update` worked ..
> Ran it earlier in a script but still didn't work until placed RIGHT before `-python-certbot-nginx`.
> 
> Why is this?

this works

**Comment by atcoolart** [comment]
`sudo apt-get install python3-certbot-nginx`
Good luck!

**Comment by yimam-michael** [comment]
> 

This worked on Ubuntu 22.04.2. Thank you!

**Comment by yimam-michael** [comment]
> `sudo apt-get install python3-certbot-nginx` Good luck!

This worked on Ubuntu 22.04.2. Thank you!
