### ISSUE TITLE
Investigate packaging options

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#5884]

**Comment by bmw** [comment]
@kr4ut had some higher level questions about our approach to packaging at https://github.com/certbot/certbot/issues/5234#issuecomment-432765480. This seemed to me like the most appropriate place to respond.

> 5. What about LTS/ESR releases of Certbot itself that would help backporting and QA in distribution?

We've been pretty reluctant to offer an LTS/ESR version of Certbot. The project is still changing rapidly and backporting fixes to older versions is painful. 

Instead what we've attempted to do for the main Debian and Ubuntu repos is to recommend they ship versions of Certbot that have been released for a while. This gives our releases time to be tested by people using [certbot-auto](https://certbot.eff.org/docs/install.html#certbot-auto) or faster moving distros and we only push those changes out to LTS distros once this testing has been done and any bugs have been fixed. We also have largely avoided making backwards incompatible changes to Certbot since we launched.

If a real LTS/ESR version of Certbot would be enough for [Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=887399) and [Ubuntu](https://bugs.launchpad.net/ubuntu/+source/python-letsencrypt/+bug/1745126) to actually offer regular updates to their packages, we'd consider it, but otherwise I don't think the small team of Certbot developers wants to take on this work.

I'll also add that due to all of the problems we're having with getting distros to package Certbot, we're working on a new packaging solution ourselves which is the main purpose of this issue. We're still figuring out what exactly we want to do and it won't be built and tested for months, but we have something in the works which should hopefully alleviate a lot of these problems.

**Comment by oerdnj** [comment]
Just to chime in - the main problem isn't the acme, certbot and josepy packages going forward, but the version requirement for dependencies and strong need to not divert much from the main Debian packages.

And as usual, the situation is complicated by Ubuntu LTS version (5 year support on server) - the software there is well outdated and it requires packagers to jump through many hoops to get it working, sometimes making compromises that wouldn't be required if only (say) Xenial and up were supported.

Perhaps, if we can come to agreement about the distro support for packages (and supporting the rest with [certbot-auto](https://certbot.eff.org/docs/install.html#certbot-auto), then the packaging repository might be much cleaner.

**Comment by adferrand** [comment]
It is even worse with the latest Ubuntu LTS, that will have 10 years of support. But we are working on a new packaging approach, that will address this specific issue: how to be independant from the specific python dependencies on a given Linux distribution.

**Comment by bmw** [comment]
> And as usual, the situation is complicated by Ubuntu LTS version (5 year support on server) - the software there is well outdated and it requires packagers to jump through many hoops to get it working, sometimes making compromises that wouldn't be required if only (say) Xenial and up were supported.
>
> Perhaps, if we can come to agreement about the distro support for packages (and supporting the rest with certbot-auto, then the packaging repository might be much cleaner.

Sure. We could talk about making changes here, however, if Trusty is the main issue, I'm hesitant to try and transition people using the PPA there to `certbot-auto` when the release is reaching it's EOL in a few months. I'm also hesitant to abandon the users without updates until Trusty is EOL'd.

**Comment by bmw** [comment]
Assuming we don't find any major last minute issues this is done. We will be releasing Certbot as a snap.
