### ISSUE TITLE
Define clean method for servers to inform client of necessary update

### ISSUE THREAD

**Issue by jcjones** [certbot/certbot#589]
Since Boulder uses hostnames to delineate between breaking protocol versions, there may be instances where a Boulder instance stops working at a particular URI. While not a preferred approach, if a serious security issue were to arise at `acme-isrg-v09.host.tld` prompting the server to stop accepting version `09`, it'd be nice to provide enough data to the client that the client could provide a useful error notification.

I would also prefer this be a static notice, such as a static json response.

Presumably the client cannot on its own provide remediation in these cases, but it may be good to provide plaintext description (localized?), and perhaps links to more details (CVE, blog post?).

The ultimate result would be an updated client, using a new URI, such as `acme-isrg-v0A.host.tld/acme/new-reg`. And I've no idea if we want to use hex or decimal for versioning, but hey, thought I'd be inclusive.

**Comment by bifurcation** [comment]
Decimal versioning.

**Comment by bmw** [comment]
This is out of scope for Certbot so I'm closing this issue.

It seems like a decent idea to me, but since we're in the final stages of getting ACME finalized, I'm not sure we want to add anything like this now. Presumably, the ACME server could do a decent job here with the current protocol by raising an error with an informative `detail` field.
