### ISSUE TITLE
Certbot-auto error due to sh/bash confusion?

### ISSUE THREAD

**Issue by gmolau** [certbot/certbot#5900]
## My operating system is (include version):
SunOS 5.11

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
```
$ ./certbot-auto --help
./certbot-auto: OLD_VENV_PATH=~/.local/share/letsencrypt: is not an identifier

```
## Certbot's behavior differed from what I expected because:
The certbot-auto script errored on [line 29](https://github.com/certbot/certbot/blob/f510f4bddf4da1411c1966a9cbed2b7e630cba30/certbot-auto#L29).

## Possible explanation

Looks like the script runs in sh while it would actually require bash. See this Stackoverflow post for more info: https://stackoverflow.com/questions/50029500/launching-certbot-auto-fails-on-old-venv-path

**Comment by sydneyli** [comment]
Thanks for the report! We technically don't support Solaris (#3841) though it looks like you got it to work by running this script with `bash`. It looks like this is a problem with the version of `sh` that is shipped with Solaris. Closing this issue in lieu of #3841 unless this problem pops up on our [supported systems](https://certbot.eff.org/).

In particular, older versions of `sh` expect syntax like:
```
OLD_VENV_PATH="$XDG_DATA_HOME/letsencrypt"; export OLD_VENV_PATH
```
rather than
```
export OLD_VENV_PATH="$XDG_DATA_HOME/letsencrypt"
```
We welcome any contributions for #3841!
