### ISSUE TITLE
SERVFAIL with bind9 (apparmor and bind issue, really, the solution needs to be added to the documentation)

### ISSUE THREAD

**Issue by Nullcaller** [certbot/certbot#5906]
## My operating system is (include version):
Ubuntu 18.04 LTS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt & certbot-dns-rfc2136 with pip

## The Issue and the Solution
I've tried to issue a wildcard certificate with certbot-dns-rfc2136 and bind, but it didn't work because of SERVFAIL error the server was returning. All the settings were pretty much identical to what you can read in certbot-dns-rfc2136's documentation, so I just skip right past them. The solution was to set the permissions for /etc/bind to 774, since bind could not create a journal file in that directory and set access mode to rwix for /etc/bind/** in /etc/apparmor.d/usr.sbin.named, since apparmor was blocking it too.

## The Reason Why
I don't really know how to edit the documentation and I don't have any ideas about it, so if anyone could add this to the documentation, just as a kind of a warning, or "if you have this issue, just maybe, maybe, this could help", that would have been wonderful.

**Comment by joohoi** [comment]
This is actually an issue with BIND9 (or OS) configuration, and not in Certbot itself. We have a lot of plugins across all kinds of services and against external APIs. To collect a comprehensive troubleshooting guide for all of them would probably make the documentation huge and hard to read.

Because of this reason my personal preference would be to leave this issue open here, so it, and its solution part can be found with searches. It could also make sense to post the solution to https://community.letsencrypt.org/ for added discoverability.

**Comment by bmw** [comment]
I'm happy for this issue to exist, but I don't want to leave it open because that mixes it with the actionable tasks for people working on Certbot.

If someone has a proposal for a change we should make related to this, please let me know, but for now, I'm closing this issue.
