### ISSUE TITLE
ambiguous error messages form when using --manual

### ISSUE THREAD

**Issue by herrold** [certbot/certbot#5930]
## My operating system is (include version):

CentOS 7 updated current, with EPEL 7 enabled

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

package manager:
certbot-0.23.0-1.el7.src.rpm

## I ran this command and it produced this output:

[root@router ~]# /usr/bin/certbot certonly --manual  -d router.example

http-01 challenge for router.example.com

Create a file containing just this data:

hJe2tuvhNYW6961Rurfq8wmCynH3SJmta1wq9fxPJNE.VTBSmjWND-K9yS2ltVBlXVvpaNQi6gtDaJgu3GcA2uA

And make it available on your web server at this URL:

http://router.example.com/.well-known/acme-challenge/hJe2tuvhNYW6961Rurfq8wmCynH3SJmta1wq9fxPJNE
**** this line A ***

Failed authorization procedure. router.owlriver.net (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://router.example.com/.well-known/acme-challenge/hJe2tuvhNYW6961Rurfq8wmCynH3SJmta1wq9fxPJNE: Error getting validation data
 **** this line C ***

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: router.example.com
   Type:   connection
   Detail: Fetching
   http://router.example.com/.well-known/acme-challenge/hJe2tuvhNYW6961Rurfq8wmCynH3SJmta1wq9fxPJNE:
 **** this line B ***

   Error getting validation data

## Certbot's behavior differed from what I expected because:

The file to be produced does NOT have a trailing 'colon'
see: line A

The error messages DO have trailing 'colon' characters
see: line B, line C

Expected result:

The filename to edit, and the error messages as to what was sought to retrieved, should be identical, and not carry the extra 'colon'

(assuming it is such)

**Comment by schoen** [comment]
Hi @herrold ,

That colon is meant in a grammatical sense, like

> There's a problem with item 1235142: it's too small!

In this case, the item number is "`1235142`", not "`1235142:`". However, since URLs can also contain colons in some circumstances, I can see where this might be confusing.

This error message is created by the Let's Encrypt CA software, Boulder, not by Certbot. In order to change it, it would have to be changed on the CA side. (Certbot is just showing the exact detail string that was received from the CA, which already includes the colon.)

You can post an issue at https://github.com/letsencrypt/boulder/issues asking for the syntax of the error to be changed. Again, the developers there would have the power to change this, but we wouldn't.

Thanks, and sorry for the inconvenience!

I can also confirm from looking at the error messages that the specific reason for the failure of your certificate issuance in this case was not related to the colon and probably relates to your domain or server configuration in some way. If you continue to have trouble getting your certificate, you could try using the new third-party tool at https://letsdebug.net/, or post a message on our community forum at https://community.letsencrypt.org/.
