### ISSUE TITLE
ACME Version 0.25.0 can't be found officially on Python Foundation Webpage

### ISSUE THREAD

**Issue by daVincere** [certbot/certbot#6025]
Hey, I am having some issues with applying SSL certificate to my website hosted on AWS. I've been at it since the last 20 days and still can't find a way to do it. 
While installing and setting up the certbot-aws-route53 module of yours, there's come a point to install ACME. The setup.py doc has put it's value at >0.24.0 but I can't find any module of ACME greater than version 0.24.0. On the official Python Foundation page too the latest stable release is 0.24.0, updated on 2nd May, 2018. 

Please help. 

## What have I tried
I tried editing the setup.py file to look for >=0.24.0 (instead of just >0.24.0) to move ahead but now a new module that, I guess, is only added to 0.25.0 version, magic_typing gives the Import error.
```
  File "/usr/local/lib/python2.7/dist-packages/certbot-0.25.0.dev0-py2.7.egg/certbot/main.py", line 14, in <module>
    from acme.magic_typing import Union  # pylint: disable=unused-import, no-name-in-module
ImportError: No module named magic_typing

```
Just wanted to know if there's way to overcome this or if there's a better way to do apply SSL on a Django Webapp hosted on AWS ElasticBeanstalk

**Comment by schoen** [comment]
Hi @daVincere ,

I talked to @bmw who suggested that this is likely due to using some parts of Certbot from our GitHub page and other parts from PyPi. The main way to avoid this is to be consistent and use all of your Certbot packages from the same place and method.

If you continue to have problems, please ask over on the Let's Encrypt Community Forum at https://community.letsencrypt.org/.

You can also consider other clients

https://letsencrypt.org/docs/client-options/

Thanks!
