### ISSUE TITLE
Invalid acme requirement preventing setup.py from completing

### ISSUE THREAD

**Issue by mynameiscfed** [certbot/certbot#6037]
After cloning the repo and running _sudo python setup.py install_ I receive the error message _Could not find suitable distribution for Requirement.parse('acme>0.24.0')_ but there is not version great than 24. 

It appears to have been changed in commit https://github.com/certbot/certbot/commit/36dfd065037678bf38b7adb95ab16ed951ebbd18

**Comment by joohoi** [comment]
Can you take a look @bmw ?

**Comment by bmw** [comment]
This is correct. This repository contains multiple packages including `certbot` and our `acme` library. The version of `certbot` in `master` currently depends on the version of `acme` in `master` because it's making use of unreleased changes. This will change when we release new versions of both packages next month.

To install the version of `certbot` from `master`, I'd recommend following our [developer guide](https://certbot.eff.org/docs/contributing.html). Alternatively, you'll need to install the package in the `acme/` directory before installing `certbot`.

I believe this answers your question so I'm going to close this issue, but please comment if you think I missed something and would like me to reopen.
