### ISSUE TITLE
Should show IPs of domains

### ISSUE THREAD

**Issue by vporton** [certbot/certbot#6041]
Please (maybe on user option) print the IPs of the domains certificates are obtained for.

It is useful for instance if we recently changed the IP of our domain. We need to know whether certbot uses the old or new IP.

**Comment by vporton** [comment]
I mean the IPs used by the verifier at LetsEncrypt server, not "local" values of the IPs (which can be shown by `host ...` command).

**Comment by ohemorange** [comment]
Does adding the verbose flag `-vvv` solve this? That prints the data structures returned to us by Let's Encrypt, we don't have more information than that.

**Comment by schoen** [comment]
Hi @vporton ,

The behavior of the Let's Encrypt verifier is determined by the Boulder project, which is the software that the certificate authority runs.

https://github.com/letsencrypt/boulder

Right now the certificate authority does include the resolved IP address in *some* error messages, which has often been helpful for debugging purposes. However, it might be possible to make this behavior more consistent so that users can always see these addresses.

As @ohemorange notes here, Certbot can't display any information about the validation process except what the certificate authority has chosen to send back to us.

**Comment by jsha** [comment]
@schoen Based on your comment, I think you may have misunderstood Erica's comment above. *Every* validation from Let's Encrypt includes a ValidationRecords section, which includes the information this @vpo is asking for. Using the `-vvv` flag will expose that information reliably.

**Comment by schoen** [comment]
I agree that I misunderstood Erica's comment. Certbot doesn't always default to showing all of the available information, but the information requested about IP addresses should be available if necessary.
