### ISSUE TITLE
CLI parameters such as --test-cert shouldn't be aliased in error output context

### ISSUE THREAD

**Issue by nuxwin** [certbot/certbot#6049]
## My operating system:
```
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.10 (jessie)
Release:	8.10
Codename:	jessie
```
## I installed Certbot with certbot-auto, which version is:
```
root@konzeptplus:~# certbot --version
certbot 0.24.0
```
## I ran this command and it produced this output:
```
root@konzeptplus:~# certbot certonly --test-cert --server 'https://acme-staging.api.letsencrypt.org/directory'
--server value conflicts with --staging
```
## Certbot's behavior differed from what I expected because I would expect following output:
```
root@konzeptplus:~# certbot certonly --test-cert --server 'https://acme-staging.api.letsencrypt.org/directory'
--server value conflicts with --test-cert
```
## Discussion
This is only a cosmetic issue but that could be also source of confusion for end-users.

**Comment by bmw** [comment]
I agree it'd be good to fix this. We used to add a lot of aliases like this, but we don't do so anymore as I think it often just complicates the CLI.

Unfortunately, it's a bit cumbersome to fix this because our current argument parser doesn't retain this information. For example, `--staging` and `--test-cert` both modify the value of `staging` in the parsed configuration and no information is retained about what flag set this value. To fix this, we'd have to write our own code to (re)parse the command line to determine which flag set it and we may have to run this code every time we want to return an error string like this.

Things get a lot more complicated if we also want to do this for values set in a [configuration file](https://certbot.eff.org/docs/using.html#configuration-file).

This might be a lot easier if we resolve https://github.com/certbot/certbot/issues/4493 first.
