### ISSUE TITLE
Unexpected error: "too many labels" on my domain name?

### ISSUE THREAD

**Issue by vecna** [certbot/certbot#6064]
## My operating system is (include version):
Ubuntu 16.04.3

## I installed Certbot with
OS package manager

## I ran this command and it produced this output:
Command: 
```
certbot certonly --standalone -d google.fuck.off.of.kreuzberg.or.we.make.more.of.your.tracking.exposed
```

Error:
```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
An unexpected error occurred:
The request message was malformed :: Error creating new authz :: DNS name has too many labels
```

## Certbot's behavior differed from what I expected because:
I was not expecting the number of dots will prevent ACME to work. And I'm not aware of any hard limit about the number of dots.

**Comment by cpu** [comment]
Hi @vecna, sorry to see you're having trouble.

> The request message was malformed :: Error creating new authz :: DNS name has too many labels

This error & the corresponding validation are properties of the ACME server and not something Certbot can change. For Let's Encrypt the ACME server is [Boulder](https://github.com/letsencrypt/boulder).

Boulder and Let's Encrypt support a maximum of [10 DNS labels](https://github.com/letsencrypt/boulder/blob/b2f5cf39b91d0aa0103809c095e22d49c7f1c310/policy/pa.go#L151
) in subject domain names.

I'm going to close this issue since the Certbot team won't be able to help you with this problem. If you have further questions about Boulder's DNS label validation please open a new issue [on the Boulder repo](https://github.com/letsencrypt/boulder/issues).

Thanks!
