### ISSUE TITLE
AH00526: Syntax error on line 56 of /appli/apache/2.4.29/apacheshinken/conf/conf.d/vhost-graphite.conf:

### ISSUE THREAD

**Issue by m2cci-KGY** [certbot/certbot#6139]
Hi 
I need your help to resolve my problem.
I install the "mod_wsgi" for apache but when I run my apache I get this problem :

AH00526: Syntax error on line 56 of /appli/apache/2.4.29/apacheshinken/conf/conf.d/vhost-graphite.conf:
Invalid command 'Order', perhaps misspelled or defined by a module not included in the server configuration
[ERR] apache apacheshinken start err 0

I don't idea, so I see the file of "vhost-graphite.conf"
I see this at line 56
 <Directory /opt/graphite/conf/>
               Order deny,allow
                Allow from all
        </Directory>
thank for your help.

**Comment by schoen** [comment]
Hi @m2cci-KGY ,

You didn't explain whether this problem was related to enabling Let's Encrypt on your site using Certbot, but if so, please try asking for help on the Let's Encrypt Community Forum at https://community.letsencrypt.org/. Hopefully someone will be able to answer your question.

Thanks!
