### ISSUE TITLE
Certbot Ubuntu 16.04 creating redirect loop

### ISSUE THREAD

**Issue by claythearc** [certbot/certbot#6146]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Ubuntu 16.04 xenial

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
I followed the steps directly from the lets encrypt website

## I ran this command and it produced this output:
```
server {
    if ($host = website here) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

```
## Certbot's behavior differed from what I expected because:
It created this redirect loop inside of the https AND http version of my config file. This is problematic because it kept sending 301 redirects to https:// even though it was already in the https:// branch

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
Fixed version just removed the if($host) inside the server block. Fix for issue proposed as checking 

```
  if ($http_x_forwarded_proto = "http") {
      return 301 https://$server_name$request_uri;
  }
```

Rather than the host name.

**Comment by bmw** [comment]
@ohemorange, can you take a look at this?

**Comment by ohemorange** [comment]
Hi @claythearc, I'd love to get more information about how this happened so we can fix it for future users. Could you send a copy of your logs located inside `/var/log/letsencrypt` to erica@eff.org?

**Comment by ohemorange** [comment]
What's happening here:

Start:

```
server {
  listen 8000;
}
server {
  listen 80;
}
```
both with `server_name` set correctly.

Then we install the cert to the first one:
```
server {
  listen 8000;
  listen 443;
  ssl_certificate...
}
server {
  listen 80;
}
```
Then we put the redirect in the other one:
```
server {
  listen 8000;
  listen 443;
  ssl_certificate...
}
server {
  if ($host = ...)
  listen 80;
}
```

Then, Certbot is run again.
This time, we install the cert in the second one:
```
server {
  listen 8000;
  listen 443 ssl;
  ssl_certificate...
}
server {
  if ($host = ...)
  listen 80;
  listen 443 ssl;
  ssl_certificate...
}
```
Then, we're asked to enable redirect, so we split the latter server block in 2:
```
server {
  listen 8000;
  listen 443 ssl;
  ssl_certificate...
}
server {
  if ($host = ...) [redirect 1]
  listen 443 ssl;
  ssl_certificate...
}
server {
  if ($host = ...) [redirect 2]
  listen 80;
  return 404;
}
```
But we put redirect 1 in there last run, so we don't know to remove it.

So the question is, why did we put `listen 443 ssl` in the `listen 8000` server in the first place? If we stop doing that, that should fix this problem.

**Comment by claythearc** [comment]
Admittedly, this for sure could have been a bit of user error on my part too, because it was my first experience really with setting up any type of SSL or nginx in general.

**Comment by ohemorange** [comment]
Looking back, I'm not certain my original analysis was correct, since we have a mechanism to remove existing redirects. Leaving this open in case anyone else wants to try to investigate, or in case someone else runs into the same issue.

If you do hit this issue, just delete the extraneous redirect that Certbot put in and try again.

**Comment by bmw** [comment]
I was able to reproduce this on `master` (and Certbot 0.25.0). To do it, I had to manually modify my nginx config between Certbot runs, but not in anyway I personally consider too out of the ordinary. I'm not sure if the original bug report was caused by similar modifications or by another issue.

Steps to reproduce are:

1. Start with only these two nginx files in `/etc/nginx/sites-enabled` (assuming you're on a Debian based distro): [default.txt](https://github.com/certbot/certbot/files/2527542/default.txt) and [myvhost.txt](https://github.com/certbot/certbot/files/2527543/myvhost.txt). (I only added the `.txt` extension before uploading to make GitHub happy.)
2. Run `certbot -d example.org --nginx --redirect` which results in a redirect being added to the server block in `default` and the cert being installed to the server block in `myvhost`.
3. Modify `myvhost` so Certbot's nginx plugin no longer sees it as a match for `example.org`. You can just delete the vhost entirely or change the `server_name` directive. To keep the setup valid, I'll do the latter but also add `default_server` to the `listen 443` statement.
4. Run `certbot -d example.org --keep --nginx --redirect` which results in the following config file:
```
server {
    if ($host = example.org) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
    root /var/www/html;
    server_name example.org;



    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/example.org/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/example.org/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = example.org) {
        return 301 https://$host$request_uri;
    } # managed by Certbot




    listen 80 default_server;
    listen [::]:80 default_server;
    server_name example.org;
    return 404; # managed by Certbot


}
```

**Comment by octageeks** [comment]
I see this behavior as well, but it only happens once in a blue moon.
The only 301 redirect in my nginx conf file is the one added by certbot for the SSL redirection as others have shown here.
