### ISSUE TITLE
Use Google DNS when checking _acme-challenge.example.com

### ISSUE THREAD

**Issue by jbauson** [certbot/certbot#6163]
First, I would like to thank everyone who's been working really hard to provide us free SSL. 
This post is more of a feature request, I just noticed that when I use the dns-01 challenge, it will take sometime for some servers to get the update from zone files maintained from different Domain Registries. So it will be good to have the challenge checked via Google's DNS which is 8.8.8.8.

From dig TXT +short _acme-challenge.example.com
To dig TXT +short _acme-challenge.duyan.ph @8.8.8.8

I'm not really sure how certbot is doing it's validation, but I bet it's simply relying to how the machine digs on the target.

Thanks!

**Comment by schoen** [comment]
Hi @jbauson ,

Certbot doesn't try to resolve domain names during the verification process at all. All of the resolution is happening on the certificate authority side, in order to decide where the certificate authority will connect in order to validate challenges. This is the responsibility of the Boulder project:

https://github.com/letsencrypt/boulder

The DNS lookups that the Let's Encrypt CA performs are mainly handled by an internal copy of Unbound

https://www.unbound.net/

That is, the CA is handling the entire lookup process itself and not delegating the DNS lookup to *any* third-party recursive nameserver. You can see a simulation of this process at

https://unboundtest.com/

where you can perform a similar query for any DNS record and see the exact steps that the CA would have taken to look up that record.

If you'd like to talk about this more generally, or ask about how the CA looked up a particular record in practice, or try to figure out where the delay is happening, I suggest posting on https://community.letsencrypt.org/. If you want to make a specific proposal to change how Let's Encrypt handles DNS lookups, I suggest posting on https://github.com/letsencrypt/boulder/issues. In the second case, the Let's Encrypt developers will expect you to already understand the general details of how Let's Encrypt is currently using Unbound for DNS lookups.

Thanks!
