### ISSUE TITLE
Potential new required dependency for lexicon. 

### ISSUE THREAD

**Issue by AnalogJ** [certbot/certbot#6212]
CC: @bmw 

Hey @certbot

I wanted to give you guys a heads up that [AnalogJ/lexicon](https://github.com/AnalogJ/lexicon) will have a new top level dependency once the Google Cloud DNS provider is merged in https://github.com/AnalogJ/lexicon/pull/261

Basically the idea is to add `cryptography` as a top level dependency so that developers implementing providers that utilize OAuth will have a library available to do most of the heavy lifting for them. 

I know lexicon dependency changes have broken your build/CI process in the past, so I wanted to give you guys a heads up and see how you guys wanted me to proceed doing the merge & release. 

Also, if you guys have any feedback about the Google Cloud DNS provider, you can comment here: https://github.com/AnalogJ/lexicon/pull/261

**Comment by bmw** [comment]
Thanks a lot for flagging this for us @AnalogJ. Since Certbot also depends on `cryptography`, this shouldn't be a problem for us.

The only potential issue that could come up is if Lexicon starts depending on newer version of `cryptography` than is available in some of the LTS repos where we're packaged. I looked through all the uses of `cryptography` in AnalogJ/lexicon#261 and this isn't a problem right now. We're also currently rethinking on how we're distributing Certbot so this concern could go away in the near future, but if you happen to notice you're starting to use functionality in cryptography that is only available in newer versions, I'd appreciate a ping. If not, our tests should catch it.

Thanks again @AnalogJ!
