### ISSUE TITLE
Installer does not update NSSCertificateDatabase

### ISSUE THREAD

**Issue by ivordurham** [certbot/certbot#6213]
## My operating system is (include version):

Fedora release 27

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

OS package manager (dnf)

## I ran this command and it produced this output:

sudo certbot --apache

(normal output)

## Certbot's behavior differed from what I expected because:

My Apache server is using mod_nss. The directives for the certificate etc. were added "normally". However this was not correct for my configuration because it has the following directives with the certificates in the "alias" database:

NSSNickname "MY_CERT_NAME"
NSSCertificateDatabase /etc/httpd/alias

I removed the certbot-added directives and added the certificate to the database using the following shell commands:

1) openssl pkcs12 -export -in live/HIDDEN.com/fullchain.pem -inkey live/HIDDEN.com/privkey.pem -out server.p12 -name "MY_CERT_NAME" -passout pass:foo

2) certutil -d /etc/httpd/alias -D -n 'MY_CERT_NAME'

3) pk12util pk12util -i server.p12 -d /etc/httpd/alias -W foo

After a restart Apache used the new certificate correctly.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

N/A

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

N/A

**Comment by bmw** [comment]
@joohoi, what are your thoughts on this?

**Comment by joohoi** [comment]
I feel that this is a rather unusual configuration, at least in large scale, and managing it would require shelling out to, and expecting external tools to be available to handle within Certbot. Because of that, I believe supporting it withing Certbot itself would probably make little sense.

However, to mitigate the issue for @ivordurham usecase, I feel using renewal deployment hooks would be in order. [There's some documentation](https://certbot.eff.org/docs/using.html#renewing-certificates) how to use the hooks, and different approaches of deploying one. This pretty much means creating a small shell script, with the required commands, and deploying it to `/etc/letsencrypt/renewal-hooks/deploy`. If you have multiple certificates on the same machine, of which not every requiring this functionality, you can check environment variable set by Certbot to verify that the certificate being deployed is the correct one. The env variables for this use are: `RENEWED_DOMAINS` and `RENEWED_LINEAGE`.

**Comment by ivordurham** [comment]
I am using the default mod_nss default configuration that came with the Fedora release, so the NSSCertificateDatabase is appears to be their preferred configuration. I wrote a script to add my original self-signed certificate to the database per instructions and modified that script to replace the original key/cert it with the certbot key/cert. This script is probably all that is required for the deployment hook assuming the new key/cert are generated in the same place as the originals. 

 

I will try to use the hooks for renewal.

**Comment by joohoi** [comment]
> I am using the default mod_nss default configuration that came with the Fedora release, so the NSSCertificateDatabase is appears to be their preferred configuration.

Oh! This is a new bit of information for me. We do have an distribution based overrides for some Apache plugin internals in place, so if this is the default, I believe we should try to support it. I'll investigate the availability of the required tools in different versions of Fedora/CentOS/RHEL family.

Thanks for bringing this up @ivordurham !

**Comment by bmw** [comment]
At least on the latest version of Fedora, `mod_ssl` is installed with `httpd` by default and `mod_nss` is not. As far as I know, this is also the only request for this feature we've seen in the 3+ years of our Apache plugin and while we'd love to make it work for all use cases, we just realistically can't. For this reason, I'm going to close this issue with the recommendation being to use hooks as briefly described [here](https://certbot.eff.org/docs/using.html#renewing-certificates).
