### ISSUE TITLE
Warning: Could not choose appropriate plugin for updaters

### ISSUE THREAD

**Issue by bong0** [certbot/certbot#6221]
The described error running the renew routine suddenly appeared two days ago (on 2018-07-12) and since that daily with each run.
 
## My operating system is (include version):
Debian 8 (jessie)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
`/usr/local/bin/certbot-auto renew --installer None --authenticator standalone --pre-hook "apache2ctl stop; sleep 1;" --post-hook "apache2ctl start" --agree-tos --quiet`
output on stderr:
```
Could not choose appropriate plugin for updaters: Could not select or initialize the requested installer None. 
[repeated 6 times or so]
```

A note on that possibly weird-looking renew call: I ran into an issue with the apache plugin since it restarted the server too fast or so. Due to that the plugin wasn't working anymore and thus I'm using the standalone option with a hard stop/start in between.

## Certbot's behavior differed from what I expected because:
I expected no error to be happening or else a descriptive error message appearing => I don't know what's wrong.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

```
2018-07-13 23:35:19,373:DEBUG:certbot.cli:Var authenticator=standalone (set by user).
2018-07-13 23:35:19,373:DEBUG:certbot.cli:Var installer=None (set by user).
2018-07-13 23:35:19,373:DEBUG:certbot.cli:Var pre_hook=apache2ctl stop; sleep 1; (set by user).
2018-07-13 23:35:19,373:DEBUG:certbot.cli:Var post_hook=apache2ctl start (set by user).
2018-07-13 23:35:19,409:INFO:certbot.renewal:Cert not yet due for renewal
2018-07-13 23:35:19,410:DEBUG:certbot.plugins.selection:Requested authenticator standalone and installer None
2018-07-13 23:35:19,410:WARNING:certbot.updater:Could not choose appropriate plugin for updaters: Could not select or initialize the requested installer None.
2018-07-13 23:35:19,410:DEBUG:certbot.renewal:no renewal failures
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
this should not be of relevance here since I'm not using the apache module

**Comment by joohoi** [comment]
Hi, this issue is actually due to `None` not being a valid value for `--installer`, although it's listed as a default value in our command line help text:
```
  -i INSTALLER, --installer INSTALLER
                        Installer plugin name (also used to find domains).
                        (default: None)
```

Previously the value of `--installer` wasn't used for renew functionality, hence the value was never checked during runtime for `certbot renew`, this however changed with the recent Certbot versions when we added functionality to check if a requested installer needs to perform tasks on renewal.

If you initially acquired your certificates without installer (ie. running `certbot certonly ...`) the `certbot renew` verb without `--installer` defined should skip this part altogether. If you want to check the saved values, the renewal configuration files can be found under `/etc/letsencrypt/renewal/` directory.

That said, we should probably do better job with how to persent the command line option default values.

**Comment by bong0** [comment]
@joohoi thank you for clarifying this 👍 so just running the tool without the installer flag suffices now not to get the warning.

**Comment by mnordhoff** [comment]
Another user reported this on the forum after upgrading from 0.4.1 to 0.30.0.

https://community.letsencrypt.org/t/renew-fails-could-not-select-or-initialize-the-requested-installer-none/82858

**Comment by refringe** [comment]
Additionally, going into the `/etc/letsencrypt/renewal/example.com.conf` file and removing the `installer=none` line solves the problem. Perhaps the next update should scan these configuration files and remove lines that have default values?

**Comment by joohoi** [comment]
In contrary to the issue title, this is not an _error_, but a **warning**, meaning it's non-fatal. Certbot has Installer specific functionality that gets run on `renew` verb, regardless of if a certificate needs to be renewed or not. This functionality is used for security enhancements like gradually increasing HSTS `max-age` value in Apache configuration, or refreshing the OCSP cache (upcoming).

That being said, automatically removing invalid values could cause some adverse side-effects, especially if we would be removing all invalid values (think of Apache plugin being temporarily unavailable due to a packaging issue), while user relies one of the security enhancement functionalities described above. We'll have to think of how to resolve this - a solution might be just to make the warning message more descriptive and underlining the fact that it's in fact non fatal.

**Comment by bmw** [comment]
Playing with this a bit, it seems the problem does not occur when renewal actually happens and only when `certbot renew` is run but a new certificate is not obtained. The code printing this message runs in either case though.

When a new certificate is actually obtained, Certbot prints:
```
Plugins selected: Authenticator standalone, Installer None
```
It is correctly recognizing that `none` is the Python type `None` and the problem that causes the warning message to be printed is avoided.

Can we refactor the code so more or less the same code is used for parsing installer value in both cases avoiding this problem?

**Comment by shakaran** [comment]
I am having this issue too for several domains. The installer is None too, but I am using nginx. My certs are about to expire. There is another way to renew avoiding this warning/fatal error?

**Comment by benyaminl** [comment]
> 
> 
> I am having this issue too for several domains. The installer is None too, but I am using nginx. My certs are about to expire. There is another way to renew avoiding this warning/fatal error?
> 
> EDIT: I just fix my problem installing the plugin missing:
> 
> `sudo apt-get install certbot python-certbot-nginx `

centos, rhel, or it's derivative use python3-certbot-<webserver>, or apache = python3-certbot-apache, nginx = python3-certbot-nginx on CentOS/RHEL 8 above

**Comment by precisionpete** [comment]
I just had this same problem after upgrading a server from Ubuntu 20.04 to 22.04. 

Similar but not identical to above, the problem was fixed with:

`sudo apt-get install certbot python3-certbot-nginx`

**Comment by UmarFKhawaja** [comment]
I was getting this error because I had install `python-is-python3` on Ubuntu. After I removed that, things worked without a hitch.
