### ISSUE TITLE
CentOS 7 install fails ('module' object has no attribute 'pyopenssl')

### ISSUE THREAD

**Issue by MrMoronIV** [certbot/certbot#6245]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
CentOS 7

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
yum install epel-release // was already installed
yum install certbot

## I ran this command and it produced this output:
certbot --version

## Certbot's behavior differed from what I expected because:
It gave me this error
```
Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.25.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 21, in <module>
    from certbot import client
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 16, in <module>
    from acme import client as acme_client
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 39, in <module>
    urllib3.contrib.pyopenssl.inject_into_urllib3()
AttributeError: 'module' object has no attribute 'pyopenssl'
```

I've encountered this issue so many times but I always google around until it works but I can't find a solution anymore.
I tried certbot-auto, but all my scripts rely on certbot, I just want to install it, that's all :(

**Comment by joohoi** [comment]
This looks like a dependency issue, I'm suspecting `python-requests` package.
Could you please run: 
```
python -c 'import requests;print(requests.__version__)'
```

**Comment by MrMoronIV** [comment]
Result: 2.19.1

I do know a little bit more though: `yum install certbot` runs fine on a clean installation. 
I can manage to break it by installing the openstack neutron-client

```
yum install -y python-devel
pip install python-neutronclient
```
It installs a lot of packages and when I then do certbot --version it gives the above error.

Another way to break it:
` ``
pip install requests --ignore-installed six
```

**Comment by joohoi** [comment]
Thanks for digging more into it! Do you have an idea what's going on @hogarthj or @elyscape ?

**Comment by elyscape** [comment]
I did some digging and the issue is a conflict between pip-installed packages and yum-installed packages. The `python2-certbot` RPM package has a dependency on `python2-acme`, which depends on `python2-requests`, which depends on `python-urllib3`. If urllib3 has already been installed with `pip`, the installation of `python-urllib3` fails with this error:
```
  Installing : python-urllib3-1.10.2-5.el7.noarch                                                                               19/50
Error unpacking rpm package python-urllib3-1.10.2-5.el7.noarch
error: unpacking of archive failed on file /usr/lib/python2.7/site-packages/urllib3/packages/ssl_match_hostname: cpio: rename
  Installing : python-requests-2.6.0-1.el7_1.noarch                                                                             20/50
error: python-urllib3-1.10.2-5.el7.noarch: install failed
```
This is caused by the `python-urllib3` package having `packages/ssl_match_hostname` as a symlink to `../../backports/ssl_match_hostname` but the pip package having it as an actual folder with files inside it. I don't know why this doesn't cause the entire transaction to fail, but a few things happen as a result of this. Firstly, as a result of the package failing to install, yum doesn't register `python-urllib3` as having installed.

Secondly, and more problematically, the in-progress installation is not rolled back, leaving the files in an inconsistent state. Files that it were installed before the failure are left in place. In practice, this means `/usr/lib/python2.7/site-packages/urllib3-1.10.2-py2.7.egg-info` and its contents as well as anything semantically before `packages/ssl_match_hostname` inside `/usr/lib/python2.7/site-packages/urllib3` are installed, replacing any existing files, and `/usr/lib/python2.7/site-packages/urllib3/packages/ssl_match_hostname` is created a suffix of `;SOMEHASH`. This renders the urllib3 package unusable, because approximately half of its files are from version 1.10.2 and some of its files are from the version installed by pip (currently 1.23).

As a general rule, if you use Python (or Ruby, Perl, etc) packages that are installed through your distro's package manager, you'll want to avoid using the language's package manager to install packages on a system-wide level, lest you run into conflicts like this. You'll want to either use something like virtualenv or just specify a different installation path when installing things with `pip`, `gem`, etc. I recommend the former, as it sets up various shims and such to simplify the process, and the binaries it creates for installed packages can be symlinked into `/usr/local/bin` directly.

One thing that can work as a workaround is to install any distro-packaged dependencies through the distro first so that the language-provided package manager won't install those, but that may not work if the distro has a version that's too old to meet the requirements of the package you want to install. In this case, for example, `python-requests` in CentOS 7 is version 2.6.0, but `python-neutronclient` requires `requests>=2.14.2`. As a result, `python-neutronclient` is probably best installed inside a virtualenv.

**Comment by MrMoronIV** [comment]
Oh wow, amazing digging! I'm not too much into python, but does a virtual environment give overhead on the server when for example certbot is not used or is it merely a namespace?

Need to find out how to install pip stuff in a virtual environment as well and know how to use it :)

**Comment by elyscape** [comment]
My understanding is that there is a very small amount of overhead in terms of space (on the order of maybe a few MB), as it basically creates another install of Python and the various libraries that you're using, but there's no performance overhead. It's not virtualized in the sense of running in a VM or container. The name refers to it being a virtual Python environment separate from the system Python environment.

**Comment by stupidoes** [comment]
I had this issue to recently. I identified this error after following tutorial [how to install glances, influxdb & grafana on techmint](https://www.tecmint.com/install-glances-influxdb-grafana-to-monitor-centos-7/) 

The error is as @elyscape said. 

Since i had this error on my development server, 

I tried to remove python-urllib3 via yum, remove requests & urllib3 via pip. After that, i install python-certbot-apache again via yum. And i have running certbot again. 

I don't recommended doing this on production server.

**Comment by willemdh** [comment]
Seems I also stumbled on this issue. 

> Error unpacking rpm package python-urllib3-1.10.2-5.el7.noarch

As I had this on an Ansible generated server, where I just added:

```
- name: Install Python packages
  pip:
    name: "{{item}}"
    state: present
  with_items:
    - linode-cli
```

My guess is there is some conflict with `linode-cli` python package or dependencies...

**Comment by elyscape** [comment]
@willemdh This is the same issue as what I described above. When you install `linode-cli` with `pip`, it installs urllib3, which then causes problems when `yum` tries to install `python-urllib3`. I would recommend installing `linode-cli` in a virtualenv.

As an aside, while trying to figure out why you were installing `linode-cli` through `pip` instead of `yum`, I found that the EPEL-provided package is the old Perl version. I'll work with the maintainer to see about replacing that with the new Python implementation.

**Comment by MCDELTAT** [comment]
Posting just to express that I had the same issue as OP with pyopenssl. It's strange because we have maybe 5 CentOS 7 servers for various things and only one encountered this issue. But yes, I ended up going through certbot-auto and just putting that in my bin so that all users can reference it.

**Comment by bmw** [comment]
This issue has been closed due to lack of activity, but if you think it should be reopened, please open a new issue with a link to this one and we'll take a look.
