### ISSUE TITLE
Use pebble for all/more of our tests requiring an ACME server?

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6305]
This isn't a high priority for us, but @jsha, when you get the time, I'd love to hear your recommendation here. The main benefit for us is pebbles are more lightweight than boulders.

cc @joohoi

**Comment by jsha** [comment]
I think that's probably a reasonable approach now, especially since ACME is all-but-done. When we were revving the ACME protocol support in Boulder frequently it made more sense to verify there was a close match between Boulder and Certbot, but now I think Pebble is sufficient (and testing is what it's for!).

**Comment by adferrand** [comment]
And now Pebble is used instead of Boulder during PRs integration tests. I think we can close this.
