### ISSUE TITLE
certbot fails without erroring from cron due to lack of PATH

### ISSUE THREAD

**Issue by ethanj** [certbot/certbot#6348]
## STATUS

I figured out the cause of my issue, but certbot should be fixed so this is **way** more obvious.

## What I did

I added a cron job as follows
```
0 3 * * * /usr/bin/certbot renew -n --pre-hook "service nginx stop" --post-hook "service nginx start"
```

The cron log show it running with no output other than the following single line
...
Sep  6 03:00:01 ip-172-31-34-208 CROND[16715]: (root) CMD (/usr/bin/certbot renew -n --pre-hook "service nginx stop" --post-hook "service nginx start")
...

The Certbot log has no contents generated from the cron job.

I figured out that the pre and post hooks needed to have full paths as follows
```
0 3 * * * /usr/bin/certbot renew -n --pre-hook "/sbin/service nginx stop" --post-hook "/sbin/service nginx start"
```

Now it works, and generates correct output in the Certbot log.

## What should have happened?

There should be an error generated in the Certbot log showing that the pre-hook failed, rather than having no log output at all (regardless of verbosity setting).

**Comment by bmw** [comment]
Hi @ethanj.

Sorry for the trouble but I'm glad you figured it out. When you run a command like this with Certbot where your hooks aren't in your PATH, it exits with a non-zero status and outputs something like:
```
Unable to find pre-hook command service in the PATH.
(PATH is /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin)
```
Ideally, cron should be configured to send you this output, especially from failing jobs. You can find guides on how to do this online.

The reason Certbot didn't create its own logfile is a bit structural. The error occurred while parsing command line arguments. Until this parsing is done, we don't know how to configure logging because it is configurable through command line arguments so we print messages to the terminal.

I think this is a pretty standard approach, but we could potentially break argument parsing into multiple phases, where we first parse any logging related arguments, set up logging, and then parse any remaining command line arguments. Since this would help in situations like this, I'm happy to make this a wishlist ticket. The small team of core Certbot developers probably won't have the time to change this behavior anytime soon, but maybe you or someone else will.

Thanks for reporting the issue!

**Comment by ethanj** [comment]
Thanks @bmw !

Just as a PSA regarding this, turns out some versions of linux (including Amazon Linux!) have cron configured such that /var/log/cron logs the execution of commands, not the results or exit statuses. The output of the executed command goes to the user's mail by default, so I found the errors in /var/mail/root !!!!!
Also, an alternate email can be specified by the MAILTO variable inside of the crontab.
