### ISSUE TITLE
Add a command line option to set renewal interval

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#6399]
https://community.letsencrypt.org/t/certbot-how-is-the-renewal-time-calculated/73394 includes a feature request for a `--renew-before-expiry` option that will set the renewal interval in the renewal configuration file. (Maybe we should also call it something else like `--renewal-window` or `--renewal-interval` on the command line, because maybe the significance of those names would be clearer?)

**Comment by fuzl-llc** [comment]
Hi @schoen. I came here after seeing your comment on https://community.letsencrypt.org/t/certbot-how-is-the-renewal-time-calculated/73394/5 that "you’re the first person I’ve heard ask about a command line option to set it." I wanted to add a second for this feature.

I could be misunderstanding something but it seems that if certs are issued for 90 days, and the automated renewal script runs daily and renews anything expiring in less than 30 days, aren't you really defaulting to closer to a 60 day cycle, i.e. I get a new cert and it expires in 90 days but renews in around 60 days. I understand some buffer being desirable but I'd rather have it be only 5 or 10 days instead of 30. I like to check on the renewals to ensure everything is working after renewals and less frequent renewals for my large list of domains would be desirable as it reduces my workload.

This is potentially a good thing for reducing the frequency of renewals hitting your servers... but perhaps that isn't really an issue of concern.

**Comment by schoen** [comment]
Hi @fuzl-llc,

The 30-day default shows its value pretty often over on the community forum, where people often show up to ask for help after automated renewals have been failing for some time. In that case, it's nice that they still usually have more than a week left to debug the problem before it starts to affect their users.

I wouldn't want to encourage a lot of people to cut it closer than that, because I think it would increase the amount of stress for both question askers and answerers on the forum.

If a site had a 5-day renewal interval, then a DNS error that's not noticed until the next day might end up forcing the sysadmin to work over the weekend to get the renewal working.

Do you suppose there's any way to discourage people from changing this value without thinking through the implications carefully? (Also note that if you set it above 85 days, you would routinely start hitting rate limits, while if you set it below 2 days, you might not get any failure notifications at all before your certificate expired!) I agree that in principle people ought to be able to customize this if they understand the implications.

**Comment by Bachsau** [comment]
You don't need to discourage people from anything. Having a good default and the reasons for it documented should be enough. If people change it without being aware of the consequences, it's their problem. No one likes to be patronized.

**Comment by mimosvk** [comment]
@schoen I came here from the Let’s Encrypt community forum, and I believe this feature is highly needed. For instance, we use Let’s Encrypt certificates for about 90% of our infrastructure with default auto-renewal, but we also manage around 20 certificates from DigiCert (RapidSSL) via their ACME API. These certificates cost €30 each, and without the option to set a custom renewal period (e.g., 7 or 14 days), we end up paying for a one-year certificate but effectively using it for only 11 months.
