### ISSUE TITLE
OVH IP load balancers hijacking /.well-known/acme-challenge/ not reaching backend servers

### ISSUE THREAD

**Issue by mbfdias** [certbot/certbot#6443]
OVH IP load balancers hijacking /.well-known/acme-challenge/ not reaching backend servers

## My operating system is (include version):
Linux, Ubuntu, 16.04 and 18.04 but will happen on any OS and version

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
any certbot instalation using HTTP-01 Challenge

## Certbot's behavior differed from what I expected because:
because OVH is hijacking /.well-known/acme-challenge/  url on every http request, the challenge is never received by the server/backend. 

It would be wonderful if there could be a way to ask certbot to use a different HTTP-01 Challenge /.well-known/acme-challenge/ path

**Comment by bmw** [comment]
Are you asking Certbot to have the server verifying that you complete the challenge correctly request a URL other than `/.well-known/acme-challenge/...` or for Certbot to put files at a different location on your server's filesystem?

**Comment by bmw** [comment]
If the former, requesting this URL is mandated by the [ACME spec](https://github.com/ietf-wg-acme/acme) and not something Certbot has control over.

If the latter, this is possible with the [webroot plugin](https://certbot.eff.org/docs/using.html#webroot).

Either way, since this doesn't seem to be a feature or bug that can be implemented in Certbot, I recommend you post to https://community.letsencrypt.org where there is a larger community of users who can help you find a way to obtain a certificate for your configuration.

**Comment by mbfdias** [comment]
actually it should be both simultaneously, so that both can perform the challenge and respond to it, using a "secondary path", in cases like the one of ovh, where they hijack everything that starts with /.well-known/acme-challenge/ to their own servers
