### ISSUE TITLE
subject CN is no longer set

### ISSUE THREAD

**Issue by seandilda** [certbot/certbot#6463]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Fedora 28

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
dnf

## I ran this command and it produced this output:
certbot -h certonly

....
  -d DOMAIN, --domains DOMAIN, --domain DOMAIN
                        Domain names to apply. For multiple domains you can
                        use multiple -d flags or enter a comma separated list
                        of domains as a parameter. The first domain provided
                        will be the subject CN of the certificate, and all
                        domains will be Subject Alternative Names on the
                        certificate. The first domain will also be used in
...

## Certbot's behavior differed from what I expected because:

The CSR created by certbot has all the domains in the Subject alternate name, but does NOT set the CN.

It looks like commit https://github.com/certbot/certbot/commit/cacee80c51fe276c8284769229a9b5e6565d9988 dropped the line that sets the CN.

**Comment by bmw** [comment]
Using the common name for this purpose has been deprecated with subject alternative names being the preferred alternative. See https://tools.ietf.org/html/rfc2818#section-3.1.

For this reason, I'm closing this issue as I don't think we're going to undo this change, however, if you have a use case with a technical reason for wanting a common name, please comment explaining what it is and I'll consider reopening the issue.

**Comment by sekrause** [comment]
I think there are a few good reasons why `certbot` should set the subject CN or at least _optionally_ allow to set one in the CSR (without manually creating the whole CSR):

- The Let's Encrypt servers add back a subject CN anyway if it's missing, using the first domain.
- However some alternative ACME implementations like [Buypass](https://www.buypass.com/ssl/products/acme) do **not** set a subject CN in the certificate if it's missing in the CSR. [They officially recommend](https://community.buypass.com/t/x1j8vt/create-a-certificate-with-subject) to manually create a CSR if you want to get a subject CN with `certbot` (which is kind of a bummer). So now you have a different behavior between different ACME servers (e.g. Let's Encrypt and Buypass) which can lead to confusion.
- Some (legacy) clients still have weird behavior when the subject CN is missing completely, even though it's deprecated. [OfflineIMAP](http://www.offlineimap.org/) refuses completely to work with a certificate which has an empty subject CN. Firefox uses the subject CN for the title when viewing a certificate chain.

So there are good reasons why the Let's Encrypt servers still add a subject CN: Because otherwise some clients would show weird behavior. And by not setting a subject CN in the CSR `certbot` is harder to use with alternative ACME implementations. So I suggest an optional URL parameter that allows to pick a domain to use in the subject CN.
