### ISSUE TITLE
HTTPS Redirect gets added to existing HTTPS redirect.

### ISSUE THREAD

**Issue by fake-name** [certbot/certbot#6466]
Basically, I'm running `nginx` with a already existing http -> https redirect:

```
server
{
	listen 80;
	server_name my_domain.com www.my_domain.com;
	return 301 https://www.my_domain.com$request_uri; # enforce https
}
```

Running `certbot-auto` apparently does not recognize this, and then offers to generate a pointless addition to the nginx config:

```
server
{
    if ($host = www.my_domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


	listen 80;
	server_name my_domain.com www.my_domain.com;
	return 301 https://www.my_domain.com$request_uri; # enforce https


}
```

It seems that if the server config entry has a `return 301 https://<anything>` entry in it's root, certbot shouldn't even offer to add a https redirect of it's own, since it's already done?

It also appears that `certbot-auto` offers to add the redirect even if it's already present, but it apparently does remove the existing redirect if present.

This is definitely not a major issue.

**Comment by sydneyli** [comment]
Thanks for the report @fake-name! Yeah, we don't try to detect whether a redirect is already set before prompting the user about it. Wishlisting for now since we still do ask the user about it beforehands. If we do decide to redirect by default then I'd bump up the priority on this. If anyone's interested in implementing a fix for this in the meantime, we can give you some guidance!

**Comment by jonastheis** [comment]
I'd like to help out on this one. Can you please give me some guidance?

**Comment by fake-name** [comment]
As far as I know, this issue is as present now as it was when I reported it.

**Comment by RasPat1** [comment]
Related PR: #6539

**Comment by eddiewebb** [comment]
this IS a major issue when:
- using multiple domains with ALIAS
- trying to go direct from http-alias --> https-primary


Even with `--no-redirect` the installer will add the pointless blocks.

WHY that is a major issue for me is it violates google webmaster migration guidelines as the intermediate redirect does not match the expected (primary) domain.


### Before `certbot install -n --nginx --no-redirect -d mydomain -d aliasdomain`


```
server {
    listen 443;
    root /var/www/domain;
    index index.php index.html index.htm;
    server_name domain www.domain;
  ...
}
server {
    server_name domain;
    rewrite ^/(.*)$ https://domain/$1 permanent;
    listen 80;
}


#
# Aliases are a redirect, straight to https://domain
#  

  server {
    server_name aliasdomain  ;
    rewrite ^/(.*)$ https://domain/$1 permanent;
    listen 80;
}
 server {
    server_name aliasdomain  ;
    rewrite ^/(.*)$ https://domain/$1 permanent;
    listen 443;
}

```


After
```
server {
    listen 443;
    root /var/www/domain;
    index index.php index.html index.htm;
    server_name domain www.domain;

    # stronger SSL settings
    include optionals/strongssl.conf;
    # Gzip compression
    include optionals/gzip.conf;

    ...
    ssl_certificate /etc/letsencrypt/live/domain/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/domain/privkey.pem; # managed by Certbot

}
server {
    if ($host = domain) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
  # ^^^ pointless but no damage done....

    server_name domain; 
    rewrite ^/(.*)$ https://domain/$1 permanent;
    listen 80;
    
    
}   
#   
# Aliases are a redirect
# 

  server {
    if ($host = aliasdomain ) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
  
  #^^^^ breaks my setup adding extra rediredct not needed.

    server_name aliasdomain ;
    rewrite ^/(.*)$ https://domain/$1 permanent;
    listen 80;

}
 server {
    server_name aliasdomain  ;
    rewrite ^/(.*)$ https://domain/$1 permanent;
    listen 443;
    ssl_certificate /etc/letsencrypt/live/domain/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/domain/privkey.pem; # managed by Certbot
}

```


### Problem

Instead of respecting my `http://alias` --> `https://domain` 

certbot ignores my exsiting redirect, adds ots own, pointing to same domain, adding a hop and making google webmaster tools mad.

`http://alias` --> `https://alias` --> `https://domain` 

### Desired http flow is a single redirect, I can acheive this by deleting extra cettbo lines.

```
$ curl -IkL "http://aliasdomain/"
HTTP/1.1 301 Moved Permanently
Server: nginx/1.18.0 (Ubuntu)
Date: Sun, 19 Feb 2023 14:06:16 GMT
Content-Type: text/html
Content-Length: 178
Connection: keep-alive
Location: https://domain/

HTTP/1.1 200 OK
Server: nginx/1.18.0 (Ubuntu)
Date: Sun, 19 Feb 2023 14:06:16 GMT
Content-Type: text/html
Content-Length: 54252
Last-Modified: Sat, 04 Feb 2023 22:05:35 GMT
Connection: keep-alive
Vary: Accept-Encoding
ETag: "63ded6af-d3ec"
Strict-Transport-Security: max-age=63072000; includeSubdomains
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
Accept-Ranges: bytes
```
