### ISSUE TITLE
Tracking Amazon Linux 2 support

### ISSUE THREAD

**Issue by sydneyli** [certbot/certbot#6506]
Tracking issue for Amazon Linux 2 support.

If you stumbled onto this issue, try out our [CentOS/RHEL 7](https://certbot.eff.org/lets-encrypt/centosrhel7-other) instructions or one of the guides written by Amazon about this: [\[1\]](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/SSL-on-an-instance.html#letsencrypt) [\[2\]](https://aws.amazon.com/blogs/compute/extending-amazon-linux-2-with-epel-and-lets-encrypt/)

If you're having trouble getting Certbot to work on Amazon Linux 2, try asking for help [at the Let's Encrypt Community Forums](https://community.letsencrypt.org/c/help).

**Comment by RichardBradley** [comment]
This issue shouldn't have been closed. `certbot` does not yet install properly on Amazon Linux 2.

I got it working recently by installing from source, but it wasn't straightforward. The currently distributed binary package of certbot does not work. See my comment at #6505.

I really hate "stalebot". Just because no-one has commented for a little while doesn't mean that it's at all appropriate to close an active issue.
