### ISSUE TITLE
Getting root CA cert for Certificate generated by docker image

### ISSUE THREAD

**Issue by vineetvermait** [certbot/certbot#6530]
## My operating system is (include version):

Docker - Scratch/Alpine

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

I have Docker Image certbot/certbot:latest. 

## I ran this command and it produced this output:

certbot-auto certonly -d mydomain.com -n --preferred-challenges dns --manual-auth-hook /etc/scripts/manual-dns-auth.sh --agree-tos -m admin@mydomain.com --manual --manual-public-ip-logging-ok --server http://traefik.boulder.com:4001/directory

I received the certificates as expected:

- fullchain.pem
- chain.pem
- cert.pem
- privkey.pem

When i installed the same in an alpine/scratch image, and tried to make a call to the https service, the error i received was 

> TLS handshake error from 10.5.0.16:34980: remote error: tls: unknown certificate authority

Need to know how can i make the certificate authority trusted by the server as well as client

## Certbot's behavior differed from what I expected because:

The certificates installed were not trusted by the server/client. Expected was that the certificate authority would be trusted or at least Root CA certificate would be available...

**Comment by schoen** [comment]
Hi @vineetvermait,

Maybe you configured your HTTPS service with `cert.pem` instead of `fullchain.pem`?

**Comment by schoen** [comment]
Oh wait, I missed the really important detail that you were using some kind of Traefik CA rather than the public Let's Encrypt CA, via the `--server` option.

In this context I think your problem is real but has something to do with the integration of different parts of Traefik or with incomplete associated documentation there—not with the Certbot or Boulder software itself.

Could you please file this over at

https://github.com/containous/traefik/issues

or some other repository related to Traefik or its documentation? If anyone dealing with it needs any specific advice about our certificate technology, we'll be happy to help answer questions.

**Comment by vineetvermait** [comment]
The problem was that boulder image was using one of its test certificates to sign the certificates...meaning that the root ca was lying in the repository of lets encrypt boulder...

once i installed them as CA, it worked...
