### ISSUE TITLE
acme module: bad nonce error request retry logic regression

### ISSUE THREAD

**Issue by cpu** [certbot/certbot#6542]
:wave: Hi folks,

I think https://github.com/certbot/certbot/commit/0b5468e992ab57fa028ddf33ca2351cb37c8e1ee from https://github.com/certbot/certbot/pull/6522 introduced a regression that causes the retry logic for badNonce errors in the `acme` module to fail.

Pebble uses Certbot master for its acme module in CI:
https://github.com/letsencrypt/pebble/blob/dadfdf1571ab506718a5ac7face55778c3e2ee31/.travis.yml#L15-L20

It uses our small ACME test client ([`chisel2.py`](https://github.com/letsencrypt/pebble/blob/dadfdf1571ab506718a5ac7face55778c3e2ee31/test/chisel2.py)) to test issuance against a `pebble` instance that by default rejects 15% of all valid nonces as invalid so that client retries are exercised. 

Prior to 0b5468e992ab57fa028ddf33ca2351cb37c8e1ee Certbot and the `acme` module handled this as-expected and would retry requests that failed from a badNonce error. After this commit the badNonce errors seem to consistently cause an overall failure. Here's an [example build](https://travis-ci.org/letsencrypt/pebble/builds/461873896) of Pebble `master` with a log.

To confirm this was a regression I pushed 10 builds of Pebble master using Certbot master (named `test-certbot-regression-1` .. `test-certbot-regression-10`) and 10 builds of Pebble master using Certbot pinned [one commit before tip of master](https://github.com/letsencrypt/pebble/commit/63090c585740f66757c4cdb938a40350d454f7e7) at 8b5ac9e2573de9dfd4182bdcd98d7262a2bdc8f0 (named `test-certbot-regression-bisect-1` .. `test-certbot-regression-bisect-10`). The results are visible [here](https://travis-ci.org/letsencrypt/pebble/branches). All 10/10 of the builds using `acme` from Certbot master failed and all 10/10 of the builds pinned a commit before passed.

**Comment by bmw** [comment]
@adferrand, @ohemorange: Are you able to take a look at this?

We can always revert #6522 for now until we've been able to fix any problems here.

**Comment by ohemorange** [comment]
Let's revert now so tests pass

**Comment by adferrand** [comment]
So I put here what has been discussed on IRC. In fact this is an expected behavior. Certbot will try only once the request on a badNonce error.

As Pebble randomly refuses the badNonce, there is a probability that a request is refused more than two times, and that will lead Certbot to give up. And fail the test.

This probability was sufficiently low before, to not be observed very often in the tests. 

However, the POST-as-GET drastically increased the probability. First, because most of the get requests are now post requests, exposed to the badNonce error. So there is an order of magnitude more of post requests for a standard certificate issuance workflow. Second, by the fact that Pebble will sleep for a while before trying the challenge, leading Certbot to poll regularly until the challenge is tested and the certificate issued: the polls are done as post-as-get, so it adds another order of magnitude of post requests.

All of this push the probability at sufficiently hight level to almost always fail the test.

So the test is inherently unstable. Its unstability can be reduced by playing with three parameters: reducing the percentage of random badNonce errors rate of Pebble, reducing the sleep time before challenge testing of Pebble, and increasing the number of retry on badNonce error of Certbot.

**Comment by cpu** [comment]
> reducing the percentage of random badNonce errors rate of Pebble, reducing the sleep time before challenge testing of Pebble

I can take these on our side :+1: I'd like to keep the values high enough to encourage client developers to implement retries but the current rate of nonce rejection is probably too high.

> increasing the number of retry on badNonce error of Certbot.

I think this with an appropriate backoff schedule would be a good idea for the long-term robustness of Certbot but I can understand not prioritizing it - presently it seems to primarily affect Pebble & its a pretty artificial environment :-)

@ohemorange @bmw @adferrand Are you folks happy if I close this issue & if you feel up to improving the retry robustness it could be tracked separately in a dedicated issue?

Thanks for investigating!

**Comment by adferrand** [comment]
From Certbot, I propose to implement a configurable number of retries on badNonce errors, by environment variable or cli parameter, and to increase the number of retries (so a default value), to 2.

cc @ohemorange @bmw

**Comment by ohemorange** [comment]
I think if 2 retries fixes the problem here, we should hold off on adding yet another configuration option, because we already have an unmanageable amount.

**Comment by cpu** [comment]
> Either way, I agree that the issue should be close, and open a feature issue instead.

Sounds good. Thanks all!
