### ISSUE TITLE
Certbot doesn't work on Ubuntu 16.04, outputs pkg_resources.ContextualVersionConflict

### ISSUE THREAD

**Issue by hbielenia** [certbot/certbot#6587]
## My operating system is (include version):
Ubuntu 16.04 (xenial)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Package manager, using instructions from https://certbot.eff.org/lets-encrypt/ubuntuxenial-nginx

## I ran this command and it produced this output:
`$ sudo certbot --nginx certonly`
```
An unexpected error occurred:
pkg_resources.ContextualVersionConflict: (cryptography 1.9 (/usr/lib/python3/dist-packages), Requirement.parse('cryptography>=2.2.1'), {'PyOpenSSL'})
Please see the logfile '/tmp/tmpfwhq_j1x' for more details.
```

## Certbot's behavior differed from what I expected because:
It returned a version conflict where all dependencies were installed automatically and not changed by me.

## Here is a Certbot log showing the issue (if available):
n/a

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
```
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
        }
}
```

**Comment by bmw** [comment]
You have a mix of Python packages from multiple sources. The version of `pyopenssl` available both in Ubuntu's official repos and our PPA do not depend on that version of `cryptography`. Usually this is caused by installing packages from `pip` which I strongly recommend you do not do outside of a virtual environment. I recommend you remove these packages and try running Certbot again.

If you need more help, you should make a post on https://community.letsencrypt.org where there is a large community of users familiar with the project who should be able to help you clean up the installed Python packages on your system.
