### ISSUE TITLE
Do you support Wildcard Subdomain

### ISSUE THREAD

**Issue by gremdev** [certbot/certbot#66]
[Moderator's note: If you'd like to express your support for wildcard issuance, please hit 'like' on [this thread on the community forum](https://community.letsencrypt.org/t/please-support-wildcard-certificates/258) rather than opening an issue.]

Hi, I have a question. Does Let's Encrypt supports wildcard subdomain or just just the main domain/www only? Thanks.

**Comment by jbiel** [comment]
+1. We make use of wildcard certs in lots of places and this would be very useful to us. They help us reduce our administrative overhead by simply installing one cert rather than one for each hostname.

**Comment by jdkasten** [comment]
@jbiel If it helps, we will support names with multiple Subject Altnerative Names (SANs or UCC certificates in the CA nomenclature) at launch.  This would allow you to simply specify your names ahead of time and get a single certificate for all of them.

This does create a hassle when you do add a new subdomain, but hopefully the 30 second process shouldn't be that large of a problem.

**Comment by jbiel** [comment]
@jdkasten - thanks. I certainly can't complain about whatever decision is made (these certs are free after all!) However, changing a cert is not a 30 second process for everyone. Deployment architectures can be very complex and spread across many servers/technologies (ELBs, haproxy (which needs to be restarted), etc.) I can see how changing the certificate on a single development server would be very quick, but changing SSL certs isn't something I look forward to in any case. :)

**Comment by lbadger** [comment]
+1 to support wildcard certs!

**Comment by rcc26** [comment]
As far as I know wildcard support is not implemented and won't be.

Lance Badger <notifications@github.com> escreveu no dia qui, 26/02/2015 às
17:59:

**Comment by coe-jeubanks** [comment]
Hi everyone, before you make the final decision on this topic, I hope you'll consider a real world example where wildcard certs are more than a convenience. In IIS, only one certificate can be specified for a site (which runs from a single folder). If a CMS in that IIS site folder serves multiple subdomains, then a wildcard certificate is required in order to secure all of them.

So without wildcard certificate support, that class of customer (my organization included) would be unable to use letsencrypt. Thanks for your consideration of this feature! I'm really looking forward to seeing how it all comes together, especially from a Windows perspective.

**Comment by diracdeltas** [comment]
@coe-jeubanks Thanks for the info. Please see https://github.com/letsencrypt/acme-spec/issues/64 and https://github.com/letsencrypt/acme-spec/pull/97 for the current wildcard discussion.

**Comment by mscreenie** [comment]
Definitely need wildcard certs. It will reduce sys admins workloads.

pls spoderman.

**Comment by blieque** [comment]
I'll chime in, with a familiar tone. Wildcard certificates would make life much easier.

**Comment by oliverjanik** [comment]
@coe-jeubanks You can have multiple certs in IIS if you enable SNI

**Comment by uakfdotb** [comment]
Wildcard certificates are also necessary for websites that use the subdomain to generate dynamic content. For example https://onion.to

**Comment by FranBar** [comment]
+1

**Comment by NurdTurd** [comment]
+1

**Comment by mesouug** [comment]
+1

**Comment by mjbrownie** [comment]
+1

**Comment by lewie** [comment]
+1

**Comment by Murilirum** [comment]
+5

**Comment by samholmes1337** [comment]
+1

**Comment by frederich** [comment]
+1

**Comment by tvvocold** [comment]
+1

**Comment by pinki** [comment]
+1

**Comment by jdkasten** [comment]
This is the client code repo. Policy discussions should be had elsewhere.

https://community.letsencrypt.org/t/please-support-wildcard-certificates/258

Some other work and discussion...
https://github.com/letsencrypt/acme-spec/pull/97

**Comment by NGenesis** [comment]
+1

**Comment by carras** [comment]
+1

**Comment by frankhommers** [comment]
+1

**Comment by 77v** [comment]
+1

**Comment by Firefishy** [comment]
Instead of +1'ing... Top right of this issue on Github under Notifications click the subscribe button. KThxBye

**Comment by blieque** [comment]
@Firefishy I think people are voicing their support more than anything. People showing that they want wildcard certificates if the best thing for them to do.

**Comment by jmhodges** [comment]
+1 comments here spam all of the developers and everyone else subscribed to this thread with noise. The developers are extremely aware of this feature request. Follow up, +1s, and discussion about Let's Encrypt in general (instead of just about the client) can happen on [the community website](https://community.letsencrypt.org/t/please-support-wildcard-certificates/258).

Thanks much for your interest!

**Comment by NurdTurd** [comment]
Good clarification @jmhodges.

**Comment by mikebronner** [comment]
I also wanted to add that wildcard certs are invaluable for multi-tenant sites, where sub-domains are generated dynamically for each client. Having to reregister a cert each time a client signs up isn't really  practical.

**Comment by uakfdotb** [comment]
@mikebronner I mentioned above about websites like https://onion.to that don't have defined subdomains, and so the webserver might need to fetch a new certificate for each request.

However, registering a new certificate each time a client signs up seems to be much less complicated. Can you clarify why it's not practical with the automated system that letsencrypt would be providing?

**Comment by mikebronner** [comment]
@uakfdotb You are absolutely right, I skipped the automated process part for some reason. :) It would be trivial to script a command that runs for each client signup.

**Comment by DominikTo** [comment]
Not sure if that has been previously discussed (at least I didn't see it in here), but a use case where there is almost no practical way around wildcard certificates is when using a load balancer such as AWS ELB with multiple vhosts behind it and doing SSL termination on the load balancer. Without wildcard certificates you have to spin up a separate ELB for every vhost, which not only results in additional management workload, but also significantly increases cost.

**Comment by FranBar** [comment]
If you open a kiosk in the desert to sell umbrellas, what do you think people will ask? water!

There are already methods to get free or low-cost certificates, we want water! :-)

They should not be angry because people ask them what they need.

**Comment by bjm904** [comment]
I would love Wildcard support however I do understand this:
"Wildcard certificates decrease the effectiveness of fraud-containment measures on the CA side"
http://security.stackexchange.com/a/32366/46982

**Comment by FranBar** [comment]
We need a protocol to simply encrypt traffic, without server authentication. The self-signed certificates would be an option if an error does not show, it is safer traffic with a self-signed certificate that any at all.

**Comment by ntdaley** [comment]
FranBar:

1. They're not selling umbrellas in the desert.  They're giving away water
in the desert, and people are complaining it's not tropical punch.
2. If you can't verify the validity of a certificate, then people can do a
man-in-the-middle attack on the traffic, and you've won nothing from the
encryption.


--
bits and peace
Nicholas Daley

**Comment by FranBar** [comment]
You've convinced me, much better no encryption at all. :-)

* Umbrellas give shade, I do not say it offers something useless.

**Comment by lewie** [comment]
Sorry, but you FranBar did not understand what a real desert is, or to hope stay the only seller of water in desert? ;-)

Self-signed certificates are no option for anybody it is a crutch from air.
To become a little more safety is an initiative like letsencrypt and all and you know this exactly.

**Comment by FranBar** [comment]
With the desert simile not intended to criticize the project, only anger with wildcard +1.

I do not care if they are certified in one kind or another, but we need a fast, simple and free system to encrypt the traffic, including wildcards, the current situation is anachronistic.

**Comment by HLFH** [comment]
.@Angristan and I are also adding with anger our +2. 

![Image of Yaktocat](https://octodex.github.com/images/yaktocat.png)

**Comment by FranBar** [comment]
So angry can even affect your health.

**Comment by Angristan** [comment]
I'm not as angry as my name would let you think, but I add of course my +1. Generating a certificate for each subdomain is such a pain... I would be a great feature for Let's encrypt. At this point, does it even support subdomains ?

**Comment by rcc26** [comment]
Why are we even still discussing wildcard? This is already free, get your
contempt down. It's sad when people don't understand the problem of using
wildcard and keep bashing about it just because they are too lazy to build
their own (sub)domain records which considers lazyness over security.

Angristan <notifications@github.com> schrieb am Mi., 28. Okt. 2015 08:55:

**Comment by Angristan** [comment]
Why wildcards exist then ?

**Comment by oliverjanik** [comment]
@rcc26 Where can I get free wildcard certs accepted by all major browsers? For environments like ELB on AWS you can only have one ssl cert per ELB. Wildcards solve real problems people have.

**Comment by svennek** [comment]
Actually the (open source) web-platform sandstorm (http://sandstorm.io) NEEDS wildcard to run, else it will be completely unprotected...

**Comment by ccatlett2000** [comment]
@rcc26 As others have said, some services mint wildcards on the fly, and as such *need* wildcard support. Some of these services cannot afford to wait 30 seconds when a new subdomain is accessed. In example, https://onion.to uses subdomains as input.

Some applications of wildcards aren't laziness but legitimate design decisions.

In relation to wildcards, +1

**Comment by ducktype** [comment]
+1

**Comment by kyrylkov** [comment]
+1

Wildcard certs are *required* by IBM Bluemix

**Comment by hyusetiawan** [comment]
considering that wildcard costs a lot more from commercial CAs, it would be very beneficial for us to have it.

**Comment by s0r00t** [comment]
+1
Wildcards are expensive, and it would be very useful for a lot of tools, such as [ngrok](https://ngrok.com/), or [YunoHost](http://yunohost.org/).

**Comment by chmduquesne** [comment]
+1

I use 26 domain names in my lighttpd.conf, and I am glad this is the only file I have to maintain. I would like to keep it that way.

**Comment by mloffer** [comment]
+1

**Comment by VarunAgw** [comment]
+1.  StartSSL already offers a free SSL certificate. They are not very costly either. But currently there is no way to get a wildcard certificate for cheap.

**Comment by ChioriGreene** [comment]
I want to say that I totally understand not implementing wildcard subdomains at the moment, you need to focus on the general product first, but please AS SOON AS POSSIBLE.
I too have similar issues of needing to add a subdomain at a moments notice, while it was previously suggested to rerun the script each time you need to add a subdomain, I want to point out this is NOT an option because I just received my beta invite and according to it, each domain and subdomain needs to be whitelisted explicitly, one can't just whitelist the TLD and expect all subdomains to whitelist. So now I'm disappointed because I have to resubmit my beta request with all my current subdomains and resubmit a beta request for each subdomain I add in the future, so now I'm waiting a few weeks again.

**Comment by njb-said** [comment]
@ChioriGreene I am in exactly the same position as you and second your comment :+1:

**Comment by ChioriGreene** [comment]
@njb-said I did just see the announcement that Public Beta is coming December 3rd, so this should remedy the Beta Invite problem unless that is they still require whitelisting in one way or other.

**Comment by VarunAgw** [comment]
Letsencrypt will be in public beta soon so I think white-listing sub-domain will be instant after that. 

https://letsencrypt.org/2015/11/12/public-beta-timing.html

**Comment by Yamakaky** [comment]
Don't close the issue, it's not solved.

**Comment by ukkpower** [comment]
+1

**Comment by elpado** [comment]
+1

**Comment by GodMod** [comment]
+1

**Comment by smarek** [comment]
+1

**Comment by NHellFire** [comment]
It'd be good to have wildcard certificates. One of my sites, subdomains are dynamically generated.. currently there's ~220 in use. I could script it to get a new certificate when a new subdomain is requested.. but that leaves some issues, neither of which I like.
I'd have to either..
a) One cert for all subdomains, which then means there's a list of the ones in use.
or b) One cert per subdomain and a script to generate a huge config file.
Either way the subdomain is left without a valid certificate for couple minutes.

**Comment by zaninime** [comment]
+1

**Comment by jmhodges** [comment]
Hey, folks, thanks for the input! We're super aware of this feature request. Wildcard support is highly desirable for us, too! However, doing domain validation for wildcard certificates is not currently in the ACME spec because it's a hard problem. We want to get it right in Let's Encrypt, right in the ACME spec, and, currently, we're swamped in work getting Let's Encrypt ramped up for the Public Beta on December 3rd.

More discussion on this topic is best done on the [community site](https://community.letsencrypt.org/) as this repo is specifically for the client code and, really, this is a bigger project. I've locked this ticket. Thanks, y'all!
