### ISSUE TITLE
Self signed certificate continues to be served with Apache on CentOS 6

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6606]
I've heard about two reports of the Apache plugin thinking it obtained and installed a certificate for Apache on CentOS 6, but when the user visits their domain, Apache's self signed certificate is served. This is a pretty serious problem and should be fixed.

The one report I've seen myself is at https://community.letsencrypt.org/t/connection-not-secure-on-centos-6/80054. @schoen has seen more.

We're thinking this probably has something to do with vhost precedence rules, especially on CentOS 6 where if I remember correctly, [NameVirtualHost](https://httpd.apache.org/docs/2.2/mod/core.html#namevirtualhost) is disabled by default.

We should definitely try and get a configuration that reproduces this problem as it will make debugging much easier.

**Comment by bmw** [comment]
I'm moving this to the current sprint because I think its one of our more important tasks and it makes it more visible.

**Comment by schoen** [comment]
I tried testing this today and I found that it was quite easy to reproduce (fortunately and unfortunately, we might say).

I installed CentOS 6.9 on a new VM, installed Apache, and created a single HTTP virtual host in `/etc/httpd/conf.d` for a name which was pointed at the CentOS machine. The machine didn't immediately support HTTPS at all.

When `certbot-auto` installed packages including `mod_ssl`, the `/etc/httpd/conf.d/ssl.conf` was added. The `certbot-auto` process then obtained a cert and created an `-le-ssl` variant of my existing HTTP virtual host.

However, the new cert was not actually used; instead, the default system cert specified with `<VirtualHost _default_:443>` in `ssl.conf` continued to be used. :slightly_frowning_face: That virtual host (just as in a number of users' similar experiences) seems to override the more-specific one in the Certbot-created `-le-ssl` file!

This is a relatively plausible sequence of events for a new user on CentOS 6.9, so I guess this bug is pretty easy to run across.

**Comment by joohoi** [comment]
I have looked into this as well, and the CentOS 6 HTTPS VirtualHost precedence seems to be decided by the `Include` order, and the _**last**_ one taking over the control. One of the common configuration structure that users of CentOS have is having all `VirtualHost`s in the main `httpd.conf` file. In this case everything works as expected, as the HTTPS configuration file created by Certbot gets `Include`d in the end of `httpd.conf`. 

It all works also if your `VirtualHost` configuration filename under `conf.d/` comes after filename `ssl.conf` when sorted alphabetically. So the Certbot configuration for `VirtualHost` in `conf.d/kissa.conf` would fail to take precedence while `conf.d/this.conf` would succeed.

Everything works also, if the created HTTPS `VirtualHost` configuration file is `Include`d separately in the end of `httpd.conf` regardless of being already included earlier through directive like `Include conf.d/*`.

So easy fix - while absolutely not optimal - here would be always adding a `Include conf.d/$SSL_VHOST_FILENAME` to the end of `httpd.conf` for CentOS 6.

**Comment by bmw** [comment]
> I have looked into this as well, and the CentOS 6 HTTPS VirtualHost precedence seems to be decided by the Include order, and the last one taking over the control. 

That's insane :/

Does Apache 2.2 really not offer a more robust way to control vhost precedence here?

**Comment by schoen** [comment]
> Everything works also, if the created HTTPS VirtualHost configuration file is Included separately in the end of httpd.conf regardless of being already included earlier through directive like Include conf.d/*.

!

I just confirmed this on my CentOS VM. The same configuration file consistently works, or doesn't work, depending on whether it's named `foo.conf` or `yowl.conf`!

**Comment by schoen** [comment]
We would have an even more amazing Heisenbug here if SSL had been named ZSL (in honor of Phil Zimmermann or something).

**Comment by schoen** [comment]
Another potential fix would be to move the Apache package's `conf.d/ssl.conf` into `conf` and then change the `Include` line to the two lines

```
Include conf/ssl.conf
Include conf.d/*.conf
```

**Comment by schoen** [comment]
I had good luck with this approach:

```
Include conf.d/ssl.conf
Include conf.d/[s].conf
Include conf.d/[^s]*.conf
Include conf.d/s[^s]*.conf
Include conf.d/ss[^l]*.conf
```

It doesn't require moving or renaming any files. (This version fails to include `conf.d/.conf`, which might have been included by the original `Include` directive.)
