### ISSUE TITLE
acme library HTTP01Response.simple_verify should not verify host certificate

### ISSUE THREAD

**Issue by gpjt** [certbot/certbot#6614]
## My operating system is (include version):

Ubuntu 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

pip install acme

## I ran this command and it produced this output:

We have some custom code using the `acme` library directly to generate Let's Encrypt certificates for our customers.

If a customer has a site set up with an invalid certificate, which redirects HTTP traffic to HTTPS, then calling `simple_verify` on an `HTTP01Response` throws an exception because the server certificate is invalid.   This is because it's using

```python
http_response = requests.get(uri)
```

...at line 311 in `acme/challenges.py` rather than

```python
http_response = requests.get(uri, verify=False)
```

## Certbot's behavior differed from what I expected because:

The Let's Encrypt servers do not validate the HTTPS certificate when handling the challenge, so `simple_verify` is inconsistent with what will happen when you call `acme.answer_challenge`.  Given that fixing broken certificates by issuing good ones is pretty much what people are using the system for, the server's behaviour feels like it's the right way to go.

Happy to put in a pull request if it would help!

**Comment by sydneyli** [comment]
We're aware that `simple_verify` is not entirely consistent with the ACME challenge checks, and because of these discrepancies and a couple other issues (according to @bmw, verifying challenges on the same machine that served them was unreliable) we stopped using it in Certbot a while back, too. It's sort of legacy at this point, and we haven't pulled it out since we know other acme clients use it-- though we should at least make the status of this routine clear in the documentation.

However, if you're still inclined to use it in your own ACME client, feel free to make a PR to put in this relatively straightforward change!

**Comment by gpjt** [comment]
Thanks for the details!  Is there something else we should use instead of `simple_verify`?  We just want to do some basic preflight checks to make sure everything is working on our side before bothering the Let's Encrypt servers with our cert request.

**Comment by sydneyli** [comment]
What we do in [our integration tests](https://certbot.eff.org/docs/contributing.html?highlight=boulder#integration-testing-with-the-boulder-ca) is spin up a local instance of [Boulder](https://github.com/letsencrypt/boulder) (the CA software LE uses) which is a much better approximation of how LE will actually respond! The code for this is in [boulder_fetch.sh](https://github.com/certbot/certbot/blob/master/tests/boulder-fetch.sh).

**Comment by gpjt** [comment]
Thanks!  I've submitted a PR.

**Comment by m0namon** [comment]
This is still a problem.
