### ISSUE TITLE
certbot delete by name

### ISSUE THREAD

**Issue by bes-internal** [certbot/certbot#6625]
`certbot delete` should allow to delete by domain name (-d) or at least filter to select by number

**Comment by sydneyli** [comment]
> allow to delete by domain name (-d)

I like this as a UX improvement to cert selection in general. Flagging @ohemorange because cert management UX things. Would you like to work on this?

> filter to select by number

What do you mean by this?

**Comment by ohemorange** [comment]
We didn't do this because multiple certs might include the same domain, and there can be overlapping subsets of certs and domains. So then you'd have to run `certbot certificates` anyway (or at least print its results) to figure out which is the right one.

If each cert only has one domain in it, the `--cert-name` will be the domain name and that can be passed to `certbot delete`.

**Comment by sydneyli** [comment]
Thanks @ohemorange, that makes sense. Closing!

**Comment by bes-internal** [comment]
> We didn't do this because multiple certs might include the same domain

In this case, you must show all records of certificates with this domain in order for the user to choose from this short list himself by number. Or. You must delete only certificates with the same set as the user has typed in for `certbot delete`.

> If each cert only has one domain in it, the --cert-name will be the domain name and that can be passed to certbot delete

Great, it works! But I didn't know it because the --help command looks like this:
```
    certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN]
    ...
    manage certificates:
    certificates    Display information about certificates you have from Certbot
    revoke          Revoke a certificate (supply --cert-path or --cert-name)
    delete          Delete a certificate
```


>  filter to select by number

My list of domains includes 1500 pieces of unsorted records in the output `certbot delete`. It would be nice to deduce only the domains containing the substring from the input. Like `certbot delete exam` show only \.\*exam\.\* cert names.

**Comment by sydneyli** [comment]
Re-opening!

Thoughts, @ohemorange?

**Comment by sydneyli** [comment]
@bes-internal To be specific: if you're interested (or anyone else looking at this issue is interested) in taking this on, please do! We probably won't have the capacity to work on this for a while.

Also, to get help for a particular subcommand you can do `certbot <subcommand> help`, for instance in your case you can do `certbot delete help` ^_^

**Comment by ohemorange** [comment]
```
$ certbot --help delete
usage: 

  certbot delete --cert-name CERTNAME

optional arguments:
  -h, --help            show this help message and exit
  -c CONFIG_FILE, --config CONFIG_FILE
                        path to config file (default: /etc/letsencrypt/cli.ini
                        and ~/.config/letsencrypt/cli.ini)

delete:
  Options for deleting a certificate

  --cert-name CERTNAME  Certificate name to apply. This name is used by
                        Certbot for housekeeping and in file paths; it doesn't
                        affect the content of the certificate itself. To see
                        certificate names, run 'certbot certificates'. When
                        creating a new certificate, specifies the new
                        certificate's name. (default: the first provided
                        domain or the name of an existing certificate on your
                        system for the same domains)
```

I think that having a system that the user has to intuit to filter domains isn't quite the UX direction we want to take. I've pasted above the output of the specific help for the `delete` subcommand. How can we improve this text so that another person with a similar issue would understand about using the `certificates` subcommand in conjunction with `delete`?

**Comment by bes-internal** [comment]
Now everything got clear.
1. `certbot delete help` this is not working
2. `certbot delete --help` show help of certbot itself, but not delete subcommand.  I understand why this was created so, but if you want to improve usability, then you need to create an alias for `--help` of subcomand `delete` to `certbot --help delete`. Repeat for all subcommands. This is exactly the expected behavior.
3. `certbot --help delete` its clear to undestand, nothing to improve
4. You should improve out of `cetbot --help` in place of subcommand `delete` with this text (bold):

> ...
> manage certificates:
>     certificates    Display information about certificates you have from Certbot
>     revoke          Revoke a certificate (supply --cert-path or --cert-name)
>     delete          Delete a certificate _**(supply --cert-name)**_

**Comment by trinopoty** [comment]
I've looked into this and I've come up with two possible ways and their respective problems:
- Force user to supply all domains using the `-d` parameter. The problem being that the user has to know all the domains. This is the easiest to implement but I'm guessing not what we want.
- Allow the user to select from a list after filtering the lineages using the domains provided using `-d`. This option will need some changes to a lot of parts since this kind of filtering isn't supported atm as far as I know.
