### ISSUE TITLE
ContextualVersionConflict with CloudFlare

### ISSUE THREAD

**Issue by Bluscream** [certbot/certbot#6645]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Linux teagaming.de 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
First with certbot-auto as instructed on https://certbot.eff.org/lets-encrypt/debianstretch-apache
After that with `sudo pip install certbot-dns-cloudflare` as instructed on https://bjornjohansen.no/wildcard-certificate-letsencrypt-cloudflare

## I ran this command and it produced this output:
root@teagaming:~# /usr/local/bin/certbot certonly --dns-cloudflare --dns-cloudflare-credentials /root/.secrets/cloudflare.ini -d mexogames.de,*.mexogames.de --preferred-challenges dns-01
An unexpected error occurred:
ContextualVersionConflict: (cryptography 1.7.1 (/usr/lib/python2.7/dist-packages), Requirement.parse('cryptography>=2.2.1'), set(['PyOpenSSL', 'pyOpenSSL']))
Please see the logfile '/tmp/tmp0Q7b0n' for more details.

## Certbot's behavior differed from what I expected because:
I don't know why it is different, i just know that it is.

## Here is a Certbot log showing the issue (if available):
root@teagaming:~# cat /tmp/tmpZPqVif
2019-01-06 16:44:23,441:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/certbot/main.py", line 1334, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/local/lib/python2.7/dist-packages/certbot/plugins/disco.py", line 206, in find_all
    plugin_ep = PluginEntryPoint(entry_point)
  File "/usr/local/lib/python2.7/dist-packages/certbot/plugins/disco.py", line 52, in __init__
    self.plugin_cls = entry_point.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2290, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2307, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 854, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (cryptography 1.7.1 (/usr/lib/python2.7/dist-packages), Requirement.parse('cryptography>=2.2.1'), set(['PyOpenSSL', 'pyOpenSSL']))
2019-01-06 16:44:23,441:ERROR:certbot.log:An unexpected error occurred:

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
idk whats relevant?

**Comment by schoen** [comment]
Hi @Bluscream and @khasburrahman,

We currently don't have an officially supported way to install the DNS plugins on operating systems where you use `certbot-auto`. We realize that this is a problem and we're working on it. Two issues related to this are

https://github.com/certbot/certbot/issues/6531
https://github.com/certbot/certbot/issues/6613

and there may be others.

Broadly, the `ContextualVersionConflict` error arises when you use `pip` manually and there is some kind of dependency version conflict.

As we currently have no supported way to do this, I'm going to close the issue as a special case of the known problem that DNS plugins aren't supported with `certbot-auto`. I suggest that you look for help with workarounds on the Let's Encrypt Community Forum, perhaps by searching for `ContextualVersionConflict` there. For example, one person with a similar problem found a workaround here:

https://community.letsencrypt.org/t/centos7-certbot-python2-cryptography-version-mismatch/81161

If no existing thread on the forum addresses your problem, you could start a new one and share ideas with other people there.

Also, on operating systems where we don't have an OS package or PPA containing the DNS plugins, you might want to try the alternative client acme.sh (https://github.com/Neilpang/acme.sh) instead of Certbot if you need to do DNS authentication—it has excellent DNS API support natively in the client and has dramatically fewer dependency issues than Certbot.

Sorry for the inconvenience!

**Comment by schoen** [comment]
Just to clarify, the advice at https://bjornjohansen.no/wildcard-certificate-letsencrypt-cloudflare is not something we officially support because we don't recommend manually installing anything Certbot-related via `pip`. You might want to ask the original author of this advice to investigate workarounds for this problem because it's clear that it's arisen in several circumstances where people ran `pip` themselves to install Certbot dependencies or plugins.

**Comment by schoen** [comment]
My colleagues have pointed out that for certain operating systems which should include both of yours, we do already have official solutions using OS packages. In that case, you wouldn't need to follow external tutorials related to pip, because you wouldn't need to use certbot-auto at all. Please see https://certbot.eff.org/ and select your operating system environment there for instructions, including instructions related to installing plugins.

**Comment by Bluscream** [comment]
Thanks for the heads-up. I really appreciate the explanations!

**Comment by Bluscream** [comment]
P.S. You might want to make your tutorials more clear so one like me doesn't get the idea of searching advice on sites like bjornjohansen.no

**Comment by Yamboy1** [comment]
For anyone who installed cloudflare-dns-certbot through pip and now getting this error, make sure you uninstall both cloudflare-dns-certbot AND certbot through pip. `pip uninstall cloudflare-dns-certbot certbot`, this shouldn't affect your local installation

**Comment by bjornjohansen** [comment]
Hi, I’m the author of the article on bjornjohansen.no, and found this issue because, well, the pip installation method didn’t work. It used to be the easiest way to install certbot with plugins, but now that OS packages are available, together with the excellent installation guide on https://certbot.eff.org/instructions, that’s much better.

(Oh, and of course I have updated the article mentioned above.)
