### ISSUE TITLE
dns_rfc2136: UDP instead of TCP, seperate SAO request server for dyn.com / dyndns.com

### ISSUE THREAD

**Issue by magnific0** [certbot/certbot#6655]
## My operating system is (include version):
python2.7

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt

## I ran this command and it produced this output:
hangs during certificate generation, then produces a dnspython timeout

There are three issues to be solved to make certbot also compatible with dyn.com

1. update.dyndns.com only support UDP. 
2. update.dyndns.com does not support domain name queries, only does updates.
3. subsequent `.add` with records of the same name are [updated instead of added](https://www.dyncommunity.com/questions/7682/update-an-address-entry-without-replace-the-previo.html) (i.e., resulting in one entry). For wildcard and domain certificate, two TXT entries with the exact same record name are required. This is only possible if the records are added in the same request. Hence a little dictionary of lists to keep a history.

I believe issues 1 and 2 are perhaps something to implement as configurable items for the general rfc2136. Issue 3 is really an issue with Dyn.com, however this was already addressed 8 years ago and is likely to be fixed.

I have uploaded my ["fixed" dns_rfc2136.py here.](https://gist.github.com/magnific0/8f71defb6a2bf4d7b8a424512e61972a). Unfortunately, I don't have time to make this into a pull request, nor do I think it's ready for that in this state.

**Comment by schoen** [comment]
@bodgit, would you be willing to comment on this (whether or not you want to actually deal with the code changes)?

**Comment by bodgit** [comment]
It doesn't seem to be a very conforming DNS server.

1) The reason for using TCP is to prevent getting truncated responses, without investigating I'm not sure how likely that would be when using UDP but you would likely need to add retrying with TCP to be on the safe side.
2) That behaviour just seems odd. Querying is used in order to be able find the closest SOA, your patched version just seems to circumvent that by hardcoding the answer.
3) That's doesn't appear to be RFC-compliant behaviour.

The first point seems to be the only one that could be realistically addressed in a generalised way.

**Comment by schoen** [comment]
Thanks, @bodgit!

@magnific0, in light of @bodgit's comments, I'm going to suggest that these behaviors ought to be fixed by Dyn on their end, rather than in Certbot. But thank you for sharing your workaround here. It may be very helpful to other users who encounter the same problem.

If you find that Dyn is unwilling to fix these issues, or you need our help in contacting them, or you find another dynamic DNS provider with the same problems, please continue to post here and we'll see if we can do anything.

**Comment by magnific0** [comment]
@bodgit @schoen Thanks for reacting so quickly. 

I agree that the Dyn server is not behaving normally. For me the issue is fixed and I understand the reluctance to incorporate these changes, especially the non-compliant adding of records. 

At least we have a note of the issue here and an outline of my fixes, so hopefully it's helpful to other in that respect.

**Comment by bodgit** [comment]
If there is a different API available for Dyn, it might make sense to create a separate authenticator. The only reason I suggest that is that Hashicorp Terraform has a dedicated [Dyn provider](https://www.terraform.io/docs/providers/dyn/index.html) which I have briefly used that doesn't seem to use RFC 2136 DNS updates, it looks like some sort of HTTP API.
