### ISSUE TITLE
certbot --nginx ignores http-01-address, instead of adding it to listen directive

### ISSUE THREAD

**Issue by manger** [certbot/certbot#6716]
On renewing a cert using the nginx module in http-01 mode, the nginx server block generated by certbot (...['listen', '80']...) causes a failure (bind() to 0.0.0.0:80 failed (98: Address already in use)) if the nginx configuration specifies an address when it listens to port 80 (listen 1.2.3.4:80).

Configuring Nginx to serve http typically involves a line like:
  listen 80;
But when a server has multiple IP addresses and you only want to use 1 the line can be:
  listen 1.2.3.4:80;
However, the latter seems to clash with the block generated by certbot (which appears to be equivalent to "listen 80"), causing a "address already in use" error and hence the ACME challenge not being properly answered.

Certbot has a --http-01-address option (which I believe sets an http01_address line in /etc/letsencrypt/renew/x.example.com.conf). The Nginx should probably use this to restrict the "listen" directive that it generates to just the specified address.

The function _default_listen_addresses in certbot_nginx/http_01.py should use http01_address (not just http01_port).

## My operating system is (include version):
Ubuntu 18.04.1

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS package manager

## I ran this command and it produced this output:
$ sudo certbot --nginx --http-01-address 1.2.3.4
...
[from /var/log/nginx/error.log]
2019/01/29 10:55:57 [emerg] 5566#5566: bind() to 0.0.0.0:80 failed (98: Address already in use)

## Certbot's behavior differed from what I expected because:
Certbot should be able to listen on port 80 as well as the rest of the web server, even when the rest of the web server is only listening on a specific IP address.

## Here is a Certbot log excerpt showing the issue (if available):
2019-01-29 08:57:45,822:DEBUG:certbot.plugins.selection:Requested authenticator nginx and installer nginx
2019-01-29 08:57:47,445:INFO:certbot.auth_handler:Performing the following challenges:
2019-01-29 08:57:47,446:INFO:certbot.auth_handler:http-01 challenge for x.example.com
2019-01-29 08:57:47,463:INFO:certbot_nginx.http_01:Using default address 80 for authentication.
2019-01-29 08:57:47,465:DEBUG:certbot_nginx.http_01:Generated server block:
[[['server'], [['listen', '80'], ['server_name', 'x.example.com'], ['root', '/var/lib/letsencrypt/http_01_nonexistent'], [['location', '=', '/.well-known/acme-challenge/Klxm1KXttUeSoAlQN-jRLoFFDzs
3-WllD4jm9uKhfsI'], [['default_type', 'text/plain'], ['return', '200', 'Klxwu5746D....I_GK_Q8dTdShh...']]]]]]

2019-01-29 08:57:47,471:DEBUG:certbot_nginx.parser:Writing nginx conf tree to /etc/nginx/nginx.conf:
include /etc/letsencrypt/le_http_01_cert_challenge.conf;

2019-01-29 08:57:51,821:DEBUG:acme.client:Sending GET request to https://acme-staging-v02.api.letsencrypt.org/acme/authz/P_d-15...
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:unauthorized",
        "detail": "Invalid response from http://x.example.com/.well-known/acme-challenge/Klx...",
        "status": 403
      },

2019-01-29 08:57:52,104:DEBUG:certbot.reporter:Reporting to user: The following errors were reported by the server:

Domain: x.example.com
Type:   unauthorized
Detail: Invalid response from http://x.example.com/.well-known/acme-challenge/Klxwu5746D... 404 Not Found

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
[/etc/nginx/sites-enabled/use_https.conf]
server {
  listen 1.2.3.4:80;

  location / {
    error_page 404 /use_https.html;
    return 404;
  }
  location = /use_https.html {
    charset UTF-8;
    root /var/www/html;
  }
}

**Comment by Nefsen402** [comment]
Hi, I ran into a similar issue except for ivp6. My VPS has multiple public ipv6 address assigned, but I only want to bind to certain addresses. When certbot would try to renew, it would try to bind to all ip addresses but of course can't bind because one of them has already been bound like the problem described above. I noticed that my nginx configuration file was being mutated such that all assigned `server`s are given a special ACME challenge. In addition to this 

I was able to gather that renew script was creating a `le_http_01_cert_challenge.conf` file that would be imported by the nginx configuration. This file would contain a bunch of extra server definitions binding to all IP addresses and of course clashing with my existing servers. After reading the source code of the `certbot-nginx` python script, it seems that the renew script will only generate this file if it can't find any `http_vhosts`. I suppose because of the special IP binds the renew script got confused and refused to acknowledge these existing vhosts. It seems though that there was some sort of escape hatch in the code where if it can't find said `http_vhosts` it will just fill it with whatever server was marked with `default_server`.

Adding the `default_server` to my http traffic server designation worked around the issue.
