### ISSUE TITLE
Once Ubuntu 19.04 comes out, update test farm tests

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6720]
We should probably be regularly testing against Ubuntu 19.04 when it comes out.

In April, Ubuntu 14.04 will be end-of-lifed so we can remove our AMIs for that release as well.

Erica and I had different opinions about whether we should keep the Ubuntu 18.10 tests when tests for 19.04 are added at https://github.com/certbot/certbot/pull/6700#pullrequestreview-197820088.

**Comment by ohemorange** [comment]
Either way we should for sure add 19.04 when it comes out, thanks for making this issue to track that.

As for 18.10, I said replace because I expect most of the 18.10 users to migrate to 19.04, since neither of them are LTS. Whether it's worth the extra time during releases to keep it or not depends on the number of users, which we can figure out when the time comes.
