### ISSUE TITLE
Certbot fails on windows with AttributeError: module 'os' has no attribute 'chown'

### ISSUE THREAD

**Issue by Camusensei** [certbot/certbot#6739]
PR #6480 breaks certbot on Windows: there is no os.chown on windows and running certbot certonly results in:

> AttributeError: module 'os' has no attribute 'chown'

See my comment on https://github.com/certbot/certbot/pull/6480/files#r254051247

**Comment by adferrand** [comment]
Hello @Camusensei, thank you for your report. I am currently handling the project to port Certbot on Windows.

Please note that support on Windows is still in its alpha state, while an active development is progressively pushing it to a stable state.

But at this point, we cannot garantee a correct execution of Certbot on Windows upon each release. 

However, I have the PR #6497, that takes care of this regression among over issues related to files security on Windows. It is under review, and should hopefully be available for the next release.

Until that, I would advise you to fallback to the previous release of Certbot.

In few releases, integration tests will be available for Windows, and will give to Certbot a far better testability and stability on this platform.

I will close the issue for now. Please feel free to ask for more information if the response I gave to you is not satisfactory.

**Comment by Camusensei** [comment]
Thanks for your prompt reply. I don't need to use an older version, simply commenting the line was fortunately enough for it to work. Thank you for your work on Windows support though!

**Comment by x1angli** [comment]
I encountered the same issue. Before adferrand's PR got checked in and pushed to PyPI, I have to fall back on Windows Subsystem for Linux  (WSL)......

Actually, Python did a lowsy job. I believe it's python's `os,chown` that should be changed. The `os` in Python is supposed to be a primitive and basic module, so everything in it should be OS-independent (like `os.walk` etc). Even if we may concede that sth OS-dependent should be in there, they should be put in a separate module such as `os.posix.chown` that we Pythoners can easily tell whether a func is os-dep or os-indie by just checking a module's name. Furthermore, for backward compatibility, the func should at least pretend to be implemented on Windows (I mean, even though this func may do nothing but just throwing an error on Windows, it should at least be **i-m-p-l-e-m-e-n-t-e-d**), rather than "has no attribute" on windows to begin with, which is like bluescreens on Windows. errh...

**Comment by ndurner** [comment]
Error message in 1.22:
`←[31mFailed to renew certificate ndu-t14s.namger.ovh with error: module 'os' has no attribute 'chown'←[0m`

As @Camusensei pointed out, this can be resolved by #-ting invocations of os.chown in filesystem.py
