### ISSUE TITLE
Stop using global state in cli.py

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6802]
See #6799 and in particular https://github.com/certbot/certbot/pull/6799#pullrequestreview-208968600.

**Comment by YtvwlD** [comment]
The linked pull request has been merged in March. Is this issue still relevant?

**Comment by bmw** [comment]
Yes this issue is still relevant. This issue was created out of the conversation in #6799.

In #6799, I fixed our failing tests by mocking out the problematic code, but it'd be better if this wasn't necessary. The functions causing problems are the two functions called by `certbot.cli.option_was_set`, both of which rely on mutating global state. It would be better if they did not do this and some ideas were proposed on how to refactor the code to accomplish there are in https://github.com/certbot/certbot/pull/6799#pullrequestreview-208968600.

**Comment by RConn12** [comment]
Hi my name is Robert. I'm a student at the University of Michigan. I'm working on a project where I am looking to submit a pull request in an established code base on github. Certbot seemed like a great candidate as I am somewhat familiar with the tool and would like to contribute to it's goal. I think this issue would be a good starting point for me and I would like to take it on if that's alright.

**Comment by bmw** [comment]
Hi Robert!

Taking this on sounds great. A couple caveats:

1. We're stretched pretty thin at the moment so we may not be able to quickly review any pull requests, but we/I would definitely like to see this resolved so we should get around to it at some point.
2. This will require a bit of refactoring/design. You may want to propose how you plan on resolving this here to get a +1 from someone on the Certbot team before you dive deep into implementing it.

**Comment by RConn12** [comment]
As far as being stretched thin goes that's totally okay if this pull request does not get reviewed quickly. I think it makes a lot of sense to propose a plan. I will definitely do that. Thank you for the reply!

**Comment by RConn12** [comment]
Hi, I have been exploring options for fixing this issue. In this post: https://github.com/certbot/certbot/pull/6799#pullrequestreview-208968600 there were a couple of proposed solutions. The second option was to generate an independent dict when argparse parsing is invoked and to pass this dict to functions that need to know if an option has been set explicitly. I think that this option makes realistic sense for me to implement as it's relatively straightforward in what it will require and how it will be done. 

- To implement this the function `prepare_and_parse_args` in `cli.py` would return an object with relevant information along with what it already returns
- `helpful_parser` will be included as a parameter in the function `certbot.cli.option_was_set`. `option_was_set` will pass this parameter to the two functions that it calls so that they do not rely on a global `helpful_parser`
- Tests will be modified according to this update in the code

One downside to this refactoring is that I am noticing a decent uses of the relevant `cli.py` functions throughout more of the code. This refactoring would end up affecting a decent amount of code. If I could get some thoughts that would be greatly appreciated. Thank you!

**Comment by bmw** [comment]
What does the new data returned by `prepare_and_parse_args` look like? For instance, what are their types? I'm just trying to get a little better idea on how you're structuring things here.

As for getting that information piped throughout Certbot's codebase, you'd need to do some plumbing but it may not be that bad. The config object created [here](https://github.com/certbot/certbot/blob/e048da1e389ede7a52bd518ab4ebf9a0b18bfafc/certbot/certbot/_internal/main.py#L1329) is passed throughout the majority of Certbot's code. You may have to pass that data through a few extra function calls, but that object is passed through all of the high level functions in Certbot's codebase.

Another piece of global state discussed in the comment you linked is [set_by_cli.detector](https://github.com/certbot/certbot/blob/e048da1e389ede7a52bd518ab4ebf9a0b18bfafc/certbot/certbot/_internal/cli.py#L215). It'd be nice to remove this as well as `helpful_parser`, but we can always do that later and waiting may be better to avoid a massive PR.

**Comment by adferrand** [comment]
Still relevant.
