### ISSUE TITLE
Support multiple A records in TLS-SNI mode

### ISSUE THREAD

**Issue by ionelmc** [certbot/certbot#6809]
So I have a really simple load balancing setup with 2 A records. It appears that certbot sometimes fails with `Failed authorization procedure. HOSTNAME (http-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from https://HOSTNAME/.well-known/acme-challenge/... [IP]: "<h1>Not Found</h1><p>The requested URL /.well-known/acme-challenge/... was not found`.

I was wondering if certbot could tell letsencrypt what ip to send the authorization request (it could grep out the ip out of ifconfig or something). Does the letsencrypt protocol even support something like this?

I was using the apache plugin on centos 7.

And yes, you could say that I should use the DNS challenges but I can't use that unfortunately.

**Comment by schoen** [comment]
Hi @ionelmc,

The ACME protocol that Let's Encrypt uses doesn't support this, basically because of a desire to keep the protocol simple and to avoid features that might allow an attacker to exercise more control over the validation process in order to obtain a fake certificate.

We have in the past found some pretty good solutions to address DNS round-robin load balancing setups, often using HTTP 301 redirects (which the Let's Encrypt validation is willing to follow). If you'd like to discuss how to do this—or other options for this setup—please bring up your question on the Let's Encrypt Community Forum, https://community.letsencrypt.org/. There are more people participating there and they will be happy to help with your question.

By the way, the validation method that you're using involving `/.well-known/acme-challenge` is HTTP-01 rather than TLS-SNI-01. (In TLS-SNI-01 there's no HTTP request and therefore no URL or path.)

Thanks! I hope you have good luck finding a solution.
