### ISSUE TITLE
Deprecate "ACMEv1" support

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6844]
Now that [ACME is an RFC](https://www.rfc-editor.org/info/rfc8555), we should deprecate "ACMEv1" support to push people towards using the standardized version of the protocol.

**Comment by bmw** [comment]
I think we can and should do this much faster than Let's Encrypt, but see https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for their deprecation plan for ACMEv1.

**Comment by ohemorange** [comment]
Hey, we should do this.

**Comment by bmw** [comment]
I agree. I think we just need to start raising deprecation warnings out of `acme` and printing a warning in Certbot when using ACMEv1.

I'm not exactly sure what the deprecation in `acme` should look like. For example, what class(es) do we want to deprecate in `acme.client`, do we want to us and others to use the name `acme.client.ClientV2` in the long term, and is there other code in `acme` that should be deprecated? I don't think any of that should be too bad though and I think even just deprecating the big chunks in `acme` would be a big win and step towards simplifying our code/tests.

**Comment by alexzorin** [comment]
I imagine for `acme.client.` we will want to deprecate both `Client` and `BackwardsCompatibleClientV2` in favor of `ClientV2` as they do not seem to serve a current or future need.

`BackwardsCompatibleClientV2` does just one one different thing compared to `ClientV2`, and that's [the terms of service callback](https://github.com/certbot/certbot/blob/667750f3fffc60cec74a387c292e9cdc12dc18af/acme/acme/client.py#L842-L855) in `new_account_and_tos`. This could be addressed by adding that callback kwarg to `ClientV2.new_account` in a backwards compatible way.

Does this sound good:

1. Next release, add PendingDeprecationWarning to those two classes + add a user-facing warning when an ACMEv1 directory is used (work for #8929).
2. In a following release, complete the deprecations and move Certbot to `acme.client.ClientV2`.
3. Much later, delete those classes and remove various ACME-v1 special cases found around `acme`.

I noticed [there are some active ACMEv1 endpoints from a real CA](https://community.buypass.com/t/63d4ay/buypass-go-ssl-endpoints-updated-14-05-2020). Because of this, would we want to stagger the move to `ClientV2` across one renewal period (?) worth of releases, so there is a chance for a user-facing warning to be printed and seen?

**Comment by ohemorange** [comment]
Hm, I'd rather not show warnings to certbot users of acmev2, which this plan would currently do. This can be fixed with the following slight change, addition bolded.

1. Next release, add PendingDeprecationWarning to those two classes + add a user-facing warning when an ACMEv1 directory is used, **probably by catching the `acme.client.Client` warning + catch and silence PendingDeprecationWarning in Certbot for `BackwardsCompatibleClientV2`, so that only users of `acme.client.Client` get shown a warning** (work for #8929) 
2. In a following release, complete the deprecations and move Certbot to `acme.client.ClientV2`.
3. Much later, delete those classes and remove various ACME-v1 special cases found around `acme`.

I do like this plan. though it does assume we'll keep the `ClientV2` name around forever. I don't have a strong opinion either way, but figured I'd make it explicit in case someone else does.

**Comment by ohemorange** [comment]
Oy, just realized, step 2 probably has to be a major release, because all of `acme` is in the api.

**Comment by bmw** [comment]
I personally haven't worried too much `PendingDeprecationWarning` vs `DeprecationWarning` for better or worse. Doing it may be a good idea and doesn't really hurt anything though.

Any reason for us not to change these warnings to `DeprecationWarning` after our next release? If so, I think we can move this to the next milestone.

**Comment by ohemorange** [comment]
You're correct, this should now be in the next milestone, or perhaps create a new issue (similar to #8929) and put that in the next milestone.
