### ISSUE TITLE
Represent revocation in storage.py

### ISSUE THREAD

**Issue by jdkasten** [certbot/certbot#688]
There has been lots of discussion about how to represent revocation within RenewableCerts but the code hasn't been written yet.

When this is completed the cert_manager will have to be updated to display the info appropriately.

**Comment by schoen** [comment]
Unfortunately I don't fully remember our latest consensus about the "covetousness" or "ambition" of lineages.

Do we want this status to be set proactively with OCSP  queries? I haven't found an OCSP client in Python that we can include and am still hoping we don't have to implement our own. Or is this status set only when the user actively uses the revoker?

And which of the following should we do?

* Deploy the latest unrevoked predecessor version of the cert from the lineage (if any) when we know or notice that a cert in a lineage is revoked (probably requires an OCSP client implementation in order to find out whether individual prior versions are unrevoked).
* Automatically attempt to renew the lineage with a new key when we know or notice that a cert in a lineage is revoked, if autorenewal is enabled.
* Both (presumably the autorenewal first, and the rollback only if that fails?).
* Neither.

**Comment by schoen** [comment]
OK, we're talking about putting it in the renewal config file in a separate section, like this:

```
[certstatusdata]
revoked_versions = 3 4 8 11
```

Then any part of the renewer or cert manager that found out that a version was revoked could mention that fact by adding to this list. We would probably want to try to have a comment at the beginning like

```
# Automatically generated; do not edit
[certstatusdata]
revoked_versions = 3 4 8 11
```

**Comment by schoen** [comment]
@jdkasten's view on the other part ("Deploy the latest unrevoked predecessor version of the cert from the lineage?") is that we should currently not automatically roll back to an earlier version. But we can try to autorenew following revocation, if we have autorenewal enabled.

**Comment by pde** [comment]
Revised plan: call out to a command line openssl OCSP command for every cert, load state that way.  If you aren't getting OCSP responses, error out and tell the admin.  For bonus points, do all the OCSP queries simultaneously and asychronously.

**Comment by jdkasten** [comment]
Currently fixed in https://github.com/letsencrypt/letsencrypt/tree/cert_manager

**Comment by bmw** [comment]
We originally added this to "1.0 for launch" because James had a working branch that just needed some tests. Since then, the client has changed around the cert manager and the branch needs some more work.

While it's certainly a nice feature, this is not a show stopper for launch so I'm kicking this out of the launch milestone. With that said, if James has the spare time to implement it before launch, we should merge it in.

**Comment by jdkasten** [comment]
Thanks @bmw for understanding. Hopefully things will be settling down for
me and I can get back on a normal schedule.

**Comment by bmw** [comment]
No problem at all! I know you're busy and have other responsibilities.

**Comment by bmw** [comment]
This has become less important as we currently do not allow users to use anything other than the latest version of their cert found in `archive`. We have #1028 for checking the OCSP response for the currently deployed certificate. After talking about this on the call, we decided to close this issue until such a feature is implemented.

Mentioning `deploy_before_expiry` so it can be easily found in a GitHub search.
