### ISSUE TITLE
Disable TLS session tickets in Nginx?

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6902]
Inspired by https://jhalderm.com/pub/papers/forward-secrecy-imc16.pdf, we might want to look into changing our nginx plugin's behavior around TLS session tickets. The [Mozilla site](https://mozilla.github.io/server-side-tls/ssl-config-generator/) where we get our TLS config from has TLS session tickets disabled, but this setting is not present in our config file at https://github.com/certbot/certbot/blob/master/certbot-nginx/certbot_nginx/options-ssl-nginx.conf.

This is likely due to the minimum version Nginx that supports these settings, however, I don't believe this has been investigated for a while. We should see what version these settings were added to Nginx and what versions are available in major distros.

Even if support is not available everywhere yet, it is probably worth adding these values conditionally as I suspect it will work on the vast majority of systems.

**Comment by sydneyli** [comment]
`ssl_session_tickets` is available in nginx 1.5.9.
Versions in oldest distros we support: Debian 8 (jessie):1.6.2; Centos 6 EPEL: 1.10.2; Ubuntu 16.04: 1.10.3
Ubuntu 14 (trusty) is listed on our site, but it's supposed to be EOL'ed by now?

Either way, this will work on most major distros, but we still do gate [OCSP stapling](https://github.com/certbot/certbot/blob/master/certbot-nginx/certbot_nginx/configurator.py#L832) for versions of nginx > 1.3.7 so we should probably do the same here.

Given the way `options-ssl-nginx.conf` is carefully version-controlled and managed, and that nginx will error if it encounters a directive it doesn't recognize, one way to do this might be to create more versions of the file that are included conditionally. If we do this for more config defaults in the future it might lead to file bloat, but I'd feel better doing it this way rather than arbitrarily changing a file in code that's so carefully version-controlled.

**Comment by bmw** [comment]
That plan sounds good to me! That's what we currently do in the Apache plugin. Let me or Joona know if you'd like a bit of a primer on how that works.

I think we can separately work on deprecating support for old versions of Nginx if that's what we want to do, but I think we should probably do than separately and more gracefully than suddenly causing your nginx config to break when your TLS settings are updated.
