### ISSUE TITLE
Make tools/venv.py prefer Python 3

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6937]
In the next year, Certbot should stop supporting Python 2 but if someone gets to this issue before then...

There were some concerns raised about `tools/venv.py` continuing to use Python 2 despite Python 2 approaching its deprecation date. To try and restate these concerns myself, they were:

* Python 3 is what Certbot will use in the future while Python 2 is going away so we should be running on Python 3 wherever possible to increase the chance of finding bugs.
* Most devs will already have Python 3 installed (however, devs on Debian based systems may not have the `python3-venv` package installed which is needed for our `tools/venv3.py` script)
* Tools such as `pip` are starting to print deprecation warnings on Python 2.7 in newer versions. Seeing warnings like this should not be a regular part of the development process in Certbot.
* People may notice that we're continuing to use Python 2 and not switch to Python 3 themselves which hurts the Python ecosystem.

Despite these concerns, I was hesitant to make this change because we tell devs to run `certbot-auto --os-packages-only` which automates installing Python 2 and not Python 3 (on most systems). This isn't entirely trivial as different systems use different names for the Python 3 package and I personally prefer this extra automation for devs over solving the problems above.

One idea I had to try and address all of these concerns is to rename `tools/venv.py` to `tools/venv2.py` and make `tools/venv.py` an automagical script that will use either Python 2 or Python 3 but prefers Python 3 and only falls back to Python 2 if Python 3 is not available. `tools/venv.py` should also check that the Python 3 `venv` module is available before agreeing to use Python 3.

Another benefit of a script like this is we can probably use it to solve test failures in https://github.com/certbot/certbot/blob/master/tests/letstest/scripts/test_sdists.sh which I believe are failing due to not trying to use Python 3.

**Comment by adferrand** [comment]
I quite disagree with the idea to do more magic in `venv.py`, or its associates, including detecting if python3-venv is installed in a Debian system, or toggle installation of Python 2 or Python 3 automatically based on crafted rules.

Indeed, `venv.py` is not `certbot-auto`. While it is understandable that `certbot-auto` takes an opiniated approach to ease at most the burden to setup a correct runtime for a lambda user, this is not the same thing for a developer. For the latter, a basic understanding is required to make contributions in Certbot, that can be covered by the documentation. If it is an advantage to have some boring operations be automated in a script, it is another thing to make operations on an implicit logic. If you setup a runtime to develop, having the knowledge for an explicit and repeatable process is the most desirable thing for the dev and after for the debugging.

Some propositions based on what I said:
* change `venv.py` to `venv2.py`, making explicit that this script is to setup on Python 2
* keep `venv3.py` on this name
* remove `venv2.py` when we do not want any dev on Python 2
* updating documentation towards these two scripts appropriately
* optionally detect that `venv` module is not available on Python 3 for `venv3.py`, and make a meaningful exception, developers will know what to do
* adjust pip version in these `venv*.py` to follow what pipstrap does for `certbot-auto`, not to take care of suppressing warnings that are at their right place because in fact, they are for developers
* use another approach than `venv*.py` in `test_sdists.py`, because it is for dev, not for user side tests (it could be for instance the venv setup by `certbot-auto`)

**Comment by adferrand** [comment]
For the renaming, yes, I agree `venv.py` is better. Python 3 will be here for a really, really long time. Just as a side note, then the remaining `venv2.py` becomes weird, making think that it could be an "improved" version of `venv.py`. We should rename it to something like `venv_py2.py`. 

For the venv error message, ok, Debian did the job. They did like nobody, but a least with the style ^^

For the warning messages in pip, ok, I agree that theses messages are annoying, we are aware of the situation. My point was to say three things :
* I may have understood from the recent PR about removing the deprecation warning for py27 in pip by sticking to an old pip, could have been partially justified to silence this warning. This cannot be a sane reason. The only sane reason here is to have the same runtime than what certbot-auto gives for users.
* The visual noise stay negligeable where it worth, in the CI pipeline thanks to the folded logs in Travis
* The contribution about helping the Python ecosystem will be better by assuming from our doc and communication that we are dropping progressively Python 2, than silently shifting developers runtime from Python 2 to Python 3

That said, as it is assumed, indeed I agree that these messages can be silenced here. 

Beside that, no more to say ^^

**Comment by bmw** [comment]
> For the renaming, yes, I agree venv.py is better. Python 3 will be here for a really, really long time. Just as a side note, then the remaining venv2.py becomes weird, making think that it could be an "improved" version of venv.py. We should rename it to something like venv_py2.py.

I was thinking we keep `venv2.py` and `venv3.py` until there is only one at which point we can just call it `venv.py`. That keeps a hint in the filename about which script uses which Python until there is only one option available.

**Comment by jsoref** [comment]
Fwiw, I'm 👍 on hiding the:
```
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
```

I'm trying to run `tox` locally (before making a PR) and the visual noise isn't helpful.

Specifically I've managed to get to:
```
________________________________________________________________________________ summary _________________________________________________________________________________
  modification: commands succeeded
ERROR:   py3: commands failed
  py27-cover: commands succeeded
  lint: commands succeeded
  mypy: commands succeeded
```
but it isn't easy for me to look through the output to find the py3 commands that `failed` ... the easiest thing I can find is the irrelevant (but non-white/gray) text from pip...

**Comment by bmw** [comment]
My opinion has changed a bit. I think we should update `venv.py` to `venv2.py`. We may also want to rename the resulting venv to `venv2`. These changes affects our test farm tests.

I don't have a strong preference anymore whether we also change `venv3` to `venv` in both the name of the Python script and the resulting virtual environment.

**Comment by bmw** [comment]
When making any changes here, we should search far and wide for any references to `venv` or `venv3` in any of the Certbot or certbot-docker repos.

**Comment by bmw** [comment]
I'm closing this in favor of https://github.com/certbot/certbot/issues/8387.
