### ISSUE TITLE
Fix certbot-ci on macOS

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6959]
When I run `certbot-ci` on macOS, I get the following test failures:

* certbot-ci/certbot_integration_tests/certbot_tests/test_main.py:64 test_renew_files_permissions
* certbot-ci/certbot_integration_tests/certbot_tests/test_main.py:88 test_renew_with_hook_scripts
* certbot-ci/certbot_integration_tests/certbot_tests/test_main.py:26 test_manual_http_auth

All failures are due to failing to perform the HTTP challenge. An error from Pebble looks like:
```
Domain: le.gw3.wtf
Type:   unauthorized
Detail: Non-200 status code from HTTP: http://le.gw3.wtf:5002/.well-known/acme-challenge/MURJ9f0w83vSKPg1UaFQ-ZP5JkLNUKo5JryiSCejh8s returned 502
```

When I run the same code on my Ubuntu VPS, tests pass, but it would be nice if I was able to run these tests locally as well.

As the one with the Macbook, this might be on me to debug, but if anyone has any ideas I'd appreciate it. My guess is something is different with the Docker network setup on macOS vs. Linux.

cc @adferrand

**Comment by adferrand** [comment]
Yes, there are several blocking differences, like with  Windows: https://docs.docker.com/docker-for-mac/networking/

In fact, I think that at some point, I will remove the Docker layer, at least with Traefik and Pebble, because it will simplify the runtime requirements, and these components are easily runnable directly on each platform, and that remove all problems about Docker networking. Boulder is another story.

However, I plan to do that once certbot-ci will be full running on Linux.

**Comment by adferrand** [comment]
Still relevant I would guess.

**Comment by alexzorin** [comment]
@bmw do you have any thoughts on enhancing Pebble's CI to generate macOS releases, so that I could `tox -e integration` locally without hackery involving renaming binaries? It seems to otherwise pass just fine.

I get that it's like, mega low priority, but I was thinking of doing it during some relaxing downtime and wanted to see whether you knew of any reason it's a bad idea 🙏 .

**Comment by bmw** [comment]
I do not know of any reason it's a bad idea. I'd certainly appreciate it if I could trivially run Pebble locally.
