### ISSUE TITLE
Handling the Let's Encrypt certificate chain switchover

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#6971]
Per https://letsencrypt.org/2019/04/15/transitioning-to-isrg-root.html and https://community.letsencrypt.org/t/how-to-request-identrust-intermediate-ca/91323/1, some of our users will want to continue serving the intermediate signed by the DST root instead of the ISRG root even if the CA starts recommending the ISRG-signed intermediate.

It would be good to have a straightforward and documented way to allow people to do that.

As an alternative, we could have a way to opt in to the new chain instead of a way to opt out.

Or we could try to have a good general way to handle choosing among potentially available certificate chains.

**Comment by tdelmas** [comment]
Could that feature be used to choose not only the intermediate but the root too? In the prevision of the ECDSA root.

**Comment by orangepizza** [comment]
> 
> 
> Could that feature be used to choose not only the intermediate but the root too? In the prevision of the ECDSA root.

I think only need to be able to select root, is it's only thing that matters. (DST root/ISRG-RSA/ISRG-ECDSA)

**Comment by tdelmas** [comment]
> I think we only need to be able to select root, it's only thing that really matters. (DST root/ISRG-RSA/ISRG-ECDSA)

I think it's not that clear if we think about cross-sign ISRG-RSA/ISRG-ECDSA: https://community.letsencrypt.org/t/ecdsa-root-and-intermediates/57978/19

**Comment by bmw** [comment]
Let's Encrypt delayed the transition to the ISRG root for a year: https://letsencrypt.org/2019/04/15/transitioning-to-isrg-root.html

I think we may want to revisit this depending on the state of the Android ecosystem then, but for now, I think this can be closed.

**Comment by alex7kom** [comment]
Since a year has passed, can this be re-evaluated?

**Comment by alexzorin** [comment]
I had been planning to work on this. https://github.com/letsencrypt/boulder/pull/4714 is merged and will hopefully eventually be deployed, so just need to think about how to expose it in Certbot. 

The idea I had so far was adding a flag like `--prefer-issuer <CN/SKI>`, which would fetch each fullchain offered by the ACME server (`rel="alternate"`), and if any of the fullchains chained to that certificate (not necessarily from the leaf), Certbot would choose that chain.

**Comment by bmw** [comment]
Thanks for thinking about this @alexzorin.

I think Let's Encrypt will only go forward with the chain switchover if they think the ecosystem is ready so we may not have to do much/anything here. With that said, if we think there will be much of a demand, we should do something. Something like what Alex proposed might be the best approach.

In the ideal world, I think it'd be good if the user didn't have to make this choice when the certificate was issued and the user could easily swap to other chains that were provided by the CA later. Realistically though, I think that would require quite a bit of work and it probably doesn't make sense, especially for an initial version, if we don't expect many people to use the feature.

Reopening this and moving it to our next milestone for now.

**Comment by alexzorin** [comment]
New date is September 29 (110 days from now): https://community.letsencrypt.org/t/transition-to-isrgs-root-delayed-until-sep-29/125516

**Comment by bmw** [comment]
Yeah I think we'll want to do this no later than our 1.8.0 release. Help here would be much appreciated.

Does anyone have thoughts about my idea of allowing users to select alternate chains after certificate issuance? Maybe it is overkill, but I worry there will be a significant amount of people reissuing certs just to use a different chain with Certbot.

**Comment by alexzorin** [comment]
>Does anyone have thoughts about my idea of allowing users to select alternate chains after certificate issuance?

I'm not seeing how it would work practically speaking. It can't be an installation-time choice because that would exclude `certonly` users. We don't want to create new commands (like `certbot switch-chain`). We DO want `fullchain.pem` to automatically point to the preferred chain, if it exists.

I am tentatively working on first adding alternate chain support to `acme.ClientV2.finalize_order`. At the moment I'm fighting with `requests` because its `Link` parsing doesn't support (otherwise conformant) duplicate relation types. It looks like we're going to have to do our own parsing there.

**Comment by bmw** [comment]
> We don't want to create new commands (like `certbot switch-chain`).

What's your concern with this? Something like that is exactly what I had in mind probably in addition to something like what you have now.

**Comment by tdelmas** [comment]
Will this work with ECDSA? https://community.letsencrypt.org/t/lets-encrypt-new-hierarchy-plans/125517

**Comment by alexzorin** [comment]
>Will this work with ECDSA? https://community.letsencrypt.org/t/lets-encrypt-new-hierarchy-plans/125517

The use of this feature would be to switch between Y3 and Y3-cross-sign. (And between Y1 and Y1-cross-sign *if* it existed, but the posted suggests that it's not planned). Switching between RSA and ECDSA hierarchies isn't possible without issuing an entirely new certificate.

>What's your concern with this? Something like that is exactly what I had in mind probably in addition to something like what you have now.

For me it's a question of whether the complexity is warranted. Improvement (try save some reissuances) vs cost (new top-level command, changes to the storage tier).

If we do add `certbot switch-chain`, what if we store the Order URL in a lineage file `orderr.json` instead of downloading a copy of each alternative fullchain at finalization time? Defers the requests until actually needed, and avoids N*M storage of each alternative chain.

**Comment by bmw** [comment]
> For me it's a question of whether the complexity is warranted. Improvement (try save some reissuances) vs cost (new top-level command, changes to the storage tier).

I can get behind that concern. Let's keep it simple for now and we can add that if a demand pops up.

> If we do add `certbot switch-chain`, what if we store the Order URL in a lineage file `orderr.json` instead of downloading a copy of each alternative fullchain at finalization time? 

Since you convinced me, we can probably kick this decision down the road but the first concern that comes to mind is the stability of order URLs both from Let's Encrypt and an arbitrary ACME CA. Does the spec guarantee anything about their lifetime?

**Comment by alexzorin** [comment]
>Does the spec guarantee anything about their lifetime?

Good point. The Let's Encrypt staging server demonstrates the problem succinctly. The certificate lifetime is 90 days, but the lifetime of a `valid` order is only 7 days. We'd need to download everything at issuance time.

>Let's keep it simple for now and we can add that if a demand pops up.

:+1:.

**Comment by bmw** [comment]
This was fixed in #8080.
