### ISSUE TITLE
Unable to determine zone identifier

### ISSUE THREAD

**Issue by sreyemnayr** [certbot/certbot#6972]
Just wanted to leave a note saying that using the dns-linode plugin, my zone identifier started with a capital letter, which caused the whole thing to choke with the "Unable to determine zone identifier" error message. When I went to linode console and changed the zone name to a lowercase letter, it worked correctly. Capitalizing the commands didn't make a difference. Had to do it from the linode dns manager side.

**Comment by ohemorange** [comment]
Thanks for the report!

**Comment by bmw** [comment]
I'm closing this in favor of https://github.com/certbot/certbot/issues/7631.

This issue is resolved by using a new version of our dependency `dns-lexicon`. #7631 is tracking updating the version of the library we have pinned so it will be updated everywhere we have control over our dependency versions like in our Docker images.

If you're having this issue using packages provided by your OS, I'd ask your distro maintainers to update the packaged version of `dns-lexicon`.
