### ISSUE TITLE
--preferred-challenges flag completely ignored

### ISSUE THREAD

**Issue by tomaskir** [certbot/certbot#6983]
### My operating system is (include version):
Ubuntu 18.04
certbot 0.31.0

### I ran this command and it produced this output:
`/usr/bin/certbot certonly -n --agree-tos -m [email] --no-eff-email -d [cert domain] --rsa-key-size 4096 --webroot -w [path to webroot] --preferred-challenges http`

``` - The following errors were reported by the server:

   Domain: [cert domain]
   Type:   tls
   Detail: Fetching
   https://[cert domain]/.well-known/acme-challenge/[challenge string]:
   remote error: tls: handshake failure
```
### Certbot's behavior differed from what I expected because:
The `--preferred-challenges http` flag was completely ignored, and HTTPS was used.

### Why is this important?
When automating (in our case using Puppet), or when trying to generate certs for domain currently using expired certificates, it's impossible to generate a cert without first removing the https configuration for this domain.

What is even worse, is that for security purposes, we have a blank "catch-all" HTTPS nginx "server" clause, that simply refuses the connection for HTTPS connections to our server IP using an un-defined HOST. We have to completely disable HTTPS on nginx, or the certbot connections fall through to the blank HTTPS server and cert retrieval fails.

**Comment by schoen** [comment]
Hi @tomaskir,

`--preferred-challenges http` is redundant with `--webroot`; the `--webroot` method supports only the HTTP-01 method, which is the same method that would be selected by `--preferred-challenges http`.

What you're seeing here is that Let's Encrypt tries to connect to your server via HTTP on port 80 to download the challenge file, but instead of receiving the file content, it receives an HTTP redirect (such as a 301 redirect) to the HTTPS version of your site. Let's Encrypt is willing to follow this redirect during validations

https://letsencrypt.org/docs/challenge-types/

but in this case the HTTPS URL to which your site redirected the request is also invalid, so the challenge fails.

To make this work, you should ensure that either (1) the HTTPS service is up and running during the challenge (which apparently would be difficult in your configuration), or (2) `/.well-known/acme-challenge` is excluded from the HTTP → HTTPS redirect rules, and instead simply serves file contents directly.

If you have any further questions or problems about this, please follow up on the Let's Encrypt Community Forum at https://community.letsencrypt.org/. Thanks!
