### ISSUE TITLE
(possible security problem) certbot apache plugin should not start apache if apache is not initially running

### ISSUE THREAD

**Issue by frodeborli** [certbot/certbot#6985]
Hi,

I am using certbot with the apache plugin. Some times, the apache plugin can't be used, and the fallback for me is then to stop apache, and use the standalone authenticator. This is fine: If `certbot --apache renew` fails; make an attempt with `certbot --standalone renew`

But, doing this - I noticed that Apache gets started between each certificate renewal (even when using '--standalone'. This implies two things:

1. That it causes apache to restartbetween each certificate renewal - which is inefficient; apache should be reloaded once all certificated are renewed. Apache can be slow to restart in many configurations.

2. That it starts apache, even if I have manually stopped it before running `certbot --standalone renew`.

**This last point is the biggest concern; if Apache has been stopped, for example due to some security issue - then certbot should not start it during it's scheduled cron renewal run.**

In good programming practice; you want 'no side effects' when you call a function. This principle should also apply to the certbot renewal script.

**Comment by adferrand** [comment]
Hello @frodeborli.

First, I would need to clarify a thing about the flags passed to certbot in the context of a renewal, because I think there is a misunderstanding here: passing `--apache` or `--standalone` to `renew` has no effect. Indeed, these flags are used for the creation of its certificate, to choose the plugin to use, not for the renewal.

Indeed for the renewal, Certbot will find the relevant renewal configuration (or all of them if you do not pass any `--cert-name` to `renew`), then use its content to make the renewal. And in this config, you have the plugin to use (the one that have been used to create the certificate). So basically for your situation, as the Apache plugin has been used to create the certificate, it will be reused for any `renew` call.

So calling `certbot --apache renew` then fallback to `certbot --standalone renew` is calling `certbot renew` two times if the fallback is triggered.

Now about the Apache restart during certificate renewal, since we established that the Apache plugin is always used. It can be expected that Apache is restarted unconditionally during a renewal, since it is required to have Apache up and running to fulfill the HTTP-01 challenge in this situation. Without that, Certbot cannot work correctly.

So about your security concern here: I think that if your Apache instance needs to be shutdown for any reason, then you need also to shutdown the cron job that renews the certificates.

**Comment by jsoref** [comment]
@adferrand : I don't think that's fair.
Let's say I have a mix of systems (which afaiu is still supported by certbot). Some certificates are renewed via DNS and some via Apache. The dns ones are used for some internal facing mail system. There's a security vulnerability in Apache (or an affiliated module) and I use `systemctl stop apache2` + `systemctl disable apache2`. I shouldn't have to go through each certificate renewal configuration and decide whether I want to disable it, and someone who is tasked with emergency security bits shouldn't have to figure that out either.

In this configuration, certbot is triggered via `certbot.timer` and `certbot.service`. Disabling both of them will break the mail server (eventually).

**Comment by frodeborli** [comment]
@adferrand The problem is not that Apache restarts. The problem is that Apache is started, when it was initially running.

So, for example in this scenario:

1. For some reason, you decide to stop apache. Perhaps you're being hacked, or perhaps some information has been published on your website.

2. There is a cron-job that triggers `certbot renew` to happen. This will cause Apache to start up - because that happens if you simply issue an `apache2 restart`. Certbot **should** check that apache is running, before it attempts to renew using the Apache plugin.

There definitely is a difference between `certbot --apache renew` and `certbot --standalone renew`. Yes, it uses the installer that has been configured, but it uses a different validator.

There is not difference between `certbot renew` and `certbot --apache renew`, but there certainly is a difference if you use `certbot --standalone renew`.

**Comment by adferrand** [comment]
So I will include other devs to the conversation because this is only my position here, and I may be wrong in some part of it.

To go back to the effect of passing `--standalone` or `--apache`, no definitively it cannot have any effect to the renewal process. Conceptually, it makes sense as the renewal process is supposed to renew each certificate in a consistent way each time, that it the exact runtime used to issue in the first place. And effectively:
1) You will find in a renewal configuration both the installer to use and the authenticator, like:
```
[renewalparams]
authenticator = apache
installer = apache
```
```
[renewalparams]
authenticator = standalone
installer = none
```
2) These parameters are reconstructed from the configuration in the live certificate configuration for each of it:
https://github.com/certbot/certbot/blob/6a970f74d0fe13c739a105e20dc8892c49b677b1/certbot/renewal.py#L416
3) That is latter consumed by the renewal process itself:
https://github.com/certbot/certbot/blob/6a970f74d0fe13c739a105e20dc8892c49b677b1/certbot/main.py#L1199
4) The documentation does not associate any authenticator/installer flag to the `renew` verb:
https://github.com/certbot/certbot/blob/6a970f74d0fe13c739a105e20dc8892c49b677b1/certbot/cli.py#L1423-L1425
```
renew:
  The 'renew' subcommand will attempt to renew all certificates (or more
  precisely, certificate lineages) you have previously obtained if they are
  close to expiry, and print a summary of the results. By default, 'renew'
  will reuse the options used to create obtain or most recently successfully
  renew each certificate lineage. You can try it with `--dry-run` first. For
  more fine-grained control, you can renew individual lineages with the
  `certonly` subcommand. Hooks are available to run commands before and
  after renewal; see https://certbot.eff.org/docs/using.html#renewal for
  more information on these.
```

**Comment by adferrand** [comment]
About the effect of the Apache plugin that start Apache when invoked now.

The basic purpose of Apache plugin is to orchestrate the Apache instance to honor the challenges, and install the certificates. So without a running instance, the plugin cannot fulfill its purpose.

I understand that this effect is not explicit through `certbot renew`, as it implicitly affect Apache if one of the renewal configuration state to use the Apache plugin, and so could be considered as a side effect. But the `renew` action is designed to be an automated action that does not require any manual action, and so proceed to any required action to renew all the certificates that needs to be renewed.

I do not know what could be done to make it more explicit, but removing the start/restart on renew action would have the effect to make certificates not been renewed on time. This would happen more often than an Apache accidentally restarted after a breach detected.

In my opinion, this corresponds to exceptional actions for an exception situation, but not the general case. As an admin sys, if I need to shutdown Apache for these situations, I would shutdown also every associated services, including the cron job on certbot as I would know that it is connected to Apache.

**Comment by adferrand** [comment]
@joohoi @bmw, what do you think on that matter?

**Comment by frodeborli** [comment]
@adferrand 

**Regarding `certbot --standalone renew`, I just double checked it.**

This is the output:

    Plugins selected: **Authenticator standalone**, Installer apache
    Renewing an existing certificate
    Performing the following challenges:
    ....

When using `certbot renew` this is the output:

    Plugins selected: **Authenticator apache**, Installer apache
    Renewing an existing certificate
    Performing the following challenges:
    ....

**Regarding the potential security issue:**

Since the website is down, because Apache is stopped - then certbot should say something like:

    `apache2 is not running. Can't renew using apache authenticator. Moving on...` and move on to the next domain.

Normally, there is no need to renew certificates if apache is down. This situation will only become a problem if Apache remains down for 30 days (renewal window I think?), but having 30 days of downtime is unique anyway.

**Comment by jsoref** [comment]
I think 30 days of downtime is pretty rare.

But even if it isn't rare, it's definitely intentional.

For a while we would have downtime like that for one domain (it's a domain we only use for about one week every quarter, and the rest of the time, my preference was to not have the domain point to our servers, but I've of late reconsidered and will probably just leave it around).

**Comment by adferrand** [comment]
> @adferrand
> 
> **Regarding `certbot --standalone renew`, I just double checked it.**
> 
> This is the output:
> 
> ```
> Plugins selected: Authenticator standalone, Installer apache
> Renewing an existing certificate
> Performing the following challenges:
> ....
> ```
> 
> When using `certbot renew` this is the output:
> 
> ```
> Plugins selected: Authenticator apache, Installer apache
> Renewing an existing certificate
> Performing the following challenges:
> ....
> ```

Acknowledged. I am really surprised by this behavior, as it is not documented and not commented in the code. I do not see any test also that checks the precedence of a config parameter stored in the renewal configuration file versus the corresponding CLI argument. I will definitively ask to know if it is an expected behavior.

This behavior may be defined by:
https://github.com/certbot/certbot/blob/6a970f74d0fe13c739a105e20dc8892c49b677b1/certbot/renewal.py#L148-L160

> **Regarding the potential security issue:**
> 
> Since the website is down, because Apache is stopped - then certbot should say something like:
> 
> ```
> `apache2 is not running. Can't renew using apache authenticator. Moving on...` and move on to the next domain.
> ```
> 
> Normally, there is no need to renew certificates if apache is down. This situation will only become a problem if Apache remains down for 30 days (renewal window I think?), but having 30 days of downtime is unique anyway.

I understand the use case. But the impact of not trying to start the Apache instance is potentially huge, for users that relies on the current behavior, and also for the internal logic of the Apache plugin. I do not think that for this situation, where a manual action (like disabling the cron) is a valid solution, we can change the behavior of Certbot.

That said, if passing `--standalone` has really an impact on the renewal process, indeed it is very suspicious that apache plugin is trigger to restart apache: either as an authenticator it should not be invoked as the standalone has been selected, either as an installer it should not do anything if there is not actual renewal done, so no certificate to be reinstalled.

**Comment by bmw** [comment]
I hope I can clear some things up here.

### CLI flags with certbot renew

I agree this could be better documented but the way this works is if you run `certbot renew` with no flags (and no [global configuration file](https://certbot.eff.org/docs/using.html#configuration-file)), the relevant configuration options that were last used to obtain each certificate will be used. For instance, if you last used the standalone plugin to obtain a certificate in a lineage and that certificate is due for renewal, the standalone plugin will be used to obtain to the new certificate. If you later use the Apache plugin to obtain a certificate for that same lineage, its usage will be remembered and used for subsequent renewals.

**When you provide flags to `certbot renew`, they override any settings from the previous renewal.** If you provide `--apache` on the command line and a certificate is due for renewal, the Apache plugin will be used to obtain the certificate regardless of the plugin that was last used to obtain a certificate in that lineage. Not only that, but as described above, the Apache plugin will then be used by default for subsequent renewals of that certificate lineage.

This all only applies to certificates that are actually renewed though. If you run `certbot renew --apache` and no certificates are renewed, the `--apache` flag has no effect.

### Meaning of --apache and --standalone

The way these flags work is they set that plugin to be used everywhere that is applicable. Since standalone is an authenticator but not an installer, `--standalone` has the same effect as `-a standalone` or `--authenticator standalone`. Since the Apache plugin is both an authenticator and an installer, `--apache` has the same effect as `--authenticator apache --installer apache`. See https://certbot.eff.org/docs/using.html#getting-certificates-and-choosing-plugins for more info about this jargon.

### Restart after each renewal?

> 1. That it causes apache to restartbetween each certificate renewal - which is inefficient; apache should be reloaded once all certificated are renewed. Apache can be slow to restart in many configurations.

Sure, but I don't think we're going to change this behavior. We have Apache reload its config (which results in no downtime) after each certificate is updated because it allows us to test each change being made to the configuration so we and our users are able to better pinpoint when a problem occurred rather than making all changes at once and failing at the end for _some_ reason.

There are also significant implementation benefits for us with this approach. For a single run of `certbot renew`, multiple [installer plugins](https://certbot.eff.org/docs/contributing.html#installer) (or even the same plugin with different configurations) can be used so properly grouping them given Certbot's architecture isn't entirely trivial. Given that and the benefits above, I don't think we're going to make this change for a small performance improvement.

### Starting Apache when it's stopped

> 2. That it starts apache, even if I have manually stopped it before running `certbot --standalone renew`.

While I'm only one voice on this project, I think we could look into changing this behavior, but I don't think we will be doing so in the immediate future. In addition to Adrien's concerns about it being a breaking change in behavior, I don't think doing this is very easy given how Apache and its tooling works and the large variety of OSes supported by the plugin.

### What problem are you having?

With all of that said, @frodeborli, I have some questions.

1. You say that sometimes the Apache plugin can be used and sometimes it cannot. Why can't it be used sometimes? Is this something we could fix in Certbot?
2. While you may also want to see the title of the issue resolved, what is the problem that you personally are having? Is it that Apache gets started in between renewing multiple certificates causing subsequent renewals to fail?

**Comment by frodeborli** [comment]
@adferrand 

> That said, if passing --standalone has really an impact on the renewal process, indeed it is very suspicious that apache plugin is trigger to restart apache: either as an authenticator it should not be invoked as the standalone has been selected, either as an installer it should not do anything if there is not actual renewal done, so no certificate to be reinstalled.

The installer should install the certificate. But there is no need to start after the certificate has been installed. If apache is not running, it should not get automatically started. The certificate should be installed though.

@bmw 

Regarding your questions: In my case - the authenticator tried to define a rewrite rule, so that the .well-known/ folder is served. RewriteRule does not always work/is not always respected, for example because other rewrite rules take precedence or perhaps RewriteEngine Off etc. On my server, creating an `Alias /.well-known/...` worked. Perhaps the Apache installer should use `Alias`, as well as `RewriteRule` - since it seems there is no problem in having both simultaneously anyway.

The final solution was to make sure the authenticator places files in the webroot instead of /usr/share/...

The fallback authenticator is using the apache installer. The apache installer causes apache to start, even though it is not running - so once a website has been updated, if other websites need updating during that update job - you will get an "unable to open port 80" error for the next website to be updated.

**Comment by frodeborli** [comment]
I fully understand that this is a change to certbot that warrants a proper discussion. Unfortunately - I am overworked enough and don't have any more time to spend on this debate - so I decided to fix the issue for myself and let you guys handle the politics of certbot  :)

I know that if I shut down a server, I want it to stay down until I tell it to start up. :) 

My recommendation for future users of certbot is really **don't use `--nginx` or `--apache` authenticators with certbot**. These authenticators work in a particular way - and due to them having a lot of users already - these things aren't easily fixed, because others may rely on these things.

You'll probably be much better off creating a path such as /var/local/well-known/, then making sure your web server will serve those files whenever a request begins with '/.well-known/'. **Next, use certbot with the `--webroot` authenticator.**

**Comment by bmw** [comment]
@frodeborli, thanks for the response! I was writing a comment proposing that you use the webroot plugin in the meantime but it looks like you beat me to that conclusion.

We're not aware of any authentication problems with our Apache plugin due to the user's rewrite config like you described. If you have the time, it'd be great if you opened a new issue describing your config that causes the plugin to fail so we can try to fix it, but again, I'm glad you found a solution that works for you and sorry for the trouble!

**Comment by frodeborli** [comment]
@bmw I really don't know why the `RewriteRule` didn't work in my setup. It was hard enough to figure ut that you were in fact using `RewriteRule` since certbot cleans up everything after it fails. :)

This is what I remember:

To prevent access to folders such as .git I had the following global configuration:

    <Directory  ~ "\/\.">
      Order allow,deny
      Deny from all
    </Directory>

which became

    <Location ~ "\/(?!\.well-known.*)\..*">
      Order allow,deny
      Deny from all
    </Location>

I added the following as well, because somehow the RewriteRule certbot inserts did not work:

    Alias /.well-known/acme-challenge /var/lib/letsencrypt/http_challenges/
    <Directory /var/lib/letsencrypt/http_challenges/>
      Satisfy any
    </Directory>
    # To prevent site specific rewrite rules from tampering/interfering with the certbot rewrite rule, I added:
    RewriteEngine on
    RewriteCond %{REQUEST_URI} /\.well\-known/acme\-challenge/
    RewriteRule (.*) /.well-known/acme-challenge/$1 [L,QSA]

**Comment by bmw** [comment]
Unfortunately I wasn't able to reproduce the issue. If you're willing to open a new issue and completely fill out the issue template, we may be able to debug the problem.

**Comment by mowny** [comment]
Why would it be a problem if apache would not be implicitly started if it's not running already? The reload is only necessary for apache to use the new certificates, and they would be loaded on the next startup anyway.
By the way, the implicit reload apparently does NOT happen for nginx, because I was just now running into the problem that nginx still had the old cert in use that expired today, and which has been renewed on April 20th. So now I'll have to look into how to use renewal-hooks/post/ and put a nginx -s reload somewhere ...
This means the behaviour is inconsistent anyway.

@bmw one reason where it would fail is a forced http->https redirect, at least that's why I use standalone.
@frodeborli and that's why I use http01_port with standalone so it does not conflict with the ports nginx has open.

**Comment by bmw** [comment]
> Why would it be a problem if apache would not be implicitly started if it's not running already? The reload is only necessary for apache to use the new certificates, and they would be loaded on the next startup anyway.

Automated deployments that are relying (knowingly or not) on Certbot starting Apache/Nginx.

> By the way, the implicit reload apparently does NOT happen for nginx

The nginx plugin should start nginx when the plugin is being used. I would encourage you to post at https://community.letsencrypt.org where there is a large community of people familiar with the project who will be able to make suggestions for your setup.

> @bmw one reason where it would fail is a forced http->https redirect, at least that's why I use standalone.

This should work as long as the redirect does not happen by another service before the traffic reaches Apache/nginx. The Apache plugin also handles the case of the external redirect, but unfortunately, the nginx plugin does not.

If you think you've found a problem with this using an up-to-date version of Certbot, if you open a new issue describing the problem, we'd be happy to take a look.

**Comment by JialuZhang** [comment]
For Apache configuration,
```
RewriteEngine Off
```
the line "RewriteEngine Off“ is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine Off" is introduced by Apache to explicitly disable all "RewriteRule" and "RewriteCond".
That is to say, if you include multiple "RewriteRule" and "RewriteCond" parameters in your configuration, then instead of commenting them all, you can explicitly set “RewriteEngine Off” to disable all "RewriteRule".
More importantly, the default value of “RewriteEngine" is already an "off", so adding “RewriteEngine off" is quite unnecessary and it may cause confusion to users.
Since herein there is no "RewriteRule" in this directory, deleting “RewriteEngine Off” would be ideal.
Related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```
