### ISSUE TITLE
Staging DNS update faster than production ones

### ISSUE THREAD

**Issue by jourji** [certbot/certbot#6999]
I felt like leaving a few words on my experience. Maybe not so uncommon.
Anyway, as I'm moving like 20 domains by hand, it's quite tedious.

## I ran this command on new server and it produced this output:
`certbot certonly --staging=true --domains=$DOM`
`==> OK`
`certbot certonly --domains=$DOM  --force-renewal --break-my-certs`
`"detail": "Invalid response from https://$DOM/.well-known/acme-challenge/xxx **[OLD_IP_ADDRESS]**`

## Certbot's behavior differed from what I expected because:
Once the staging setup recognizes my new IP address, the production one still doesn't.
I can't tell how long to wait for the cache to expire. If I try too often, I run into quotas exceeded.

Sharing the same DNS cache would help here. 
Maybe you could consider not using any cache since most production requests should be only every 2 months. 
Maybe an option for full dns resolution on demand, though it could be over used.

Nota: Preparing for the change, I removed any secondary NS some days ago, so only up-to-date data could be obtained form the DNS, if ever asked for it.

**Comment by schoen** [comment]
@cpu, can you think of a reason that could account for this discrepancy?

@jourji, Let's Encrypt infrastructure *already* doesn't use any cache and already queries authoritative name servers directly, so there shouldn't be a propagation delay here. So I don't know how to explain the difference in behavior here.

**Comment by schoen** [comment]
@jourji in any case, this is a server-side issue rather than a client-side (Certbot) issue, so I'm going to close the issue here because this particular issue tracker is only meant for tracking Certbot issues.

I hope @cpu will be willing to respond here, but you can also take up the discussion over on https://community.letsencrypt.org/, where both server-side and client-side issues are in scope.

One potential explanation (since you didn't give your full Certbot output here) is that your staging method didn't attempt any renewals at all (only `--dry-run` will force a renewal without `--force-renew`). In that case Certbot might exit with success and indicate that the renewal wasn't attempted at all.

**Comment by cpu** [comment]
@schoen It's impossible to say with much certainty without the domain name in question. I would guess that the authoritative DNS is incorrect but the staging server has a cached valid authorization that masks the error while production does not and so fails. 

@jourji I would recommend you try testing your configuration in staging using a brand new ACME account. If that doesn't fail then I can investigate further if you share the domain name you're testing with.

> Maybe you could consider not using any cache since most production requests should be only every 2 months.

Both staging and production's recursive DNS servers have a max TTL of 60s. If your authoritative DNS sets a larger TTL it will be ignored. If you don't want any caching to be done, set your DNS records with a TTL of 0. This is under your own control and we don't maintain any persistent caching.
