### ISSUE TITLE
certbot-auto writes check_permissions.py file in root folder

### ISSUE THREAD

**Issue by artgud** [certbot/certbot#7031]
We are using the latest certbot-auto script from by using the following command:

`wget https://dl.eff.org/certbot-auto ; chmod 0700 ./certbot-auto`

Recent version (0.34.0) writes file `check_permissions.py` in the `/` (root) folder. 

My suspect is the following code part:

```
if [ "$PYVER" -ge "$MIN_PYVER" -a "$NO_PERMISSIONS_CHECK" != 1 ]; then
    # ---------------------------------------------------------------------------
    cat << "UNLIKELY_EOF" > "$TEMP_DIR/check_permissions.py"
```

Looks like TEMP_DIR is not set at this point and content is written to `/check_permissions.py`.

It looks a bit worrying, because TEMP dir sometimes is emptied with `rm -rf "$TEMP_DIR"` ...

Thanks.

**Comment by bmw** [comment]
Thanks for reporting this.

I don't think we have to worry about `rm -rf "$TEMP_DIR"` because the only place that code exists, `TEMP_DIR` is overwritten in the line before: https://github.com/certbot/certbot/blob/6a970f74d0fe13c739a105e20dc8892c49b677b1/certbot-auto#L1020-L1021
but regardless we shouldn't be writing things to filesystem root.
