### ISSUE TITLE
 DNS problem: NXDOMAIN looking up TXT

### ISSUE THREAD

**Issue by Naidu369** [certbot/certbot#7041]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (Amazon Linux 2 AMI (HVM)
![Untitled](https://user-images.githubusercontent.com/47345582/57280898-7679b000-70c7-11e9-9fc1-0a02d5613ee7.jpg)):

## Here is the relev
![Untitled1](https://user-images.githubusercontent.com/47345582/57281364-7a5a0200-70c8-11e9-8dca-95a1892ddff9.jpg)
ant nginx server block or Apache virtualhost for the domain I am configuring:

**Comment by adferrand** [comment]
Hello!

I suppose your question concerns the correct procedure to follow in order to issue a certificate and install it on Apache using a manual DNS challenge. 

Github issues are used for questions related to potential bugs and improvements that concerns Certbot development. For questions related to Certbot use, you should ask questions on the community forum, https://community.letsencrypt.org/, where you will find a large community of experienced Certbot users willing to help you.
