### ISSUE TITLE
certbot nginx is not redirecting

### ISSUE THREAD

**Issue by NTMS2017** [certbot/certbot#7136]
After updateing ubuntu my nginx  proxy_pass is not working. With below configuration it worked over a 8 months but after ubuntu update to 18.04.2 the  proxy_pass is not working. 

my certbot nginx version is:  nginx/1.15.10

Also I found there is 2 enteris in my etc/host has a 2 lines like
127.0.0.1	localhost 
127.0.1.1     my_site.com

1. How to configure or what should I make so, my proxy_pass work again?
2. should Iremove and install certbot nginx again?
3. where I can find certbot nginx with letencrypt installation documantation?
4. Is new certbot nginx instalation uses new stable of nginx (currently stable nginx is 1.16 somting)?

```
server {
    charset UTF-8;
    listen 80 ;
    listen [::]:80 ;
    
    server_name mysite.com; # managed by Certbot    
    
    if ($host = mysite.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
    return 404; # managed by Certbot
}

server {
    charset UTF-8;
    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    server_name mysite.com; # managed by Certbot

    ssl_certificate /***************/mysite.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /*****************/mysite.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    location / {
	# First attempt to serve request as file, then
	# as directory, then fall back to displaying a 404.
        try_files $uri $uri/ =404;
        proxy_pass http://127.0.0.1:1024/;
   }
}
```

**Comment by adferrand** [comment]
Hello @NTMS2017!

In fact Certbot is not shipping Nginx. It interfaces itself with the Nginx installed by your OS, and modify it to allow the generation and installation of SSL certificates provided by an ACME server like Let'sEncrypt.

So the failure you are observing about `proxy_pass` is not due to Certbot, but because your Nginx version has been upgraded by your OS when moving to Ubuntu 18.04.2, and for some reasons, this version is not supporting your current `proxy_pass` configuration.

So I would advice you to check your Nginx log files (typically in `var/log/nginx`) and check what is saying about your current configuration vs what is explained in the relevant part of the official Nginx documentation (http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass).

I will close now the issue, since it is not directly related to Certbot. Feel free to open a new issue if you see a specific failure of Certbot on Nginx.
