### ISSUE TITLE
Add a ca-bundle command line flag

### ISSUE THREAD

**Issue by dopey** [certbot/certbot#7170]
https://community.letsencrypt.org/t/changing-the-ca-bundle-with-custom-server/96251/3

It is possible to change the server path (using the `--server` flag) but there is no flag to change the ca-bundle used to do tls server auth.

There is an environment variable (`REQUESTS_CA_BUNDLE`) that works, but it is not mentioned in the documentation. 

It would be great to add a command line flag, such as `--ca-bundle` (along with documentation). In addition, it would be nice to add documentation about the environment variable.

**Comment by jsha** [comment]
I'm in favor of documenting the existing environment variable rather than adding a flag. I think we already have a pretty good method of doing what's needed (REQUESTS_CA_BUNDLE) and would rather not add a second way.

Thanks for filing the issue, @dopey!

**Comment by mmalone** [comment]
Documentation would be great, but I'm running into some trouble with the existing mechanism when it comes to renewals. Since the bundle config comes from the environment, it's not used when `certbot renew` is run. You can set this up yourself by modifying the `cron` job and adding the environment variable there manually, of course, but things get complicated if you have certificates from different CAs installed on one machine. It seems like it'd be better to pass this as a flag and store it in the domain-specific config so it's available during renewal.

For some context, I'm working with @dopey on [a certificate authority](https://github.com/smallstep/certificates) for internal PKI. We're adding ACME support, and would like to be interoperable with `certbot`. The use case we're focused on is internal service-to-service communication using mTLS, so you'll likely *not* want to install your root certificate in your system trust store in that context (instead you'd likely want to configure internal services explicitly to trust *only* your internal CA, and leave only public root CAs in your default system trust store).

If you have any other suggestions that'd be super helpful. Thanks!

**Comment by jsha** [comment]
That's rad about the internal CA you're working on!

You make a good point about having to manually edit your cron job to add the REQUESTS_CA_BUNDLE - and actually you probably have to edit the systemd timer depending on what system you're on.

To make sure I understand correctly: You don't need a per-issuance CA config, right? In other words, you don't have ACME CA 1, with a server certificate signed by Issuer A, and ACME CA 2, with a server certificate signed by Issuer B?

**Comment by mmalone** [comment]
>  you probably have to edit the systemd timer depending on what system you're on.

Oof. I know nothing about systemd timers. Do you know off the top of your head which systems use those vs. cron?

> You don't need a per-issuance CA config, right?

I mean, probably not. I think it'd be a pretty niche use case to have two, independent, non-federated internal CAs. The use case I was thinking of is a system that is getting a certificate from Let's Encrypt _and_ from an internal CA and uses `certbot` for both (e.g., an nginx ingress proxy that uses a Web PKI cert to talk to the public internet and an internal client certificate to talk to upstreams). To make that work currently I think you'd need to have two separate `certbot` config directories and two separate cron jobs (or systemd timers) that run with different `--config`s (or `--config-dir`s?) since `certbot renew` will renew all certs in the config dir and the `REQUESTS_CA_BUNDLE` will apply to all renewals.

I'm actually running into one more issue getting this all wired together: `certbot` is tuned for Let's Encrypt's 90 day certs: it schedules renewals for a fixed 60 days after issuance and creates a `cron` entry to run every 12 hours. Our CA issues shorter-lived certificates with 24 hour lifetimes by default. My guess is changing the default 12 hour cron timing is infeasible (ideally we need it to be short enough that multiple renewals are attempted before expiry in case of CA downtime). However, even after adjusting the cron entry, accommodating shorter lifetimes requires a manual edit of a per-domain renewal configuration to add something like `renew_before_expiry = 8 hours`. It seems like this could instead be captured as a command-line flag during certificate issuance and stored in that config file automatically, which would save a bit of hassle. I understand that this may be too niche a use case, but figured I'd mention it.

For comparison, the `acme.sh` client supports a `--ca-bundle` flag and lets you adjust the renewal interval by passing a `--days` flag during issuance. It's still a bit busted, however, since it appears to persist the CA bundle globally and since _days_ isn't granular enough for our purposes. So close!

We're going to announce our ACME support soon and in the announcement we're going to document our support for popular ACME clients. If you're interested, [here's what I have written about `certbot` currently](https://gist.github.com/mmalone/b595a86722319559f66afff8ab0408d9). Feedback very welcome!

**Comment by jsha** [comment]
> Oof. I know nothing about systemd timers. Do you know off the top of your head which systems use those vs. cron?

If you're using certbot packages that were installed via OS packaging, they will use systemd timers on OS' that use systemd, and cron elsewhere. I happen to know that Ubuntu and Debian are on systemd, and therefore the certbot packages automatically set up a systemd timer. If you look at the auto-installed cronjob, you'll see that it's prefaced with a test to see if the systemd timer exists, and won't run if so.

> The use case I was thinking of is a system that is getting a certificate from Let's Encrypt and from an internal CA and uses certbot for both (e.g., an nginx ingress proxy that uses a Web PKI cert to talk to the public internet and an internal client certificate to talk to upstreams). To make that work currently I think you'd need to have two separate certbot config directories and two separate cron jobs (or systemd timers) that run with different --configs (or --config-dirs?) since certbot renew will renew all certs in the config dir and the REQUESTS_CA_BUNDLE will apply to all renewals.

For this use case, I'd recommend making a single certificate bundle that contains both the system ca-certificates package and the internal CA root, and have `certbot` use that bundle. True, it's not quite as strict as separate bundles for each type of issuance, but it's simpler and IMO safe enough.

> I'm actually running into one more issue getting this all wired together: certbot is tuned for Let's Encrypt's 90 day certs: it schedules renewals for a fixed 60 days after issuance and creates a cron entry to run every 12 hours.

This is great feedback, thanks! Could you file a separate ticket for this one? I want to make sure we stay on topic in this issue.

**Comment by mmalone** [comment]
> I happen to know that Ubuntu and Debian are on systemd ... if the systemd timer exists, [the certbot cronjob] won't run if so.

Ha, I noticed that check while testing on Ubuntu 18.04, got confused, and removed it. I also can't find anything in `/etc/systemd` that references `certbot`... so I _might_ have found another issue. Looks like renewals might be broken for Ubuntu 18.04. It's been a while since I installed, but pretty sure I just ran through the instructions on certbot.eff.org. If I have an opportunity to repro I'll report back.

> I'd recommend making a single certificate bundle that contains both the system ca-certificates package and the internal CA root

Alright, good thinking, you got me. This is a reasonably straightforward workaround. I'll leave my pony request outstanding though: it'd be nice to be able to configure the root trust bundle on a per-server basis without shenanigans. I understand if you wontfix :).

> Could you file a separate ticket for this one?

On it.

Thanks for your help!
