### ISSUE TITLE
Clarify that dns-cloudflare requires the global API key

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7280]
Since the Cloudflare plugin was written, Cloudflare has added support for API tokens with permissions a (slightly) smaller scope. For more information about this see https://github.com/certbot/certbot/issues/7252.

As pointed out in that thread at https://github.com/certbot/certbot/issues/7252#issuecomment-515739140, our Cloudflare plugin isn't very clear which kind of credentials it requires. While #7252 remains unresolved, we require the global API key so we should update the docs and CLI output to clarify this.

**Comment by BierDav** [comment]
I just wanted to point out that I was really confused until I found this issue. Because the docs say that it is possible to use an API Token like this:
![image](https://user-images.githubusercontent.com/46626041/147508824-2140c7f4-4f6a-44c1-a2a9-893f3e8f8d3e.png)
![image](https://user-images.githubusercontent.com/46626041/147508835-3a87bb4f-6c7f-43bf-aba4-2aeaefa3ff29.png)

Docs found on: https://certbot-dns-cloudflare.readthedocs.io/en/stable/

I'm pretty sure that the Docs are wrong, because I've tried it and got this error:
`Error determining zone_id: 6003 Invalid request headers. Please confirm that you have supplied valid Cloudflare API credentials. (Did you copy your entire API token/key? To use Cloudflare tokens, you'll need the python package cloudflare>=2.3.1. This certbot is running cloudflare 2.8.15)`

If I use the global key it works fine.

It would be kind if you fix that.

**Comment by storrgie** [comment]
@BierDav I think that this was confusing me as well, when you use the global token the variables for authentication look like:

```
dns_cloudflare_email=
dns_cloudflare_api_key=
```

But when you use a scoped token you have a different variable:

```
dns_cloudflare_api_token=
```

This was hard for me to find, I don't know if it was in the documentation clearly.

**Comment by BierDav** [comment]
Ahh thanks
