### ISSUE TITLE
Unpin dependencies pinned back for python3.4 support

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#7358]
As per https://github.com/certbot/certbot/pull/7337#issuecomment-524084164

**Comment by bmw** [comment]
While I hope to land https://github.com/certbot/certbot/pull/7268 for our next release, I think it'd be best to have at least one release of Certbot printing deprecation warnings on Python 3.4 during which we're still testing our support for Python 3.4 which means we won't be able to update our pinning in certbot-auto because that version is also used in our tests.

For that reason, I'm bumping this to the next milestone.

**Comment by bmw** [comment]
I pinned back more dependencies in #7558 that should also be unpinned when we do this.
