### ISSUE TITLE
Certbot `–reuse-key` flag does not preserve public key

### ISSUE THREAD

**Issue by sebashack** [certbot/certbot#7361]
According to the documentation, it is possible to tell certbot to reuse the same private key that already exists in the current certificate. Thus I have been running the following command to renew certificates:
```
certbot renew 
–rsa-key-size 4096 
–no-self-upgrade 
–dns-route53 
–noninteractive 
–reuse-key 
–post-hook ‘systemctl reload nginx.service’
```

Nevertheless, the cert.pem is modified after this operation – when diffing it with its version before renewal. I would expect it not to change at all since the private key is being reused.

I need to reuse the same public key in order to avoid pinning issues with IOS, is there a way to actually preserve it?

**Comment by schoen** [comment]
Hi @sebashack,

`cert.pem` or `privkey.pem`? The goal of `--reuse-key` is to avoid changing the content of `privkey.pem`, not of `cert.pem`. The certificate itself inherently has to change because it needs a new issuance and expiration date, new serial number, and new CA signature confirming that the CA still believes in the data in the certificate.

If you run `openssl x509 -in cert.pem -modulus -noout`, you should see that the public key itself hasn't changed. If this key value is referred to by a pinning process, that pin should still be valid for new versions of the associated certificate.

**Comment by adferrand** [comment]
Your mixing the public key concept of an asymmetric encryption protocol (like RSA), and the certificate in the X.509 protocol (like TLS).

I found a good link that is explaining the difference: https://docs.oracle.com/cd/E19509-01/820-3503/ggbgc/index.html

To sum up: a certificate uses a private key (and so a public key) as its encryption mechanism. But a certificate is more than that: it contains its validity period, and more importantly, the data it is signing, mainly the idea that the website you are browsing is owned by the holder of the private key.

The certificate changes at each Certbot renewal, at the very least for its validity period, and so its signature, even if the private key behind does not change. Here `--reuse-key` instruct Certbot to keep the same private key across renewals.

**Comment by sebashack** [comment]
Thanks everybody for your answers. I have run the commands suggested by @schoen and I get the expected results.

It's nice to know that certbot has good support for this feature.
