### ISSUE TITLE
h2o HTTP/2 webserver support

### ISSUE THREAD

**Issue by HLFH** [certbot/certbot#740]
Hi,

Please support the h2o HTTP/2 webserver:

https://github.com/h2o/h2o

Thanks in advance,

**Comment by kuba** [comment]
You should probably request that over at https://github.com/h2o/h2o/issues.
Let's Encrypt client supports plugin infrastructure, for more info see
https://letsencrypt.readthedocs.org/en/latest/plugins.html.

-- 
Yours virtually,
Jakub Warmuz

**Comment by kazuho** [comment]
As the author of H2O, I would definitely want to support Let's Encrypt.

That said, I would not want to let the letencrypt command line tool modify H2O's configuration file, since it may cause errors.  While I understand that it is inevitable to do so to support other web servers, I anticipate that there could be easier and more decoupled ways if the server could be modified.  For example...

@kuba under my understanding that the letsencrypt client maintains both the private key and the certificate chain, is there any way to obtain the paths of the key file and the certificate chain file via command line?  I run `letsencrypt --help all` but could not find any such command.

If such command option could be provided, I can provide support to letsencrypt just by adding a configuration directive to H2O to execute such command to read the paths returned.  Portion of configuration file loading the key pair for www.example.com would look like this:
```
ssl:
  certificate-file: "exec letsencrypt --print-certificate-chain-file www.example.com |"
  key-file: "exec letsencrypt --print-key-file www.example.com |"
```

Having such option would help other small servers run from command line as well.  For example, nghttpx (an HTTP2 reverse proxy, provided as part of [nghttp2](https://github.com/tatsuhiro-t/nghttp2)) could be launched by:
```
$ nghttpx --frontend=443 --backend=127.0.0.1:8080 `letsencrypt --print-key-file www.example.com` `letsencrypt --print-certificate-chain-file www.example.com`
```

**Comment by kuba** [comment]
`--print-key-file` doesn't sound like a useful plugin-like integration. Users see the certificate path once its issued in `letsencrypt auth` command and they can just copy-paste it. Let's Encrypt plugins are a bit more complicated conceptually...

Authenticator plugins are meant to perform challenges, which requires interaction with the webserver configuration (in order to have no downtimes). This doesn't have to involve config file updates - you could provide API on the webserver side to update configuration "on the fly" (in memory), e.g. `h2octl add-new-letsencrypt-dvsni-challenge-host --key foo --cert bar ...` and then create a python plugin that exploits this API. Otherwise, people have to stop the webserver (at least for port 443), use `letsencrypt auth` and afterwards set the paths to the issued certificates manually,

Installer plugins (`letsencrypt install`) are passed certificate paths and it's up to them to decide how to interact with the webserver. You could for example put certificates and keys into predefined directory structure, say `/etc/h20/letsencrypt/$domain/{key,cert}.pem`, and code the server, so that it defaults to reading those files if no key/cert for SSL was provided. This wouldn't require any interaction with the config files.

As you can see, there are other ways than changing the configuration files directly. Use your imagination! :)

**Comment by kazuho** [comment]
@kuba Thank you for the response.

> Let's Encrypt plugins are a bit more complicated conceptually...

Yeah! I agree that there could be other ways than updating the configuration file when implementing a plugin.  I also understand that unless you write a plugin it would be impossible to perform domain validation without stopping a server.

OTOH, the downside of the plugin architecture is that such plugin should be developed for every server (should it be H2O or nghttp2 or a SMTP server or whatever).  If a command line interface exists that returns the paths of the keys and certificate files, then server administrators can use that command line interface to setup servers that do not have the plugins.

There are a large number of programs that implement TLS protocol, and IMO providing a command line interface to obtain the paths would help them work together with Let's Encrypt.

**Comment by kazuho** [comment]
The other advantage of providing command line interface to obtain keys and certificate files is that it could be used for automatically distributing the pair to a cluster of HTTP servers.

In case of running a HTTP server cluster, once DV is complete, you would want to run the letsencrypt client on a single machine (to occasionally renew the certificate), and distribute the key and certificate file to the HTTP servers.

Without having a command line interface to obtain certificate files, it is impossible to setup such distribution unless you have the guts to write a plugin specific to your data-center needs.

But with a command line interface to obtain the files, it would become easy for administrators to write simple scripts to do the job.

**Comment by dch** [comment]
a big +1 for supporting composability

**Comment by evrial** [comment]
IIRC letsencrypt planned standalone version (minimal script, just validate list of domains from dvsni and obtain cert file signed by letsencrypt with intermediate CA). Is it still in roadmap? I'd be happy with that and h2o could use that without crap overhead.

**Comment by kuba** [comment]
Standalone plugin has been in `master` for a long time now (`letsencrypt -a standalone auth`); likewise manual (`letsencrypt -a manual auth`).
