### ISSUE TITLE
dns_rfc2136_base_domain is not used?

### ISSUE THREAD

**Issue by sanigo** [certbot/certbot#7445]
dns_rfc2136_base_domain is not used by certbot dns-rfc2136 plugin anymore?

## My operating system is (include version):
CentOS 7.5

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
I use --dns-rfc2136-credentials with a config file which include dns_rfc2136_base_domain.

## Certbot's behavior differed from what I expected because:
My purpose is to use CNAME to redirect the _acme-challenge to a subdomain. I do not want my main domain to accept DDNS updates.
But the dns_rfc2136_base_domain is not used, so the dns update was REFUSED by the main domain.

**Comment by alexzorin** [comment]
Just looking at the issue history, it looks like the change that introduced `base_domain` (https://github.com/certbot/certbot/pull/7029) was reverted (https://github.com/certbot/certbot/pull/7142) [in 0.35.1](https://github.com/certbot/certbot/commit/23b52ca1c8798285698b2a051a36b3c98d70191b) due to breaking the plugin in other ways: 

> Support for specifying an authoritative base domain in our dns-rfc2136 plugin has been removed. This feature was added in our last release but had a bug which caused the plugin to fail so the feature has been removed until it can be added properly.

So far, it looks like nobody has tried re-adding it.

**Comment by adferrand** [comment]
I can add some context.

I merged the initial PR that has been reverted after due to an uncaught defect. I would have normally try to merge back the PR with the trivial fix, but then this PR https://github.com/certbot/certbot/pull/7244 appeared.

It improves greatly the algorithm that finds the actual DNS zone behind the `_acme_challenge.*` FQDN, and should remove the need to set the base domain explicitly from the command line.

We should merge #7244 sooner than later in my opinion.

**Comment by sanigo** [comment]
I have tested the PR locally, it worked charmly

**Comment by vwbusguy** [comment]
This is still an issue.  The examples in other plugins of CNAME _acme-challenge.foo.com to _acme-challenge.acme.foo.com don't work currently with the rfc2136 plugin as it only recurses on the domain given via SOA query and doesn't appear to follow a CNAME if it exists, so the normal workaround for not wanting DDNS on a higher level isn't currently possible with this plugin.
