### ISSUE TITLE
Revert #7510

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7513]
Unfortunately we had to revert dropping Python 3.4 support due to a bug. We definitely want to do this so I think we should fix the bug and unrevert the code.

Below is my understanding of the problem, but I wasn't able to 100% verify this so whoever takes this issue should do so.

I believe this bug is hit when a certbot-auto user on a RHEL 6 based system upgrades certbot-auto to a version that no longer supports Python 3.4 and certbot-auto delays rebootstrapping either because `--non-interactive` wasn't provided on the command line, we cannot non-interactively rebootstrap on this OS, or certbot-auto is not connected to a terminal. After rebootstrapping is skipped the first time, on subsequent runs certbot-auto will crash with output like:

```
WARNING: couldn'\''t find Python 3.5+ to check for updates.
Traceback (most recent call last):
  File "<stdin>", line 16, in <module>
  File "/usr/lib64/python3.4/distutils/version.py", line 58, in __lt__
    c = self._cmp(other)
  File "/usr/lib64/python3.4/distutils/version.py", line 176, in _cmp
    if self.version != other.version:
AttributeError: '\''StrictVersion'\'' object has no attribute '\''version'\'''
```

I think what's happening is [here](https://github.com/certbot/certbot/blob/73cd5aa81c56a1dfc87f27dd9124dab525c1e9df/certbot-auto#L1891) if Python 2.7 or Python 3.5+ isn't installed, `REMOTE_VERSION` will not have been set a few lines above. [CompareVersions](https://github.com/certbot/certbot/blob/73cd5aa81c56a1dfc87f27dd9124dab525c1e9df/certbot-auto#L996) is passed an empty string as its third argument which causes the Python script there to crash which in turn causes all of certbot-auto to crash because that command exited with a non-zero status. This only happens when the [version number in certbot-auto](https://github.com/certbot/certbot/blob/v0.40.0/certbot-auto#L34) doesn't end in `.dev0` like it usually does, because `.dev0` in the version string causes `CompareVersions` to exit before getting to the problematic code.

If this is correct, I think the fix is just skipping calling `CompareVersions` when `REMOTE_VERSION` is unset for any reason.

**Comment by adferrand** [comment]
I confirm, this what is happening. And your fix would work. However I wanted to think of the outcome, that is why I was more in favor of a fallback to give us the time.

If we apply your correction, certbot-auto will assume everything is up to date until the user sees the logs in the non interactive session (typically a cron) and fixes the runtime requirements. Then `fetch.py` will be called again and eventually certbot-auto will update itself again.

I think it is not great, it means some certbot instances could stay stuck on a old version without a way to redeploy any necessary correction in future certbot releases. 

One simple fix would also to assume in this case that certbot-auto is always out of sync. It would update itself each time, even if a new version is not released, again until the local runtime is fixed. 

It is better in my opinion, but still not great, with unnecessary network trafic and work on the local venv. 

Here is my proposition. We test here against `MIN_PYVER` because "naively" it makes sense to use the minimal python version requirement to run certbot as the basis of all similar operations where a minimal version needs to be checked. 

However technically `fetch.py` does not need Python 2.7+ for Python 2 configs, and Python 3.5+ for Python 3 configs. It just requires Python 2.7+, and any version of Python 3 is fine even the deprecated ones. 

I propose to run `if [ "$PYVER" -lt 27 ];` instead of `if [ "$PYVER" -lt "$MIN_PYVER" ];` in the branch that skips executing `fetch.py`. This way most of the systems will still be able to check for new versions.

At this point, if `REMOTE_VERSION` is still not set, it means we are still on Python 2.6, the bootstrap has failed, and Certbot installation is broken: I think it is safe here to do the logic you propose, and keep the installation in its current state.

**Comment by bmw** [comment]
> If we apply your correction, certbot-auto will assume everything is up to date until the user sees the logs in the non interactive session (typically a cron) and fixes the runtime requirements. Then fetch.py will be called again and eventually certbot-auto will update itself again.
>
> I think it is not great, it means some certbot instances could stay stuck on a old version without a way to redeploy any necessary correction in future certbot releases.

This is true but we've had our current behavior of not upgrading certbot-auto if the version of Python installed doesn't support Certbot for nearly two years (see https://github.com/certbot/certbot/pull/5389). I'm a little hesitant to make any unnecessary changes to the design of certbot-auto right now.

If we did do that though, I think that code like `fetch.py` and `CompareVersions` would not actually be tested on older versions of Python risking problems if we have to change something in the future. I also worry that it confuses an already impossible script: `MIN_PYTHON_VERSION` applies unless you want to run script X, Y, or Z in which case there's a different minimum version.

While I do see the value in trying to keep certbot-auto as updated as possible, for these reasons I personally don't think the change is worth it and would prefer the script had behavior similar to what I described in my initial post.

**Comment by adferrand** [comment]
Indeed. I focused the design of the fix around the bug itself, but if it is a feature on its own to have no upgrade on ancient python versions, it is better to follow that.

Really, I do not want to be creative with certbot-auto :)

**Comment by sjaanus** [comment]
Is there a quick fix for users that have this error? certbot-auto renew failing with this exact error. I have python 3.4.5 and CentOS 6.  What commands should I run to get my cert updated?

**Comment by bmw** [comment]
Yes. You should be able to fix the problem by downloading a new version of `certbot-auto` from https://dl.eff.org/certbot-auto to replace your local one.

If you have any questions or problems about this, please follow up at https://community.letsencrypt.org/t/certbot-failing-to-find-python-version-on-centos-6-10/105634
