### ISSUE TITLE
Automatically clean up __pycache__ and .pyc files?

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7581]
Especially if you've had a Certbot repo locally for a long time, things can get pretty messy with `__pycache__` and `.pyc` files. They get left behind if components of the project move around and the directories containing them aren't deleted either.

Is there anything we can do to help automate this cleanup? I feel like I've seen other Python projects have a script for this purpose but when is it run? Do they just occasionally do it manually or is it triggered on something?

**Comment by alexzorin** [comment]
Nice-to-have: if `tools/venv[3].py` deleted all the existing `.pyc` before [re]creating the virtualenv.

For some time, I wasn't able to run coverage because of some inscrutable 'bad magic number'  error (though with enough frustration I eventually looked it up). Might be worth saving the next guy or gal.

**Comment by bmw** [comment]
What command were you using to run coverage? `tox`?

Another option might be to clean up those files there, maybe in addition to `venv*.py`.

**Comment by alexzorin** [comment]
Yep, `tox -e py3-cover`.
