### ISSUE TITLE
Ubuntu PPA hasn't been updated in ages, and now the client doesn't work since ACME v1 endpoint is disabled

### ISSUE THREAD

**Issue by vegarnilsen** [certbot/certbot#7601]
```bash
clsvegar@web02 $ sudo certbot certonly --agree-tos --webroot --webroot-path /var/www/html -d web02.example.com
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
An unexpected error occurred:
The client lacks sufficient authorization :: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.
Please see the logfiles in /var/log/letsencrypt for more details.
clsvegar@web02:~$ cat /etc/apt/sources.list.d/certbot-ubuntu-certbot-bionic.list 
deb http://ppa.launchpad.net/certbot/certbot/ubuntu bionic main
# deb-src http://ppa.launchpad.net/certbot/certbot/ubuntu bionic main
clsvegar@web02:~$ certbot --version
certbot 0.31.0
```

Following the official installation instructions on Ubuntu 18.04 leads to a non-working setup.

**Comment by alexzorin** [comment]
Hi @vegarnilsen,

Certbot has defaulted to the ACME v2 endpoint [since 0.26.0](https://github.com/certbot/certbot/blob/master/certbot/CHANGELOG.md#0260---2018-07-11). I've tested just now that a fresh install of Certbot on Ubuntu Bionic uses ACME v2.

It's possible that there is a configuration file (such as `/etc/letsencrypt/cli.ini`) that is telling Certbot to use the older endpoint.

Perhaps:

    grep -R acme-v01 /etc/letsencrypt

You can also try force it, if it helps:

    --server https://acme-v02.api.letsencrypt.org/directory

**Comment by vegarnilsen** [comment]
> It's possible that there is a configuration file (such as `/etc/letsencrypt/cli.ini`) that is telling Certbot to use the older endpoint.
> 

Thanks, this was the problem, updated the config file and now it works.
