### ISSUE TITLE
Change log handler

### ISSUE THREAD

**Issue by vliggio** [certbot/certbot#7644]
The current log handler, RotatingFileHandler, rotates logs every time the log changes. Specifically, the logs are named log/letsencrypt/letsencrypt.log, log/letsencrypt/letsencrypt.log.1, etc, and what’s annoying is that all the logs renumber every day (1 becomes 2, 2 becomes 3, etc). This means that if you do backups of your server (and you are doing backups, right?!), every day every single log is re-backed up, because each file is essentially new as the name has changed.

I know I can configure the number of logs (1000 as a default seems very high but that I can at least change).

TimedRotatingFileHandler would allow for naming by date instead.

**Comment by adferrand** [comment]
Hello!

I largely agree that having timestamped logs would be a more efficient strategy in a normal production use. We do not have the time to implement that for now, but if you or someone else is ready to write a PR on that matter, we would review and integrate it.

Two things would need to be handled in this case:
1) Even if logs are rotated, one convenient behavior would have to not have the logs of a given Certbot execution been splitted in two different log files
2) A migration path needs to be provided with the new log strategy, in order to consolidate old logs done by the current strategy: we should avoid these files been deleted, or kept in there current state forever.
