### ISSUE TITLE
Google DNS Fails: "Error Finding Zone"

### ISSUE THREAD

**Issue by Danc2050** [certbot/certbot#7653]
## My operating system is (include version):
Ubuntu 18.04
## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Pip
## I ran this command and it produced this output:
**Command:** sudo certbot certonly                  --dns-google                  --dns-google-credentials ~/haveibeenexploited-d09329c31e8c.json                   -d haveibeenexploited.com                  -d www.haveibeenexploited.com
**Output:**
```Renewing an existing certificate
Performing the following challenges:
dns-01 challenge for haveibeenexploited.com
dns-01 challenge for www.haveibeenexploited.com
URL being requested: GET https://www.googleapis.com/discovery/v1/apis/dns/v1/rest
URL being requested: GET https://dns.googleapis.com/dns/v1/projects/haveibeenexploited/managedZones?dnsName=haveibeenexploited.com.&alt=json
Attempting refresh to obtain initial access_token
Refreshing access_token
URL being requested: GET https://dns.googleapis.com/dns/v1/projects/haveibeenexploited/managedZones?dnsName=com.&alt=json
Cleaning up challenges
URL being requested: GET https://www.googleapis.com/discovery/v1/apis/dns/v1/rest
URL being requested: GET https://dns.googleapis.com/dns/v1/projects/haveibeenexploited/managedZones?dnsName=haveibeenexploited.com.&alt=json
Attempting refresh to obtain initial access_token
Refreshing access_token
URL being requested: GET https://dns.googleapis.com/dns/v1/projects/haveibeenexploited/managedZones?dnsName=com.&alt=json
Error finding zone. Skipping cleanup.
URL being requested: GET https://www.googleapis.com/discovery/v1/apis/dns/v1/rest
URL being requested: GET https://dns.googleapis.com/dns/v1/projects/haveibeenexploited/managedZones?dnsName=www.haveibeenexploited.com.&alt=json
Attempting refresh to obtain initial access_token
Refreshing access_token
URL being requested: GET https://dns.googleapis.com/dns/v1/projects/haveibeenexploited/managedZones?dnsName=haveibeenexploited.com.&alt=json
URL being requested: GET https://dns.googleapis.com/dns/v1/projects/haveibeenexploited/managedZones?dnsName=com.&alt=json
Error finding zone. Skipping cleanup.
Unable to determine managed zone for haveibeenexploited.com using zone names: ['haveibeenexploited.com', 'com'].
```
## Certbot's behavior differed from what I expected because:
Certbot should have no problem creating (or renewing) and should know the "zone" as this command has worked in the past.
## Here is a Certbot log showing the issue (if available):
[letsencrypt.log](https://github.com/certbot/certbot/files/3992736/letsencrypt.log)

**Comment by bmw** [comment]
Thanks for the detailed issue!

You may have made this change after encountering this problem, but at least right now the plugin is not going to work because it looks like haveibeenexploited.com is no longer being managed by Google Cloud DNS. We have thousands of people who have been regularly using this plugin for years, so it's hard to know what went wrong without more information.

If you're interested in continuing to debug this, please make a post at https://community.letsencrypt.org where there is a large community of people familiar with Certbot and server administration who can help you track down the problem. If it ends up being a Certbot issue, we can make a new issue to track fixing Certbot, but I'm going to close this one for now until we know the cause of the problem.
