### ISSUE TITLE
"Changing the ACME Server" docs out-of-date

### ISSUE THREAD

**Issue by mnordhoff** [certbot/certbot#7686]
The documentation section [Changing the ACME Server](https://certbot.eff.org/docs/using.html#changing-the-acme-server) needs to be updated -- in particular, it still says Certbot uses Let's Encrypt's ACMEv1 API by default.

This was [discovered](https://community.letsencrypt.org/t/certbot-upgrade-to-support-acmev2/110720) by mojoa on the Let's Encrypt forum.

**Comment by bmw** [comment]
Thanks for pointing this out.

If anyone is interested to submit a PR for this, we'd happily review it.

**Comment by nomadme** [comment]
I'd like to volunteer for fixing some in the docs.

Should I fork the `https://github.com/certbot/website` to be able to contribute to the docs?

**Comment by bmw** [comment]
Thanks @nomadme!

I think @schoen was planning to work on this particular issue, but if you have other improvements in mind you'd like to make, forking the git repository and submitting a pull request is the best way to do that.

The repository for our website is https://github.com/certbot/website, however, all of the docs found at https://certbot.eff.org/docs/ including the documentation described in the issue here are in this repository (https://github.com/certbot/certbot) under the [certbot/docs directory](https://github.com/certbot/certbot/tree/master/certbot/docs). Fork whichever repo(s) you'd like to work on!

**Comment by nomadme** [comment]
Perfect! I will scan over the issues, and see what I can do. I leave this to @schoen.

**Comment by bmw** [comment]
This was fixed in https://github.com/certbot/certbot/pull/7924.
