### ISSUE TITLE
--reuse-key ambiguity

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7711]
If you run
```
sudo certbot -d example.org --standalone certonly
```
Certbot will obtain a certificate using a 2048 bit RSA key.

If you then run
```
sudo certbot -d example.org --standalone certonly --force-renewal --rsa-key-size 4096 --reuse-key
```
the current 2048 bit RSA key is reused in the new certificate and the resulting renewal configuration file contains the following renewal parameters
```
reuse_key = True
rsa_key_size = 4096
```
I don't think this is the correct behavior. We had a brief [conversation about this in Mattermost](https://opensource.eff.org/eff-open-source/pl/4qo67zuj7brcfbjaxsecqy3our), where most people thought erroring out was the correct behavior.

This probably seems right, however, I then think we need a way to specify that a new key should be created and that key should be used for subsequent renewals. Peng suggested maybe using a separate flag for this?

I think we should fix this, however, I think this is technically a breaking change and should be done a little cautiously.

**Comment by ohemorange** [comment]
+1 to @m0namon's suggestion of erroring out with a helpful message.

**Comment by alexzorin** [comment]
>This probably seems right, however, I then think we need a way to specify that a new key should be created and that key should be used for subsequent renewals. Peng suggested maybe using a separate flag for this?

I've been [looking at `--reuse-key` scenarios](https://docs.google.com/spreadsheets/d/1B1XbsCsgvBOP0TlYhFFXNaQoJTVe_7UEfI_WphaeMp8/edit?usp=sharing) and it's mainly this question that's standing out.

Would it make sense to do a similar thing as we do for "unexpected key type migration"? That is:

- For interactive mode, an interactive prompt (1: Create a new key, or 2: Keep using the existing key). Both options would retain `reuse_key`.
- For non-interactive mode, error out: user needs to provide `--cert-name` in order to confirm the creation of a new key.

**Comment by bmw** [comment]
One problem I have is I think `--reuse-key` is ambiguous, even with `--cert-name`. When modifying an existing lineage with any subcommand which of the following does `--reuse-key` mean:

1) Reuse the existing key
2) Generate a new key and then reuse that key on subsequent renewals

I think currently it means (1) and I'm not sure the presence of `--cert-name` should change its behavior to (2). What's stopping a user from meaning (1) but still using `--cert-name`?

The details of the interactions with various other settings would need to be worked out, but the approach that I think I'd currently like the best would be to introduce a flag like `--generate-and-reuse-key`. After introducing this flag, `--reuse-key` would always mean (1) and the new flag would always mean (2). What do you think about something like this?

**Comment by adferrand** [comment]
Just to build on the potential alternatives, what about `--new-key` that always mean "generate a new key" for commands that issue a new cert, `--reuse-key`that always mean "always reuse key during renewal", and use both flags to say "generate a new key and reuse it during renewals"?

**Comment by alexzorin** [comment]
For sure `renew --reuse-key` is ambiguous. Certbot can always error in that case, directing them to `certonly/run`.

>One problem I have is I think --reuse-key is ambiguous, even with --cert-name. When modifying an existing lineage with any subcommand which of the following does --reuse-key mean:
> 1.    Reuse the existing key
> 2.  Generate a new key and then reuse that key on subsequent renewals

I'm not feeling the `{certonly,run} --reuse-key` ambiguity. 

Maybe I am alone with this, but I've always understood these verbs as generating a certificate from scratch, without looking at or inheriting the parameters of any previous lineages. It just happens to have the same certificate name.

From that perspective, it seems consistent that (2) is the unambiguous meaning. 

The old lineage is only relevant in that we are adding a guardrail to prevent the user accidentally changing key types (or key parameters under `reuse_key`), as they overwrite the old lineage with a fresh one.

I guess I'm holding onto the idea that we could avoid a new flag, especially since it only applies to a rare case (reuse_key + key param change + non-interactive).

What do you think?

**Comment by adferrand** [comment]
But certonly and run are not always generating a new certificate from scratch: if a certificate already exists for this lineage and is not due to removal, it will skip the entire process, making this an equivalent, at least at first sight, to the renew verb.

So I think there is indeed an ambiguity with these verbs and so the interpretation of what `--reuse-key`will do.

It seems that a dedicated flag, either on the specific combination of key for new cert + reuse on renew, or to do a combination of two flags (have you seen my proposition above ?) is the only way to build a clear and unique meaning for each flag.

**Comment by alexzorin** [comment]
>making this an equivalent, at least at first sight, to the renew verb.

I guess I disagree a little bit here.

As we know, renewal via the `renew` verb differs from renewal via the `{certonly,run}` verbs: `{certonly,run}` don't reconstitute the previous renewal params and the cert is generated according to CLI params only.

It would be consistent for `reuse_key` to also be discarded, because it also is a renewal param. In other words, a user who does `certonly --reuse-key` should be aware of the fact that the previous renewal params are not being retained. This is unambiguously meaning (2).

I get the feeling that I'm on the minority side of this issue, which is OK. I wanted to make sure I communicated my take on it fully.

**Comment by bmw** [comment]
I think I like the `--new-key` flag better than my `--generate-and-reuse-key` flag. Thanks for the suggestion Adrien.

I see what you mean about `--reuse-key` with certonly/run Alex. I think there is a bit of awkwardness in the design Adrien and I propose because if we're running certonly/run with `--reuse-key` and **not** modifying an existing lineage, we either need to also require `--new-key` or accept a bit of inconsistency here. (I personally prefer the latter.)

With that said, I think I still personally prefer this design because it's how `--reuse-key` currently works with certonly/run and it allows us to resolve the `renew --reuse-key` ambiguity without resorting to telling people to renew using certonly/run which is something we were trying to avoid.

If we go with this `--new-key` design, I also want to suggest that we may not need an interactive prompt here initially. I think it's a pretty uncommon scenario so I think it may be OK to just error out in the case of `reuse_key`, key params being explicitly set on the CLI which conflict with the existing key, and no `--new-key`. We could always add an interactive prompt later if people find rerunning things after fixing their command too cumbersome.

What do you think?
