### ISSUE TITLE
run_acme_server and DNS plugins

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7717]
As reported at https://github.com/certbot/certbot/pull/7583#issuecomment-577433664, if you're trying to use `run_acme_server` while working on a DNS plugin, you're going to have some issues.

What can we do to avoid people hitting this problem? My first thought would be to update our docs to say that if people are using a real domain for testing, they should just use Certbot with `--staging` rather than running an ACME server locally.

**Comment by Tugzrida** [comment]
The one thing I seem to remember from previous testing (and this happens if you don't restart the local pebble instance too) is that once the domain has been verified once, you can't verify it again due to it being verified to your account for 60 days. Knowing that, I decided to get the local server working so I didn't end up with a bunch of staging accounts, not that that really matters I guess.

**Comment by bmw** [comment]
What I do personally is use staging and regularly delete Certbot's configuration directory so it creates a new account.

Another way to get around the ACME server not verifying your domain again is to use the `--dry-run` flag which will cause Certbot to deactivate any existing authorizations for a domain before trying to perform the challenge which causes the ACME server to verify it again. That flag has other effects though such as not saving the resulting certificates to disk.

We could also make the DNS resolver to use configurable on the command line when starting the ACME server. We could allow you to set it to an arbitrary IP address and port and/or just provide a flag like `--public-dns`. I think this is my favorite option right now.

**Comment by adferrand** [comment]
I like the `--public-dns` also.
