### ISSUE TITLE
Hooks and certonly needs improvement

### ISSUE THREAD

**Issue by udf2457** [certbot/certbot#7737]
certbot 0.31.0
Debian 10

At the moment `certbot certonly` has no ability to self-disover hooks, unlike `certbot renew` which automagically looks in `/etc/letsencrypt/renewal-hooks`.

This causes a problem when it comes to the use of `certbot certonly` becuase `certbot certonly` does not automagically execute scripts in `/etc/letsencrypt/renewal-hooks/deploy` (I've tried !), and further more, ` --deploy-hook` has a PATH requirement of which `/etc` based paths are not one of them (only `/usr/local/bin, /usr/local/sbin etc`)

Reproduction of the problem as follows:
1) Put a hook script somehwere (e.g. `/usr/local/bin/myhook.sh`)
2) Put a copy of the same hook in `/etc/letsencrypt/renewal-hooks/deploy`
3) Run `certbot certonly -m test@example.com --agree-tos --no-eff-email --dns-rfc2136 --dns-rfc2136-credentials /etc/foobar/certbot.ini --deploy-hook /usr/local/bin/myhook.sh --server https://acme-v02.api.letsencrypt.org/directory -d example.com -d *.example.com`
4) Run `certbot renew --dry-run --force-renewal`, note how it attempts to run both the original hook (due to its automatic definition in `/etc/letsencrypt/renewal/example.com.conf` as part of the `certbot certonly` process) and also the automagic hook in `/etc/letsencrypt/renewal-hooks/deploy`

This causes un-necessary duplicaton. 

Either `/etc/letsencrypt/renewal-hooks/deploy` should be supported by `certbot certonly` or there should be a seperate directory under `/etc/letsencrypt` which is supported by `certbot certonly`  and automatically deconflicted when `certbot renew` is later run.

**Comment by adferrand** [comment]
For the record, this issue was the first I had to deal with, way before starting to contribute on certbot.

Indeed, the hooks in `/etc/letsencrypt/renewal-hooks` are executed only for renewal, not for first certificate issuance, as the name of the folder says it. The reasoning behind is that it is constructed around the usual way to use certbot: run it once (interactively, with `certonly` for instance), then forget about it (scheduled non interactive executions with `renew`).

In that extend, the `renewal-hooks` is designed for these non interactive executions.

Now there are also the `--deploy-hook` flag, that do two things: execute the hook for `certonly`, and store it in the certificate renewal configuration, that will be executed each time a `renew` is done for this particular certificate.

So I think hooks here are provided through two opinionated approaches, and one or the other need to be chosen given the situation. Personally I always use the `--deploy-hook` flag only, because it allows to have dedicated hooks for each certificate.

What can be improved here ? I do not have a clear solution that would not have significant drawbacks:
* migrating the `renewal-hooks` directory to be run on `certonly` would potentially create regressions on existing certbot installations
* creating a new hooks directory for `certonly` + `renew` adds a significant complexity, and a deduplication mechanism seems error prone to me

Maybe it is about improving `--deploy-hook`. In particular, the fact that the executable needs to be in the PATH is kind of a limitation. Hooks scripts should work if the full path is given.

**Comment by udf2457** [comment]
@adferrand Thank you for your comments.

To pick up specifically on the PATH limitation, the interesting thing is that it seems to be some sort of recent introduction as a restriction. I was actually in the process of migrating my certbot install to a new server.  On the old server my script was calling `--deploy-hook` on a custom path (`/etc/foobar/certbot/hook.sh`).  But when I ran `certonly` on the new server, I was surprised to discover the PATH limitation.

I agree with you that the old behaviour should be the default.  `--deploy-hook` should respect the full path when given. It should not be opinionated.

On another note, you could create a new hooks directory for `certonly` and leave `renew` as presently constituted. That would provide clear seperation of the tasks ?

**Comment by thenewguy** [comment]
For me, the filesystem approach is much preferred to the command line hook. It is a lot easier to know the right thing will happen for an environment without me having to remember what that is every time I request a certificate.

Perhaps a new "common" hooks folder should be created that runs for both renewals and first issuance requests.

**Comment by FelixSchwarz** [comment]
I'm in the same boat as well:

- I need a way to trigger some action whenever there is a new (or changed/renewed) certificate (e.g. deploy the certificate to our  load balancer or multiple machines sharing the same certificate)
- Ideally the action is not statically configured via a specific certbot config file but certbot should iterate over all scripts in a directory (same as "renew" does with `renewal-hooks/deploy` currently). That is easy to manage via ansible and we can apply changes easily.

The current state of affairs is pretty confusing especially because `certbot certonly --dry-run ...` emits log messages like `Dry run: skipping deploy hook command: ...` but the real `certonly` run will not trigger these deploy hooks anyway.

I think #6346 and #9010 are related.

**Comment by stokito** [comment]
How about `/etc/letsencrypt/issue-hooks/{deploy,pre,post}` folder name? It looks for me most obvious and can be backward compatible.

See also #9530
