### ISSUE TITLE
Support async/await in the acme client library

### ISSUE THREAD

**Issue by babolivier** [certbot/certbot#7756]
It would be great if the client library could provide an `async` client, using Python's new `async`/`await` semantics. The current main solution is to use Twisted's [txacme](https://github.com/twisted/txacme) which doesn't seem to be very actively maintained and currently doesn't support ACMEv2.

**Comment by bmw** [comment]
That would be cool! Realistically, I doubt this is something the Certbot team would get to anytime soon but maybe we could support it if someone else initially wrote it.

Do you know how much code could be shared between the synchronous and asynchronous clients? I haven't played around with `async`/`await` yet.

**Comment by babolivier** [comment]
> Do you know how much code could be shared between the synchronous and asynchronous clients? I haven't played around with `async`/`await` yet.

I'm not exactly sure. I think some part of the `ClientNetwork` would need an async copy, but there might be some clever thing one can do with coroutines to make it async or not depending on the use case. I don't know `async`/`await` enough to give you a definitive answer on this.

**Comment by bmw** [comment]
Got it.

The answer to questions like that will probably dictate whether or not this is something we'd accept a PR for. We don't really have a need for an `async` client in Certbot so if adding one will result in a lot of code that we don't use and would have to maintain, I think it probably makes more sense in a different library. If the maintenance burden is relatively small though, I could see us taking this on.

**Comment by babolivier** [comment]
Yes, that makes sense.

**Comment by adiroiban** [comment]
Hi. txacme was not active as it used to just work with ACME v1 :)

I am using txacme in production.
I have an old account, and I can continue to use ACME v1... so there is no rush for me to upgrade.

I dedicated time to get ACME v2 support in txacme and it now works for me with ACME v2.
It just need testing and feedback from other users, in order to make a final release of txacme with v2 support.

It would be nice to have sans i/o support in acme library... but I think that this is something for an external library... and it much easier to convert txacme library to support asyncio than convert certbot
 
txame already uses the messages (json serialization / deserialization) from certbot

The only thing that is missing is the  network interaction and then the logic of creating RSA keys, the CSR  and retry on errors.

I think that this can be closed and have an external sans i/o library for ACME v2.

**Comment by bmw** [comment]
Thanks for the update @adiroiban.

I'd still potentially be open to accepting a PR to add asyncio support to our ACME library if the amount of code we had to maintain was small, but since I don't think this is something the Certbot team will ever implement themselves, I'm going to close this issue as wontfix.
