### ISSUE TITLE
[feature request] Root CA inclusion

### ISSUE THREAD

**Issue by johnnybubonic** [certbot/certbot#7768]
Often, certain software requires the concatenation of the root CA and the intermediate together to be treated and trusted as a single CA certificate (e.g. openLDAP, for instance).

I'd like to suggest that certbot have the ability to download the root CA signing certificate and place that in `/etc/letsencrypt/live/<domain>/` (technically, the archive) (or a place higher in the hierarchy) as well. Optionally, but highly recommended, provide a "trusted-chain.pem" that consists of a concatenated file of the root CA and intermediate *only*. Otherwise the user is forced to concatenate themselves on every renewal.

**Comment by schoen** [comment]
Hi @johnnybubonic,

Can you explain why openLDAP has this requirement? It doesn't make sense from the point of view of my understanding of PKI.

In particular, a copy of the root certificate is either *redundant* or *not useful* from the point of view of the TLS validator. If the TLS validator trusts the root, it already has a copy of it and already knows its contents, while if it doesn't, it shouldn't start to accept it merely because someone sends a copy of its self-signed certificate.

Although it's available on the Let's Encrypt "documentation" pages, the Let's Encrypt CA does not include, within the ACME protocol, a copy of the root that signed the intermediate certificate that issued the new leaf certificate, for the reason that I just mentioned.

**Comment by johnnybubonic** [comment]
> Can you explain why openLDAP has this requirement? It doesn't make sense from the point of view of my understanding of PKI.

Sure. I don't agree with the design, either, personally, but openldap (along with others- ejabberd faces similar issues) only allow for one source of a CA. That means either:

1. The system trust store (which is only root CAs), or
2. The intermediate (which it rejects as invalid because see point above; it doesn't read in the root/system's trust).

As a result, to get a properly validating chain, one has to concatenate the root and intermediate together themselves. What you said is absolutely correct- NORMALLY, for MOST software when operating as an end-user client, this situation doesn't come up. But if the server software itself is validating against another source (for instance, in the case of openldap both serving startTLS and also proxying some requests to another LDAP server via startTLS, or encrypted S2S connections in ejabberd), it would need both the CA and intermediate combined into a single CA reference.

I fully recognize and concede this is a request to help compensate for software's poor decisions in chain validation, but X509 in general is sort of a mess these days anyways. ;)

Of course, the ideal solution for everyone would be for LE themselves to be added as a trusted root everywhere, but that is not a feasible option at the moment. I suppose I could add the LE intermediate, in this case, as a trusted root for all machines I manage, but that strikes me as hacky and I'm not entirely sure of the scope it'd affect.

Does that make sense from a design perspective?

**Comment by schoen** [comment]
Yes! But I think it's even lower priority for us than other bundles and formats that have been proposed for Certbot to create automatically (such as PFX and JKS), since those other ones would improve the ease of our integration with even more software environments.

I would say that our recommended approach for this is a `--deploy-hook`, where you can specify a script of your own to perform the concatenation you want; this script could probably be just a single line. I've seen some people using that approach quite successfully in analogous cases.

**Comment by johnnybubonic** [comment]
Understood and agreed on priority! I'm currently using a deploy hook for it now already, but my worry is if the root CA cert changes and https://letsencrypt.org/certs/trustid-x3-root.pem.txt isn't updated, for instance, and it's a bit hard to scrape that page's text contextually to find the link to where it could be downloaded again, etc. Basically, automation predictability.

Thanks! I find it kind of crazy that the ACME protocol's RFC doesn't even provision for providing the root CA if an intermediate is signed, even as a MAY clause. Especially since default root trusts can differ between clients/client software!

Thanks again!

**Comment by osirisinferi** [comment]
> I find it kind of crazy that the ACME protocol's RFC doesn't even provision for providing the root CA

As a workaround, one could parse the intermediate certificate and parse the "CA Issuers" field from the "Authority Information Access" part of the certificate. Not sure if *every* intermediate certificate would have such a field (I don't know if it's mandatory or not..), but all Let's Encrypt intermediate certs have the field present pointing to the root certificate which signed the intermediate.

**Comment by johnnybubonic** [comment]
The problem is this assumes that the cert referenced by the issuer is indeed available locally already, however.

**Comment by alexzorin** [comment]
The AIA CA Issuers field points to an HTTP location where you can download the root in DER format.

In theory, armed with nothing but the chain that the ACME server gave you, you should always be able to locate and download a a root certificate. @osirisinferi makes a good point that the field may not be guaranteed to be there, but it seems to be there in practice for every Let's Encrypt issuer so far:

    $ curl -s https://letsencrypt.org/certs/letsencryptauthorityx3.pem | openssl x509 -in - -noout -text | grep "CA Issuers"
                    CA Issuers - URI:http://cert.root-x1.letsencrypt.org/

    $ curl -s https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem | openssl x509 -in - -noout -text | grep "CA Issuers"
                    CA Issuers - URI:http://apps.identrust.com/roots/dstrootcax3.p7c

    $ curl -s https://letsencrypt.org/certs/lets-encrypt-e2.pem | openssl x509 -in - -noout -text | grep "CA Issuers"
                    CA Issuers - URI:http://x2.i.lencr.org/
