### ISSUE TITLE
Stop emailing when no certificate is renewed

### ISSUE THREAD

**Issue by Zyles** [certbot/certbot#7775]
Is it possible to tell certbot not to email me every day when running on cronjob?

My cronjob is:

`0 0 * * * sudo /usr/bin/certbot renew --post-hook "sudo service nginx reload"`

And I get emails:

`Cert not yet due for renewal`

I only want to get emailed when a certificate is up for renewal, failed to renew, or has been renewed.

I don't need to be notified daily that there is nothing to renew.

## My operating system is (include version):

Ubuntu 18.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
pip3

## I ran this command and it produced this output:

`0 0 * * * sudo /usr/bin/certbot renew --post-hook "sudo service nginx reload"`

`Cert not yet due for renewal`

**Comment by alexzorin** [comment]
Pass the `-q` flag to Certbot in your cronjob. It will silence unimportant output.

You should also include a random sleep rather than running at exactly midnight or on any hour, otherwise you are more likely to run into CA-based timeouts due to other similarly unstaggered cronjobs.

Take a look at how the Debian package does it for guidance: https://salsa.debian.org/letsencrypt-team/certbot/certbot/blob/master/debian/certbot.cron.d

**Comment by schoen** [comment]
Thanks, @alexzorin! I think that's exactly right.

The cron jobs that we and packagers create generally do silence Certbot's non-error output for this reason; people creating their own cron jobs can do this for themselves exactly as you suggest.
