### ISSUE TITLE
dns_cloudflare_api_token not working

### ISSUE THREAD

**Issue by edwardjohnson11** [certbot/certbot#7779]
#7513  My operating system is (include version):
FreeBSD 11.2

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Compiled from source via ports

## I ran this command and it produced this output:
I followed the [cloudflare plugin documentation](https://certbot-dns-cloudflare.readthedocs.io/en/stable/) and put in my .ini the following, as directed:

dns_cloudflare_api_token = [...]

However, the error I get is that dns_cloudflare_email and dns_cloudflare_api_key are not provided. It doesn't seem like the plugin/certbot is accepting the api_token method of accessing my cloudflare account.

**Comment by bmw** [comment]
This is because the FreeBSD maintainers haven't updated the cloudflare plugin to version 1.2.0 or greater to include this feature. See https://svnweb.freebsd.org/ports/head/security/py-certbot-dns-cloudflare/.

I'd recommend reaching out to them asking them to update it. In the meantime, you'll have to use the email and API key which is also documented at the link you provided.

**Comment by AlexanderBech** [comment]
How do I see what version of certbot cloudflare plugin I'm running?

**Comment by bmw** [comment]
There's no output from Certbot that includes this. You have to use the package manager you used to install the plugin and instructions will vary based on the package manager.

If you need additional help with this, I recommend making a post at https://community.letsencrypt.org where there is a large group of people familiar with the project who should be able to help you.
