### ISSUE TITLE
On RHEL6 with python3 pointing to python 3.4, and python3.6 existing, certbot won't find python3.6

### ISSUE THREAD

**Issue by matiu2** [certbot/certbot#7792]
## My operating system is (include version):

Red Hat Enterprise Linux Server release 6.10 (Santiago)

    $ python3 -V
    Python 3.4.10

    $ python3.6 -V
    Python 3.6.8

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

    sudo -i
    wget https://dl.eff.org/certbot-auto
    chmod u+x certbot-auto

## I ran this command and it produced this output:

(I also made it print some variable values)

    $ ./certbot-auto --no-bootstrap
    Creating virtual environment...
    You have an ancient version of Python entombed in your operating system...
    This isn't going to work; you'll need at least version 3.5.
    LE_PYTHON: python3
    PYVER: 34
    MIN_PYVER: 35
    USE_PYTHON_3: 1

## Certbot's behavior differed from what I expected because:

When I changed line 274 from:

    for LE_PYTHON in "$LE_PYTHON" python3; do

.. to ..

    for LE_PYTHON in "$LE_PYTHON" python3 python3.6; do

It worked with '--no-bootstrap' but not without.

## Here is a Certbot log showing the issue (if available):

Nothing in /var/log/letsencrypt

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

N/A

**Comment by bmw** [comment]
Unfortunately, we're not able to help you get certbot-auto working without `--no-bootstrap` on your system. By using this flag, you're taking things into your own hands and setting up Certbot's dependencies yourself rather than relying on our well tested approach. If you want to continue to do this though, you can probably make things work by setting the `LE_PYTHON` environment variable to `python3.6`.

If you want to make things work without `--no-bootstrap` on RHEL 6, you'll need to enable the SCL repository.

I hope this helps, but if you need additional help making the script work on your system, I recommend making a post at https://community.letsencrypt.org where there is a large community of people familiar with the project and server administration who should be able to help you.
