### ISSUE TITLE
Windows client has problem working on shared drives

### ISSUE THREAD

**Issue by ragimiri** [certbot/certbot#7799]
Hello, I am using certbot as administrator on Windows 10. I found two problems with it:

1. When running certbot on shared drive (like L:) it does not save any file and crash with error An unexpected error occurred: pywintypes.error: (1307, 'CreateFile', 'This security ID may not be assigned as the owner of this object.') Please see the logfiles in C:\Certbot\log for more details.

2. Even when --config-dir C:\Other_folder is used, logs from certbot goes every time to C:\Certbot\log folder.

**Comment by adferrand** [comment]
Hello @ragimiri ! Thanks for your report.

Thanks for your report! Indeed, shared folders will create problems with the current process. I will improve that as soon as possible. For now sadly you will need to use local drives.

For your second remark, in fact it is expected. The `--config-dir` controls only the configuration folder (default `C:\Certbot`), but not the log folder (`C":\Certbot\logs` and the workdir folder (default `C:\Certbot\lib`). For them, you need the flags `--logs-dir` and `--work-dir` flags, respectively.

Could you update the issue title to reflect the specific need to handle shared folders on Windows ?

**Comment by ragimiri** [comment]
Hi, thanks for clarification. I will use local drive and I changed title.

**Comment by zoracon** [comment]
Closing due to our decision to discontinue our Beta distribution of the Windows Installer:
https://github.com/certbot/certbot/wiki/Architectural-Decision-Records#-certbot-discontinuing-windows-support

If you need alternatives. They are listed in this community forum post:
https://community.letsencrypt.org/t/certbot-discontinuing-windows-beta-support-in-2024/208101
