### ISSUE TITLE
Certbot reports error when reloading NGINX

### ISSUE THREAD

**Issue by Code-You-Fools** [certbot/certbot#7830]
## My operating system is (include version):
Debian Buster (Linux (redacted) 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
`apt install certbot`

## I ran this command and it produced this output:
`sudo certbot renew --dry-run`

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/(redacted).conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Cert not due for renewal, but simulating renewal for dry run
Plugins selected: Authenticator nginx, Installer None
Renewing an existing certificate

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
new certificate deployed without reload, fullchain is
/etc/letsencrypt/live/(redacted)/fullchain.pem
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates below have not been saved.)

Congratulations, all renewals succeeded. The following certs have been renewed:
  /etc/letsencrypt/live/(redacted)/fullchain.pem (success)
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates above have not been saved.)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Running post-hook command: /etc/letsencrypt/renewal-hooks/post/nginx-reload.sh
Error output from nginx-reload.sh:
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

## Certbot's behavior differed from what I expected because:
Certbot improperly flags `nginx -t` success output as an error.

## Here is a Certbot log showing the issue (if available):
```
2020-03-03 12:20:55,486:DEBUG:certbot.renewal:no renewal failures
2020-03-03 12:20:55,486:INFO:certbot.hooks:Running post-hook command: /etc/letsencrypt/renewal-hooks/post/nginx-reload.sh
2020-03-03 12:20:55,594:ERROR:certbot.hooks:Error output from nginx-reload.sh:
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
Shouldn't be relevant to the issue

**Comment by Code-You-Fools** [comment]
This also occurs when not run with the `--dry-run` flag.

**Comment by m0namon** [comment]
@Code-You-Fools Would you feel comfortable copying the contents of your post-hook `nginx-reload.sh` script here?

**Comment by alexzorin** [comment]
>Certbot improperly flags nginx -t success output as an error.

I think this is just wording being slightly confusing. 

I don't think Certbot is treating it as an error, it's just reporting that the hook generated some output on `stderr` (and indeed it did, `nginx -t` sends its output to `stderr`).

Perhaps it is wrong for Certbot to log this at the `ERROR` severity, but perhaps not. Logging it at this level would allow it to surface in cronjob output if run with `--quiet`.

Perhaps you can just redirect it to `>/dev/null` and check the exit code?

**Comment by Code-You-Fools** [comment]
@m0namon I haven't changed it from stock.
`nginx -t && systemctl reload nginx`

@alexzorin Ah. Wasn't aware that `nginx -t` put that message onto `stderr`, my shell wasn't highlighting it as being abnormal. I'll close this and report the bug to them, instead.

**Comment by vgrebenschikov** [comment]
In fact - it is certbot who treat stderr output with rc=0 as error:

```
# certbot renew 
...
Error output from post-hook command service:
nginx: the configuration file /usr/local/etc/nginx/nginx.conf syntax is ok
nginx: configuration file /usr/local/etc/nginx/nginx.conf test is successful


# nginx -t > /dev/null
nginx: the configuration file /usr/local/etc/nginx/nginx.conf syntax is ok
nginx: configuration file /usr/local/etc/nginx/nginx.conf test is successful
# echo $?
0
#
```

Nothing bad with nginx, some command, with some output - nothing to be evaluated as error, but certbot thinks that it was an error and confuse users 

IMHO, clearly certbot bug

**Comment by alexzorin** [comment]
nginx is sending the output of `nginx -t` to its "standard error" stream. That's why Certbot reports it as "error output". 

I can see how that can be misleading: "oh no, there's an error in nginx".

The problem is that hooks are just a generic way to run arbitrary commands, and it's never going to be a perfect fit with every piece of software that Certbot gets combined with, which do slightly different things with their output streams and exit codes.

I am not convinced that we should start suppressing stderr in these cases. My current thoughts on this are:

- We quite recently looked at the different hooks out there, and decided that we can't start hiding their stdout or stderr output, because some of the hook workflows rely on the user actually seeing the output (like the acme-dns ones).
- You are ultimately writing a hook to be consumed by Certbot. If the superfluous stderr bothers you, you can `2&>/dev/null` the relevant process.
- In the specific case here, something like `systemctl reload nginx` or `nginx -s reload` on their own probably match better, because they don't produce any output on success, and otherwise just report the error.

If this continues to be a point of confusion, we could potentially look at clarifying the wording of the error output reporting.
