### ISSUE TITLE
Using a DNS name instead of IP address for rfc_2136_server should give a useful error

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#7871]
According to https://community.letsencrypt.org/t/erreur-certbot-text-input-is-malformed/117957/, if you use a DNS name instead of an IP address for the value of `dns_rfc2136_server`, you get a pretty unhelpful traceback instead of a clear explanation of the problem. The traceback ends up saying `Text input is malformed` but doesn't mention that the problem is the use of a DNS name rather than an IP address.

I confirmed that the DNS library gives this exception with

`response = dns.query.udp(request, "ns1.sonic.net", port=53)`

or 

`response = dns.query.tcp(request, "ns1.sonic.net", port=53)`

instead of what the library expects, which is more like

`response = dns.query.udp(request, "208.201.224.11", port=53)`

@bmw noted that this is specified in the `dnspython` docs at

http://www.dnspython.org/docs/1.16.0/dns.query-module.html#udp

This is kind of a problem for us at

https://github.com/certbot/certbot/blob/bc3088121b74158ca4b24bc380d043f187196957/certbot-dns-rfc2136/certbot_dns_rfc2136/_internal/dns_rfc2136.py#L208

because the error the user receives doesn't indicate what value needs to be changed, or how, just `Text input is malformed`!

**Comment by mateuszdrab** [comment]
Why doesn't this work with dns names? I just came across this issue whilst implementing my dynamic dns solution.

**Comment by droesen** [comment]
Better support FQDN instead of just IP addresses, see:

https://github.com/certbot/certbot/pull/5664

**Comment by mateuszdrab** [comment]
Awesome, glad to see it's gonna be fixed in the next release. I'll keep an eye and rebuild my docker container when the new version is out.

**Comment by anarcat** [comment]
shouldn't certbot just *look* at which nameserver(s) are responsible for a zone? this can't be a one-to-one mapping, different domains might have different master DNS servers... either we look at NS records for the zone, or we have a TLD->NS map somewhere in the config. but a single IP address definitely doesn't cut it for our use case here at least.

**Comment by mateuszdrab** [comment]
> shouldn't certbot just _look_ at which nameserver(s) are responsible for a zone? this can't be a one-to-one mapping, different domains might have different master DNS servers... either we look at NS records for the zone, or we have a TLD->NS map somewhere in the config. but a single IP address definitely doesn't cut it for our use case here at least.

The verification phase at LetEncrypt's side happens by looking up the nameservers registered for the zone publicly. Any other solution would defeat the point of verification since you could give your own fake zone nameservers for any public domain. 
However, being able to point the IP on certbots side allows you to implement various solutions. In my case, I'm connecting to my master dns server internally and that server isn't even registered as a nameserver for my zone, I have slaves registered instead which zone transfer from my master. You could have your master completely isolated from the internet this way (just need to allow the masters to zone transfer).

**Comment by anarcat** [comment]
> The verification phase at LetEncrypt's side happens by looking up the nameservers registered for the zone publicly. Any other solution would defeat the point of verification since you could give your own fake zone nameservers for any public domain.

Well, that's what I am saying here: we are explicitely *not* doing that here. We are hardcoding the NS server instead of doing the same thing the ACME protocol does (which is an NS lookup).

>  However, being able to point the IP on certbots side allows you to implement various solutions. In my case, I'm connecting to my master dns server internally and that server isn't even registered as a nameserver for my zone, I have slaves registered instead which zone transfer from my master. You could have your master completely isolated from the internet this way (just need to allow the masters to zone transfer).

I understand, that's a common (and reasonable) setup...

>  I get you however, being able to provide multiple masters in certbot would be useful.

... but it breaks down if you have multiple primary servers you need to talk to.

In my case, I need to create a cert for `foo.example.com` and `bar.example.org` which have distinct primary nameserver, which happen to be in the public `NS` records as well. If we would rely on those by default, my use case would be covered. And yours would be as well with a configurable fallback.

**Comment by osirisinferi** [comment]
Original issue (OP) has been fixed in #8990 (i.e.: certbot now provides a useful error, not hostname support).

**Comment by bmw** [comment]
Thanks for pointing that out!
