### ISSUE TITLE
Conflicts when alias is also used for another domain

### ISSUE THREAD

**Issue by duck-rh** [certbot/certbot#7887]
## My operating system is (include version):
Debian Buster

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot 0.36.0-1 is installed from the Debian archive
python3-certbot-dns-rfc2136 0.35.1-1 is a patched version from the Debian archive to add support for CNAMEs in DNS challenge, see #7244 

## I ran this command and it produced this output:
I ran this command:
`
2020-04-07 08:14:35,734:DEBUG:certbot.main:Arguments: ['--text', '--renew-by-default', '--rsa-key-size', '3072', '--email', 'root+lets-mail.duckcorp.org@duckcorp.org', '--domains', 'mail.duckcorp.org,imap.duckcorp.org,pop.duckcorp.org,sieve.duckcorp.org,Orfeo.duckcorp.org', '--agree-tos', '--dns-rfc2136', '--dns-rfc2136-credentials', '/etc/letsencrypt/rfc2136.ini', '--dns-rfc2136-propagation-seconds', '15']
`

And got this result:
`Your certificate and chain have been saved at:
/etc/letsencrypt/live/orfeo.duckcorp.org/fullchain.pem`

## Certbot's behavior differed from what I expected because:
The main domain is always used so far to create and get the certificate, here it should have been `/etc/letsencrypt/live/mail.duckcorp.org/fullchain.pem` instead. It happens that `orfeo.duckcorp.org` already exist (using webroot challenge, for HTTPS usage) and its configuration has been crushed.

If I move aside the `orfeo.duckcorp.org` directories, recreate the `mail.duckcorp.org` cert above (after a revokation and removal), then it is created properly. I then restored the `orfeo.duckcorp.org` files and tested a renewal of woth certs and it works fine, so this is only a bug at initial creation.

## Here is a Certbot log showing the issue (if available):
[20200407_certbot_shared_alias_conflict.log](https://github.com/certbot/certbot/files/4447975/20200407_certbot_shared_alias_conflict.log)

**Comment by alexzorin** [comment]
Putting aside that Certbot overwrote the certificate in this case (probably because of `--renew-by-default`?), you could avoid this by nominating a name for your certificate:

    --cert-name duckcorp-mail-cert

and it'd be stored in `/etc/letsencrypt/live/duckcorp-mail-cert/` instead.

Apologies if you weren't looking for a workaround.

**Comment by duck-rh** [comment]
Yes, we're using `--renew-by-default` and the automation (Ansible) decides if the command needs to be run again or skipped.

So I think I missed this part of the documentation because I did not look at this option, but it seems it does what it says it would:
`(default: the first provided domain or the name of an existing certificate on your system for the same domains)`

It is totally acceptable for me to use this option. I just tested and it works fine.

Since a name can be used for various services on different ports and you might want to use a separate certificate for each of them, this situation is not that uncommon. I wonder what is the rational behind matching any certificate in the aliases and I cannot see any practical use case.

So I guess it's up to you to decide how much confusing it is to users and if you want to deprecate this behavior. The documentation is not bad, just that did not make sense to me I guess and overlooked it.

**Comment by bmw** [comment]
> I wonder what is the rational behind matching any certificate in the aliases and I cannot see any practical use case.

The rationale was preventing people from accidentally obtaining and then maintaining many different certificates when they try to modify properties of an existing certificate such as the domains, private key, plugins and their options used for renewal, etc. I think this may be slightly more common than wanting to obtain two certificates with the exact same domains (or a superset of the domains in the cert if you have `--expand` set), but I don't think defaulting to overwriting the certificates is the best behavior here.

Instead, in cases of any ambiguity like this, we should probably error out and/or prompt the user about what to do when running interactively. We've had this behavior since we initially launched Certbot in 2015 and I doubt we'll get a chance to change it anytime soon, but I definitely think this is something that can be improved. I'll leave this issue open to track maybe redesigning this behavior in the future.

This is probably something that is hard to fix through documentation, but if people have ideas for changes we can easily make there in the meantime, please propose them!

**Comment by duck-rh** [comment]
Alright, let's close this.
Thanks for the replies.
