### ISSUE TITLE
apt packet outdated

### ISSUE THREAD

**Issue by Nisutec** [certbot/certbot#7888]
## My operating system is (include version):
Debian GNU/Linux 10 (buster)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS package manager (apt)

## I ran this command and it produced this output:
The Command `certbot --version` outputs `certbot 0.31.0`

## Certbot's behavior differed from what I expected because:
I have seing that already a certbot Version 1.2.0 or greater is avaliable but at the moment this is not on apt released.

**Comment by bmw** [comment]
The Certbot packages in stable versions of Debian (as well as most other packages) don't usually see updates unless there is a security or compatibility issue due to distro policy.

One option we used in the past was the backports repo, however, that caused some issues when `jessie-backports` was shutdown before jessie reached its end-of-life.

Another option is we're actively working on packaging Certbot as a [snap](https://snapcraft.io/). This may not be people's first choice for packaging, however, it would provide Debian users an easy way to obtain the latest version of Certbot and keep it up-to-date.

What do you think @hlieberman? Do you have any plans or interest in pushing Certbot to backports or should we close this issue as wontfix?

**Comment by enoch85** [comment]
Just tried `snap install certbot` and it said that there were two versions available: `--beta` and `--egde`, though when trying to install `--beta` it said that only `--edge` was available - resulting in that I got 1.4.0dev.

Is that expected? Where's the stable version of certbot as a snap?

**Comment by bmw** [comment]
We're working on the snap. We're not encouraging people to use it yet, although the snap you installed with `--edge` is built by us. You can track the announcement of beta versions of the Certbot snap at https://github.com/certbot/website/pull/558 if you'd like.

In the meantime, if you need the latest version of Certbot you can use [certbot-auto](https://certbot.eff.org/docs/install.html#certbot-auto) or [Docker](https://certbot.eff.org/docs/install.html#running-with-docker), but keep in mind that we're planning on deprecating certbot-auto in the coming months.

**Comment by enoch85** [comment]
Thanks for the info. I'm waiting eagerly on the snap version as I'm planning to include it in the [Nextcloud VM](https://github.com/nextcloud/vm).
