### ISSUE TITLE
virtualenv', '--no-site-packages', '--python', '/usr/bin/python2.7', '/opt/eff.org/certbot/venv']' returned non-zero exit status 2

### ISSUE THREAD

**Issue by djdevil** [certbot/certbot#7897]
My operating system is (include version):

Buster (Raspberry)

I installed Certbot with (certbot-auto, OS package manager, pip, etc):

certbot-auto
I ran this command and it produced this output:

`usage: virtualenv [--version] [--with-traceback] [-v | -q] [--app-data APP_DATA] [--clear-app-data] [--discovery {builtin}] [-p py] [--creator {builtin,cpython2-posix}] [--seeder {app-data,pip}] [--no-seed] [--activators comma_sep_list]
                  [--clear] [--system-site-packages] [--symlinks | --copies] [--download | --no-download] [--extra-search-dir d [d ...]] [--pip version] [--setuptools version] [--wheel version] [--no-pip] [--no-setuptools] [--no-wheel]
                  [--symlink-app-data] [--prompt prompt] [-h]
                  dest
virtualenv: error: unrecognized arguments: --no-site-packages
Traceback (most recent call last):
  File "<stdin>", line 27, in <module>
  File "<stdin>", line 19, in create_venv
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['virtualenv', '--no-site-packages', '--python', '/usr/bin/python2.7', '/opt/eff.org/certbot/venv']' returned non-zero exit status 2
`

**Comment by alexzorin** [comment]
https://github.com/certbot/certbot/issues/7828#issuecomment-595903388 seems related.

`python-virtualenv` in the Debian Buster repos does support `--no-site-packages`. 

You have probably got an "extra" `virtualenv` installation, probably in `/usr/local/bin/virtualenv`, probably installed directly via `pip`.

If you remove that `virtualenv`, everything should work.

Alternatively, if you just install Certbot using `apt install certbot` rather than using `certbot-auto`. that should work too.

**Comment by djdevil** [comment]
hello ok it work witk cerbot-auto thx
