### ISSUE TITLE
Run mypy on our tests again

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#7909]
Similarly to #7908, when we moved our tests out of our packages, we accidentally stopped running `mypy` on them. Getting mypy to run on the tests won't be an issue, but if we run it as is, we start to hit errors. The first level of these, which causes `mypy` to print an error and stop running, is the duplicate named files (for example, `acme/tests/client_test.py` and `certbot/tests/client_test.py`). A way to fix that would be to run a small script that runs `mypy` individual on each directory and/or module. But a complication here is that many of the files depend on `acme/acme/magic_typing.py`, and will print errors when not run alongside `acme/acme`. Hardcoding that in would be a bit of a hack, so a better solution is probably to deprecate `magic_typing` by no longer doing any Python 2.7-style mypy support in our codebase (also see https://github.com/certbot/certbot/issues/7806).

If we choose to go ahead with option 2 from https://github.com/certbot/certbot/issues/7908, that may solve at least some of the issues (probably the ones around naming, since those weren't a problem before we reorganized the tests and removed the `__init__.py`s). But there are some other issues to deal with.

An initial attempt at dealing with all of this was made on the run-all-mypy branch, but that is probably not actually the best way to move forward here.

**Comment by ohemorange** [comment]
See closed https://github.com/certbot/certbot/pull/7907

**Comment by michael-joy** [comment]
Would setting the python_version to something like this help?
python_version = platform.python_version()
It would make it frendlier to multiple versions.

**Comment by ohemorange** [comment]
Thanks @michael-joy! Just changing the version is one piece of the problem; we need to fix some errors that pop up when we do that.

**Comment by bmw** [comment]
I've been working on this because I'd like mypy's sanity checking for some of my test refactoring.

Building off what I said in https://github.com/certbot/certbot/issues/7908, just sticking `__init__.py` files in each of our test directories doesn't work. This results in tools like mypy or pytest seeing N different definitions for the `tests` module which conflict with each other.

Because of this, I'd like to deviate from the design I proposed many years ago at https://github.com/certbot/certbot/issues/5775. Specifically, I'd like to move our tests back in with our application code, but place it under the `_internal` directory which already exists for most of our packages. While the use of `_internal` is somewhat unique, this is [a common approach supported by tools like pytest](https://docs.pytest.org/en/7.1.x/explanation/goodpractices.html#tests-as-part-of-application-code). This gives each file a unique name (`acme._internal.tests.client_test` vs `certbot._internal.tests.client_test`) and very clearly communicates that people shouldn't touch this stuff (unlike [`certbot.tests` which is part of our API](https://eff-certbot.readthedocs.io/en/stable/api/certbot.tests.html)).

I'd love to hear peoples thoughts here before we/I start doing this work. This will take some time because lots of files need to change and as part of this we'll have to fix this issue and #7908 (or explicitly configure these tools to ignore these files for now), but I personally think it's worth it.

**Comment by ohemorange** [comment]
Trying to recall why we moved them out in the first place by reading through some old documentation and discussions. Seems like it was a combination of 1) don't ship tests and 2) make it clear tests aren't part of the public api. Was there another reason I'm forgetting? If it's just these, this solves 2) but doesn't solve 1).

The issue mentioned in the first comment about `magic_typing` no longer applies, of course.  Is there a problem with doing "run a small script that runs mypy individually on each directory and/or module"?

I know we get complaints sometimes about the size of certbot, that's probably the main reason to put effort into not shipping tests but pretty sure it won't actually change things on that front too much. Is there any other reason to want to not ship tests? If not, does seem like the easiest thing would be to do as you've proposed and just stick them in `_internal`.

**Comment by bmw** [comment]
You may have found/remembered something I didn't, but I think our main goal with this was to accomplish 2) and not 1). I traced the origin of this work to https://github.com/certbot/certbot/issues/5775. In [the design doc linked in that issue](https://docs.google.com/document/d/1ozJvEDq2qTtKMeicCUyxH6BZ80_7XZSQDMHMo8uA1WA/edit?usp=sharing), I do say:

> There used to be a debate about whether or not you should ship your tests alongside your code in Python, but I think that debate has settled with nearly all significant Python projects taking this approach. Other than not deviating from modern conventions unnecessarily, the other benefit is it is very explicit that our tests are not part of Certbot’s API. There isn’t even a way to import them outside of using a relative import like “import .utils”

That's maybe a bit misleading because we do still ship our tests in our packages and I believe we want to continue to do so. What we did with this work years ago is we stopped shipping them **alongside or intermixed with** our application code. In other words, we switched to the first approach from the second approach of [the two "common" approaches supported by pytest](https://docs.pytest.org/en/7.1.x/explanation/goodpractices.html#choosing-a-test-layout-import-rules). Our tests are still used by OS packagers, these [config lines like this tell Python packaging to include these files](https://github.com/certbot/certbot/blob/34e6b1e74db1f0af21224208cc7a3507d8cbf301/certbot/MANIFEST.in#L7), and if you do something like inspect the [latest Certbot tarball from PyPI](https://files.pythonhosted.org/packages/d3/79/2ed6c08fc864e735221c14a62c5fc269988cb61955fcb24df8bffd0fffd1/certbot-2.3.0.tar.gz), you'll find our tests there. [Other popular Python projects do this as well](https://github.com/pyca/cryptography/blob/a434b7b19dd68202a4352501f4af418a58780403/MANIFEST.in#L17).

I think that quote is otherwise still true though. I'm not sure I'm aware of any modern and popular Python project that doesn't use the structure we currently have (often with an extra `src` directory that contains the application code). As we unfortunately found here, that approach doesn't nicely work for us and our monorepo.

> Is there a problem with doing "run a small script that runs mypy individually on each directory and/or module"?

That should work. The only minor problems I see that make me prefer this approach are:

1. It requires some custom tooling.
2. It is likely to be slower due to the repeated starts and stops of `mypy`, `pylint`, etc.
3. It feels less conventional than throwing our tests back in our package. Putting your test code in your application package is still [a documented and recommended by projects like `pytest` as I also linked above](https://docs.pytest.org/en/7.1.x/explanation/goodpractices.html#tests-as-part-of-application-code) and it used to be the standard with many/some [older but popular Python packages still doing it](https://github.com/pypa/setuptools/tree/9022a215459137d8bd9446d995c0dd159079a2b2/setuptools/tests).

Those reasons personally make me prefer throwing things in `_internal`, but do you have a preference for the approach of using a small, custom script?

**Comment by ohemorange** [comment]
> That's maybe a bit misleading because we do still ship our tests in our packages and I believe we want to continue to do so. 

Ah yes, I definitely assumed from that comment that the debate had been settled the other way, thanks for clarifying.

While I'm a little wary of going against modern convention (how have all these other projects managed to get their tests to work quickly despite this? Why is everyone like that if it has these problems?), faster with less custom tooling does seem worth it. So it's really just the orange flag of doing something in a less-standard way vs. clear and compelling reasons to change it to being inside `_internal`. In which case, unless new information comes to light, I agree that the inside `_internal` strategy seems to make most sense here.

**Comment by bmw** [comment]
Cool. Thanks for thinking about this with me.

> How have all these other projects managed to get their tests to work quickly despite this? Why is everyone like that if it has these problems?

My understanding is the current tooling for Python monorepos is pretty bad. Looking around at the Python ecosystem it's hard for me to find (m)any good examples of them. I picked on `setuptools` for being older, however, that's actually one example of a popular project that has two somewhat separate packages in their repo and their solution was to keep `tests` importable inside their packages.

Leaving the world of open source, my understanding is that for larger Python monorepos, people start using a build system like Bazel or Pants. We could look into that, but it personally feels like overkill to me for us. Before doing that, I'd personally consider moving more of our different components into a single package with optionally installable dependencies depending on what functionality the user needs. That project also personally feels like overkill to me for this particular problem though.
