### ISSUE TITLE
Certbot snap doesn't provide man pages

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7942]
Copied from https://github.com/basak/certbot-snap-build/issues/1#issuecomment-400884529:

> Blocked on https://forum.snapcraft.io/t/support-for-man-pages/2299/13
>
> A workaround might be to provide a command like `certbot.man certbot`. git-ubuntu does something like this. I'm not sure how helpful this would be, though, as it wouldn't be discoverable.

**Comment by samboy** [comment]
Has anyone written a troff man page we can put in `/usr/local/man/man8` or wherever?

**Comment by samboy** [comment]
OK, found it: http://manpages.ubuntu.com/manpages/bionic/en/man1/certbot.1.html

So, I just need to find the raw *roff file for that and put it in `/usr/local/man/man1/`

As an aside, a package manager which can not install man pages is, IMHO, seriously broken. I know it’s 2021, but Stackoverflow is *not* a substitute for a good man page (since the stackoverflow answer may be outdated and no longer work)
