### ISSUE TITLE
Unable to install on Ubuntu 19.04

### ISSUE THREAD

**Issue by kittenswolf** [certbot/certbot#7947]
## My operating system is (include version):
Ubuntu 19.04

## Command I ran
`sudo apt-get install certbot python-certbot-nginx`

## Output
```Reading package lists... Done
Building dependency tree
Reading state information... Done
Package certbot is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'certbot' has no installation candidate
E: Unable to locate package python-certbot-nginx
```

Yes, I ran `apt-get update` and `apt-get upgrade` before trying to install certbot.

**Comment by bmw** [comment]
[Ubuntu 19.04 has reached it's end of life](https://lists.ubuntu.com/archives/ubuntu-announce/2020-January/000253.html), is no longer receiving security updates, and is no longer supported by Certbot.

In order to use Certbot, you'll need to upgrade your OS and after that you can follow the instructions at https://certbot.eff.org/instructions.

**Comment by kittenswolf** [comment]
@bmw Same thing happens when updating to Ubuntu 19.10.
