### ISSUE TITLE
ImportError: cannot import name 'constants' from 'certbot' (/usr/lib/python3/dist-packages/certbot/__init__.py)

### ISSUE THREAD

**Issue by springjools** [certbot/certbot#7960]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
debian 10 (Linux jovian 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
sudo apt install python3-certbot-nginx

## I ran this command and it produced this output:
certbot --version

https://pastebin.com/pA4yF1bs

## Certbot's behavior differed from what I expected because:

Errors. See above.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
https://pastebin.com/Kzg2skEa
## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
Not applicable

**Comment by springjools** [comment]
Btw, I followed this guide: https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-debian-10

The problem is with the nginx plugin.

**Comment by bmw** [comment]
The problem here is you have a mix of packages from different sources. `certbot --version` outputs 1.3.0 on your system while [certbot 0.31.0 is what is available in Debian 10](https://packages.debian.org/buster/certbot) and the version of the nginx plugin in Debian is not compatible with newer versions of Certbot.

Removing Certbot from the other source and installing the package from Debian 10's repos should solve your problem. If you need additional help installing Certbot packages, I recommend posting to https://community.letsencrypt.org where there is a large community of people familiar with the project and server administration who should be able to help you.

**Comment by compumatter** [comment]
installing either **python3-certbot-apache** or **python3-certbot-nginx** causes certbot to not work and throw errors.
uninstalling both works
certbot --version then shows
certbot 1.21.0

**Comment by pallinger** [comment]
There is a quick fix here: 
https://github.com/xiretsa/certbot-haproxy/commit/64fc9b286391b7fbe65362ca499fafb5b93cd580
It works, but it most probably breaks compatibility with old certbot versions.
