### ISSUE TITLE
CentOS 8: failing test due to 1024 bit RSA key in standalone_test.py

### ISSUE THREAD

**Issue by FelixSchwarz** [certbot/certbot#7985]
OpenSSL in RHEL 8/CentOS 8 uses system-wide crypto policies.

`tests/standalone_test.py` uses a 1024 bit key since commit 07abe7a8d68961042ee301039dd4da87306cb1a0 (certbot 1.4) and the test fails because 1024 bit keys are not acceptable by the default crypto policy.

The tests pass if I generate a key with 4096 bit ([python-acme-strong-keys-in-standalone_test.patch](https://github.com/certbot/certbot/files/4614878/python-acme-strong-keys-in-standalone_test.patch.txt)).

I'm not sure what the best course of action is for Fedora EPEL - should I just carry a local patch or would you mind upgrading your keys in the test suite? You might need to handle this as well when you add CentOS 8 machines to your test farm (#7420).

Please note that a `pip`-installed `cryptography` module might hide the problem because the binary wheels contain a statically compiled OpenSSL which does not care about the system-wide policy.

Just for reference the default OpenSSL config in CentOS 8:

    $ cat /etc/crypto-policies/back-ends/openssl.config
    @SECLEVEL=2:kEECDH:kRSA:kEDH:kPSK:kDHEPSK:kECDHEPSK:-aDSS:-3DES:!DES:!RC4:!RC2:!IDEA:-SEED:!eNULL:!aNULL:!MD5:-SHA384:-CAMELLIA:-ARIA:-AESCCM8

**Comment by alexzorin** [comment]
There was some chat earlier about this when it happened with Debian sid (https://opensource.eff.org/eff-open-source/pl/o4aq7kkdjjn8zd1r9iy1trwnrh):

@bmw mentioned:

>OK. We'll fix this in our next release and may do a point release for it because I doubt you'll be the only one hitting issues.
>I suspect Fedora, arch, etc. will too.

**Comment by FelixSchwarz** [comment]
Thank you for the link - unfortunately I don't have an account for the Mattermost instance. Is it possible for me to get access there?

**Comment by alexzorin** [comment]
Oh yeah, the invite/registration link is on this page: https://certbot.eff.org/contribute

**Comment by bmw** [comment]
Sorry for not pinging you on this earlier @FelixSchwarz. As you may have seen in my Mattermost messages, I planned to write this up last week and was going to @ mention you when doing so, but it's been a bit hectic lately and I haven't had a chance to write it up yet.

This problem will be fixed in our next release. If it's easy for you to patch it yourself for now, that'd be great, but if it's a hassle, we can probably put out a point release to fix the problem before our 1.5 release in the beginning of June.

**Comment by bmw** [comment]
I rewrote this issue at https://github.com/certbot/certbot/issues/7988 so I'm going to close this in favor of that.

@FelixSchwarz, please let me know either here or there if:

1. You'd like us to do an early release. Especially due to some of the difficulties with us doing our normal release process during the lockdown for COVID-19, it'll take us 2-3 hours of extra work to do an early release, but I'm happy to do that if it saves you a significant headache.
2. I currently think only the smaller diff I wrote in that issue is required instead of the patch you provided here. The other uses of 1024 bit (or in many other places 512 bit) keys predate 1.4.0 so unless something very recently changed with OpenSSL on CentOS 8, I don't think the other changes are required, but if I'm wrong please correct me!

**Comment by FelixSchwarz** [comment]
just a quick response as I'm a bit short on time right now: Thanks for the reply. No need for a point release. I think I'll just disable that one test just like debian does.
