### ISSUE TITLE
certbot-auto: E: Package 'python-virtualenv' has no installation candidate

### ISSUE THREAD

**Issue by x011** [certbot/certbot#8021]
`certbot-auto` -  broken installation on Ubuntu 20.04

```
Note, selecting 'python-is-python2' instead of 'python'
Note, selecting 'python-dev-is-python2' instead of 'python-dev'
Package python-virtualenv is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-virtualenv' has no installation candidate
```

**Comment by m0namon** [comment]
Hi! We don't recommend using `certbot-auto` on Ubuntu. See https://certbot.eff.org/lets-encrypt/ubuntufocal-other for more info.

To help you troubleshoot your installation, I recommend heading to the [Let's Encrypt Community Forums](https://community.letsencrypt.org/), where there's lots of people who are familiar with the project. You'll get faster help there.

If it turns out there's a bug in your Certbot installation, feel free to file a new issue here using the issue template. Closing for the time being.

**Comment by brinsleyparagao** [comment]
In debian 10 today [16-12-20202] this error persist

Starting create Let's Encrypt SSL Certificate...
Skipping bootstrap because certbot-auto is deprecated on this system.
Your system is not supported by certbot-auto anymore.
Certbot cannot be installed.
Please visit https://certbot.eff.org/ to check for other alternatives.
Error: Create Let's Encrypt SSL Certificate failed
