### ISSUE TITLE
Windows Binaries/Installer Checksum

### ISSUE THREAD

**Issue by silverkorn** [certbot/certbot#8123]
Greetings!

I would like to add `certbot` to [Scoop](https://scoop.sh/) within their extra bucket and it needs (or at least strongly recommend) to have a checksum to compare with.

Is there a place where we can find a MD5 or SHA256 checksum of the `certbot-beta-installer-win32.exe` releases?
Otherwise, is it something that could be provided in the future?

Thank you!

**Comment by bmw** [comment]
Thanks for your interest in doing this!

We don't have a precomputed checksum stored anywhere, but this is something we could add in the future. I'd imagine us accomplishing this by placing a SHA256 checksum in the [GitHub release](https://github.com/certbot/certbot/releases) along with the executable.

Slightly off topic, but if you're going to be maintaining the Scoop package, we plan to make Certbot on Windows automatically update itself in the near future which may affect how you configure the package. Work on that can be tracked at https://github.com/certbot/certbot/pull/7539.

@adferrand, if you have any opinions on this, I'd be interested to hear them.

**Comment by adferrand** [comment]
Yes the checksum file published alongside with the installer is something I wanted to add nonetheless. One more argument to add it sooner than later.

Indeed in the scope of scoop, the installer should not install the auto update task in the Scheduler and let the packaging system handle that. Scoop can do it by templating the Github release download URL with the version semantic. I believe it will be globally the same for most other alternate packaging systems. One simple way to disable the embedded auto update logic is to add an optional flag in the NSIS installer config to skip this part during installation.

As a final note, currently the installer is not signed. I think this will need some specific config in the Scoop manifest to handle that nicely. It is temporary however, since we plan to sign the installer in the near future. This work is tracked on #8046.

**Comment by silverkorn** [comment]
That's good news!
I will wait for those to be implemented.
Thanks!

**Comment by silverkorn** [comment]
Installer's checksum(s) are still not available.
+ Both mentioned issues/PR are still opened: #7539 & #8046.
