### ISSUE TITLE
Redirect https://letsencrypt.readthedocs.org to https://certbot.eff.org/docs/ (bis)

### ISSUE THREAD

**Issue by tdelmas** [certbot/certbot#8155]
The documentation used to be hosted on https://letsencrypt.readthedocs.org but now is https://certbot.eff.org/docs/ (cf #7757)

Some code still refers to the old url, for example https://github.com/certbot/certbot/blob/master/letsencrypt-auto-source/letsencrypt-auto#L933

There is still a large number of website with link pointing to the old url, and it's a best-practice to avoid 404 for old urls. Not only because of the risk of cybersquatting, but also to help lost users (for example, reading on threads on a forum...).

Related: https://community.letsencrypt.org/t/https-letsencrypt-readthedocs-io-gone/128660

The redirect was in place, but now it's not anymore... #6444

![image](https://user-images.githubusercontent.com/1955774/87830998-9c314600-c882-11ea-86ff-934dda9ef192.png)

**Comment by bmw** [comment]
We tried this but was never able to make it work consistently. See https://github.com/certbot/certbot/issues/6728.

While I agree with you in theory that breaking links is bad, after spending hours trying to fix it, we decided there were more effective uses of our time and moved on, choosing to shut the project down rather than continue to serve incorrect documentation from the URL.

If someone is able to figure out how to make it work, we can probably set it up again, but we're really not able to spend any more time debugging this ourselves with the resources we have right now.

**Comment by adferrand** [comment]
@bmw in https://github.com/certbot/certbot/issues/6728#issuecomment-460468585 you explained that the redirects set following https://docs.readthedocs.io/en/latest/user-defined-redirects.html works only for pages that do not exist in readthedoc.

Would it be possible to have an empty `letsencrypt.readthedoc.io` site, and set the redirect to make it work for any URL? This is the same kind of implementation that is suggested here https://github.com/readthedocs/readthedocs.org/issues/2267#issuecomment-438741041 to offer inconditionnal redirects on Readthedoc.

**Comment by bmw** [comment]
Maybe, but I think you need a valid Sphinx setup whose build results in no files and then readthedocs needs to not complain about this and still host your project. If the build on readthedocs fails, I don't think this approach will work. Also notice that that readthedocs issue in general is tracking how to solve the same problem we have here and it remains open.

I'll admit that we shut down the site a little sloppily as evidenced by the [link to the build status](https://github.com/certbot/certbot/pull/7757) and [a couple links in our FAQ](https://github.com/certbot/website/pull/535) which were removed earlier this year and output in [an obscure error message in certbot-auto](https://github.com/certbot/certbot/blob/270b5535e24fd3dab4c05fa8929adca8117942f1/letsencrypt-auto-source/letsencrypt-auto.template#L455) and a few code comments which still exist.

I looked through git history though and those are all of the references to the site we've had on our end since 2016. While it'd be nice to keep the redirect up indefinitely or maybe just a longer period of time, we renamed the project to Certbot over 4 years ago now and removed the vast majority of the links to the site then. Because of that and the fact that readthedocs doesn't seem to officially support shutting down or migrating the site in another way, I personally don't think it's a major problem for the site to disappear now.

**Comment by tdelmas** [comment]
> I personally don't think it's a major problem for the site to disappear now.

I agree. The main problem I see is old (+3year) posts on https://community.letsencrypt.org/search?q=%22https%3A%2F%2Fletsencrypt.readthedocs.org%22%20order%3Alatest_topic so I think it's acceptable now.

> in an obscure error message in certbot-auto 

Some people do hit that error so the message should be updated: https://community.letsencrypt.org/t/help-needed-to-run-certbot-in-busybox/107134

**Comment by bmw** [comment]
Thanks for pointing out that some people hit this case.

This was fixed in https://github.com/certbot/certbot/pull/8168 and will be included in our next scheduled release.
