### ISSUE TITLE
Issues installing certbot snap if DNS plugin snap already installed

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#8182]
Probably nobody will hit this in real life, but if you do something like:

    snap install --classic --edge certbot
    snap set certbot trust-plugin-with-root=ok
    snap install --edge certbot-dns-digitalocean
    snap remove certbot
    snap install --classic --edge certbot

The last command produces instructions which do not make much sense:

    $ sudo snap install --classic --edge certbot
    error: cannot perform the following tasks:
    - Run hook prepare-plug-plugin of snap "certbot" (run hook "prepare-plug-plugin":
    -----
    Only connect this interface if you trust the plugin author to have root on the system
    Run `snap set certbot trust-plugin-with-root=ok` to acknowledge this and then run this command again to perform the connection
    -----)

It seems like the install hook is assuming that the snap being installed is a plugin.

If this is not convenient to fix in the install hook I think it's probably fine to just close this.

**Comment by bmw** [comment]
Thanks for writing this up Alex. This certainly isn't ideal.

What's going on here is the [content interface](https://snapcraft.io/docs/content-interface) used between the two snaps tries to automatically connect because the snaps are both published by us. When a connection is attempted to be made, [this hook](https://github.com/certbot/certbot/blob/332def46dad245421968fd030f8093aa0ad486ec/snap/hooks/prepare-plug-plugin) is run which we're required to have following [conversations with the snap store maintainers](https://forum.snapcraft.io/t/certbot-request-for-classic-snap-approval/6240/19).

I'm trying to learn more about how these automatic connections can be controlled at https://forum.snapcraft.io/t/how-do-you-configure-multiple-slots-to-auto-connect-to-a-single-plug/19172/, but I think we have somewhat limited control over the need for this hook and the snaps trying to automatically connect.

I personally think we probably won't prioritize fixing this ourselves unless a significant amount of people start hitting it, but the best solution I have in mind right now is seeing if the snap store maintainers are OK with our own snaps connecting without running `snap set certbot trust-plugin-with-root=ok` and finding someway to check for this case in the hook I linked above. This should solve the problem for ourselves and the problem shouldn't exist if anyone writes a 3rd party Certbot plugin snap because it won't be published by us so `snapd` won't try to automatically connect the two snaps. Users of 3rd party plugins have to manually run a `snap connect` command after Certbot is installed and they can set `trust-plugin-with-root=ok` before doing that.

**Comment by jmooo** [comment]
Running into this on Ubuntu 20.04 w/ certbot 1.7.0 snaps and `certbot-dns-cloudflare`

**Comment by adist** [comment]
is there any temporary solution for this? 

its happend in my Ubuntu 18.04...

**Comment by alexzorin** [comment]
As long as you do everything in order, you shouldn't run into this in a normal situation.

Starting from a blank state:

    sudo snap remove certbot certbot-dns-cloudflare

Follow the instructions according to https://certbot.eff.org/lets-encrypt/snap-other:

    sudo snap install --beta --classic certbot
    sudo snap set certbot trust-plugin-with-root=ok
    sudo snap install --beta certbot-dns-cloudflare
    sudo snap connect certbot:plugin certbot-dns-cloudflare

If you are doing exactly that and you're still running into issues, then please post back with the exact commands you are running and what output you are getting.

**Comment by adist** [comment]
thanks @alexzorin thats work for me.. (y) 

> As long as you do everything in order, you shouldn't run into this in a normal situation.
> 
> Starting from a blank state (make sure you remove _all_ the DNS plugins):
> 
> ```
> sudo snap remove certbot certbot-dns-cloudflare
> ```
> 
> Follow the instructions according to https://certbot.eff.org/lets-encrypt/snap-other:
> 
> ```
> sudo snap install --beta --classic certbot
> sudo snap set certbot trust-plugin-with-root=ok
> sudo snap install --beta certbot-dns-cloudflare
> sudo snap connect certbot:plugin certbot-dns-cloudflare
> ```
> 
> If you are doing exactly that and you're still running into issues, then please post back with the exact commands you are running and what output you are getting.

**Comment by bmw** [comment]
Since at least two users hit this in the less than a month that our DNS plugins have been out, I think we may want to look in a fix here.

The general design I have in mind is described in https://github.com/certbot/certbot/issues/8182#issuecomment-666584165 and I think the first step is seeing if there is a way to reliably identify the connecting snap in our hook that cannot be spoofed.

I'll also note that we probably want to make sure to continue to unset `trust-plugin-with-root=ok` after installing one of our own externally snapped plugins. Otherwise users that follow our current instructions will leave the Certbot snap open to be connected to by another plugin without setting `trust-plugin-with-root=ok`

**Comment by ohemorange** [comment]
> the first step is seeing if there is a way to reliably identify the connecting snap in our hook that cannot be spoofed.

`snap info certbot` has a `publisher` line that says `publisher: Certbot Project (certbot-eff✓)`. So the metadata is there; the thing to check is that we have the permissions to access it at the appropriate point in execution. We don't want to use anything self-reported like we do for versions, because that's easier to spoof.

**Comment by ohemorange** [comment]
> seeing if the snap store maintainers are OK with our own snaps connecting without running snap set certbot trust-plugin-with-root=ok

We haven't checked with the maintainers about this yet, right?

**Comment by bmw** [comment]
We have not and we definitely should do that before making any changes here. They also may be able to help us to find a good way to check the metadata on the plugin trying to connect.

**Comment by ohemorange** [comment]
Actually, I bet that won't be a problem, since we're doing the check from within the certbot snap, which has classic containment and makes things much easier.

**Comment by ohemorange** [comment]
GREAT news: the certbot snap can run `snap info SNAPNAME` no problem. now to figure out how to tell which snap is the one being installed...

**Comment by ohemorange** [comment]
You know, alternatively, we could just update the error message.

**Comment by ohemorange** [comment]
The `env` doesn't seem to have any info about the other snap being connected to.

**Comment by ohemorange** [comment]
Hm, I wonder if we can access the command that launched this. I don't think we'll be able to get the info we want from `snap` or `snapctl`; they even hide the name of the interface on the other side, you're really not meant to be accessing this.

**Comment by alexzorin** [comment]
Could we fix this by having both `prepare-slot` and `prepare-plug` hooks. Currently we only have the latter.

In both hooks, pass silently if `$SNAP_NAME` is `certbot`. Otherwise, perform the authentication flow. Exactly one of the hooks is guaranteed to run.

That way, we don't run into the original scenario. It's strictly worse than @bmw's idea. I'm throwing this out there in case there's no other solution.

**Comment by ohemorange** [comment]
I don't think I understand this proposal. How could we differentiate between one of our plugins and a third-party plugin?

**Comment by alexzorin** [comment]
Sorry, I meant if at the end of the day, it's not possible to identify the other snap, full stop.

The idea was to ask the user to set `trust-plugin-with-root` on either the plug or slot side, depending on what the already-installed snap is. (And make the same change when checking the attribute).

That way, the user can still resolve this problem of the autoconnection blocking the installation of the snap.

**Comment by ohemorange** [comment]
> Sorry, I meant if at the end of the day, it's not possible to identify the other snap in a non-spoofable way, full stop.

Oh, I see what you mean now. So, I think whether slot or plug, we want the check to be done by the `certbot` snap when certbot tries to connect with any other snap; if we put the check in the third party plugin, there's nothing to stop other plugin authors from not putting that check in.

**Comment by ohemorange** [comment]
I think what you have above, telling the user to remove the plugin and then redo the whole install flow, is the best way to resolve it barring non-spoofable detection or snapcraft maintainer intervention.

**Comment by alexzorin** [comment]
@bmw are you onboard with that suggestion, to tell the user to remove the plugins first? It seems like the most achievable thing right now.

Otherwise, I think this might require reopening the conversation with the jdstrand/snap maintainers.

**Comment by bmw** [comment]
I personally think that's fine as an easy improvement we can make, however, if people continue to hit this issue and complain about the awkwardness of removing and reinstalling everything, I think we should try something else here.

**Comment by ohemorange** [comment]
@bmw, do you still think that even if there is no way to reliably identify the connecting snap in our hook that cannot be spoofed?

**Comment by bmw** [comment]
If reliably identifying the connecting snap in our hook in a way that cannot be spoofed doesn't seem feasible, then I think just improving the error message here is a good idea and what we should do for now.

I do still think though that if we see continue to see users regularly complaining about this issue, we should try to do something else to help. That may mean coming up with a different solution if the one I initially proposed doesn't work (without changes to `snapd`).

**Comment by ohemorange** [comment]
I took a stab at improving the error message [here](https://github.com/certbot/certbot/pull/8338).

**Comment by bmw** [comment]
Thanks!

With that PR, I personally think we shouldn't worry about this anymore unless people continue to complain about the problem once the fix is released. Because of that, I'm closing this issue for now, but if someone else on the Certbot team disagrees, you're welcome to reopen the issue.

**Comment by DeamonMV** [comment]
Today I had something similar

```
# snap install certbot-dns-cloudflare
error: cannot perform the following tasks:
- Setup snap "certbot-dns-cloudflare" (373) security profiles (cannot setup apparmor for snap "certbot-dns-cloudflare": cannot unload apparmor profile: exit status 2
apparmor_parser output:
File snap-update-ns.certbot-dns-cloudflare not found, skipping...
File snap.certbot-dns-cloudflare.hook.post-refresh not found, skipping...
)
- Setup snap "certbot-dns-cloudflare" (373) security profiles (cannot unload apparmor profile: exit status 2
apparmor_parser output:
File snap-update-ns.certbot-dns-cloudflare not found, skipping...
File snap.certbot-dns-cloudflare.hook.post-refresh not found, skipping...
)
- Run hook prepare-plug-plugin of snap "certbot" (run hook "prepare-plug-plugin": error: error running snapctl: Unknown command `unset'. Please specify one command of: get, restart, services, set, start or stop)
```

Problem resolved after snap was updated.

```
# snap --version
snap    2.37.4-1+b1
snapd   2.37.4-1+b1
series  16
debian  10
kernel  5.4.78-2-pve
# snap install core
2020-12-28T10:29:11+01:00 INFO Waiting for restart...
core 16-2.48 from Canonical✓ installed
Channel latest/stable for core is closed; temporarily forwarding to stable.
# snap --version
snap    2.48
snapd   2.48
series  16
debian  10
kernel  5.4.78-2-pve
```

ENV: Deabin 10 + proxmox

**Comment by hibouambigu** [comment]
Just happened to me, too. Glad I found this issue.

In my case, I don't usually use snaps but had to after realising the default package manager certbot-dns-cloudflare doesn't support Cloudflare APIv4 tokens.

I tried installing just the dns-cloudflare snap first, so that's how I ran into this issue.

**Comment by ivanvmoreno** [comment]
> Today I had something similar
> 
> ```
> # snap install certbot-dns-cloudflare
> error: cannot perform the following tasks:
> - Setup snap "certbot-dns-cloudflare" (373) security profiles (cannot setup apparmor for snap "certbot-dns-cloudflare": cannot unload apparmor profile: exit status 2
> apparmor_parser output:
> File snap-update-ns.certbot-dns-cloudflare not found, skipping...
> File snap.certbot-dns-cloudflare.hook.post-refresh not found, skipping...
> )
> - Setup snap "certbot-dns-cloudflare" (373) security profiles (cannot unload apparmor profile: exit status 2
> apparmor_parser output:
> File snap-update-ns.certbot-dns-cloudflare not found, skipping...
> File snap.certbot-dns-cloudflare.hook.post-refresh not found, skipping...
> )
> - Run hook prepare-plug-plugin of snap "certbot" (run hook "prepare-plug-plugin": error: error running snapctl: Unknown command `unset'. Please specify one command of: get, restart, services, set, start or stop)
> ```
> 
> Problem resolved after snap was updated.
> 
> ```
> # snap --version
> snap    2.37.4-1+b1
> snapd   2.37.4-1+b1
> series  16
> debian  10
> kernel  5.4.78-2-pve
> # snap install core
> 2020-12-28T10:29:11+01:00 INFO Waiting for restart...
> core 16-2.48 from Canonical✓ installed
> Channel latest/stable for core is closed; temporarily forwarding to stable.
> # snap --version
> snap    2.48
> snapd   2.48
> series  16
> debian  10
> kernel  5.4.78-2-pve
> ```
> 
> ENV: Deabin 10 + proxmox

Had the exact same issue today on Debian 10. After tinkering with the AppArmor profiles, just updating snap with `sudo snap install core` solved the issue.
