### ISSUE TITLE
Stop printing nginx: [error] invalid PID number "" in "/run/nginx.pid"

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8231]
If you use Certbot to obtain a certificate using the nginx plugin and nginx is initially off, you should see output like:
```
nginx: [error] invalid PID number "" in "/run/nginx.pid"
```
As part of our results from user testing, we should remove this output.

This should be verified, but my understanding here is this comes from [this call to `nginx -s reload`](https://github.com/certbot/certbot/blob/2a047eb526ee02d4bb3bb3668260ac6d481b99d3/certbot-nginx/certbot_nginx/_internal/configurator.py#L1178-L1179) where stdout/stderr isn't captured. This command fails and then we try starting nginx which works.

If this understanding is correct, I think we should capture the output from the first command and either:

1. Log it at the debug level.
2. Hold it in a local variable to be logged/raised in an exception if the command starting nginx also fails.

**Comment by alexzorin** [comment]
I think that just logging it will be sufficient. 

I'm having a hard time imagining a situation where displaying the output from both commands would be useful. Either:

- Both commands will show the same error (e.g. if nginx.conf is bad), or
- The first command's output will be a red herring (e.g. pidfile missing, but who cares, the real problem is that it won't start at all)
