### ISSUE TITLE
Audit Certbot error output

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8233]
Under the "Open design questions" section of https://docs.google.com/document/d/1aKnQYEzCrZgYX-iuE-ErOdIKERUuLmZSX_BDb7d0M6I/edit?usp=sharing, there are number of cases of Certbot error output that have not been looked at. We should look at these cases and suggest improvements that we can make to Certbot's output.

**Comment by alexzorin** [comment]
Can't modify the doc but left [some thoughts here](https://gist.github.com/alexzorin/3fbc218b99c180206d95b13cf529b8bf).

Removing *IMPORTANT NOTES* seems problematic for renewal, as long scrollback may be unavoidable if there are a few certificates, especially so if they are all failing at the same time. Didn't see an obvious solution.

**Comment by ohemorange** [comment]
https://docs.google.com/document/d/1RcBPHGkFiY4vospMVwlAG1mRqetWNIi-9Ei2ArCywfk/edit#

**Comment by bmw** [comment]
Can this issue be closed or is these still discussion or further work needed here?

**Comment by alexzorin** [comment]
We're iterating on adjusting the error output, but it's not yet clear what to do in some concrete cases. It makes sense to me to keep this open, though it might help to track specific issues.

**Comment by ohemorange** [comment]
This issue is also about auditing error output specifically; the doc I posted above has some errors, but that's not the focus. That's on me for not specifying, I just wanted to have the link.

There's a couple of error-related suggestions in the main document that I think are best saved here:

* If we fail to deploy, tell the user to run `certbot install --cert-name foo.bar` after fixing the problem.
* If we fail to get the certificate, we should print an error message the user can google along with “certbot” that will get them to the community forums or stackoverflow if someone’s had that problem before. (This is more of a general suggestion than a specific change.)

**Comment by alexzorin** [comment]
This is done or folded into a more specific issue like #8233.
