### ISSUE TITLE
Fix "stack smashing" problem in the Certbot snap

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8245]
A couple times now I've seen people report seeing the following output from the Certbot snap:
```
*** stack smashing detected ***: <unknown> terminated
```
I just reproduced this myself on a clean CentOS 8 DigitalOcean droplet (with `httpd` installed) after following the [snapd installation instructions](https://snapcraft.io/docs/installing-snap-on-centos), installing the Certbot snap, and running (almost) any command such as `certbot plugins` or `certbot --version`.

What's going on here? Is there a problem in the snap that needs to be fixed? I think we should take the time to understand the root cause here and at a minimum squelch this output, but there may be a more significant problem that needs to be fixed here.

**Comment by alexzorin** [comment]
I've narrowed this down to:

https://github.com/certbot/certbot/blob/e8518bf206020bc0163f7db33eb7b31126bac6a2/certbot.wrapper#L45

Reproduction is your DigitalOcean droplet plus running that `sed` *inside* a `snap run --shell certbot`:

    [root@centos-s-1vcpu-2gb-sgp1-01 ~]# snap connections certbot > conns.txt
    [root@centos-s-1vcpu-2gb-sgp1-01 ~]# sed -n '2,$p' < conns.txt
    *** stack smashing detected ***: <unknown> terminated
    Aborted (core dumped)

Here's the backtrace:

    0x00007ffff761570f in raise () from /lib64/libc.so.6
    (gdb) bt
    #0  0x00007ffff761570f in raise () from /lib64/libc.so.6
    #1  0x00007ffff75ffb25 in abort () from /lib64/libc.so.6
    #2  0x00007ffff7658897 in __libc_message () from /lib64/libc.so.6
    #3  0x00007ffff76eb905 in __fortify_fail_abort () from /lib64/libc.so.6
    #4  0x00007ffff76eb8b8 in __stack_chk_fail () from /lib64/libc.so.6
    #5  0x00007ffff7f49118 in __pthread_tunables_init () from /snap/certbot/500/usr/lib/x86_64-linux-gnu/../../../lib/x86_64-linux-gnu/libpthread.so.0
    #6  0x00007ffff7f3a0d4 in __pthread_initialize_minimal () from /snap/certbot/500/usr/lib/x86_64-linux-gnu/../../../lib/x86_64-linux-gnu/libpthread.so.0
    #7  0x00007ffff7f3900d in _init () from /snap/certbot/500/usr/lib/x86_64-linux-gnu/../../../lib/x86_64-linux-gnu/libpthread.so.0
    #8  0x00007ffff7dd44d8 in ?? () from /lib64/ld-linux-x86-64.so.2
    #9  0x00007ffff7de3e8a in call_init.part () from /lib64/ld-linux-x86-64.so.2
    #10 0x00007ffff7de404e in _dl_init () from /lib64/ld-linux-x86-64.so.2
    #11 0x00007ffff7dd508a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
    #12 0x0000000000000001 in ?? ()
    #13 0x00007fffffffe252 in ?? ()
    #14 0x0000000000000000 in ?? ()

I guess the root cause is that we are being messed about by `LD_PRELOAD_PATH` again - `libpthread` should be coming from the host:

    [root@centos-s-1vcpu-2gb-sgp1-01 ~]# ldd /usr/bin/sed
            linux-vdso.so.1 (0x00007ffd72f72000)
            libacl.so.1 => /lib64/libacl.so.1 (0x00007fb749ee9000)
            libselinux.so.1 => /lib64/libselinux.so.1 (0x00007fb749cbe000)
            libc.so.6 => /lib64/libc.so.6 (0x00007fb7498fc000)
            libattr.so.1 => /lib64/libattr.so.1 (0x00007fb7496f6000)
            libpcre2-8.so.0 => /snap/certbot/500/usr/lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007fb74a49d000)
            libdl.so.2 => /lib64/libdl.so.2 (0x00007fb7494f2000)
            /lib64/ld-linux-x86-64.so.2 (0x00007fb74a30f000)
            libpthread.so.0 => /snap/certbot/500/usr/lib/x86_64-linux-gnu/../../../lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb74a472000)

On my Ubuntu 20.04 machine, `pthread` comes from the host.

**Comment by alexzorin** [comment]
Could we potentially just move:

https://github.com/certbot/certbot/blob/e8518bf206020bc0163f7db33eb7b31126bac6a2/certbot.wrapper#L30-L32

to be directly above the exec call:

https://github.com/certbot/certbot/blob/e8518bf206020bc0163f7db33eb7b31126bac6a2/certbot.wrapper#L47

They don't seem to have any side effects until then.

**Comment by bmw** [comment]
Thanks for digging into this Alex!

I think something like that is what we should do, however, I wonder if we actually want different environment variables for different parts of the problematic line you found. For instance, while I'm not 100% sure, I suspect the `snap connections certbot` command needs to be run on the host, but I wonder if the rest of that UNIX pipeline shouldn't be using executables found within the snap. They may not be there now, but I think making sure they are installed and using them would make things more reliable.

If we did that, then I think we'd want to set these variables after calling `snap connections certbot` but before the rest of the commands.

What do you think?

(Part of me now wonders what shell is being used to execute this script too...)

**Comment by alexzorin** [comment]
Yes, agreed on all points. 

I will give this a short try (if I can get the build environment to work locally, didn't go so great last time).

**Comment by alexzorin** [comment]
Wrote a fix for this at #8249, but I'm nervous about `certbot.wrapper`'s reliance on the the output of `snap connections`. 

As we do not control the version of `snapd` on the host, there is a risk that the CLI gets tweaked and breaks the parsing.

Could we instead use the stable API provided at `unix:///run/snapd.socket/v2/connections?snap=certbot`? Consume it via a small Python program, or a combination of `curl + jq`?

Maybe something for another issue.

**Comment by bmw** [comment]
> if I can get the build environment to work locally, didn't go so great last time

I'm happy to help with this if you still have issues. If you haven't seen it, our best documentation for building snaps locally can be found at https://github.com/certbot/certbot/blob/d62d853ea4c03676f1a10248d01b91aa61eaec3e/tools/snap/README.md#use-testing-and-development.

I created https://github.com/certbot/certbot/issues/8250 to talk about the output from `snap`. Thanks for flagging that issue.

**Comment by bmw** [comment]
With the current plan being for us to delay our 1.8.0 release for a week (see Mattermost), I'm moving this issue to the 1.8.0 milestone. If we don't finish it in time, that's fine, but I think we should try to include this change if we can.

Us printing output about stack smashing isn't great and I suspect this breaks externally snapped plugins which would explain https://github.com/certbot/certbot/issues/8235/.

**Comment by alexzorin** [comment]
@bmw do you recall why it was necessary to modify `LD_LIBRARY_PATH` in #8230?

https://github.com/certbot/certbot/blob/8c3c55f8c52388ff8ab0182c5f1e630c486486a3/certbot.wrapper#L31

I've learned that, for classic snaps, snapcraft patches [rpath](https://en.wikipedia.org/wiki/Rpath) in ELF files (e.g. `libaugeas0.so`) precisely so that packagers can avoid the resorting to `LD_LIBRARY_PATH`: <sup>though it'd be nice if it actually said so in the docs</sup>

    $ readelf -d /snap/certbot/current/usr/lib/x86_64-linux-gnu/libaugeas.so.0

    Dynamic section at offset 0x63000 contains 33 entries:
      Tag        Type                         Name/Value
    0x000000000000000f (RPATH)              Library rpath: [$ORIGIN/../../../lib/x86_64-linux-gnu:$ORIGIN]

If we can avoid using `LD_LIBRARY_PATH` entirely, I think we will end up with correct linker behavior and ARM will still work.

I have updated #8249 with all of the changes related to this crash, #8250 and #8251. I was able to build it for amd64 and armhf (with legacy-mode `setuptools` :roll_eyes:). With those builds, I was able to successfully issue certificates via the Apache plugin on a CentOS 8 droplet and a Raspberry Pi 4.

**Comment by bmw** [comment]
Interesting! I didn't add the modification of `LD_LIBRARY_PATH` in #8230. I just moved it inside of `certbot.wrapper` and fixed its value so it is correct for architectures other than x86_64.

The original addition of `LD_LIBRARY_PATH` came from https://github.com/basak/certbot-snap-build who built the Certbot snap as a proof of concept for us. I would check the git history and if that's not informative, ask rbasak in our public Mattermost/IRC channel to see if they remember. Robie is quite friendly, but I can help ask them about this if you like.

If all ELF files in the snap such as `libaugeas`, `python`, any other shell utilities we use like `sed` or `curl`, etc. are properly modified to not require `LD_LIBRARY_PATH` to be set, I think it can be removed. (There is some very minor potential value in that Python will fallback to using it if it cannot load shared libraries through other means as discussed in https://github.com/certbot/certbot/issues/8229, but I don't think we should be letting the Certbot snap use that functionality to begin with since we cannot control what is found on the host.)

#8249 in general looks very good! Thanks for looking into all of these issues. I really would like to fix this particular issue (and maybe https://github.com/certbot/certbot/issues/8251) for our release on Tuesday though and all EFF employees are on vacation this Friday and Monday. Before double checking things like if we need to be setting `LD_LIBRARY_PATH`, what do you think about making a conservative version of that PR that just fixes this issue (and maybe https://github.com/certbot/certbot/issues/8251) for us to quickly review? All of your work in #8249 may end up landing before the release on Tuesday anyway, but I personally will experience less anxiety once this issue (and maybe https://github.com/certbot/certbot/issues/8251) are resolved in `master`.

**Comment by alexzorin** [comment]
>The original addition of LD_LIBRARY_PATH came from https://github.com/basak/certbot-snap-build who built the Certbot snap as a proof of concept for us

Ah, I missed that, thanks. It seems that @adferrand originally added that part in https://github.com/basak/certbot-snap-build/commit/48e640e1a2353476ba8417e6562a031f86838735.  

At the time, the project was not using the `python-augeas` fork, so it made sense to use `LD_LIBRARY_PATH`. But now that we load `libaugeas.so.0` by explicit path and the relevant rpaths are patched, I do not think we need `LD_PRELOAD_PATH` any longer. Adrien does that sound right to you?

>Before double checking things like if we need to be setting LD_LIBRARY_PATH, what do you think about making a conservative version of that PR that just fixes this issue (and maybe #8251) for us to quickly review?

I'm not sure what a conservative PR looks like. My initial attempt https://github.com/certbot/certbot/pull/8249/commits/9b3b161d82fdacbbebecac37da9c01793689e61d turned out to only work by coincedence - much like the released stable snap today. The loader behavior was not still not correct in every environment.

I can kick the `snap connections`→`curl` and `bash`→`sh` changes to another PR, but `LD_PRELOAD_PATH` seems crucial to fix *this* issue.

**Comment by adferrand** [comment]
Yes I edited `LD_LIBRARY_PATH` in the early days of the snap, because at that time the snap would just search for the `libaugeas` library exclusively on the host without it. The fork of `python-augeas` was not sufficient on its own.

Now if the library search mechanism is patched right during the build, it is completely ok for me. Anyway it is quite simple to check if it worked: if the snap is able to instrumentate apache without `libaugeas` installed on the host, then it is working.

What makes snapcraft patching the library ? Because it is set in the `stage-packages` ?

The separation into three PRs looks good to me, with a top priority on reviewing and merging operations related to `LD_LIBRARY_PATH`. Anyway I honestly think that as a unified PR or with three of them, everything will be merged by tomorrow.

**Comment by alexzorin** [comment]
>What makes snapcraft patching the library ? Because it is set in the stage-packages ?

I believe it is the `priming` stage. I could find scarce documentation on it besides a TINY mention on https://snapcraft.io/docs/parts-lifecycle and reading `snapcraft` sources.

**Comment by bmw** [comment]
> My initial attempt 9b3b161 turned out to only work by coincidence - much like the released snap today. The loader behavior was still not correct in every environment.

I believe you, but I'd be interested to hear why your initial attempt doesn't work. It's not immediately clear to me why it does not.

After the further digging and discussion, I think just removing `LD_LIBRARY_PATH` is fine. Thanks for jumping on that. I personally think making a PR just for this piece makes sense.

Decoupling the `snap connections`→`curl` and `bash`→`sh` changes might be hard. I have some questions about the socket approach at https://github.com/certbot/certbot/issues/8250#issuecomment-685972929 and have a suggestion I think will work and personally like better in the long term for relying on `/bin/bash` at https://github.com/certbot/certbot/issues/8251#issuecomment-685970461, but I'm fine with us using `/bin/sh` for now if we've removed all bashism.

**Comment by alexzorin** [comment]
>I believe you, but I'd be interested to hear why your initial attempt doesn't work. It's not immediately clear to me why it does not.

Despite rpath patching, `LD_LiBRARY_PATH` takes precedence. This means that the runtime dependencies of libaugeas and gawk still ended up as a (somewhat random) mix of snapped and host libraries. 

Maybe it does not crash, but that's the same thing that caused this issue. On Debian, `sed` loading the `$SNAP/usr/lib/` version of `libpthread-2.31.so` just happened to work. On CentOS though, we got the "stack smashing". Better to avoid a game of whack-a-mole.

>After the further digging and discussion, I think just removing LD_LIBRARY_PATH is fine. Thanks for jumping on that. I personally think making a PR just for this piece makes sense.

OK, I'll work on this.

**Comment by bmw** [comment]
Thanks a lot! That raised a couple new questions for me though.

> Despite rpath patching, `LD_LiBRARY_PATH` takes precedence. This means that the runtime dependencies of libaugeas and gawk still ended up as a (somewhat random) mix of snapped and host libraries.

Does that mean that the Certbot snap will break if the user has `LD_LIBRARY_PATH` set in their environment? Does us prepending our own path to it prevent that? Unless we're running code not contained in the snap with a modified `LD_LIBRARY_PATH`, I wouldn't expect there to be a problem if `LD_LIBRARY_PATH` was set to the correct location in addition to the rpath patching.

**Comment by alexzorin** [comment]
>Despite rpath patching, LD_LiBRARY_PATH takes precedence

OK, turns out my previous comment is wrong. DT_RPATH does take precedence, and https://en.wikipedia.org/wiki/Rpath says so much. I couldn't break my armhf build with LD_LIBRARY_PATH just now, no matter how hard I tried.

**Comment by bmw** [comment]
Sounds good! Unless you can find a problem, even if https://github.com/certbot/certbot/commit/9b3b161d82fdacbbebecac37da9c01793689e61d seems to work, no longer setting `LD_LIBRARY_PATH` seems like the best fix to me.

**Comment by alexzorin** [comment]
It's not important anymore, but I retraced my steps to find what was bugging me about https://github.com/certbot/certbot/commit/9b3b161d82fdacbbebecac37da9c01793689e61d.

If `certbot.wrapper` was setting `LD_LIBRARY_PATH=/snap/certbot/x1/usr/lib/x86_64-linux-gnu/`, then (I believed) when Certbot reloaded Apache on the host, the `httpd` invocation could potentially end up with an incompatible mix of libraries.

However, this was already fixed in a different way inside Certbot in #8108. The reason I believed this was a problem was because I was testing via `snap run --shell` (where things look really broken), instead of actually looking at what Certbot was actually doing (stripping out the parts of `LD_LIBRARY_PATH` before invoking the host executable).

**Comment by bmw** [comment]
Got it. Thanks for following up with the explanation!
