### ISSUE TITLE
Windows: Prevent the Scheduled Task from creating a popup window

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#8308]
[Apparently](https://community.letsencrypt.org/t/certificate-renewal-console-popup/133760?u=_az), the Scheduled Task on Windows causes a console to pop up for a fraction of a second.

If there's an way in `renew-up.ps1` to prevent it appearing at all, we should do it.

**Comment by AuracleTech** [comment]
Thank you for windows servers it's really distracting.
Interrupting the windows focus or current work to open a window for a split second.

**Comment by AuracleTech** [comment]
Just reinstalled certbot on windows and got the popup had to find the thread again
Hope they fix it eventually, annoying af

**Comment by war59312** [comment]
Is annoying.

https://github.com/PowerShell/PowerShell/issues/3028

**Comment by Roelovic** [comment]
if you want to run this when user is logged in without highest privileges. just dont use the arguments box. put everything immediately after powershell.exe and make sure that -windowstyle hidden is first.
![image](https://github.com/certbot/certbot/assets/61496058/c1bdc37f-e9f6-43a5-a7c7-c3a4d73d9300)

**Comment by SeidChr** [comment]
you can avoid all popups by deploying this little tool to your target machines and use powershellw.exe / pwshw.exe instead
https://github.com/SeidChr/RunHiddenConsole

**Comment by zoracon** [comment]
Closing due to our decision to discontinue our Beta distribution of the Windows Installer:
https://github.com/certbot/certbot/wiki/Architectural-Decision-Records#-certbot-discontinuing-windows-support

If you need alternatives. They are listed in this community forum post:
https://community.letsencrypt.org/t/certbot-discontinuing-windows-beta-support-in-2024/208101
