### ISSUE TITLE
Do a final audit on IDisplay, logging, IReporter calls

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#8332]
After making explicit changes based on terminal output and audit per section (https://github.com/certbot/certbot/issues/8328, https://github.com/certbot/certbot/issues/8327, https://github.com/certbot/certbot/issues/8233, https://github.com/certbot/certbot/issues/8329, https://github.com/certbot/certbot/issues/8253), we should do a final review through all the calls that print to the terminal to make sure we haven't missed any categories of output.

This will probably involve auditing all `IDisplay` calls, all `logger/logging` calls that don't use debug(), and possibly all `IReporter` calls, though that may need to be saved for https://github.com/certbot/certbot/issues/8331.

**Comment by alexzorin** [comment]
The only remaining part of this issue is figuring out how to safely reduce `logging`'s default verbosity (currently `INFO`). This will probably be the final change for the terminal revamp.

We need to come to an understanding on how we use the `logging.warning/error/critical` error levels and also how we use the `warnings` module.

I will audit these individually and then see how we can make our priorities work, which are:

- Being able to reduce the verbosity without obscuring important warnings and errors (such as feature deprecations)
- At the same time, unimportant warnings and errors should be relegated to the debug log
- The distinction between error levels and `warnings` (if still used) must be clear

**Comment by bmw** [comment]
For the sake of making the list of issues in our current milestone a little more attainable, I'm moving all of the issues in the UX project that are currently blocked to the next milestone, but feel free to recategorize it if you disagree.

**Comment by ohemorange** [comment]
Closed by #8852.
