### ISSUE TITLE
Implement a force option when creating a new certificate (live directory exists)

### ISSUE THREAD

**Issue by butlerfr** [certbot/certbot#8333]
Hello

I'm facing an issue with certbot when trying to get certificate.
I'm using ansible to fully automating my system setup.

Ansible deploy apache with dumy certificate in the letsencrypt directory (/etc/letsencrypt/live) to make apache working.
Next when I try to setup certbot it fail with the following error : "live directory exists"

I just want certbot to overwrite those dummy certs.
I'm not alone cf last message in : https://github.com/certbot/certbot/issues/3396

otherwise, is their a way to make this working without doing manual tricks?
Actually the only way I see to fix this is to have an ansible playbook to install apache and vhost with dummy cert outside LE directory and an other playbook to manage apache and vhost after certbot installation. And that solution sucks (need to manage 2 playbook and 2 version of vhost).

Thanks,

**Comment by alexzorin** [comment]
I'm not sure about this one. Given the number of votes on the previous issue, it's certainly a real pain point for config management and Docker users. And I've run into it myself as well.

There are strategies to deal with that. You can point your webserver configuration to a bootstrapped certificate file of your own (outside of `/etc/letsencrypt`) and once the new certificates are issued,  change that certificate file to be a symlink pointing into `/etc/letsencrypt/live`.  

That could be a pure documentation fix.

One major problem with making a software change (such as this force option) is that as it stands, users should avoid modifying `/etc/letsencrypt/{live,archive}` at all just because it's quite easy to break things (even though it shouldn't be).  It does not seem wise to add a flag which appears to explicitly encourage that.

**Comment by Shardj** [comment]
For those having issues with dummy certificates in docker volumes. I got around it by using https://github.com/gchan/auto-letsencrypt which has a CERTS_PATH environment variable that will copy the certificates to that path out of the /etc/letsencrypt/live/{domain}/ directory. So you can simply create a volume against the CERTS_PATH instead of against /etc/letsencrypt/live/{domain}/ directly and your dummy file can sit in there without issue.
