### ISSUE TITLE
Log the real path to the running certbot executable

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#8340]
This was suggested at https://community.letsencrypt.org/t/add-the-run-from-path-to-log/134964

I think it's a good idea for the purposes of forum investigations. Might come in handy as certbot-auto is deprecated and as users migrate to snaps.

**Comment by osirisinferi** [comment]
Would using `sys.argv[0]` suffice? On my system it returns `/usr/lib/python-exec/python3.8/certbot` due to the use of [python-exec](https://github.com/mgorny/python-exec/). I have no idea what the return values would be for other distributions than Gentoo, Snap or Windows, so it's difficult for me to say if `sys.argv[0]` is the way to go.

**Comment by alexzorin** [comment]
I think that'd be fine, since this is [just for debugging purposes](https://github.com/certbot/certbot/blob/38893115572ee1bc91fcaf10669a80686795ba0b/certbot/certbot/_internal/main.py#L1384-L1387). 

Even if `sys.argv[0]` returns something unintuitive like a `python-exec` path, it's still useful information to disambiguate *which* Certbot ran.

Certbot already uses `sys.argv[0]` in a couple of places ([1](https://github.com/certbot/certbot/blob/38893115572ee1bc91fcaf10669a80686795ba0b/certbot/certbot/_internal/main.py#L207-L215), [2](https://github.com/certbot/certbot/blob/38893115572ee1bc91fcaf10669a80686795ba0b/certbot/certbot/_internal/main.py#L948-L950)) for display purposes, but as you point out, the output can get weird. This is on my list of things to investigate.
