### ISSUE TITLE
apache: authenticator breaks if `RewriteEngine off` is in the body of the virtualhost

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#8367]
This bug was the root cause of https://community.letsencrypt.org/t/type-unauthorized-detail-invalid-response-from/135681.

## My operating system is (include version):
Ubuntu Focal

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
snap

## I ran this command and it produced this output:
    certbot --apache -d www.example.com

## Certbot's behavior differed from what I expected because:
The HTTP challenge 404s. It should succeed.

The virtual host before:

    <VirtualHost *:80>
      ServerName www.example.com
      DocumentRoot /var/www/html
      RewriteEngine off
    </VirtualHost>

The virtual host after:

    <VirtualHost *:80>
      Include /etc/apache2/le_http_01_challenge_pre.conf
      ServerName www.example.com
      DocumentRoot /var/www/html
    RewriteEngine off
    Include /etc/apache2/le_http_01_challenge_post.conf
    </VirtualHost>

The pre-include enables `mod_rewrite`, but it is disabled before the post-include is evaluated. As a result, the request is not intercepted and results in a 404.

**Comment by JialuZhang** [comment]
This setting “RewriteEngine Off” alone is a misconfiguration and adding it to your system will not change any system misbehavior. Why "RewriteEngine Off" is allowed by Apache is that, if you include multiple "RewriteRule" parameters in your configuration, then instead of commenting them all, you can explicitly using “RewriteEngine Off” to disable all "RewriteRule".

Since herein there is no "RewriteRule", possible delete “RewriteEngine Off” would be ideal.

Related Apache source code snippet:

run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
