### ISSUE TITLE
How do deploy hooks work for automated renewals?

### ISSUE THREAD

**Issue by SamusAranX** [certbot/certbot#8368]
I checked the official documentation and scoured the community forums and wasn't available to find *anything* on this.

Assume I have two certs, set up ages ago, that are being automatically renewed by cron-powered calls to `certbot renew` every now and then. Now, a situation has emerged where I need a deploy hook for one of them.
CLI options are obviously no-gos because the certs are being renewed automatically. I tried putting a shell script into the renewal config file like this:
```
# renew_before_expiry = 30 days
version = 1.6.0
(stuff)

# Options used in the renewal process
[renewalparams]
(more stuff)
deploy_hook = scripts/do_stuff.sh
```
but certbot appears to overwrite these files with every renewal, so this is also a no-go.

What's the official, supported way of telling an automated certbot that I want it to execute a given shell script whenever a deploy happens for one specific certificate?

**Comment by alexzorin** [comment]
Annoyingly, the CLI flags you can pass to Certbot (like `--deploy-hook`) do not necessarily match the name of the corresponding key in the renewal parameters file.

`--deploy-hook` on the CLI actually corresponds to `renew_hook` in the renewal parameters file.

>but certbot appears to overwrite these files with every renewal

Indeed, it is wiping out your `deploy_hook` line because it is not a valid parameter.

If you instead include:

    renew_hook = /path/to/scripts/do_stuff.sh

then it won't get overwritten.

You can also throw scripts into `/etc/letsencrypt/renewal-hooks/deploy/`, though those only affect renewal, not the initial issuance (unlike `--deploy-hook` which affects both).

Hope that helps.

**Comment by SamusAranX** [comment]
I think that did the trick, thanks!

~~While testing this with `certbot renew --force-renewal`, I managed to get myself timed out. welp~~
