### ISSUE TITLE
Error in aws ec2 instances

### ISSUE THREAD

**Issue by thiagodeandrade** [certbot/certbot#8377]
Error in aws ec2 instances

## My operating system is (include version):
Amazon Linux 2

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
installed with snap
 snap list
Name       Version      Rev    Tracking  Publisher     Notes
certbot    1.9.0        652    stable    certbot-eff✓  classic

## I ran this command and it produced this output:
any command with certbot return the same errors messages

An error occurred while fetching Certbot snap plugins: your version of snapd is outdated.
Please run "sudo snap install core; sudo snap refresh core" in your terminal and try again.
An unexpected error occurred:
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://snapd/v2/connections?snap=certbot&interface=content

## The snap is update
sudo snap refresh core
snap "core" has no updates available

**Comment by alexzorin** [comment]
Hi @thiagodeandrade,

Thanks for the report.

I wasn't able just now to install snapd on Amazon Linux 2 at all, because apparently the packaged `selinux-policy-base` is too old.

1. With the `core` snap installed, would you be able to post the output of:

       snap version

2. Post its output again after restarting snapd (`service snapd restart`)?

3. Check whether `certbot` works now?

4. If not, is the issue resolved after running the following?

        snap install snapd

We may need to provide altered instructions for Amazon Linux 2.

**Comment by thiagodeandrade** [comment]
## 1) Snap Version
snap version
snap    2.36.3-0.amzn2
snapd   2.36.3-0.amzn2
series  16
amzn    2
kernel  4.14.198-152.320.amzn2.x86_64

## 2) restart snapd (same error)

## 3) Certbot
certbot certonly --no-bootstrap -d mydomain.com.br
An error occurred while fetching Certbot snap plugins: your version of snapd is outdated.
Please run "sudo snap install core; sudo snap refresh core" in your terminal and try again.
An unexpected error occurred:
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://snapd/v2/connections?snap=certbot&interface=content

## Instal snapd
snap install snapd
error: cannot install "snapd": cannot install snapd snap on a model without a
       base snap yet

**Comment by alexzorin** [comment]
I'm hoping to get a official-ish answer about snap support for Amazon Linux 2 [here](https://forum.snapcraft.io/t/are-snaps-supported-on-amazon-linux-2/20587). Fingers crossed.

**Comment by thiagodeandrade** [comment]
Thanks!
I hope a patch to this errors.
I have 25 ec2 instances with cerbot and some next to expire!

**Comment by alexzorin** [comment]
@thiagodeandrade could you confirm whether you installed snapd from https://github.com/albuild/snap/releases?

**Comment by thiagodeandrade** [comment]
Preparing...                          ################################# [100%]
        package snap-confine-2.36.3-0.amzn2.x86_64 is already installed
        package snapd-2.36.3-0.amzn2.x86_64 is already installed

**Comment by bmw** [comment]
> I wasn't able just now to install snapd on Amazon Linux 2 at all, because apparently the packaged `selinux-policy-base` is too old.

I've had an email thread with some people at Amazon about this for a while but we haven't been able to get this fixed yet.

**Comment by thiagodeandrade** [comment]
Can I use the old  method tar.gz ?

**Comment by thiagodeandrade** [comment]
Any reports about this?

**Comment by vrakesh1** [comment]
I have same issue


[ec2-user@ip-....... ~]$ sudo certbot certonly --nginx
An error occurred while fetching Certbot snap plugins: your version of snapd is outdated.
Please run "sudo snap install core; sudo snap refresh core" in your terminal and try again.
An unexpected error occurred:
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://snapd/v2/connections?snap=certbot&interface=content
Please see the logfile '/tmp/tmp5hd1j4xp/log' for more details.

**Comment by alexzorin** [comment]
Hi @thiagodeandrade,

Sorry for the delay, I meant to ask about this last week but forgot. This is part of a broader issue #6506 which we hope to get resolved eventually.

snapd isn't yet supported on Amazon Linux 2 (that `albuild/snap` build notwithstanding). It's tricky to know when that is going to change.

Right now, you should be able to use Certbot from EPEL 7 [using AWS' instructions](https://aws.amazon.com/blogs/compute/extending-amazon-linux-2-with-epel-and-lets-encrypt/) and it should receive updates for at least another year. One caveat is that the Route53 plugin is not working.

We plan to also write up instructions for systems, where for whatever reason, snaps can't be used.

**Comment by vrakesh1** [comment]
Hello All

I was able to install and set SSL using following approach
for AWS Amazon linux2, NGINX setup
hope it may help someone

1. cd /home/ec2-user/
2. wget -O epel.rpm –nv https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

3. sudo yum install -y ./epel.rpm

4. sudo yum install python2-certbot-nginx.noarch

5. Then I run following
sudo certbot -i nginx -a manual --preferred-challenges dns -d domain.com,subdomain.domain.com,www.domain.com --expand

6. after that Add TXT records as it prompts and follow steps
once done you will get message
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Congratulations! You have successfully enabled domain.com,subdomain.domain.com,www.domain.com
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

7. Then added cron entry in crontab to auto renew
Sudo vi /etc/crontab
39      1,13    *       *       *       root    certbot renew --no-self-upgrade

8. Restarted cron
[ec2-user ~]$ sudo systemctl restart crond

* I am not yet sure step #7 working because it will autorenew after it is expired.

Thanks

**Comment by thiagodeandrade** [comment]
Great!

Works for me!

wget -O epel.rpm –nv https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

**Comment by vrakesh1** [comment]
> Great!
> 
> Works for me!
> 
> wget -O epel.rpm –nv https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

Hello thiagodeandrade
I am very happy that my findings work for you :)
May be you can mark my answer as solution and close this case. 
Thanks
