### ISSUE TITLE
Delete Dockerfile-dev

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8386]
I checked with the team and no one that regularly works on Certbot is using it. Rather than continuing to maintain it, let's delete it and the instructions for it.

https://github.com/certbot/certbot/issues/8385 is tracking writing proper macOS development instructions. If that's not done before this issue, I personally think it's fine to remove all macOS dev instructions for now.

**Comment by lfundaro** [comment]
I think having docker environment ensures that the project is easier to get bootstrapped. Getting an OS specific environment setup often leads to problems because environments are complex and change from one workstation to the other. I think I would be rather a step backward to remove this and an entry barrier for people who might want to collaborate for the first time in this project. I opened https://github.com/certbot/certbot/issues/8517 while trying to get started developing something on certbot and I'm happy to help with a PR if I get to the root cause.
