### ISSUE TITLE
32bit support, please

### ISSUE THREAD

**Issue by voarsh2** [certbot/certbot#8441]
Can 32bit support be added?

I have a 32bit ubutnu 18 computer and need a 32bit build (i386)

**Comment by alexzorin** [comment]
Hi @voarsh2,

Unfortunately we can't re-add support to the Certbot snap because Ubuntu stopped supporting i386 in general.

For now, you can install the Ubuntu `python3-certbot` package via `apt`. It's [`0.27.0-1`, a fairly old version](https://packages.ubuntu.com/bionic-updates/python3-certbot) but it should keep working for the remainder of Ubuntu 18.04's life.
