### ISSUE TITLE
Can we unpublish the i386 snap?

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#8459]
There's a `1.5.0` release in the `edge` channel.

When people follow the website instructions on i386, they end up being prompted by `snap` that a release is available in the `edge` channel, and install that.

Could we unpublish it?

**Comment by bmw** [comment]
Not easily. See https://forum.snapcraft.io/t/is-it-possible-to-drop-an-unsupported-architecture-from-the-store/10510. I just bumped that thread asking if there's anything that can manually be done until they fix the code.

**Comment by bmw** [comment]
Since my new question received no response, I created a new store requests thread at https://forum.snapcraft.io/t/manually-delete-snaps-for-an-architecture/21398.

**Comment by bmw** [comment]
The snap store should really fix this bug and I just reached out to some friends at Canonical to see if they can move things along, but if not, we may want to try to do something ourselves here.

The best idea I have is to upload a new i386 snap to the snap store that provides better behavior than giving the user an old version of Certbot that works. One option would be to upload a simple snap that prints an informative error message and exits with a nonzero status. Another option would be to add informative error messages to Certbot's output but otherwise keep it working.

I prefer the first option, but there's a slight downside of us shipping that snap immediately breaking things for the 175 i386 snap users we currently have. We could do the 2nd option or try to add some logic that keeps Certbot working if and only if it was maintaining certificates, but I personally think it's probably not worth it and we can just ship the breaking change for that small number of current users which improves the behavior for new users.

**Comment by bmw** [comment]
I tried closing the edge channel again but this time I left it closed for 10 hours or so as opposed to immediately rebuilding new edge snaps. On a i386 system I see this which I guess is progress...
```
# sudo snap install --classic certbot
error: snap "certbot" is not available on stable but is available to install on the following
       channels:

       edge       snap install --edge certbot

       Please be mindful pre-release channels may include features not completely tested or
       implemented. Get more information with 'snap info certbot'.
#  snap install --edge --classic certbot
error: snap "certbot" is not available on latest/edge but other tracks exist.

       Please be mindful that different tracks may include different features. Get more information
       with 'snap info certbot'.
```

**Comment by bmw** [comment]
I made more noise about this at https://forum.snapcraft.io/t/inconsistent-snap-store-state/26109.
