### ISSUE TITLE
Stale branches

### ISSUE THREAD

**Issue by atombrella** [certbot/certbot#8473]
There are quite a lot of (feature) branches that appear to be stale, or merged in some way. Some of them are for versions, which probably ought be deleted/replaced by tags.

**Comment by bmw** [comment]
I doubt we'll ever (be able to) take the time to manually go through these branches and clean them up as I personally think there are more impactful things Certbot devs can spend their time on.

I also don't think we should just delete old branches since it is not uncommon for us to save work we may pick up later in a branch. For instance, see https://github.com/certbot/certbot/issues/6203 and the `bmw-ocsp-apache` branch.

If someone wanted to for example programmatically identify the branches that have been merged into `master`, we could delete those.

As for the version branches, we could in theory delete old `<major>.<minor>.x` branches, however, those are the branches we do point releases off of and they already have things like GitHub branch protections and CI set up. It's unlikely that we'll ever do a point release for an older version of Certbot, but keeping the branches around makes that easier and I personally don't think it's worth the extra automation or manual work to delete them after doing a new major or minor release.
