### ISSUE TITLE
manually created snap certbot plugins are not recognized by certbot

### ISSUE THREAD

**Issue by BigMichi1** [certbot/certbot#8504]
## My operating system is (include version):
Ubuntu 20.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
snap

## I ran this command and it produced this output:
`snap install certbot-dns-dnsimple_1.11.0.dev0_amd64.snap --devmode`

## Certbot's behavior differed from what I expected because:
the plugin is not listed when I run certbot plugins,
when I install it via  `snap install certbot-dns-dnsimple` it is listed
my expectation is that I can also install it via the snapfile so that I can test my changes to the code

It looks like that that some hook script is not run compared to the "normal" snap installation

when running `snap install certbot-dns-dnsimple` it fails intentionally with the message from `prepare-plug-plugin` hook, but when using a snapfile it doesn't so I think it is not called, am I missing something? I know that according to the docs I need to run two `snap connect` commands to get it working. when I publish now my plugin to snapcraft.io the hook still is not called, so I need to run also the connect commands which should not be needed compared to the plugins that are provided by certbot

**Comment by bmw** [comment]
If you run the snap connect commands as described at https://certbot.eff.org/docs/contributing.html#writing-your-own-plugin-snap do things work as you expect?

Whether we like it or not, snaps from the same publisher will autoconnect while snaps from different publishers will not. See https://snapcraft.io/docs/content-interface. That's why you don't need `snap connect` commands when installing our own plugins from the snap store.

Once you run the `snap connect` commands either when installing from the snap file directly or when installing your own snap from the snap store, your plugins should work the same as ours from the perspective of snaps.

Does that solve the problem you're having?

**Comment by BigMichi1** [comment]
sorry for the confusion, now I got it, thanks for pointing to the link https://snapcraft.io/docs/content-interface, then everything is fine as it works normally after running the connect commands
