### ISSUE TITLE
Make Windows installer builds reproducible

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8520]
Another EFF project written in Python is https://github.com/EFForg/https-everywhere-standalone. They were able to easily achieve reproducible Windows executables with Pyinstaller. See https://github.com/EFForg/https-everywhere-standalone#windows-10-1.

Are we able to do something similar with our Windows installer builds? I don't think this is a must have feature, but I think it would be nice.

**Comment by osirisinferi** [comment]
> I don't think this is a must have feature

This, I think, depends if the source code can be inspected when using the Windows installer. If one can inspect the actual certbot code on their machine (i.e.: verify that certbot doesn't leak the private key somehow or otherwise have security backdoors), this isn't a must have indeed.

However, if a user of the Windows installer *cannot* verify the integrity of the code, I think it **is** a must have! People should be absolutely certain that compiled code doesn't contain other code than what can be verifiable from the public source code.

This is of course a principally issue regarding binaries & security software.

That said:

* The certbot code actually consists of *regular Python files*, no binaries there (just byte-coded cache files which are compiled during the installation, those files aren't in the installer, and I assume you could remove them probably if you don't trust them)
* However, Python itself in the `/Python/` directory are binaries only. Which makes sense. I'm wondering however i *that part of the installer* can be reproducible with regard to *their* source code? Where do those binaries come from?
