### ISSUE TITLE
Feature Request: "prune"

### ISSUE THREAD

**Issue by githubsaturn** [certbot/certbot#8525]
Related issues:
certbot/certbot#4634
certbot/certbot#4635

Currently, a large number of files are stored in `/etc/letsencrypt/{keys,csr}` directories. Going through the previous discussion, it looks like they were introduced for backup purposes. However, they are not being utilized by users and they just take up space.

Since we can't tell for sure whether or not users are using them, but we know that they are not useful content, we can introduce a new command to remove these files. 

I suggest something like `certbot prune` which removes these files.

In future, we can extend the functionality of this command to maybe also expired certs and etc.

**Comment by bmw** [comment]
I updated https://github.com/certbot/certbot/issues/4634 arguing that I think we can just stop creating these files which I prefer to adding Certbot functionality to help users manually delete them. I feel the same way about https://github.com/certbot/certbot/issues/4635, however, what that behavior should be is trickier.

Because of all this, I think we can close this issue in favor of those, but please let me know if you'd like me to reconsider.
