### ISSUE TITLE
Certbot always adds manual_public_logging_ok to configuration file

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8540]
After https://github.com/certbot/certbot/pull/8500, Certbot always includes `manual_public_ip_logging_ok = None` in its renewal configuration file. That PR took the approach of making adding deprecated plugin flags work the same way as adding deprecated core Certbot flags. Turns out there's also a bug in that approach too which was also introduced by the default detection system in 2016 in https://github.com/certbot/certbot/pull/2388.

The bug is `certbot._internal.cli.set_by_cli('manual_public_logging_ok')` always returns `True` because [its looking for our magic default value](https://github.com/certbot/certbot/blob/fcc8b38c02cc10ff320b401ffa242f2253ce9552/certbot/certbot/_internal/cli/__init__.py#L487) which deprecated flags don't have because we skip the extra default parsing [here](https://github.com/certbot/certbot/blob/fcc8b38c02cc10ff320b401ffa242f2253ce9552/certbot/certbot/_internal/cli/helpful.py#L361-L372). I think we never noticed this before because deprecated flags were either not relevant for renewal or they were plugin flags which took a single argument which worked properly before https://github.com/certbot/certbot/pull/8500.

I think we should fix this, but I think the effect of the bug is pretty minimal. The only effect I can think of is people who downgrade their Certbot version (and are using the manual plugin) may have trouble, but that's always been the case.

I started working on a fix for this at https://github.com/certbot/certbot/compare/deprecation-fix-part2. The code currently makes two changes:

1. It causes deprecated arguments to have no effect on the resulting namespace config. It's probably fine, but this is currently relying on undocumented behavior which I asked about at https://bugs.python.org/issue42650.
2. It causes renewal config items that start with the name of the selected plugin but are otherwise not recognized to be silently dropped.

I'm unsure about (2). Our current behavior here is:

a. Any unrecognized parameters that do not start with the name of a plugin are silently dropped.
b. We error about any unrecognized parameters that do start with the name of the plugin.

(b) is kind of nice, but I think we should silently drop deprecated plugin options from the renewal config. If the option is deprecated (in the sense of the deprecation methods being used here), it has no effect and it will be removed in a future release. If we do not drop the option from the renewal config, Certbot will crash when it encounters the renewal config option after support for it has been removed.

To drop these flags while keeping the behavior in (b), I think we'd essentially need a generalized way to recognize deprecated plugin flags so they can be dropped. This seems tricky and for that reason I'm leaning towards just doing (2), but I wanted to get someone else's thoughts on this issue before I spent more time on it.

**Comment by alexzorin** [comment]
I took some time to look more closely at how this part of Certbot works and this approach looks okay to my eyes.

One thing about (b) is that it might provide some minor protection against being accidentally destructive. Maybe something like `nginx_sleep_seconds` getting wiped out if there's two different Certbot versions setup on the system. Maybe that is slightly too contrived, but OTOH at scale, all the possibilities tend to happen.
 
(Came across a minor problem in the branch: I think the detection of unrecognized config items should be `hasattr(config, config_item)` rather than `config_item in config`.)

**Comment by bmw** [comment]
Thanks a lot for helping me with this Alex.

Thinking about this problem some more, what I personally think Certbot's behavior should be in general is to error when it encounters values it doesn't understand in the renewal configuration file. If this happens, something has gone wrong, and I think just dropping the values can hide problems like the ones you described.

I think fully making that change is out of scope of this issue, but making the change I described in (2) moves us further away from that behavior. What if instead we added logic to `HelpfulArgumentParser` where if an argument is deprecated we add the flag or destination to a global `set` somewhere in `certbot._internal.cli` named something like `DeprecatedOptions`. When parsing plugin options in renewal configuration files, we will drop these options while continuing to error on unrecognized values. In the future, we could do something similar for the rest of our renewal parameters by checking if every value in the configuration file is either in the global config object or in the deprecated arguments list. If it's not, we raise an error.

Thoughts on this approach?

**Comment by bmw** [comment]
I haven't fully dug into this idea yet, but I wanted to share some further thoughts I had in case someone else is willing and able to take a look.

I think a simpler and safer approach to resolving this issue might be to fix the default detection logic for deprecated arguments rather than skipping it like I did in https://github.com/certbot/certbot/pull/8500. I think we'd first need to look into commit/GitHub history to see why `modify_kwargs_for_default_detection`  does what it does in the first place, but depending on what we find there, I think we may be able to fix this issue by instead of returning early in `add` if `action is util.DeprecatedArgumentAction` which I added in https://github.com/certbot/certbot/pull/8500, we go ahead and let `modify_kwargs_for_default_detection` be called but skip changing the `action` or removing kwargs based on `ARGPARSE_PARAMS_TO_REMOVE` if `action is util.DeprecatedArgumentAction`.

Again, I think whether or not this is actually a decent idea requires further digging which I haven't had a chance to do myself yet, but if it works I think it may be the best approach.

**Comment by ohemorange** [comment]
Ugh I wrote up a whole comment but chrome crashed and ate it, so that's fun. Let me try to reconstruct it...

1. No matter which option we take, I agree we need a transition plan for renewal configs that we've erroneously added that option to in particular, and removing deprecated arguments from renewal configs in general. I think if we have a good one here, we won't need to worry too much about unrecognized arguments in the future; I do agree that erroring on those is a nice property to have, and I think it's reasonable to have if arguments sit in deprecated-state for long enough.
2. I'm very hesitant to rely on undocumented behavior, since we were recently bitten by that. Hopefully we won't need to use that option.
3. I'm also hesitant to mess around with implicit behavior or let too much be called on something that isn't supposed to be doing anything in the first place. Basically I'm hesitant to muck around with code we already know has led to bugs unless we're completely rewriting it from scratch. What if we continue to return early, and also return early in `set_by_cli`? Is there ever a case where a deprecated argument should return `True` in `set_by_cli`? Even so, we should probably be changing that to false, anyway, right? So my suggestion would be to add an additional early-return to `set_by_cli` when `action is util.DeprecatedArgumentAction`. Unless of course I've misunderstood exactly what a deprecated flag is and does.

**Comment by bmw** [comment]
> No matter which option we take, I agree we need a transition plan for renewal configs that we've erroneously added that option to in particular, and removing deprecated arguments from renewal configs in general. I think if we have a good one here, we won't need to worry too much about unrecognized arguments in the future; I do agree that erroring on those is a nice property to have, and I think it's reasonable to have if arguments sit in deprecated-state for long enough.

I think that's good enough to solve this particular issue and is how things have always worked more generally.

With that said, I'm personally also interested in the idea you proposed to me of permanently keeping around a list of deprecated arguments. If someone makes a large jump in Certbot versions (by for example switching from OS packages to snaps), they may have missed our deprecation period. If the deprecated argument became a noop which is usually the case for us, erroring about the problem doesn't seem ideal to me. We can save this for future work if you want though.

> I'm very hesitant to rely on undocumented behavior, since we were recently bitten by that. Hopefully we won't need to use that option.

I'm kind of curious what undocumented behavior we were recently bit by as I think I may have missed it, but assuming here you're referring to my sentence:

> It's probably fine, but this is currently relying on undocumented behavior which I asked about at https://bugs.python.org/issue42650.

The Python maintainers responded at that link with a way to do what I wanted there using documented behavior.

> I'm also hesitant to mess around with implicit behavior or let too much be called on something that isn't supposed to be doing anything in the first place. Basically I'm hesitant to muck around with code we already know has led to bugs unless we're completely rewriting it from scratch. What if we continue to return early, and also return early in `set_by_cli`? Is there ever a case where a deprecated argument should return `True` in `set_by_cli`? Even so, we should probably be changing that to false, anyway, right? So my suggestion would be to add an additional early-return to `set_by_cli` when `action is util.DeprecatedArgumentAction`. Unless of course I've misunderstood exactly what a deprecated flag is and does.

One complication with making `set_by_cli` return early is it currently only has access to the result of parsing arguments and not the CLI parsing setup where `action` is given. A couple ways we could fix this are keeping track of deprecated arguments either globally or in a list returned up through `prepare_and_parse_args` which is what `set_by_cli` uses.

Digging into this a bit again to respond to you though, I'm not sure that's sufficient. The behavior I think we want here is for `manual_public_ip_logging_ok` to be dropped from the renewal config regardless of its value. I think changing the behavior of `set_by_cli` is not enough because items are saved in the renewal config based on [this conditional](https://github.com/certbot/certbot/blob/adb7e5e62f4c96be678c5af3e55a82ddcc717590/certbot/certbot/_internal/storage.py#L279). The [code for cli.option_was_set](https://github.com/certbot/certbot/blob/adb7e5e62f4c96be678c5af3e55a82ddcc717590/certbot/certbot/_internal/cli/__init__.py#L534) returns true if the option was set on the command line or if its value differs from the current default value. This is complicated by the fact that we now have both `manual_public_ip_logging = True` and `manual_public_ip_logging_ok = None` in renewal config files, however, I think we would have had problems here anyway because the default of `manual_public_ip_logging_ok` changed to `None` when it was deprecated. My most recent proposal doesn't handle this either.

With this in mind, I'm personally leaning most towards keeping a list of deprecated arguments, ideally a static one in my opinion as I described in my response to (1) and checking if the option being considered is in that list as needed. Whatever approach we take here, I think we should make sure we're happy with the behavior with the different combinations of `manual_public_ip_logging_ok` in a renewal config file being `True`, `None`, or nonexistent and the option being set on the command line or not.

**Comment by ohemorange** [comment]
Ah, I didn't realize that deprecating it changes the default value, that's a nice catch. And glad to hear they responded with an official way to do it.

But I think that honestly, I want to do several things here. I like the keep-around-a-list-forever for the reason you mentioned about big skips such as in OS upgrades, but I'd *also* like to continue returning early where we currently do, and additionally return early in other places that reference deprecated options, as needed.

My assumption here is that many of our problems are caused by interactions of this kind-of-edge-case with the default detection system, so let's avoid those interactions to the extent possible. And further, I have a preference for doing things explicitly rather than implicitly; if we want deprecated options removed from the renewal config, let's explicitly remove deprecated options from the renewal config. So:

- make a list of deprecated options
- explicitly remove deprecated options from the renewal config
- keep the code where it checks if it's a deprecated action and return early so we don't bother doing additional processing on it
- anywhere else where we do things with cli options where we might be passed a deprecated option, check if it's deprecated, and if so, return early (where it makes sense). this is more of a preemptive measure, and there might be more or fewer places than I'm imagining, so this one is very much a "look into it and see if it makes sense", but I'd like to have it as a principle/theory.

**Comment by bmw** [comment]
That all sounds good to me!

The only downside I see is `set_by_cli` cannot really answer if a deprecated option was set on the command line or not because the `_Default` detection for deprecated arguments is broken and you're proposing not to fix it, however, whether or not a deprecated flag was set on the command line isn't a question that we should have to ask and if we have a need to actually do this in the future, we can always revisit this.

To give you some pointers in case it's useful, I think we may want to consider adding an explicit filter for deprecated values at:

* https://github.com/certbot/certbot/blob/b4e955a60e78c622b03108ba933ddedc2ca236ff/certbot/certbot/_internal/renewal.py#L158
* https://github.com/certbot/certbot/blob/b4e955a60e78c622b03108ba933ddedc2ca236ff/certbot/certbot/_internal/storage.py#L279 (maybe inside `_relevant`)?

**Comment by ohemorange** [comment]
> whether or not a deprecated flag was set on the command line isn't a question that we should have to ask

That's exactly what I was hoping/assuming would be the case.

Thanks for the pointers!

**Comment by ohemorange** [comment]
I obviously haven't added tests or comments yet or even tested it myself, but #8617 is my idea of where I'm going with this in case anyone feels like throwing in an early opinion on that.
