### ISSUE TITLE
alphabetize AUTHORS.md

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#8543]
In https://github.com/certbot/certbot/pull/8521#pullrequestreview-552161887 we discovered that `AUTHORS.md` is not quite alphabetized.

We could try something simple in the PR test suite to ensure names are sorted. 

Or just sort it once, this time.

**Comment by osirisinferi** [comment]
> Or just sort it once, this time.

Didn't https://github.com/certbot/certbot/pull/8521/commits/b3aa35bcf16f393b2e08ca22278d4c0cfe6c7282 sort it already?

**Comment by alexzorin** [comment]
That commit was subsequently reverted before the PR was merged

**Comment by osirisinferi** [comment]
Hmm, my bad. Because I thought that commit actually sorted everything correctly and I checked if the current AUTHORS.md from master was sorted with `sort` and `diff`, which resulted in no difference:

```
osiris@erazer certbot $ tail -n +4 AUTHORS.md | sort | diff <(tail -n +4 AUTHORS.md) -
osiris@erazer certbot $ 
```
(The `tail -n +4` is for removing the heading above the actual author list. If you remove that, you'll see that `sort` detects the sorting of the header among the authors.)

So it seems the current AUTHORS.md is sorted according to GNU coreutils `sort` already, even without that commit.

**Comment by alexzorin** [comment]
That commit looks like alphabetical sort on the first name (cc @lfundaro). I think that's fair, since it's probably how a human navigates the list. 

Just running `sort` on `AUTHORS.md` isn't quite alphabetical because the sorting key is the entire line of markdown, so the sorting rules around word length fail to be applied.

Sorting by first name automated way might be quite complicated though:

    pandoc --to=plain AUTHORS.md | tail -n +6 | sort -b -k2,2 | diff --color <(pandoc --to=plain AUTHORS.md | tail -n +6) -

Maybe we do nothing and live with `sort` order, maybe we reorder it by hand. I doubt anybody notices!
