### ISSUE TITLE
Using the acme library, how do you issue an order with an existing account?

### ISSUE THREAD

**Issue by bendavis78** [certbot/certbot#8554]
The [example](https://github.com/certbot/certbot/blob/master/acme/examples/http01_example.py) currently only shows how issue  an order with an existing account. Currently the docs don't explain how to get a `regr` object for an account that already exists. How is this done?

I'm able to successfully issue an order when creating a new registration:

```python
def get_client(acct_key):
    print("Connecting to Let's Encrypt on {}".format(DIRECTORY_URL))
    net = acme.client.ClientNetwork(acct_key, user_agent=USER_AGENT)
    directory = acme.messages.Directory.from_json(net.get(DIRECTORY_URL).json())
    client = acme.client.ClientV2(directory, net=net)
    return client


def create_registration(client):
    # Register and agree to TOS
    regr = client.new_account(
        acme.messages.NewRegistration.from_data(email=ACME_ACCT_EMAIL, terms_of_service_agreed=True)
    )
    return regr


def get_acct_key():
    with open(ACME_ACCT_KEY_PATH) as pem_in:
        pemlines = pem_in.read().encode('ascii')
    key = load_pem_private_key(pemlines, None, default_backend())
    return josepy.JWKRSA(key=key)

key = get_acct_key()
client = get_client(key)
reg = create_registration(client)

domain = 'foo.example.com'
pkey = new_pkey(domain)  # creates the pkey pem
csr = new_csr(pkey, domain)  # creates the csr

order = client.new_order(csr)  # success
```

However, when I try to create the order _without_ creating the registration (event though I'm using the same acct key), it fails:

```python
key = get_acct_key()
client = get_client(key)

domain = 'foo2.example.com'
pkey = new_pkey(domain)
csr = new_csr(pkey, domain)

order = client.new_order(csr)
# acme.messages.Error: urn:ietf:params:acme:error:malformed :: The request message was malformed :: No Key ID in JWS header
```

**Comment by bendavis78** [comment]
Update - I was able to work around this thanks to [this post](https://community.letsencrypt.org/t/103452/3) on the forums.

The problem seems to be that `client.net.account` needs to be set to the `regr` object before sending any requests. I implemented a function that uses the internal `_post()` function to grab the registration resource and set it on `client.net`:

```python
def get_registration(client, acct_key):
    # from https://community.letsencrypt.org/t/103452/3
    reg_data = acme.messages.NewRegistration(key=acct_key.public_key(), only_return_existing=True)
    response = client._post(client.directory['newAccount'], reg_data)
    regr = client._regr_from_response(response)
    client.net.account = regr  # sets the account for future requests
    return regr
```

Perhaps this should be added to the acme library so that we don't have to use "private" methods?

**Comment by alexzorin** [comment]
In order to be functional, an ACME client needs to know its Account URL. It can do this in one of two ways:

1. Remembering what the Account URL is, or
2. Registering to the ACME server again with the same key. The ACME server [must respond with the existing account](https://tools.ietf.org/html/rfc8555#section-7.3.1), which will include the Account URL.

From your question, you want to avoid (1). Therefore your client needs to persistently store the Account URL in addition to the Account Key.

With `acme`, you can [store](https://github.com/certbot/certbot/blob/1146f3551992aeddff9991ef1aeef856d7540ee9/certbot/certbot/_internal/account.py#L369) the `acme.messages.RegistrationResource` (the `regr` value) as JSON, [load](https://github.com/certbot/certbot/blob/1146f3551992aeddff9991ef1aeef856d7540ee9/certbot/certbot/_internal/account.py#L218-L219) and [restore it](https://github.com/certbot/certbot/blob/1146f3551992aeddff9991ef1aeef856d7540ee9/certbot/certbot/_internal/client.py#L41-L42) subsequently.

**Comment by bendavis78** [comment]
That makes sense. Thanks!

**Comment by ipilcher** [comment]
> In order to be functional, an ACME client needs to know its Account URL. It can do this in one of two ways:
> 
>     1. Remembering what the Account URL is, or
> 
>     2. Registering to the ACME server again with the same key. The ACME server [must respond with the existing account](https://tools.ietf.org/html/rfc8555#section-7.3.1), which will include the Account URL.

@alexzorin - Is there actually a way to (re-)register with the same key without delving into internal functions?  The two examples that I've been able to find ([here](https://community.letsencrypt.org/t/acme-python-clientv2-not-able-to-renew-a-certificate-without-enrolling-new-account/103452) and [here](https://github.com/certbot/certbot/issues/6246)) both depend on internal functions (`ClientV2._post()` and `ClientV2._regr_from_response()`).
