### ISSUE TITLE
Disable certbot-auto upgrades

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8615]
This is a (main) piece of https://github.com/certbot/certbot/issues/8526.

`certbot-auto` is completely deprecated from a user's perspective and will not try to install newer versions of Certbot, however, the script is still checking for updates to itself on every run. Due to the way this system works, until it is disabled, we have to continue providing updated and signed versions of certbot-auto during every release or certbot-auto will freak out and I'd like to stop doing this.

What I would like to do is something very similar to what we did in deprecating certbot-auto on different OSes. `certbot-auto` has long supported the flag `--no-self-upgrade` which causes the environment variable `NO_SELF_UPGRADE` to be set during argument parsing. When this environment variable is set, certbot-auto skips checking for updates to itself later in execution. Over 3 releases, I'd like to set `NO_SELF_UPGRADE` after identifying the OS.

Rough numbers for a current count of certbot-auto users is:

|os|unique certbot-auto user count|
|--|--|
|debian & friends|235666|
|RHEL & co.|131709  |
|other|27153  |
|Amazon 2|3515|

In our first release, I'd set `NO_SELF_UPGRADE` for every OS other than Debian and RHEL. In the next release, I'd set it for RHEL and in the final release I'd set it for Debian. After this is done, we have to keep the final version of the file around as people will continue to update to it over time, but it no longer needs to be updated.

The downside of this approach is once we ship the release disabling updates, we're locked out. If the update breaks things, the only way users who updated can fix it is manual intervention. To work around this, we could try to make further changes to the update system and do something like check for the existence of a file on our GitHub and only update if that file exists, however, doing something like this to me seems more error prone, more likely to create a problem, and excessive work for a script that's printing deprecation warnings on every run.

@adferrand, @ohemorange, since you've been my partners in killing this script, I'd love it if you could take a look at this plan when you find the time.

**Comment by ohemorange** [comment]
I support this plan technically; I think it's lightweight and likely to work well without breaking things.

I think we can further mitigate the danger caused by no longer being able to push updates by modifying the deprecation message, now that we're officially deprecated on all systems. We could say stronger things than we currently say, like "this script no longer self-updates" and "this script and certbot installation may break in the future" and "to fix a broken installation, visit certbot.eff.org to learn how to download a version of certbot that is packaged for your system." We could do this alongside the first round of disabling certbot-auto upgrades, or beforehand.
