### ISSUE TITLE
New Certbot hard to use

### ISSUE THREAD

**Issue by Articuno1234** [certbot/certbot#8618]
## My operating system is (include version):
Ubuntu Server 20.10

All I want to do is run 

./certbot-auto certonly -manual -email ***@gmail.com -server https://acme-v02.api.letsencrypt.org/directory -agree-tos -d *.-----.com

but I can't because it's deprecated. My domain registrar (Hostinger) doesn't have a DNS plugin. Is there any way that I can just use certbot-auto?

**Comment by alexzorin** [comment]
Hello @Articuno1234,

`certbot` supports the same commands as `certbot-auto`, including your manual way of obtaining a wildcard certificate.

If you follow the [instructions to install Certbot on Ubuntu](https://certbot.eff.org/lets-encrypt/ubuntufocal-other), you will be able to run the same command as you did with `certbot-auto`, just by replacing the command name:

    certbot certonly -manual -email ***@gmail.com -server https://acme-v02.api.letsencrypt.org/directory -agree-tos -d *.-----.com

I am going to close this because hopefully this answers your question fully, but if you have any followup questions about obtaining your certificate, https://community.letsencrypt.org/ is a good place to ask them.

**Comment by Articuno1234** [comment]
Thanks! Sorry i'm just dumb.
