### ISSUE TITLE
Skipping bootstrap because certbot-auto is deprecated on this system.

### ISSUE THREAD

**Issue by aportetecnologia** [certbot/certbot#8625]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
Skipping bootstrap because certbot-auto is deprecated on this system.
Your system is not supported by certbot-auto anymore.
Certbot cannot be installed.

## Certbot's behavior differed from what I expected because:
did not install my certificate as 3 months ago.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
did not generate log

**Comment by alexzorin** [comment]
Hello @aportetecnologia,

Please have a read of [this post](https://community.letsencrypt.org/t/certbot-auto-no-longer-works-on-debian-based-systems/139702/7) regarding the deprecation of `certbot-auto`.

Since `certbot-auto` is not currently installed on your system, you will need to replace it with `certbot` by following the instructions at https://certbot.eff.org/instructions. After it's installed, it will work exactly the same way that `certbot-auto` did.
