### ISSUE TITLE
[PROPOSAL] Support ZeroSSL out of the box

### ISSUE THREAD

**Issue by fancsali** [certbot/certbot#8647]
This is not a bug per se; rather a feature request/proposal.

There's this new (to me) service, that is very similar to Letsencrypt: [ZeroSSL](https://www.zerossl.com).

They do provide a wrapper so one can use `certbot` to request a certificate from them, but I figured it'd be nice to have the ability to do it out of the box.

**Comment by alexzorin** [comment]
Certbot does support ZeroSSL out of the box, since ZeroSSL implements standard ACME EAB account registration.

1. Head to https://app.zerossl.com/developer and generate your "EAB Credentials"
2. Register your ZeroSSL ACME account using those credentials:

        certbot register --server https://acme.zerossl.com/v2/DV90 \
        --eab-kid "EAB_KID_GOES_HERE" --eab-hmac-key "EAB_HMAC_KEY_GOES_HERE"

From there, you can issue certificates via ZeroSSL by specifying `--server https://acme.zerossl.com/v2/DV90` any time you create a new certificate. You can also set the server in `/etc/letsencrypt/cli.ini` to save yourself including it every time.

I can't speak for ZeroSSL, but the ZeroSSL Certbot wrapper seems to exist to simplify the above steps. It's not required to use ZeroSSL's ACME server.

**Comment by fancsali** [comment]
Right, didn't read the fine manual properly then.

Apologies...

**Comment by alexzorin** [comment]
Not at all - it is not an obvious thing. Your question will hopefully help other users on the same path. Sorry if my response was a bit rough.
