### ISSUE TITLE
Outdated regex in utils - enforce_le_validity does not allow for wildcard domains

### ISSUE THREAD

**Issue by geberl** [certbot/certbot#8658]
I think the regular expression `^[A-Za-z0-9.-]*$` used in https://github.com/certbot/certbot/blob/master/certbot/certbot/util.py#L485 is outdated. It raises `ValidationError` for wildcard domains like `*.example.com`.

Correct should be `^(\*\.)?[A-Za-z0-9.-]*$`.

**Comment by bmw** [comment]
Thanks for the issue. You're correct that wildcard domains are now valid for use with Let's Encrypt.

I'm curious what prompted this issue though. Did you hit this in practice when using Certbot? The reason I'm asking is while it is true the behavior of the function doesn't match its name, I'm not immediately sure we actually want this change in behavior due to where the function is used so I'd be interested to hear your motivation here.

**Comment by geberl** [comment]
I did not hit this while using certbot.

My idea was to re-use the validation logic of certbot for our internal tooling, to not waste API requests towards Let's Encrypt. Feel free to close with wontfix.

**Comment by bmw** [comment]
I see! Thanks for the info and you're right that the maximum length of a domain name should be 253 characters.

I'm fine with changing the behavior of `enforce_le_validity`, but the main place we use this function ourselves is to filter out some of the domains found in Apache and Nginx config files before suggesting them to the user. For that use case, I think we should still filter out wildcards since our Apache and Nginx plugins aren't able to do the DNS challenges Let's Encrypt requires to obtain certs for them.

All that's to say that I'd accept a PR refactoring the code a bit to get that behavior from our plugins while allowing wildcards in `enforce_le_validity` if you or someone else wanted to write one.
