### ISSUE TITLE
Audit references to certbot-auto and letsencrypt-auto

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8661]
As part of killing certbot-auto and letsencrypt-auto, I think we should look through our repo for references to them and either delete them or make a plan to do so as appropriate. If they need to be deleted in the future, I think creating new issues/PRs to track this work would be ideal.

The places we need to be careful are:

* `certbot-auto` and `letsencrypt-auto` in the root of our repo and `letsencrypt-auto-source/certbot-auto.asc ` as I think they are used to update the files at https://dl.eff.org such as https://dl.eff.org/certbot-auto. I think we should decide what behavior we want from that site (404 or continue to serve last version?) and then coordinate with tech ops to ensure we get this behavior without breaking things.
* `letsencrypt-auto-source/letsencrypt-auto` and `letsencrypt-auto-source/letsencrypt-auto.sig` as these files are what letsencrypt-auto uses to upgrade itself. Once letsencrypt-auto is truly dead, I think we may want to add a simple nightly test to ensure these files never change. (It's OK for the files to change on `master`, but them changing in a new `git` tag is a problem.)

**Comment by ohemorange** [comment]
So I started work on this in the `remove-le-auto-refs` [branch](https://github.com/certbot/certbot/compare/remove-le-auto-refs?expand=1), but then realized how many things are referenced from the release script. There's a few things we *could* remove now, but honestly, it'll probably be easiest just to do it in one big batch after.

My "remove later" checklist includes:
- `tests/letstest/scripts/test_leauto_upgrades.sh` and its callers (inc. release script)
- `tests/letstest/scripts/test_letsencrypt_auto_certonly_standalone.sh` and its callers (inc. release script)
- modify `tests/modification-check.py` as described
- most of the `letsencrypt-auto-source` files, since the release script calls `build.py` (I removed these in the branch, but that was a mistake)

The very small amount of things that could be removed now include a few places in certbot itself, a couple sections of the docs, and a few remaining references to the requirements file that will probably get cleaned up in the course of the pip constraints rewrite anyway. Happy to pull those out onto a branch if we think it's worth it.
