### ISSUE TITLE
Certbot not detecting if www is used with nginx when server is configured with *.example.com

### ISSUE THREAD

**Issue by andrerom** [certbot/certbot#8665]
A bit of an edge case, but Certbot could have some detection to see if some DNS CNAME / www-redirects is done on domain when setting up certificate to avoid security warnings on resulting traffic.

## My operating system is (include version):
Ubuntu 20.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
`snapd`

## I ran this command and it produced this output:
`sudo certbot --nginx`

1. It suggest to generate cert for `example.com´, when traffic (setup via DNS) is actually redirected to `www.example.com`
2. Browser shows security warning due to invalid/missing cert for `www.example.com`

## Certbot's behavior differed from what I expected because:

When performing http-01 challenge it can try to detect what domain is coming to the server to double check for missmatch against what it is trying to generate cert for. 

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

```
server {
    server_name example.com *.example.com;
    root /home/user/www/example.com;

    index index.html index.htm;
}
```

**Comment by alexzorin** [comment]
Hello @andrerom,

Thank you for opening this issue and sharing your experience.

>When performing http-01 challenge it can try to detect what domain is coming to the server

It's an interesting idea, but I'm not sure there is a reliable way to do this. There are some complications, like wildcard DNS records being indistinguishable from non-wildcard ones.

This looks like an edge case relating to wildcard names, which produces a confusing user experience. 

You have configured the vhost to respond to any [*.]example.com` domain, which is fine. However, Certbot filters out `*.example.com` from the proposed certificate names, because wildcard certificates cannot be obtained using HTTP-01/`--nginx`, instead requiring a DNS plugin.

Maybe Certbot should still list the wildcard name, but say that it is disabled/unavailable, explain why, and offer alternative strategies.

**Comment by andrerom** [comment]
Unsure about disabling it, might not always be right. But indeed have some kind of notification here as it might mean:
- wildcard is needed
- traffic on other sub domains is expected, and hence should be generated cert for (unless you opt for wildcard cert)

In my case I didn't need a wildcard certification, but forgot I had www-redirect (at dns provider) setup from root domain to www sub.
