### ISSUE TITLE
certbot delete needs to take --cert-path like revoke.

### ISSUE THREAD

**Issue by bsutton** [certbot/certbot#8669]
The certbot revoke command allows us to target a certificate by path (--cert-path) when revoking a certificate.

Can we enhance the delete command to also allow deletion via path rather than just name.

**Comment by alexzorin** [comment]
`certbot revoke` can take `--cert-path` because one of its use cases is to revoke a certificate which is not managed by Certbot. For example, if you download it from crt.sh or even from your browser's certificate interface.

The same is not true of `certbot delete`. The command is only designed to delete a certificate lineage from Certbot.

I suppose that we could make `certbot delete` take `--cert-path` and try map it back to an existing lineage with `cert_manager.cert_path_to_lineage`. 

But, to me it feels a bit pointless. It is the same as passing `--cert-name` but makes Certbot jump through an extra hoop.  So my question to you is, why would you find this useful?
