### ISSUE TITLE
Another Instance Of Certbot Is Already Running.

### ISSUE THREAD

**Issue by shashiskm** [certbot/certbot#8703]
HI,
I host multiple domains and upon HTTP request, a script creates a Nginx conf file for the domain along with its certificate.
Script Create SSL Certificate using Sudo certbot certonly --dns-route53-propagation-seconds. But when two domain entries are requested at the same time two certbot command runs at the same time. But I get an error as Another Instance of Certbot is Already Running for one domain.

What is the cause of this issue? Also, How can I generate multiple domain certificates from one server using a script?

**Comment by alexzorin** [comment]
It is not safe to run multiple concurrent instances of Certbot against a single `--{config,work,log}-dir`, because it may cause corruption or reads of half-written files.

In order to prevent this unsafe behavior, Certbot creates lockfiles in each of these directories, which can only be held by one Certbot process at a time.

Some choices that you have:

- Use a different `--{config,work,log}-dir` for each of your tenants, so that no two Certbot instances will overlap on the same directory.
- Ensure you only run one instance of Certbot at a time. A job queue could be a good way to do this.

**Comment by shashiskm** [comment]
Thank you very much for the reply. As it is a critical issue for my organization.

**Comment by shashiskm** [comment]
Hi @alexzorin Can you explain the 1st choice in more detail how can i have different directory for each tenants?

**Comment by alexzorin** [comment]
There's some discussion on this exact topic [here](https://community.letsencrypt.org/t/how-to-run-certbot-instance-simultaneously-without-creating-account-for-each/144879/17?u=_az), where one user has given an example of that strategy.

I think that's a good place to continue this discussion if you want, so I'm going to close this issue.

**Comment by shashiskm** [comment]
Thank you very much I am going with the 1st choice.
