### ISSUE TITLE
Remove modifications to certbot-auto from the release script

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8707]
After our 1.14.0 release, we no longer need to make changes to certbot-auto as part of the release script and should remove all code making changes to it.

This is blocked until https://github.com/certbot/certbot/pull/8706 is included in a release.

**Comment by adferrand** [comment]
I suppose we can also remove the letsencrypt-auto-source folder in the process?

**Comment by bmw** [comment]
I don't think we can unfortunately. I wrote about this a bit more in https://github.com/certbot/certbot/issues/8661, but I think we essentially have to keep `letsencrypt-auto-source/letsencrypt-auto` and `letsencrypt-auto-source/letsencrypt-auto.sig` around forever.

**Comment by adferrand** [comment]
Maybe not forever? If these files are removed, `fetch.py`will fail, but this does not prevent old versions of certbot-auto to run certbot, it just breaks the ability to self-upgrade.

Maybe in a decently far future, with metrics proving that only a small fraction of old versions of certbot-auto are still out there, it could be acceptable to break their ability to upgrade, since them to still be here would prove that they would never try to upgrade anyway?

**Comment by adferrand** [comment]
My bad, it seems it would break the script completely actually...

**Comment by ohemorange** [comment]
WHAT, I always assumed it just grabbed the files from the repo root...TIL...
