### ISSUE TITLE
Simplify dependencies between packages

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8761]
@hlieberman, @nbebout, and @FelixSchwarz, I wanted to simplify how we specify dependencies between our different packages and wanted to check in with you all before doing so. Currently, our dependencies are as flexible as possible with for example our Cloudflare plugin declaring dependencies on `acme>=0.29.0` and `certbot>=1.1.0`. We regularly test with the different oldest supported versions of each package to ensure everything works, but running tests with a mix of new and old packages when everything is in the same repo is a bit cumbersome for us.

What I would like to do instead is to not try to support older versions of `acme` and `certbot` with newer versions of our packages. With this approach, version 1.15.0 of our Cloudflare plugin would declare dependencies on `acme>=1.15.0` and `certbot>=1.15.0`. This isn't going back to way we used to declare dependencies which would have been `acme==1.15.0` and `certbot==1.15.0` causing you to upgrade all components every time you upgraded one, but it would mean that upgrading `certbot` requires updating `acme` and updating a plugin would require updating both `acme` and `certbot`.

My question is how cumbersome would this be for you? Do you have any significant concerns about us making this change?

**Comment by hlieberman** [comment]
The situation I'd like to avoid is having to upload empty packages just to get version numbers bumped. I don't think I've ever seen this happen for any of the plugins, but I have seen a situation where this might happen with `acme` and `certbot`. For example, the 1.11 release contained changes to `certbot` but no changes to `acme` (except for the version string being bumped). If that version of certbot had shipped `acme>=1.11`, I would have been forced to upload an empty bump of acme just to make the dependencies work.

As long as you're always declaring the actual requirements, not just blindly updating things, this shouldn't be a problem.  But that situation is food for thought; blindly bumping the requirements to always be equal to the current version will cause some amount of annoyance downstream.  Honestly, I'd probably end up undoing the dependency in patches rather than ship empty versions.

**Comment by bmw** [comment]
What's the problem with empty package uploads? If you wanted to go the route of undoing the dependency in patches, how annoying would that be for you?

The problem on our end is we have a nontrivial amount of custom tooling to test new versions of our packages with our older ones which I'd like to remove. If we don't have that testing, I don't think we can reliably claim support for older versions of our packages as we'll inevitably forget to update the dependency when new required functionality is added.

I pinged our EPEL maintainers on this issue as well to be sure this change is OK with them, but for better or worse, I believe Debian is the only distro that's actually making use of our packages no longer being in lockstep. Pages like https://repology.org/project/certbot/versions suggest that.

I want to work with you here to ensure that whatever change we make isn't too much of a headache for you, however, I really would like to make some kind of change on our end rather than continuing with the current approach.

**Comment by hlieberman** [comment]
On Fri, Apr 2, 2021 at 2:00 PM Brad Warren ***@***.***> wrote:

> What's the problem with empty package uploads? If you wanted to go the
> route of undoing the dependency in patches, how annoying would that be for
> you?
>
Because it's not one source package, it means preparing uploads for
packages that have no real changes.  It's pushing updates down to users'
machines that have no purpose.

Undoing the dependency by patches isn't the most annoying thing in the
world; I can do it if it must be done.

-- 
Harlan Lieberman-Berg
~hlieberman

**Comment by FelixSchwarz** [comment]
For Fedora+EPEL we treat certbot+plugins as "one package" which means  we update these at once anyway. If it helps you I think we don't have a problem with the `>=` approach.

**Comment by bmw** [comment]
> Because it's not one source package, it means preparing uploads for
packages that have no real changes.  It's pushing updates down to users'
machines that have no purpose.

I see. I agree neither of those things are ideal for you.

I'll think about it a bit more and I'm happy to chat more about alternatives if you want, but right now I'm thinking that we'll probably go forward with this change and we can revisit it if it's causing significant headaches for anyone.

**Comment by bmw** [comment]
Closing this with the plan that we're probably going to try making this change in the next couple months.
