### ISSUE TITLE
I encountered a confusing error message in storage.py, and while investigating that, I found another confusing error message.

### ISSUE THREAD

**Issue by jeffsilverm** [certbot/certbot#8807]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Ubuntu 18.04

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
I don't remember.
## I ran this command and it produced this output:
````
2021-03-17 06:28:14,756:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.31.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1365, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1119, in run
    certname, lineage)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 121, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 428, in obtain_and_enroll_certificate
    self.config)
  File "/usr/lib/python3/dist-packages/certbot/storage.py", line 1008, in new_lineage
    "live directory exists for " + lineagename)
**certbot.errors.CertStorageError: live directory exists for jeffsilverm.ddns.net**
(END)
````
This is confusing because it says that the live directory exists (which is true) but doesn't state where the live directory is or what should be done.

I inspected the code and found 2 similar error messages in **storage.py** and fixed them both:
````
root@raspberrypi:/usr/lib/python3/dist-packages/certbot# diff  storage.py storage.py_ORIGINAL
**1004c1004**
<                 "archive directory " + archive +" exists for " + lineagename + ". Save its contents and get rid of the archive directory" )
---
>                 "archive directory exists for " + lineagename)
**1008,1009c1008**
<                 "live directory " + live_dir + " exists for " + lineagename + ".  Save its contents and get rid of it")
< 
---
>                 "live directory exists for " + lineagename)
root@raspberrypi:/usr/lib/python3/dist-packages/certbot# 
````
To recreate the problem and verify the fix worked,

1. Prior to running certbot, `mkdir /etc/letsencrypt/live/_DOMAIN_ ` or `mkdir /etc/letsencrypt/live/_DOMAIN_ `, where `__DOMAIN__` is the FQDN for which the certificate is being generated.  
2. Run certbot.
3. You will see the error message `certbot.errors.CertStorageError: live directory exists for jeffsilverm.ddns.net`.
4. After the fix is applied, you will see the error message ` live directory /etc/letsencrypt/live/_DOMAIN exists for _DOMAIN_. `, which is much clearer and more helpful.

## Certbot's behavior differed from what I expected because:
The error messages don't tell me what the live directory is or what the archive directory is.  If I knew what these directories were, then I could them out of the way and let Certbot rebuild them.

**Comment by jsoref** [comment]
Ah, I was hoping you'd actually make a PR -- you can click the ✏️ at the top of https://github.com/certbot/certbot/blob/master/certbot/certbot/_internal/storage.py and make the corrections and then create a PR from there.

See https://github.com/certbot/certbot/blob/master/CONTRIBUTING.md

That said, what you've provided here is indeed enough for me to do something if I needed to (I ended up deleting/renaming a bunch of directories / hacking a bunch of conf files)

**Comment by jeffsilverm** [comment]
Josh,

I'm sorry.  I did not understand what you were asking for.  If I understand
what you wrote, then you made more extensive changes than I had intended.
That's okay: it's your software.

What I tell my students, when they are crafting error messages, is to think
about what the recipient needs to know in order to resolve the issue.
Assume that the recipient cannot read the source code, so that everything
the recipient needs to know is in the error message.  Sometimes, you can't
do that because you yourself have no idea why this error occurs.

Thank you,


Jeff

**Comment by jsoref** [comment]
Git is built around commits which are a way to package `diff`s with additional metadata including an author, a date stamp, and a description of changes.

GitHub adds to this two other things, issues which you used here and pull requests which are basically a hybrid of commits and an issue.

I was asking for you to create a commit with the diff you created here (including some basic commit message) and then create a pull request referencing that commit.

**Comment by ohemorange** [comment]
You're right, these comments could be improved. Please submit a pull request with those changes.

**Comment by alexzorin** [comment]
We discussed this issue and some potential ways we could improve the error message.

An underlying issue is that Certbot's storage is a bit malleable and fragile. As a result, it's (too) easy to take actions that result in problems with symlinks, missing files and directories.

I think the suggested change here has exactly the right instinct: have an error message that tells the user what they should do to resolve the issue.

However, I am hesitant to add an outright instruction like "delete directory X" because I'm not sufficiently confident that it's the right course of action in every case. Bad things can happen storage for a number of different reasons.

Instead, if the user has encountered a situation that resulted in such a storage error, I think we would prefer that they reach out on the community forums to try identify what has gone wrong in their situation (whether on disk or in terms of how they are using Certbot) and to then make the right correction. We're going to be adding such a message to Certbot's error output.

That is not ideal UX for sure, but I think it strikes the right balance for storage errors specifically, because they can be a bit curly.

In an upcoming major version of Certbot, this issue could/should be addressed by making the storage more resilient. I have opened #8842 to track this.

Thanks @jeffsilverm for the contribution. I'd be happier if we could just apply your suggestion, but I think for now I think we should stick to "get help". If there is some other way we could improve those messages though, we're open to hear it.
