### ISSUE TITLE
Remove `letsencrypt-auto-source/letsencrypt-auto` and `letsencrypt-auto-source/letsencrypt-auto.sig`

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#8812]
These files are what `letsencrypt-auto` uses to upgrade itself.

Older users who haven't upgraded to the version where everything is deprecated might still be trying to upgrade directly to the latest version.

In a few months, we should look at statistics to see if any stragglers are actually still updating to the latest version, and when they're not, delete these files, in tandem with https://github.com/certbot/certbot/issues/8742.

**Comment by ohemorange** [comment]
Either this issue or #8742 (whichever comes later) should delete `tests/modification-check.py` and its callers.

**Comment by ohemorange** [comment]
Adding this to the milestone so it doesn't get lost; we may not be ready for it.

**Comment by bmw** [comment]
I started looking into this and pulled stats on certbot-auto users from Let's Encrypt, but I actually don't see a way for us to really estimate here how many people this is going to effect.

The certbot-auto deprecation did two things:

1. Running the script on a system without an existing Certbot installation errors out without running or installing Certbot.
2. When certbot-auto upgrades itself on a system with an existing Certbot installation, the certbot-auto script will update to the latest available version, but it will leave the Certbot installation untouched. For example, if you create an installation using certbot-auto 1.0.0 and then let it upgrade, `grep -m1 LE_AUTO_VERSION certbot-auto` will output `LE_AUTO_VERSION="1.14.0"` which is the last version of certbot-auto while `certbot-auto --version` will output `certbot 1.0.0`. 1.0.0 is the version that Let's Encrypt sees.

Because of all this, I don't see a way for us to really estimate how many people are continuing to rely on certbot-auto's self-upgrade process working.

As a reminder, if we delete these files, old versions of certbot-auto that haven't upgraded to the latest version will crash with output like this if the try to upgrade:
```
Upgrading certbot-auto <current certbot-auto version> to <latest certbot version on PyPI>...
Couldn't download https://raw.githubusercontent.com/certbot/certbot/<latest certbot version on PyPI>/letsencrypt-auto-source/letsencrypt-auto. HTTP Error 404: Not Found
```
The script will work again if the user includes `--no-self-upgrade`.

I doubt deleting these files will cause that much trouble, but I don't think there's any way we can really know that. I don't have that strong of an opinion, but what I'd personally like to do is while the existence of these files isn't really causing a problem to just let them be. If there ever comes a time where we really want to delete them for some reason, I think we can just go ahead and do that. To communicate this plan, I'd propose doing something like creating a `letsencrypt-auto-source/README.md` file briefly explaining this, linking to this file in `tests/modification-check.py`, and closing this issue.

Thoughts?

**Comment by ohemorange** [comment]
Two major thoughts:
1. Didn't we used to have some indicator that people were using certbot-auto in particular? Did we remove that at some point?
2. What types of situations could have resulted in certbot-auto users with a version other than 1.13.0 (or the last certbot version that auto-upgraded on their system)? Maybe people who run their own renew scripts, in which case there should still only be a range of a few versions. I'm not overly worried about manual users, as long as we have clear, sufficiently-SEO'd instructions for how to handle this (basically, switch installation methods, or use `--no-self-upgrade`). I suspect we could do some cross-referencing of oldest versions in distros with last versions of cb-auto left on various systems, and look at the OS and certbot version to get a sense of these numbers. Or at least, when there are sufficiently few certbot users on 1.13.0 or earlier, we'll know for sure we can remove these files.

That being said, that's a lot of work to be able to delete these last two files, so I'm not particularly overly worried about. If you want to, we can try some of these, or just forget it and go with your plan, which I think is fine.

**Comment by bmw** [comment]
> Didn't we used to have some indicator that people were using certbot-auto in particular?

It's still there.

> What types of situations could have resulted in certbot-auto users with a version other than 1.13.0 (or the last certbot version that auto-upgraded on their system)?

If during the month the last version of certbot-auto that worked on their system was our latest release, they didn't upgrade for whatever reason. The kinds of cases of this that come to mind to me are people with their own renew scripts or people who set `--no-self-upgrade` which from https://github.com/certbot/website/commit/14e1b046594cdf85abf98fbe822d71b50d960116 to https://github.com/certbot/website/commit/10253e5825b48335bc2d197460ef63038963da1d was part of our renewal instructions. Again, I think it's _probably_ fine to just delete these files, but I suspect it's somewhat common for people to have `--no-self-upgrade` in their renewal scripts and eventually have to manually run `certbot-auto` again to change something about their setup at which point they forget to include the flag.

> I'm not overly worried about manual users, as long as we have clear, sufficiently-SEO'd instructions for how to handle this (basically, switch installation methods, or use --no-self-upgrade)

I don't think we do currently based on https://www.google.com/search?hl=en&q=%22Couldn%27t%20download%20https%3A%2F%2Fraw.githubusercontent.com%2Fcertbot%2Fcertbot%2F%22.

I initially pulled stats yesterday for 3 months in 1 month intervals grouping certbot-auto users into `certbot>=1.8.0` and `certbot<1.8.0` as 1.8.0 is potentially the last version of Certbot certbot-auto would have installed on their system. That data is:

| Time period       | Certbot version | Unique IP count |
|-------------------|-----------------|-----------------|
| 3 to 2 months ago | >=1.8           | 159,826         |
| 3 to 2 months ago | <1.8            | 28,431          |
| 2 to 1 months ago | >=1.8           | 160,352         |
| 2 to 1 months ago | <1.8            | 27,452          |
| 1 to 0 months ago | >=1.8           | 158,508         |
| 1 to 0 months ago | <1.8            | 26,562          |

I wanted to answer your questions and share the work I already did, but I personally would still like to go with my plan including in the README that before deleting these files we should make a community forum post containing the error message users will see and describing how they can work around the problem.

Sound good or do you have more ideas or questions?

**Comment by ohemorange** [comment]
Thanks for sharing this! Yeah, that's enough remaining users that it's probably worth keeping it around, and I like that plan.
