### ISSUE TITLE
Error when setting pre-hook or post-hook

### ISSUE THREAD

**Issue by fermmm** [certbot/certbot#8885]
When I run this command:
```certbot renew --pre-hook "pm2 stop my-app" --post-hook "pm2 start my-app"```

I get this error:
```Unable to find pre-hook command pm2 in the PATH.```

pm2 it's a globally avaiable command, I don't understand why it's important that the command is on the PATH.
I want to know if the hooks are going to work despite the error. How can I check that?

**Comment by alexzorin** [comment]
Hi @fermmm,

Where is the `pm2` program located on your system, and what is the `PATH` reported by Certbot in the error message?

**Comment by fermmm** [comment]
This is the full text of the error including the path:
```
Unable to find pre-hook command pm2 in the PATH.
(PATH is /snap/certbot/1201/bin:/snap/certbot/1201/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games)
```
This is the location of pm2:

```/home/fer/.nvm/versions/node/v14.16.1/bin/pm2```

Originally I configured certbot with sudo and now I'm executing certbot renew without sudo, maybe that is a problem

**Comment by alexzorin** [comment]
OK, thanks.

By the looks of things, `pm2` is not globally available. 

It's probably being added to `fer`'s terminal session `PATH` via a `nvm` setup script in `~/.profile` or whatever equivalent file.

Since Certbot usually runs and renews certificates as the `root` user, it does not see `fer`'s nvm-related paths.

If I were you, I would create a couple of shell scripts like `/root/start-my-app.sh` and `/root/stop-my-app.sh`. These would perform the process of:

1. switching to the `fer` user
2. making sure `nvm` is initialized (you can the 2 lines of script on how to do that [here](https://github.com/nvm-sh/nvm#install--update-script))
3. and finally running `pm2`

Then, you would use these two scripts as the `--pre-hook` and `--hook-hook`.

I know is a lot of work compared to just running `pm2` directly, but because of the way you have `pm2` installed, it's probably best to make sure you're running as the right user and with the right shell environment.

**Comment by fermmm** [comment]
I logged as root and tried, nothing, the same error. It seems there are no commands avaiable at all. I dried this:

```
certbot renew --pre-hook ". ~/.bashrc && pm2 stop my-app" --post-hook ". ~/.bashrc pm2 start my-app"
```

That in theory should make nvm commands available before executing pm2, but certbot gets in the way, this error is returned:
```
pre-hook command . exists, but is not executable.
```

Any idea how this can be fixed without creating scripts? because that complicates many things in my project, I'm looking for an easier solution.

**Comment by alexzorin** [comment]
Certbot doesn't run the hooks inside a bash shell, so you'd need to wrap everything in a `bash` command, as well as changing to the correct user (since Certbot will be doing this as `root`).

It'd end up looking something like:

    --pre-hook "sudo -u fer bash -c '. ~/.nvm/nvm.sh; pm2 stop my-app'"

Hopefully that gives some insight into how Certbot hooks work and what kind of approach you'd need to take to run a command in another user's shell. 

I am going to close this issue as the Github issue tracker is for bug reports and feature requests, but if you're looking for more suggestions on how to get this working, https://community.letsencrypt.org/ has a lot more people available to help out exactly with questions like this.

**Comment by fermmm** [comment]
This is the command that I used and it seems it's going to work, at least this time does not throw error, thanks!:

`certbot renew --pre-hook "sudo -u USER bash -c '. ~/.bashrc; pm2 stop poly'" --post-hook "sudo -u USER bash -c '. ~/.bashrc; pm2 start poly'"`
