### ISSUE TITLE
debian instructions on website missing apt install.

### ISSUE THREAD

**Issue by thctlo** [certbot/certbot#8903]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Debian Buster

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
apt or apt-get  Its forbidden to install snapd on my debian servers, this breaks other software. 

## I ran this command and it produced this output:
none since i didnt see them on the website. 

## Certbot's behavior differed from what I expected because:
why the hell do we need snapd which is out off band with the debian defaults. 
if you want snapd, Ubuntu fine. Debian Not.

**Comment by bmw** [comment]
We recommend using snaps because it allows you to get a version of Certbot that stays up to date. Our instructions also link to https://certbot.eff.org/docs/install.html where you can find instructions using docker or pip. You're of course welcome to continue using OS packages and we maintain a good relationship with the Certbot package maintainer for Debian so the Certbot packages should continue to mostly work, but because it doesn't receive most updates and does things like configures Apache and nginx with a less secure TLS configuration than moderns version of Certbot do, we don't recommend it to most users.

I'm sure this isn't what you wanted to hear, but it's our rationale here and we're not planning on changing this so I'm closing this issue.

**Comment by thctlo** [comment]
Thank. for the updated . 

Yeah, thats not what i hoped for but i get it. 

My problem with most of these thing.. docker pip and i dont know snapd at atll. 
Why it is used anyway, i dont get that, but how are security updated handled by snap, or docker of pip. 
because i run all my servers with unattended upgrades, and im wondering how that's handled then.

And yeah, debian configures it all in a "safe" setting. not most secure, i do that myself. 
i've just finish with that.. 

You can keep it closed, om only wondering then how unattended upgrades are handled buy snapd and certbot.

**Comment by bmw** [comment]
`snapd` by default checks for updates to itself and all installed snaps 4 times a day and automatically installs the update if one is available. There's more info about this at https://snapcraft.io/docs/keeping-snaps-up-to-date.
