### ISSUE TITLE
Should certonly call `restart` at the end if the installer is set? And/or if no installer is set but the authenticator is also an installer?

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#8912]
Based on an ad-hoc user test from a user who was upgrading to an ACMEv2-compatible version of certbot after using an old version entombed in a docker distribution.

Since the user already had their nginx config set up, they only wanted to renew an existing cert, not install it, so they used `certonly` and followed the prompts to renew the existing cert. But they had to restart nginx after getting the cert, despite using nginx for the authenticator, which was unexpected and made it seem like certbot might not have worked somehow.

They'll be fine on renewal since `--nginx` does set an installer and so will restart nginx despite having run `certonly` (is this weird and unexpected?), but given that we do know that `nginx -s reload` is successful because we literally just called it to get the cert, should we just call it anyway? To me, this doesn't make sense in theory due to our internal auth/installer splits, but if it's a common-enough use case (which I suspect it might be), it probably makes sense in practice for users who shouldn't need to fully understand our internal structure, especially if they're just following the instruction generator instructions.

Alternatively, we could just throw a line in the instruction generator steps about this, to the effect of "this will update the files but you will need to modify or reload where you have them installed to pick up the files". Although that is a little specific to this case, and would be confusing to users who haven't yet installed the certificate, since it does assume certs are already installed. We could try to catch this case early and tell users that they can just run `renew` if they already have certs from an old installation, but I'd personally prefer more branching in code and less in user-facing instructions, especially since we do try to catch all the ways users might run certbot and make them "just work."

Leaving this untagged so people see it during triage in case I forget to bring it up for discussion at the weekly meeting.

**Comment by osirisinferi** [comment]
> They'll be fine on renewal since `--nginx` does set an installer and so will restart nginx despite having run `certonly` (is this weird and unexpected?)

Personally, I think this is very weird. Not everyone knows the `-a` and `-i` options and it's very much possible to get a certificate for a hostname for which a VirtualHost does **not** exist. Think SMTP or IMAP servers. (At least, I can perfectly get certs with the `--apache` plugin without actually having that hostname in my Apache configuration.. Not sure if that's by design..)
So it wouldn't make sense *at all* if someone gets a certificate with `certonly`, possibly not even used in Apache, but using the `apache` authenticator.
I would say: certonly? Then don't set an installer.

**Comment by bmw** [comment]
I'd personally be OK with having `certonly` call `restart` if the installer is set.

I understand that this is kind of weird with our mental model of Certbot, but that weirdness arguably already exists with commands like `certbot certonly --nginx` setting an installer that is used by `certbot renew`. I think us matching this behavior with `certonly` is reasonable enough and should essentially completely resolve this issue with little to no downside.

I think this issue essentially only affects our own plugins because third party plugins currently cannot have flags like `--nginx`. See https://github.com/certbot/certbot/issues/1549. Because of this, 3rd party plugins will only be affected if the user is explicitly setting an installer. If they are and it's already going to be used with `renew` anyway, calling `restart` initially with `certonly` to have consistent behavior and potentially catch renewal problems earlier seems fine to me personally.

For our own plugins, our only installer plugins are for Apache and nginx and both do graceful restarts with no downtime. In essentially all cases, I'd expect Apache or nginx to have been used as the authenticator too because we tell people to use the `--apache` and `--nginx` flags and in that case we've already restarted the web server successfully in both cases. Adding another `restart` call after saving the certificate doesn't seem to me like it should cause any problems and it'd automatically avoid issues like the one described in the initial post.

**Comment by ohemorange** [comment]
Great points, thanks, I agree. In general, between matching our mental model of certbot and the user's expectations, the latter is more important. This is a step towards making our UX more seamless.
