### ISSUE TITLE
Clarify what email address for alerts is used for and who gets access to it (public vs. only letsencrypt?)

### ISSUE THREAD

**Issue by CodingSpiderFox** [certbot/certbot#8916]
I ran the following command

```
sudo certbot --apache -d host.mydomain.org
```

And it produced the following output

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator apache, Installer apache
Enter email address (used for urgent renewal and security notices) (Enter 'c' to
cancel):
```

It is not clear to me whether my email is exposed then and where

**Comment by alexzorin** [comment]
The email address, if you choose to provide one, is transmitted directly to the Certificate Authority (by default, Let's Encrypt) during the CA account registration process when you first use Certbot (https://certbot.eff.org/privacy/).

From there, you can check the the CA's subscriber agreement or privacy policy regarding the handling of your email address, such as https://letsencrypt.org/privacy/#subscriber.

**Comment by CodingSpiderFox** [comment]
It would be nice to directly add that link to the log output

**Comment by alexzorin** [comment]
Yes, maybe something like that can be done. It is a bit silly that the "terms of service" prompt comes *after* you have already entered your email address.

**Comment by CodingSpiderFox** [comment]
That would be nice, thank you :)

**Comment by CodingSpiderFox** [comment]
@alexzorin any updates on this?

**Comment by alexzorin** [comment]
A couple of thoughts:

1. We shouldn't make any new changes which are specific to Let's Encrypt. Certbot is used with a variety of certificate authorities, other than Let's Encrypt. We shouldn't link to letsencrypt.org and Let's Encrypt's policies are subject to change and we're not going to entomb any of that in Certbot.
2. We can probably swap the order in which the Terms of Service and Email prompt appear, which would allow the user to refer to the CA-provided Terms of Service document before providing their email address. It would take a bit of work because of how the code was written originally.
3. Without more demand for this change, we are most likely not going to implement it.

**Comment by CodingSpiderFox** [comment]
OK, that sounds reasonable. Thank you!
