### ISSUE TITLE
Please update the documentation for the docker image certbot/dns-route53

### ISSUE THREAD

**Issue by adrianwix** [certbot/certbot#8925]
Setting the AWS variables inside .aws/config does not work I assume it's because it's looking for that INSIDE the container. There is really no explanation of how to use the image. 
Hope this help some people. One needs to pass the AWS variable using docker variables. You can store it in a file a load them using `source` (bash only)
```bash
echo "Setting AWS_KEY"
source $(pwd)/letsencrypt.env
echo $AWS_ACCESS_KEY_ID
echo $AWS_SECRET_ACCESS_KEY

echo "Running certbot"
docker run -it --rm --name certbot \
  -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
  -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
  -v "$(pwd)/nginx/letsencrypt:/etc/letsencrypt" \
  certbot/dns-route53 certonly \
  --dns-route53 \
  --agree-tos \
  -m user@domain.con \
  --no-eff-email \
  --test-cert \
  -d *.user-staging.domain.com \
  --server https://acme-v02.api.letsencrypt.org/directory
```

**Comment by osirisinferi** [comment]
Couldn't you just as easily use `-v ~/.aws/:~/.aws/` ?

**Comment by alexzorin** [comment]
On https://certbot.eff.org/docs/install.html#running-with-docker, there is a section of text which talks about this:

>You may also need to add flags to Certbot and/or mount additional directories to provide access to your DNS API credentials as specified in the DNS plugin documentation.

Maybe this is insufficient because it requires too much interpretation, or maybe nobody sees it.

Maybe something we could do is to add one final example to each of the DNS plugin documentation pages, like https://certbot-dns-google.readthedocs.io/en/stable/#examples. It would show the user how to run the container and would include any appropriate volume mounts or environment variables, right there on the page.

If anybody wants to write that PR, please go ahead.

**Comment by adrianwix** [comment]
Not sure if the documentation is still unclear since I haven't used this plugin for a long time
