### ISSUE TITLE
"The account is not awaiting external account binding" when ACME account recovery was expected

### ISSUE THREAD

**Issue by christian-2** [certbot/certbot#8944]
## My operating system is:
Debian 10

## I installed Certbot with:
I have tried both the Debian 10 package version (0.31.0) and the latest Docker-based version (1.17.0).

## I ran this command and it produced this output:
`certbot register --server https://acme.sectigo.com/v2/OV --eab-kid $EAB_KID --eab-hmac-key $EAB_HMAC_KEY`
```
An unexpected error occurred:
The request message was malformed :: [External Account Binding] The account is not awaiting external account binding
```

## Certbot's behavior differed from what I expected because:

This happened after I had previously used the same credentials for issueing a certificate, also from Sectigo and with certbot, but had then deleted certbot (including `/etc/letsencrypt/accounts`) by accident. I would have expected Certbot to recover the account given that I was passing EAB credentials again, but it did not. `acme.sh` can do this in the same situation. Is the apparent fact that certbot cannot a feature or a bug? Or does this require different command options?

**Comment by bmw** [comment]
I tested with ZeroSSL instead of Sectigo, but I'm not sure `acme.sh` can recover in this situation either. `acme.sh --register-account` works, however, when I go to issue a cert, it fails for me with:
```
Create new order error. Le_OrderFinalize not found. {"type":"urn:ietf:params:acme:error:malformed","status":400,"detail":"A Key ID MUST be specified"}
```
My understanding of what's going on here is `acme.sh` has hardcoded the Sectigo/ZeroSSL specific error message of "The account is not awaiting external account binding". See [here](https://github.com/acmesh-official/acme.sh/blob/a76dcd4ba1c6045794968bad38538afd1c9236ad/acme.sh#L3636). There is no mention of this text in the [standardized protocol](https://datatracker.ietf.org/doc/html/rfc8555). When `acme.sh` gets that error, it ignores it and tries to continue execution which at least in my case causes it to fail later because it wasn't properly able to create an account.

While sticking to the standard which is what Certbot tries to does as much as possible, the only way to recover an account is with the account key that is stored in `/etc/letsencrypt` and presumably under `~/.acme.sh` in the case of `acme.sh`. See https://datatracker.ietf.org/doc/html/rfc8555#section-7.3.1. Because of all this, I'm closing this issue, but please comment and let me know if I'm misunderstanding something and I'll consider reopening.

**Comment by christian-2** [comment]
Thanks for your quick follow-up. Yes, I can confirm by now that `acme.sh --issue` fails with "A Key ID MUST be specified". I had tried only up to `acme.sh --register-account` before, as you say. I'm still not sure about the "correct" behavior, e.g. because I was under the impression from cert-manager/issues#2882 (the last comment there is mine) that ACME account recovery was possible at least with `cert-manager` as ACME client (and Sectigo as CA). However, I can also request new EAB credentials and should be able to solve the problem that way (without recovery).

**Comment by bmw** [comment]
I'm glad that you're seeing the same behavior as me and you have a workaround.

Reading through that thread though, Rob Stradling who is the lead developer of Sectigo's ACME service also says that the account private key is needed to recover the account at https://github.com/jetstack/cert-manager/issues/2882#issuecomment-815715850.

**Comment by christian-2** [comment]
That nails it. I am obviously new to ACME/EAB, so that clause had escaped me. Thanks again.
