### ISSUE TITLE
Investigate Apache plugin issues on Big Sur

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#8978]
We have a handful of reports from macOS Big Sur users that the Apache plugin can't find their virtual hosts.

Here are some of the threads:

- https://community.letsencrypt.org/t/certbot-does-not-find-my-virtual-host-in-macos/157363
- https://community.letsencrypt.org/t/renewal-fails-with-unable-to-find-a-virtual-host-listening-on-port-80/151295
- https://community.letsencrypt.org/t/unable-to-find-a-virtual-host/155170
- https://community.letsencrypt.org/t/unable-to-find-vhost-on-port-80/154621
- https://community.letsencrypt.org/t/moved-apache2-and-letsencrypt-directories-and-sites-from-a-mac-intel-to-a-mac-m1-and-certbot-now-issues-the-dreaded-unable-to-find-a-virtual-host-listening-on-port-80/157615

What stands out to me is the `/private/etc/apache2/extra/` path in those threads. I'm not sure how it relates to what we have in our macOS override:

https://github.com/certbot/certbot/blob/3058b6e748d085f53dd5c550be2806b26e7195eb/certbot-apache/certbot_apache/_internal/override_darwin.py#L10-L11

At least one of the threads says they are using Apple-installed Apache, rather than Homebrew or something. What is Certbot's Apache plugin compatible with?

cc @bmw since you are our sole macOS user.

**Comment by bmw** [comment]
I need to look into this more but to document my thoughts so far for myself/others, this doesn't immediately make sense to me. Using the Apple provided Apache installation on Big Sur on my system, if I uncomment the `Include /private/etc/apache2/extra/httpd-vhosts.conf` line from the default `httpd.conf` file, Certbot is able to find those vhosts.

I don't think the use of `/etc` vs. `/private/etc` should matter because at least on my system:
```
$ ls -al /etc 
lrwxr-xr-x 1 root wheel 11 Jan  1  2020 /etc -> private/etc
```

Also, I don't expect the value for `vhost_root` to have much effect. It used to back in the day, but now I believe it is only used for:

1. Searching for extra vhosts that may not be included in the current Apache config.
2. Where to place any vhost files that Certbot creates.

I'll read through all the community forum threads that Alex collected more closely, but I think the biggest thing that'd help me out is getting a copy of the files under `/etc/apache2` from a user having trouble here.

**Comment by bmw** [comment]
At least https://community.letsencrypt.org/t/certbot-does-not-find-my-virtual-host-in-macos/157363 and I suspect all issues are due to https://github.com/hercules-team/augeas/issues/729 which affects Augeas in Homebrew. I just reported the problem to the Homebrew maintainers at https://github.com/Homebrew/homebrew-core/issues/83407.

What happens in Certbot here is the search for virtual hosts here quietly returns no results. You can work around the problem for now using `brew install augeas --head` which I also posted about in the LE forum post.

Alex, I'm unassigning myself, but let me know if you think I/we should do anything else now. I'd personally like to sit tight and hope the Homebrew maintainers just fix their package for us.

**Comment by bmw** [comment]
The issue I described in my last post is fixed in Homebrew with revision 1 of the Augeas 1.12.0 formula. Closing this for now but please reopen or create a new issue if people continue to hit similar problems here.
