### ISSUE TITLE
Multiple (failover) ACME servers

### ISSUE THREAD

**Issue by hvisage** [certbot/certbot#8986]
Although Certbot allows for other ACME servers, and allowing changing the ACME server, I have a use case where I'd prefer to first use a specific ACME server, but then when I hit limits on that server (like a week's spike of new request) or some other connection issues, to then try the next ACME server in the list.

 Would be great if this is possible during both initial and renewal phases

**Comment by bmw** [comment]
To be honest, I'm personally a little hesitant to accept this feature as I suspect it won't be used by many people so I worry the maintenance burden is more trouble than it's worth for our small team here, but I could potentially be convinced otherwise.

Regardless, I don't think we'll have time to implement or review a PR for this feature anytime soon. We can leave this open to track the issue though.

If anyone else is curious, you may also want to look at https://community.letsencrypt.org/t/certbot-and-multiple-fail-over-acme-servers/157665 where there is more discussion about this feature.
