### ISSUE TITLE
Certbot Renew does not use the renewalparams server conf

### ISSUE THREAD

**Issue by danislav** [certbot/certbot#9081]
My domain is: custom internal domain
We have a running internal acme server at `acme02-dev.internal.com`

I ran this command to issue the certificate from the internal acme server:
 `certbot --nginx -d myhost.internal.com --server https://acme02-dev.internal.com/acme/acme/directory`

The certificate is issued and installed properly. So far so good.
I see that there is a conf file:
 `/etc/letsencrypt/renewal/myhost.internal.com.conf`
In the conf file there is a row
 `server = https://acme02-dev.internal.com/acme/acme/directory`
which is how it should be

But when I run:
 `certbot renew --dry-run`
Certbot does not use the custom acme server but tries to renew from letsencrypt instead. Which fails of course.

I have to run `certbot renew --server https://acme02-dev.internal.com/acme/acme/directory` to make it work.
Which means that certbot does not use the server setting in the conf file.

The version of my client is:
certbot 1.20.0

Community link:
https://community.letsencrypt.org/t/renew-does-not-use-the-renewalparams-server-conf/164610

**Comment by alexzorin** [comment]
This is intentional, but I can see how it's confusing.

One of the things `--dry-run`does is to set the server to `https://acme-staging-02.api.letsencrypt.org/directory`, unless further overridden by `--server` (on the CLI or in `/etc/letsencrypt/cli.ini`).

The documentation around `--dry-run` should be improved to clarify how it works. The help text is currently pretty vague ("... obtaining test (invalid) certificates ...").

If all your certificates come from this private ACME server, you could set `server` in `/etc/letsencrypt/cli.ini`, so it is used for both live certificates and dry-runs.

It might also make sense to change the behavior of `--dry-run` to use the Let's Encrypt staging *only if* the `--server` happens to be set to Let's Encrypt. This would be a breaking change and would need to wait until Certbot 2.0.

**Comment by danislav** [comment]
It makes sense now. Thank you so much for the reply.

**Comment by osirisinferi** [comment]
Isn't it an idea to introduce something like `--staging-server`?
