### ISSUE TITLE
CVE-2021-28831

### ISSUE THREAD

**Issue by thomas-schn** [certbot/certbot#9103]
We are using the certbot docker image (certbot/certbot:v1.21.0). 
Our security-scan with trivy shows us CVE-2021-28831 for ssl_client and busybox. The fixed version is not available in alpine 3.12.7 which is actually the base-image for the certbot-image.

![grafik](https://user-images.githubusercontent.com/55287942/142398085-2069ee8f-1266-4c9c-8ccc-d0534ec9b3ca.png)

**Comment by bmw** [comment]
Thanks for reporting this, but I don't believe this vulnerability affects Certbot and since our images are based on `python:3.8-alpine3.12`, I think this will be fixed when we do our December release in a couple weeks.

If I'm missing something, please comment and I'll consider reopening this though.
