### ISSUE TITLE
--dns-route53-propagation-seconds not respected?

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#9121]
We got a report that `--dns-route53-propagation-seconds` is not respected. Quickly looking at the code, this seems like a real problem because that flag is added by the common DNS authenticator class in Certbot and used in the `perform` method which the route53 plugin overrides without calling the parent class.

It looks like the route53 plugin has some additional logic to wait for DNS changes to propagate, but I think we should either respect that flag or deprecate it and remove it from the plugin in the future.

**Comment by bmw** [comment]
This is still valid.

**Comment by jgoldfarb1123** [comment]
I can confirm this is still valid and the default timeout of 10 seconds can cause verification failure in large hosted zones. Is it possible to increase the default timeout from 10 seconds until this issue is resolved?

**Comment by alexzorin** [comment]
>I can confirm this is still valid and the default timeout of 10 seconds can cause verification failure in large hosted zones

As bmw mentioned, the plugin does not use the 10 second sleep, but instead uses the Route53 GetChange API to confirm that each change request has transitioned into the `INSYNC` state (propagated to all Route53 nameservers).

This should be in theory sufficient to guarantee that the ACME server can see the DNS records.

I'm not super keen on reviewing https://github.com/certbot/certbot/pull/9591 unless we have a working theory about why failures are happening. If we want to do this off a single report, I'd like at least to see the Certbot logs showing the plugin doing its job and failing. Thanks!

Otherwise, I'm in favor of deprecating the flag.

**Comment by jeffb4** [comment]
I can say that for @jgoldfarb1123 's issue (coworker) it was unrelated, we had a CAA failure that wasn't showing up in certbot logs. I'm going to close my draft PR as the feature isn't really necessary, but some indication should maybe be given by the route53 provider that it isn't going to respect that setting, in case someone passes it in.
