### ISSUE TITLE
Option to generate on-demand, or always include, options-ssl-*.conf configuration files

### ISSUE THREAD

**Issue by mhitza** [certbot/certbot#9153]
There's already a question related to my feature request on the forum https://community.letsencrypt.org/t/how-to-get-the-options-ssl-conf-files/108550 .

I manage the Apache/nginx configuration through Ansible, thus I would not like certbot to touch configuration files. However I like the idea of defering the SSL security tweaks to what certbot is able to generate/update through it's Apache/nginx plugins when certificates are renewed.

I would be happy if those files would be available under any of the following conditions (or any other options you can think of which doesn't require touching Apache/nginx configuration files):

 * bundled in the plugin packages (thus when I run a package manager update I'm guaranteed to get a copy on disk)
 * always generated when certbot is called with the --apache/--nginx flags, even if an alternative option like --webroot is used
 * a special flag for the plugins to be able to run certbot --apache --dump-ssl-options on demand to dump the contents to stdout/hardcoded path

**Comment by ohemorange** [comment]
You're right, and this would absolutely be nice to have. Unfortunately it's a little tricky to implement on our end, because of how much is generated dynamically, so it's probably unlikely that our small team will be able to address it any time soon.

But all is not lost!

If you're ok with certbot *temporarily* and *reversibly* changing your files, you can:
- run the certbot installer to generate the desired file
- copy the generated ssl-options file to your desired path
- use `certbot rollback` to restore the file to its previous form.

`rollback` is saving a copy of your configuration before our changes, so this will have the overall effect of not making any lasting changes to your system.

Run `certbot help rollback` for more information about using the rollback feature.

Note that this will not get you automatic updates in that way that using our installer would, but rerunning it periodically will pick up updates, as long as certbot is being updated.
