### ISSUE TITLE
acme: setuptools is a test dependency

### ISSUE THREAD

**Issue by 0-wiz-0** [certbot/certbot#9159]
Perhaps I'm missing something, but in acme/setup.py, setuptools is listed as a dependency.
I don't see the code using anything from setuptools after installation.
So I think that setuptools should be a test dependency only.

**Comment by 0-wiz-0** [comment]
This also affects some more setup.py files.

**Comment by ohemorange** [comment]
Thank you for submitting this, you're absolutely right, it's not necessary. But it's also not too large of an issue, since this is a common enough library that most users already have it installed and it's not that large of a dependency. Given this, we have enough higher-priority tasks in our queue that realistically we're unlikely to get to fixing this, so I'm closing the issue. Thanks for reporting though!
