### ISSUE TITLE
Using NAT and changing the port

### ISSUE THREAD

**Issue by spqrforever** [certbot/certbot#9178]
Hello. When using NAT to my server, from which IP addresses is the connection coming from? Is it possible to change the port of certbot from 80 to another? I just don't want to open port 80 for everyone. Do I understand correctly that I should then use WEBROOT ?

**Comment by bmw** [comment]
Since this question is more about how to use Certbot/Let's Encrypt as opposed to a bug or feature request, I'm going to close this and recommend you post to https://community.letsencrypt.org where there is a much larger community familiar with the projects and server administration that can help you.

**Comment by spqrforever** [comment]
> Привет. При использовании NAT на моем сервере, с каких IP-адресов исходит соединение? Можно ли изменить порт certbot с 80 на другой? Я просто не хочу открывать порт 80 для всех. Правильно ли я понимаю, что я должен использовать WEBROOT?

Okay. Thank you.
