### ISSUE TITLE
SSLHonorCipherOrder

### ISSUE THREAD

**Issue by hlieberman** [certbot/certbot#9180]
We received a [feature request](https://bugs.debian.org/1004140) asking for SSLHonorCipherOrder to be enabled in the default SSL configuration [(certbot-apache/certbot_apache/_internal/tls_configs/current-options-ssl-apache.conf#L12)](https://github.com/certbot/certbot/blob/3d5defe28a69f284bc0f7638f7160a59004fe0bf/certbot-apache/certbot_apache/_internal/tls_configs/current-options-ssl-apache.conf#L12).

They state that even not setting the value is preferable, as it allows it to be easily overwritten without worrying about include orders.

**Comment by osirisinferi** [comment]
As far as I know, this is "by design". Certbots Apache plugin uses the "Intermediate" Mozilla SSL Configuration from https://ssl-config.mozilla.org/. You can read the rationale about the configuration options here: https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility_.28recommended.29

The rationale of `SSLHonorCipherOrder off` is:

> The cipher suites are all strong and so we allow the client to choose, as they will know best if they have support for hardware-accelerated AES

**Comment by nirgal** [comment]
Mozilla is known to favor weak ciphers. You can't even change that. No comment.

Anyway, this resulted in web servers offering the possibility to violate the RFC and refuse their weak cipher order, and to Honor their own cipher order.

If you don't have "SSLHonorCipherOrder on" in your apache configuration, [testssl](https://tracker.debian.org/pkg/testssl.sh) (and other tools) will complain your site is weak:
> Has server cipher order?     no (NOT ok)

You must have "SSLHonorCipherOrder On" to work around crazy mozilla policy to prefer weak ciphers on the client side.

I would certainly recommend changing the default in certbot to On.

Now, I had a bunch of web sites where I set "SSLHonorCipherOrder On" manually. But because certbot forces the weak value, it is cleared, and I end up having ssl test "poor strength" warnings.

"SSLHonorCipherOrder off" is the default value. It is wrong to force the default value. It is useless in general cases.
It make the life of sysadmins more difficult if they want to improve security.
This has no reason but to weaken the security.
If you don't want high standard quality in automatically configures web sites, please, at least, don't ruin sysadmin efforts. Just remove that line in that case.

Here's an extract of [Debian default ssl configuration](https://salsa.debian.org/apache-team/apache2/-/blob/master/debian/config-dir/mods-available/ssl.conf#L61), with suggestion to remove the # in the last line:
```
# SSL server cipher order preference:
# Use server priorities for cipher algorithm choice.
# Clients may prefer lower grade encryption.  You should enable this
# option if you want to enforce stronger encryption, and can afford
# the CPU cost, and did not override SSLCipherSuite in a way that puts
# insecure ciphers first.
# Default: Off
#SSLHonorCipherOrder on
```

**Comment by ohemorange** [comment]
Thanks for the discussion. @osirisinferi is correct -- certbot's policy is to use Mozilla's recommendations to set a default balance between security and compatibility. Users who prefer a stronger setup can manually that value manually, and certbot will not overwrite their changes even on update. Given that, I don't think this is the right place to have this discussion. For maximum impact, I'd recommend discussing it with the maintainers of the Mozilla recommendations, who keep far more up to date on TLS configuration and ecosystem news than the certbot developers. Thanks for supporting security on the web!

**Comment by nirgal** [comment]
@ohemorange Mozilla policy is highly frustrating. But this is another topic.

Here's my issue:
I changed SSLHonorCipherOrder in my config (per ssllabs recommandation and per testssl recommendation).
I include https://github.com/certbot/certbot/blob/master/certbot-apache/certbot_apache/_internal/tls_configs/current-options-ssl-apache.conf
As a result, my change is ignored and my settings are reset to "Off" default and bad value.

Please consider my alternative: Don't touch SSLHonorCipherOrder if you prefer default value (Off). Stop overriding admin changes!

This is compliant with Mozilla recommandation (weak ciphers prefered), and you should be happy about it if you want.

Please consider removing the harmful line.

Please consider reopening that bug.

**Comment by ohemorange** [comment]
You can fix this by modifying the line in that file to your preference, or possibly by changing the import order in Apache? I'm less sure about that latter one, might depend on Apache. The first is certainly possible. We include that file for admins who prefer to not manually manage their configurations like you do, and make our decisions based on what is best for the majority of users. We handle the issue of needing more specific configurations by making that file configurable by the user, and by not clearing away your changes to the file.
