### ISSUE TITLE
Does certbot run all renewal hooks for unchanged certificates on purpose?

### ISSUE THREAD

**Issue by zoracon** [certbot/certbot#9189]
### Discussed in https://github.com/certbot/certbot/discussions/9135

<div type='discussions-op-text'>

<sup>Originally posted by **harridu** December 10, 2021</sup>
Hi folks,

even if just a single certificate is renewed, certbot seems to run **all** post scripts defined for any certificate. This is pretty painful. Jenkins and Nexus are restarted, secrets are changed in some Kubernetes clusters, etc. Shouldn't certbot run only the post script for the changed certificate?</div>

**Comment by bmw** [comment]
If you defined your post hook using the `--post-hook` flag, Certbot will only run that hook if it attempts to renew that certificate. Hooks defined in the `renewal-hooks` directory will be run any time any certificate renewal is attempted.

To fix this problem, I'd recommend either:

1. Using `--post-hook` instead of the `renewal-hooks` directory.
2. Using a "deploy hook" instead of a post hook. Deploy hooks are run when a certificate is obtained. You could also set this for a single certificate using `--deploy-hook`, however, deploy hooks also get environment variables which you could use to make certain steps conditional.

```
  --deploy-hook DEPLOY_HOOK
                        Command to be run in a shell once for each
                        successfully issued certificate. For this command, the
                        shell variable $RENEWED_LINEAGE will point to the
                        config live subdirectory (for example,
                        "/etc/letsencrypt/live/example.com") containing the
                        new certificates and keys; the shell variable
                        $RENEWED_DOMAINS will contain a space-delimited list
                        of renewed certificate domains (for example,
                        "example.com www.example.com" (default: None)
```

**Comment by bmw** [comment]
If you need additional help with this, I recommend creating a thread at https://community.letsencrypt.org.
