### ISSUE TITLE
How to install certbot;  no SNAP available, got Git repo cloned

### ISSUE THREAD

**Issue by egberts** [certbot/certbot#9192]
## My operating system is (include version):
Debian 9, 10, 11, and 11.2
CentOS 8
Gentoo
ArchLinux

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):

Was install by certbot-auto.sh

## I ran this command and it produced this output:

Still stuck on Certbot v0.12.0 by offline Debian APT packaging

## Certbot's behavior differed from what I expected because:

Adding additional subdomain requires a 'certbot certonly' instead of 'certbot renew' (at version 0.12).

Am trying to update to the latest certbot using Git repo but there is no install procedure for Debian 11.2 using just the Git repo onto a bare-metal Linux (no Docker, no SNAP).

**Comment by osirisinferi** [comment]
You could try the pip installation method: https://certbot.eff.org/instructions?ws=other&os=pip (change "Other" to your actual webserver if applicable.)

By the way, you mention Gentoo. Gentoo obviously has excellent up to date packages for Certbot: [app-crypt/certbot](https://packages.gentoo.org/packages/app-crypt/certbot). I know the Certbot team doesn't like distribution packages and prefer snap, but Gentoo uses OpenRC by default and snap requires systemd, so that's no option **and** the Gentoo packages are usually very up to date, as is with Certbot. If required, you can also emerge app-crypt/certbot-apache, app-crypt/certbot-nginx and/or app-crypt/certbot-dns-nsone. If you require any of the other official DNS plugins on Gentoo, you could use my [certbot-dns-plugins](https://github.com/osirisinferi/certbot-dns-plugins-overlay) overlay.

**Comment by alexzorin** [comment]
In addition to Osiris' suggestions, Debian 11 ships its own Certbot 1.12 package (https://packages.debian.org/stable/certbot), which might be recent enough for you.

I'm going to close this as I think the question has probably been answered.

**Comment by egberts** [comment]
thanks.  it answers my question.
