### ISSUE TITLE
enum34 python error, certbot will not run on fresh install

### ISSUE THREAD

**Issue by archhorde** [certbot/certbot#9239]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):

Debian 9

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):

Snap

## I ran this command and it produced this output:

I am running python 2.7.13, uninstalled python 3 as I saw that certbot had issues with the newer versions of python 3. Reinstalled certbot from scratch with snap, still getting this output. Enum34 does exist on the server as shown by a pip list command (enum34 version 1.1.10)

 $sudo certbot
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'enum34; python_version < "3"' distribution was not found and is required by cryptography

## Certbot's behavior differed from what I expected because:

Was working a few months ago, then this error came up

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

Not needed, as the base command will not work. Error is the same when running the server.

**Comment by archhorde** [comment]
Forgot to mention, certbot is 1.25.0 rev 1888

**Comment by alexzorin** [comment]
> File "/usr/local/bin/certbot", line 6, in 

This is not the Certbot snap, this is Certbot installed using `pip` globally. Doing so is a bad idea (for Python in general, not just for Certbot) because it conflicts with the Python packages installed via `apt`. 

Two suggestions:

1. Remove `/usr/local/bin/certbot` so that `/snap/bin/certbot` takes precedence in your `PATH`. Also check [step 6 here](https://certbot.eff.org/instructions?ws=other&os=snap) to make sure the snapped version of Certbot is in your `PATH`.
2. If the snap doesn't work for whatever reason, we have instructions for using `pip` safely [here](https://certbot.eff.org/instructions?ws=other&os=pip). Using a Python virtual environment is going to avoid creating those Python package conflicts.

Good luck.

**Comment by archhorde** [comment]
Thank you, deleting /usr/local/bin/certbot was enough to fix it.
