### ISSUE TITLE
Hook to early skip renew ?

### ISSUE THREAD

**Issue by eLvErDe** [certbot/certbot#9246]
Hello Certbot developers,

I think at the moment there is no way to have a renew hook being able to skip renew if some conditions fails.

Here is that I'm trying to do:
Considering a 3 hosts HA cluster with floating IP/DNS address. Each server has its own certificate matching it's DNS and also have one certificate matching DNS name pointing to the floating IP address.
Of course, the only server being able to renew the certificate for the floating address is the one that currently have the address, so I added in the renewal config file a renew_hook calling a script syncing the update certificate and associated to config to peer host.
It's working perfectly fine, and if I try to renew this certificate on non-master server it's failed to verify the challenges and renew fails, renew_hook is not run in that case.

So that's pretty okay except embedded certbot.service run by certbot.timer appears as failed on slave servers, succeeded on master.
The only way I see to avoid this is being able to see something like renew_skip_if hook in renewal config that could run a command to check if the server is being master, otherwise it just skips renewal and keep a success status.

Does it makes sense ? Is this possible at the moment ?

Thanks in advance,

Best regards, Adam.

**Comment by alexzorin** [comment]
Hi,

Thanks for the clear description of your scenario. Your feature request makes sense to me.

The only thing that comes to mind would be to implement this logic externally to Certbot, by creating a shell script that will run immediately before Certbot's renewal unit does:

You can can get systemd to call your script by creating [a systemd override](https://blog.hqcodeshop.fi/archives/444-systemd-setting-overrides.html) and setting a `ExecStartPre` pointing to your script.

The shell script itself would modify the `/etc/letsencrypt/renewal/*.conf` file for the floating domain. If the server is the current master, it should set:
  
    renew_before_expiry = 30 days

Otherwise, the script would "disable" early renewal by setting:
 
    renew_before_expiry = 1 day

The effect of this would be that only the master server will try to renew the certificate in practice. The slaves would only try to renew if the master continually failed to renew the certificate for 29 days.

The master needs to know that it is the master, though.

I hope that helps. The idea to have a "skip-if" hook is intriguing but it's probably not going to be high on our priorities.

**Comment by eLvErDe** [comment]
Hello @alexzorin,

Thanks a lot for the prompt and swift reply. Systemd pre script to delay renewal is a very clever idea that should do it, I'll try to implement that.
Good to see it makes sense and you keep it as a feature request, I understand it's not a priority but took my chance to create a ticket nevertheless because my use case did make sense to me :D

Regards, Adam.
