### ISSUE TITLE
ECDSA-by-default community announcement

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#9263]
We should warn the community of the upcoming switch to ECDSA-by-default soon.

I have started a document at https://docs.google.com/document/d/1C8Hig0zpYPE8Z65U9u8VvktEuk17vKmd4v0DRrrvK4s/edit?usp=sharing with an outline of what we should say, please share edits/comments/suggestions there.

We should also say something in a CHANGELOG entry in a couple of releases time, I guess?

**Comment by bmw** [comment]
Other than the single comment in the Google doc, I think that announcement looks good.

I also liked your suggestion of looking for other 2.0 changes. The way I'd do this is a case insensitive grep for something like "deprecat" to catch "deprecation" and "deprecated". We could also look through all `warning` messages which I think we should probably do to be safe, but I suspect the grep will catch almost everything.

I think we should announce things in the changelog shortly after the community forum post goes out. We could block either on determining the full list of 2.0 changes, but I think ECDSA-by-default is certainly the biggest one and I think it'd be acceptable to make another post/changelog entry with a more complete list of changes later if we wanted.

**Comment by bmw** [comment]
If you'd like, I can do the search for other changes we were planning to make in 2.0.

**Comment by bmw** [comment]
As of the state of `master` on 4/27/22, here’s the other changes we’re planning to make in version 2.0 in addition to the ECDSA-by-default change.

### `acme `API Changes
* `acme.client.Client`, `acme.client.BackwardsCompatibleClientV2`, and `acme.magic_typing` will be removed.

### `certbot` API Changes
* Certbot’s zope based interfaces in `certbot.interfaces` will be removed in favor of the `abc` based interfaces found in the same module.
* The attributes `FileDisplay`, `NoninteractiveDisplay`, `SIDE_FRAME`, `input_with_timeout`, `separate_list_input`, `summarize_domain_list`, `WIDTH`, `HELP`, and `ESC` from `certbot.display.util` will be removed.
* `certbot.crypto_util.init_save_csr`, `certbot.crypto_util.init_save_key`, and `certbot.compat.misc.execute_command` will be removed in favor of `certbot.crypto_util.generate_csr`, `certbot.crypto_util.generate_key`, and `certbot.compat.misc.execute_command_status` respectively.
* `certbot.tests.util.patch_get_utility`, `certbot.tests.util.patch_get_utility_with_stdout`, and `certbot.util.get_strict_version` will be removed.
* Functions in `certbot.tests.util` were previously using the third party `mock` module if it was available for backwards compatibiliy. This behavior will be removed and `unittest.mock` from the standard library will always be used instead.

### `certbot` UI Changes
* Our Apache plugin will no longer support Apache 2.2 which reached its end-of-life in 2018.
* Certbot will no longer accept the arguments `--manual-public-ip-logging-ok`, `—os-packages-only` `--no-self-upgrade`, `--no-bootstrap`, and `--no-permissions-check`. All but the first argument were previously accepted to help support the old certbot-auto script.
* When Certbot was first released, 3rd party plugins names had to have the format `dist_name:plugin_name` instead of just `plugin_name` both on the CLI and in configuration files. Certbot has accepted the shorter `plugin_name` version for a while now and support for the format `dist_name:plugin_name` will be dropped.

**Comment by zoracon** [comment]
For a lot of the granular changes I can throw it all in a comprehensive ADR [here](https://github.com/certbot/certbot/wiki/Architectural-Decision-Records) for in depth reference. For those who want an in-depth look vs. people who immediately want to know if they have to do anything that the community post will cover. I plan to document this change in the ADRs anyway, so just putting it out there as an option.

**Comment by zoracon** [comment]
Resolved with: https://community.letsencrypt.org/t/ecdsa-certificates-by-default-and-other-upcoming-changes-in-certbot-2-0/177013
