### ISSUE TITLE
Fix repeated docker push failure

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#9278]
For a while now, `docker push` for the "arm32v6" architecture has been spuriously timing out. Here's a successful and failed log of the step in Azure that's failing: https://gist.github.com/55652a31fe08ecf0b65bfbe7213e6e33

I think it's noteworthy that when it succeeds, it takes less than 2 minutes, but it times out after an hour. Regardless of the problem, we've been dealing with this recurring problem long enough that I personally think we should fix this.

**Comment by bmw** [comment]
We recently saw this for amd64 too. T is the first time that's happened to my knowledge. Here's the log for that: https://gist.github.com/ffc4d091c0ab5fde39f150988e1b5bc8

**Comment by wgreenberg** [comment]
FWIW, in true heisenbug fashion, since we added the `--debug` flag to `docker push` in April (https://github.com/certbot/certbot/commit/3b6f3450c2), we haven't seen this bug again. if we're feeling brave, we could remove the flag and see if it starts failing again. otherwise, maybe we add a comment that those are load-bearing debug flags that shouldn't be removed?

**Comment by bmw** [comment]
I think we should add a comment to the deploy script referencing this issue and close this for now. The `--debug` flag doesn't seem harmful and things are working for whatever reason now.
