### ISSUE TITLE
Issue with Certbot, Nginx & Crowdsec

### ISSUE THREAD

**Issue by rc042** [certbot/certbot#9347]
## My operating system is (include version):

- Raspbian GNU/Linux 10
- Nginx 1.14.2
- Crowdsec-nginx-bouncer-v1.0.4
- Certbot 1.29.0

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):

Certbot was installed with `pip`.

## I ran this command and it produced this output:

`sudo certbot --nginx -d my.domain.com`

The following error appear:

`Could not parse file: /etc/nginx/conf.d/crowdsec_nginx.conf due to Expected string_end, found 'init'  (at char 152), (line:4, col:1)`

`/etc/nginx/conf.d/crowdsec_nginx.conf` is the default configuration file:

```
lua_package_path '/usr/local/lua/crowdsec/?.lua;;';
lua_shared_dict crowdsec_cache 50m;
lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
init_by_lua_block {                                #  <=== THIS LINE !!!!
        cs = require "crowdsec"
        local ok, err = cs.init("/etc/crowdsec/bouncers/crowdsec-nginx-bouncer.conf", "crowdsec-nginx-bouncer/v1.0.4")
        if ok == nil then
                ngx.log(ngx.ERR, "[Crowdsec] " .. err)
                error()
        end
        ngx.log(ngx.ALERT, "[Crowdsec] Initialisation done")
}

access_by_lua_block {
        local cs = require "crowdsec"
        cs.Allow(ngx.var.remote_addr)
}
```

Certbot works fine if I disable Crodwsec, any help appreciated! I want to keep Crowdsec enable :)

**Comment by ohemorange** [comment]
Yes, the parser doesn't currently handle `*_by_lua` blocks, which is being tracked [here](https://github.com/certbot/certbot/issues/9066). It's a bit of a tricky issue to solve since the parser is a little hairy. If you need a solution in the meantime, you could use the [webroot](https://eff-certbot.readthedocs.io/en/stable/using.html#webroot) method instead, and manually modify your nginx config to serve the certificate. For more help on setting that up, I recommend asking on the [Let's Encrypt community forums](https://community.letsencrypt.org/). Since the underlying issue has already been reported, I'm closing this issue in favor of that one.
