### ISSUE TITLE
"Edit on GitHub" link doesn't lead to the actual page

### ISSUE THREAD

**Issue by dandv** [certbot/certbot#9349]
I wanted to update the instructions at https://certbot-dns-linode.readthedocs.io/en/stable/#credentials so I clicked on the "Edit on GitHub" link. That let to an `rst` file that didn't contain anything resembling the source of that page, and didn't point to where that source might be.

In case I forget until this ticket is solved, the changes would be:
* Instruct the user to only enable the "Domains" scope in Linode
* The "version" line in the `.ini` isn't necessary

Add an example for adding a wildcard certificate:

    certbot certonly --dns-linode --dns-linode-credentials linode.ini -d example.com -d '*.example.com'

**Comment by osirisinferi** [comment]
Note that I don't have much experience with Sphinx, but I'm guessing that's just how Sphinx *can* operate. The `index.rst` is the building block for Sphinx and it tells Sphinx to use the `autodoc` feature using the command `automodule` to include all the documentation from the `certbot_dns_linode` module. So that's why the `index.rst` seems to be so empty.

You can find the *actual* documentation in the modules `__init__.py` file here: https://github.com/certbot/certbot/blob/master/certbot-dns-linode/certbot_dns_linode/__init__.py

**Comment by alexzorin** [comment]
There is more background about Linode scopes here: #8702. I still don't know what the truth of the matter is. Everybody is saying different things and I've never been able to reproduce the issue. But I welcome more reports there.

Regarding the "Edit on GitHub" link, it is unfortunate. Maybe we can leave a comment in each `index.rst` file which explains that the bulk of the documentation is generated from code comments and tells the reader where to look. If anybody wants to make that PR, I'll merge it.
