### ISSUE TITLE
Nginx configurator should preserve whitespace on output

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#938]
When the configurator edits a config file, it normalizes all the whitespace in the file it outputs. This is confusing if you are used to editing your configs by hand, because it changes the visual appearance of the file. When I first ran the configurator, I was convinced that letsencrypt had completely overwritten my nginx.conf.

**Comment by aprescott** [comment]
Having just encountered this, I'm mostly okay with the normalized indentation whitespace, since it neatened up my inconsistent config files. My only real complaint is that blank lines were all removed, which made things harder to read. For instance, groupings like

```ruby
x 1;
y 2;
z 3;

m 10;
n 20;

foo 1000;
bar 2000;
```

were all "ungrouped" since the blank lines were deleted.

**Comment by olabini** [comment]
This is being worked on by @iapazmino

**Comment by olabini** [comment]
The linked PR fixes this issue, so once merged we can close this ticket.

**Comment by pde** [comment]
@sagi is going to take a closer look at pyparsing to figure out whether there's any way to persuade/modify it to do this for us
