### ISSUE TITLE
Windows Installer Not Trusted in Windows 11

### ISSUE THREAD

**Issue by gravidThoughts** [certbot/certbot#9385]
![image](https://user-images.githubusercontent.com/5057342/186784394-7ce2280c-0199-40fa-846a-b661e66d5954.png)

**Comment by bmw** [comment]
Interesting...

Is there anything unusual about your Windows system that you're aware of? I also wonder if anyone else is hitting this.

**Comment by gravidThoughts** [comment]
Brand new Surface 8 Pro. Not anything unusual that comes to mind except maybe default Active Directory group policy? I just set up my first domain controller, but have not done anything custom. Whatever comes out of the box.

**Comment by bmw** [comment]
Unfortunately I don't have easy access to a Windows 11 machine to test this on. I have access to Windows Server machines that don't seem to have this problem, but I'm not sure what the difference would be 🙁 

If this issue is reproducible though, we should get to the bottom of it. If anyone else is hitting this issue, that'd be useful for us to know.

As for poking around Windows to provide more insight into this problem, I'm not really sure where to start looking, but if someone wants to figure that out, do some of that digging, and report back here, that'd be much appreciated.

**Comment by wgreenberg** [comment]
We had some minor issues w/ the Windows installer's cert, but this should be fixed in the 1.30.0 release!
![image](https://user-images.githubusercontent.com/626277/189434294-c536a89d-801a-4b8e-a3fa-62c91358f743.png)

**Comment by bmw** [comment]
Oh awesome!

@gravidThoughts, if you have a chance to test our new installer at https://dl.eff.org/certbot-beta-installer-win_amd64.exe and report back on if you still have issues that'd be much appreciated! I'm going to close this for now, but I can reopen if people are still having trouble.
