### ISSUE TITLE
Certbot on MidnightBSD: documentation add

### ISSUE THREAD

**Issue by laffer1** [certbot/certbot#9396]
## My operating system is (include version):
MidnightBSD 2.2.4

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):

OS package manager named mport

Would it be possible to get MidnightBSD added to the list of operating systems on the eff certbot page? It's been available from mports and in package form for several years now.

Instructions for installation on MidnightBSD via packages

standalone:
mport install py38-certbot

apache:
mport install py38-certbot-apache

nginx:
mport install py38-certbot-nginx

(python 3.8 is default on MidnightBSD currently) 

mport is the package manager and mports is what we call our ports tree.  These are based on FreeBSD ports, so pretty much work the same. 

The MidnightBSD mports repository is at https://github.com/midnightbsd/mports if you want to look at the implementations here. 

We currently offer
py-certbot
py-certbot-apache
py-certbot-dns-google
py-certbot-dns-ovh
py-certbot-dns-route53
py-certbot-nginx

**Comment by osirisinferi** [comment]
> Would it be possible to get MidnightBSD added to the list of operating systems on the eff certbot page?

Wich Certbot page do you mean exactly? Because if it's a page on [certbot.eff.org](https://certbot.eff.org/), it's probably better to open the issue at the [`certbot/website`](https://github.com/certbot/website) repo. In that repo, the entire source for [certbot.eff.org](https://certbot.eff.org/) used to be available, but it has been internalised. However, I believe issues for the [certbot.eff.org](https://certbot.eff.org/) site are better to be opened in the [`certbot/website`](https://github.com/certbot/website) repo.

**Comment by laffer1** [comment]
Thanks. I opened a PR there.
