### ISSUE TITLE
certbot windows not following the installation path

### ISSUE THREAD

**Issue by muxcc** [certbot/certbot#9450]
directory will be created C:\Certbot\

![image](https://user-images.githubusercontent.com/11799987/198998259-70d11a11-40d8-4303-9a9f-46b862ea5d34.png)

installed in C:\Server\Certbot\

![image](https://user-images.githubusercontent.com/11799987/198998592-b42ebafd-e781-4ca8-9c44-ff81b81ce4ee.png)
--
certbot 1.31.0

**Comment by alexzorin** [comment]
Currently, Certbot will always use `C:\Certbot\{,lib,log}` for its `--config-dir`, `--work-dir` and `--logs-dir`, regardless of what your installation directory is.

This probably isn't ideal, we'd have to have a think about whether we'd like to change this, if at all.

At the moment, you'd have to create `C:\Certbot\cli.ini` in order to redirect these directories, with entries like:

    config-dir = C:\Server\Certbot
    ...

**Comment by muxcc** [comment]
Yes thank you! This is what you need. It is enough to specify in cli.ini 
`config-dir = C:\Server\Certbot`
This is quite enough and can not be considered a problem.
