### ISSUE TITLE
Remove misleading prompt that shares alerting email with the EFF.

### ISSUE THREAD

**Issue by davidbstein** [certbot/certbot#9462]
## My operating system is (include version):

Ubuntu 20.04

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):

snap

## I ran this command and it produced this output:

```
sudo certbot --nginx
```

Output in relevant part:

```
Enter email address (used for urgent renewal and security notices)
(Enter "c' to cancel) : [my email]
```

```
Would you be willing, once your first certificate is successfully issued, to
share your email address with the Electronic Frontier Foundation, a founding
partner of the Let's Encrypt project and the non-profit organization that
develops Certbot? We'd like to send you email about our work encrypting the web
EFF news, campaigns, and ways to support digital freedom.
```

## Certbot's behavior differed from what I expected because:

**Observed Behavior**
The email I provided for "urgent renewal and security notices" *pages my team when emailed* is not "my" email. The alerting email was subscribed to an EFF mailing list. This woke me up the first time it went off. 

**Expected Behavior**
I expected the script to ask for my email address since that's what I'd consented to. I did not expect or intend to give ISRG permission to share my paging email with the EFF.

**Comments**
Frankly, I didn't want to sign up for the mailing list. I was answering "yes" in the middle of an incident triggered by an expired cert, was basically doing the human equivalent of `yes Y |`. I imagine this isn't that uncommon a situation among certbot users. 

I trust the ISRG and the EFF wouldn't intentionally build a consent-grabbing dark pattern.

**Comment by alexzorin** [comment]
>was basically doing the human equivalent of yes Y |

Could you please elaborate on what aspect of the prompt you find misleading? 

Would it help to include the email address being shared, in the prompt message?

**Comment by davidbstein** [comment]
My flow:
* `Enter email address (used for urgent renewal and security notices)` **`SRE_PAGER@example.com`**
* `other prompts with paragraph-long messages (Y)/(N)` (yes to all)
* the EFF is now paging me.

Possible solutions:
* Display the email that will be shared with the EFF.
* Confirm the email that will be shared and give the option to switch.
* Replace the interactive dialog with a message encouraging people to run something like `certbot --eff-newsletter-signup` after completing setup.
* Don't include a newsletter signup in a cert signing workflow?

**Comment by davidbstein** [comment]
My flow:
* `Enter email address (used for urgent renewal and security notices)` **`SRE_PAGER@example.com`**
* `other prompts with paragraph-long messages (Y)/(N)` (yes to all)
* the EFF is now paging me.

I can think of a few fixes:
* Display the email that will be shared with the EFF.
* Confirm the email that will be shared and give the option to switch.
* Replace the interactive dialog with a message encouraging people to run something like `certbot --eff-newsletter-signup` after completing setup.
* Don't include a newsletter signup in a cert signing workflow?

**Comment by osirisinferi** [comment]
While I'm sure there's perhaps room for improvement (have the option to enter a separate email address at the EFF prompt), IMO simply answering "yes to all" prompts is the actual problem here, not how Certbot handles this. "Yes to all" is, I believe, *not common* in any way. While I understand not everybody does it, you _should_ _always_ read the prompts.

That said, Certbot has the `--no-eff-email` option which could also be added to `cli.ini` options file (`no-eff-email = True`) which would have prevented the prompt in the first place (and for every Certbot run in the future too). See https://eff-certbot.readthedocs.io/en/stable/using.html#configuration-file for more info about `cli.ini` and https://eff-certbot.readthedocs.io/en/stable/using.html#certbot-command-line-options for all the CLI options which are supported by Certbot (just remove the `--` from a command line option to get a `cli.ini` option).

Personally I'd rather see "No" as the default option for the EFF email question, but that's entirely my personal view of opt-in being better than opt-out for non-critical situations, even in situations where the user is being asked.

**Comment by zoracon** [comment]
Closing for now, but it does not mean we won't consider iterations of this discussion in the future UX decisions around the CLI. While I understand the point, the prompts are not a dark pattern. The options do not intentionally weigh one for the other or exploit user choice. We explicitly inform the user here with full usage and intent of the prompt.
