### ISSUE TITLE
Feature request: Netim.com plugin for DNS-01 challenge

### ISSUE THREAD

**Issue by mehov** [certbot/certbot#9510]
Netim is a large french registrar focusing specifically and primarily on domain names.

According to Google Trends, Netim is out there on par with DNSimple and DNSMadeEasy: https://trends.google.com/trends/explore?q=netim,dnsimple,dnsmadeeasy,luadns,sakuracloud

They do have API, and seemingly it can get the job done: https://support.netim.com/en/docs/api-rest-1-0/domain-names/domain-services/create-dns-zone

Do you think an official plugin for Netim sounds realistic? 

Thank you!

**Comment by alexzorin** [comment]
Hello!

An offiial plugin is not going to be merged but you are welcome to publish one yourself:

>The Certbot team is not currently accepting any new plugins because we want to rethink our approach to the challenge and resolve some issues like [#6464](https://github.com/certbot/certbot/issues/6464), [#6503](https://github.com/certbot/certbot/issues/6503), and [#6504](https://github.com/certbot/certbot/issues/6504) first.
>
>In the meantime, you’re welcome to release it as a third-party plugin. See [certbot-dns-ispconfig](https://github.com/m42e/certbot-dns-ispconfig) for one example of that.

**Comment by m0pam** [comment]
I also need one for netim...

**Comment by osirisinferi** [comment]
@m0pam Your best option is to write a Certbot plugin yourself (and publish it). Or wait until [lego](https://go-acme.github.io/lego/) has [added NetIM support](https://github.com/go-acme/lego/issues/1271) (but that issue is stale for more than 3 years already) and afterwards wait until [certbot-dns-multi](https://github.com/alexzorin/certbot-dns-multi) has been updated to include the `lego` version with NetIM support.

In any case there's no use replying on this issue I'm afraid as the Certbot team still doesn't add new DNS plugins as mentioned before.
