### ISSUE TITLE
Consider whether to add a flag to control whether the CSR contains a Subject CN

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#9543]
Related to #9542 and [this community thread](https://community.letsencrypt.org/t/connection-between-ios-9-support-and-subject-common-name-or-x509v3-subject-alternative-name-critical/191619/31?u=_az), there's an argument for adding a flag to control whether Certbot includes a Subject CN on its CSR.

Currently, Certbot does not do it, which is a best practice, and that [has been the justification in the past](https://github.com/certbot/certbot/issues/6463#issuecomment-435151087).

Let's Encrypt forcibly includes a Subject CN on the certificate, so no compatibility problems crop up in practice. However, they have indicated that they will stop doing so in future.

As pointed out by our users in numerous issues, some other CAs like BuyPass, do respect the CSR's choice of Subject CN, and this has compatibility consequences for TLS clients.

It feels a bit backwards to include a flag for a deprecated behavior this late in the game, but I think we could consider whether doing so will have any future-proofing benefit for our users (like `--preferred-chain` did).

**Comment by bmw** [comment]
Hmm. My memory was that there was a pretty strong push from jsha for us to not set the CN and [while he did make the change](https://github.com/certbot/certbot/pull/4165), I can't find his reasoning anywhere. This was from the BC (before covid) era though so a conversation may have happened offline or I could be misremembering.

I'm not too against a flag like this, but it feels like an extremely obscure option to me that very few people need and even fewer are going to find. Alex, if you'd like to add a flag like this, I'd be happy to review and merge the PR if someone writes one.

I'm a little curious if jsha has strong opinions, the different compatibility problems, what other ACME clients do, and what bad things would happen if we started setting the CN by default again though. We don't have to look into all those things, but I think things like that could influence us to just close this as extremely niche and wontfix or consider making setting the CN the default (maybe with a flag to not set it).

I'm going to mark this as "unplanned" for now, but feel free to bump the priority if you disagree.

**Comment by jsha** [comment]
Huh, looking back at #4165, I'm surprised I changed the behavior (include Subject CN in CSR or not) without mentioning it in the PR. Perhaps I figured the old behavior was accidental / no big deal. Or perhaps at the time we were planning for the server side to condition Subject CN on the contents of the CSR, and wanted to make sure that most clients were not requesting it unnecessarily.

Update on the [community thread](https://community.letsencrypt.org/t/connection-between-ios-9-support-and-subject-common-name-or-x509v3-subject-alternative-name-critical/191619/31?u=_az): at Let's Encrypt we're going back to the old behavior for now (first SAN from CSR promoted to Subject CN instead of alphabetically-first SAN). But we still plan to push towards no-Subject-CN issuance for almost everyone, and eventually for everyone.

My main memory in terms of pushing for no-Subject-CN issuance back in the 2016 era was that I hoped to launch Let's Encrypt with no-Subject-CN, since that was more standards-friendly. But we found a bug in Safari (long since fixed) that made that pretty impractical at the time.

We're still trying to decide how we want to proceed with no-Subject-CN issuance: should it be opt-in for a short period before we make it default? Turn it on in percentages and offer an opt-out? What should the opt-in or opt-out look like? I.e. something in the CSR, or a JSON field in new-order (which would require clients to update, but that's not so bad).

> As pointed out by our users in numerous issues, some other CAs like BuyPass, do respect the CSR's choice of Subject CN, and this has compatibility consequences for TLS clients.

To clarify, does BuyPass use presence / absence of Subject CN in the CSR to decide on presence / absence of Subject CN in the issued certificate? If so that argues in favor of us doing the same thing (at least for a period, followed by gradually requiring no-Subject-CN).

**Comment by alexzorin** [comment]
>To clarify, does BuyPass use presence / absence of Subject CN in the CSR to decide on presence / absence of Subject CN in the issued certificate?

It does, yes:

    $ sudo openssl x509 -in /etc/letsencrypt/live/x1.zorin.au/cert.pem -noout -subject
    subject=

Patching Certbot to include a Subject-CN on the CSR:

    $ sudo openssl x509 -in /etc/letsencrypt/live/x1.zorin.au-cn/cert.pem -noout -subject
    subject= /CN=x1.zorin.au

I think if there is going to be a transitional period with Let's Encrypt before Subject-CN goes bye bye entirely, adding a flag to Certbot will be worthwhile, especially with the user feedback we've been seeing trickling in. Do you have an opinion on what you'd like to see clients do?
