### ISSUE TITLE
docs: generated man pages sticks everything under NAME

### ISSUE THREAD

**Issue by igalic** [certbot/certbot#9560]
## My operating system is (include version):

FreeBSD

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):

i didn't, really, i was just looking for a man page on https://man.freebsd.org when I noticed this

## I ran this command and it produced this output:

apropos certbot

https://man.freebsd.org/cgi/man.cgi?query=certbot&apropos=1&sektion=0&manpath=FreeBSD+13.1-RELEASE+and+Ports&arch=default&format=html

## Certbot's behavior differed from what I expected because:

this should only show the first line, but it has the entire man page. That means that the source must be formated wrong

**Comment by alexzorin** [comment]
Yeah, we should fix this. Everything is going under `.SH NAME` because we are just piping the output of `certbot --help all` into `rst2man`. We're probably not going to go to the effort of writing a structured man page, but possibly we can just shift everything into the "Options" section, instead of "Name".
