### ISSUE TITLE
hook commands wrongly documented to be shell commands

### ISSUE THREAD

**Issue by calestyo** [certbot/certbot#9611]
Hey.

The `--help` text and https://eff-certbot.readthedocs.io/en/stable/using.html#certbot-command-line-options claim that the hook commands would be commands run in a shell:
```
  --pre-hook PRE_HOOK   Command to be run in a shell before obtaining any
                        certificates.
…
  --post-hook POST_HOOK
                        Command to be run in a shell after attempting to
                        obtain/renew certificates.
…
  --deploy-hook DEPLOY_HOOK
                        Command to be run in a shell once for each
                        successfully issued certificate.
…
```

A command run in a shell is however any valid [shell command as defined by POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09) i.e. not just simple commands (and AFAICS even that wouldn't work).

So not only `/path/to/executable` but also e.g. `{ echo foo; /path/to/executable; }`.<br>
The latter does e.g. not seem to work however.

In https://github.com/certbot/certbot/blob/7a6752a68ed77e73c2b29ab20d3ca8927f4fa7b0/certbot/certbot/_internal/hooks.py#L45-L61 however, certbot seems to check whether the "shell command" string starts with a executable, which is however not necessary for shell commands.

It is however indeed started in a shell:
https://github.com/certbot/certbot/blob/7a6752a68ed77e73c2b29ab20d3ca8927f4fa7b0/certbot/certbot/compat/misc.py#L157-L160

Either documentation should be corrected, or better, (all) shell commands be supported.

The above example may not make that much sense, but consider e.g. something like (pseudocode):
```
if isServerRunning; then reloadServer; fi
```
of course that `if` can also be replaced by `[` / `test` and combined with `&&`... but then just think about more complex examples where one might want to use case or so.

Cheers,
Chris.

**Comment by osirisinferi** [comment]
> The latter does e.g. not seem to work however.

Are you sure? Because when I try the following command:

    certbot certonly -a apache --staging --cert-name testcert -d example --deploy-hook 'echo ${RENEWED_DOMAINS} > /tmp/testcert; /bin/ls >> /tmp/testcert'

I did get the variable in the temporary file and the output of the `ls` command too.

So I'm wondering if you perhaps didn't enclose the value to deploy hook in (single) quotes for example?

Anyway, "works for me". 🙂

**Comment by calestyo** [comment]
Well as I said... checks whether there's a executable as the first argument... and in your example there is (`echo` typically exists as a binary, in addition to being shell built in).

Try the same in a subshell like `{ echo … ; }`?

**Comment by osirisinferi** [comment]
I think I understand your issue. With the check in place, such shell commands *not* starting with an executable script are currently indeed not possible.

However, I'm not sure if the Certbot team would want this any other way. Not sure if it's here on Github or on the Let's Encrypt community, but it has often been advised for people just to add all the required shell stuff into a script instead of putting everything on the command line in a hook option.

That said, the documentation does suggest you could put anything into the hook command, so I *personally* agree that could be improved.

**Comment by alexzorin** [comment]
`--disable-hook-validation` will allow something like `--post-hook "{ echo 123; }"` to work.

The issue was raised 7 years ago and there's [a comment from an original/former maintainer](https://github.com/certbot/certbot/issues/3020#issuecomment-220128531) that suggests that the hook validation does do actually something useful, despite its limitation. 

Some potential directions to go:
- Rip out hook validation.
- Clarify the documentation that hooks should refer to executables. This makes it clear that shell builtins are not supported.
- Refer to `--disable-hook-validation` in the error message, so users know that there is an escape hatch.

I'd probably go for the latter.

**Comment by calestyo** [comment]
> Rip out hook validation.

I'd probably have chosen this... I mean the current check doesn't really give much benefit IMO.. except checking that there is an executable. But no guarantee at all, that it does anything useful.

Anyway... if you don't want the former, above's a PR that would improve `--help` and error message.
