### ISSUE TITLE
How to setup certbot and cloudflare using docker-compose?

### ISSUE THREAD

**Issue by MrPhyaeSoneThwim** [certbot/certbot#9613]
Now I want to enroll the wild card certificate of *.example.com from cloudflare using docker-compose file. Can you guys help me how to enroll the certificate and auto renew when it's getting to expire.

**Comment by wgreenberg** [comment]
Here's a guide for the cloudflare + wildcard cert part of your question: https://labzilla.io/blog/cloudflare-certbot

For the docker-compose element, I wouldn't necessarily advise going that route unless you're sure you want to/have to, since installing certbot on a host machine is quite a bit simpler. Check out our certbot + docker docs to learn more: https://eff-certbot.readthedocs.io/en/stable/install.html#alternative-1-docker.

**Comment by slidenerd** [comment]
That linked article honestly is missing a lot of details, where is the cron job? how do you renew those certificates? how do you get the certificate the very first time?

**Comment by wgreenberg** [comment]
The labzilla article covers renewal (via systemd rather than cron, see the "Renewal" section) as well as the first cert request (see the section "Get your Certificates").
