### ISSUE TITLE
Apache plugin does not respect port 80 VirtualHost order

### ISSUE THREAD

**Issue by triatic** [certbot/certbot#9695]
Ubuntu 22.04, latest snap installation. When the certbot Apache plugin is run against a series of VirtualHosts on port 80, it creates a corresponding set of VirtualHosts for port 443. However, the order of the VirtualHosts for port 443 is not the same as that for port 80.

This is significant because in Apache, the first VirtualHost which matches a given port is the VirtualHost which answers any domain name for which the web server has no specific VirtualHost for.

Therefore it is important that the Apache plugin is modified so that the first port 80 VirtualHost is also the first port 443 VirtualHost which certbot creates.

**Comment by alexzorin** [comment]
Hi,

I don't follow the description of the issue, sorry. Could you please create a contrived dummy `httpd.conf` configuration file which demonstrates the problem?

I vaguely get the sense that this has something to do with which virtual host Apache uses as the default non-SNI HTTPS virtual host. If that is the case, I don't think it's likely that this is something we're going to prioritize fixing, sorry.

**Comment by triatic** [comment]
Here's an example on a fresh server with no existing certificate.

A port 80 config with gamma.suti.uk as the primary port 80 domain:

```
ServerName gamma.suti.uk
<VirtualHost *:80>
	ServerName gamma.suti.uk
	DocumentRoot /var/www/html
</VirtualHost>
<VirtualHost *:80>
	ServerName alpha.suti.uk
	DocumentRoot /var/www/html
</VirtualHost>
<VirtualHost *:80>
	ServerName beta.suti.uk
	DocumentRoot /var/www/html
</VirtualHost>
```

The certbot Apache plugin creates a port 443 config but changes the VirtualHost order, making alpha.suti.uk the primary port 443 domain:

```
<IfModule mod_ssl.c>
<VirtualHost *:443>
        ServerName alpha.suti.uk
        DocumentRoot /var/www/html


SSLCertificateFile /etc/letsencrypt/live/alpha.suti.uk/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/alpha.suti.uk/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
<IfModule mod_ssl.c>
<VirtualHost *:443>
        ServerName beta.suti.uk
        DocumentRoot /var/www/html

SSLCertificateFile /etc/letsencrypt/live/alpha.suti.uk/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/alpha.suti.uk/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
<IfModule mod_ssl.c>
<VirtualHost *:443>
        ServerName gamma.suti.uk
        DocumentRoot /var/www/html


SSLCertificateFile /etc/letsencrypt/live/alpha.suti.uk/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/alpha.suti.uk/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>

```

**Comment by alexzorin** [comment]
I see, thanks for confirming.

While testing this, I noticed that Certbot will follow the order that is specified by the user. i.e.

    certbot --apache -d gamma.suti.uk -d alpha.suti.uk -d beta.suti.uk

will give you the behavior you want.

It seems that if you run `certbot --apache`, then the interactive domain list is sorted alphabetically (due to #3892), which in turn affects the order that Certbot installs a certificate to its target domains.

I am satisfied that:

- The default SNI virtual host is not a sufficiently notable issue for us to do anything. (in my opinion, but if more users show up to this issue, we can reconsider). Ideally I'd like to see webservers just reject handshakes that are for an unrecognized server name.
- There is a way for Certbot users to control the order,
- Even if the wrong domain order is applied, it can be manually adjusted by the user afterwards without Certbot reverting that change.

**Comment by triatic** [comment]
Thank you for your reply. Whilst I could specify the domains manually on the command line or edit the port 443 configuration file post execution, I still feel it would be nicer for the Apache plugin to handle this itself.

And for those who aren't aware about this, may I suggest a small notice from the Apache plugin when it executes that the user's port 80 primary domain might not be made the primary domain by certbot for port 443?
