### ISSUE TITLE
Website displays that it's not secured, in spite in installed certificates succesfully

### ISSUE THREAD

**Issue by pasturryx** [certbot/certbot#9752]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Windows 10

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):

I tried installing it with pip python/ and windows cmd
## I ran this command and it produced this output:

Microsoft Windows [Version 10.0.19045.3324]
(c) Microsoft Corporation. All rights reserved.

C:\Windows\system32>certbot-auto -d forgottennot.online -d www.forgottennot.online
'certbot-auto' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\system32>certbot certonly --webroot
Saving debug log to C:\Certbot\log\letsencrypt.log
Please enter the domain name(s) you would like on your certificate (comma and/or
space separated) (Enter 'c' to cancel): forgottennot.online, www.forgottennot.online
Certificate not yet due for renewal

You have an existing certificate that has exactly the same domains or certificate name you requested and isn't close to expiry.
(ref: C:\Certbot\renewal\forgottennot.online.conf)

What would you like to do?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: Keep the existing certificate for now
2: Renew & replace the certificate (may be subject to CA rate limits)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 2
Renewing an existing certificate for forgottennot.online and www.forgottennot.online

Successfully received certificate.
Certificate is saved at: C:\Certbot\live\forgottennot.online\fullchain.pem
Key is saved at:         C:\Certbot\live\forgottennot.online\privkey.pem
This certificate expires on 2023-11-20.
These files will be updated when the certificate renews.
Certbot has set up a scheduled task to automatically renew this certificate in the background.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
If you like Certbot, please consider supporting our work by:
 * Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
 * Donating to EFF:                    https://eff.org/donate-le
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

C:\Windows\system32>
Ceritificated are being installed succesfully there are no errors during the proces

## Certbot's behavior differed from what I expected because:

in spite everything seems to have been installed properly, website still appears as not secured

**Comment by pasturryx** [comment]
know that it might be because of some part or points in my websites are directing to htttp: but this did not happen to me in linux

**Comment by osirisinferi** [comment]
I believe your question is better suited on the [Let's Encrypt Community](https://community.letsencrypt.org/) as mentioned in the first part of the form for this issue.

That being said, please note that Certbot on Windows doesn't have any capabilities to actually install the issued certificate into your webserver: that's a manual process *after* getting a certificate using Certbot.

Also note that forcibly getting more and more certificates using the "Renew & replace the certificate" option does not actually help you, as there was no problem with getting a certificate in the first place.

**Comment by rramondo** [comment]
I noticed a change in the behavior of certificated requested from certbot in the 2.10.0_x builds on my FreeBSD 14.x nodes.
Chrome and Firefox started to alert that my internal sites are no longer protected due to invalid certificate verification. 
* Error code: [SEC_ERROR_UNKNOWN_ISSUER]
* Looking into the differences from prior certs, I noticed there is no longer a Subject identifier in the cert?? weird...

Using an internal site, I deleted the certificate (certbot delete --cert-name xxx)
then recreated: certbot certonly -vvv -d xxx and captured the CSR from the debug logs.
The certificates contained valid SAN domains, but there was no Subject set. 
The internal requests go against an internal step-ca setup for acme issuance.
This same node requests public verification from letsencrypt and the CSR's going external also do not have a Subject set?
But, when I get the cert responses from letsencrypt, the Subject is set to the first of the SAN entries???

I assume their ACME service has a template that notices a blank subject and inserts the first SAN as that Subject: CN=xxx

I can post additional information if you need.

Env: FreeBSD stable/14-a2eaf1cdd amd64
py311-certbot-2.10.0,1         Let's Encrypt client

**Comment by osirisinferi** [comment]
@rramondo I'm sorry, but I don't see how your problem is related to this issue. It also sounds you're probably better off opening a thread [on the Let's Encrypt Community](https://community.letsencrypt.org/c/help/13) as I don't think this is anything related to Certbot: Certbot has not included a CommonName Subject field in the CSR since somewhere between 2017-04-11 and 2017-05-07 (based on my own archive of Certbot CSRs). Unless you recently upgraded from a Certbot 7 years old.

**Comment by zoracon** [comment]
Closing due to our decision to discontinue our Beta distribution of the Windows Installer:
https://github.com/certbot/certbot/wiki/Architectural-Decision-Records#-certbot-discontinuing-windows-support

If you need alternatives. They are listed in this community forum post:
https://community.letsencrypt.org/t/certbot-discontinuing-windows-beta-support-in-2024/208101
