### ISSUE TITLE
`certbot reconfigure` used production API instead of staging API

### ISSUE THREAD

**Issue by avirshup** [certbot/certbot#9847]
**My operating system**: the `python:3.11-alpine` container, w/ Alpine Linux v3.18
**I installed Certbot with**: `pip install certbot==2.7.4 certbot-dns-cloudflare`
**I ran this command** several times, trying to debug my deployment script:
```bash
certbot --run-deploy-hooks reconfigure --cert-name internal.example.tech
```
with the following `cli.ini`:

```ini
preferred-challenges = dns-01
dns-cloudflare = true
dns-cloudflare-propagation-seconds = 30
dns-cloudflare-credentials=[REDACTED]

non-interactive = true
agree-tos = true
```

## Expected behavior
When running `certbot reconfigure`, the certificate would _not_ be renewed, and no certificate transparency logs would be generated.

### CT Logs
Each time `reconfigure` was run, it appears that certificate transparency logs _were_ in fact generated:

<img width="482" alt="crt sh-logs" src="https://github.com/certbot/certbot/assets/9388007/7d22e575-b308-4bb9-983d-73c88d95f426">

### Console output
The first few times I ran this command, the output was:

```text
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Simulating renewal of an existing certificate for internal.example.tech and *.internal.example.tech
Waiting 30 seconds for DNS changes to propagate
Hook 'deploy-hook' reported error code 127
[REDACTED deploy hook error output]

No changes were made to the renewal configuration.
```

But then, I got rate limited by the API:
```text
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Simulating renewal of an existing certificate for internal.example.tech and *.internal.example.tech
An unexpected error occurred:
Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours: *.internal.example.tech,internal.example.tech, retry after 2023-12-03T08:18:03Z: see https://letsencrypt.org/docs/duplicate-certificate-limit/
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
```

### Certbot logs
The logs from one of these runs also seems to show that the staging server _should_ have been used, but the production server was actually used: 

```log
[...]
2023-12-01 15:43:14,248:DEBUG:certbot._internal.main:Arguments: ['--run-deploy-hooks', '--cert-name', 'internal.example.tech']
2023-12-01 15:43:14,248:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#dns-cloudflare,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2023-12-01 15:43:14,267:DEBUG:certbot._internal.log:Root logging level set at 30
2023-12-01 15:43:14,269:DEBUG:certbot.configuration:Var pref_challs=['dns-01'] (set by user).
2023-12-01 15:43:14,270:DEBUG:certbot.configuration:Var dry_run=True (set by user).
2023-12-01 15:43:14,270:DEBUG:certbot.configuration:Var server={'staging', 'dry_run'} (set by user).
2023-12-01 15:43:14,270:DEBUG:certbot.configuration:Var dry_run=True (set by user).
2023-12-01 15:43:14,270:DEBUG:certbot.configuration:Var server={'staging', 'dry_run'} (set by user).
2023-12-01 15:43:14,270:DEBUG:certbot.configuration:Var account={'server'} (set by user).
[...]
2023-12-01 15:43:14,543:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
[...]
```

### Certbot's behavior differed from what I expected because:
1. The output says `Simulating renewal of an existing certificate [...]`, not "renewing certificate".
2. The [documentation](https://eff-certbot.readthedocs.io/en/stable/using.html#certbot-v2-3-0-and-newer) says that staging servers will be used, not actual servers.

## Notes
 - Could this be because of the order of the `--run-deploy-hooks` and `reconfigure` arguments? I did pass the flag before the subcommand for some reason.
 - If the complete (but redacted) logs would be useful, please let me know.

**Comment by osirisinferi** [comment]
I can confirm this issue: when running `certbot reconfigure`, it *says* it will "Simulate" renewal, but actually uses the production API. Even with a test certificate which used the staging environment, Certbot will simply override the staging `server` variable with the production ACME server URL.

**Comment by bmw** [comment]
So while I think we should fix this as without a patch `certbot reconfigure` essentially functions like `certbot certonly`, I don't think it's a huge priority as it appears less than 600 people have used this command with Let's Encrypt in the last 2 months.

Essentially, I think the problem is that https://github.com/certbot/certbot/blob/9d8eb6ccfd513cf2bfd0c0920c9eb006ad536f4f/certbot/certbot/_internal/main.py#L1730-L1732 is insufficient. I think you also need the logic from https://github.com/certbot/certbot/blob/9d8eb6ccfd513cf2bfd0c0920c9eb006ad536f4f/certbot/certbot/_internal/cli/helpful.py#L335-L347

I started to fix that by setting `dry_run` if `reconfigure` is the "verb" during CLI parsing so this second code block runs, but then I think you also need to handle making sure the `server` value (or any other renewal config relevant values that `dry_run` implies) doesn't get changed in the renewal config unless of course the user requested these changes (to, for example, try and change the CA being used on future issuances).

Handling all this cleanly with tests is definitely doable, but due the current structure of the code, it doesn't currently seem trivial to me to fix. I also believe this problem has been around since `certbot reconfigure` was first introduced for what it's worth.

**Comment by ohemorange** [comment]
While I agree that we need great tests here, I actually think the problem shouldn't be quite that bad to solve. The problem with just running the CLI parsing logic during parsing is that then the config has those values the whole time, when really we only want them set as we go to test the new config. So if we:

1. Parse and modify the config as we currently do, without touching `server`
2. Make a deep copy of `lineage_config` (almost certainly necessary)
3. Right before actually getting the cert (between lines 1176 and 1777 below), set `dry_run` and `server` and account-related vars as in `helpful.py` in the copy of `lineage_config`, either by sticking the `helpful` logic in a util somewhere or just copying it
4. Get the cert, confirm it works as is currently done, but when saving it out using `save_new_config_values`, used the cached `lineage_config`

https://github.com/certbot/certbot/blob/9d8eb6ccfd513cf2bfd0c0920c9eb006ad536f4f/certbot/certbot/_internal/main.py#L1775-L1786

The thing to check here is that neither `_init_le_client` nor `_get_and_save_cert` modify `lineage_config`; I...don't *think* they do, but haven't checked all the way down yet. If they do, in a way that we need those changes to be saved, it gets a little more complicated, yeah, but still doable.

The other major assumption is that the logic done during `helpful` can be executed at that point and in that function, but I'm not seeing anything obvious where it wouldn't.

By moving the setting of `dry_run` and its associated values later to just where it's needed, it should be a relatively straightforward fix.

**Comment by bmw** [comment]
I think your plan should work!

> The thing to check here is that neither `_init_le_client` nor `_get_and_save_cert` modify `lineage_config`; I...don't *think* they do, but haven't checked all the way down yet.

This happening or that we might do it in the future scared me. I feel like there's all sorts of logic like option A implies B or ask about options C and D but default to D if noninteractive throughout Certbot, but since this is essentially using the same process as `certbot renew` instead of `certonly` or `run`, maybe it avoids all that.

**Comment by ohemorange** [comment]
I feel that. Certainly certbot is no exemplar of distinguishing between read and write operations. At minimum, maybe we should start documenting when we modify objects given as input, which we do a little but by no means universally. Separating out input collection for required values from acting on those values would also help, but that's the sort of thing that would either be a bugs-inducingly-large refactor or just cleaning it up as we go. Obviously the correct solution is to rewrite the whole thing in a functional language, but...

Anyway, the worst case scenario here should that happen in the future is we fail to update the new value when running `reconfigure`, meaning `reconfigure` can't be used for that scenario, which isn't so bad. Because yeah, it's just abstracting out what we do when we renew in a dry run, after actually doing the updates.

In practice, I think going down that stack and marking where inputs get updated in comments (copied up to their callers) would both help reassure us that we're not changing things, and remind us in the future when we go to do those updates to check on those functions' callers. But again ideally nothing significant *should* be happening in those functions.

Or maybe even explicitly updating function names to indicate when values are modified. This comment inspired by my nemesis when writing the code the first time, when I discovered that `choose_configurator_plugins` BOTH returns the chosen ones AND records it in the config. But yeah, I think the solution is less never rely on functions not changing things, and more make it explicit when they do.
