### ISSUE TITLE
Please prevent old versions of Certbot from appearing in Debian/Ubuntu apt

### ISSUE THREAD

**Issue by paulehoffman** [certbot/certbot#9906]
## My operating system is (include version):
Any recent version of Debian or Ubuntu

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
`apt-get`

## I ran this command and it produced this output:
```
# certbot --version
certbot 1.21.0
```
## Certbot's behavior differed from what I expected because:
It is typical to expect that packages in repositories to be at least reasonably up-to-date. This is what caused me to open ticket #9903.

## What I would like:
For the Certbot maintainers to contact the Debian package maintainers, explain that Certbot is now a snap, the Debian package version is old and buggy, and that you would either like them to remove the package or replace it with a stub that prints out something about "use the snap instead".

**Comment by heini** [comment]
@paulehoffman, I doubt Debian will ship such stupid snap stubs. Debian 12 ships certbot 2.1.0. If you'd like to run this version on an older Debian version, you'd need to ask for a backport in the Debian backports project. Otherwise, you can still install any version you like via the pip installation method, on any Debian version you like.

**Comment by paulehoffman** [comment]
Thanks, I didn't see that they finally updated to 2.x in Debian 12. This is good enough (well, maybe for a few years).
