### ISSUE TITLE
I m getting the same error i have done everything correct but still don;t know whats wrong ?

### ISSUE THREAD

**Issue by pranjalpagaria** [certbot/certbot#9908]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

**Comment by osirisinferi** [comment]
You haven't answered any of the questions. It sounds like it would be best to follow the link to the Community as mentioned in the first paragraph and open a thread there.

As this issue is probably not going anywhere anytime soon and the aforementioned Community can probably help you faster, I'm closing this issue.
