### ISSUE TITLE
need huawei dns

### ISSUE THREAD

**Issue by xiaoyi510** [certbot/certbot#9932]
need huawei dns

https://www.huaweicloud.com/product/dns.html

**Comment by osirisinferi** [comment]
The Certbot team currently does not accept third party DNS plugins into their repository, let alone they'll code one from scratch.

The only ACME client out there capable of using Huawei Cloud DNS, as far as I can tell, is `acme.sh`: https://github.com/acmesh-official/acme.sh/wiki/dnsapi2#dns_huaweicloud.

If you want/need to keep using Certbot (instead of switching to `acme.sh`; note that `acme.sh` defaults to ZeroSSL instead of Let's Encrypt), it shouldn't be too hard to rewrite the `acme.sh` code for Huawei Cloud DNS at https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_huaweicloud.sh to work with Certbot using the [`--manual-auth-hook`](https://eff-certbot.readthedocs.io/en/stable/using.html#pre-and-post-validation-hooks) option (and of course the `--manual-cleanup-hook` to remove the TXT RR after usage).

If you require further assistance, you might be able to get help at the [Let's Encrypt Community](https://community.letsencrypt.org/), although e.g. helping you with adapting the `acme.sh` code for Certbot might be difficult for the volunteers if they don't have access to a Huawei Cloud DNS account.. So please keep that in mind :slightly_smiling_face:
